
(IN-PACKAGE :SP)
(DEFPARAMETER |*NS-RD-covid-2020-04-03-0403-COM-PMC-1801-1900*|
  '("<0.0001" "<0.01" "<0.05" "<1" "<10" "<100,000" "<1000" "<102" "<11" "<12" "<14" "<18" "<19"
    "<1year" "<2" "<20" "<23nt" "<24" "<28°C" "<30" "<4" "<40" "<5" "<500" "<65" "<85%" "<−1.960σ"
    "<−2.576σ" "<−3.291σ" ">1" ">1.5" ">1.960σ" ">10" ">10%" ">100" ">1000" ">14" ">19" ">1975"
    ">2" ">2-fold" ">2.0" ">2.5" ">2.567σ" ">20-fold" ">25%" ">3.291σ" ">35" ">35nt" ">400,000"
    ">5" ">50" ">50%" ">500" ">6" ">75" ">76%" ">8" ">80%" ">86°F" ">95%" ">98%" ">99%" "A&F" "A-1"
    "A-3" "A-C" "A-site" "A103R" "A75" "AAV-293" "AAV1" "AAV2-EGFP" "AAV6" "AAVP" "AAVP‐GFP"
    "AAVP‐HSVtk" "AAVP‐Luc" "ABD28180" "AC_000008" "ADB-GMS-CDC" "AF112189" "AF339484" "AGC-3"
    "AH-HA" "AI-HI" "ALPV_M1" "AMD-3100" "AMPV-4" "ANOVA-type" "AP-Substrate" "APD50" "APD90"
    "APMV-1" "APMV-2" "APMV-3" "APMV-4" "APMV-5" "APMV-7" "AS2TS" "ASEAN-WEN" "ASGPR-1" "ASPGR-1"
    "ATC-3" "ATF6f" "ATF6β" "ATI-like" "AUG→UCG" "AY142960.1" "AY386316" "AY702913" "AY769362.1"
    "AZN-D1" "Abderrahim-Ferkoune" "Ac-ΔP" "Ad-Cre-dependent" "AdHu5" "AdNrf2" "AdV-12" "AdV-2"
    "AdV-3" "AdV-4" "AdV-5" "AdV-6" "AdV-7" "AdV-7-positive" "Adeno-associated" "Adv-12" "Adv-41"
    "Ag" "Ag-ELISA" "Ag-capture" "Aichi" "Al-Quds" "Al-Taif" "Alexa" "AlexaFluor‐conjugated"
    "Analytical-grade" "Anhui" "Ao-Ai=1+Kd" "Apr-Dec" "April–June" "Asia-Pacific" "Astra-Zeneca"
    "At-risk" "AtIRE1-2" "AtbZIP60" "Aux" "Axioma" "Axl‑expression" "Axl‑negative" "Axopatch-200B"
    "A–C" "A–D" "A→G" "B1-13" "B1-20" "B20-30" "B4" "B4a1" "B6lpr" "B8" "BAB" "BAL-MNC" "BALB"
    "BCF03" "BH-2" "BHQ1" "BIO-RAD" "BM2" "BO1" "BO4" "BP≥140" "BSA+0.1%" "BSL-3" "BSL-4" "BSL3"
    "BSL4" "BSR-T7" "BVDV-Npro" "BX51" "BZ-9000" "BafA1" "Bahey-El-Din" "Balb" "Bangkok"
    "Becton-Dickinson" "Bermúdez-Humarán" "Bio-Gel" "Bio-Meditech" "Bio-One" "Bio-Products"
    "Bio-Rad" "Bio-Tek" "Bio-tech" "Biologically-derived" "BlaM-Vpr" "Bondelum" "Borate"
    "Braun‐Falco" "BstN1" "C-C" "C-HMW" "C-X-C" "C-terminally" "C.I" "C.K." "C14a" "C3" "C33E10"
    "C34-biotin" "C50B12)" "C5b-9" "CARV-RTID" "CARYYA-stimulated" "CB-DOTS" "CC-2011" "CCF2"
    "CCF2-AM" "CCL-1" "CCL-185" "CCL-44" "CCL-81" "CCL-94" "CCL3-5" "CCR-81" "CCR5-antagonists"
    "CC_CUU_UUU" "CD138high" "CD172" "CD3-cychrome" "CD40L-dependent" "CD40L-mediated" "CD40high"
    "CD40low" "CD44hi" "CD44hiCD62Llo" "CD44loCD62Lhi" "CD45R-PE" "CD45Rlow" "CD45hi" "CD45int"
    "CD45lo" "CD4CD44hiCD62Llo" "CD4CD44loCD62Lhi" "CD62LhighCD43low" "CD62LlowCD43high"
    "CD62LlowCD43low" "CDV-F" "CDV-H" "CFX96" "CG-3" "CG10" "CGB10" "CH2Cl2" "CH3OH" "CIEBOV-GP"
    "CKX41" "CN2-29" "CPI−-infected" "CPR39" "CRL-11663" "CRL-1573" "CRL-1746" "CRL-2787" "CS5"
    "CTLA4-mouse" "CV777" "CXCL15" "CXCL9-11" "CXR4" "CY041531" "C_CCY" "Ca+2" "CaCl2"
    "Calmette-Guérin" "Cerbios-Pharma" "Cesarean-derived" "Chediak-Higashi" "ChiCTR-TRC-12002296"
    "Clean-Up" "Cochrane-Armitage" "Coronavirus-COC43" "Cosmos-600" "CpG-A" "CpG-B"
    "CpG-B-adjuvanted" "CpG-B." "Crandell-feline" "Cre" "Crimean-Congo" "Cross-reactivity"
    "Cross-sections" "Cs2CO3" "Ct-value" "Cullin1" "Cys119-Cys205" "Cys126-Cys196" "Cys131-Cys157"
    "Cys218-Cys247" "Cys296-Cys331" "Cys378-Cys445" "Cys385-Cys418" "Cys54-Cys74" "Cytofix"
    "Cytoperm" "Cα" "Cγ" "D.D." "D.Igs" "D1R" "D2" "D3" "DB3.1" "DC500" "DC‑SIGN" "DC‑SIGNR"
    "DEAE-Dextran" "DEAE-dextran" "DH5α" "DIQPR↓F" "DK001" "DK004" "DM-10" "DMEM-5%" "DMI6000B"
    "DNAs" "DQ447659" "DQ915164" "DRSC07426" "DRSC16678" "DRSC16795" "DRiP-independent" "DXM1200F"
    "Dcp1a" "De-Wen" "Dead" "Dessau-Thornau" "Dinesh-Kumar" "Director-General" "Dog94SE"
    "Dose-dependently" "Dose-response" "E-XMP" "E-value" "E.coli" "E1" "E1-like" "E2-Fc" "E2-like"
    "E2-similarity" "E2340-Fc" "E2GBV-C" "E492" "E5" "EBOV-like" "EC100" "EC50" "ECL-Plus" "EEC"
    "EF206716.1" "EID50" "EIF2AK3_1" "EIF2AK3_10" "EIF2AK3_5" "EIF2AK3_6" "EL-4" "EL-4CN2"
    "EL-4NS2" "ELISA-Reader" "EN_GIP_20120810CumulativeNumberH5N1cases" "EPI-INFO" "ER-Tracker"
    "ERN1_17" "ERN1_18" "ERN1_5" "ERN1_6" "EU015061" "EU015062" "EU015063" "EU033966" "EU074218"
    "EU500827.1" "EX-swab" "EZview™-red" "Eckardt-Michel" "EcoRI-BamHI" "EcoRI-firefly" "Eg9" "EgE"
    "Eight-week-old" "EndoH" "Engelbreth-Holm-Swarm" "English-language" "Enter-ne" "Epstein-Barr"
    "Et3SiH" "Express-96" "F-12" "F-distribution" "F0" "F1" "F103" "F12" "F2-F1" "F425B4e8"
    "FACS-based" "FAK56D." "FBG-like" "FFU" "FH900" "FL-l" "FLAG-HIS" "FLAG-tag" "FMDV" "FSC-SSC"
    "Fab" "Fab-specific" "Fc" "Fc-gp120" "Fc-gp120JRCSF" "FcαR" "Fcγ" "FcγIII" "FcγRII" "Fd-His"
    "FeCl3" "FeLV-A" "February-November" "Ficoll-Hypaque" "Ficoll-PaqueTM" "First-Strand"
    "Flat-bottom" "Flour488" "FluA" "Fold-change" "Folin-Ciocalteau" "Forty-eight" "Francois-Loic"
    "Friedrich-Loeffler-Institut" "G+C" "G-V" "G-tetrad" "G0" "G1" "G5P" "GAA_AAA_A" "GB12" "GBV-A"
    "GBV-B" "GBV-C" "GBV-D." "GCCACCATGGTGAGCAAG-3" "GCN4pII" "GETV_LEIV_17741_MPR" "GETV_M1"
    "GF-3" "GF-4" "GF-5" "GF-6" "GF-8" "GF254" "GFP-E" "GFP-E-expressing" "GFP-N-expressing"
    "GFP-TGB2" "GFP-fusions" "GFP-transfer" "GFP2" "GFP2-M9core" "GFP2-cNLS" "GP*Lab-ILI" "GP-7A"
    "GP-8A" "GP-LAPSN" "GP0" "GP1-GP2" "GPI-anchored-protein-enriched" "GRO-α" "GRQGR↓L" "GS10-2"
    "GST-WAFYVR" "GST-fusion" "GTR+I+G" "GUU_CGG_C" "GUU_stop_C" "G_GGC_CCY" "Gag-YFP-expressing"
    "Gal-On" "Garcia-Contreras" "García-Marcos" "Gcc" "GenBank" "Gene-spin"
    "Georg-August-University" "Glasgow-1" "GlobPlot2.3" "Global_Gateway" "Grau-Roma" "Greven"
    "Griess-Assay" "Guangdong" "Guizhou" "H&E" "H-2Db-restricted" "H1N1-SARI" "H1N1-coinfected"
    "H1N1-positive" "H1N2" "H2N2" "H2O" "H2SO4" "H5" "H5-bearing" "H6N1" "H7422P-40" "H7N2" "H7N3"
    "H7N7" "H9N2" "HA-112–263" "HA-13–158" "HA-13–218" "HA-13–263" "HA-13–263-Fc" "HA-13–263-Fd"
    "HA-13–263-Fd-His" "HA-13–263-Fdc" "HA-13–263-His" "HA-13–90" "HA-38–263" "HA0" "HA1-Fdc"
    "HA1-based" "HAB2" "HAU" "HB0215-3" "HB0234" "HB2151" "HBoV1" "HBoV1-4" "HCE-K294A-HA"
    "HCE-T1–219" "HCE-WT-HA" "HE649912" "HE649912–HE649914" "HE649913" "HIV-1+1" "HIV-1-based"
    "HIV-1-inhibitory" "HIV-192UG024" "HIV-1AD8" "HIV-1ADA" "HIV-1BCF03" "HIV-1BaL" "HIV-1HXBc2"
    "HIV-1IIIB" "HIV-1JR-FL" "HIV-1LAV" "HIV-1NL4-3" "HIV-1RW009" "HK483" "HKU-1" "HL-60"
    "HLA-DRhigh" "HM-CCR5" "HMPV-A" "HMPV-B" "HPIV-2" "HPIVs-positive-patients" "HQ460" "HQ530"
    "HRP-anti-human" "HRP-anti-mouse" "HRSV-A" "HRSV-B" "HRV-A" "HRV-B" "HRV-B-positive" "HRV-C"
    "HRV-C." "HSV-1" "HSV-1-based" "HSV-2" "HTA-125" "HTB-37" "HTB-55" "HTX" "Hai-jie" "Han"
    "Heavy" "Heilongjiang-SYXK-2006-032" "Hemmings-Mieszczak" "Henan" "Hep-2" "Hep2"
    "Hermansky-Pudlak" "High-Fidelity" "High-resolution" "High-risk" "HindIII" "His-GP1" "His-sGP"
    "His-x-Cys-x-Ser" "His6-fusion" "Hitachi-8100" "Hoechst33342" "Hong-Juan" "Houck-Loomis" "Huh7"
    "Hung-Jen" "HxCxS" "Hz" "I-Chueh" "I-EcoRV-NheI-Renilla" "I-like" "I106"
    "I=n∑i=1n∑j=1nwijzizjS0∑i=1nzi2" "IACUC-YB-R-2009-15" "IB-HI" "IC50>2" "ICAM-3-Fc" "ICD-10"
    "ICP6" "ICPC-2" "IDT2889" "IDT5959" "IFETP-Thailand" "IFIT1-induced" "IFIT1-knockdown"
    "IFIT1-mediated" "IFITM1>IFITM2>IFITM3" "IFN-induced" "IFN-γin" "IFNα-2b" "IFNω" "IGKV1"
    "IGKV2" "IGKV3" "IGKV7" "IGR-IRES" "IGVH4" "IGVH5" "IL-2-stimulated" "IL-β" "IL12α" "IM-Q"
    "IMGT" "INF-A" "INF-B" "IQPR↓F" "IRE1-bZIP60" "IRE1p" "IRE1β" "IREα" "ISG-15" "ISG-like"
    "IT-001-002MNp" "IT-19" "IU" "IX71" "Ibaraki" "IgA-like" "IgA2" "IgA2-like" "IgG-ELISA"
    "IgG-ELISAs" "IgG-FITC" "IgG2b" "IgLλ" "Igκ" "Igλ" "IgλC" "IgλV" "Immobilised-Peptide"
    "Immobilon-P" "In-Situ" "Influenza-A" "Influenza-B" "Inno-lia" "Interferon-λ1" "International"
    "Internet-based" "Intra-articular" "Intra-herd" "Iα" "J.3.3" "J.D." "J02459" "J12.1" "J12.9"
    "J18.0" "J18.9" "J21.0" "J21.8" "J21.9" "JAZ3" "JAZ5" "JC53" "JF690260" "JN812975" "JQ410000"
    "JSU-hFc" "JX853179" "JX853180" "JX853181" "JX982976–JX982978" "July-September" "J–K" "K2CO3"
    "K2SO4" "KH2PO4" "KHMC-IACUC12-006" "KIOM-198" "KNCQ1" "KO7" "KPEDV-9" "KPR9" "KRKKR↓F"
    "KRQKR↓F" "Kaplan-Meier" "Kd<10" "Knock-down" "Koreans" "Kraft-Bruhe" "Krijnse-Locker"
    "Kruskal-Wallis" "Kruskal–Wallis" "Kv7" "L." "L103" "L3T4" "LALIGN_form" "LC-ESI" "LC-MS"
    "LC16m8" "LC3-I." "LC3I" "LC3II" "LD50" "LH2SN" "LSM510" "LSM710" "LT-B" "Large-scale"
    "Leborgne-Castel" "Leon-Rot" "Leu3a" "Light" "Likelihood-based" "Lion94SNP" "Liposome-Based"
    "Liposome-encapsulation" "Live" "Lns-FF" "Log-rank" "Log10TCID50" "Loop36ox" "Loop36o×"
    "Loop36s" "Loss-of-function" "Lot" "Lsk-FF" "Luria-Bertani" "Ly6C" "Ly6Chi" "M-phase" "M.D.-R."
    "M.F.I." "M106" "M13–M17" "M2-1" "M2-2" "M5" "M9–M12" "MA-ZEBOV" "MARV-GP-bearing" "MAbCPR39"
    "MAbEg9" "MDG4" "MFN116" "MHC-I" "MHC-like" "MHV-1" "MHV-68" "MHV-A59" "MIP1α" "MM2021"
    "MMLV-RT" "MSA-to-consensus" "Ma-ZEBOV" "Mac-3" "Madin-Darby" "Maedi-Visna" "MagMax-96"
    "Mann-Whitney" "May-September" "Melt-curve" "Methyl-β-cyclodextrin" "Met–tRNA" "Met–tRNAi"
    "Mg+2-free" "Mip2γ" "MluI-NotI" "Mock-inoculated" "Modeller6.2" "Montanide" "Munthe-Fog" "MyD8"
    "Myc-RevM10" "MβCD" "Mφ" "Mφs" "N-acetyl-D-glucosamine" "N-cyclohexyl-3-aminopropanesulfonic"
    "N-methyl-D-aspartate" "N.A." "N.J." "N0" "N1" "N158D" "N1–N19" "N2" "N224K" "N35s" "N5N1"
    "N7-methyl-capped" "N7-methylguanosine" "NA" "NAMRU-3" "NATRVP-2" "NATRVP2" "NC_001560.1"
    "NC_001906" "NC_003045" "NC_003045.1" "NC_006432.1" "ND-HI" "ND-IB-AI" "NEDI-USA" "NF-κb"
    "NF-κβ" "NIH-Swiss" "NL-63" "NL4-3" "NLS-3xFLAG-6xHIS" "NLS-3xV5" "NLS-3xc-myc" "NLS-FLAG-HIS"
    "NP-antigen" "NPC-1" "NPC1-usage" "NPQTR↓F" "NPS@" "NS3-4A" "Na2ATP" "Na2CO3" "Na2PO4" "Na2SO4"
    "Nano-KAg" "Naturally-infected" "Near-cognate" "Negative-staining" "Neu5Acα2-3Gal"
    "Neu5Acα2-3Gal-containing" "Neu5Acα2-6Gal" "Nhe-Eco47" "Ni-NTA" "Ni2+-agarose" "Nick-End"
    "Ninety-nine" "Ninety-six" "Ninety-six-well" "NoLS" "Nullbasic" "Nullbasic-FLAG"
    "Nullbasic-induced" "Nullbasic-mCherry" "Nullbasic-mediated" "Nunc-Immuno"
    "N‐Acetyl‐Leu‐Leu‐Norleu‐al" "O.A." "O.D" "O127" "O2" "OD450" "OD600" "OD>" "OD>0.6"
    "ORF1-frame" "ORF4a" "October-December" "Oil-red-O" "On-site" "One-Step" "One-Way"
    "One-day-old" "One-way" "Ortega-Hernandez" "OsbZIP50" "P.R." "P3-0083" "P3N–PIPO" "P4-7"
    "P4-7s" "P4-P1R" "P6-2" "P6-2s" "P<0.02" "P<0.03" "P<0.05" "P=0.99" "PAFr-ligand" "PAR-F2"
    "PAR-R" "PASR↓F" "PAbC4" "PAbCGB10" "PBCV-1" "PBS+Tween" "PBS-T" "PBS-T." "PBS-buffer"
    "PBST+2%BSA" "PCV1" "PCV2" "PCV2-PRRSV" "PCV2-PRRSVgroup" "PCV2-free" "PCV2a" "PCV2b" "PE-Cy5"
    "PE_PGRS33" "PG16" "PHA-P" "PI3P" "PIV-1" "PIV-2" "PIV-3" "PIV1" "PIV1-3" "PIV2" "PIV3" "PIV5"
    "PJ69-4a" "PKR-like" "PKR∼P" "PM-1" "PMR=p1" "PMV-PCR" "PMWS-affected" "PP1α-96A" "PRRS-MLV"
    "PSI-BLAST→CD-HIT→MUSCLE" "PSSR↓F" "Parainfluenza-1" "Parainfluenza-3" "Parainfluenza-4" "Pd"
    "PeIF2α" "Pearson-χ2" "Penicillin" "Per-protocol" "Perez-Pepe" "Perkin-Elmer" "Phage" "PhiX174"
    "Pichla-Gollon" "Pictet–Spengler" "Piperacillin" "Plan-Apochromat" "Plan-Neofluor"
    "Plaque-forming" "Platinum-Taq" "Pm-infected" "Pm-mono" "Post-Reaction" "Post-exposure"
    "Post-infection" "Post-termination" "Pro–tRNA" "Pseudovirus-antiserum" "PstS-1" "PtO2"
    "PtO2·H2O" "Puerto" "P≤0.01" "P≤0.05" "Q1<Q2<Q4" "Q226L" "Quil" "R&D" "R-L3" "R-configuration"
    "R1" "R2" "R2-gated" "R3" "R3-gated" "R4" "R4-6A2" "R4-gated" "R5" "R5-tropic" "R539W" "R6CN2"
    "R6CN2HCV" "R6CN2HCV-MxCre" "R6CN5HCV" "R6CN5HCV-MxCre" "RC-10" "REBOV-NP" "RES-MOR-HEN-F2"
    "RES-MOR-HEN-R" "RESTV" "RF483" "RGD" "RGD4C" "RLM-RACE" "RMH-PCR" "RMP1-30" "RNAi-based"
    "RNAs" "RPA-T4" "RPMI-1640" "RPMI-C" "RPMI-C." "RPMI1640" "RPQGR↓F" "RPRGR↓L" "RRQKR↓F" "RSV-A"
    "RSV-B" "RT-qRT-PCR" "RTD-PCR" "RTI40" "RTII70" "RTase+GTase" "RUBV-1" "RUBV-2" "RUBV-G1"
    "RUBV-G2" "RVA" "Rank-Sum" "Rate4site" "Rcontrol-Rbuffer" "Re-infections" "Redcliff-Caboolture"
    "Reed-Muench" "RelAΔ" "Renilla" "Respi-Finder-19" "RespiFinder-19" "RespiFinder-SMART"
    "RespiFinder-SMART-22" "RespiFinder19" "RespiFinderSMART-22" "Respondent-driven"
    "Rhine-Westphalia" "Rico" "Roferon-A" "Roissy-Charles" "Romano–Ward" "Rota-gene" "Rotor-Gene"
    "Rovere-Querini" "Rtest-Rcontrol" "Ryan-Poirier" "RzCN5-15" "R↓" "R↓F" "R↓L" "S-OIV"
    "S-configuration" "S.A" "S0" "S0=∑i=1n∑j=1nwij" "S1" "S1A–B" "S1C" "S2-S3" "S2A" "S2A-C" "S2B"
    "S2C" "S2D" "S2–S3" "S3" "S3C" "S3D" "S4" "S4A" "S4B" "S4C" "S4D" "S5" "S510" "S5A" "SA14-14-2"
    "SAα2,3" "SAα2,6" "SAα2,6," "SBVp32" "SBVΔNSs" "SCR7" "SD-Ura-Trp-Leu" "SDF-1α"
    "SDF-1α-chimeric" "SDOW17" "SDS-polyacrylamide" "SDS-sample" "SEAMEO-Tropmed" "SH05-15–17"
    "SJ-2176" "SKIM-PBS-T" "SKIM-PBS-T." "SMART-22" "SMI-31" "SMI-32" "SNPs" "SSL7" "ST-cells"
    "SU-human" "SV5" "SV5-NP-a" "SV5-P-e" "SVBp32" "SZ" "S_KOREA" "SacI-L" "Salm-Gene" "Salm-gene"
    "Salvador-Morales" "Sanofi-Pasteur" "Sapphire" "Sch-DTM" "Sch-FRI-adj" "Sch-LCC"
    "Schmidt-Puchta" "Self-reported" "Semliki" "Shapiro-Wilk" "Sigma-Aldrich" "Single-cell"
    "Single-segment" "Smaug1" "Somatic-cell" "South-East" "Spectra-Physics" "Stop–carry"
    "Sub-Region" "Sub-Saharan" "Sub-cohort" "Sub-diffraction"
    "Susceptible-Exposed-Infectious-Recovered" "Sv" "SwH1N1" "SwIV-infection" "SwIV-inoculum"
    "SwIV-particles" "SwIV-titers" "Swine" "System" "S–S" "T-cell" "T-helper" "T.V." "T1L" "T1L."
    "T318I" "T3A" "T3Dc" "T7e" "TAK-779" "TAK1" "TBLN-MNC" "TBS-T" "TCID50" "TCM-2010-03"
    "TCTCCAGATTCCAGATGTCAGGG-3" "TCTCGCTCCTGGAAGATGG-3" "TE-2000" "TE2000‐S" "TF-104" "TGB1-TagRFP"
    "TGB3-GFP" "TGBp3" "TGBp3-elicited" "TGBp3-triggered" "TGC-3" "TI+0%" "TI+10%" "TI+15%"
    "TI+20%" "TI+5%" "TI-like" "TIB-202" "TII+0%" "TII+10%" "TII+15%" "TII+20%" "TII+5%" "TI∶TII"
    "TLR-agonists" "TNF-β" "TPL-N" "TRIM-25" "TS-jPCR" "TSV01" "TURBS-like" "TWxS" "TZM-bl-based"
    "Taq-enzym" "Teacher-led" "Th17" "Thirty-six" "Thr-Trp-x-Ser" "Three-segment" "Three-week-old"
    "Ti" "Tl2SO4" "Tn5" "Todd-Corlett" "Todd-Hewitt" "Toll" "Toluidine" "Trans-Activation"
    "Trans-Blot" "Trim5α" "Tris" "Tris-Cl" "Tris-HCl" "Tris-glycine" "Tris–HCl" "Triton-100"
    "Triton-X100" "TritonX-100" "Trujillo-Alonso" "Trypsin-EDTA" "Tumor-node-metastasis" "Tween-20"
    "Twenty-five" "Twenty-four" "Twenty-seven" "Twenty-three" "Two-week" "Two-week-old" "Ty21a"
    "U-bodies" "U-bottom" "U18666A" "U23187.1" "U53" "U6" "U758-ENS" "U95551" "U9B" "U9D"
    "UAG_CAR_YYA" "UL12" "UL2" "UL50" "US$2,240" "US$5.77" "US‐FDA" "UTR-GFP-FLAG" "UTR-L"
    "UTR-SacI-GFP-FLAG" "UV-RNA" "Ultra-4" "Uni-Form" "United-Kingdom" "V-QUEST" "V-V" "V1" "V1-V5"
    "V2" "V3" "V3-loop" "V3.2" "V3B" "V3C" "V4" "V5" "VH4" "VH5" "VH6" "VLK2" "VLκ" "VLλ" "VP2"
    "VP30" "VP4-VP2" "VP6" "VP9" "VPQSR↓F" "VR-1492" "VR2332" "VRC01" "VSV-G" "VSV-RESTV-GP1"
    "VSV-based" "Vera-Otarola" "Verchot-Lubicz" "Version3.0A" "Virus-Discovery-cDNA" "Vpr-BlaM"
    "WB" "WHO" "WK1" "WK2" "Well‐plate" "White–Duroc" "Wild-caught" "Winston-Salem"
    "Wiskott-Aldrich" "X-100" "X-bodies" "X-body" "X06980" "X4" "X4-tropic" "X4env" "XBP1u"
    "XL-1500" "XL-TOPO" "XMG1.2" "XXX_YYY" "XXY_YYZ" "X_XXY_YYZ" "Xin-Gang" "X‐100" "Y.X." "Y1"
    "Y2" "Y2H" "Y2H." "Y3H" "YF-17D" "YM-10" "YN0540" "YN0542" "YN08" "Yamagata" "Yan-Ming"
    "Yong-Jun" "Z1" "Z13e1" "ZB4" "ZEBOV-Fko" "ZEBOV-GP" "ZEBOV-GP-mediated" "ZEBOV-GPΔTM" "ZH5-04"
    "ZIM-domain" "Z‐Leu‐Leu‐Leu‐al" "ab68129" "above-mentioned" "acid-anthrone" "acid-based"
    "acid–Schiff" "actin-based" "acute-phase" "acute-respiratory-infection" "ad-hoc" "add-on"
    "adeno" "adeno-associated" "adhesion-molecule-like" "adult-only" "advice-Improved"
    "aerosol-initiated" "affec-ted" "age-category" "age-specific" "air-liquid"
    "alkaline-phosphatase" "allophycocyanin-conjugated" "alpha-MEM" "alpha-blockers"
    "alpha-interferon" "alternate-day" "amino-acid" "amino-terminal" "amino-terminus" "amos"
    "animal-friendly" "ante-mortem" "antibody-AP" "antigen-1" "antigen-4" "antigen-capture"
    "antigen-serum" "antigenemia" "anti‐M13" "anti‐cancer" "anti‐mouse" "anti‐rabbit" "array-based"
    "as-yet-unidentified" "at-risk" "at160" "attB1" "attB2R-attB3" "attB4" "attL4" "attR1"
    "avian-like" "bZIP17" "bZIP28" "bZIP60" "bacterial-delivered" "base-pairing" "batch-to-batch"
    "baybio" "bcv1" "bed-days" "bed-side" "best-in-class" "best-studied" "beta-blockers"
    "better-quality" "between-season" "bio-rad" "biodefense-related" "bioinformatics-based"
    "biologically-derived" "births" "black-footed" "blasticidin-S-hydrochloride" "blue‐exclusion"
    "bottom-up" "brain-heart" "broad-spectrum" "bromo-phenol" "bronchio-alveolar"
    "broncho-alveolar" "burn-in" "bwmorph-shrink" "by12%" "c.p.m.of" "c01-c04" "c05-c08" "c09-c12"
    "c13194g" "c15639g" "c2149g" "cDNA-RAPD" "calcein-AM" "calves" "cancer-stimulatory"
    "capacity-building" "capped-nature" "carboxy-tail" "carboxy-terminal" "carboxyl-terminal"
    "carmovirus-like" "case-case" "case-control" "case-fatality" "cases" "case‑fatality"
    "cat#07-685" "cat#200-401-438" "cat#2118" "cat#7074" "cat#7076" "cat#8443" "cat#9176"
    "cat#A11008" "cat#A22283" "cat#D1306" "cat#P36935" "cat#PAB17107" "cat#T8154-100ML" "cat#V5111"
    "cat#ab55837" "cat#ab71780" "cat#ab90641" "cat#sc-8044" "cause-and-effect" "cell-based"
    "cell-specificities" "cell-to-cell" "cells" "ch" "chaperon-mediated" "charcoal-stripped"
    "chi-square" "chronically-infected" "cis-acting" "cis-elements" "class-room" "classroom-based"
    "clinic-based" "closed-type" "cloud-like" "clustal_x" "coalescent-based" "coding-sense"
    "cohort-study" "coiled-coil" "cold-arrested" "collagen-like" "colonization-inhibition"
    "colostrum-deprived" "community-based" "competency-based" "complement-directed"
    "complement-mediated" "complementarity-determining" "computer-based" "consensus-HA-based"
    "contai-ning" "copro-ELISA" "copro-PCR" "copro-antigen" "core+1" "core-loading" "core-specific"
    "coreceptor-positive" "coronavirus-like" "cost-effective" "country-level" "cow-calf"
    "cross-amplification" "cross-border" "cross-clade" "cross-depleted" "cross-immunity"
    "cross-inhibitory" "cross-linker" "cross-neutralizing" "cross-protected" "cross-protection"
    "cross-react" "cross-reacted" "cross-reacting" "cross-reactivity" "cross-referencing"
    "cross-serogroup" "cross-species" "cryo-EM" "custom-made" "cut-off" "cychrome-labeled"
    "cycles-cycle" "cystatin-like" "cyto-protective" "cytomegalo-virus"
    "cytosine–phosphate–guanosine" "data" "data-collection" "david" "day-patient" "dead-end"
    "death-1" "death-receptor" "decision-makers" "deep-purple-colored" "deliveries"
    "deoxycytidyl-deoxyguanosinyl" "depressible-4" "dicistrovirus-like" "distribution-based"
    "dnr2009" "donor-to-donor" "dose-escalation" "dose-response" "double-blind" "double-strand"
    "dsAAV-EGFP" "dsRNA-treatment" "dual-purpose" "dual-use" "d‐luciferin" "eIF-2α∼P" "eIF1A."
    "eIF2-GTP" "eIF2-α" "eIF2α∼P" "eIF2α∼P." "eIF2–GDP" "eIF2–Met–tRNAi–GTP" "early-stage"
    "easy-to-amplify" "eat-me" "eco-system" "elF2α" "electro-blotted" "emnet-nedi" "end-labeling"
    "end-organ" "end-product" "end-stage" "endo-β-N-glucosaminidase" "english" "enzyme-based"
    "epidemiologically-based" "episodes" "epitope-glutathione" "europium-labelled"
    "experimentally-infected" "extra-retinal" "facility-specific" "family-interacting" "fcwf-4"
    "feet" "ficolin" "ficolin-binding" "ficolins-1" "field-derived" "fine-tune" "fine-tuning"
    "first-ever" "first-line" "flat-bottom" "flat-bottomed" "flip-flop" "flu-like"
    "fluorescence-lifetime" "fold-change" "fold-deviations" "fold-increases" "fold-regulation"
    "follow-up" "followed-up" "food-handlers" "foot-and-mouth" "forward-versus-side-scatter"
    "four-point" "front-line" "gag-HIV" "gdo-bioinformatics" "gel-based" "gene-start" "gene-stop"
    "gene‐transfer" "genome-sense" "germline-encoded" "goodness-of-fit" "gp120-CD4-coreceptor"
    "gp120-DC" "gp120ADA" "gp120BAL" "gp120HIV" "gp120HXBc2" "gp120IIIB" "gp120MN" "gp160HxB2"
    "gp41-mAbs" "gp41IIIB" "gp41MN" "gp41binding" "graft-versus-host" "graft-vs-host"
    "greater-fold" "growth-stimulatory" "guanine-N7" "hairpin-like" "half-life" "half-lives"
    "half-month" "hand-written" "hands-on-time" "head-protection" "health-care" "health-seeking"
    "heavy-chain" "hemagglutinin-neuroamindase" "hemato-oncological" "hematoxylin-and-eosin"
    "hepatitis–including" "herb-synthetic" "hetero-complexes" "hexa-histidine"
    "high-CXCL14-expressing" "high-acuity" "high-affinity" "high-density" "high-dose"
    "high-efficiency" "high-energy" "high-exhaust" "high-fat" "high-income" "high-intensity"
    "high-level" "high-mannose" "high-performance" "high-prevalence" "high-quality"
    "high-resolution" "high-risk" "high-value" "higher-fold" "higher-order" "highest-ranking"
    "highly-passaged" "hind-limb" "histidine-tag" "home-made" "home-quarantine"
    "homosexuality-associated" "host-defense" "host-pathogen" "hot-spot" "http" "https"
    "human-like" "human-to-human" "human_animal_interface" "humidity-controlled" "hyper-induction"
    "hypo-responsiveness" "hypothesis-driven" "hypoxanthine–aminopterin–thymidine"
    "hypoxanthine–thymidine" "i.e.,1x" "iC3b" "iQ5" "idiotype" "ill-defined" "im2bw" "imgt"
    "immune-complex" "immune-compromised" "immune-enhancing" "immune-mediated" "immune-privileged"
    "immuno-chemotherapy" "immuno-modulator" "immunoglobulin-like" "in-depth" "in-frame" "in-gel"
    "in-house" "in-patient" "in-patients" "in-room" "includeupper-respiratory" "individual-level"
    "induced-ER" "infections" "influenza-like" "influenza-like-illness" "influenza-like-illnesses"
    "insect-specific" "insulin-Cy3" "insulin-like" "intent-to-treat" "inter-chain"
    "inter-connection" "inter-country" "inter-day" "inter-disulfide" "inter-disulfide-bonded"
    "inter-domain" "inter-experiment" "inter-herd" "inter-laboratory" "inter-molecule"
    "inter-quartile" "inter-subgroup" "interferon-response" "internationally-accepted"
    "internet-based" "intra-cerebrally" "intra-chain" "intra-cluster" "in‐house" "ion-trap"
    "isolation-based" "isomerases" "isotope-coded" "i≠j" "jp" "jslc" "juice-leaf" "k91Kan"
    "kainate-induced" "kappa-light-chain-enhancer" "knock-down" "know-how" "laboratory-based"
    "laboratory-confirmed" "laboratory-generated" "laboratory–confirmed" "lactide-co-glycolides"
    "ladder-like" "large-capacity" "large-scale" "large-sized" "late-preterm" "late-stage"
    "latency-associated" "leaky-scanning" "lectin-like" "left-shift" "length-of-stay"
    "lethally-infected" "leukemia-2" "life-span" "like-particles" "lineage-specific"
    "lipid-enveloped" "live-attenuated" "log-rank" "log-unit" "log-units" "log10" "long-distance"
    "long-lasting" "long-lived" "long-pentraxin" "long-range" "long-standing" "longer-term"
    "longer-than-genome-length" "long‐term" "loss-of-function" "low-CXCL14-expressing" "low-acuity"
    "low-burden" "low-copy-number" "low-cost" "low-grade" "low-molecular-weight" "low-pH"
    "low-performance" "low-population" "low-prevalence" "low-resolution" "loxP"
    "luciferase-KpnI-Sac" "lymphocytes" "lysosomes" "l‐Glutamine" "m-osaka" "m7-Cap-RNA"
    "m7GpppRNA" "mCCR5" "mCXCR3" "mRNA–protein" "mRNA–rRNA" "machine-learning" "macrophages"
    "manual-counted" "manually-counted" "max-G" "mc2155" "mean±SD" "mechanistically-motivated"
    "medical-dpc" "melting-curve" "mesh-like" "metamyelocytes" "metformin+AAV2" "metformin+scAAV2"
    "methionine-tRNA" "methyl-β-cyclodextrin" "methylthiazolyl-diphenyl-tetrazolium" "micro-RNA"
    "micro-organism’s" "microarray-based" "microbial-protein-rich" "microparticle-based"
    "microwell-based" "mid-1990s" "mid-June" "mid-September" "mid-career" "mid-stage" "mid-stream"
    "mid-year" "milliliters" "mini-kit" "minus-strand" "mmol−1" "mmwr" "mmwrhtml" "mock-infected"
    "mock-injected" "mock-inoculated" "mock-inoculation" "mock-treated" "mock-treatment"
    "model-based" "modified-self" "molecule-1" "monocytes" "mother-daughter" "mother-to-child"
    "multi-cat" "multi-cell" "multi-channel" "multi-collinearity" "multi-cycle" "multi-day"
    "multi-drug-resistant" "multi-epitope" "multi-faceted" "multi-host" "multi-modal"
    "multi-occupancy" "multi-organ" "multi-protein" "multi-specialty" "multi-step" "multi-system"
    "multiple-range" "multi‐subunit" "myelocytes" "myxovirus-resistance" "n+m≥8" "n-BuLi" "n1" "n2"
    "n=15" "n=17,108" "n=30,017" "nano-spray" "nanoparticle-based" "nasal-associated"
    "naturally-infected" "naturally-occurring" "near-cognate" "near-molecular" "near-past"
    "nearest-neighbor" "negative-sense" "negative-strand" "negative-stranded" "newly-formed"
    "newly-initiated" "next-generation" "nickel-agarose" "no-auto-correlation" "no-reflow"
    "no-subconsensus" "noise-removal" "north-central" "nose-only" "nsp1and" "oTr-1" "off-label"
    "off-line" "off-target" "oligo-dT" "oligo-nucleotide" "oligodT-Cy3" "on-chip" "on-site"
    "on-the-job" "one-exon" "one-fifth" "one-log" "one-minute" "one-sided" "one-step" "one-third"
    "one-time" "one-way" "one-yearly" "open-source" "optimization-based" "oral-administered" "org"
    "out-patient" "out-patients" "out-perform" "over-activated" "over-exploits" "over-production"
    "over-representation" "over-the-counter" "oxidants" "p-ASK1" "p16R1" "p2=m1" "p7.5" "p<0.0001"
    "p<0.001" "p<0.01" "p=0.005" "p=0.01" "p=0.015" "p=0.037" "p=0.079" "p=0.726" "p>0.05"
    "pAG-series" "pAmp-rgEBOV" "pAmp-rgEBOV-Mut" "pBEVY-A" "pBEVY-GL" "pBMSF-CN5" "pBMSF7C"
    "pBMSF7C-CN2" "pBMSF7C-N25" "pBR322" "pBR322-based" "pCAGGS-GFP-FLAG" "pCAGGS-L" "pCAGGS-NP"
    "pCAGGS-T7" "pCAGGS-VP30" "pCAGGS-VP35" "pCAGGS-VP35-FLAG" "pCANTA-5E" "pCANTAB-5E"
    "pCG-5804P-CDV-H+pCG-5804P-F" "pCG-A75" "pCG-Dog94SE-CDV-H"
    "pCG-Dog94SE-CDV_H+pCG-Lion94SNP-CDV-F" "pCG-Lion94SNP-CDV-H+pCG-Lion94SNP-CDV-F"
    "pCG-lion94SNP-CDV-H" "pCG-lion94SNP-F" "pCITE-4a" "pCMV-BlaM-Vpr" "pCMV-GFP-MLV" "pCMV-T7"
    "pCMV-gag-pol-MLV" "pEGFP-E" "pEGFP-N1-E" "pEGFP-N1vector" "pEN-L1-NINJA-L2" "pEN-L4-GPD-R1"
    "pEN-R2-NLS-3xFLAG-6xHis-L3" "pET-30a" "pET28a" "pET42b" "pFUSE-hIgG1-Fc2" "pGAD424" "pGADT7"
    "pGBKT7" "pGBKT7-clones" "pGEM-T" "pGEM7z" "pGEX-6p-1" "pH-5.0" "pHW2000" "pIC-treated" "pIgR"
    "pJON-IgG" "pKS336-RESTV-GP1" "pKm43GW" "pMG416" "pMG426" "pMM310" "pNL4-3" "pNL4-3-Luc"
    "pRetro-Tet-IFITM" "pS-EGFP-N1" "pS1-EGFP-N1" "pS2-EGFP-N1" "pS3-EGFP-N1" "pSFJ1-10"
    "pSV7d-AD8gp160" "pSV7d-JR-FLgp160" "pTEF-b" "pTM-1" "pU6" "pU6-siRNA" "pU6-siRNA-Ctrl" "pUC57"
    "pUCSBVLT7" "pUCSBVMT7" "pUCSBVST7" "pUCSBVΔNSsT7" "paired-end" "pan-filovirus"
    "partial-length" "partially-purified" "particle-containing" "password-protected"
    "pathogen-associated" "pathogen-based" "pathogen-specific" "pathogens" "pattern-recognition"
    "pcDNA3.1" "pcDNA3.1-eGFP" "pcDNA3.1B" "pcr" "pdm09" "pdmH1N1" "penicillin-streptomycin"
    "pentraxin-like" "peptide-like" "peptide_length" "peptide_start" "peptidyl–tRNA" "per-sample"
    "percpCy5.5" "person-to-person" "pgl4.20" "phage‐based" "phase-contrast" "phenol-chloroform"
    "phoshpho-elF2α" "photo-multiplier" "physician-administrator" "physician-administrators"
    "picornavirus-like" "pig-industry" "pin-like" "ping-pong" "pixel" "placebo-controlled"
    "plaque-forming" "plastic-immobilized" "pmCherry-LacRep" "policy-makers" "poly-A" "poly-L"
    "poly-adenosinic-polyuridylic" "polyadenylation-specificity" "poorly-controlled" "pop-attack"
    "population-based" "positive-cases" "positive-control" "positive-sense" "positive-strand"
    "positive-stranded" "positively-charged" "positives+all" "post-CD4" "post-CatB" "post-RSV"
    "post-UPR" "post-administration" "post-antibiotic" "post-binding" "post-challenge"
    "post-challenged" "post-entry" "post-exposure" "post-graduate" "post-hoc" "post-immunization"
    "post-incubation" "post-infection" "post-inoculation" "post-intervention" "post-mortem"
    "post-onset" "post-poly" "post-sequencing" "post-termination" "post-test"
    "post-transcriptional" "post-transduction" "post-transfection" "post-translationally"
    "post-transplant" "post-treated" "post-vaccination" "postero-anterior" "post‐GCV"
    "post‐transduction" "post‐vector" "prepub" "previously-described" "pri-miR-122-derived"
    "primary-participant" "prime-vaccinated" "primer-derived" "primer3" "prime–boost" "pro-drug"
    "pro-inflamatory" "pro-survival" "probiotic-treated" "product-based" "promoter-5"
    "proof-of-concept" "prophyl-actically" "proprotein-processing" "propyltriethoxysilane-coated"
    "protein-DNA" "protein_length" "protein‑specific" "proteome-wide" "protocol-based"
    "province-specific" "pseudo-VRC" "pseudo-capped" "pseudo-particles" "pseudo-stratified"
    "pseudovirion-bound" "pseudovirus+antisera" "psiEGFP-N1" "public-sector" "pulse-labeled"
    "pyrimidin-5-yl" "rAAV‐2" "rAAV‐7" "rAAV‐8" "rAMPV-4" "rVV-CN" "rVV-CN2" "rVV-CN5" "rVV-HCV"
    "rVV-HCV-treated" "rVV-N25" "rVV-N25-induced" "rVV-N25-treated" "rabies-like"
    "range=300-100000" "rank-sum" "ready-to-use" "real-life" "real-world" "realplex2"
    "receptor-alpha" "reductases" "regimen!" "replication-transcription" "research_and_development"
    "residue-level" "resource-limited" "resource-rich" "respirations" "respvir" "retro-orbitally"
    "reverse-correlated" "reverse-transcribed" "reversed-phase" "rfeIFNα" "rgEBOV-Mut" "rhCXCL14"
    "rho=0.08" "rho=−0.001" "risk-ratio" "rnx-reaction" "roche-applied-science" "roost-tree" "row2"
    "rr5710a2" "rsb" "rt-RT-PCR" "ruo" "sGP" "sGPEdit+GP1" "sGPEdit+vector" "sGPEdit∶GP1" "sGP∶GP1"
    "sHyal2" "sXBP1" "same-day" "sample-passage" "sample-to-sample" "sc-7392" "scAAV1"
    "scAAV2+metformin" "scAAV2-EGFP" "scAAV6" "scaled-down" "scaled-up" "school-age" "school-based"
    "school-closure" "school-level" "science-based" "score>3" "seizure-induced" "self-antigens"
    "self-degradation" "self-identified" "self-limited" "self-reported" "self-reporting"
    "self-sustaining" "semi-adherence" "semi-automated" "sequence-expressing" "sera"
    "sero-positivity" "sero-prevalence" "serotype" "serotypes" "seven-bedded"
    "severe-acute-respiratory-syndrome" "shCXCL14" "shISG56" "short-course" "short-pentraxins"
    "short-term" "shut-off" "siHsc70" "side-by-side" "side-effect" "side-effects" "similar-sized"
    "similarity-based" "simulation-based" "single-cell" "single-cell-based" "single-cell-sorted"
    "single-chain" "single-cycle" "single-fragment" "single-membrane" "single-molecule"
    "single-segment" "single-step" "single-variable-domain" "singly-spliced" "situations" "six-bed"
    "six-helix" "six-question" "size-based" "size‐matched" "slow-to-decode" "sm98"
    "small-interfering" "small-molecule" "smaller-sized" "smear-positive" "so-called"
    "socio-demographics" "socio-economic" "solid-phase" "source-sink" "south–north" "soy-based"
    "specific-pathogen-free" "spike-and-slab" "spill-over" "spinal-cord" "split-plot"
    "split-product" "sputum-positive" "square-wave" "ssAAV2" "stage-specific" "stand-alone"
    "steady-state" "stem-loop" "stem–loop" "sterile‐filtered" "stop-codon" "stop–carry" "strains"
    "streptavidin–Alexa" "stress-activated" "stress-induced" "stress-responsive" "stress-stimulus"
    "structure-function" "sub-G1" "sub-Saharan" "sub-analysis" "sub-clinical" "sub-compartments"
    "sub-consensus" "sub-lethal" "sub-optimally" "sub-region" "sub-regions" "sub-study"
    "sub-threshold" "subtilisin-like" "subtype" "subtype-A" "subtype-B" "summer-heat"
    "super-resolution" "superantigen-like" "supra-molecular" "surface-expression"
    "susceptible-exposed-infected-recovered-susceptible" "swine-origin" "swine-raising"
    "switch-like" "symptoms" "systemically‐administered" "t11548c" "takara-bio" "take-over"
    "target-cell" "teacher-in-charge" "teacher-led" "temperature-arrested"
    "termination–reinitiation" "tested-for" "tetC" "the16-bit" "thin-layer" "three-category"
    "three-dimensional" "three-pronged" "three-segment" "three-step" "three-times" "three-way"
    "through-out" "tick-borne" "tightly-regulated" "time-bound" "time-chase" "time-course"
    "time-frame" "time-point" "time-points" "time-to-result" "time-window" "timepoint0hMean"
    "time‐points" "to108" "top-down" "trade-off" "trade-offs" "trans-Golgi" "trans-acting"
    "trans-cis" "transcription-PCR" "transfection-based" "treatment-to-cure"
    "treatment–efficiently" "tri-clade" "tri-country" "triage-to-service" "trimer-of-hairpin"
    "trimer-of-hairpins" "trust-based" "trypsin-EDTA" "trypsin-like" "tumor-node-metastasis"
    "turn-around" "turn-around-times" "tw91" "two-ddCt" "two-exon" "two-layered" "two-sample"
    "two-segment" "two-step" "two-tailed" "two-thirds" "two-tier" "type-1" "type-2" "type-C"
    "type-I" "type-II" "type5-Q" "uAUG" "uAUGs" "uORF" "uORF-GFP" "uORFs" "ug"
    "ultra-centrifugation" "un-2" "under-five" "under-representation" "units" "up-to-date"
    "upper-room" "use-on-demand" "user-friendly" "vaccine-strain" "vacuole-like" "value<0.05"
    "vector-based" "vector-borne" "vector-infected" "ventilator-induced" "vg" "vgs" "villi"
    "viremia" "virion-based" "virion-bound" "virus+antibody" "virus+antibody+sGP" "virus-8"
    "virus-based" "virus-like" "virus-only" "wake-up" "water-acetonitrile" "water-based"
    "water-in-oil" "wave-like" "web-based" "well-adapted" "well-characterized" "well-defined"
    "well-described" "well-designed" "well-differentiated" "well-documented" "well-equipped"
    "well-established" "well-exercised" "well-mixed" "well-reported" "well-studied" "well-suited"
    "well-ventilated" "white-shelled" "whole-cell" "whole-proteome" "whole-thickness"
    "whole-transcriptome" "wide-spread" "wiener2" "wild-caught" "wildlifetrade"
    "wildlifetradetracker" "wind-heat" "within-household" "within180" "without-cross-linker"
    "workers" "www" "www3" "x-ray" "x-y" "x1" "x2" "x|negative" "x|positive" "year-to-year"
    "z-score" "z-scores" "zero-frame" "zi=xi−x¯" "ztz240" "§24" "Â¼" "×100" "í3" "ΔCt" "ΔCt-values"
    "ΔG*" "ΔΔCt" "ΔΨm" "α-32P-radiolabeled" "α-HIV-1-gp120" "α-Mac-3" "α-aminophosphonate"
    "α-helices" "α-hnRNPA1" "α-non-phosphorylated" "α2,3" "α2,6" "α2→3" "α2→6>α2→3>α2→8" "α3" "αv"
    "β-D-1-thiogalactopyranoside" "β-d-thiogalactopyranoside" "β-defensins-2" "β-jelly"
    "γ-32P-radiolabeled" "γ-irradiation" "γ134.5" "δAg" "μL" "μLof" "μg" "μl" "μmol" "σ1" "σ1s"
    "σC" "χ2" "−were" "△potentiation"))

