
(IN-PACKAGE :SP)
(DEFPARAMETER |*NS-RD-covid-2020-04-03-0403-COM-PMC-1-100*|
  '("1R1L" "20S" "<0.001" "<0.05" "<10%" "<15" "<20%" "<25" "<25%" "<30%" "<40%" "<5%" "<50%"
    "<60%" "<70%" "<75%" "<80%" "<9" "<90%" "<confirm_length" "<confirm_score" "<maxgap"
    "<minscore" "<qual_show" ">0.5" ">10,000" ">100-fold" ">102–3" ">38°C" ">8000" ">94%" ">99%"
    ">>" ">four-fold" ">ten-fold" "A-3" "A-B" "A-C" "A-MLV" "A-RNA" "A-bulge" "A-form" "A.G." "A1"
    "A1-B2-C" "A13456C" "A13465G" "A182" "A2" "A260" "A33" "A4R" "A5" "A59-infected" "A59-sized"
    "AA-3" "AAC-3" "AAGTGC-3" "ABI3730" "ACAAGUU" "ACAUCCGUAAGUCCUUCCCUU" "ACE2-SARS-CoV"
    "ACGGAUGUUU" "ACTGG-3" "AF370851" "AGAGCGAACACGAAUU" "AJ271612" "AJ427629" "ALI" "AN18" "APG5"
    "AS+RS" "AS37" "ASGP-R" "ASLV-A" "ATCGAATTCGGTCAGTGG-3" "ATS" "AU_041" "AU_042" "AY165779"
    "AY297028" "AY304486" "AY700211" "AY733102-AY733566" "Ac·T" "Ad35" "Adeno-associated"
    "AfllII-rITRΔE3" "African" "African-American" "Africans" "Alb17Rs" "AmC6-dT" "Asia1" "Atg12p"
    "Atg8p" "B-D" "B1c" "B2c" "B6" "BALB" "BG933897" "BG936672" "BIAcore3000" "BIP-1" "BJ302" "BL3"
    "BODIPY-C5" "BSL-4" "BU693999" "BamHI-and" "Becton-Dickinson" "Bed" "Bio-Rad" "Bio-Tek"
    "Bonferroni" "Bp" "BspMI" "Business" "Bxz1" "C-S8c1" "C-S8c1p100" "C-terminally" "C2-like"
    "C20880→U" "C3" "C9" "CAAAGUUCCUUGUACCUGAUU" "CAGTGAG-3" "CAUAU" "CB-O" "CC-chemokine"
    "CCGACUUAUU" "CCGCAAGACTGCTAGCCGAG-GCAAGCACCCTATCAGGC" "CCL-61"
    "CCTGCTGCTATGCCTCATCTTCTT-T-GACAAACGGGCAACATACCTT" "CD40-ligand" "CD8+T-cell" "CD8+T-cells"
    "CD8+effector" "CD8α" "CDC-notifiable-disease" "CF-11" "CGAGCGCUAUU" "CGCGGACAUCUAUU" "CL-100"
    "CM10" "CO1-animal" "CO1-insect" "CO1-moth" "COS-7" "CR022" "CR3014" "CR3022" "CRL-11268"
    "CRL-1658" "CUHK-Su" "CUHK-Su10" "CUHK-W1" "CUUGUAUCGUUCUAUUAUCUU" "CYDV-RPV" "CaCl2" "Cabb-S"
    "Calmette-Guérin" "Cbz-VNSTLQ-CMK" "Chinese-English" "Communication-recovery" "Control"
    "Cor-p-F4" "Cor-p-R4" "Cor-probe" "Corbett-Research" "Cross-border" "Cross-inhibition"
    "Csp6I-F" "Ct-value" "Ct-values" "CuKα" "Culture-competence" "Cα" "Cβ" "Cβ–Cγ" "D-x" "D0" "D3"
    "D5" "DALYs" "DC-SIGN–interacting" "DENV-2" "DH5α" "DMEM" "DN59" "DNA+XIAP" "DNA-NC" "DNA-PEI"
    "DP47" "DPK22" "DPL16" "DQ066891" "DQ066892" "DQ066893" "DQ066894" "DQ066895" "DQ066896"
    "DQ066897" "DQ066898" "DR2" "Diels-Alder" "Dimerized_RII" "Dimerized_TGF-beta" "Dose-response"
    "Dual-color-stained" "Dunn" "Dupont-NEN" "E.coli" "E1" "E3-deleted" "EC50" "EF1AA" "EF1AB"
    "EF1AB>EF1AA>β-actin>18S" "EF1AB>EF1AA>β-actin>S20>18S" "EGFP" "EGFP-N1" "ER-to-Golgi" "ERS"
    "ETH-2" "Eighty-two" "Electrical-based" "Ellermann-Eriksen" "End-Users" "End-user" "EnvIssues"
    "Epitope-MHC-TCR" "Epon-Araldite" "Epon-embedded" "European" "Event-phase" "Evidence-Based"
    "Excel-application" "Excel©" "F1" "F12" "F1c" "F2" "F2c" "FASTA3" "FAdV-9" "FEV1" "FFM-1"
    "FLPs_all" "FM1" "FR-E" "FRhK-4" "FRhK4" "FiO2" "First-Strand" "First-strand" "FluA"
    "Follow-up" "Food-and-mouth" "Food-borne" "Foot-and-Mouth" "Foot-and-mouth" "Forty-eight"
    "Forty-nine" "Forty-one" "Forty-six" "Forward-thinking" "Foundation-supported" "FynSH3" "G-H"
    "G0" "G13423–C13425" "G139c" "G139t" "G2565AA" "G2565AB" "G38" "GAACACCAAGUUUCACUGUUU"
    "GAGCGAGUUGGUCAAUU" "GATAAAACGCCGCAGACACATCC-TT-CCAACCTCTTGTCCTCCAA" "GATT" "GCAGCUUCCUACUUCUU"
    "GEFood" "GEN12" "GEN13" "GFP–LC3-containing" "GG-3" "GG-TAMRA" "GGACGGCUUCCUCUAUAUGUU"
    "GGATCCTTCCCTTCTGTC-3" "GGTTKATCCAAGAAAGGACCCAGTC-GCCATAGTGGTCTGCGGA" "GO-DEV" "GPΔTM" "GRO-α"
    "GRO-β" "GSM8528" "GTAGAACCTGTCTACATAGCT-3" "GTCAGTGG-3" "GZ-C" "GZ02" "Genenco"
    "Goat-anti-Mouse-HRP" "Guinea-2" "Gulu" "H+L" "H-π" "H1" "H1-H16" "H1N2" "H2O" "H2SO4" "H3"
    "H3N8" "H5" "H5N3" "H7" "H7N3" "H9N2" "HBS-EP" "HBsAb" "HEPES-TALP" "HHV-6" "HIS3" "HIV-D"
    "HIV2" "HK022" "HKL2000" "HKU-39849" "HKU39849-infected" "HLA-DR2" "HNN-COSY" "HPA-Coronavirus"
    "HRV14" "HRV87" "HRV89" "HSV-1" "HSV-2" "HSV-2-induced" "Haber-Weiss" "Hardy-Weinberg"
    "Health-Evidence" "Hep_1F" "Hep_4R" "Hi-Bred" "High-affinity" "High-density" "High-quality"
    "Hospital" "Huber" "Huh7" "IC90" "ICD-10" "ICD9" "ICP47" "IFN-like" "IFN-response" "IFN-αR2"
    "IFN-γ-IFN-γR1-STAT1" "IFN-γR1" "IFN-γR2" "IFN-γand" "IFN-δ" "IFN-λ2" "IFN-λR1" "IFN-ξ" "IFN-ω"
    "II–VI" "IL-10-592A" "IL-13Rα" "IMGT-Ontology" "IO" "ION" "IX70" "Ia-antigen"
    "Ia1−Ba1+Ia2−Ba22" "Ig-like" "IgG2" "IgG2b" "IgV-like" "Immuno-Plate" "In-depth"
    "Internet-based" "Invitrogen" "Iup*Idn" "Iup+Idn" "J-L" "J2EE" "JD1228" "JD1229" "JD932"
    "JM109" "Jack-knife" "January-March" "Jukes-Cantor" "K.J.R." "K.K." "KA" "KGa-1b" "KO-mice"
    "KT2440" "Kagawa-Singer" "Kaplan-Meier" "Kassim-Lakha" "Ki" "Klenow" "Kolmogorov-Smirnov"
    "Kruskal-Wallis" "Kruskal–Wallis" "Kwok-yung" "L-A" "L-A-promoted" "L-α-phosphatidyl-L-serine"
    "L12" "L7" "LAMP-PEI" "LCDV-1" "LEISS" "LK2H10" "LKM" "LLCKM-2" "LLCMK-2" "LT-like" "LTα"
    "Lab-on-a-Chip" "Ladekjær-Mikkelsen" "Large-scale" "Latino" "Lin-Kou" "Long-range"
    "Low-density" "Luria-Bertani" "Ly-6G" "M-Medical" "M13" "M17-agar" "MA2D5" "MATα" "MBq"
    "MCA-AVLQSGFR-Lys" "MCA-AVLQ↓SGFR-Lys" "MHC-I" "MHV-4" "MHV-A59" "MIP-lα" "MM007"
    "MMLV-derived" "MOMA-2" "Ma=log⁡2" "Madin-Darby" "Mann-Whitney" "Mark-S" "Markov-chain-based"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWG4baEdaqhaaWcbaGaem4AaSgabaGaemiwaGfaaaaa@30EA@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWG5bqEdaqhaaWcbaGaem4AaSgabaGaemiwaGfaaaaa@30EC@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWG6bGEdaqhaaWcbaGaem4AaSgabaGaemiwaGfaaaaa@30EE@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWGebarcqGGOaakcqWG1bqDcqGGPaqkcqGH9aqpdaGadaqaamaaqahabaGaeiikaGIaemyDau3aaSbaaSqaaiabbMgaPbqabaGccqGHsislcqWG1bqDdaWgaaWcbaGaeeyAaKMaee4Ba8gabeaakiabcMcaPmaaCaaaleqabaGaeGOmaidaaaqaaiabdMgaPjabg2da9iabigdaXaqaaiabiodaZiabiodaZaqdcqGHris5aaGccaGL7bGaayzFaaWaaWbaaSqabeaacqaIXaqmcqGGVaWlcqaIYaGmaaGccqGGUaGlcaWLjaGaaCzcaGqabiab=zda2aaa@4CDC@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWGnbqtdaWgaaWcbaGaemyyaegabeaakiabg2da9iGbcYgaSjabc+gaVjabcEgaNnaaBaaaleaacqaIYaGmaeqaaOGaeiikaGYaaSaaaeaacqWGjbqsdaWgaaWcbaGaemyyaeMaeGymaedabeaakiabgkHiTiabdkeacnaaBaaaleaacqWGHbqycqaIXaqmaeqaaOGaey4kaSIaemysaK0aaSbaaSqaaiabdggaHjabikdaYaqabaGccqGHsislcqWGcbGqdaWgaaWcbaGaemyyaeMaeGOmaidabeaaaOqaaiabikdaYaaacqGGPaqkaaa@4924@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWGtbWudaWgaaWcbaGaemOBa4gabeaakiabg2da9maalaaabaGaemivaqLaemiuaafabaGaemivaqLaemiuaaLaey4kaSIaemOrayKaemOta4eaaiabcYcaSiaaxMaacaWLjaacbeGae8xmaedaaa@3B71@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqWGtbWudaWgaaWcbaGaemiCaahabeaakiabg2da9maalaaabaGaemivaqLaemiuaafabaGaemivaqLaemiuaaLaey4kaSIaemOrayKaemiuaafaaiabcYcaSiaaxMaacaWLjaacbeGae8Nmaidaaa@3B7B@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvcqqGAbGwcqGH9aqpdaGbdaqaaiabdseaenaaDaaaleaacqaIWaamaeaacqaIYaGmaaGccqGHsislcqWGebarcqGGOaakcqWG1bqDcqGGPaqkdaahaaWcbeqaaiabikdaYaaaaOGaayj84laawUp+aiabc+caViabcIcaOiabikdaYiabgEna0kabdseaenaaDaaaleaacqaIWaamaeaacqaIYaGmaaGccqGGPaqkcaWLjaGaaCzcaGqabiab=Dda3aaa@49B6@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaee4AaSgabaGaeeiwaGfaaaaa@30A0@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeOmaiJaee4mamdabaGaee4qameaaaaa@30F1@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeOmaiJaee4mamdabaGaee4raCeaaaaa@30F9@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeOmaiJaee4mamdabaGaeeivaqfaaaaa@3113@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeOmaiJaee4mamdabaGaeeyqaeeaaaaa@30ED@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeymaeJaeeOmaidabaGaee4qameaaaaa@30ED@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeymaeJaeeOmaidabaGaee4raCeaaaaa@30F5@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeymaeJaeeOmaidabaGaeeivaqfaaaaa@310F@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaacqqGwbGvdaqhaaWcbaGaeeymaeJaeeOmaidabaGaeeyqaeeaaaaa@30E9@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaGabaqaauaabaqadmaaaeaacqWG1bqDdaWgaaWcbaGaeGymaedabeaakiabg2da9iabdIha4naaBaaaleaacqaIXaqmaeqaaOGaeiilaWcabaGaemyDau3aaSbaaSqaaiabikdaYaqabaGccqGH9aqpcqWG5bqEdaWgaaWcbaGaeGymaedabeaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIZaWmaeqaaOGaeyypa0JaemOEaO3aaSbaaSqaaiabigdaXaqabaGccqGGSaalaeaacqWG1bqDdaWgaaWcbaGaeGinaqdabeaakiabg2da9iabdIha4naaBaaaleaacqaIYaGmaeqaaOGaeiilaWcabaGaemyDau3aaSbaaSqaaiabiwda1aqabaGccqGH9aqpcqWG5bqEdaWgaaWcbaGaeGOmaidabeaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaI2aGnaeqaaOGaeyypa0JaemOEaO3aaSbaaSqaaiabikdaYaqabaGccqGGSaalaeaacqWG1bqDdaWgaaWcbaGaeG4naCdabeaakiabg2da9iabdIha4naaBaaaleaacqaIZaWmaeqaaOGaeiilaWcabaGaemyDau3aaSbaaSqaaiabiIda4aqabaGccqGH9aqpcqWG5bqEdaWgaaWcbaGaeG4mamdabeaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaI5aqoaeqaaOGaeyypa0JaemOEaO3aaSbaaSqaaiabiodaZaqabaGccqGGUaGlaaaacaGL7baacaWLjaGaaCzcaGqabiab=vda1aaa@7097@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaGabaqaauaabaqadmaaaeaacqWG4baEdaqhaaWcbaGaem4AaSgabaGaemiwaGfaaOGaeyypa0JaeiikaGIaemiCaa3aaSbaaSqaaiabdUgaRbqabaGccqGGOaakcqqGybawcqqGbbqqcqGGPaqkcqGHRaWkcqWGWbaCdaWgaaWcbaGaem4AaSgabeaakiabcIcaOiabbIfayjabbEeahjabcMcaPiabcMcaPiabgkHiTiabcIcaOiabdchaWnaaBaaaleaacqWGRbWAaeqaaOGaeiikaGIaeeiwaGLaee4qamKaeiykaKIaey4kaSIaemiCaa3aaSbaaSqaaiabdUgaRbqabaGccqGGOaakcqqGybawcqqGubavcqGGPaqkcqGGPaqkcqGGSaalaeaaaeaaaeaacqWG5bqEdaqhaaWcbaGaem4AaSgabaGaemiwaGfaaOGaeyypa0JaeiikaGIaemiCaa3aaSbaaSqaaiabdUgaRbqabaGccqGGOaakcqqGybawcqqGbbqqcqGGPaqkcqGHRaWkcqWGWbaCdaWgaaWcbaGaem4AaSgabeaakiabcIcaOiabbIfayjabboeadjabcMcaPiabcMcaPiabgkHiTiabcIcaOiabdchaWnaaBaaaleaacqWGRbWAaeqaaOGaeiikaGIaeeiwaGLaee4raCKaeiykaKIaey4kaSIaemiCaa3aaSbaaSqaaiabdUgaRbqabaGccqGGOaakcqqGybawcqqGubavcqGGPaqkcqGGPaqkcqGGSaalaeaacqqGybawcqGH9aqpcqqGbbqqcqGGSaalcqqGdbWqcqGGSaalcqqGhbWrcqGGSaalcqqGubavcqGGSaalaeaacqWGRbWAcqGH9aqpcqaIXaqmcqaIYaGmcqGGSaalcqaIYaGmcqaIZaWmcqGGSaalaeaacqWG6bGEdaqhaaWcbaGaem4AaSgabaGaemiwaGfaaOGaeyypa0JaeiikaGIaemiCaa3aaSbaaSqaaiabdUgaRbqabaGccqGGOaakcqqGybawcqqGbbqqcqGGPaqkcqGHRaWkcqWGWbaCdaWgaaWcbaGaem4AaSgabeaakiabcIcaOiabbIfayjabbsfaujabcMcaPiabcMcaPiabgkHiTiabcIcaOiabdchaWnaaBaaaleaacqWGRbWAaeqaaOGaeiikaGIaeeiwaGLaee4raCKaeiykaKIaey4kaSIaemiCaa3aaSbaaSqaaiabdUgaRbqabaGccqGGOaakcqqGybawcqqGdbWqcqGGPaqkcqGGPaqkcqGGUaGlaeaaaeaaaaaacaGL7baacaWLjaGaaCzcaGqabiab=rda0aaa@BAD0@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaGabaqaauaabaqadqaaaaqaaiabdIha4naaBaaaleaacqWGPbqAaeqaaOGaeyypa0JaeiikaGIaemyyae2aaSbaaSqaaiabdMgaPbqabaGccqGHRaWkcqWGNbWzdaWgaaWcbaGaemyAaKgabeaakiabcMcaPiabgkHiTiabcIcaOiabdogaJnaaBaaaleaacqWGPbqAaeqaaOGaey4kaSIaemiDaq3aaSbaaSqaaiabdMgaPbqabaGccqGGPaqkcqGGSaalaeaaaeaaaeaaaeaacqWG5bqEdaWgaaWcbaGaemyAaKgabeaakiabg2da9iabcIcaOiabdggaHnaaBaaaleaacqWGPbqAaeqaaOGaey4kaSIaem4yam2aaSbaaSqaaiabdMgaPbqabaGccqGGPaqkcqGHsislcqGGOaakcqWGNbWzdaWgaaWcbaGaemyAaKgabeaakiabgUcaRiabdsha0naaBaaaleaacqWGPbqAaeqaaOGaeiykaKIaeiilaWcabaGaemiEaG3aaSbaaSqaaiabdMgaPbqabaGccqGGSaalcqWG5bqEdaWgaaWcbaGaemyAaKgabeaakiabcYcaSaqaaiabdQha6naaBaaaleaacqWGPbqAaeqaaOGaeyicI4Saei4waSLaeyOeI0IaeGymaeJaeiilaWIaeGymaeJaeiyxa0LaeiilaWcabaaabaGaemOEaO3aaSbaaSqaaiabdMgaPbqabaGccqGH9aqpcqGGOaakcqWGHbqydaWgaaWcbaGaemyAaKgabeaakiabgUcaRiabdsha0naaBaaaleaacqWGPbqAaeqaaOGaeiykaKIaeyOeI0IaeiikaGIaem4zaC2aaSbaaSqaaiabdMgaPbqabaGccqGHRaWkcqWGJbWydaWgaaWcbaGaemyAaKgabeaakiabcMcaPiabc6caUaqaaaqaaaqaaaaacqWGPbqAcqGH9aqpcqaIXaqmcqGGSaalcqaIYaGmcqGGSaalcqaIZaWmcqGGUaGlaiaawUhaaiaaxMaacaWLjaacbeGae83mamdaaa@8F74@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaGabaqaauaabaqaemaaaaqaaiabdwha1naaBaaaleaacqaIXaqmcqaIWaamaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabigdaXiabikdaYaqaaiabdgeabbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaIXaqmaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabigdaXiabikdaYaqaaiabdgeabbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaIYaGmaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabigdaXiabikdaYaqaaiabdgeabbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaIZaWmaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabigdaXiabikdaYaqaaiabdoeadbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaI0aanaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabigdaXiabikdaYaqaaiabdoeadbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaI1aqnaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabigdaXiabikdaYaqaaiabdoeadbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaI2aGnaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabigdaXiabikdaYaqaaiabdEeahbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaI3aWnaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabigdaXiabikdaYaqaaiabdEeahbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaI4aaoaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabigdaXiabikdaYaqaaiabdEeahbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIXaqmcqaI5aqoaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabigdaXiabikdaYaqaaiabdsfaubaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaIWaamaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabigdaXiabikdaYaqaaiabdsfaubaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaIXaqmaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabigdaXiabikdaYaqaaiabdsfaubaakiabcYcaSaaaaiaawUhaaiaaxMaacaWLjaacbeGae8xnauJae83jaCcaaa@AA82@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaGabaqaauaabaqaemaaaaqaaiabdwha1naaBaaaleaacqaIYaGmcqaIYaGmaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabikdaYiabiodaZaqaaiabdgeabbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaIZaWmaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabikdaYiabiodaZaqaaiabdgeabbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaI0aanaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabikdaYiabiodaZaqaaiabdgeabbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaI1aqnaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabikdaYiabiodaZaqaaiabdoeadbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaI2aGnaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabikdaYiabiodaZaqaaiabdoeadbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaI3aWnaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabikdaYiabiodaZaqaaiabdoeadbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaI4aaoaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabikdaYiabiodaZaqaaiabdEeahbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIYaGmcqaI5aqoaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabikdaYiabiodaZaqaaiabdEeahbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIZaWmcqaIWaamaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabikdaYiabiodaZaqaaiabdEeahbaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIZaWmcqaIXaqmaeqaaOGaeyypa0JaemiEaG3aa0baaSqaaiabikdaYiabiodaZaqaaiabdsfaubaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIZaWmcqaIYaGmaeqaaOGaeyypa0JaemyEaK3aa0baaSqaaiabikdaYiabiodaZaqaaiabdsfaubaakiabcYcaSaqaaiabdwha1naaBaaaleaacqaIZaWmcqaIZaWmaeqaaOGaeyypa0JaemOEaO3aa0baaSqaaiabikdaYiabiodaZaqaaiabdsfaubaakiabc6caUaaaaiaawUhaaiaaxMaacaWLjaacbeGae8xnauJae83jaCIae83jaCcaaa@ABAD@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaGcaaqaaiabiAda2iabc6caUiabiMda5iabicdaWaWcbeaaaaa@3093@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaadaaeWaqaamaaemaabaacbiGae8NrayecbaGae4hkaGIae83vaCLae4xkaKIaeyOeI0Iae8Nray0aaSbaaSqaaiab=Dha3bqabaGccqGFOaakcqWFxbWvcqGFPaqkaiaawEa7caGLiWoaaSqaaiab+PgaQbqaaiab+LgaPbqdcqGHris5aaaa@3F04@"
    "MathType@MTEF@5@5@+=feaafiart1ev1aaatCvAUfKttLearuWrP9MDH5MBPbIqV92AaeXatLxBI9gBaebbnrfifHhDYfgasaacH8akY=wiFfYdH8Gipec8Eeeu0xXdbba9frFj0=OqFfea0dXdd9vqai=hGuQ8kuc9pgc9s8qqaq=dirpe0xb9q8qiLsFr0=vr0=vr0dc8meaabaqaciaacaGaaeqabaqabeGadaaakeaaieWacqWF1bqDdaWgaaWcbaGaeGymaeZaaSbaaWqaaiabb+gaVbqabaaaleqaaOGaeyOeI0Iae8xDau3aaSbaaSqaaiabiodaZiabiodaZmaaBaaameaacqqGVbWBaeqaaaWcbeaaaaa@36F7@"
    "May-Grünwald-Giemsa" "Me" "Mean-squared"
    "Met-Gly-Glu-Phe-Lys-Val-Asp-Lys-Phe-Asn-Ile-Glu-Asp-Phe-Phe-Ser-Gly" "Michaelis-Menten"
    "Mpro-N1" "Mpro–N1" "Mte-PrPSc" "Multi-FASTA" "Multi-collinearity" "Multiscreen-HTS"
    "Murray-Garcia" "Myc-captured" "M−1•s−1" "N-2-hydroxyethylpiperazine-N" "N-A1-A2-B2-C"
    "N-A1-B2-C" "N-A2-B2-C" "N-B2-C" "N-p-tosyl-L-phenylalanine" "N-α-9-flurenylmethyloxycarbonyl"
    "N1" "N1-N9" "N2" "N3" "NAHPD-oxidase" "NAP25" "NC_000857" "NC_000899" "NC_000902" "NC_001132"
    "NC_001266" "NC_001322" "NC_001451" "NC_001546" "NC_001566" "NC_001598" "NC_001609" "NC_001623"
    "NC_001625" "NC_001659" "NC_001661" "NC_001753" "NC_001803" "NC_001824" "NC_001962" "NC_002084"
    "NC_002188" "NC_002306" "NC_002484" "NC_002520" "NC_002532" "NC_002593" "NC_002642" "NC_002687"
    "NC_002702" "NC_002767" "NC_002794" "NC_003092" "NC_003215" "NC_003372" "NC_003533" "NC_003554"
    "NC_003557" "NC_003631" "NC_003847" "NC_003848" "NC_003977" "NC_004047" "NC_004062" "NC_004690"
    "NC_004718" "NC_005038" "NC_005084" "NC_005309" "NC_005336" "NC_005337" "NC_005902" "NC_005906"
    "ND-1000" "NFn+1" "NH4Ac" "NM_021677" "NP_308832" "NP_743718" "NP_892111" "NRC+Picker"
    "NT$15,100" "NT$17,420" "NT$27,170" "NT$32,330" "NW633959" "NW_047556" "NXS" "NZ9000"
    "Na+-SWy-2" "Na2HPO4" "Nasopharyngeal-aspirate" "Negative-strand" "Nei-Gojobori" "Neuman-Keuls"
    "Newman-Keuls" "Ni-NTA" "Ninety-five" "No-template" "NsiI-EcoRI-cut" "NsiI-EcoRV-cut" "Nuc"
    "Nunc-Immuno" "O-phenylendiamine" "O-phenylenediamine" "O.D." "O157" "OD405" "OD600" "OD600nm"
    "OPTI-MEM" "ORF1b" "OSU3" "One-Step" "One-dimensional" "One-third" "Open-ended" "P.C." "P3-1"
    "P5-2" "P6" "P6–P1" "PAM250" "PAML3.14" "PAdV-5" "PBS+0.05%" "PBS-T" "PBS-Tween" "PBV-like"
    "PCR-RFLP" "PCV2" "PCV2-infection" "PCV2-inoculation" "PCV2-replication" "PCV2-titre"
    "PCV2-titres" "PE501" "PEI-DNA" "PEI-LAMP" "PIV1" "PIV2" "PIV3" "PL12" "PLP139-151" "PMA"
    "PMMV-FP1" "PMMV-Probe1" "PMMV-RP1" "PMMV-like" "POD-substrate" "PSG10" "PSG16" "PSG16-PSG32"
    "PSG17" "PSG17N" "PSG2" "PSG24" "PSG30" "PSG31" "PSG32" "PSG36" "PSG36-PSG40" "PSG37" "PSG38"
    "PSG39" "PSG40" "PSG41" "PSG42" "PSG43" "PSG6" "PUMC03" "PWMS-affected" "PY54" "PaCO2" "PaO2"
    "Pages" "Parallel-track" "Passing-Bablok" "Payment-DRG" "Phi29-like" "Poly" "Population-based"
    "Positive-strand" "Post-mortem" "PrPC–PrPSc" "PrPSc-Mte" "PrPSc-soil" "Prism-7000" "Probe70"
    "Psg16" "Psg21" "Psg23" "Psg29" "Psg32" "R&D" "R-PE-conjugated" "R.G." "R2" "R4-6A2-Biotin"
    "RBSusp45" "RD114" "RF-5000" "RGD-like" "RGE-like" "RGE1" "RGSC3.1" "RNApol" "RNaseV1" "RQ1"
    "RR-MS" "RS18" "RS42" "RS43" "RS71" "RS78" "RS8" "RS91" "RS94" "RSB-NP40" "RSV-A" "RSV-B"
    "RT-RTCK-05" "RT-less" "RU2000" "Rattus_norvegicus" "Reaction-Restriction"
    "Reverse-transcription" "Ribo-Green" "Rodriguez-Roisin" "Rotor-Gene" "S-x-R-E-x" "S1"
    "S1-subunit" "S1C" "S1I" "S1O" "S2B" "S2D" "S2I" "S2O" "S3" "S318–510" "S3C" "S4"
    "SARS-CoV-like" "SARS-NC" "SARS-NC-CHO" "SARS-antisense" "SARS-like" "SC-2084" "SD6-escape"
    "SD6-resistant" "SDS2.1" "SEQ96" "SIVmac239" "SIVsmmH4" "SK-4200" "SN-titre" "SN-titres"
    "SNPs_all" "SP6SARS" "SPF-pigs" "SPUsp45" "SPusp45" "STAT-pathway" "SV-MWLMV" "SW28" "SWy-2"
    "SZ3" "Sec12p" "Sec13p" "Sec16p" "Sec23p" "Sec24p" "Sec31p" "Self-regulation" "Semi-thin"
    "Set-up" "Shapiro-Wilk" "Sigma-Aldrich" "Sino1-11" "Sn=TPTP+FN" "South-North" "Sp1-like"
    "Sp=TPTP+FP" "Spearman-Karber" "SplitsTree4" "State-transition" "Stoon-1010"
    "Streptavidin-ALP-PQ" "Student-T" "Sub-sequences" "Synonymous" "Sγ" "T-2" "T-3" "T-CL"
    "T-helper" "T2" "T29" "T7-like" "TATGTC-3" "TBE-Urea-PAGE" "TBq" "TC-3" "TC-preparation"
    "TC-provider" "TCCCCTCAGAACATAACATAGTAATGCGGTAA-GTCGCATAAAAACCATTC" "TCGGTCAGTGG-3" "TCID50"
    "TCM1" "TES-Lys" "TGAAAATTCCCCTAATTCGATGA-GGTCGGCGCATAGCTGATAACAAT" "TGF-beta-TβRII_Complex"
    "TH1and" "TNF-β" "TT-virus" "TTAAGTCCAAGAACATTAAATGC-3" "TTACAAACTTGTGTCC-3" "TTCTGTC-3"
    "TTGGGTTGCGAAAGG-ROX" "TTGGTAGCC-3" "Tamura-Nei" "TaqI-F" "Technical" "Telechem-Arrayit"
    "Terminator" "Test-sequences" "Tet-off" "Th2-like" "Thirty-five" "Thirty-four" "Tien-YJ"
    "Tricolor-conjugated" "Tris-Cl" "Tris-HCl" "Triton-X100" "Tween-20" "Twenty-eight"
    "Twenty-first" "Twenty-five" "Twenty-four" "Two-fold" "Two-way" "TβRI" "TβRII" "U-21660" "U122"
    "U13424" "U13448" "U13451" "U13464" "U19383→C" "U274" "U274mut1" "U59" "UAAGU" "UAGAUGU"
    "UDG-treatment" "US$2" "US$3,000" "US$766–US$3,035" "UU" "UUCAU" "UUCGUGUUCGCUCUACUGCUU"
    "UV-Vis" "Uni-form" "V-like" "V1" "V1V2" "V1V2DF" "V1V2DR" "V1–V2" "V2" "V3" "VB-G05" "VI-A-10"
    "VICTOR-2TM" "VIV2" "VP16" "VP3-VP1-2A-coding" "VR1520" "VR544" "VSV-G" "VTF7.3" "VZ=⌊D02−D"
    "Virus" "Viscous-only" "Vmw65" "Vn+1" "WN53" "WN83" "Watson–Crick" "Watson–Crick-type" "Web"
    "Web-based" "White" "Whole-genome" "Wi-Fi" "Wimley-White" "Win32" "Wiskott-Aldrich"
    "Within-transcript" "Wright–Fisher" "X04615" "X14307" "X4" "X=A" "YM-10" "YM-100" "YM10" "YN00"
    "YP_089649" "YP_138545" "Yahoo!" "Yeargin-Allsop" "Z-curve-based" "ZCURVE_CoV" "ZCURVE_V"
    "ZJ01" "Zero-Order" "Zero-order" "Zymed" "a+c+" "abc+" "above-described" "above-mentioned"
    "acid-based" "actions" "acute-phase" "acute-stage" "ad-supported" "adaptor-ligated"
    "added-value" "ade2–1" "adeno-associated" "after-action" "age-matched" "agreed-upon" "ai+ci"
    "ai+gi" "ai+ti" "air-blood" "alignment-independent" "alkaline-phosphatase" "all-in-one"
    "all-or-nothing" "all_discriminating_sets" "alpha-melanocyte-stimulating"
    "already-characterized" "amino-acid" "amino-modified" "amino-terminal" "aminoallyl-dUTP"
    "amplicon+enzyme" "and-Ning" "animal-to-animal" "animal-to-human" "anterior-posterior"
    "antro-coanal" "appetite-regulation" "applications" "association-mapping" "at-risk"
    "atomic-resolution" "auto-PEEP" "autophagosome-like" "a–b" "back-slab"
    "bacteriologically-confirmed" "base-pairing" "base–base" "base–sugar" "bed-capacity"
    "bed-utilization" "beliefs" "bench-top" "best-case" "best-fit" "best-performing"
    "better-defined" "between-city" "between-host" "between-run" "bi-phosphate" "bio-computing"
    "birth-and-death" "birth–death" "bisectionally-distributed" "black-tar"
    "blood-monocyte-derived" "body-TRS" "bottom-up" "bp-56,248" "branch-chain" "broad-based"
    "broad-host-range" "broad-spectrum" "bullseye-type" "buy-in" "by-product" "b–c" "c4872–c5093"
    "can1–100" "cap-1" "capacitance" "carbon-containing" "carbon–carbon" "carboxy-terminal"
    "carboxyl-terminal" "carry-over" "case-by-case" "case-contact" "case-control" "case-fatality"
    "case-payment" "catch-up" "cauliflower-like" "caveolae" "cell-based" "cell-type-dependent"
    "cells" "center-to-center" "character_haplotypes" "charge-coupled-camera" "chi-square"
    "chip-based" "chorio-allantoic" "chronic-relapsing" "ci+ti" "cis-acting"
    "citrate-bicarbonate-dithionate" "class-responsibility" "clean-up" "clinical-grade"
    "codon-position-dependent" "coiled-coil" "collaborators…and" "column-based" "commonly-accepted"
    "commonly-used" "communication-recovery" "communicative-skill" "community-based"
    "community-health" "concentration1" "conditional-lethal" "condom-promotion"
    "conformation-linked" "consequence-phase" "contexts" "cost-effective" "cost-effectiveness"
    "cross-border" "cross-checking" "cross-contamination" "cross-hybridization" "cross-hybridizing"
    "cross-infection" "cross-protection" "cross-reactivity" "cross-reacts" "cross-referenced"
    "cross-rotation" "cross-section" "cross-species" "cross-strain" "cross-transcript"
    "culture-based" "cumulus-oocyte" "cytosine-rich" "c–d" "dN-dS" "dN-dS>0" "dS>dN"
    "data-coordinating" "day-to-day" "decision-makers" "delayed-onset" "desk-top"
    "diagnosis-related" "direct-sum" "dis" "discipline-specific" "discontinuous-extension"
    "distinguish-with" "distinguishing-score" "dn" "dna_rm" "dose-dependant" "dose-dependency"
    "dose-ranging" "dose-response" "double-infected" "double-lock" "double-membrane"
    "double-membraned" "double-pseudoknot" "double-rolling-circle" "double-strand-specific"
    "draw-back" "droplet-spread" "ds" "dsRNA-exposure" "dual-color" "dual-use" "dual-wavelength"
    "e-book" "e-mail" "e-value" "early-warning" "east–west" "emotional-competence"
    "emotional-skill" "end-expiratory" "end-piece" "end-products" "end-stage" "end-to-end"
    "end-user" "end-users" "epitope139-152" "equilibrium-binding" "error-and-trial" "event-based"
    "evidence-based" "exon-exon" "experiment-based" "experimentally-determined" "externally-added"
    "e−γt" "face-to-face" "faculty-development" "faculty-selection" "family-care" "fast-breaking"
    "fdseq1" "fed-back" "feed-back" "fer-de-lance" "field-effect" "file1" "fine-tune"
    "first-generation" "first-line" "first-order" "first-responder" "first-response" "first-strand"
    "fixation-permeabilization" "flat-bottomed" "flip-back" "flu-like" "fluorescence-conjugated"
    "focus-forming" "follow-on" "follow-up" "food-grade" "food-insecurity" "foot-and-mouth"
    "foot-print" "four-color" "four-level" "four-marker" "freeze-substituted" "freeze-thaw"
    "freeze-thawed" "front-line" "full-genome" "full-genome-length" "full-sequence" "full-text"
    "full-time" "g-POCT" "gel-based" "gene-based" "gene-product" "gene-sequence" "gene-sequences"
    "gene-stability" "general-time-reversible" "genetically-determined" "gene–environment"
    "genome_groups" "geo-data" "geodata-rich" "geographically-as" "geospatial–temporal" "geq"
    "gi+ci" "gi+ti" "globalisation-induced" "glutaraldehyde-0.05%"
    "glyceraldehyde-3P-dehydrogenase" "good-quality" "google-earth" "groEL" "ground-glass"
    "group-level" "gut-associated" "hACE-2" "halo-like" "haplotypessCnumber_combinations_to_test"
    "health-action" "health-care" "health-enhancement" "health-promotion" "health-status"
    "healthy-looking" "heat-killed" "heat-shock" "heavy-chain" "heavy-handed" "helix-3" "help-desk"
    "high-affinity" "high-density" "high-dimensional" "high-dose" "high-efficiency" "high-income"
    "high-intensity" "high-level" "high-output" "high-pressure" "high-profile" "high-quality"
    "high-resolution" "high-risk" "high-speed" "higher-education" "higher-level" "higher-order"
    "higher-ordered" "hinge-like" "homo-dimers" "hospitals" "host-country" "host-language"
    "host-pathogen" "host-society" "host-to-host" "http" "human-to-human" "humanistic-values"
    "hybridisation-based" "hyper-innate" "hyper-reactivity" "hypercapnia" "hyperoxia-induced"
    "hypothesis-generating" "hypoxemia" "i<j<k" "i=1,2,3." "iNOS-mRNA" "icSARS-CoV"
    "illness-prevention" "image-plate" "immediate-early" "immigrants" "immune-mediated"
    "immune-sensitised" "immuno-functional" "impedance" "in-depth" "in-frame" "in-house"
    "in-patient" "in-patients" "in-person" "in-solution" "incidents" "individual-based"
    "individual-level" "individual-patient" "infection-synthesized" "infections" "inhibitor-κB"
    "integrin-interacting" "inter-animal" "inter-connecting" "inter-domain" "inter-quartile"
    "inter-sibling" "inter-survey" "inter-tissue" "internet-based" "intra-animal" "intra-culture"
    "intra-host" "intra-molecular" "intra-peritoneally" "intra-venously" "iom" "isolate-level"
    "j<k<i" "jack-knife" "jump-return" "juxta-localized" "k
3"
    "k-l" "k-nearest-neighbour" "ketone-treated-trypsin" "kissing-loop" "kml+xml" "knowledge-based"
    "kobs" "large-genome" "large-scale" "latency-associated" "lead-time" "leader-TRS"
    "leptin-agonist" "leu2–3,112" "level-3" "life-cycle" "life-style" "life-style-linked"
    "ligand-receptor" "ligands" "like-minded" "limited-access" "limitin" "lipid–RNA"
    "live-attenuated" "live-virus" "location-based" "log-transformed" "log10-transformation"
    "log10TCID50" "log2Y" "log4" "loge-transformed" "long-and" "long-established" "long-lived"
    "long-range" "longer-lasting" "longer-term" "loop–stem" "low-affinity" "low-cost" "low-density"
    "low-fidelity" "low-income" "low-level" "low-melt" "low-molecular-weight" "low-pH"
    "low-passage" "low-temperature" "mAb" "mAb-escape" "mCXCR2" "mN2" "mN3" "macro-level"
    "macrophages" "mak8–1" "male-to-female" "managed-care" "many-fold" "marker-containing"
    "max_amplicon_length" "mean-centered" "medical-consultation" "medical-injection"
    "medical-school" "medical-treatment" "melt-curve" "meningo-encephalitis" "mental-health"
    "mental-health-care" "meta-analyses" "micro-environment" "micro-scale" "microarray-based"
    "micron-size" "mid-April" "mid-lower" "mid-values" "middle-income" "migrant-community"
    "migrant-health" "migrant-health-care" "migrant-patient" "mild-to-moderate"
    "min_len_downstream" "min_len_upstream" "mind-the" "mineral-bound" "mineral-sorbed"
    "mini-ethnography" "minus-strand" "mixed-cultural" "mock-infected" "mock-infecting"
    "mock-transfected" "monocytes" "montanide" "months-3" "mosm" "multi-analyte" "multi-causality"
    "multi-cellular" "multi-component" "multi-detection" "multi-dimensionally" "multi-locus"
    "multi-nature" "multi-organ" "multi-position" "multi-purpose" "multi-source" "multi-step"
    "multiple-comparison" "multiple-membrane" "multiple-membrane-spanning" "multiple-sequence"
    "myc-3amut1" "n-dimensional" "nano-devices" "nano-miniaturization" "nation-state" "near-zero"
    "negative-sense" "negative-strand" "negative-stranded" "neuro-transmitter" "new-onset"
    "newly-infected" "next-highest" "next-to-lowest" "nisin-inducible" "nm≅" "no-peptide"
    "no-template" "northwest–southeast" "northwest–southwest" "nsp12–16" "nsp12–nsp16"
    "num_restriction_enzymes" "number_combinations_to_test" "nγ" "n→∞" "object-orientation"
    "off-chip" "oil-based" "oligo-dT25" "oligoadenylate-dependent" "omega-like" "on-call"
    "on-column" "on-going" "on-side" "on-site" "one-dimensional" "one-fifth" "one-half" "one-set"
    "one-step" "one-tail" "one-tailed" "one-tenth" "one-third" "one-way" "only-protein"
    "open-ended" "open-source" "optical-based" "org" "origin-and-destination" "ostio-meatal"
    "out-dated" "out-of-country" "out-of-frame" "out-patient" "out-patients" "out-sample"
    "outcome-based" "outcomes" "over-annotation" "over-prediction" "over-predictions"
    "over-predicts" "over-representation" "over-rule" "over-the-counter" "p2luc" "p2luci" "p416ADH"
    "pAdApt-Ebola" "pBR322" "pBR322-based" "pCDNA3-ACE2-ecto" "pCMV-tPA" "pCMVΔR8.2" "pCR4-TOPO"
    "pCa37" "pEF6" "pEF6-Myc" "pEF6-NC" "pEGFP-C3" "pGEX-4T-1" "pH8.0" "pHIT111" "pJD435" "pJD464"
    "pJD465" "pJD466" "pJD467" "pJD469" "pJD474" "pJD479" "pJD480" "pJD487" "pJD488" "pJD490"
    "pJD491" "pJD492" "pJD502" "pJD503" "pJD504" "pJD506" "pJD536" "pJD537" "pJD538" "pJD539"
    "pJD540" "pJD541" "pJD542" "pJD544" "pJD545" "pJD567" "pMal-GroEL" "pMark-S" "pMark-S."
    "pQE-Tri" "pSEC" "pSV2pac" "pSecTag2" "pUC18" "pUC19" "pVAX-1" "pXJ40-3a" "pXJmyc-3a"
    "pXJmyc-3amut1" "pXJmyc-GST" "pack-years" "pair-π" "pairwise-alignment" "papain-like"
    "paper-based" "pare_groups" "parent-child" "part-time" "partnership-based" "password-protected"
    "pathogen-specific" "patient-care" "patient-ventilator" "pattern-based" "pattern-recognition"
    "pcDNA3-XIAP" "pcDNA3A" "peace-time" "peak-SARS" "peer-based" "pepper-containing" "per-case"
    "person-to-person" "person-to-person-contact" "person-years" "perspective-both" "phage-like"
    "phase-specific" "phenol-chloroform" "photo-bleach" "physio-chemical" "pico-scale"
    "pin-prick-sized" "place-specific" "plaque-forming" "plaque-forming-units" "plaque-purified"
    "plaque-reduction" "plate-to-plate" "plus-sense" "plus-strand" "plus-stranded" "pmak8–1"
    "pneumonia-like" "point-of-care" "population-based" "pore-size" "positions1-2"
    "positive-pressure" "positive-sense" "positive-strand" "positive-stranded" "post-11" "post-PCR"
    "post-SARS" "post-antibiotic" "post-classroom" "post-graduate" "post-infection"
    "post-infectious" "post-inoculation" "post-intervention" "post-migration" "post-mortem"
    "post-test" "post-transcriptional" "post-transfection" "post-treatment" "post-vaccination"
    "post–11" "present-day" "previously-described" "primer-CAS" "primer-dimer" "primer-dimers"
    "primer3" "priority-setting" "pro-TNF" "pro-spike" "proMED-mail" "proS-Golgi" "probe-based"
    "program-based" "promoter-region" "proofreading-repair" "protease–substrate" "protein-10"
    "protein-C" "protein-RNA" "protein-ligand" "protein-lipid" "protein-only" "protein-resin"
    "provider-patient" "public-health" "publicly-funded" "pulse-periods" "pΔTM" "quasi-randomly"
    "rAd" "rAd5-Ebola" "rN1" "rRNA>GAPDH" "rRNA>S20>GAPDH" "raccoon-dog" "raft-associated"
    "random-primed" "re-analysed" "re-analysis" "re-analyzed" "re-emergence" "re-emerging"
    "re-form" "ready-to-use" "real-life" "receiving-country" "recommendations" "referrals"
    "refugees" "relapsing-remitting" "relationship-building" "reno-vascular" "repSZ-1" "repSZ-3"
    "replicase-transcriptase" "replicase–transcriptase" "requirement-gathering"
    "reverse-engineering" "reverse-phase" "reverse-transcribed" "reverse-transcribes" "revertant"
    "rhACE2" "rheostat-controlled" "rhino-pathologies" "right-upper" "rotating-anode" "s=Serum"
    "sCEACAM1a" "sGP" "sample-collecting" "sample-to-answer" "sample-to-sample" "scale-down"
    "scenario-specific" "second-order" "self-call" "self-care" "self-checks" "self-cleaves"
    "self-contradictory" "self-disclosure" "self-evaluations" "self-extension" "self-injection"
    "self-limiting" "self-primed" "self-protection" "self-regulating" "self-regulation"
    "self-reliance" "self-reports" "self-serving" "self-splicing" "self-stimulating"
    "self-sufficient" "self-sustaining" "semi-conserved" "sepsis-induced" "sequence-based"
    "sequence-binding" "sequence-diversity" "sequence-spaces" "sequence-specificity"
    "sero-epidemiological" "service-learning" "set-up" "setting-ups" "seven-category" "seven-step"
    "sgRNA3" "short-term" "shortgagF1" "side-chains" "sign-up" "signal-to-noise"
    "silicon-technology" "sim_anneal_results_summary" "single-base" "single-case" "single-chain"
    "single-color" "single-cycle" "single-exon" "single-genome-length" "single-membraned"
    "single-modality" "single-source" "single-strand" "six-helix" "size-fractionated"
    "size-independent" "skill-deficit" "small-group" "smear-positive" "smooth-walled" "snap-frozen"
    "so-called" "social-change" "social-context" "socio-economic" "socio-economically" "soil-bound"
    "solid-phase" "sorption-desorption" "south-east" "speech-simplification" "spin-column"
    "stand-alone" "state-and" "statistics-based" "steady-state" "stem-loop" "stem–loop"
    "stop-valve" "streptavidin-biotin" "streptavidin-conjugated-HRP" "study-cohort" "sub-Saharan"
    "sub-class" "sub-domains" "sub-groupings" "sub-periods" "sub-sequence" "sub-sequences"
    "subgenome-length" "substitutions" "sum-normalized" "super-cube" "super-epoxi-coated"
    "super-epoxy-coated" "supernatant" "surface-area" "susceptible–exposed–infectious–recovered"
    "susceptible–infectious–recovered" "sustainability-of" "systems" "t*−t" "t>t" "take-off"
    "target-to-background" "team-based" "team-members" "tegument-like" "temperature-sensitive"
    "template-switching" "test-sequence" "test-sequences" "therapies" "thin-section" "think-aloud"
    "think-model" "third-culture" "third-party" "three-dimensional" "three-fifths"
    "three-helix-containing" "three-locus" "three-member" "three-phase" "three-stemmed" "three-way"
    "time-course" "time-frame" "time-point" "time-points" "time-series" "time-space"
    "time-to-event" "top-down" "trade-off" "trans-Golgi" "trans-activate" "trans-activates"
    "trans-border" "trans-complement" "trans-membrane" "trans-shipment" "trans-α"
    "transcription-PCR" "transcription-polymerase" "transcription–polymerase" "transition-state"
    "transmembrane-deleted" "transmission-blocking" "transnational-competence" "tree-building"
    "tree-structure" "tri-group" "tri-groups" "tri-peptide" "trial-and-error" "triple-helix"
    "triple-layer" "trophoblast-specific" "trp1δ" "trp1–1" "ts18" "ts19" "ts3" "ts329" "ts36"
    "ts38" "ts8" "ts88" "ts9" "two-component" "two-culture" "two-dimensional" "two-sample"
    "two-set" "two-sided" "two-stage" "two-stem" "two-stemmed" "two-step" "two-steps" "two-tailed"
    "two-thirds" "two-tier" "two-way" "type-1" "type-2" "t≤t" "u1" "u11=y12A" "u12=z12A" "u13=x12C"
    "u14=y12C" "u15=z12C" "u16=x12G" "u17=y12G" "u18=z12G" "u19=x12T" "u1o−u33o" "u2" "u20=y12T"
    "u21=z12T" "u23=y23A" "u24=z23A" "u25=x23C" "u26=y23C" "u27=z23C" "u28=x23G" "u29=y23G" "u2=y1"
    "u30=z23G" "u31=x23T" "u32=y23T" "u33=z23T" "u3=z1" "u4=x2" "u5=y2" "u6=z2" "u7=x3" "u8=y3"
    "u9=z3" "ug" "uk" "ul" "ultra-thin" "under-estimation" "under-glycosylated" "under-predicts"
    "under-produced" "under-representation" "unequal-variance" "unit-vector" "units" "up-shift"
    "up-to-date" "ura3–1" "ura3–52" "uracil–adenine" "us-against-them" "user-friendly"
    "user-selected" "users" "vaccination-challenge" "value-based" "variable-region" "vector-NC"
    "vector-expressed" "ventilation-perfusion" "ventilator-induced" "vira!" "viral-like" "virus-6"
    "virus-RPV" "virus-based" "virus-like" "viruses2" "viscous-only" "vnd" "w1w2" "w2w3" "war-zone"
    "water-bath" "water-nucleobase" "web-based" "well-characterized" "well-defined" "well-designed"
    "well-documented" "well-established" "well-fitted" "well-publicized" "well-recognized"
    "well-served" "well-structured" "well-studied" "white-noise" "whole-genome" "whole-genomes"
    "whole-killed" "wide-spectrum" "wide-spread" "within-host" "within-slide" "wm-1"
    "wound-botulism" "www" "y-axis" "y-intercept" "yaba-like" "yeast-based" "z-score" "z-scores"
    "zero-frame" "zi∈" "{France}" "{u10=x12A" "{u1=x1" "{u22=x23A" "×1000" "×400" "˜1,000" "Δ-ln"
    "Δ1" "Δ2" "Δ3" "ΔCT" "ΔG" "ΔS3" "ΔTM" "ΔΔCT" "α-carbon" "α-trans-inducing" "β-sheet"
    "β-sheet-forming" "β-sheets" "β0" "β0
N"
    "β1" "β2" "βR" "βs" "γ1" "γ2" "κB" "κB-sequence" "κB-site" "μCi" "μL" "μg" "μgprotein" "μl"
    "μmol" "νA" "νB" "τ1" "τ1+τ2+τ3" "τ2" "τ3" "τD" "τQ" "τmix" "τs" "χ2" "∑ji|F"))

