
(IN-PACKAGE :SP)
(DEFPARAMETER |*NS-RD-covid-2020-04-03-0403-COM-PMC-901-1000*|
  '("6×His" "<0.05" "<0.1" "<0.1%" "<0.3" "<0·05" "<1" "<1000" "<12" "<18" "<2-months" "<2.5"
    "<3.2" "<4%" "<5" "<50" "<5000" "<5years" "<6" "<65%" "<67%" "<7%" "<75%" "<90%" "<S"
    "=∑kkIk∑ll" ">0.1%" ">1" ">10" ">102°F" ">11" ">11,000" ">1300" ">16-hours" ">16-hrs" ">1∶80"
    ">2-fold" ">2.0" ">20" ">200" ">25-fold" ">3" ">30" ">39°C" ">4" ">40" ">5" ">5-fold" ">50"
    ">50%" ">6" ">6-months" ">70%" ">75%" ">80%" ">80°C" ">9" ">90%" ">900" ">94%" ">97%" ">98%"
    ">99%" ">>" ">ACCTGCCCAGTGTGCGTGAG<3" ">TGGTGGGGACTGAG" "A&B" "A&E" "A-1" "A-375" "A-6" "A-B"
    "A-C" "A-HA" "A-T" "A-T-G" "A-Tailing" "A-ended" "A1" "A13P" "A193T" "A1B" "A2" "A2-like"
    "A2-type" "A27L" "A5" "A98P" "AA975560.1" "AB256671-AB256678" "AB259709-AB259716" "ABI3130"
    "ABSL-4" "ACACAC-3" "ACAP27" "AEFM01000000" "AF-liposome" "AF-liposomes" "AF264042" "AF495467"
    "AFHSC-GEIS" "AFSHC-GEIS" "AIDS-related" "AIV" "AJ318512" "AJ457137" "AJ865337" "AJ865341"
    "AMBER-03" "AMC" "AP33" "APC-Cy7" "APMV-1" "APMV-1-specific" "APMV-2" "APMV-2-infected"
    "APMV-3" "APMV-4" "APMV-5" "APMV-6" "APMV-7" "APMV-8" "APMV-9" "APOM1" "APOM5" "APOM5-G"
    "APOM5-T" "ARK99" "ASGP-R" "ASGP-R-independent" "ASGP-R-mediated" "ATCC-CCL33" "ATCC9372"
    "AY043312" "AY078417" "AY078417.1" "AY296746" "AY372123" "AY427818" "AY561713" "AY622943"
    "AY846750" "AZT-RV" "Above-mentioned" "AdV" "Adad-apla-iddina" "Additionally" "AgPath-ID"
    "Aim-2" "Aim-3" "Aim-4" "Alamos" "Alberta" "Alexa-488" "Alexa-594" "Alexa-pDNA" "Alexa594"
    "Alexa633-labeled" "Almost-daily" "Amylmetacresol" "Anal" "April-July" "April–May" "Arg16"
    "Arg36→His36" "Arm53b" "Asian-Indian" "Aspo0F" "Assembly" "August-October" "Az150" "Azi}"
    "Aβ42" "B." "B.E" "B.V." "BACI051" "BACI051-E" "BACI051-N" "BALB" "BALB-c" "BD-FACS"
    "BD-Pharmingen" "BDCA3" "BFLA-1" "BFLA1" "BHK21" "BI757556" "BIAcore®3000" "BL13W1" "BMB171"
    "BPV1" "BRC1" "BSL-3" "BSL3" "Bacteria" "Bacto-agar" "BafA1" "Bakpak6" "Balb" "Best-fit"
    "Bio-HepB" "Bio-Plex" "Bio-Rad" "Bio-imaging" "Bioinformatics" "BlaM1" "Bland-Altman" "Blast"
    "Brandenburg" "Brennan-Benson" "BrevigMission" "Brisbane" "Brittain-Long" "Broncho-pneumonia"
    "Bt-CoV" "B–C" "C+1871A" "C+G" "C-1065A" "C-C-G" "C-G" "C-T-T" "C-terminally" "C1576–C1910"
    "C3" "C3%" "C3+G3" "CA-CB-CG-CD2" "CA-STAT5b" "CA-STAT5bER" "CAdV-2" "CB6F1" "CBB-G250"
    "CBB-stained" "CC50" "CCANNNNN" "CCC-3" "CCF-2" "CCF2-AM" "CCL-10" "CCL-121" "CCL-185" "CCL-33"
    "CCl4-induced" "CD11b+CD11c−macrophages" "CD11ccre" "CD19cre" "CD27pos" "CD3negCD19posCD27pos"
    "CD3negCD19posCD27possIgGpos" "CD40L-L" "CD4cre" "CD8-4" "CFI>0.90" "CFP-E1" "CFP-E2+YFP-E1"
    "CFP-E2TM" "CFP-EYF" "CFP-p7" "CFP-p7+YFP-NS2" "CGACAACGAGCTCCTCATCT-3" "CITES" "CL-4B"
    "CLIK148" "CMV-R-Cali-04-09" "COX-2-down" "COX-2-nest" "COX-2-up" "CQ08" "CQ8" "CR6261"
    "CRL-11147" "CRL-11268" "CRL-1424" "CRL-1573" "CRL-1593.2" "CRL-1619" "CRL-1675" "CS50" "CU-LM"
    "CU-LM1973" "CU-LM1983" "CU-LM1984" "CY062545-52" "CY062553-60" "CY062561-68" "Ca-074"
    "Ca2+-signaling" "CaCl2" "Calcein-based" "Caledonia" "Cantonese-speaking" "Captive-bred"
    "Cat#22-230-900" "Cergy-Pontoise" "Cesena-Forli" "Chicken" "Child-Pugh" "Chongqing" "Ci" "Cl13"
    "Clean-Up" "Clean-up" "Cochran-Armitage" "Combivir" "Community-based" "Concern" "Crandell-Rees"
    "Crl" "Cross-reactivity" "Ct-method" "Cullin-based" "Current_Scientific_Issues" "Cy2"
    "Cy3-Streptovidin" "CyDs" "Cytofix" "Cytoperm" "Cytotoxicity" "Cα" "C–F" "D-HA" "D-MEM"
    "D-cell" "D.G." "D0" "D1" "D1D2" "D1–D4" "D2" "D3" "D4" "DBL1X" "DBL1X-3D7" "DBL1x-6ε" "DBL2X"
    "DBL3X" "DBL3X-HB3" "DBL3X-VAR2CSA" "DBL3γ" "DBL3γ-VAR1-FCR3" "DBL3γVAR1" "DBL4ε-3D7"
    "DBL4ε-FCR3" "DBL5ε" "DBL6x" "DBL6ε" "DDBJ" "DF-1" "DFNB3" "DFNB31" "DH5α" "DLPC-liposome"
    "DM-β-CyD" "DM1A" "DMEM+10%" "DNA+RNA" "DNA-protein" "DNM3B" "DNMTs-b" "DP70" "DQ000495"
    "DQ160004" "DQ335247" "DQ397521" "DQ679420" "DQ834384" "DYNA-DEP" "DYNA-IND" "Day-21"
    "December-March" "December–February" "Degree-based" "Deinococcus-Thermus" "Detected-Recovered"
    "Detrick-1" "Detrick-2" "Detrick-2exhibited" "Detrick-3" "Detriment" "Di2" "Directive-2"
    "Disease-9" "DoD-GEIS" "Double-barreled" "Dr" "Dual-Luciferase" "Duck" "Duffy-binding-like"
    "E-values<0.01" "E.U." "E0.5" "E1" "E11.5–E12.5" "E13.5–E14.5" "E14.5–E17.5" "E15.5–E16.5"
    "E1E2-p7-NS2" "E1E2p7NS2" "E2-p7" "E3-80" "E7aa49-57" "EBPα-C" "EBPζ" "EBY100" "EBY1001" "EC50"
    "ED-W187A" "EG&G" "EID50" "ELS-8000" "EMBL" "ENC-plot" "ENC-plots" "ENSRNOG00000028597"
    "ENST00000375916" "ENVA" "ER-Serie" "ER-like" "ER-to-Golgi" "ER0100" "ESE-Quant" "EU-FP6"
    "EU-INCO" "EU310373" "EU790642" "EU918736" "EV71" "EYF-Flag" "EZ1" "Eastern" "Editor-in-Chief"
    "Eighty-five" "Eighty-percent" "Emilia–Romagna" "Ensembl-ENST00000375916"
    "Ensembl-ENST00000375918" "Ensembl-ENST00000375920" "Environment" "Equipment-free"
    "Erdös-Rényi" "Esp15-DN" "Eurasian" "F-statistics" "F0" "F1" "F122" "F1×LEW" "FACS-based"
    "FC500" "FCR3-IE" "FCS+p" "FFMM94" "FINAL_CONCEPT_NOTE_Hanoi" "FIV-GP64-ntLacZ"
    "FIV-L260F-ntLacZ" "FIV-VSV-G." "FJ170278" "FL2000" "FP6" "FRET-FLIM" "FV2" "FV300-BXCarl"
    "FZB42" "Farm-1" "Farm-2" "FastPrep-24" "Fcα" "FcαR" "Fcγ" "FcεRI" "February-April"
    "Ficoll-isopaque" "Fifty-eightnucleotide" "Fifty-one" "Five-week-old" "Follow-up"
    "Food-and-Mouth" "Forty-eight" "Forty-one" "Forty-six" "Four-primer" "Four-week-old" "FuGENE6"
    "G+1837T" "G+203A" "G+C" "G-C" "G-sepharose" "G1" "G1-like" "G18-145"
    "GACAGGTAGGTGTCTATGAGGC-3" "GATCGTTGGGAACTACATCCGAG-3" "GBT23197-2008" "GBoV1" "GC3s"
    "GE-Healthcare" "GGA-3" "GMO-UN-A100" "GP-C" "GP64" "GQ258305" "GQ258327" "GQ265940" "GQ265943"
    "GQ265944" "GQ387499" "GQ387500" "GQ867667" "GSE23955" "GST-3CLp" "GST-IRF3131–426"
    "GST-fusion" "GTC-3" "GTR+I+Γ" "GU471793-GU471805" "GU471864-GU471897" "GU902971" "GZ02" "Gal"
    "Galacto-Light" "Galβ1" "Galβ1–3GalNAc" "Galβ1–3GlcNAc" "Galβ1–4" "Galβ1–4GlcNAc" "GenBank"
    "GeneAmp9700" "Gent" "Gini-Simpson" "GlcNAcβ" "Gln-P1" "Gly16" "Gr1+" "Gray-type" "GuSCN-based"
    "Guillain-Barre" "GxxxG-like" "H&E" "H-1" "H-2Db" "H-2Kb" "H1" "H1-H16" "H1-subtype" "H101Rand"
    "H10N3" "H1N1-positive" "H1N1pdm" "H1N1were" "H1N2" "H1N2-subtype" "H1N3" "H2" "H2K20" "H2K5"
    "H2O." "H2SO4" "H3" "H37Ra" "H37Rv" "H3N6" "H3N8" "H4N2" "H4N9" "H5" "H6N1" "H6N1-subtype" "H7"
    "H7N1" "H7N7" "H7N9" "H9" "H9-subtype" "H9N2" "H9N2-subtype" "H?N9" "HA-NS2" "HA-NS2-GFP"
    "HA-NS2-GTM" "HA1-For" "HA1-HA2" "HA11" "HA2-For" "HA2-based" "HA98,153,155,183,190" "HB-65"
    "HBoV1" "HBoV1-4" "HBoV2" "HBoV3" "HBoV4" "HDL-C" "HEK293T-mCEACAM-1" "HEK293T-mCEACAM1"
    "HEPES-KOH" "HIT3a" "HK$10,000" "HK$100–150" "HK$100–200" "HK-39" "HKL-2000" "HKL2000"
    "HLA-A*0201" "HLA-A*1101" "HLA-A2" "HLA-B27" "HLA-G1" "HM031135" "HM053672" "HM053673"
    "HM053693" "HM053694" "HM145750" "HM623207-HM623277" "HM623754" "HM74039" "HM747056" "HN08"
    "HN08-type" "HP-CyDs" "HP-α-CyD" "HP-β-CyD" "HP-γ-CyD" "HP-γ-CyDs" "HPIV-2" "HPV-16"
    "HQ291308-HQ291309" "HQ291310-HQ291343" "HQ336973–HQ336976" "HQ845737" "HQ845738" "HRSV-A"
    "HRSV-B" "HRSV-B." "HRV-A" "HRV-B" "HRV-B." "HRV-C" "HRV-C-like" "HRV-Cc" "HRV-D" "HSV-1"
    "HSV-2" "HTB-30" "HTB-68" "HTB-72" "HXB2" "HY2" "HY52" "Hank’s" "Hardy-Weinberg" "Hauke-type"
    "HbA1c" "High-Five" "High-confidence" "High-shedders" "High-speed" "His-tag" "His41-Cys145"
    "HmN-2" "Hoffman-LaRoche" "Hokkaido" "Holm-Sidak" "Home" "Hong-Kong" "HongKong" "Hospital"
    "Hs00191900_m1" "Hs03928985_g1" "Hs_P2RX7_1" "Hs_P2RX7_2" "Huh7" "Huriet-Sérusclat"
    "Hybond-ECL" "H}" "Hα" "I+EP" "I-TASSER" "I-like" "I=1n∑x" "IAF-404" "IAV-WSN"
    "IBV-Massachusetts" "IBVSX4" "ICD-10" "ICD-9" "IFN-antagonism" "IFN-β+" "IFN-βfloxβ-luc"
    "IFN-βΔβ-luc" "IFNW-like" "IFNα-2b" "IIH6" "IL-XPCI" "IPA3" "IQ5" "IRDye700DX" "ISO-15189"
    "IT-23" "IU" "IVIS-200" "IX71" "Ig-like" "Ik−kIk" "Il∝k" "Il∝kl" "Imipenem" "InfA&B"
    "Information-dependent" "International" "Internet-based" "Intervet-Schering" "Italy-02"
    "I˙=τpIθg" "I˙a=Sa" "I˙k=τ" "Iκ" "IκIλ" "IκIλ˙" "IκRλ" "IκRλ˙" "Iκ˙" "I→SκIλ" "I→SκRλ" "I→SλIκ"
    "J-F" "J.A" "J00–J06" "J00–J99" "J02275" "J18" "J30–J39" "J40–J47" "J6" "JF05-1C2"
    "JF414933–JF414936" "JFH-3BS" "JFH-A41-HA" "JFH-HA-PP" "JFH-RR" "JFH-ΔE1E2-HA" "JFH-ΔE1E2-Luc"
    "JFH-ΔTM12-HA" "JFH-ΔTME2-HA" "JFH-Δp7-HA" "JFH1" "JFHGND-Luc" "JNKp38" "JP9758" "JS"
    "Jean-Luc" "Johannesburg" "June–August" "June–October" "K14cre" "K6" "KDEL-1" "KDEL-2" "KDEL-3"
    "KDEL-4" "KDEL-containing" "KH2PO4" "KHCO3" "KMB17" "Kaila-kona" "Khi2" "Kika-Werke" "Kinetic"
    "Kruskal-Wallis" "Kunitachi" "Kunitz-type" "L-5" "L-DNA-shuffling" "L-arginine-HCl" "L1"
    "L260F." "LC-MS" "LC480" "LCMVNP" "LCQ" "LD-ER" "LD-Plan-Neofluar" "LDL-cholesterol" "LEW"
    "LHM2" "LI-COR" "LILRA1–A6" "LILRA3D1D2" "LJS" "LO28" "LOC100130866" "LOT-R" "LSM-410" "LSM510"
    "LSM710" "LSR-II" "LVPR|GS" "LVPR|SG" "LZ05" "LZ07" "LaSota" "Laboratory-confirmed" "Lac-α-CDE"
    "Leu-to-Gln" "Levallois-Perret" "Li-Ac" "Li-COR" "Li-Cor" "Live-bird" "Low-exponent" "Ly6C"
    "Ly6Chigh" "Lys137-Phe140" "LysM-promoter" "LΩ" "L∶D" "M-5" "M694" "M6941" "MAL-1" "MAL-I"
    "MAL-II" "MALDI-TOF-TOF" "MALs" "MBB-like" "MC1061" "MEGA4" "MHC-B" "MHV-A59" "ML" "MM301"
    "MP90" "MS2F" "MS2R" "MS2probe" "MSI-99" "MSP-2" "MW173P" "MW70,000" "MYO15A" "Macrophage-SFM"
    "Management" "Mann-Whitney" "March-May" "March–April" "Marcy-l" "Mardin-Darby" "Market-1"
    "Market-4" "Market-5" "Market-6" "Mc-Nemar" "Merck" "Michealis-Menten" "Micro-CT" "Micro7"
    "MicroMax007" "Mil-Spec" "Millicell-ERS" "Millipore" "Mini-beadbeater" "Mock-infected"
    "Mock-treated" "Multiple-cycle" "Muscovy" "Muti-Beads" "MyTH4-FERM" "Myo15" "Myo15-mRNA"
    "Myo15sh2" "Myo7ash1" "MyoII-head" "MyoII-tail" "N+1" "N-CA-CB-CG" "N-H" "N-Morpholino"
    "N-ethyl-N-isopropyl" "N-hydroxysulfosuccinimide" "N-liposome" "N-liposomes" "N-morpholino"
    "N-α-9-fluorenylmethyloxycarbonyl" "N1" "N2" "N2D" "N4" "NAMRU-3" "NC_000012" "NC_001539"
    "NC_001540" "NC_001630" "NC_001701" "NC_002488" "NC_003030" "NC_003080" "NC_003092" "NC_004554"
    "NC_004943" "NC_005229" "NC_005951" "NC_006147" "NC_006259" "NC_006347" "NC_006663" "NC_006855"
    "NC_006873" "NC_007274" "NC_007336" "NC_007410" "NC_007414" "NC_007455" "NC_007483" "NC_007515"
    "NC_007608" "NC_007641" "NC_007801" "NC_007901" "NC_012042" "ND-1000" "NDM-1" "NH4C1" "NH4HCO3"
    "NIS-Elements" "NLPR3" "NM_000605" "NNNNTGG" "NRS-356" "NS1-V5" "NS1-host" "NS2-p7" "NS2TM"
    "NS3-4A" "NS5A-positive" "NSTC-7" "NT$1,685" "NT$29.16" "NT$3,212" "NT$61,000" "NU606001"
    "NY-ESO-1" "NYMC" "Na2HPO4" "Naso-pharyngeal" "Nefp24" "Netherland" "Neu5Acα2–3Gal" "Neu5Gc"
    "New" "NewYork" "Ni-chelating" "Nickel-NTA" "Ninety-seven" "Ninety-two" "Nishi-Kobe"
    "North-East" "N−1" "O.C.T." "O.D." "O157" "O2" "O3" "O323" "OD-EC50" "OD1" "OD405" "OD450"
    "OD450nm" "OD492" "OD570" "OD600" "OD600nm" "OD600≈1×107" "ONT" "OR=p11−p1×1−prpr" "ORF1b"
    "One-Step" "One-fourth" "One-step" "Ontario" "Opti-MEM" "P.W." "P.vampyrus" "P1-1" "P1–P6"
    "P2-3" "P3-1" "P3-like" "P<2.2×10−16" "PADRE-expressing" "PALS1-siRNA" "PALS1–siRNA"
    "PAR6-siRNA" "PBS-0.1%" "PBS-0.3%" "PBS-T" "PBS-T." "PBS-solution" "PBS1X" "PBS1X." "PBo-likeV"
    "PBoV1" "PBoV1-H18" "PBoV1-L1" "PBoV1-L2" "PBoV1-R1" "PBoV1-R2" "PBoV2-A6" "PBoV2-G1"
    "PBoV2-G2" "PBoV2-L1" "PBoV2-L2" "PBoV2-R1" "PBoV2-R2" "PBoV3" "PC-based" "PCL-C" "PCO2"
    "PCS-2000-012" "PCV-1" "PCV-2" "PCV-2a" "PCV-2b" "PCV-7" "PCV2" "PE-Cy5" "PE-Cy7" "PEG6000"
    "PHEV-JL09" "PHEV-JLsp09" "PIV3" "PK15" "PKCζ" "PKT" "PL2pro" "PM1-10" "PM10" "PM11-20" "PM2.5"
    "PM20" "PNC100–300" "PNC10–30" "PNC300–1" "PNC30–50" "PNC3–10" "PNC50–100" "PPV4" "PRNT50"
    "PSC100–300" "PSH050513" "PT1" "PT3" "PUR46-MAD" "PXP-HF" "Pair-based" "Pan-Enterovirus"
    "Pastor-Satorras" "Perkin-Elmer" "PfEMP-1" "PfEMP1" "Phase-I" "Phe140-Cys145" "Pierce®BCA"
    "Pirl1" "Platinum" "Plus-The" "Polar-Lipid" "Population-based" "Post-SARS" "Primer3-based"
    "Prism5" "Prisma5" "Prrn" "Puerto" "Px+1" "P˙x" "Q-SiteFinder" "QQ" "QQ-HA" "QT6" "QX-like"
    "QZ1" "QZ2" "QZ3" "Quail" "R&D" "R-AXIS" "R0" "R0=1γ" "R0CM=〈n" "R1" "R1–R4" "R1–R5" "R2"
    "R298A." "R3" "R3–R5" "R4" "R5" "R=34r" "RA3-6B2" "RBP-retinol" "RC-581" "RD114" "RD114-like"
    "REFMAC5" "RH-AF-liposomes" "RH-PE" "RLU" "RM-Bat-CoV" "RM-Bt-CoV" "RM-Bt-CoV-15" "RMPI-1640"
    "RNO10" "RPM-Flu" "RPMI-1640" "RPMI–1640" "RSV-B-N" "RT-PCR-Tao1" "RT-PCR-Tao2" "RT-PCR-YY12"
    "RT-PCR-YY13" "RT-PCR-YY14" "RT-PCR-technique" "RT-buffer" "RT-qPCR" "Rab-10" "Rab-11A"
    "Rab-1A" "Rab-2b" "Rap-2b" "Re-analyses" "Re-isolation" "Refinement" "Refmac5"
    "Reverse-transcription" "Rico" "Roche" "Rosuvastatin" "Rt-PCR" "R∗=n¯Gττ+γZ∞n" "R∞≈f" "S-OIV"
    "S-X" "S." "S.D" "S1" "S1A–D" "S1B-upper" "S1C" "S1D" "S1E" "S1F" "S1R" "S1were" "S1–S6" "S2A"
    "S2A." "S2B" "S3" "S3C" "S3D" "S4" "S5" "S=g" "SARS-CoV-like" "SARS-Rh-BatCoVs" "SARS-like"
    "SARs-like-bat-CoVs" "SAα2" "SAα2-3Gal" "SAα2-6Gal" "SAα2–3Gal" "SAα2–3Galβ1–3" "SAα2–3Galβ1–4"
    "SAα2–3Galβ1–4GalNAc" "SAα2–3Galβ1–4GlcNAcβ" "SAα2–6" "SAα2–6Gal" "SC-6400" "SC1919" "SDS-PAGs"
    "SDS-Polyacrylamide" "SDS-polyacrylamide" "SE600" "SHFV-krc" "SHFV-krc1" "SHFV-krc2"
    "SIR-model" "SJ25C1" "SK-MEL-28" "SMZ1500" "SNA-I" "SO2" "ST6GalI-MDCK" "STAT5b-ER" "STAT5bER"
    "STAT5bER-IRES-GFP" "STAT5bERpos" "SV96" "SZ" "Santa-Cruz" "Saturn944" "Schafer-N" "Sci-B-Vac"
    "September-November" "September–October" "Sequest-based" "Ser-to-Gly" "Ser139-Phe140"
    "Ser139-Phe140-Leu141" "Seventy-two" "Sig" "SigE7LAMP1" "Sigma-Aldrich" "Single-cycle"
    "Sirtuin-3" "Sixty-five" "Sixty-four" "Sixty-one" "Size-dependent" "Size-exclusion"
    "Size-segregated" "Sk+1" "Sk+1+Ik+1" "Sl+Il" "Slc26a4+" "Social-distancing" "South-East" "Sp02"
    "Sp02<94%" "Spe4262" "Spe4263" "SpeI-XbaI" "Spo0Fsequence" "St-George" "St-Louis"
    "St-Quentin-Fallavier" "Stelzer-Braid" "Stokes-Einstein" "Sub-department" "Sulfo-NHS-AF"
    "Surface-bound" "Susceptible-Exposed-Infected-Infected"
    "Susceptible-Infected-Recovered-Susceptible" "Susceptible-Infectious-Removed"
    "Susceptible-Infectious-Susceptible" "Swine" "Swiss-Prot" "S˙a=−Sa" "S˙k=−ρ" "S˜" "SκIλ"
    "SκIλ˙" "SκRλ˙" "SκSλ˙" "SκSλ⟵I" "Sκ˙" "Sκ⟵I" "Sκ⟵Iλ" "SλSκ⟵I" "Sλ⟵Iκ" "T2D" "T2D." "T4-MS2"
    "T4F" "T4R" "T4probe" "TAGCCTAT-3" "TCCTGTGGCATCCATCCACGAAACT-3" "TCID50" "TCO2"
    "TCTCGTGTTGATTGTAGCTC-3" "TDS" "TGCCTG<3" "TGEV+LiCl" "TGEV+PDTC" "TGEV-RNAs"
    "TGTGATTTCACCCTAGCGACC-3" "TIP3P" "TLI>0.90" "TLR9-agonists" "TM7" "TOF-MS" "TU" "TU-02"
    "TYLCV" "TYLCV-Mld" "Taiwan-isolated" "Teal" "Teflon-glass" "Thirty-eight" "Thirty-six"
    "Thr45-Ala46-Glu47-Asp48-Met49" "Thr45-Met49" "Threading" "Threshold-based" "Time-pregnant"
    "Tip-DCs" "Todd-Hewitt" "Tools" "Total" "Towne-GFP" "Tox" "Tp>7°C" "TrEMBL" "Tracheal"
    "Trans-Blot" "TransIT-293" "Transmission-Rate" "Transmission-reducing" "Trends-CDC"
    "Tri-council" "Tris" "Tris-HCl" "Tris-HCl-buffered" "Triton-X" "Triton-X-100" "Triton-X100"
    "TritonX-100" "Tween-20" "Twenty-eight" "Twenty-five" "Twenty-four" "Twenty-one" "Twenty-three"
    "Twenty-two" "Two-day" "Two-dimensional" "Two-fold" "Two-pollutant" "Two-step" "Two-tailed"
    "Tyr76→Ile76" "T→C" "U-2000A" "U-bottom" "U.S" "U.S.A" "U26342" "U3" "U3%" "UC2T" "UL18" "UPEC"
    "US$0.52" "US$0.56" "US$0.88" "US$1,286" "US$13–20" "US$13–25" "US$181.66" "US$2.58" "US$2.98"
    "US$275" "US$3.78" "US$5.88" "US$51" "US$97" "USAMRU-K" "USH-animal" "USH-patients" "USH1"
    "USH1-patients" "Ud" "Udorn" "Ultra2" "Uni12" "UniProtKB" "Unit-Kenya" "User-friendly" "V2.2"
    "V5" "V5-tagged" "V5–V6" "V6" "V7" "VAR2CSA" "VAR2CSA-3D7" "VAR2CSA-FCR3" "VAR2CSA-domain"
    "VIC-AACCAGTAATTTCATCTGCTTCTGATGTGAGGC-TAMRA" "VIC-TCAGACACGCGGTCCGCTATAACGA-TAMRA" "VLGR1b"
    "VP16" "VP2" "VSV-FL" "VSV-G" "VSV-G-pseudotyped" "VSV-G." "VSV-based" "VSVΔG" "Vac-1"
    "Val303-Thr304-Phe305-Gln306" "Vector-Borne" "Vector-NTI" "Viability" "Village-1" "Village-5"
    "Virus" "W312" "WCMC-CITES" "WHLG2" "WHO" "WI-Myo7atnd" "WM-115" "WRL-68" "WST-1" "WT-like"
    "Watson-Crick" "Weight-Melanoma" "Whole-cell" "Whole-genome" "Whole-mounts" "Wiesbaden"
    "Wiki-like" "Wild-caught" "Wimley-White" "X!" "X-179A" "X-S" "X02342" "X8" "XD3" "XL-10"
    "Xba4260" "Xba4261" "Y280" "Y=34" "Y=34y" "YCH46" "YFP-E1TM" "YFP-NS2" "YM-3" "YZ07" "Yes"
    "Yokohama" "Yucaipa" "Z-curve's" "Z=34" "Z=34z" "Zn-β-lactamase" "Ztm" "Ztm-Myo15ci2" "Ztm-ci2"
    "Ztm-ci2×BN" "Z∈" "a+c" "a+g" "a+t" "a-priori" "a-wave" "aa49-57" "aa50-57" "aadA" "ab9482"
    "above-mentioned" "above-suggested" "absorption-based" "actin-ring" "active-site"
    "acyl-carrier-protein" "acylation-deacylation-based" "ad-hoc" "adeno-associated"
    "advantages-of-chloroplast-transformation" "aeruginosaPA01" "affinity-matured" "age-classes"
    "age-dependent" "age-group" "age-specific" "aged15" "aged≥18" "agent-based" "agro-terror"
    "air-tissue" "all-atom" "allophycocyanin-indotricarbocyanine" "alpha-COPI" "alpha-helices"
    "alpha1" "amiloride-derivative" "amino-4-trifluoromethyl" "amino-acid" "amino-acids"
    "amino-terminal" "among-site" "anaesthetic-like" "and15" "animal-to-animal" "animal-to-human"
    "anion-exchanger" "antibiotics-resistant" "antibody-antigen" "antigen-detection"
    "antigen-expressing" "antigen-presenting-cell" "antimicrobial-resistance" "apico-basal" "apnea"
    "apneas" "aq-55" "array-based" "artificially-created" "as-yet" "attitudes" "auss"
    "automorphism-driven" "autumn-winter" "avian-influenza-like" "avian-like" "b-wave" "b5-GFP"
    "back-translated" "background-monitoring" "bacterial-cell-sized" "bacteriophage-based"
    "base-pair" "base-pairing" "bat-to-human" "beliefs" "best-fit" "beta-COPI" "beta-site"
    "better-characterized" "between-community" "between-group" "bicarbonate-solution" "big-footed"
    "binding-pocket" "bio-based" "bio-climates" "biosecurity-facilities" "black-and-white"
    "black-pigmented" "black-tinted" "blanco" "blasticidin-resistance" "boca-like" "bocavirus-like"
    "boot-strap" "bottom-up" "bright-field" "broad-range" "broad-spectrum" "broncho-pneumonia"
    "brown-bat" "built-in" "built–up" "bundesrecht" "c+t" "c-di-AMP" "captive-bred"
    "captive-breeding" "carbon-nitrogen" "carboxy-terminal" "carboxyl-terminal" "care-giver"
    "case-control" "cds" "cell-based" "cell-specifically" "cell-to-cell" "cell-type-specific"
    "cell-viability" "cells" "cellular-scale" "census-by-sequencing" "change-from-baseline"
    "charge-coupled" "checks-and-balances" "chi-square" "child-minders" "circling-2" "citestrade"
    "class-separation" "class=1|x" "cleavage-based" "clinically-validated" "clone13"
    "clone×experiment" "closed-loop" "closely-followed" "clustalw" "coarse-grained" "coiled-coil"
    "cold-chain" "color-coded" "colour-coded" "community-level" "commuter-movement"
    "complete-linkage" "configuration-model" "configuration-network" "congressionally-mandated"
    "connecting-piece" "constant-temperature" "contact-day" "contact-reducing" "continuous-time"
    "control-OD" "control-policy" "core-mediated" "coronavirus-like" "cortico-medullary"
    "cost-effective" "cost-effectiveness" "counter-intuitively" "covariance" "cross-HI"
    "cross-cutting" "cross-label" "cross-neutralizing" "cross-protection" "cross-reactivity"
    "cross-reacts" "cross-sections" "cross-species" "cry1Ab" "cry1Ac" "cry2Aa2" "cry9Aa2"
    "cryo-sections" "cut-off" "d+3" "dI-dC" "dM199" "dark-adapted" "data" "day-14" "day-21" "day-7"
    "day-care" "day-to-day" "ddH2O" "degree-based" "density–dependent" "detections"
    "diabetes–continue" "diacylphosphatidylethanolamine-N-lissamine" "diary-based"
    "differential-equation-based" "difficult-control" "dimethyl-ammonio" "directly-transmitted"
    "discrete-time" "disease-based" "dissonance-generating" "docs" "don't" "dorso-medial"
    "dose-response" "dot-blot" "dot-like" "double-barreled" "double-blind" "double-distilled"
    "double-stained" "double-strand" "dove" "down-stream" "dried-down" "drug-drug" "dry-cell"
    "dually-infected" "dye-terminator" "e-mail" "e-mailed" "e-value" "early-onset"
    "easy-to-implement" "edge-enhancement" "elastin-like" "electrically-powered" "electricity-free"
    "electro-oculogram" "elsewhere23" "en_AI_avianinfluenza" "end-labeled" "end-market" "end-user"
    "equipment-free" "error-free" "ever-expanding" "ever-increasing" "evidence-based"
    "evolution-proof" "expectations" "experimentally-determined" "experimentally-measured"
    "exposure-response" "exp{dj" "extra-domain" "f*log" "face-masks" "face-to-face" "factors"
    "falciparum-FCR3" "false-negatives" "false-positives" "false-positivity" "false-receptor"
    "far-UV" "farrowing-time" "fat-based" "field-data" "fields-of-view" "fileadmin" "fine-tuned"
    "first-dimension" "first-hand" "first-responder" "first-strand" "five-member" "five-point"
    "flat-bottom" "flow-cytometry" "floxβ-luc" "flu-like" "fluid-phase" "fluorescence-based"
    "fluorescently-labeled" "flutrends" "fold-change" "fold-changes" "follow-up" "followed-up"
    "foreign-origin" "four-primer" "four-step" "fraction-of-individuals-living-with-AIDS"
    "free-to-air" "freeze-thaw" "freezing-thawing" "fromVAR2CSA-3D7" "fruits" "fully-human"
    "fundingresearchareas" "funding–The" "fusion-mediated" "g+c" "g+t" "gB-1" "gB122" "gB131"
    "gB64" "gM" "gN" "gain-of-function" "gaps" "gastro-enteritis" "gel-to-fluid" "gel-to-gel"
    "gene-products" "gene-therapy" "genotype–HRV" "genotype–phenotype" "glutaraldehyde+2%"
    "gold-wire" "gonorrhoea-like" "goodness-of-fit" "gorf" "gray-level" "grey-cheeked" "group-OD"
    "guardians" "g⋅L−1" "h1+h0" "hBoV" "hPIV1" "hRV-72" "hRV-C" "haemalun-eosin-safranin"
    "half-closed" "half-life" "half-links" "hand-warmer" "hard-to-reach" "head-to-tail"
    "health-care" "health-system" "heat-shock" "heater-lid" "helium-driven" "helix-helix"
    "helix-strand" "hemi-nested" "herbs" "high-bond" "high-confidence" "high-degree" "high-density"
    "high-dimensional" "high-elevation" "high-fidelity" "high-frequency" "high-impact" "high-level"
    "high-leverage" "high-lighting" "high-mobility" "high-molecular" "high-performance"
    "high-profile" "high-quality" "high-resolution" "high-risk" "high-shedders" "high-shedding"
    "high-temperature" "high-value" "high-yield" "higher-dimensional" "higher-order" "higher-risk"
    "higher-throughput" "highest-risk" "highly-connected" "homodimer-1" "hospital-based"
    "host-country" "host-pathogen" "host-pathogen-interactions" "house-keeping" "house–to–house"
    "hpr" "http" "human-like" "human-to-human" "human–to–human" "hunter-killed"
    "hygromycin-resistance" "hyper-expression" "hyper-plane" "hyper-surface" "hyper-ubiquitinated"
    "hypo-ubiquitinated" "hypopnea" "hypopneas" "i=1ki∑j∈Nbrsikj" "iSTAT1" "ice-water"
    "illness-related" "imaging-plate" "immediate-early" "immune-mediated" "immuno-complex"
    "immuno-dominance" "immuno-electron" "in-component" "in-contact" "in-country" "in-degree"
    "in-force" "in-frame" "in-gel" "in-home" "in-hospital" "in-house" "in-person"
    "incubation-vessels" "indel" "individual-level" "infections" "influenza-A"
    "influenza-circulation" "influenza-like" "info_ev" "information-based" "insertions"
    "instrument-free" "intention-behavior" "intention-behaviour" "intention-to-treat"
    "inter-domain" "inter-helices" "inter-plate" "inter-protomer" "inter-replicate" "inter-test"
    "interest-group" "interventions" "intra" "intra-plate" "intra-protomer" "intra-strain"
    "investigator-led" "iodoacetamide" "ischemia-reperfusion" "iso-surface"
    "isopropyl-1-thio-d-galactopyranoside" "i∈{L" "joined-up" "k+1" "k-means" "kSk−γ"
    "kernel-transformed" "keto" "km2" "knock-down" "laboratory-based" "laboratory-confirmed"
    "large-early" "large-scale" "larger-scale" "late-onset" "late-stage" "latent-infectious"
    "lattice-based" "least-squares" "limα→1Hα" "lipid-lipid" "liposome-mediated" "little-brown-bat"
    "live-attenuated" "live-bird" "live-dead" "local-host" "log-likelihood" "log-log" "log-phase"
    "log-transformation" "log-transformed" "log10" "long-distance" "long-eared" "long-legged"
    "long-lived" "long-range" "long-standing" "lost-to-follow-up" "low-cost" "low-dimensional"
    "low-dose" "low-flow" "low-frequency" "low-grade" "low-income" "low-level" "low-pH"
    "low-quality" "low-resource" "low-risk" "low-serum" "low-shedders" "low-speed" "lower-income"
    "lysosomes" "mIU" "mPDCA-1" "mPDCA-1clone" "mW" "macrolide-resistance" "macrophages"
    "macropinocytosis-like" "main-chain" "make-up" "malignantly-transformed" "mammals-models"
    "man-made" "marama" "mass-vaccination" "matrix-based" "maturity-onset" "maximum-likelihood"
    "mean-field" "mean±SD" "medicine-treated" "medium-throughput" "medium-to-large" "mega41"
    "melanin-like" "meso-DAP" "metal-binding" "methyl-sulfate" "methyl-β-CyD"
    "methyl-β-cyclodextrin" "mg−1" "micro-CT" "micro-structures" "micro–environment" "mid-1980s"
    "mid-1990s" "mid-altitude" "mid-time" "military-to-military" "minigenome-based" "minimum-cost"
    "mm-diameter" "mo-1" "mock-infected" "mock-infection" "mock-inoculated" "mock-treated"
    "modern-dayBG" "molecular-level" "monocytes" "monocytic-like" "mononucleosis-like"
    "morbidities" "mouse-IgG" "mpex" "multi-electrode" "multi-item" "multi-parameter"
    "multi-protein" "multi-resistant" "multi-system" "multi-user" "multiple-alignment"
    "multiple-cycle" "multiple-sequence" "multiple-testing" "mutation-environment" "n-cliques"
    "n-mers" "n-regular" "n-tuple" "nano-ESI" "nano-LC" "nano-LC-ESI-MS" "nasal-throat"
    "naturally-expressed" "near-full" "near-infection" "negative-pressure" "negative-sense"
    "negative-strand" "negative-stranded" "neighbour-joining" "neomycin-resistance" "network-based"
    "network-mediated" "next-generation" "next-nearest-neighbour" "next–generation" "nine-carbon"
    "nitrogen-based" "nl" "no-disease" "no-template" "normally-distributed" "north-central"
    "nuclear-to-cytoplasmic" "nucleo-cytoplasmic" "nucleotide-oligomerization" "n¯−1n¯" "n¯≡〈n〉"
    "object-detector" "odds-ratio" "off-the" "off-the-shelf" "often-repeated" "oligo-probe"
    "on-farm" "on-site" "on-target" "one-by-one" "one-dimensional" "one-fifth" "one-leaf"
    "one-step" "one-third" "one-to-one" "one-way" "open-ended" "open-label" "open-source" "org"
    "oseltamivir-resistance" "oseltamivir-susceptible" "out-compete" "out-component" "out-degree"
    "out-patient" "output-score" "over-dimensionality" "over-inflate" "over-reaction"
    "over-the-counter" "over-treatment" "overweight-obese" "oxidants" "oxyanion-binding"
    "oxyanion-loop" "p125Luc" "p7-Flag" "p7-NS2" "p7-NS2-E1E2" "p7NS2" "p<" "p<0.0001" "p<0.001"
    "p<0.0125" "p<0.017" "p<0.05" "pAcGP67-A" "pBABE-puro" "pBABE-puro-mCEACAM-1" "pCAGGS-BlaM1"
    "pCAGGS-HA" "pCAGGS-NA" "pCMV" "pCMV-HBx" "pCMV-LAP" "pCMV-LIP" "pCMV-Myc" "pCMV-Myc-PLP2"
    "pCMV-Myc-PLP2-C106A" "pCMV-Tag2A" "pCOX-2-Luc" "pCR2.1" "pCR2.1-TOPO" "pCR4" "pCTCON-2"
    "pCTCON-HA1" "pCTCON-HA2" "pCTCON-T" "pCTCON2" "pCambia0380" "pET21a" "pET28a" "pET30a"
    "pFlag-CMV2-IRF3" "pGEM-T" "pGEX-4T-1" "pGEX-4T-1-IRF3-131C" "pGEX-6P-2" "pGEX-6P-2-PLP2"
    "pGL3-control" "pGluc-basic" "pH-units" "pH1N1" "pH1N1vaccination" "pH7.2–7" "pH7.4" "pH9.6"
    "pHBV-1.2" "pHBV-1.2*7" "pHEF-VSVG" "pHH-Fluc" "pHW2000" "pM-HBx" "pMD19-T" "pNN50" "pPRV111A"
    "pRK5-HA-Ub" "pRL-CMV" "pRL-CMV-Luc" "pRSFDuet-1" "pSilencer™2.1-U6" "pTG-Luciferase"
    "pTY-EfnLacZ" "pVP16" "pVP16-LAP" "pZS197" "pageLocation=Megabat" "pair-based" "palm-civets"
    "pan-CoV" "panIFN-α" "papain-like" "paper-based" "para-influenzavirus" "parents"
    "partially-mediated" "particle-conjugated" "particle-incorporated" "particle-mediated"
    "particle-mesh" "particle-protected" "partner-country" "pathogen-associated" "pathogen-free"
    "pathogen-specific" "patient-level" "pcDNA-E1E2" "pcDNA3" "pcDNA3-CRT" "pcDNA3-IiPADRE" "pdf"
    "penicillin-non-susceptible" "penicillin-streptomycin" "peptide-based" "peptide-peptide"
    "per-partnership" "per-protocol" "per-residue" "percolation-based" "person-dependent"
    "person-to-person" "phage-based" "pharmaco-epidemiological" "phase-contrast" "phase-inversion"
    "phase-sensitive" "phospho-IRF3" "phosphoHSPB1" "photons" "phycoerythrin-cyanine"
    "phycoerythrin-indotricarbocyanine" "physician-patient" "physionet" "pigment-producing" "pirl1"
    "pixels×2672" "plant-based" "plant-biotechnology-genomics" "plaque-forming" "plaque-purified"
    "plasmid-driven" "plastid-based" "pocket-type" "policy-makers" "pollutant-independent"
    "polymorpho-nucleated" "pool-within-class" "population-based" "population-level" "positive-ion"
    "positive-sense" "positive-stranded" "post-SARS" "post-challenge" "post-contact"
    "post-electroporation" "post-entry" "post-exposure" "post-fusion" "post-genome"
    "post-infection" "post-injection" "post-inoculation" "post-natally" "post-passage" "post-sleep"
    "post-transcriptional" "post-transfection" "post-translationally" "posttrial-of-labor"
    "pouch-like" "power-law" "pox-based" "prepub" "previously-determined" "primary+secondary"
    "primer-probe" "priority-setting" "private-practice" "proIL-1β" "probe-based" "progenitors"
    "project-species-m-Megabat" "protein-1" "protein-10" "protein-RNA" "psbA3" "pull-down"
    "pull-downs" "puromycin-resistance" "p˙I=τpSpIθg" "p˙S=τpSpI" "p≤0.00001" "p≤0.0001" "p≤0.05"
    "quality-assured" "quasi-hemolytic" "r-biopharm" "r-project" "r-square<0.1" "r=43R=43×14=13"
    "rCM=〈n" "rNS1" "rPR8" "rRT-PCR" "rabbit-IgG" "radicals" "radiographically-confirmed"
    "ranch-raised" "random-mixing" "rank-order" "rapid-acting" "rapidly-spreading" "rat-IgG"
    "rationally-designed" "rattenhaltung" "rbcS" "rbcS-tp" "ready-to-eat" "reagent-grade"
    "real-time-RT-PCR" "real-transmission" "real-valued" "reassortant" "reassortants"
    "receptor-adaptors" "red-tailed" "reduced-dose" "regional-level" "remote-sensing"
    "renin–angiotensin–aldosterone" "resource-limited" "respondent-driven" "responders"
    "reverse-correlated" "reverse-phase" "reverse-transcribed" "reverse-transcription" "rgVac1"
    "rgVac1ins-P2" "rgVac1sub-P2" "rgY55" "rgY55sub-P10" "rgY55sub-P8" "rigid-body" "risk-benefit"
    "risk-structure" "role-based" "rotating-anode" "round-window" "routine-based" "rs1042713"
    "rs1042714" "rs11462733" "rs1266078" "rs1801252" "rs2273612" "rs28432254" "rs3117581"
    "rs3132449" "rs3178094" "rs34490746" "rs4947251" "rs6921907" "rs7070922" "rs707921" "rs707922"
    "rs707922-T" "rs805264" "rs805296" "rs805297" "rs805297-A" "rs805297-C" "rs9267528" "rs9404941"
    "rsbweb" "rt-PCR" "rt-RT-PCR" "run-to-run" "r·w+b" "s-ms" "sCD40L" "saline-assisted" "same-day"
    "sample-to-result" "satellite-based" "sc-32321" "sc-51956" "scale-up" "school-closure" "scoC"
    "score-positive" "screw-cap" "season-dependent" "second-dimensional" "second-generation"
    "secondary-antibody" "self-associate" "self-association" "self-built" "self-consistent"
    "self-contained" "self-described" "self-efficacy" "self-esteem" "self-interaction"
    "self-ligation" "self-limited" "self-limiting" "self-management" "self-propagated"
    "self-protection" "self-replicate" "self-report" "self-reported" "self-reports"
    "self–protection" "semi-fluid" "semiconductor-based" "sequence-homology" "serially-diluted"
    "set-up" "severely-affected" "sexual-activity" "sexually-transmitted" "shaker-1" "shaker-2"
    "short-chain" "short-course" "short-range" "short-stay" "short-term" "short-time" "siRNA-based"
    "siRNA2" "sialic-acid" "side-chain" "side-chains" "side-effects" "sigma-weight" "sigma-weights"
    "signed-rank" "single-bounded" "single-cell" "single-cycle" "single-domain" "single-domains"
    "single-dose" "single-nucleotide" "single-pollutant" "single-source" "single-unit"
    "single-user" "single-valued" "site-directed-mutagenesis" "six-floor" "six-week-old"
    "size-segregated" "size–segregated" "slow-growth" "slow-scan" "slower-than-hoped" "small-angle"
    "small-molecule" "small-scale" "small-world" "smart-phones" "smart-polymer-based" "so-called"
    "soap-grade" "social-distancing" "socio-economic" "sodium-acetate" "sound-bites" "source-code"
    "south-west" "specific-pathogen" "specific-pathogen-free" "speck-like"
    "spectinomycin-streptomycin" "spo0F." "sponge-like" "sporulation-deficient" "sprot"
    "sprot_details" "spur-thighed" "stand-alone" "steady-state" "step-by-step" "strand-strand"
    "strands-helices" "stress-induced" "study-design" "sub-Saharan" "sub-age" "sub-analysis"
    "sub-assemblies" "sub-clinical" "sub-compartments" "sub-critical" "sub-family" "sub-groups"
    "sub-infection" "sub-populations" "sub-region" "sub-text" "subtilis" "subtilis-like"
    "sugar-based" "super-spreaders" "susceptible-infectious" "swine-origin" "sydney"
    "temperature-controlled" "temperature-induced" "temperature-responsive" "test-and-treat"
    "tgaaaatgtttttgcttcct-3" "thin-section" "third-codon" "third-degree" "third-generation"
    "third-order" "third-party" "thoughts" "threat-agent" "three-color" "three-dimensional"
    "three-motifs" "three-scale" "threshold-based" "tick-borne" "time-course" "time-delay"
    "time-delayed" "time-limited" "time-of-addition" "time-of-flight" "time-point" "time-points"
    "time-scale" "time-scales" "time-series" "time-since-infection" "time-step" "time-trajectories"
    "time-window" "time–step" "titanium-based" "tj−ti" "tj−tk" "top-down" "top-hat" "tp"
    "tracheo-bronchial" "trade-off" "trait-associated" "trans-complementation" "trans-stadially"
    "transfected-cell" "transiently-expressed" "transmission-probability" "transmission-reducing"
    "transplastomic-plants-chloroplast-engineering" "tri-bromo-ethanol" "tri-service"
    "triple-stained" "tru" "trypsin-like" "tryptic-mass" "ttaagcataatgctgccta-3" "tumor-reactive"
    "two-class" "two-dimension" "two-dimensional" "two-domain" "two-exposures" "two-group"
    "two-letter" "two-phase" "two-pollutant" "two-sided" "two-step" "two-tailed" "two-thirds"
    "two-way" "type-16" "type-I" "type-II" "tyrosine-based" "ucsc" "ug" "uk" "ultra-centrifuge"
    "um×1" "un-phosphorylated" "under-5" "under-treated" "under-two" "under-value" "unep-wcmc"
    "units" "unwellness" "up-and-down" "up-side-down" "us-historic" "usegalaxy" "v-shaped"
    "vaccinations" "vacuolar-type" "value-beta-actin" "values<0.05" "variable-pressure"
    "vector-based" "vector-infected" "vector-to-human" "vector-transmitted" "ventral-most"
    "version27" "vice-versa" "virus-like" "volunteer-derived" "vs.0.86" "w=∑j=12mαjϕ" "warm-up"
    "wb1104" "weakly-buffered" "weather-based" "web-based" "web-server" "well-characterised"
    "well-characterized" "well-defined" "well-described" "well-documented" "well-educated"
    "well-established" "well-funded" "well-knit" "well-learned" "well-publicized" "well-recognised"
    "well-recognized" "well-summarized" "well-tolerated" "white-nose"
    "who-acquires-infection-from-whom" "whole-cell" "whole-genome" "whole-mounts"
    "whorl-associated" "whorl-forming" "whorl-like" "wide-scale" "wide-spread" "wild-caught"
    "with10%" "within-channel" "within-community" "within-group" "within-herd" "within-host"
    "within-species" "workers" "worse-case" "worst-case" "www" "x+1" "x-ray" "x1" "x1+z1" "x1j"
    "x1−x1j" "x2" "x2=−τ+0β0+β1x1β2+β3x1" "x2j" "x2−x2j" "x̄" "x̄j" "y+1" "y-axes" "y-intercept"
    "y=γ" "y=ϕ" "y=〈ϕ" "year-to-year" "years" "yest=∑j=12mαjk" "yi=∑j=12mαjk" "yin-yang" "z-test"
    "z-tests" "zero-order" "{PCL-C}" "{X=34" "{X=34x" "{modified" "{seed" "{σ1" "{σ1i" "}×100"
    "ÄKTA-express" "×100" "×102" "×103" "×104" "×105" "×g" "ƒyƒx" "ΔCn" "ΔG" "ΔHcal" "ΔTM12"
    "ΔTME2" "Δp7" "Δspo0F" "ΔΔCt" "Δβ-luc" "α-1,4" "α-2,6" "α-CDE" "α-D-glucopyranose"
    "α-Trimethylammonioacetyl" "α-cyano-4-hydroxycinnamic" "α-hemolysis" "α1" "α2" "α2-3" "α2-6"
    "α3" "α=n¯Gτ" "α>0" "αj" "α−1" "α≠1" "β-hemolysis" "β-sheet" "β-sheets" "β0"
    "β0+β1x1+β2x2+β3x1x2" "β1" "β1-AR" "β1j" "β2" "β2j" "β2−β1β2x1" "βCDP6" "βG=n¯Gτ" "βH" "βL"
    "βL=n¯Lτ" "βLIa+α∑b≠aIb" "βM" "βSI" "βi" "β̂" "γ-32P-ATP" "γ-CyD" "γ-CyDs" "γ32P" "γ34.5"
    "θ˙=−τpIθ" "λem" "λex" "λt0" "μL" "μg" "μl" "μmoL" "μmol" "μmoles" "πi" "ρxy=ƒxy" "σ1" "σ150"
    "σ1i" "σ2" "σ2i" "σ2}" "τ+0β0" "τ+γ" "τ0=ln" "χ2" "€991" "∆z" "∑i" "∑iβiπi" "∑i≠jdi"
    "∑j=12mαjϕ" "∑j≠kw" "∑x∈X" "−and" "〈d〉" "〈d〉=1N" "〈k
2〉"
    "〈k
2〉−〈k〉2"
    "〈kn〉=∑kknP" "〈k〉" "〈·〉" "〉+b=∑j=12mαjk" "〉〈n〉ττ+γ" "〉〈n〉τ−γ" "△Ct"))

