;; covid-2020-04-03-0403-COM-PMC-5301-5400 sample of unknown words
;; created 5/10/20 13:9:59

(in-package :sparser)

;; 3575 extracted as unknown bio-entity


(defparameter *All-Upper-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*All-Upper-Unknown-Words*) (symbol-value `*All-Upper-Unknown-Words*))
         '(
("AAALAC" "AAK" "AASI" "AAUU" "AAV" "ABSL" "ACAG" "AEC" "AEEC" "AGATCCACGCGGAACCAGAC" "AGCC" "AGRF"
 "AIC" "AIDA" "AIV" "AJCC" "AJM" "ALARIS" "ALV" "AMEN" "ANISA" "ANNANCGAGGGT" "ANSES" "ANSM" "ANV"
 "AOAC" "APMV" "AQL" "ARTI" "ATCC" "ATCGTCGTCGTAGGCTGCTCNNNNNNNN" "ATMP" "AZALEA" "AZMATICS"
 "BACPAC" "BALF" "BBB" "BBV" "BDV" "BEGM" "BIAHO" "BIORAD" "BIOVIA" "BIOVO" "BLAT" "BLG" "BLS"
 "BSE" "BSL" "BST" "CACCACCACCACCACCACT" "CAEV" "CATCTCCCCAGAGGATCCGAAGCCCCTCCTGTAACCCATTC"
 "CCACGNNGNGT" "CCHFV" "CDCD" "CELLECTRA" "CGC" "CGCGGATCCGTCCCAGGTGGTCCAGGTGAAC" "CGG" "CGI"
 "CGNC" "CGNGG" "CHIKV" "CIL" "CLSI" "CLUSTAL" "CLUSTALO" "CMVL" "COE" "COOLPIX" "CORECHECK"
 "CSCHAH" "CSLPP" "CTG" "CTT" "CTTGGATCCAAAGGCAGTTTTTGTATGAAGC" "CUC" "CVCC" "CWA" "CWHC" "CXCL"
 "CXP" "CXR" "DAKO" "DENV" "DEST" "DEVD" "DGR" "DIVEIN" "DKFZ" "DLCO" "DMEM" "DPBS" "DPO" "DPPH"
 "DSB" "ECACC" "ECMO" "EDSV" "EEV" "EGM" "EKDKKKEKK" "EMBASE" "EMCV" "EMIC" "EMICE" "ENZO" "EPEC"
 "ERSE" "ETEC" "EUCAST" "EVD" "EZ" "FASTA" "FASTQ" "FBJ" "FFV" "FIK" "FIPV" "FIVA" "FIVC" "FMC"
 "FOC" "FPKM" "FUJIFILM" "FVC" "FW" "FWC" "GAATGGGTTACAGGAGGGGCTTCGGATCCTCTGGGGAGATG" "GAC"
 "GAPPSS" "GBI" "GCTTCATACAAAAACTGCCTTTGGATCCAAG" "GGGACTTTCC" "GGGCGAAUUGGAGCU" "GGGGCC" "GGGTTA"
 "GGGTTT" "GHSA" "GIDP" "GII" "GMOD" "GNB" "GNU" "GOS" "GUI" "HCW" "HFNC" "HGAP" "HMMER" "HOXC"
 "HPAIV" "HQR" "HRCT" "HRSVA" "HRSVB" "HRVB" "HSUR" "HVAC" "IACUC" "IARC" "IAV" "IBDV" "IBM" "IBV"
 "ICGA" "ICTV" "ICU" "ICVT" "IDSR" "IDT" "IEC" "IEF" "IFNRA" "IMV" "INDEL" "INFLV" "INFORS"
 "INTERGROWTH" "IOM" "IOZK" "IPD" "IPG" "IQR" "IRB" "IRCCS" "IRES" "IRMM" "ISO" "ISRE" "IVDMD"
 "IVDS" "IVIS" "IVT" "IX" "IBIDI" "JBI" "JBS" "JDV" "JEV" "JHM" "JLR" "JMB" "JTT" "JU" "KGGGCGGRRY"
 "KNMG" "KOS" "KVGMP" "KX" "LAMV" "LBW" "LEAVNKK" "LEISS" "LEISSTCDA" "LNRV" "LOGO" "LPAIV" "LRLV"
 "LRNV" "LRT" "LRTI" "LSB" "LTR" "MAFRA" "MASCOT" "MCB" "MCDA" "MCMV" "MDRV" "MEDWS" "MEWDS" "MHV"
 "MMLV" "MMRRC" "MOHLTC" "MOI" "MOPICE" "MPPS" "MPS" "MPXV" "MRCA" "MUGA" "MVSS" "NASA" "NEJM"
 "NHI" "NHIRD" "NHIS" "NIFDC" "NLD" "NPGP" "NPLV" "NPMS" "NVSL" "NZ" "OCTA" "OD" "ODK" "OECD" "OIE"
 "OLYMPUS" "OSIO" "OTN" "PAAG" "PAMPS" "PBM" "PEDVPT" "PEDVPTP" "PEFR" "PEMS" "PHASER" "PI" "PLS"
 "PLV" "PLVA" "PLVB" "PMGTS" "PMH" "POCT" "PROTEKT" "PURINA" "PYD" "QALY" "QCMD" "QGRS" "QIA"
 "QIAGEN" "QOL" "RATT" "RECIST" "RIDD" "RIDDOR" "RIE" "RKK" "RLT" "RPD" "RPKM" "RRL" "RSII" "RVFV"
 "SAON" "SAPE" "SCID" "SCSM" "SDAV" "SDCP" "SDG" "SDM" "SDP" "SDPP" "SFF" "SFV" "SGD" "SHXB"
 "SISPA" "SMALT" "SOFA" "SONOPLUS" "SPSS" "SSQ" "SSU" "SURPI" "SVF" "SYBR" "TAE" "TAKARA" "TBE"
 "TCID" "TGEV" "TGG" "TLB" "TMAA" "TMBIM" "TMEV" "TOA" "TORSC" "TRIPS" "TTSP" "TTY" "TUNEL"
 "TXXTXGFG" "UFP" "ULPA" "UMI" "UN" "URT" "USA" "USAID" "USB" "USCN" "USD" "VACV" "VDJ" "VDX" "VHF"
 "VII" "VINARES" "VMRD" "VMRI" "VOL" "VTEC" "WBC" "WIZARD" "WNS" "WTO" "XBP" "XIII" "XP" "XTT"
 "XYS" "XZ" "YCL" "ZIVK" "ZRR" "ZYMO" "MGI" "UCSC" "ÄKTA")))
    :test #'equalp))


(defparameter *All-Lower-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*All-Lower-Unknown-Words*) (symbol-value `*All-Lower-Unknown-Words*))
         '(
("aac" "abcam" "abcc" "abnormities" "abortus" "absorbance" "acidilactici" "acidophilus" "acuminate"
 "acuta" "acutirostris" "addressin" "addressthe" "adeno" "adenoid" "adolescents" "aegypti"
 "aeruginosa" "afebrile" "affymetrix" "aga" "agc" "agrarius" "agrestis" "airstream" "alarmin"
 "albicans" "albifrons" "albopictus" "albopinctus" "albus" "alecto" "algorithm" "alphaherpesvirus"
 "alphaherpesviruses" "alveoli" "alveolus" "alveus" "amarus" "amenorrhoea" "americana"
 "aminocarophenone" "amoebe" "ampholytes" "amplicon" "amplicons" "analysers" "analyte" "anatid"
 "angiograms" "angiography" "annellovirus" "annum" "anoxia" "anser" "anserina" "anseris"
 "anthralgia" "antileishmanials" "antimonials" "antiparallel" "antiretrovirals" "antivirus" "apnea"
 "aquaglyceroporine" "arisen" "arteriviruses" "arthroplasty" "assembler" "astroviurses" "ata" "atc"
 "atratus" "atys" "aureus" "autoanalyser" "autoanalysers" "autoimmune" "autoradiography"
 "autosampler" "autostainer" "avium" "axial" "axonopodis" "b" "bandgap" "bandwidth" "basophilia"
 "bdbiosciences" "beamline" "begun" "benzo" "bereft" "berghei" "bernicla" "betaherpesviruses"
 "bewickii" "bifidobacteria" "bilayer" "biluribin" "bio" "bioaerosol" "bioassay" "biocide"
 "biocides" "biohazards" "biomass" "biome" "biopsy" "biorisk" "biosafety" "biosphere"
 "biosurfactant" "bioterrorism" "biotopes" "biotype" "bioweapon" "bioweapons" "biphenanthrene"
 "biphenanthrenes" "bisacrylamide" "blestriarene" "blogs" "blueberry" "bobcat" "bobcats" "bonafide"
 "bootstrap" "borna" "bottlenose" "botulinum" "bowtie" "brachyrhynchus" "brantae" "breakpoint"
 "breathlessness" "brent" "brevis" "broken" "broncho" "bronchoscopy" "bronchospheres" "brucei"
 "bulgaricus" "bupleurosides" "bupleurynol" "burgdorferi" "burnetii" "burnettii" "bursaria"
 "bushmeat" "c" "caa" "cac" "cacodilate" "cacodylate" "caecum" "caerulescens" "calicivirus"
 "camelpox" "campestris" "canagica" "canis" "cannula" "canthus" "capita" "capsulatum" "cardio"
 "cardioangiology" "cardiovirus" "caregivers" "carryover" "casu" "catalyses" "catarrhalis" "catus"
 "cct" "centile" "cepacia" "cerebellum" "cereus" "cervid" "cgg" "chaihunaphthone" "chemo"
 "chemokies" "chevrieri" "chinense" "chinensinaphthol" "chito" "chlorella" "chloromethyl"
 "chloroviruses" "choleratoxin" "choloform" "chorio" "choriocapillaris" "chorioretinopathy"
 "chosen" "chromagen" "chrysogenum" "chytrid" "ciliate" "ciliates" "circovirus" "citri" "clade"
 "classifier" "clinicaltrials" "clinicians" "clinico" "cloaca" "clonotypes" "coccidia"
 "cocirculate" "codon" "coldspots" "coli" "coliform" "collectin" "colonoscopy" "colorants"
 "colorimetry" "colostrum" "columbianus" "commensals" "commonalities" "communis" "comorbid"
 "comorbidities" "compendia" "concomitance" "concreteness" "condensate" "conductance" "conformers"
 "confounder" "confounders" "congolense" "contig" "contigs" "continuum" "cookstove" "cooperatives"
 "copathogens" "corin" "corr" "corvids" "cosolvents" "covariate" "covariates" "coverslips"
 "coxsackie" "coxsackievirus" "crocuta" "cropland" "croplands" "crossover" "cruzi" "ctc" "ctg"
 "ctt" "cuniculi" "cutanea" "cutpoint" "cutpoints" "cycler" "cyclo" "cygnus" "cytofluorimetry"
 "cytology" "cytomatrix" "cytometer" "davidii" "dawhere" "dehydroantofine" "dendrobatidis"
 "deontology" "deoxynucleotide" "deoxynucleotides" "der" "dermatomycoses" "descriptives"
 "desocializes" "destructans" "dev" "diaminobenzidine" "diarizona" "diaspora" "dibenzopyrazine"
 "dichroism" "difluoride" "dilutedenzyme" "dimensionless" "dinoflagellate" "diphenanthrenes"
 "diplococcus" "diplotype" "diplotypes" "discrepant" "discriminant" "dispersers" "divaricatus"
 "dmol" "domesticus" "donovani" "dormancy" "dotter" "downwind" "drawn" "dromedarius" "droplet"
 "droplets" "droppings" "dropwise" "dsb" "dubiosii" "duodenalis" "duplexes" "dysgalactia"
 "dyskinesia" "dyspnea" "eae" "ebolaviruses" "ecotones" "ectodomain" "ectokinases" "ectoparasites"
 "ectoproteins" "edeine" "edema" "edulis" "eelgrass" "efficace" "electrochromatography"
 "electropherograms" "electrospray" "ellip" "ellipsoid" "eluate" "email" "emdmillipore"
 "enantiomers" "encapsidate" "encapsulates" "encephalomyocarditis" "endodomain" "endoparasites"
 "endothelia" "enhancer" "ensheath" "enterica" "enterocolitica" "enteropathy" "enterotoxins"
 "eosin" "eosinophilia" "epididymides" "epididymis" "episomes" "epithelia" "epithelium" "esculenta"
 "etc" "ethicon" "ethnomedicines" "eukarya" "eukaryome" "eukaryotome" "ex" "exclusions"
 "experimentalists" "explant" "explants" "extravasate" "extremes" "exudates" "f" "fabalis"
 "faecalis" "falciparum" "fastidiosa" "fastq" "felis" "fermentors" "fi" "ficolins" "ficuseptine"
 "fidelis" "flavicollis" "flexuose" "floaters" "flora" "flowchart" "flowcytometry" "flowjo"
 "fluorophores" "flyways" "focusses" "foreseen" "forgotten" "formazan" "fourths" "fovea" "framings"
 "frontières" "frozen" "fructooligosaccharides" "fulminant" "fundamentals" "funders" "fundus"
 "furo" "fuscus" "gaa" "gac" "gadwall" "gallus" "gametocytes" "gammaherpesvirus"
 "gammaherpesviruses" "gastralgia" "gastro" "gat" "gcg" "genechips" "geno" "genogroup" "genogroups"
 "genome" "germplasm" "ggt" "glareolus" "glm" "glutamyl" "gondii" "gone" "gonorrhoeae" "goods"
 "gouv" "granulomas" "greylag" "griffithii" "groff" "grossedentata" "gtc" "guanyl"
 "guanylylimidodiphosphate" "guineafowl" "gz" "haematology" "hamiltonii" "hampsonii" "haplotype"
 "haplotypes" "haylage" "heartwood" "helices" "helix" "hellem" "henryi" "hepatitits"
 "hepatotropism" "heptad" "heptanucleotide" "herbivores" "hetero" "heterotetramer" "heterotrimer"
 "heterozygote" "hexamers" "hexanucleotide" "hidden" "hilar" "hips" "hirae" "histology"
 "histomorphology" "histopathology" "hmmcalibrate" "hologenome" "homepage" "hominis" "homogenate"
 "homogenizer" "homozygote" "honeycreepers" "hotspot" "hotspots" "hotstpot" "html" "humidifier"
 "hydatid" "hygienists" "hyodysenteriae" "hyper" "hyperimmune" "hyperresponsiveness" "hypoxemia"
 "icaco" "identifier" "identifiers" "iii" "ileum" "iliac" "imager" "immitis" "immuno" "immunoassay"
 "immunoassays" "immunochemotherapy" "immunocytochemistry" "immunohistochemistry" "immunopathology"
 "immunophenotype" "immunospot" "inbreds" "indels" "indenter" "indicus" "inducers" "inertness"
 "infantum" "infectiousness" "infectiveness" "influenzae" "ingroup" "feelings" "innoculum"
 "inocula" "inoculum" "inpatients" "insightful" "insulari" "inta" "interarray" "intercross"
 "interferome" "glht" "intermedius" "intermolecule" "internet" "interquartile" "intersample"
 "interspecies" "interstitium" "intersubject" "intestinalis" "intra" "intracellularis" "intraclass"
 "intrahost" "intranet" "invariant" "ionic" "isokaerophyllin" "isolators" "isotype" "iss" "italien"
 "ix" "j" "japonicas" "jejuni" "jejunum" "jirovecii" "kappa" "kerotherapy" "khmer" "kilobases"
 "kobuvirus" "lactis" "lactobacilli" "lactococci" "lambda" "lamblia" "lanceolate" "lavage"
 "leafroll" "learnt" "leftover" "leica" "leishmaniases" "leucopus" "licheniformis" "lifespan"
 "littermate" "lme" "lobar" "lobata" "longiradiatum" "lonza" "lucifugus" "lymphadenopathy"
 "lymphopenia" "macrodomain" "macula" "magnater" "magnetotherapy" "magnoliae" "makeblastdb"
 "mamastroviruses" "mangabey" "maniculatus" "manuals" "mappings" "math" "maturases" "mcrobiome"
 "medulla" "melanocentra" "meleagridis" "mengovirus" "menoxenia" "mesenteroides" "metadata"
 "metagenome" "metagenomes" "methylbenzidine" "microbiota" "microhematospermia" "microplate"
 "microplates" "microsystems" "microti" "microtissue" "microtiter" "midbrain" "midgene" "midiprep"
 "midpoint" "millennia" "minimise" "minke" "misdiagnose" "miseq" "mismatch" "mitis" "mofetil"
 "molossus" "monash" "monocytogenes" "monolayer" "monolayers" "monophenanthrenes" "montanum"
 "morpholino" "mortem" "motile" "mucosa" "mulatta" "multcomp" "multi" "multicenter" "multichip"
 "multiclass" "multicolour" "multicycle" "multidomain" "multiflorum" "multilineage" "multipathogen"
 "multisite" "multivariate" "multiwell" "multocida" "muramyldipeptide" "muris" "musculature"
 "musculus" "mutandis" "myocardium" "myofibroblasts" "n" "nano" "nanomaterials" "nanotechnology"
 "nasopharynx" "natricum" "naïve" "ncifcrf" "nearest" "nebulizer" "necropsy" "neededan"
 "needlestick" "negatives" "nemerosin" "neutralizers" "neutropenia" "neutrophilia" "nhri" "niger"
 "nigripes" "nivea" "nlme" "noncapsid" "noncompliant" "noncp" "nonduplicate" "nonhotspot"
 "nonhuman" "nonleaky" "nonpathogen" "nonpneumonia" "nonsignificant" "nonsteroid" "normalizer"
 "norvegicus" "nosology" "novels" "novo" "numberings" "nuocytes" "objectives" "oblongata" "oedema"
 "officinalis" "offs" "oldhamii" "olor" "olympus" "omics" "oncology" "oncolysate" "oncolysates"
 "ones" "onsite" "openepi" "optima" "org" "organoids" "organophosphorus" "orientalis" "oropharynx"
 "ortholog" "orthologue" "orthologues" "otu" "ought" "outgroup" "overdose" "overpack" "overpacks"
 "overuse" "overview" "ovo" "oxygenases" "pairings" "pairwise" "pancreatitis" "panelists"
 "papyrifera" "parabiont" "paracrine" "parainfluenza" "paraspeckle" "parechovirus" "parenchyma"
 "parklands" "particulate" "parvo" "parvum" "passerine" "passerines" "pastureland" "pathologies"
 "pathophysiology" "pathotype" "patientswere" "pdf" "pelage" "pelltobarbitalum" "penelope" "pepino"
 "peprotech" "peptone" "perhaps" "pericarp" "peroxygen" "pestis" "pestiviruses" "petascale"
 "phagemid" "phagemids" "pharma" "pharmacophore" "phasings" "phenanthrenes" "phenols"
 "phenylaminocarbonyl" "phenylmethanesulfonyl" "phonmenon" "phosphoinsoitides" "phosphorimager"
 "phosphorodiamidate" "photopsia" "photoreceptors" "phyla" "phylogeny" "phyloseq" "physiopathology"
 "phytochemistry" "picobirnavirus" "pinna" "pintail" "pinworms" "pipiens" "piscicida" "plantarum"
 "plasmidless" "plasmon" "platyrhynchos" "plectasin" "pmole" "pneumococci" "pneumococcus"
 "pneumoencephalitis" "pneumophila" "pneumosphere" "pointes" "polyethylenimine" "polylinker"
 "polymorphism" "polyphaga" "polyprotetin" "polyserum" "polytomy" "positives" "postcapture"
 "postexposure" "postmortem" "postpartum" "poult" "poults" "pre" "predictiveness" "preterm" "primo"
 "prioritise" "procalcitonin" "prodrome" "professionals" "progeny" "propeptide" "protectotypes"
 "proteome" "proteomes" "protozoon" "proven" "pseudofowl" "pseudogene" "pseudogenomes" "pseudoknot"
 "pseudomallei" "pseudotype" "pseudoviruses" "psittaci" "psittacine" "pteropodid" "pulldown"
 "pulmonology" "pumilus" "pusillus" "putorius" "qiagen" "quasi" "quasispecies" "quinones" "quo"
 "racemosa" "ramapo" "raptors" "raybiotech" "rcf" "readout" "realtime" "reassortant" "recognise"
 "reframe" "reinfections" "relatedness" "reniformis" "replicon" "replicons" "representatives"
 "repurpose" "responders" "reticulum" "retro" "reuptake" "reuse" "rewritten" "rhamnosus"
 "ribonucleases" "ribotypes" "richiardii" "ringspot" "roseus" "rounders" "rpm" "rubra" "rubripes"
 "ruficollis" "saikochrome" "saikochromoside" "saikoisoflavonoside" "salamandrivorans"
 "sanderlings" "sanger" "sanguineum" "sans" "saponins" "sarmentosa" "scalers" "scbt" "sciureus"
 "scorzonerifolium" "scotomata" "screenings" "scriptstyle" "secretome" "semi" "sensu" "septica"
 "sequelae" "sequencinggo" "sero" "serogroup" "serogroups" "serology" "serotype" "serotypes"
 "serovars" "sewn" "shaken" "sharps" "shedders" "shipmentthe" "shorebirds" "shovelers" "shutoff"
 "sialodacryoadenitis" "sibiricum" "sigmaaldrich" "silico" "simplex" "sinusoids" "smegmatis"
 "socio" "solids" "solubles" "spacer" "spectrometer" "spectrophotometer" "spongiform" "spoonbills"
 "sporogenes" "ssp" "stakeholders" "standalone" "staphylococci" "stearothermophilus" "stemness"
 "stepwise" "sterilizers" "stirrer" "strepera" "streptavidine" "stressful" "striata" "stricta"
 "strongyle" "styryl" "subclass" "subclasses" "subclusters" "subelliptica" "subheaders" "suborders"
 "subsp" "subspecies" "substudy" "subtilis" "subtype" "sulphonamides" "sunscreens" "supernatant"
 "supernate" "sylvaticus" "sylvestris" "symptomatology" "synteny" "tachypnea" "tachypnoea" "taken"
 "tarda" "tarentolae" "taupe" "taxa" "tcc" "tcg" "tct" "teals" "tendae" "teno" "terrae"
 "terrestris" "tetrad" "tetrads" "tetramethyl" "tetramethylbenzidine" "tetrazolium" "tga" "tgc"
 "tgg" "tgt" "thaliana" "therapsids" "thermo" "thermocycler" "thermofisher" "thermophilum"
 "thermoprofile" "thiazolopyrimidines" "thomsonii" "thrombi" "thrombomoduline" "thumbprint"
 "tibialis" "timeframe" "timepoint" "titer" "titre" "toluidine" "toolbox" "topologies" "topology"
 "townsfolk" "trachomatis" "transblot" "transcriptome" "transducer" "transgenes" "transwell"
 "triage" "trimester" "trisodium" "tristyla" "triticale" "troposphere" "trypanosomatid"
 "trypanosomatids" "tryptose" "ttc" "ttg" "tubule" "tubuli" "turgida" "tylophoridicine"
 "tymoviruses" "typhimurium" "u" "ubisemiquinones" "ucsc" "browser" "postprocess" "ul" "ultilise"
 "ultracentrifuge" "ultradeep" "ultrafine" "umbels" "un" "undergone" "underpinnings"
 "understandings" "undertaken" "ungulate" "ungulates" "univariate" "unmet" "unresponsiveness"
 "urothelium" "usefull" "utero" "vaccinologists" "valaciclovir" "valuean" "var" "variables"
 "variola" "vasorum" "vdw" "vegan" "vena" "vesiculovirus" "veterinarians" "villi" "villus"
 "viraemia" "viremia" "viridae" "virocides" "viroporin" "viroporins" "virotherapy" "virotype"
 "viscera" "vitro" "vivax" "vivo" "viz" "washings" "wastewater" "waterbodies" "weaner" "webpage"
 "website" "wellness" "wetland" "wetlands" "wherefrom" "whooper" "wigeon" "wijc" "withdrawn"
 "wmpij" "workflow" "workflows" "workgroups" "workup" "worn" "woven" "written" "wto" "www" "x"
 "xenotransplants" "zoonose" "zoonoses" "zymogens" "à" "ѱm")))
    :test #'equalp))


(defparameter *MixedCase-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*MixedCase-Unknown-Words*) (symbol-value `*MixedCase-Unknown-Words*))
         '(
("AAstV" "ABHs" "AICmin" "AUCs" "Accapezzato" "AccuScript" "Aconitum" "AdV" "Adachi" "Adj" "Aedes"
 "Affymetrix" "AiV" "Aichi" "Alan" "Aldrich" "Alere" "Alisma" "Allam" "Allexi" "Almere"
 "AlphaImager" "Alphaherpesvirinae" "AlwNI" "AlwNl" "Alzheimer" "Amazon" "Americans" "Amersham"
 "Amezuca" "Ampelo" "Ampelovirus" "AmpliTaq" "Andes" "Angelicae" "AngioVue" "Anigen" "Anseriformes"
 "Anthos" "AntiHCV" "AntiHIV" "Aotus" "Apicomplexa" "Apicomplexans" "Apodemus" "ApopTag" "Aquatex"
 "Argas" "Arn" "ArrayExpress" "Arteriviridae" "Asahi" "Ashanti" "Ashfaq" "Atractylodis" "Auckland"
 "Augustijns" "Augustowska" "Auxotrophy" "Avastrovirus" "Avicel" "Axioskop" "BAstV" "BIAcore"
 "BSCs" "Bafinivirus" "Baiji" "Balak" "Baltimore" "Bamako" "Bandelin" "Basingstoke" "Basse"
 "Bassersdorf" "Bastrovirus" "Batrachochytrium" "Bayes" "BdAstV" "BeGenDiv" "Beaudette" "Beckman"
 "Becton" "Beichaihu" "Beijnum" "Beirne" "Bekerman" "Beluga" "Bencao" "Bensheim" "Benth"
 "Besnoitia" "Betaherpesviruses" "Betazoid" "Bethesda" "Bewick" "Beyotime" "Bhattacharyya" "BigDye"
 "Bihar" "Billerica" "Biltech" "BinaxNOW" "Bio" "BioEdit" "BioFire" "BioLeaf" "BioMérieux"
 "BioProject" "BioRad" "BioWhittaker" "Bioanalysier" "Bioanalyzer" "Biocare" "Biochrom" "Bioedit"
 "Biofire" "Biogot" "Bioleaf" "Biolegio" "Biomatters" "Bioproject" "Bioscences" "Bioss" "Biosystem"
 "Biotec" "Biotech" "Blair" "Blastocladiomycota" "Bletilla" "Blmh" "Bloomberg" "Blosum" "BoAstV"
 "Boehmeria" "Boehringer" "Boelaert" "Bonferroni" "Boonyasuppayakorn" "Borba" "Borna" "Bowtie"
 "Brachyspira" "Branford" "Branta" "Brasp" "Brea" "Brenan" "Briggs" "Brno" "Broussonetia"
 "Brouwers" "Browne" "Bruker" "BsYetJ" "BstBI" "Bubendorf" "BufAstV" "Bulletkit" "Buoyem"
 "Bupleuri" "Bupleurum" "Burdick" "Burgos" "Burkitt" "Burkoderia" "Burlingame" "Burm" "CAstV"
 "CHCl" "CLs" "CNTs" "CVi" "CaAstV" "CaliburTM" "Caliper" "Callison" "Camelus" "Candidatus"
 "Cantonese" "Capillo" "CapturePro" "Carcino" "Cargill" "Carla" "Carlavirus" "Carlo" "Carlos"
 "Carlsbad" "Carolina" "Carpinteria" "Cary" "Catharanthus" "Caudovirales" "CcAstV" "CellQuest"
 "CelliGO" "Cerami" "Cercocebus" "ChAstV" "Chaihu" "Chandran" "Charadriiformes" "Chatsworth"
 "Cheonan" "Chevrier" "Chloracidobacterium" "Chordata" "Chordopoxvirinae" "Chris" "Chrysobalanus"
 "Cincinnati" "Cinnamomum" "Clara" "Clausena" "Clinicaltrials" "Clinicians" "Clontech"
 "Closteroviridae" "Clp" "ClustalW" "CoPt" "Coccidioides" "Cochrane" "Colombiformes" "Columbus"
 "Combo" "CommCare" "Commitee" "Commun" "Conakry" "Conceptualizations" "Coomassie" "Coquillettidia"
 "Coraciiformes" "Cornus" "Corp" "Covidien" "CreateDB" "Crimean" "Crocuta" "Csatarys" "CslAstV"
 "Cttarget" "CuO" "Culex" "Curix" "CviQI" "CyTOF" "Cygnus" "CytBF" "CytBR" "Cytofluorometer"
 "Cytospin" "DALYs" "DAstV" "DESeq" "DIAplex" "DPGs" "Dactylogyrus" "Daecke" "Daedalus" "Dako"
 "Dallas" "Dario" "Dawley" "DcAstV" "Deborah" "Dedania" "Deventer" "Dhaka" "Diego"
 "Diphyllobothriidae" "Diphyllobothrium" "Dipylidium" "Dirichlet" "Disse" "Dividich" "Doha"
 "Doraville" "Dotter" "Dowall" "DreamTaq" "DsiRNA" "Duksan" "Dulbecco" "DuoFlow" "Dur" "Durban"
 "Duren" "Duroc" "Dux" "DyLight" "ECEs" "EIDs" "ENMs" "ERc" "ESb" "Earle" "Ebolavirus" "EcoHealth"
 "Ecohealth" "Edem" "Edmonston" "Edt" "Eimeria" "Einav" "Ekins" "Elaeocarpus" "Empel" "Enchéry"
 "Endnote" "Endopath" "Engchanil" "Entomopoxvirinae" "Eppendorf" "Eptesicus" "Eptesipox" "Erasmus"
 "Erlangen" "Ersatz" "Eugene" "Euonymus" "Eurasia" "Eurobio" "Eurofins" "EvaGreen" "Evelyn"
 "Evrogen" "Ex" "ExNPGP" "FACSAria" "FACSAriaTM" "FAstV" "FECs" "FRCs" "FaeG" "Falzarano" "Farias"
 "FastQC" "FastStart" "Fatima" "FeLV" "FedF" "Fedson" "Felis" "Felix" "Fermon" "Ficus" "FigTree"
 "FilmArray" "Finet" "Flexiviridae" "Florez" "Flos" "FlowJoTM" "FluSurver" "Fluc" "Fluidigm"
 "Fluoview" "Forma" "Foshan" "Fraxinus" "Frederick" "FreeZone" "Frenkelia" "FspI" "FtsH"
 "Fullerton" "Furovirus" "Fèvre" "GAAPs" "GFAstV" "GInaFiT" "Gagnep" "Gaithersburg" "Gallen"
 "Galliform" "Galliformes" "Gammaherpesvirinae" "Gandini" "Gangmu" "Garcinia" "Garulli" "Geiger"
 "Geisbert" "GenBank" "GenChip" "GenMark" "GenScript" "Genbank" "GeneChip" "GeneChipPrimeView"
 "GeneJET" "GeneTex" "GeneWiz" "Genechip" "Genscript" "Geobacillus" "Gibco" "GibcoTM" "Giemsa"
 "Giessen" "GigaDB" "Gils" "GlutaGro" "Glycyrrhizae" "GmBH" "GolgiStopTM" "Goodsan" "Google"
 "Guangdong" "HAstV" "HAstVs" "HCWs" "HELs" "HHMastV" "HMEs" "HQRs" "HRc" "HSURs" "Haemonchus"
 "Haldane" "Hamamatsu" "Hangzhou" "Hannon" "Hantaan" "Haoran" "Hayata" "HeSCs" "Heatmaps"
 "Heidelberg" "Heji" "Hemsl" "Hemstead" "Hendra" "Hepatozoon" "Hepeviridae" "Herba" "Hercules"
 "Herit" "Herndon" "HiFiBio" "HiScreen" "HiSeq" "Hilden" "Hiload" "Hilst" "Himalayan" "Hoff"
 "Holstein" "Homogenates" "Honeywell" "Honolulu" "Hoore" "Hopkins" "Huai" "Huimin" "HxD"
 "Hypoxemia" "Hér" "ICUs" "IIPSs" "IRDye" "ISREs" "ISVdb" "Ibidi" "Identifier" "Ifna" "IgV" "IgY"
 "Iij" "Ilium" "Illumina" "ImageJ" "ImageQuantTL" "Imager" "Influnet" "Ingelheim" "Ingolia"
 "Innocula" "Inst" "Intel" "Interferometry" "Internet" "InvivoGen" "Ipswich" "Irmsch" "Isavirus"
 "Iscove" "Istanbul" "Itlay" "Ives" "Jaccard" "Jamestown" "Janvier" "Jembrana" "Jena" "Jennio"
 "Jenoptik" "Jiancheng" "Jianchuan" "Jiangsu" "Jinmiao" "Johne" "Johns" "Jolla" "Jufang"
 "Junglinster" "Juss" "Justus" "Juz" "KNMvD" "Kaibao" "Kaposi" "Kaposica" "Karber" "Katayama"
 "Kathryn" "Kcv" "Kellaway" "Kenneth" "Kft" "Kiat" "Kinnaird" "Kirkegaard" "Klenow" "Kmer" "Koay"
 "Koff" "Konica" "Kotla" "KpnI" "Krefeld" "Kui" "Kumasi" "Köln" "LMICs" "LaSota" "Laaksonen"
 "LabChip" "Labconco" "Laboratpries" "Lafayette" "Laikipia" "Lamballerie" "Landrace" "Lasergene"
 "Lassa" "Latin" "Lausanne" "Lawsonia" "Leatherhead" "Legionnaire" "Leguminosae" "Leibniz"
 "Leibovitz" "Leiden" "Leishmaniases" "Leslie" "Lethe" "Liaoyang" "Licor" "Liebig"
 "LifeTechbologies" "LightCycler" "LightCyler" "Likert" "Lincoln" "Lindl" "Linux" "LmjF" "Loeffler"
 "Lombardy" "Lonza" "Lottia" "Loughran" "Louis" "Lue" "Lumnitzera" "Lunzen" "Luria" "Lusaka"
 "Lycoris" "Lyme" "MAstV" "MBq" "MDGs" "MDSCs" "MIDs" "MOTs" "MRCAs" "MREs" "MWCNTs" "Macrocephala"
 "Macrocephalae" "Maculavirus" "Madrid" "Mafart" "MagNA" "Magyarország" "Mamastrovirus"
 "Mammalogists" "Manassas" "Mandari" "Manila" "Mannendorf" "Mannheim" "Mapper" "Mardivirus"
 "MariaDB" "Marietta" "Martha" "Martinique" "Martinson" "Marzi" "Mascola" "MassLynx"
 "Mastadenovirus" "Materia" "Materials" "MathWorks" "Matlab" "Matlashewski" "MaxiSorp" "McMaster"
 "McVey" "Mccullers" "MedCalc" "Mediatech" "Medica" "MegaMUGA" "Megachiroptera" "Megascript"
 "Meleagridinae" "Menangle" "Menthae" "Mentzer" "Merck" "MetFS" "MetaVelvet" "Metagenome" "MiAstV"
 "MiGEC" "MiSeq" "MiXCR" "MicroDB" "Microchiroptera" "Microsoft" "Microsystems" "Microtus"
 "Microviridae" "Milan" "Milbemax" "Millipore" "Milpitas" "Miltenyi" "Mimivirus" "MinElute"
 "Miniopterus" "Minolta" "Mirus" "Mizui" "MluI" "MoPn" "Mohács" "Molossidae" "Monte" "Monza"
 "Moraceae" "Mothur" "MssI" "MuV" "Muloi" "MultiAmplicon" "Multichip" "Multiwell" "Murr" "Mustela"
 "Mutatis" "Myodes" "Myotis" "Myoviridae" "Myrica" "Médecins" "NArm" "NCBIs" "NGOs" "NTHi"
 "Nagarajan" "Nakhon" "Nanchaihu" "Nanopore" "Naphtalen" "Napolitani" "Nav" "Negatives"
 "NeoMarkers" "Nettoie" "Neufeld" "Newcastle" "NextSeq" "NexteraXT" "NibleGen" "Nidovirale"
 "Nidovirales" "Nii" "Nijmegen" "Nikon" "NimbleScan" "Nipah" "NoA" "Nobel" "Nombre" "Nontarget"
 "Norcross" "Nostoc" "Nottingham" "Novartis" "Nuaille" "NucAway" "NucT" "NucliSENS" "Nymphaea"
 "OAstV" "ODNs" "ODbank" "OVs" "Ogbonna" "Ogn" "Ohashi" "Ohwi" "Oligoadenylate" "Omniscript"
 "Oncology" "Oncomine" "Oon" "OpenEpi" "Optovue" "Orchidaceae" "Orientia" "Origene"
 "Orthomyxovirus" "Orthopneumovirus" "Ostend" "Ostertagia" "Outreach" "Ovid" "Oxoid" "Ozden"
 "PAstV" "PHiDCV" "PLpros" "PQGs" "PQSs" "PRRSv" "PSs" "PTBs" "PacBio" "PacI" "Paeoniae" "Palo"
 "Panthera" "Paola" "Papillomaviridae" "Parainfluenzavirus" "Paramecium" "Parechovirus" "Parfrey"
 "Parris" "Partula" "Passeriformes" "Passerine" "Pasteur" "Patrick" "Patrin" "Paucha" "Pefablock"
 "Pelecaniformes" "Pellicelli" "Peltier" "PenStrep" "PeproTech" "Peqlab" "PerkinElmer" "Peromyscus"
 "Persia" "Pestivirus" "Pfiesteria" "Phanom" "PharmaDB" "Pharmacia" "Phasianinae" "Phenome"
 "Photoshop" "Phyllanthus" "PhysBinder" "Phytolacca" "PiAstV" "Piccini" "Pico" "PicoTitrePlate"
 "Pingtung" "PippinPrep" "Piscataway" "Pisum" "Pittsburgh" "Plectropterus" "Pneumococci"
 "Pneumoviridae" "Podoviridae" "Poir" "Poisson" "Policlinico" "Polygonum" "Polynesia"
 "Polysciences" "Poria" "Positives" "Potex" "Potexvirus" "Precellys" "PrimeScript" "PrimeScriptTM"
 "PrinSeq" "Produits" "Profiler" "Promega" "PrtB" "Pseudogymnoascus" "Pteropid" "Pteropodidae"
 "Pteropus" "Pulser" "Purdue" "Puurs" "QALYs" "QTof" "QiaExpressionistTM" "Qiagen" "Qinghai"
 "Quant" "Quantifast" "Quaranilvirus" "Qubit" "QuickVue" "Quidel" "RAstV" "REOs" "RNAeasy"
 "RNAlater" "RNeasy" "RPFs" "RTVue" "RabAstV" "Radix" "Ranavirus" "RayBio" "RealTime" "Realtime"
 "Recens" "Rehse" "Renilla" "Reno" "Reo" "Restrictif" "Rfree" "Rhabditida" "Rhyne" "RiboBio"
 "RiboCluster" "RiboLock" "RiboSeq" "RiboTrap" "Rij" "Ringpu" "Roadmap" "Rochester" "Rockford"
 "Rockville" "Roizman" "Romanelli" "Romans" "Rome" "Roswell" "Rousettus" "Routy" "Rwork" "RxxxxxR"
 "Régime" "SDGs" "SFVs" "SGAs" "SIVagm" "SIVcol" "SIVcpz" "SIVlhoest" "SIVmac" "SIVsm" "SIVstm"
 "SIVsyk" "SIVwrc" "SPNuc" "SPUsp" "SSBPs" "Saharan" "SalI" "Sambucus" "Samsung" "Samtools"
 "Sanger" "Sant" "Santé" "Sapienza" "Sartorius" "Saurauia" "Savarino" "Saxifraga" "Scanco"
 "Scheffe" "Schiller" "Schroder" "Schum" "Scopus" "ScreenTapes" "Scrophularia" "Scutellariae"
 "ScyTek" "Sdn" "Sdpr" "Seaview" "Securité" "Semliki" "Sendai" "Seng" "Sensiscript" "Seoul"
 "Sequencher" "Sequest" "Seradigm" "Serengeti" "Sertoli" "Shennong" "Shivanna" "Shytaj" "Sida"
 "Siddharth" "Siebert" "Signa" "Sij" "Simplex" "Sindbis" "Siphoviridae" "Sliema" "SmartPLS"
 "Somerville" "Sonn" "Sota" "Sourisseau" "Soweto" "Spectralis" "Spirometra" "Spironucleus"
 "Spirurida" "Springer" "Spumaretrovirinae" "Sputasol" "SslAstV" "Stamaril" "Stanford" "Stedim"
 "Steller" "StemPro" "StepOnePlus" "Stollery" "StopGo" "Strijp" "Strophanthus" "Stupp" "Sudanese"
 "Suntreso" "SuperMix" "SuperScript" "SuperScriptIII" "Superdex" "Superflow" "Supermix"
 "Superscript" "SureSelect" "SureSelectXT" "Surrey" "Sussex" "Sybr" "Syphacia" "São" "TAAs"
 "TALENs" "TAstV" "TRNzol" "TRSs" "TTSPs" "TaKaRa" "Tabel" "Tadarida" "Taeniidae" "Takara" "Taq"
 "TaqMan" "Taqman" "Tateishi" "Taubitz" "Taudactylus" "Taxonomer" "Tecan" "Techiman" "Techonology"
 "Therler" "Thermo" "ThermoFisher" "Thermoscan" "Thogotovirus" "Thonn" "Thorowax" "Thunb"
 "Tianbang" "Tiantan" "Tikoo" "TissueLyser" "Tmax" "Tmem" "Tobin" "Tobravirus" "Tock" "Togaviruses"
 "Toluidine" "Toronto" "Torovirus" "Torr" "Torre" "Torrey" "TouchTM" "Tracey" "Tranfections"
 "Trani" "Transducer" "TreeView" "Tribhuvan" "Tribulus" "Tricho" "Trichoplusia" "Trypanosomatidae"
 "Tuankou" "Tukey" "Turcz" "Turku" "TxM" "Tymoviridae" "Typhi" "UFPs" "UGc" "UGh" "UbV" "UbVs"
 "Ulm" "Ulsan" "UltrafleXtreme" "Uneke" "Universidade" "Upjohn" "VCFtools" "VDJTools" "VHFs" "Vahl"
 "Vausselin" "Vellore" "Venn" "Ventana" "Venusil" "Vert" "Vigerust" "Villinger" "VirMet" "ViroCyt"
 "VirtualNextGenSequencer" "VirusTAP" "Viti" "Vitiviruses" "Vivaspin" "Waals" "Wageningen"
 "Waltham" "Warrington" "Waseca" "WeChat" "WebLogo" "Weesp" "Wegener" "Weibull" "Weil" "Wellcome"
 "Westbrook" "Whatman" "Whitney" "Widder" "Wikipedia" "Wilcoxon" "Willd" "Wolbachia" "Worp"
 "Worthington" "Wycombe" "Xanthium" "XbaI" "Xeon" "Xevo" "Xiaoyaosan" "Xuewen" "Xylella" "Yersina"
 "YetJ" "Yikang" "Yorba" "Yosemite" "Yunnan" "Zaritsky" "Zealanders" "Zeiss" "Zenodo" "ZeptoMetrix"
 "Zhejiang" "Zingiberis" "ZnM" "Zostera" "Zurich" "Zwick" "aDMEM" "aRNA" "Anser" "assignTaxonomy"
 "chIFITM" "dadaMulti" "drVM" "eArrayXD" "ePlex" "fGCM" "fastqPairedFilter" "gDs" "Gallus" "hAdV"
 "hGAAP" "hTel" "hVISA" "hlyA" "huHep" "iCORN" "iMotif" "iPair" "iRepertoire" "iTaq" "Ingroup"
 "Interferome" "justConcatenate" "kxM" "mCCPH" "mIBV" "mMachine" "mMessage" "mTRAIL" "maxEE" "maxN"
 "mergeMulti" "Molossus" "Phyllostomidae" "nisR" "noGenus" "noTax" "Olympus" "pBHGlox" "pBind"
 "pCYT" "pDluc" "pETpagP" "pLUCF" "pNA" "pSEC" "pUC" "pUSEamp" "pcDNA" "pdInfoBuilder" "Peprotech"
 "pmirGLO" "polyA" "rIBV" "rawDB" "recNDV" "refDB" "regressionSSQ" "rtPCR" "sCCPH" "sfRNA"
 "smallRNA" "tBLASTx" "truncLen" "truncQ" "vBMD" "vDUB" "vDUBs" "vGAAP" "vRNP")))
    :test #'equalp))


(defparameter *FirstNames*
    (remove-duplicates
      (append 
         (when (boundp '*FirstNames*) (symbol-value `*FirstNames*))
         '(
("Alexa" "Alexander" "Anderson" "Andrea" "Ann" "Charles" "Craig" "DAVID" "Daniel" "Douglas" "Evan"
 "Fernando" "Gary" "Giorgio" "Gordon" "Henry" "James" "Janet" "Jian" "Joshua" "Katja" "Kim" "Linda"
 "MEGAN" "MEM" "Maria" "Matteo" "Michael" "Niranjan" "Oliver" "Paulo" "Qian" "Robert" "Rodrigues"
 "Stephen" "Swee" "Thomas" "Werner")))
    :test #'equalp))


(defparameter *LastNames*
    (remove-duplicates
      (append 
         (when (boundp '*LastNames*) (symbol-value `*LastNames*))
         '(
("Abel" "Abolins" "Abulreesh" "Adam" "Adams" "Akaike" "Alberdi" "Albrecht" "Alexa" "Alexander"
 "Almeida" "Altfeld" "Altschul" "Amato" "Ambrose" "Amet" "Amezcua" "Andersen" "Anderson"
 "Andersson" "Andrews" "Ankeny" "Aplenc" "Arbore" "Archie" "Arnberg" "Avirutnan" "Awasthi" "Ayadi"
 "Ayala" "Azevedo" "Babayan" "Backhans" "Bajénoff" "Baldwin" "Ballestas" "Banerjee" "Barclay"
 "Barksdale" "Bartenschlager" "Barth" "Bartholomew" "Basbaum" "Bassano" "Baumgartner" "Bavia"
 "Bayne" "Becker" "Becklund" "Bedford" "Beebe" "Bejon" "Benjamini" "Benneker" "Benson" "Berendsen"
 "Bergamini" "Bergelson" "Bernasconi" "Bernet" "Bernin" "Beura" "Bhattacharya" "Bijur" "Blanchard"
 "Blanckenhorn" "Bock" "Bolker" "Bonaparte" "Borah" "Borody" "Bouchet" "Bourmaud" "Bousema"
 "Bouwhuis" "Bozzoni" "Bradford" "Bramley" "Brandt" "Braun" "Brehm" "Breinin" "Brenton" "Britanova"
 "Broekhuis" "Brownlie" "Bruton" "Budas" "Buer" "Buller" "Burgener" "Byers" "Bönner" "Cabie"
 "Calisher" "Caljon" "Callahan" "Campbell" "Cardinale" "Carnero" "Carroll" "Cassel" "Cazalla"
 "Cesana" "Chalfin" "Chalmers" "Chami" "Chandriani" "Chang" "Chao" "Charley" "Charlson" "Chauhan"
 "Chen" "Chhabra" "Chia" "Chiang" "Choi" "Chou" "Chu" "Chun" "Chung" "Cirelli" "Clarke" "Clarkson"
 "Clayton" "Clemente" "Clemson" "Clevers" "Coffman" "Cole" "Colin" "Colles" "Collins" "Compton"
 "Conde" "Conlan" "Cooray" "Cosgrove" "Costello" "Coulston" "Craig" "Cruz" "Cubillos" "Cui"
 "Curtis" "DAVID" "Damu" "Danecek" "Daniel" "Darmstadt" "Daszak" "Degn" "Degnan" "Dehaven" "Demant"
 "Denny" "Dethlefsen" "Deutsch" "Devaux" "Dickinson" "Dickx" "Djebali" "Doolittle" "Doosje" "Doran"
 "Dorig" "Douam" "Douglas" "Dovidio" "Drabløs" "Dubin" "Dumont" "Duncan" "EID" "Eastwood"
 "Ebenbichler" "Edmondson" "Ekblom" "Ellegren" "Ellemers" "Ericsson" "Ernst" "Erny" "Ewald"
 "Ezenwa" "Falk" "Fallacara" "Fatica" "Fearon" "Feenstra" "Feng" "Fenner" "Fenton" "Fernando"
 "Ferrari" "Fiebiger" "Fingeroth" "Fink" "Fischer" "Fisman" "Fitzpatrick" "Fleckenstein" "Fletcher"
 "Fleuren" "Fodor" "Fonio" "Freccero" "Freitas" "Fremont" "Freund" "Friedman" "Fu" "Fuchs"
 "Fukanoki" "Förster" "Gacias" "Gaertner" "Garenne" "Gautam" "Geng" "Girard" "Girdwood" "Girgis"
 "Giroud" "Godeke" "Goller" "Gomez" "Gonzalez" "Gordon" "Gorham" "Gough" "Gould" "Goymann"
 "Graczyk" "Graham" "Gralinski" "Greenaway" "Greenstone" "Grimwood" "Groenier" "Grol" "Gronemus"
 "Grossniklaus" "Grubb" "Gupta" "Gurley" "Guzman" "Guénet" "HA" "HAU" "HU" "Hafner" "Hahn"
 "Hamilton" "Hampton" "Hansbro" "Hanson" "Harris" "Hastie" "Hataya" "Hatha" "Hau" "Hebb" "Hebert"
 "Hedrich" "Hein" "Heitlinger" "Henry" "Herberg" "Herpin" "Hess" "Hewstone" "Higgins" "Higgs"
 "Hilbert" "Hilty" "Hirose" "Hirsch" "Hochberg" "Hodge" "Hoekstra" "Hofer" "Hoffmann" "Hogg"
 "Holdsworth" "Holmes" "Hooper" "Horvat" "Horwitz" "Hothorn" "Hou" "Howley" "Hoy" "Hsiao" "Hsu"
 "Hu" "Huang" "Huchard" "Hufeldt" "Hughes" "Hunig" "Hurley" "Höner" "Hüttenhain" "Ikeda"
 "Ilinskaya" "Imamura" "Iqbal" "Irvine" "Isaacs" "Ishii" "Iwakiri" "Jackson" "Jakubik" "James"
 "Jampol" "Jasirwan" "Jaspers" "Jayasekera" "Ji" "Jiang" "Jin" "Johnson" "Jong" "Jose" "Jørgensen"
 "Kacani" "Kadurugamuwa" "Kahn" "Kaiko" "Kalogeris" "Kambara" "Kapadia" "Kapczynski" "Karnauchow"
 "Kartzinel" "Kassa" "Kassebaum" "Kato" "Kaur" "Kaushansky" "Kawabata" "Kay" "Keane" "Kear"
 "Kelada" "Keyaerts" "Khoruts" "Kijlstra" "Kim" "Kimura" "Kitagawa" "Klaassen" "Kleijn" "Klein"
 "Klotz" "Knipe" "Knowles" "Koch" "Koenig" "Kolev" "Kool" "Koraka" "Koscielny" "Kostavasili"
 "Kover" "Kracht" "Kraft" "Kramer" "Krebs" "Kreisinger" "Krishna" "Kruuk" "Kuan" "Kubo"
 "Kuczkowski" "Kulesza" "Kuo" "Kupatt" "Kurosu" "Kwon" "Kyle" "LAI" "Lagkouvardos" "Laine"
 "Lambrecht" "Lange" "Langhorne" "Latham" "Laupland" "Lederberg" "Legendre" "Lelieveld" "Lemiere"
 "Leone" "Leonelli" "Leroy" "Liao" "Liautaud" "Lieber" "Likos" "Lillehaug" "Lilue" "Lindholm"
 "Lipoldová" "Liszewski" "Liu" "Loeuillet" "Logan" "Loney" "Lotter" "Lozupone" "Lubinski" "Lukeš"
 "Lutz" "Mabbott" "Mackay" "Mackenzie" "Macpherson" "Madec" "Madeley" "Magez" "Mahgoub" "Mahmud"
 "Maizels" "Majewska" "Manchester" "Mangandi" "Manokaran" "Martella" "Martina" "Matheis" "Mathews"
 "Matsuda" "Mawatari" "Mayer" "McLaren" "McMurdie" "Mckenzie" "Mears" "Mendel" "Meng" "Menke"
 "Meotti" "Mestas" "Michael" "Middleton" "Milstone" "Miyakawa" "Mizuguchi" "Moeller" "Moir"
 "Molleman" "Montefiori" "Montgomery" "Moore" "Morgan" "Mori" "Moriwaki" "Morrison" "Morse"
 "Moulton" "Moyo" "Mu" "Muench" "Muller" "Mullick" "Munster" "Muqaku" "Murray" "Muruve" "Muzyka"
 "Müller" "Nadler" "Nagano" "Naganuma" "Nagel" "Najarro" "Nanbo" "Naniche" "Napthine" "Nemerow"
 "Neurath" "Newell" "Newman" "Nicklas" "Nicod" "Nikolin" "Nishitsuji" "Niskanen" "Nomura" "Nonaka"
 "Nouaille" "Nowell" "Noyes" "Nussbaum" "Nussey" "Oberdorster" "Ochman" "Odet" "Ogembo" "Okroj"
 "Oladele" "Oldstone" "Olsen" "Ooi" "Opavsky" "Oreper" "Orrock" "Osterhaus" "Otten" "Ouyang"
 "Pache" "Palmenberg" "Palumbo" "Pangburn" "Pari" "Parida" "Patel" "Paton" "Paulussen" "Pavia"
 "Pearson" "Pedersen" "Peng" "Pereira" "Persson" "Piedrafita" "Pielou" "Pijlman" "Pinter"
 "Pleschka" "Plutzer" "Poelen" "Poidinger" "Poole" "Popper" "Pornon" "Posch" "Powell" "Pyaram"
 "Qian" "Quast" "Raghavan" "Ramasamy" "Rapicavoli" "Rausch" "Rayner" "Reese" "Refsum" "Reich"
 "Reijnders" "Reza" "Rhee" "Richards" "Risley" "Rivera" "Robert" "Robertson" "Robinson" "Robison"
 "Roby" "Roche" "Rochford" "Rockx" "Rodrigo" "Rodrigues" "Rogers" "Rollinger" "Rong" "Rosenberg"
 "Rosengard" "Rossetto" "Roth" "Rother" "Rothwarf" "Russo" "Rutherford" "Rux" "Ryter" "SARSTEDT"
 "SILVA" "SMART" "Saayman" "Sahu" "Saifuddin" "Samanta" "Samson" "Samuel" "Santoro" "Sapolsky"
 "Sasaki" "Schifano" "Schröder" "Schubert" "Schwanke" "Schwarz" "Schwensow" "Segal" "Segerman"
 "Sen" "Seok" "Servick" "Sfyroera" "Shafique" "Shafren" "Shamir" "Sharma" "Shastri" "Shaw" "Shenk"
 "Shimosaki" "Shirato" "Shope" "Siim" "Silva" "Simmonds" "Simpson" "Singh" "Sinha" "Sivan" "Skea"
 "Slater" "Sommer" "Sonoda" "Sood" "Spearman" "Spiller" "Sprague" "Srivastava" "Stanley" "Steinman"
 "Steitz" "Stoffels" "Stoiber" "Stuart" "Sudo" "Sunwoo" "Susal" "Svobodova" "Sweeney" "Szakonyi"
 "Takada" "Takagi" "Takano" "Takao" "Takemoto" "Takeuchi" "Tanaka" "Tannock" "Tasleem" "Tatematsu"
 "Tengs" "Thanchomnang" "Theiler" "Thiel" "Thielens" "Thiemmeca" "Thiyagarajah" "Thomas" "Thompson"
 "Tien" "Tisné" "Tola" "Tomai" "Tomlinson" "Tomor" "Torelli" "Torgerson" "Tremaroli" "Tsai"
 "Tsalik" "Tsiodras" "Tung" "Turnbaugh" "Tyler" "Ueda" "Underdown" "Uppal" "Vakharia" "Valencia"
 "Vanderplasschen" "Vannier" "Vasilakos" "Vaughan" "Venkatraman" "Verdolin" "Vickers" "Vidal"
 "Vijay" "Villena" "Viney" "Volanakis" "Vollenbroich" "Vollmers" "Wakimoto" "Waldenström"
 "Wapinski" "Wassarman" "Wathes" "Wege" "Wegner" "Weidner" "Weissmuller" "Weldon" "Werner" "Werren"
 "Whitlock" "Whittemore" "Wickham" "Wieferink" "Wilde" "Wilkinson" "Willcocks" "Wille" "Williams"
 "Willingham" "Willyard" "Wilson" "Wilusz" "Wishaupt" "Withenshaw" "Wobeser" "Wolff" "Wong" "Wu"
 "Wylie" "Würbel" "Xie" "Xu" "Yadav" "Yamakage" "Yamamoto" "Yao" "Yatsunenko" "Yi" "Yildirim"
 "Yoshiki" "Youden" "Yu" "Zaas" "Zakay" "Zamboni" "Zar" "Zelezniak" "Zeng" "Zhang" "Zhao" "Zhong"
 "Zhou" "Zhu" "Zhuang" "Zimmerman" "Zmora" "Zmud" "Zschaler")))
    :test #'equalp))

;; 2865 defined as a bio-entity


(defparameter BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-5301-5400
    (remove-duplicates
      (append 
         (when (boundp 'BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-5301-5400) (symbol-value `BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-5301-5400))
         '(
("###p" "##p" "#019-19741" "#1" "#11–13" "#14761" "#15640055" "#1B3-IIA" "#1–10" "#2" "#20090036"
 "#3" "#4" "#550992" "#551163" "#553035" "#553061" "#553652" "#557391" "#560510" "#563331"
 "#563854" "#563898" "#GSAjournals" "#MPP" "#p" "$$$p" "$$\\end{document}b" "$$\\end{document}F"
 "$$\\end{document}fE" "$$\\end{document}Ii" "$$\\end{document}IT" "$$\\end{document}N-I"
 "$$\\end{document}Ri" "$$\\end{document}RT" "$$\\end{document}α" "$$p" "$16.8 billion" "$5" "$50"
 "$7.3" "$p" "$US30,000" "&=\\dot{S}" ")/kg" ")/ml" ")/mL" ")/X" "***P" "**P" "**P<0.01" "*100%"
 "*P" "*P<0.05" "++" "+++" "++++" "+1" "+12" "+2.3" "+32%" "+35%" "+7.5" "+9.3%" "+I" "+I˙" "+p"
 "+R" "+R˙" "+ssRNA" "+U" "+wr⋅p" "-1,2,3-trihydroindolizidinium" "-1-piperazineethanesulfonic"
 "-3,5-diphenylformazan" "-8-phenyl-1-4H-1-benzopyran-4-one" "-AACACACTGAAATCAGACCTTG-3"
 "-AACUAA-3" "-AACUUA-3" "-AAGGAAAAAAGCGGCCGCCTCTGTGATATTGACCTCCACC-3"
 "-AAGGAAAAAAGCGGCCGCTTCTGTGATATTGACCTC-3" "-ACCAGCATCTTTTCCAACCG-3" "-ACTGCCAGTTCGTTTCAGT-3"
 "-AGAATCAGGCATCCCTCTGC-3" "-AGACCCCCTAGACAACAACAGCAACACT-3" "-ATAGCACCYTTGGGTGTCTG-3"
 "-ATGATATGAAAAACCATCGTTG-3" "-CACCATACTCACAACTGTGGCAG-3" "-CACCATCCATCTACTAGTGCTGAC-3" "-CACUAA-3"
 "-CAGGACGTCTAATGCAATACCT-3" "-CAGTCTTACCCCTCTTACC-3" "-CATCTTTACCTGAAATGCG-3"
 "-CATGCAGTTTGTTGGAGATCCT-5" "-CCGCTCGAGTTAGTGGTGATGGTGGTGGTGCATCACAGTGAGGTTGAGCT-3"
 "-CCGCTCGAGTTAGTGGTGATGGTGGTGGTGCCGCGTCGCCGGCTCGGGCAG-3"
 "-CCGCTCGAGTTAGTGGTGATGGTGGTGGTGGCGGTGGCGCGAGACGCC-3" "-CCGGAATTCAGGACGTGGACGCCGTGCC-3"
 "-CCGGAATTCAGGACTCCATGTATGGTTTCATCGGC-3" "-CCGGTGTCCACTCAGTGTTTAT-3" "-CCRTCATCAGANAGAATCATCAT-3"
 "-CCTGTACGTGGGGCCTTTAA-3" "-CCTTCCACAAAGTCCCTATTGC-3" "-CGCCAGTCGGCATCGTTTATG-3"
 "-CGCGGATCCGACCCAGGTGGTCCAGGTGAACG-3" "-CGGCATACAGCATCAGGTGCATAGGAG-3" "-CGGCGGTACAAGTCCAGCAT-3"
 "-CTAGCATTACTGCCTGATTGCCAATG-3" "-CTGTCTGTCATGGGGAATGAGT-3" "-CTTACTGGAGATCCCTGCCG-3" "-DENV-2"
 "-deoxy-uridine" "-end-labeled" "-G-tract" "-GACGGACCAGAGCGAAAGC-3" "-GAGATGCCTGAGACACCCAAA-3"
 "-GCAGCCCTGACGGTATCC-3" "-GCAGTCTCCTCTGAACAATCC-3" "-GCTGGCCCTGGTGAGGTTTGAT-3"
 "-GGACGACATCCTGAGCGAGT-3" "-GGACGATCTCAACAAGGTCAACTAAA-3" "-GGAGGCTGTGGATAAACTATTCC-3"
 "-GGGGGCTGCTGCAATGATGAAA-3" "-GGGRNNYYCC-3" "-GGTTGGGAYTATCCYAANTGTGA-3"
 "-GTCCTGTAGCTACCAAGGCAA-3" "-GTGACCTGGTTTTACCGTTTGA-5" "-GTGCAAACCGTTACCTTGCT-3"
 "-GTGCTGACGGGACGGTAAA-3" "-heptadecatriene-4,6-diyne-1-ol" "-in-oil" "-N-P" "-O-methylation"
 "-pentadecatriene-4,6-diyne-1-ol" "-TAGGAGGTGCCGCCATATCA-3" "-TCCACGAGGAGGTTGCGA-3"
 "-TGACTTGACACTCCAAGCAATGTTTG-3" "-TGTGCACCAGTTTTCGTTCC-3" "-TTGGTCATGATACTGCTGATTGC-3"
 "-TTTCCNTTTCTGGTTTACAAGAC-3" "-UACUAA-3" "-UUUAAAC-3" "-α-D-N-acetylneuraminic acid"
 "0$$\\end{document}k=0" "0.026122$$\\end{document}ν=0.026122" "0.05/28" "0.1°C" "0.1°C /s"
 "0.21153$$\\end{document}κτ=0.21153" "0.21153/0.026122" "0.3mg/kg/SC" "0.44°C" "0.5X" "0.5°C"
 "0.7≤AUC<0.8" "0.8≤AUC<0.9" "0111:B4" "07VII" "09/14" "1$$\\end{document}Reff<1" "1+log10"
 "1,2-isopropanediol" "1-Lang" "1-pYLD" "1.1+2+3" "1.1+2+4" "1.2+2+3+4" "1.2+2+4" "1.2+2+4+5"
 "1.56μg/ml" "1.5x106" "1/100" "1/1000" "1/13" "1/15" "1/16" "1/16th" "1/23" "1/32nd" "1/4" "1/4th"
 "1/5" "1/5000" "1/69" "1/8" "1/8th" "1/OR" "10.1 ± 2.4μg/ml" "10.1038/ncomms15582"
 "10.1038/ncomms15743" "10.6 ± 1.1μg/ml" "10/41" "100/" "10000g" "100bp" "100K." "100x"
 "100μL/well" "102/614" "103.98±50.57mg/cc" "105/mL" "105/well" "106.5CCID50" "106CCID50" "10^-5"
 "10E12" "10E9" "10mm/min" "10U/μl" "10x" "10°C" "10×" "10μl" "11.46±4.98/mm2" "11/26" "12,000g"
 "12.2 ± 2.1μg/ml" "12/35" "12000g" "129/129" "12hpi" "12number" "12pt" "13,000g" "13000g"
 "13S-trihydroxy-10E-octadecenoic" "13x109/L" "14/15" "142/1,073" "14c" "15%/50%" "15%/90%"
 "15.8 ± 2.5μg/ml" "15/15" "15/41" "1500×" "150μL" "15×" "16-plex" "16/26" "16/57" "16/60"
 "1640+10%" "1656+EN" "16°C" "17.4 ± 4.6μg/ml" "17/421" "17Cl" "18/101" "18/27" "18/78" "180°"
 "1822:2009—test" "18a" "18°C" "18μl" "19/23" "19/88" "1918/1919" "1918:GP" "196/2003" "1980a"
 "1980s/early" "1980s—have" "1993a" "1993b" "1993c" "1995a" "1a-c" "1A." "1A8" "1c-d" "1H." "1x105"
 "1½–2" "1×" "1×106" "1×109" "1×10E11" "1×10E5" "1×10E9" "1μL" "1–5μm" "1−SSQ" "2+3+4" "2+Ri"
 "2,2-diphenyl-1-picrylhydrazyl" "2,3‐dioxygenase" "2-aminophenylthio" "2-hydroxyethyl"
 "2-oxoglutarate" "2.00GHz" "2.09±1.88/mm3" "2.10Y=αX" "2.1λih=βIii+∑j∈νiIijNii+∑j∈νiNijand"
 "2.2λiw=βIii+∑j∈νiIjiNii+∑j∈νiNji" "2.3Sih=Sii+∑j∈νiSijand" "2.4Siw=Sii+∑j∈νiSji" "2.5J" "2.5x104"
 "2.6Ti" "2.7Ti" "2.8andTi" "2.8x106" "2.9ΘiC" "2/23" "2/279" "2/69" "2/IL-4" "2001+A1:2009"
 "2001a" "2001b" "2003a" "2003b" "2010a" "2010b" "2011a" "2011b" "2013a" "2013b" "2017a" "2017b"
 "209/217" "20X" "20°C" "20°C /s" "20×" "20×-40×-80×" "20μL" "20μl" "21.9 ± 3.9μg/ml" "21/21" "21a"
 "21b" "22/22" "22/26" "222D/N." "222G/N" "22E-diene-3β" "23$$\\end{document}k=23"
 "23$$\\end{document}n=23" "23/88" "24 h15" "24/25" "24hpi" "24ξ-ethylcholest-22E-end-3β"
 "24ξ-methylcholesta-7" "25°C" "25°C." "25μL" "26/41" "260/230" "260/280" "27or" "28 ± 10.4μg/ml"
 "2A-mut" "2A." "2A–2B" "2A–2B*" "2a–c" "2B*" "2b–2d" "2d–f" "2OG" "2OG-FeII" "2OG-FeII_Oxy" "2TM"
 "2where" "2xLSB" "2°C" "2°C /s" "2×" "2μl" "2‐mm3" "2−ΔΔCt" "3,000g" "3,3′-diaminobenzidine"
 "3-Amino-9-ethylcarbazole" "3-dicyano-1" "3-methylcytosine" "3-O-sulfonated-heparan sulfate"
 "3.2x104" "3.9x103" "3/26" "3/3" "3/38" "3/4" "3/69" "3/72" "30/101" "30000U/lb" "300g" "30°C."
 "30×" "31/101" "31/41" "3130xl" "32/101" "328-Mbp" "330x109/L" "33P-labelled" "33°C" "33°C."
 "34/101" "34°C." "365/2184" "37.46 ± 12.3μg/ml" "37.5°C" "374-1:2016" "37°C" "37°C."
 "39.8 ± 6.9μg/ml" "3A+3AB" "3B." "3C+3CD" "3c-like" "3C." "3CU" "3D+3CD" "3D." "3D/2D" "3ft" "3Rs"
 "3U82" "3μL" "4,000g" "4-Diamino-2" "4-methoxy-6-nitro" "4-methoxyphenyl" "4-methylumbelliferyl"
 "4-Morpholinyl" "4/10" "4/13" "4/6" "400g" "40:30:30" "40°C" "40×" "41/57" "425xg" "42°C" "42°C."
 "45°C" "48k" "4a–c" "4c–f" "4mg/kg/PO" "4MYV" "4°C" "4°C." "4×"
 "5,5′,6,6′-tetrachloro-1,1′,3,3′-tetraethylbenzimidazolyl-carbocyanine" "5-dimethylthiazol-2-yl"
 "5-diphenyltetrazolium" "5.10/0.80−1" "5.50±3.19/mm2" "5/15" "5/28" "5/6" "5/8" "500A2" "500×g"
 "50a" "50°C" "50×" "5195/2013" "52.65±18.07 N/m" "52.8/1000" "55°C" "55…" "57/101" "57/69" "57°C"
 "58.3/1000" "5A-D" "5A." "5plex" "5U/μl" "5V5G" "5V5H" "5V69" "5V6A" "5X5V" "5X5W" "5¼" "5×"
 "5×serial" "5μg" "6-diamidino-2-phenylindole" "6.8x106" "6/10" "6/2" "6/26" "6/30" "6/6" "6/6.6"
 "6/8" "6/9" "60/150" "6000g" "6000×" "60°C" "61°C" "62°C" "64.1/1000" "65°C" "66/69" "68°C" "6hpi"
 "6TM" "6×his" "6β-triol" "6‐diamidino‐2‐phenylindole"
 "7,4′-dihydroxy-isoflavone-7-O-β-D-glucoside" "7/101" "7/8" "7/9" "70.000/well" "70°C" "72A1"
 "72°C" "75,000×" "75°C" "77/81" "7900HT" "7AAD" "7A–7C" "7H2O" "7‐8‐dihydroneopterin"
 "8-oxo-2΄-deoxyguanosine" "8/101" "8/13" "8/69" "800×g" "80×" "83P-5" "85/311" "860FAM" "8ab"
 "8x106" "9.5x106" "90/150" "911c" "948/1,025" "94°C" "95%CI" "95CI" "95°" "95°C" "9A–9F"
 "9x104-3.8x108" ":3\\documentclass" ":=N$$\\end{document}N" ":=N." ":=S" ":\\documentclass"
 "<0.02%" "<0.05" "<0.92" "<1%" "<10" "<100" "<100%" "<12" "<150" "<18" "<2" "<2 h" "<20" "<20%"
 "<20-fold" "<200" "<24" "<25%" "<3" "<30" "<300" "<35" "<45" "<5" "<5%" "<6" "<60%" "<70%" "<80"
 "<80%" "<92%" "<93–95%" "=0from" "=107.5" "=12p" "=a" "=health" "=Log" "=N" "=p" "=S˙" "=wl⋅p"
 "={M}∩{C}{M}∪{C}" "=∑" "=∑g∈G" "=∑k=0nIi" ">0.05" ">0.06" ">0.25" ">0.3 µm" ">0.8" ">0.80" ">0.95"
 ">1" ">10" ">100" ">1200" ">18" ">1yr" ">2%" ">200" ">24.9" ">3-fold" ">30" ">35" ">38.5" ">38°C"
 ">40" ">4000" ">5" ">50%" ">500" ">5μm" ">6" ">60" ">65" ">7" ">70" ">75%" ">90%" ">95%" ">98%"
 "\\\\" "\\\\&=" "\\begin{document}" "\\begin{document}$$" "\\begin{document}$$\\begin{aligned}"
 "\\begin{document}$$\\begin{aligned}{}" "\\begin{document}$$\\beta$$\\end{document}β"
 "\\begin{document}$$\\kappa" "\\begin{document}$$\\kappa$$\\end{document}κ"
 "\\begin{document}$$\\nu" "\\begin{document}$$\\nu$$\\end{document}ν"
 "\\begin{document}$$\\tau$$\\end{document}τ" "\\begin{document}$$b" "\\begin{document}$$F"
 "\\begin{document}$$f_E" "\\begin{document}$$f_{E}" "\\begin{document}$$f_{E}$$\\end{document}fE"
 "\\begin{document}$$I_i" "\\begin{document}$$I_T" "\\begin{document}$$k" "\\begin{document}$$n"
 "\\begin{document}$$N" "\\begin{document}$$R_0$$\\end{document}R0"
 "\\begin{document}$$R_\\mathrm{eff}$$\\end{document}Reff" "\\begin{document}$$R_i"
 "\\begin{document}$$R_T" "\\begin{document}$$R_{\\text" "\\beta" "\\boldsymbol{\\upalpha}"
 "\\bullet" "\\cdot" "\\cong" "\\documentclass" "\\dot{I}" "\\dot{I}&=" "\\dot{N}" "\\dot{R}"
 "\\dot{R}&=" "\\dot{S}&=" "\\end{aligned}$$\\end{document}" "\\end{aligned}$$\\end{document}d=1ν"
 "\\end{aligned}$$\\end{document}fE" "\\end{aligned}$$\\end{document}I˙=κτI-νI"
 "\\end{aligned}$$\\end{document}N" "\\end{aligned}$$\\end{document}N˙"
 "\\end{aligned}$$\\end{document}N≅S.Compared" "\\end{aligned}$$\\end{document}R0=κτd"
 "\\end{aligned}$$\\end{document}R0=κτνin" "\\end{aligned}$$\\end{document}R0=∫0∞b"
 "\\end{aligned}$$\\end{document}S˙=-βSI" "\\end{aligned}$$\\end{document}β=κτN"
 "\\end{document}The" "\\frac{1}{\\nu" "\\frac{\\kappa" "\\int" "\\kappa" "\\left" "\\nonumber"
 "\\nu" "\\right" "\\setlength{\\oddsidemargin}{-69pt}" "\\sqrt{\\sum" "\\tau"
 "\\tau$$\\end{document}κτ" "\\to" "\\usepackage{amsbsy}" "\\usepackage{amsfonts}"
 "\\usepackage{amsmath}" "\\usepackage{amssymb}" "\\usepackage{mathrsfs}" "\\usepackage{upgreek}"
 "\\usepackage{wasysym}" "]/2" "]/25 s" "^2" "_0^\\infty" "_i" "_i$$\\end{document}κiτi"
 "_i$$\\end{document}νi" "_{k=0}^{n}" "A&B" "A+T" "A-chain" "A-human" "A-infected" "A-scans"
 "A-site" "A.L." "A/B" "A/B/C" "A/H1N1pdm09" "A/H3N2" "A/J" "A/Puerto" "A/T" "A127-P130"
 "A165-P250" "A1pp" "A1–A3" "A256T" "A2669C" "A4910C" "A4–A6" "A5-miseq" "A5844C" "A63V" "A6992G"
 "A_GUG_UUU" "AASI/Area" "ab6160" "absence/presence" "ABSL-2+" "accident/contamination"
 "AcCoV-JC54" "aCFX96" "acrylamide/7" "acrylamide/bisacrylamide" "Actin_SYBR_F" "Actin_SYBR_R"
 "activation/aggregation" "activator-like" "activity32" "acute/general" "ACV36" "Ad5-Fluc"
 "ADG/day" "adherence/detachment" "adhesion2" "Adv5" "Adv5-Fluc" "advantageous19"
 "aerosols/droplets" "aerosols/exp" "agents/toxins" "agents3" "ago62" "agx716" "AIDA-I+"
 "air/steam" "AJ/AJ" "AJ968413.1" "AlkB-like" "ALKB_ECOLI" "all-time" "allele_1" "allele_2"
 "alone6" "alpha/beta chain" "ALT/AST" "Al‐Bari" "amazing…" "amino acid 222D."
 "Amoxicillin/clavulanic" "AMPV-1" "analysis43" "analysis43–45" "analysis53" "Annexin V/propidium"
 "annually31" "Ansan-si" "anti-2A" "anti-AiV" "anti-apoptoic" "anti-apoptotic" "anti-bacterial"
 "anti-CD8α-APC-Cy7" "anti-CD8–allophycocyanin" "anti-chicken" "anti-EV-D68VP1" "anti-factor"
 "anti-fibrotic" "anti-fungal" "anti-genome" "anti-geronic" "anti-goat" "anti-herpetic"
 "anti-HNxanti-CD28" "anti-human" "anti-human/mouse" "anti-infective" "anti-inflammatory"
 "anti-M13" "anti-metastatic" "anti-microbial" "anti-mouse" "anti-NK1.1-PerCP-Cy-5.5"
 "anti-oxidative" "anti-p-EGFR" "anti-parasitic" "anti-pig" "anti-proliferative" "anti-rabbit"
 "anti-rabbit/mouse" "anti-rejection" "anti-scientific" "anti-tumor" "anti-tumoral" "anti-viral"
 "Anti-viral" "antibiotic/antimycotic" "antibodies/reagents" "antibodies12" "antibodies22"
 "antibodies29" "anticancer/antitumor" "antigens/antigen" "Antoine-Moussiaux" "ANV-1" "ANV-2"
 "Anyplex™" "AON1" "Appr-1-p" "approaches80" "approaches82–84" "Arg1715*" "Arg92*"
 "arteriviruses27" "arthritis/encephalitis" "as-yet-undiscovered" "as7\\documentclass"
 "as8\\documentclass" "as:p" "Asa1" "Asp1645*" "assembly4" "asserted:Investigators" "asthma-COPD"
 "astrovirus-like" "astrovirus–like" "ATCCCCL-185" "ATCC®" "Atf/Creb1" "ATGGACTGTGGTCATGAG‐3"
 "ATHL1" "attachment/entry" "ATV-NDV-bsHN-CD28" "Au5400" "AUC74" "AUC<0.7" "AUC≥0.7" "AUC≥0.8"
 "AUC≥0.9" "AUD#" "authSAML" "AV127" "AV7" "AvaII-cut" "Avicel-media" "Avina‐Zubieta"
 "AxioCamERc5s" "AY333362" "AY6894" "B-lactamase" "B4GALNT4" "B6.129S2-Ifnar1tm1Agt" "BA-10"
 "BA-13" "BA10" "BA13" "BA9" "bacteria/exp" "bacteria/virus" "bacteria7" "bacterial/fungal"
 "bacterial/viral" "BamHI/XhoI" "Bartha-K61" "bats4" "BC051839" "BC113412" "BC114928" "BC125195"
 "BC6/85" "BCL2A" "bcl2fastq" "benefit/risk" "Benjamini-Hochberg" "BF34" "BGI-GBI" "BHV-1"
 "Bio-Plex" "Bio-PLEX" "Bio-Rad" "bioinformatically17" "biological/toxicological"
 "biosafety/biosecurity" "Biosystems/Thermo" "BL19U1" "BL37.75" "Bland-Altman" "BLAST-like"
 "blast_index_virus" "BLC3" "Blosum50" "BM8" "BMTK529" "BoAstV-CH13" "Bonna-Agela" "bovine-like"
 "Bowie-Dick" "Br-U-labelled" "BRACO-19" "Bray-Curtis" "breaths/min" "Brittain-Long"
 "bronchial/epithelial" "Brong-Ahafo" "bsHN-CD28" "BSL-3" "BSL3" "BV/TV" "BV421" "BV650" "BV786"
 "bvd197" "BWA-backtrack" "BX60" "by1\\documentclass" "by2\\documentclass" "by6\\documentclass"
 "c-exNDI" "C-exNDI" "c-exNDI5" "c-exNDIs" "c-kit1" "c-kit2" "C-terminally" "C.S." "C.Z." "C/T"
 "C1s–C1r–C1r–C1s" "C3-/-" "C3-convertases" "C3-deficient" "C3c" "C3d" "C46U" "C57/BL6" "C57BL/6"
 "C57Bl/6" "C57BL/6J" "C5a" "C5b" "C5b-7" "C5b-9" "C6/36" "C9S/C60SvGAAP" "CaCl2" "calit2"
 "Calmette–Guérin" "Cameroon57" "CanFam3.1" "CAP18" "capture/handoff" "capture/release"
 "case/control" "caspase-3/9" "Cat#" "Cat#12491015" "Cat#52904" "Cat#AM2694" "CBA/N" "CC50"
 "CC50mean" "CCID50" "CCL-10" "CCL-171" "CCL-185" "CCL-34" "CCL-81" "CCL-81™" "CCL-88"
 "CCL19-diphteria-toxin" "CCP3" "CCR19-DTR" "CD105+" "CD11b+" "CD11c+" "CD19+" "CD21+" "CD21low"
 "CD3+" "CD3+/CD4+" "CD3+/CD8+" "CD34+" "CD45+" "CD45−TER119−" "CD8+ T cells17" "CD90+" "CDR3s"
 "Ce3+" "Ce4+" "cell/viral" "CellQuest™" "cells/cm2" "cells/well" "cells12" "cells35" "cells36"
 "cells37" "CeO2" "CFU/m3" "cfu/ml" "CFU/mL" "CFX96" "Ch/IBV" "CH261-109H20" "Chai-hu-shu-gan"
 "chain-like" "Chao1" "characterized21–23" "CHCl3-MeOH" "chIFITM1" "chIFITM10" "chIFITM2"
 "chIFITM3" "chIFITM5" "children24–27" "children37" "chimpanzee55" "Chirascan-Plus"
 "Chlamydophila/Chlamydia" "CHORI-261" "chromosome10" "cHSP60" "circulation31" "city/province"
 "cjq504" "CL-3" "cloning35" "club-like" "clustalW72" "Clutton-Brock" "cmH2O" "co-" "co-authors"
 "co-factors" "co-infection" "co-ligation" "co-morbidities" "co-transfected" "co-translationally"
 "co-treatment" "Cochran-Armitage" "cold-like" "collagen/gelatin" "colonized/infected" "com/"
 "com/danoreper/ISVdb" "com/r/990210oliver/drvm/" "component C4" "compound41" "Concentrator-5"
 "conditions1" "conditions11–13" "conditions14–23" "ConnectAppli" "contig/singleton"
 "contigs/singleton" "contigs/singletons" "contradicting22–24" "control/calibrator" "copies/ml"
 "copies/mL" "copies/μl" "copy/L" "CorTheoNL63F1" "CorTheoNL63R1" "cough/hemoptysis" "Counter®"
 "counts/proportions" "CPVgp1" "Cre/loxP-based" "cross-factor" "CSp11/NBam24" "culture25"
 "culture31" "CURB-65" "CV777" "CV777-based" "CVB3" "CVCCVA5" "CVCVA5" "Cytofix/Cytoperm"
 "cytoplasmic 2A" "Cy™7" "D.Lgs" "D1-4G2-4-15" "D222G/N" "dada2" "data9" "day-to-day" "day/night"
 "days34" "DBA/2" "DC1" "Dc=" "DD8" "ddH2O" "DE-32" "declines/extinctions" "defect8" "defence-like"
 "degradation29" "degraded23" "demonstrated24–30" "DENV1" "DENV‐2" "DENV‐2‐induced" "DESC1"
 "described22" "described40" "described5" "described63" "described9" "DESeq2" "detail35"
 "detect/reconstruct" "deubiquitinating/deISGylating" "DEVD-p-NA" "device/product" "dH2O" "DHV-2"
 "DHV-3" "Diaclone®" "difference:Exaggeration" "diluted10-fold" "disease/vasculitis" "diseases3"
 "disorders20–26" "disorders4" "disorders60" "DLCO/VA" "DM5" "DMI4000B" "dmol−1" "DMRIE-C"
 "DNA replication27" "DNA/cDNA" "DNA/well" "DNA27" "DNAv2" "documented711121314" "double/triple"
 "DQ294633.1" "DRR049387" "drug-like" "ds-cDNA" "dual‐luciferase" "Dunn-Walter" "Dunn-Walters"
 "during/after" "Duxf3" "dye/100" "dysuria121328" "E-GEOD-50628" "e-Myco" "E-value" "E.coli"
 "E.D.F." "E.M." "E.Z.N.A." "EAST1" "EBER1" "EBER2" "EC50" "EC90" "echovirus66" "ECM-like"
 "ecological/wildlife" "editing63" "edu/archive" "EEC" "EfCoV-JC54" "effects5" "Efk3" "EID50"
 "EID50/mL" "Eight-day-old" "EL808" "EMC/2012" "EN12942" "EN14126" "EN149" "EN349" "EN61010"
 "endosomal/lysosomal" "endothelial cells25" "Envision+system" "EnVision-DAB+" "EpCam+/CD90+"
 "epithelial/endothelial" "Epstein–Barr virus25" "Epstein–Barr virus37" "equipment–EN60601"
 "ER-TR7" "ERR1097471" "ERR1097472" "ERR690494" "ERR690519" "ERR690532" "ERS/ATS"
 "estimate_diversity" "et al.19" "et al.1934" "et al.1991" "et al.22" "et al.23" "et al.34"
 "et al.40" "et al.42" "et al.46" "et al.50" "et al.51" "et al.54" "et al.62" "ETEC-aidA"
 "ethical/legal" "etiology41" "eukaryotic cells61" "EV-D68-infectedanimals"
 "EV-D68-infectedferrets" "EV71" "EV71VP1‐F" "evaluated10" "expression18" "expression25"
 "expression36" "F.A." "F.P." "F12K" "F18ab" "F18ac" "F18R" "F4-positive" "F4-type" "F4/80+"
 "F48E8" "F4ab" "F4ab/ac" "F4ac" "F4ad" "F4R" "f_{E}" "factor 2a" "FAM/TAMRA" "family 24p3"
 "family53" "FASTX-Toolkit" "FBS+1" "FcγR3a" "FcγR3A" "felCat5" "Felis_catus" "female/male" "FEV1"
 "FFP2" "FFP2:medium" "FFP3" "FFP3:high" "FFVgag-F" "FFVgag-R" "FFVgag-TM" "FGR3A" "FHV-1"
 "fibroblast-like" "Figure3C" "findings1718" "FiO2" "FIPV_gp02" "Five-micrometre" "Five-week-old"
 "fja259" "flu-like" "Flórez-Vargas" "FO-BAL" "foci46" "folding/unfolding" "forward/reverse"
 "Forward/reverse" "FOS-like" "four-stacked-G-quartet" "Four-week-old" "fourty-four"
 "French/European" "function14" "functions15–17" "fungi/exp" "furan-2-carbaldehyde" "Fuyang0805"
 "FV10i" "FV10‐ASW" "fyc306" "G-base" "G-quadruplex" "G-quartets" "G-tract" "G-tracts" "G.B.‐Z."
 "G.F." "G.M." "g/L." "g/mL" "G1/early" "G12=" "G2-XS" "G2b" "g3journal" "G4/iMotif" "G4b" "G4f"
 "G4s" "G4s10" "G4s19" "G4s27" "G4s66" "G4s7" "G52U" "G_GUU_UUU" "GAAP-like" "Gamma-herpesvirinae"
 "gamma/delta" "gamma/delta coronavirus" "GAPDH_SYBR_F" "GAPDH_SYBR_R" "GAPDH‐F" "GAPDH‐R" "GB4"
 "GC/MS" "Gc=" "GCA_000181335.2" "GCTGATACTTCTGAGTCTTGGGCA-3" "gD284" "gD284/" "gD285/" "gD285—a"
 "gD337" "gE/gI" "gene 1b" "gene 3c" "genes/probes" "genes17" "genes20" "genes27" "genes62"
 "Genest-sur-isle" "genetics/immune response" "genome21–24" "genome4" "genome7" "genomes33–36"
 "genotype/diplotype" "genotype:p" "GG2-1" "GGG≥3N0–12GGG≥3N0–12GGG≥3N0–12GGG≥3" "Gibco™" "gkc048"
 "GKS3β" "Gln149*" "Glu1670*" "Glu1754*" "Gly1710*" "Gly1758*" "glycation7–9" "goat-anti-pig"
 "Gonzalez‐Dunia" "gov/" "gov/GenBank/" "gov/geo" "gov/geo/" "gov/ij" "gov/tools" "gp054" "gp054a"
 "gp350" "gp350/220" "gp38+CD31+CD35" "gp38+CD31−CD35" "gp38±CD31−CD35" "gp38−CD31+CD35"
 "gp38−CD31−CD35" "gQ1" "gQ2" "GQ246951.1" "GR1+" "GR1low" "granulocyte/macrophage" "GRCm38"
 "GRCm38.70" "ground-glass-like" "group52" "groups/mechanisms" "GRP94/78" "GSE13699" "GSE1739"
 "GSE29429" "GSE4128" "GSE52428" "GSE63990" "GSE68112" "Guerra-Ordaz" "guidelines75" "H&E"
 "H+-permeable" "H+-regulated" "H/R+Myr" "H1.2F3" "H1Hela" "H1HeLa cell" "H1Hela cells" "H1N1pdm"
 "H1N1pdm09" "H1N1pdm09-positive" "H2-Q2" "H2O" "H2SO4" "H3K18" "H3K27" "H3K4me2" "H3K4me3" "H3PO4"
 "H5N11" "H5N3" "H5N8" "H5–H9" "H7N9" "HA-nsp3C" "HA-nsp3C-4-V5" "HA222-for" "HA222-rev" "hABH3"
 "hairpin-like" "Hamburg" "Hasegawa-Kishino-Yano" "HAstV-1a–d" "HAstV-2a–d" "HAstV-4a–c" "HAT/DESC"
 "HB-8065™" "HB101" "hBI-1" "HBS-EP" "HBx-LINE1" "HCoV229E" "heat-labile" "heat-map" "height/crypt"
 "here32" "HF952119-HF952135" "hGM-CSF" "HH_SYBR_F" "HH_SYBR_R" "HHV-6A" "HHV-6B." "hIFITM1"
 "hIFITM3" "hind-limb" "HiSeq-PE150" "HIV-18" "HIV-254" "HIV/AIDs" "HIV65" "HKL2000" "HKU2" "HKU24"
 "HKU9" "HMMER/Pfam" "HMO—Human-Mink-Ovine-like" "HNE-α7" "homo-oligomers" "Hoogsteen-type"
 "horror/fantasy" "hospitals/exp" "host cell`s" "host34" "hour-by-hour" "hPIV1-4" "hPIV3"
 "HPLC-ELSD" "HPV-16" "HRV1A" "HRV72" "HSA0000031.1" "hSCARB2" "HSV-138" "HT29" "hTel21"
 "http://bioinformatics" "http://camera" "http://cran" "http://david" "http://dx"
 "http://interferome" "http://isvdb" "http://kccr" "http://mcmc-jags" "http://sb" "http://tree"
 "http://www" "https://authentification" "https://genome" "https://github" "https://hub"
 "https://imagej" "https://lifescience" "https://milaboratory" "https://sourceforge" "https://www"
 "Hu-M1-F-" "Hu-M1-R-" "HU-nectin-1" "Huh7" "Huh‐7" "Human herpesvirus 6A" "human/murine"
 "humans41" "humans44–46" "HVSCD59" "Hy-Line" "Hybond™" "hybrid/mixed"
 "hydrophilicity/hydrophobicity" "hypogammaglobulinaemia6" "Hypoxia/reoxygenation" "I+J" "I-like"
 "I.C." "i/d" "I:C" "I_i" "I_T" "IBV-1b" "IBV-M41#2" "iC3b" "IC5013.3 ± 2.6μg/ml"
 "IC5041.1 ± 6.7μg/ml" "IC5072.04 ± 14.5μg/ml" "IC50mean" "ICD9" "ICU/hospital" "IDBA_UD"
 "identified5" "identity/variation" "Ifi27l2a" "Ifitm6" "IFN-α/β" "IFN-α/βR" "IFN-αR1" "IFN-αR2"
 "IFN-β1a" "IFN-λ2/λ3" "IFN\\documentclass" "Ifna11" "Ifnar1−/−" "IFNα/β" "IFS/MetFS" "Ig-like"
 "IgV-like" "Ii=0" "IL-12/23" "IL-12β" "IL-1F11" "IL-33/ST2" "ILC2" "Ile131*" "Ile14*"
 "Illumina/Solexa" "immitis/posadasii" "immune cells31–33" "immune response28" "immune system11"
 "immunodeficiency syndrome-like" "Immunology1" "immunotoxicity37" "import/export" "in+Ti" "in19"
 "in=∑j∈νiwij" "increase24" "indels/SNPs" "industry30" "infected/transfected" "Infection/exp"
 "infection26" "infection4" "infection54" "infection56" "infection58" "infection59" "infection6"
 "infection7–10" "infections30" "infections33" "infections9" "inflammasomes43"
 "inflammation/chemotaxis" "inflammation35" "inflammatory response28" "influenza virus-like"
 "influenza-like" "INFγ-regulated" "inhibited9" "injection22" "injury33" "iNKT/NK cells"
 "Innovax-ND" "int/ihr/en/" "inter-TM" "INTERGROWTH-21st" "Internet-based" "Invitrogen/Thermo"
 "Invitrogen™" "ion/Ca2+" "Irgb2-b1" "is5\\documentclass" "ischemia/reperfusion" "ISFG3"
 "ISG15-AMC" "iso-butyrate" "ISO/EN" "ISO12100" "isorhamnetin-3-O-glucoside" "IU/ml" "IX/1046"
 "IX83" "I˙=βSI-νI" "i→j" "J-xY" "J171" "J=0.13" "J=0.46" "JC30" "JC34" "JC54" "Jean-Philippe"
 "JF274479" "JF930689.1" "Jordan/N3" "JX503071-JX503101" "JX503077" "JX503083" "JX503096.1"
 "J¯=0.27" "j∈νi" "K2EDTA" "Kaplan-Meier" "kappa-light-chain-enhancer" "Karin53" "kcal/mol"
 "KF294380" "Ki67+/Oct4+" "Kim15" "kinase-β-" "Kir-like" "KJ194499-KJ194510" "km2" "KMER51"
 "Kolmogorov-Smirnov" "Kon/Koff" "KPED-9" "KRT18+" "KRT5+" "Kruskal–Wallis" "KUO2000" "KX087101.2"
 "KX663833.1" "KX756441" "KX964649" "KX964650–KX964654" "KX964655–KX964657" "L-1-" "L-100XP" "L-1β"
 "L/min" "l/well" "L2-MHV3" "L2-MHV3-induced" "L2-MHV3-mediated" "L7/L12" "L90-A91" "LANA-episome"
 "large-form" "LC480" "LCS480" "LdRos3" "LEHD-AFC" "Leite-De-Moraes" "Leroux‐Roels" "Leu1682*"
 "Leukotrien-B4" "Level-4" "Lfg1" "Lfg2" "Lfg3" "Lfg4" "Lfg5" "LFP-20" "LHLJ" "Li-Cor" "life-time"
 "life-years" "ligands41" "ligands9" "light/dark" "light/fluorescence" "LightCycler480"
 "LightCycler®" "Linc-MD1" "Lipo2000" "live/dead" "liver21" "LJB/03" "lncBST2" "lncBST2/BISPR"
 "LncBST2/BISPR" "lncRNA#32" "LncRNA#32" "lncRNA-CMPK2" "lncRNA-like" "lncRNA-UCA1" "LOB7"
 "LOC107053353-dispanin-2b-like" "LOC422993-3-like" "LOC770612-1-like" "location17" "log10"
 "Longquan-343" "Longquan-353" "loop/oligonucleotide" "low/non" "loxP-based" "lpt371" "LR7"
 "LTR-III43" "LTR9" "LTα1β2" "Lucheng-19" "Luria-Bertani" "LXRα-ABCA1" "LY29002" "LY294006" "M.I."
 "M.P." "M1/70" "M95169.1" "M=ViC∩ViMViC∪ViM" "machinery–EN13445" "macrophages30" "Madin-Darby"
 "Malcolm60" "Management/Chiefs" "management1–5" "Mann-Whitney-U-test" "manner65" "MAP0403"
 "markers:p" "Martinez-Lobo" "Massachusetts-like" "matter/debris" "Maurer-Stroh" "mechanism27"
 "mechanisms7–10" "MEGA2" "MEGA6" "MEGA674" "MEGA7" "men29" "mentioned57" "mentioned61"
 "mentioned64" "mesh-like" "Met209*" "method73" "methods41" "MetS+IFS" "Meyboom-de" "Meyer-Lucht"
 "mg/cm3" "mg/day" "mg/dL" "mg/kg" "mg/kg/8 h" "mg/kg/day" "mg/l" "mg/L" "mg/ml" "MHV3" "mice56"
 "microarray-analysis-instruments-software-services" "microbiome/virome" "microorganism/exp"
 "mid-1990s" "mild/low" "mild/moderate" "Mini-Fluorometer" "MIP-1B" "MIP‐1α" "miRNA‐127‐5p"
 "miR‐127‐5p" "miR‐127‐5p‐binding" "miR‐127‐5p‐mediated" "miR‐127‐5p‐transfected" "miR‐23b"
 "miR‐296‐5p" "miR‐30a" "mixed/hybrid" "MKK3/6" "MKK4/7" "mL/embryo" "mL/min" "MLB1" "MLB2" "MLB3"
 "MM9" "Mmjax" "mmol/egg" "mmol/L" "MnSO4" "mode71" "Mogensen14" "molecules/ul" "molecules/μl"
 "molecules27" "monocytes/macrophages" "mortality/graft" "movements28" "MPK11" "MS/BS" "mScarb2"
 "MucoRice-CTB" "multiplexing36" "mut1" "mut1/2" "mut2" "mutation11" "mutually exclusive9"
 "MX3005P" "myeloid cells37" "N/mm" "N2.1" "n5M1" "n5M2" "n5M3" "n5M4" "n5M5" "n=1014" "n=130"
 "N=63" "n=858" "NA2" "Na2C03" "Na2S2O3" "NaH2PO4" "nanorod/nanowire" "NBam24" "NC_001405.1"
 "NC_001539" "NC_001612" "NC_001617" "NC_001781" "NC_002306.3" "NC_004102.1" "NC_011503.2"
 "NC_011506–NC_011510" "NC_026814.1" "NCL/DNA" "NCL/oligonucleotide" "ND-IB-EDS-H9" "NEAT1"
 "NEAT1-binding" "nectin-like" "negative/recipient" "net/" "net/projects"
 "net/projects/sb2nhri/files/drVM/" "net/projects/sb2nhri/files/drVM/Comparison/" "NeuroS1"
 "Newcastle-upon-Tyne" "NFκB19" "NH4OAc" "niger/brasiliensis" "Nij=Sij+Iij+Rij" "nimp/nic" "NK1.1+"
 "nm/min" "Nod-like" "NOD-like" "NOD/SCID" "NODE_1_length_7914" "NODE_2_length_7654" "Non-"
 "Non-binding" "Non-essential" "Non-Human" "Non-invasive" "non-NPS" "non-RTI" "Non-structural"
 "non-structural protein 3c" "Non-typeable" "non-Watson-Crick" "nr/nt" "nrk011" "NS2B" "NS3/4A"
 "NSP16" "nsp1β" "nsp1↓2" "nsp2TF" "nsp2↓3" "nsp3C-4" "nsp3↓4" "nsp4-V5" "NTU105-EL-00087"
 "Nucleo-spin" "nucleotides/host" "NZ$1.288 million" "NZ$1000" "NZ$10–12" "NZ$200" "NZ$45,000"
 "NZ$521,000" "NZ$60" "NZ$994,000" "NZ9000" "O/N" "O138" "O139" "O141" "O147" "O149" "O157"
 "O2\\documentclass" "observed1" "OD495" "OD600" "OKB105" "Olarte-Castillo" "oligo-dt"
 "oligonucleotide/loop" "on/off" "ON1" "One-day-old" "open/close" "Opi-MEM" "Opti-MEM" "ORF1a/b"
 "orf1ab" "ORF1b" "ORF1b/ORF2" "ORF3b" "ORF4a" "org/" "org/content/mpp_mouse#cc"
 "org/content/multiparental_populations" "organ-like" "orientation/topology" "Orr-Burks" "other6"
 "others1–5" "OTU-like" "OTU169-CC" "OTU185-CC" "out=∑j∈νiwji" "p-70S6K" "P-ANV" "p-distance"
 "p-IBV" "p-IBV-1b" "p-IBV-5-1b" "p-IBV-5-1b-mhvS-SIR-3" "p-IBV-5-1b-S-SIR-3" "p-MHV-S." "p-mIBV"
 "P-region" "P-site" "p-value" "P-values" "p-w" "p-y" "P.R." "P/N" "P/S" "p15E" "P58-ipk"
 "P<0.0001" "p<0.001" "P<0.01" "p<0.05" "P=0.0001" "P=0.0022" "P=0.0048" "P=0.0153" "P=0.0443"
 "P=0.0464" "P=0.0473" "P>0.05" "pan-antikinetoplastid" "PaO2/FiO2" "PaO2/fraction" "paper63"
 "paraformaldehyde/sucrose" "parallel-like" "parallel/antiparallel" "parameters37" "Pardo-Manuel"
 "particles/mL" "particulate/filtering" "parvum/C." "PAstV1–5" "pathogen/host" "pathogen24"
 "Pathogen—Midtructural" "non-structural protein 3c" "Non-typ