;; covid-2020-04-03-0403-COM-PMC-7001-7100 sample of unknown words
;; created 5/10/20 22:32:50

(in-package :sparser)

;; 3937 extracted as unknown bio-entity


(defparameter *All-Upper-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*All-Upper-Unknown-Words*) (symbol-value `*All-Upper-Unknown-Words*))
         '(
("AADIV" "AAFREQ" "AAV" "ABD" "ADFI" "ADMET" "ADV" "AIII" "AIV" "ALTRA" "AMBA" "AMBL" "AMC" "AMDIS"
 "AMED" "AMV" "AMVA" "ANN" "AON" "APCI" "APTES" "APTT" "AQI" "ARCA" "ARVO" "ASA" "ASPD" "ASTRA"
 "ATCC" "AUG" "AVV" "Aǁ" "BAGV" "BALF" "BBB" "BCED" "BCUT" "BD" "BEGM" "BEOU" "BFC" "BFGS" "BGH"
 "BIORAD" "BMCS" "BMDM" "BMG" "BMGY" "BMMY" "BQ" "BST" "BVDV" "BWG" "BZN" "CAPD" "CARV" "CCCCF"
 "CCCF" "CCGTCAGCACCTTCATCGA" "CCOP" "CEU" "CFIA" "CFTR" "CGCTGGACCTCCGTGTAGTC" "CHAM" "CHCOO"
 "CHIKV" "CHNS" "CHX" "CINAHL" "CKD" "CLAD" "CLSM" "CLT" "CMED" "CNCP" "CONHNH" "COO" "CORINA"
 "COSY" "CPPS" "CRTCRD" "CTG" "CTT" "CUHK" "CUTHIVAC" "CUTHIVEC" "CVFF" "CXCALC" "CXXC" "CHARMM"
 "DAKO" "DDM" "DEHO" "DENV" "DEPT" "DHMT" "DIVAA" "DKA" "DMEM" "DMV" "DPPH" "DSSP" "DWT" "ECI"
 "ECLIPSE" "ECMO" "EDCI" "EIMS" "ELAI" "ELMO" "ELSO" "EMCO" "EMCS" "EMCV" "EMR" "EPICS" "EPIFILTER"
 "EPIMAP" "EPON" "ESBL" "ESCRT" "EUR" "EVD" "EVOS" "EWL" "FACSARIA" "FASTA" "FBG" "FFU" "FHV" "FID"
 "FINDMAP" "FIPV" "FIRES" "FLEXMAP" "FMDV" "FMVD" "FORTRAN" "FTICR" "FTIR" "GAATTCGCTGATCTTA"
 "GATK" "GAV" "GBD" "GBR" "GCBR" "GENTEX" "GG" "GGGGSGGGG" "GLT" "GRMD" "GTC" "GTCTGCAGAGT" "GTN"
 "GVSS" "GWD" "HAADF" "HAART" "HAIYPRH" "HAU" "HBSS" "HBTU" "HCQ" "HCW" "HCWS" "HELEOS" "HELF"
 "HKSAR" "HMBC" "HMTG" "HOBO" "HOSCC" "HRESIMS" "HRIC" "HSACC" "HSQC" "HTLV" "HTNV" "HWE" "HYB"
 "HZS" "IACUC" "IAV" "IBM" "IBV" "ICMV" "IDSR" "IEF" "IEX" "IGV" "IHTS" "IID" "IIE" "IIF" "ILTV"
 "IMAGE" "INFA" "INFB" "INFO" "IONP" "IPS" "IQR" "IRB" "IRES" "ISCOM" "ISDN" "ISI" "ISL" "ITHTS"
 "ITZ" "IVI" "IVIG" "JAVA" "JCF" "JEOL" "JEV" "JSRV" "KASP" "KCDC" "KII" "KNN" "KNNC" "Kǁ"
 "LABTECH" "LECO" "LEL" "LGC" "LHID" "LIBSVM" "LOOH" "LPE" "LPLTPLP" "LRLRGG" "LRTI" "LTM" "LUMO"
 "LX" "MARU" "MASCOT" "MATLAB" "MDSC" "MDT" "MEM" "MEMS" "MFI" "MHCI" "MHCII" "MHV" "MIMOP" "MIMOX"
 "MNPS" "MOI" "MOPAC" "MPAK" "MSQ" "MVM" "NACCESS" "NAGEMA" "NASBA" "NCTC" "NHCO" "NHI" "NHIRD"
 "NHOK" "NHSRC" "NICU" "NIOSH" "NIPPV" "NIST" "NOESY" "NPV" "NRERC" "NRRL" "NRY" "NVBDCP" "NVT"
 "OAAH" "OCPA" "OCPB" "OD" "ODS" "OECD" "OI" "OMM" "ONOO" "OOB" "OPLS" "OPTIMA" "ORAC" "ORACLE"
 "PBFDV" "PCCC" "PCCH" "PCCO" "PCOC" "PDEV" "PEPBANK" "PESIN" "PHENIX" "PI" "PICU" "PIHAT" "PLATON"
 "PLG" "PLINK" "PLR" "PLUMED" "PMAPEG" "PMED" "PMWU" "POCC" "POPDIV" "PRRT" "PRXSYS" "PSAIA" "QD"
 "QLD" "QRS" "QSAR" "QSRR" "QT" "QIAGEN" "QTL" "RAFI" "RAMSEA" "RELIC" "RFLP" "RGD" "RIKEN" "RMSD"
 "RMSEA" "RPART" "SADI" "SAROTUP" "SBC" "SBVS" "SCID" "SCSIO" "SDE" "SELEX" "SFU" "SFV" "SGH"
 "SGIV" "SHAPEIT" "SHELXL" "SHELXS" "SINV" "SLEV" "SMILES" "SMOTE" "SOKALAN" "SPIO" "SPSS" "SSC"
 "SSE" "STATISTICA" "SVM" "SVSVGMKPSPRP" "SWOLS" "SYBR" "TACTCA" "TAKARA" "TALEN" "TAPSE" "TBARS"
 "TBST" "TCG" "TCNE" "TEAA" "TEAC" "TEOS" "TEV" "THREESHINE" "TMUV" "TMV" "TOTL" "TPB" "TSJW" "TTC"
 "TUNEL" "TVV" "UAE" "UBE" "UCLA" "UCSC" "UGENE" "UNA" "URTI" "USA" "USD" "USSD" "UU" "UUKV" "VACV"
 "VEB" "VEEV" "VGCC" "VHC" "VOA" "VPL" "VSVG" "VV" "WBC" "WESSV" "WPI" "XDS" "XPREP" "YHV" "YMC"
 "YPD" "YPDS" "YRI" "CCDC" "IPNI" "ℝF" "ℝFE" "ⅈ" "ⅉ" "口罩")))
    :test #'equalp))


(defparameter *All-Lower-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*All-Lower-Unknown-Words*) (symbol-value `*All-Lower-Unknown-Words*))
         '(
("aaaagggcgctgtg" "aacgacaatattgctttgctaa" "aamantadine" "aattca"
 "aattcaaaaaaacgacaatattgctttgctaaagc" "aattcaaaaagataatggaccccaatcaaacaa"
 "aattcaaaaagggaccaagacctaatcagacaagcttgt" "abomasum" "abortus" "absorbance" "abundancy"
 "accomodate" "acori" "actinohivin" "actinomycete" "actinomycetes" "actives" "acutidens" "acyl"
 "acylsemicarbazide" "adamantyl" "adduct" "adeno" "adenoid" "adhesiveness" "adjuvancy" "adjuvants"
 "adolescents" "adsorbents" "advancements" "aegypti" "aeruginosa" "afterload" "agalactiae"
 "agardhii" "agcttat" "agcttgtccttaatg" "aglycon" "aglycone" "agri" "ailanthoides" "alarmin"
 "alarmins" "albicans" "albiziae" "algal" "algomenorrhea" "algorithm" "algorithms" "aliquot"
 "aliquots" "alismatis" "alisol" "alkenyl" "alkyl" "allo" "allograft" "alloimmune" "allotropes"
 "alternifolia" "alveoli" "ambisense" "ambrum" "amethole" "amido" "amidoamine" "amidoblack"
 "aminoacids" "aminoarenesulfonate" "aminothiazolone" "amplicon" "amplicons" "ampule" "amyloids"
 "analyser" "analytes" "ananthraquinones" "anemarrhenae" "angiography" "angustifolia" "anhydride"
 "anisatum" "annulus" "antennapedia" "antidiabetes" "antifade" "antigenemia" "antilipid"
 "antimalaria" "antimoniate" "antimouse" "antioxydants" "antiplatelet" "antitumour" "antiulcer"
 "antixidant" "antixodant" "antrhrax" "apnea" "appropriateness" "apta" "aptazyme" "aquametry"
 "arabicus" "architectures" "argentipes" "aromaticum" "aroyl" "arrhythmia" "artemisinins"
 "arterioles" "arylnaphtalene" "aryls" "aryltetraline" "ascidians" "asialoglycoprotein"
 "asteltoxin" "astragaloside" "athough" "atlantica" "atractylodis" "atrio" "atrium" "audouinii"
 "aughts" "aurantium" "aureu" "austroafricanus" "autoimmune" "availble" "avium" "axb" "axial"
 "azidoalkylphosphonate" "azidoalkylphosphonates" "azomethines" "b" "backpack" "backpacks"
 "barbatae" "barona" "basale" "basophiles" "baumani" "beamlines" "begun" "benanomicins" "bentback"
 "benthamiana" "benzo" "benzopyrano" "benzopyranocoumarin" "benzotriazolide" "benzotriazolides"
 "benzoylhydrazone" "benzyloxycarbonyl" "bergamia" "beween" "bibliometrix" "bidentate" "bilayer"
 "bilirubinemia" "bio" "bioaerosol" "bioapplications" "bioassay" "biochip" "bioengineers" "bioinfo"
 "biomedicine" "biomolecule" "biomolecules" "biopsies" "biopsy" "biosafety" "biosensors"
 "bioterrorism" "bipy" "bismacycles" "bismite" "bismuthinite" "bisphenyl" "bisphosphate" "bisporus"
 "bivariate" "blocker" "blown" "bluetongue" "bolus" "boranophosphate" "bornyl" "botulinum"
 "botulinus" "bovis" "breathlessness" "brevifolia" "broken" "bronchodilators" "brushings"
 "buckyballs" "buffy" "bufonis" "bulkiness" "bupleuri" "bursa" "byxi" "c" "cablin" "caespititius"
 "calcd" "caliper" "calorimeter" "calorimetry" "calstabin" "camphoratus" "candidum" "canescens"
 "canina" "cannula" "capitata" "capitatum" "capitatus" "capitellatus" "capsulatum" "carbohydrases"
 "carboxyl" "cardamomum" "cardio" "cargos" "carotid" "carriership" "carteri" "carvi" "caryophyllus"
 "catalise" "catalyses" "catheter" "catheters" "ccdc" "cecal" "cellwall" "centroid" "centroids"
 "centrophenoxine" "cereus" "chagasi" "chemo" "chemoprophylaxis" "chemoresistance" "chemotypes"
 "chemset" "chenpi" "childcare" "chiropteran" "chlorobiocin" "chlorobismuthane" "chloroformate"
 "chloromycin" "chosen" "chr" "chromatograph" "chromon" "chuanxiong" "ci" "cinaserin" "cinerea"
 "cinnamoyl" "ciproﬂoxacin" "circovirus" "citratus" "citrinum" "clade" "classifier" "classifiers"
 "clinicaltrials" "clinicians" "cloaca" "cn" "coauthors" "codelivery" "codeplex" "codings"
 "codominant" "codon" "cofounder" "coli" "coliform" "coliphage" "collectin" "collegues" "colonise"
 "communis" "composites" "compositon" "compouds" "conc" "concentrators" "conductance" "conformer"
 "confounder" "confounders" "coniferyl" "consumables" "contigs" "continuum" "conyzoides" "coptidis"
 "cor" "coriander" "corneum" "corymbosa" "corymbulosum" "cosmeceuticals" "costimulators"
 "covariate" "covariates" "coverslip" "coworkers" "coxsackievirus" "crosslink" "crossover" "cruzi"
 "cryo" "cryostat" "cryotube" "cryptone" "cubebinolide" "cumin" "cuneata" "curcumae" "cuspidate"
 "cuspidati" "cuspidatum" "cuvette" "cyanobacteria" "cyanobacterium" "cyanovirin" "cycler" "cyclo"
 "cycloadducts" "cyclopeptide" "cyminum" "cyninum" "cyrtonema" "cytometer" "cytopathology" "ddd"
 "decomp" "defocus" "dehydrogenases" "dendrimersomes" "deoxynucleotide" "deoxynucleotidyl"
 "deoxyxylulose" "depressant" "der" "destructions" "diacid" "diacrylatepolyethylenimine"
 "dialkylalkanediamine" "dialkylalkanediamines" "dialysate" "diaminobenzidine" "diastereoisomer"
 "diastereoisomers" "diastereoselectivities" "dibenzylbutyrolactol" "dibenzylbutyrolactone"
 "dibenzylfuran" "dicarboxamides" "dichloride" "dichloromthane" "dichroism" "dideoxycitidine"
 "diene" "dienes" "diethoxyphosphoryl" "diethyl" "diethylamino" "diethylaminoethyl" "diethylether"
 "diethylethylenediamine" "difficile" "diffractometer" "difluoride" "dihalogeno" "dihexadecyl"
 "dihydrochloride" "dihydroxybenzylbutane" "dihydroxypyrimidine" "dimethoxy" "dimethylamino"
 "dimethylethylenediamine" "dimethylforamide" "dimethylsulfoxide" "dimyristodylphosphatadyl"
 "dinitrate" "diocia" "dioica" "dione" "diorgano" "dioxole" "dipalimitoyl" "diphenyltetrazolium"
 "dipsaci" "dipyrido" "disaccaharides" "disaggregate" "discrepant" "distraughtness" "distrct"
 "dithiocarbamate" "dizocipline" "dmft" "dockings" "dodecamers" "domesticus" "donovani"
 "downsamplers" "dqu" "dragmacidins" "drawn" "dreamful" "droopy" "droplet" "droplets" "dropwise"
 "druggabilty" "duplexes" "dwarfism" "dyslipidemia" "dyspnea" "dysrhythmia" "dyssynchrony" "e"
 "eagers" "easiness" "echocardiography" "ecotypes" "ectodomain" "edema" "effecter" "eg"
 "ehrenbergii" "eightgold" "eijk" "ellipsoid" "ellipsosporum" "eluents" "email" "emarginatus"
 "emmenagogue" "emphasise" "enantiomers" "enatioxidant" "encapsulate" "encephalomyocarditis"
 "endogamy" "enhancer" "enhancers" "enolate" "ensiformis" "entererovirus" "enterica" "enteritidis"
 "entero" "enteropathogen" "entropy" "eosin" "eosinophilia" "epidermidis" "epidermoid" "epithelia"
 "epithelium" "epitheloid" "epoxyphenylpropanoid" "eq" "equi" "equiv" "eremophila" "erinaceus"
 "etc" "ethanone" "ethylenediamin" "ethylphosphonate" "euro" "europaea" "evodiae" "ex"
 "exclusiveness" "explant" "explants" "exploiture" "f" "facecalis" "facemask" "facemasks"
 "facilitators" "faecalis" "falciparium" "falciparum" "farinosa" "febrifuge" "feco" "feelings"
 "fenugreek" "ferrozine" "ffu" "fibroblastoid" "ficolin" "ficolins" "flattest" "flavescentis"
 "flavi" "flavinoids" "flavum" "flavus" "flora" "flowchart" "flowrate" "fluorescens" "fluorophore"
 "fluorophores" "focusses" "foenum" "foldases" "foldback" "follicle" "foodborne" "footpad"
 "forcefield" "forceps" "forgotten" "formazan" "formulalog" "fortii" "fortyfold" "foulbrood" "fr"
 "fragrans" "franchat" "freeware" "frozen" "frutescens" "fuchsiaefolia" "fukudo" "fulminant"
 "fumigatus" "funders" "funiculosum" "furaciline" "furless" "fusogen" "g" "galacose"
 "galactopyranosyl" "gallbladder" "gamblei" "gancyclovir" "gatekeeper" "gavage" "genolin" "genome"
 "genomewide" "geometries" "ggcgcgtgacatta" "gggaccaagacctaa" "girindusglos" "github" "glandulosum"
 "glehniae" "glia" "globosa" "globulus" "glucantime" "glucotriose" "glutathionyl" "gluthatione"
 "glyco" "glycoconjugate" "glycoforms" "glycosyl" "glycotope" "glycyrrhizae" "goes" "gondii"
 "graecum" "graminei" "grandiflora" "granulosum" "graveolens" "griffithsin" "griseus" "grouper"
 "groupers" "groupware" "gypseum" "gz" "gǁ" "haematocrit" "haemocytometer" "haemolyticus"
 "halobismuthanes" "hammerhead" "hanburyi" "handheld" "haplotype" "haplotypes" "harringtonii"
 "haynaldii" "headspace" "hedycaryol" "heliotropiifolium" "helix" "helleborine" "hematocrit"
 "hemoagglutinin" "hemocytometer" "hemostatis" "hepato" "hepatotropism" "hepatovirus" "heptad"
 "herba" "herbals" "herbivores" "herbology" "hetero" "heteroaryl" "heterobismacycles"
 "heterocomplexes" "heterocylces" "heterodiene" "heterophyllus" "hexahydrate" "hexamer" "hexamers"
 "hexamethyldisilylamide" "hidden" "hinoki" "histology" "histopathology" "holism" "holstii"
 "hominis" "homogenate" "homotrimer" "homotrimers" "homozygotes" "hotspot" "html" "hungarica"
 "huntingtins" "hybride" "hydrogel" "hydrolysate" "hydrolyzate" "hydrophobes" "hydroshengmanol"
 "hydrosol" "hydroxynaphthol" "hydroxysemicarbazides" "hyper" "hyperbilirubinemia"
 "hypercytokinemia" "hyperfine" "hypermagnesemia" "hyperoxaluria" "hyperplane"
 "hyperresponsiveness" "hyperspace" "hyperuricemia" "hyphae" "hypochloride" "hypodermis"
 "hypodynamia" "hypoleuca" "hypomagnesemia" "hypothesise" "hypouricemia" "hypoxemia" "icorrespond"
 "identifier" "identifiers" "ii" "iii" "ileum" "imiquiod" "immunerecovery" "immuno" "immunoassay"
 "immunocytes" "immunohistochemistry" "immunologists" "immunopathology" "immunoprophylaxis"
 "immunoreceptors" "immunospot" "inclusiveness" "incorporators" "indica" "indolyl" "inducers"
 "infantum" "infantumis" "infectiousness" "innocua" "inocula" "inoculum" "inprinciple"
 "insecurities" "insularimontanum" "intelectins" "intercalates" "interfer" "intermedia" "internet"
 "interquartile" "interstitium" "intersubunit" "interviewees" "intra" "intrachain" "intraplasmid"
 "intrasubunit" "intricata" "invaginations" "invanovii" "invariance" "invariant" "inﬂuenza"
 "iodobismitol" "ionic" "ipni" "iridoid" "iridovirus" "isatidis" "isolators" "isomer" "isomers"
 "isosilybins" "isosteres" "isotype" "isotypes" "ist" "italica" "iter" "j" "jackfruit" "jackknife"
 "japonicum" "japonicus" "jasminoides" "jci" "jejunum" "jensenii" "jujuboside" "k" "kansasii"
 "kappa" "karyometry" "kcat" "ketimines" "kinamycins" "kirilowii" "koreana" "l" "lactis"
 "lagenarium" "lamellae" "lamiridosins" "lapochol" "lassa" "lavage" "lavescentis" "learnt"
 "leconformer" "leftover" "legume" "lemairie" "lemongrass" "lenghts" "leprae" "leydig" "libitum"
 "liensinine" "lifecycle" "lifespan" "limon" "linalyl" "lipidoids" "lipopolysaccharides"
 "lipopolyssacharide" "littoralis" "lobules" "logger" "loggers" "logit" "lomaiviticin" "longa"
 "longae" "longi" "longiflorus" "longipalpis" "lsqcurvefit" "lucidum" "luminometer" "luriei"
 "lutea" "luteus" "lymphoblastoid" "lymphopenia" "lynalyl" "lyphoprotein" "macrocephalae"
 "macroorganisms" "macropinocytose" "madurahydroxylactones" "magnoliae" "malariae" "malarie"
 "maltophilia" "mannopyranoside" "mannosidases" "mannosyl" "manose" "marcescens" "maresins"
 "margarita" "marginatum" "marianum" "marisflavi" "maritimum" "marneffei" "marschallianus"
 "martiniana" "materials" "max" "mdx" "mechano" "mechansim" "medica" "meganucleases"
 "melaninogenica" "melanogaster" "mellitus" "membranotropism" "mentagrophytes" "mercaptoethane"
 "merck" "mesangioblasts" "mesityl" "metallo" "metalloamines" "metalloids" "metalloimines"
 "metapneumo" "methanamine" "methosulphate" "methy" "methylenedioxy" "methylenedioxyphenyl"
 "methylsulfonyl" "micelle" "micelles" "microbead" "microbeads" "microbiologists" "microbiota"
 "microcapsules" "microculture" "microcystis" "microdomains" "microdosimeter" "microdystrophin"
 "micromycetes" "microplate" "microplates" "micropockets" "microsphere" "microspheres" "microtiter"
 "microtitre" "microvirin" "microwells" "miltiorrhizae" "minicircle" "minigene" "minima" "minimise"
 "minimizations" "mirabilis" "missense" "missingness" "modiﬁcations" "mone" "monocytogenes"
 "monodentate" "monodisperse" "monofluoro" "monoglucose" "monohydrate" "monolayer" "monophosphate"
 "monophyllum" "monotherapy" "montane" "montbretii" "morpholino" "mosquitos" "mouthwash" "muco"
 "mucosa" "mucosae" "mulatta" "multi" "multicenter" "multiflori" "multigene" "multilocus"
 "multimode" "multiplates" "multiplet" "multiscribe" "multisite" "multistage" "multivariate"
 "multivitamin" "multiway" "murdochii" "musculus" "mutanome" "mutans" "mycoad" "myocardium"
 "myofiber" "myofibroblasts" "n" "nano" "nanobiomaterials" "nanobiomedicine" "nanobioprobes"
 "nanocapsules" "nanocarrier" "nanocarriers" "nanoclusters" "nanocolloid" "nanocolloids"
 "nanocomposites" "nanoconjugate" "nanoconjugates" "nanocrystalline" "nanocrystallites"
 "nanocrystals" "nanodiamond" "nanogold" "nanohorns" "nanomaterials" "nanomedicine"
 "nanoparticulate" "nanoplatforms" "nanoscale" "nanosensors" "nanosilver" "nanospheres"
 "nanotechnology" "nanotoxicology" "nanovaccine" "naphthalimide" "naphthalimides" "naranjillo"
 "nauplii" "nearest" "nebulizer" "necropsy" "negatives" "neonatorum" "neparvovec" "neue" "neuro"
 "neuroepithelium" "neutropenia" "neverthelesss" "neverthless" "niger" "nigrum" "nistatine"
 "nitrato" "nitrosohydrazone" "nivalis" "niveus" "nobilis" "nonfat" "nonhuman" "nonpump"
 "nonresearch" "nonschool" "normouricemia" "notoginseng" "nth" "nucifera" "nuclein" "nucleoside"
 "nucleosides" "nucleotidyl" "nuclide" "nujol" "nutraceuticals" "o" "objectives" "obovata"
 "observables" "obtusa" "ochraceoroseus" "ochraceus" "ochrochloron" "octahistidine"
 "octylcinnamates" "odorata" "oedema" "officinale" "officinalis" "oligoadenylate"
 "oligodeoxynucleotides" "oligoes" "oligomerise" "oligonulceotides" "oligouridine" "oncologists"
 "oncology" "oneistus" "ones" "onites" "onium" "ons" "operculatus" "ophiopogonin" "ophiopogonis"
 "oraganoantimony" "oragnobismuth" "orbitals" "oregano" "organisations" "organischer" "organo"
 "organobismuth" "organolithium" "orientale" "orientalis" "ornifolia" "ortho" "orthoformate"
 "orthograft" "ortholog" "orthologues" "orthomyxovirus" "orthophenylendiamine" "os" "osmophloeum"
 "othe" "ought" "ovata" "overuse" "overview" "ovo" "oxidise" "oxocarbazate" "oxycedrus"
 "oxychloride" "oxymethine" "pachyonychia" "pairwise" "palliatives" "pancreatitis" "papatasi"
 "papilla" "paracrine" "paraesthesias" "parainfluenza" "paramagnetism" "parterns" "particulate"
 "partum" "parvifolia" "pastinacifolium" "pastoris" "pathophysiology" "pdf" "pentadentate"
 "pentaphylli" "penton" "pentons" "pentylbenzene" "peptidyl" "peptone" "perfluoropolyether"
 "perhaps" "perniciosa" "perniciosus" "peroxidant" "peroxyl" "persicum" "persistant" "petits"
 "pharmacopeia" "pharmacophore" "phellodendri" "phenols" "phenylangelate" "phenylbenzopyrone"
 "phenylpyrrole" "phenylthiosemicarbazone" "phenyltiglate" "philippinarum" "phoeniceae"
 "phosphatadylcholine" "phosphodiester" "phosphonoalkyl" "phosphonyl" "phosphopeptide"
 "phosphorodiamidate" "photocatalyst" "photoreactors" "photostabilisers" "phototherapy" "phylogeny"
 "physico" "picornoviridae" "pigmentosa" "piperascens" "piperazinyl" "piperis" "piperita"
 "pistaciiflorum" "plasmacytoid" "plasmalogen" "plasmepsin" "plasmepsins" "plasmon" "platlets"
 "pleura" "pleurodynia" "pleuropneumoniae" "plumbaginis" "plutonius" "pnictogens" "polarimeter"
 "polium" "polycations" "polyclada" "polycrystalline" "polydisperse" "polyethylenimine"
 "polyethyleninime" "polygalae" "polygoni" "polylactides" "polymerise" "polymorphism" "polyphyllin"
 "polyplexes" "polyspermine" "polyuridine" "pombe" "positives" "postconquest" "postpartum"
 "potasium" "pre" "precentage" "precocene" "precut" "prehairpin" "preload" "preschools"
 "preservatives" "pretest" "priori" "progeny" "propanoids" "propargyl" "propenylphenols"
 "prostheses" "proteinopathies" "protomers" "proven" "proventriculitis" "proventriculus" "proximus"
 "psb" "pseudonarcissus" "pseudoparticles" "pseudosubstrate" "pseudotype" "pseudovirions"
 "pseudoviruses" "psittacine" "pulcherrima" "pulmonale" "pygones" "pyogenes" "pyrazinone" "pyrazol"
 "pyrazoles" "pyridinium" "pyridyl" "pyridylthiosemicarbazone" "quadripartite" "quadruplex"
 "quadrupole" "quasi" "quasispecies" "quencher" "quercitin" "quinazolinone" "quinazolinones"
 "quinones" "quintile" "r" "rabdosiae" "radiocarbon" "radiometals" "radionuclides"
 "radioresistance" "radix" "raetam" "rainforest" "rarer" "rdfs" "reactants" "readout" "readouts"
 "recens" "recruite" "reduscd" "reflectance" "regrowth" "relatedness" "relaxant" "replicon"
 "representativeness" "representatives" "residuals" "residuces" "responders" "reticulum"
 "revertant" "revtat" "rhabdovirus" "rhodanta" "riboswitch" "ridership" "riedelianum" "ringspot"
 "rnasep" "roommates" "rosaeodora" "roundbottom" "rpm" "rubescens" "rubra" "ruetzleri" "rumen"
 "rzyl" "salicylidene" "salicylidenebenzylamines" "salina" "salviae" "samarangense"
 "samaritanpharma" "santoline" "saponins" "sativum" "scabra" "scarless" "schenckii" "schisandrae"
 "schwetzi" "scissile" "scoparia" "screenings" "scutellariae" "scytovirin" "sealant" "seawater"
 "sebum" "sediments" "segetum" "semi" "semliki" "sensu" "sequelae" "sergenti" "serotype"
 "serotypes" "sertiform" "sesquiterpenids" "sgps" "shaken" "shavings" "shengmaxinside"
 "shigelloides" "shutoff" "sialyl" "sibs" "sidechain" "sidechains" "signiﬁcance" "silico"
 "silylimines" "simaruba" "simplex" "simulans" "sindbis" "singleplex" "slows" "smartphone" "socio"
 "solids" "solute" "solutes" "sonnei" "sophorae" "spacer" "speciﬁc" "spectrograph" "spectrometer"
 "spectrophotometer" "spiegelmers" "spinosa" "spinosae" "spinosum" "splitless" "spoilage" "squares"
 "ssp" "stabile" "stephaniae" "stepwise" "stereochemistry" "stereoisomers" "stipes" "stressful"
 "stressors" "stretchings" "stricto" "strongher" "suan" "subacute" "subcitrate" "subclasses"
 "subgenotypes" "subgenus" "subhaplogroups" "submucosa" "subsalicylate" "subsample" "subsamples"
 "subsp" "substituents" "substitutents" "subsystems" "subtilis" "subtype" "suis" "sulfhydryl"
 "sunki" "superbug" "superbugs" "supercomplexes" "superhyperfine" "supermix" "supernatant"
 "supernatants" "superscript" "superspreader" "surveil" "sylvestris" "synergism" "synthases"
 "syriacum" "taeniaeformis" "taken" "tatagaatt" "tegmen" "telestem" "temozolamide" "tenuifolium"
 "terminators" "terpinoids" "tertile" "tertiles" "tester" "tetradecasaccharide"
 "tetraethoxyorthosilicate" "tetragonolobus" "tetrandrae" "tetrazolium" "tetroxide"
 "theriogenology" "thermo" "thermocycler" "thermogravimetry" "thermotherapy" "theta"
 "thiabismocine" "thiazoline" "thiocarbonohydrazone" "thione" "thiosemicarbazides"
 "thiosemicarbazone" "thiosemicarbazones" "thioureido" "thioxoketonates" "thisosemicarbazone"
 "thymbra" "thyphimurium" "timelines" "timesteps" "timosaponin" "titer" "titers" "titrations"
 "titres" "tobramycine" "toolbox" "topology" "topsentin" "toroid" "toxicant" "tragium" "trainin"
 "trainings" "tranquilizers" "transcriptome" "transdermakl" "transducer" "transductants" "transect"
 "transgenes" "transmebrane" "transportan" "transposon" "traumatology" "trialkylsilyl" "tricuspid"
 "tricyclodecane" "tridentate" "triester" "triethylammoniumacetate" "trifluoromethoxy"
 "triglucosyl" "trimannosyl" "trimethoxy" "trimethyl" "trimethylene" "triphenyl" "tripterygii"
 "triturate" "trivorsan" "tropica" "tryptone" "tumorigeneses" "tunicate" "tupaia" "tuple"
 "turbinates" "turbith" "txt" "typhi" "typhimurium" "u" "uchicago" "ucl" "ucsc" "ugent" "uij"
 "ultrathin" "un" "undergoes" "undergone" "undertaken" "univariate" "unmet" "unresponsiveness"
 "unshiu" "uploads" "upsamplers" "uraninite" "uranyl" "uridines" "utilze" "vacuo" "var" "variables"
 "variola" "varium" "vatke" "vena" "veno" "ver" "verbenacea" "verticillus" "vertisols" "verum"
 "vii" "virdis" "viremia" "viride" "viridians" "viridis" "virosomes" "virosphere" "viscosus"
 "viscus" "vitalis" "vitispirane" "vitro" "vivax" "vivo" "volatiles" "voretigene" "voxel" "vulgare"
 "vulgaris" "wallichii" "washings" "wavelet" "weakeness" "weaner" "webby" "website" "widw"
 "wilfordii" "wismuth" "withdrawn" "wordpress" "workflow" "workup" "worldbank" "worn" "wp"
 "written" "wtih" "www" "x" "xanthate" "xmipp" "y" "ylang" "z" "zao" "zeylanicae" "zeylanicum"
 "zeylonicum" "zingiberis" "ziziphi" "zoonoses" "zygis" "zymogens" "ð" "ʋ" "ʋas" "ⅈ" "ⅉ" "口罩"
 "ﬂavus" "ﬂoccosum" "ﬂow" "ﬂuconazole")))
    :test #'equalp))


(defparameter *MixedCase-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*MixedCase-Unknown-Words*) (symbol-value `*MixedCase-Unknown-Words*))
         '(
("ABDserotec" "ACVr" "AChI" "ASReml" "AUGs" "AbD" "Aba" "Ababa" "AbbVie" "Abies" "Abreu" "AcSAH"
 "AcSa" "Acari" "AciI" "Actinomycetes" "AdV" "Addis" "Adel" "Aedes" "Aegean" "Aegypti" "AffyCEU"
 "Affymetrix" "AgNano" "Agaricus" "Ageratum" "Agincourt" "Aidenbach" "Aktotiri" "Aladdin"
 "Albopictus" "Aldrich" "Alexa" "Alisma" "Alisol" "Alofisel" "Alpinia" "Alsachim" "Alzheimer"
 "Alzheimeŕs" "AmB" "Amaryllidaceae" "AmaxaTM" "Ambrum" "Americans" "Amersham" "Amomum" "Amt"
 "Analyser" "Ancistrocladaceae" "Anemarrhenae" "AniMarin" "Aniba" "Ann" "Annelloviridae"
 "Antennapaedia" "Anthriscus" "AntiMarin" "Apergillus" "Apium" "Apoalert" "ArH" "Aradigm"
 "Araliaceae" "Arcangeli" "Arcanobacterum" "Archemix" "Arenaviridae" "Aristolochia" "Arkadiusz"
 "Armeniacae" "Armonk" "Artemia" "Artemisia" "Arteriviridae" "Arterivirus" "Artocarpus" "Ashland"
 "Asso" "Astragali" "Atgs" "Athamanta" "Athens" "Atractylodis" "AttributeSelectedClassifier"
 "AutoDockTools" "AutoGrid" "AutoTors" "Autoelex" "Autosampler" "Autospec" "Avance" "Avg" "Axentis"
 "AxyPrep" "Ayyanppan" "Azidophosphonates" "BAMs" "BCFtools" "BMDMs" "Bacilllus" "Bagaza" "Balf"
 "Baragwanath" "Barbey" "Barcelona" "Barloworld" "Bayda" "Beckman" "Becton" "Belgrade" "Belo"
 "Benth" "Benzoylchloride" "Benzyloxy" "Berber" "Bergisch" "Bergstraße" "Bern" "Bertha" "Berzelius"
 "BestFirst" "Besut" "Bethesda" "Beyotime" "BgH" "BglI" "BiOCl" "BibTeX" "Bibliometrix" "Billerica"
 "BioEdit" "BioMedia" "BioPOA" "BioRad" "Bioanalyzer" "Biochem" "Biolabs" "Biomedia" "Biomedicals"
 "Bioneer" "Biopharma" "Bioproducts" "Bioresource" "Bioss" "Biosystems" "Biotec" "Biotech" "Biotek"
 "Birbeck" "Birdw" "Birnavirus" "Bismol" "Bisprin" "Bitplane" "Blanco" "Bleomycins" "Bluetooth"
 "Blume" "BoV" "Boetius" "Bohe" "Boiss" "Bonferroni" "Boolean" "Bornholm" "Botrytis" "Bošković"
 "Brea" "Bremen" "Brisbane" "Brot" "Browser" "Brucker" "Bruker" "Brune" "Bst" "BtH" "BtcCl"
 "Bubendorf" "Budapest" "Bulbus" "Burlington" "Bursera" "Böetteger" "Büchi" "CEPs" "CHCl" "CHMs"
 "CHaHb" "CLDs" "CLOSEcon" "CMVie" "CNPs" "CNTs" "COCs" "CPPs" "Caki" "Caldefie" "Calibur"
 "Callyspongia" "Calzolari" "Campanulaceae" "Cananga" "Canaria" "Canavalia" "Cangzhu" "Caoguo"
 "Capparis" "Carlo" "Carlsbad" "Carum" "Cary" "CaspaLux" "Caulis" "CdSe" "CdTe" "Cdyn" "CeGen"
 "Cephalotaxus" "Cftr" "Chagas" "Chaix" "Chamaecyparis" "Chamecyparis" "Champigny" "Changhua"
 "Changi" "Charlson" "Charmm" "Cheel" "Cheistocalyx" "Chelmsford" "ChemAxon" "ChemBioDraw"
 "ChemDiv" "ChemiDoc" "Chemlali" "Chewa" "Chirascan" "Chiropteran" "Chol" "Chonbuk" "Chonglou"
 "Chromas" "ChromasPro" "Chuan" "Cimicifuga" "Cinnamomum" "Circoviridae" "Circovirus" "Claude"
 "Cleistocalyx" "Clementine" "Clercq" "Clontech" "ClustalW" "Cmax" "Cochrane" "Colletotrichum"
 "Colter" "Columbia" "Comate" "Commiphora" "Compostela" "Coomassie" "Cordia" "Cordouan"
 "Coriandrum" "Corp" "CountBright" "Covalab" "Coxsackie" "Coxsackieviruses" "Crassostrea" "Crete"
 "Crevost" "Crithmum" "Crohn" "Cronbach" "Cryptomeria" "CrysAlis" "Culex" "Cuminum" "Cymbidium"
 "Cymbopogon" "CytoPainter" "DAAs" "DMVs" "DNApac" "DNAzyme" "DNAzymes" "Daejeon" "Dako" "Dallas"
 "Dalmatia" "Danpi" "Danvers" "Darmstadt" "Daubechies" "Deajeon" "Dehnh" "Denhardt" "Dentaire"
 "Desal" "Desf" "DharmaFECT" "Dickenson" "Didemnum" "Diego" "DifcoTM" "Difteria" "Dioncophyllaceae"
 "Dionex" "Dioscoreaceae" "DistSim" "Distichoselinum" "Divinópolis" "Dodecadenia" "Donnerstein"
 "Dorothy" "Dounce" "Dragmacidon" "Dresden" "Drigalski" "DuCV" "Duchenne" "Ducke" "Dulbecco"
 "Dulbecos" "Duren" "Dynex" "Düsseldorf" "EDEMs" "ELx" "Eastwin" "Edendale" "Eiken" "Eindhoven"
 "Eine" "Einter" "Elettaria" "Elmer" "Endproducts" "Enf" "Entacmaea" "Epipactis" "Epithelix" "Epon"
 "Eppendorf" "Erlangen" "Erlenmeyer" "Esum" "Euclidean" "Eugene" "Eugenia" "Eurobio" "EvaGreen"
 "EvdW" "Eveness" "FACSAria" "FACSCanto" "FACSCantoII" "FACScan" "FASTAcon" "FASTAskan" "FESs"
 "FSNPs" "Fabricius" "Fallavier" "Farfugium" "Fayoumi" "FeLV" "Femto" "Fenton" "Fernbach" "Finetek"
 "FitBits" "FlLuc" "FloJo" "Flowjo" "Fluorophore" "Foeniculum" "Folia" "Fondevila" "Forssk"
 "Fortunella" "Fourier" "Frederick" "Fremont" "Fritillariae" "FroggaBio" "Fruchterman" "Fructus"
 "Fuerteventura" "Fujifilm" "Fullerton" "Fundação" "Furaciline" "Fällanden" "GHz" "GRFTres" "GTEx"
 "Gaithersburg" "Galanthus" "Galindo" "Gallander" "Gallenkamp" "Ganoderma" "Garcinia" "Gaussview"
 "Gauteng" "Gedarif" "GelRedTM" "Gelovani" "Gelsinger" "GenBank" "GenEx" "GenScript" "Genbank"
 "GeneArt" "Genecreate" "Geoffroy" "Gerardo" "Gglycogen" "Gibco" "Giga" "Gilead" "Gillett" "GimHae"
 "Gini" "Gladbach" "GmbH" "Gomera" "Goods" "Goor" "Gottberg" "Gran" "Grande" "GreedyStepwise"
 "Griess" "Griffithsia" "Grifols" "Grignard" "Grubbs" "Guanarito" "Guanche" "Guangdong" "Guangzhi"
 "Guillen" "Guio" "GumGyul" "Gunung" "GyeongNam" "Gynostemmatis" "Gyrovirus" "Göteborg" "HAcPh"
 "HAcpClPh" "HAdv" "HCVpp" "HCVr" "HCWs" "HDAd" "HDVr" "HELFs" "HETEROalign" "HMTGs" "HOBOmobile"
 "HPEKs" "HRoV" "HSAs" "HSal" "Haimen" "Haiyang" "Hamburg" "Hani" "Hannover" "Hanoi" "Hantaan"
 "HapMap" "HaplotypeCaller" "Harbin" "Haromat" "Harvard" "Hastelloy" "Hayata" "Hct" "HeartMate"
 "HeartWare" "Heatlhcare" "Heidelberg" "Heilong" "Heilongjiang" "Heinrich" "Heldr" "Helichrysum"
 "Henan" "Hendra" "Hendravirus" "Henriette" "Heracleum" "Herba" "Herbarium" "Hercules" "Hexadella"
 "HiSeq" "HiSeqTM" "Highveld" "Hilden" "Himalayan" "HindIII" "HipHop" "Hippeastrum" "Hirszfeld"
 "Hoddeston" "Hoechst" "Hoffmanns" "Homozygotes" "Horizonte" "Horstmann" "Houtt" "Houttuyniae"
 "Hpn" "Hpure" "Hsinchu" "HspA" "Hstudio" "Huangbai" "Huanghai" "Huangqi" "Huangqin" "Hulu" "Humic"
 "Huntington" "HxS" "Hyalomma" "Hybond" "Hymenocrater" "Hyppeastrum" "Hz" "Hüisgen" "IECs" "IFNARs"
 "IONPs" "Ietswaart" "IgY" "Illicium" "Illumina" "ImageJ" "ImageLab" "Imager" "Imaris" "InP"
 "Infatrini" "Inova" "InsightII" "Insitute" "Institut" "Internationale" "InvivoGen" "IonSpec"
 "Ipswich" "Iridoviridae" "Iridovirus" "Isaria" "Iscove" "Istituto" "Ixodidae" "JChem" "Jaagsiekte"
 "Jaccard" "Janeiro" "Jennio" "Jenway" "Jeol" "Jesse" "Jevremovac" "Jiaogulan" "Jiegeng" "Jilin"
 "Jim" "JinGyul" "Jinyinhua" "JmolApplet" "Joes" "Johannesburg" "Jolla" "Jrans" "Jtrans" "Jukes"
 "Junin" "Kaifeng" "Kaneh" "Kaposi" "Karachi" "Karlsruhe" "Karolinska" "Keison" "Keli" "Kemika"
 "Kew" "Khartoum" "Kidlington" "Kimble" "Kinetoplastida" "Kingsuromax" "Kitt" "Klerksdorp"
 "Knoevenagel" "Kombinat" "Koreans" "Kosterm" "Kostern" "Kováts" "Kowloon" "Kraken" "Kraków"
 "Krovacek" "Kunth" "LaSota" "Labill" "Lactobacilli" "Laghouat" "Lakewood" "Lambda" "Lamium"
 "Landwirtschaft" "Lanzarote" "Lasir" "Latin" "Lauraceae" "Laurus" "Lavander" "Lavandula" "Laxus"
 "Leber" "Leco" "Lederle" "Leguminosae" "Leibovitz" "Leidos" "Lemairé" "León" "Licaria"
 "Licochalcone" "LigandScout" "LightCycler" "Ligplot" "Ligusticum" "Likert" "Liliaceae" "Lilongwe"
 "Lindera" "Lindl" "Linn" "Linum" "Linux" "Lippia" "Lisowska" "Listera" "Lodz" "Logan" "Lonicerae"
 "Lonza" "Lorenz" "Lotka" "Louis" "Luciola" "Luminex" "LuminexTM" "Lusaka" "Luxturna" "Löwe" "MBCs"
 "MBq" "MFCs" "MNPCEs" "MNPs" "MPEKs" "MSRoute" "MVNres" "MWCNTs" "Machupo" "Macugen" "Madin"
 "MagNa" "Maghreb" "Magna" "Magnettech" "Magnoliopsida" "Maidong" "Majorana" "Majorbio" "Malay"
 "Mallotus" "Manassas" "Manchester" "Mandenka" "Mannheim" "Mannich" "Maná" "Mapitope" "Mapulaneng"
 "Margalef" "MarinLit" "Markov" "Marne" "Marsupenaeus" "MassLynx" "Mathew" "Mathworks" "Matikwana"
 "Maton" "Maxi" "Mayaro" "Mayr" "Mazury" "Mazz" "MbNP" "MbNPs" "McIlwain" "MeanDecreaseAccuracy"
 "MeanDecreaseGini" "MedChemExpress" "Mederos" "Medimabs" "Medison" "Meisn" "Melaleuca" "Meliaceae"
 "Melissococcus" "Menhinick" "Mentagrophytes" "Mentha" "Menthae" "Merck" "Metropole" "Miazek"
 "Microbiologica" "Micrograph" "Microneedles" "Microplate" "Microsoft" "Microsystems" "Millex"
 "Millipore" "Millville" "Miltenyi" "Miltiorrhizae" "MimAlign" "MimCons" "MimoDB" "MimoPro"
 "MiniScope" "Mississauga" "Miswak" "ModFit" "Modulus" "Molish" "Molsheim" "Monmouth" "Montanide"
 "Moraceae" "Moritz" "Mosquiera" "Moutan" "Mpumalanga" "Mulliken" "MultiD" "MultiScreen"
 "Multicenter" "Multiskan" "Multisource" "Murrieta" "Myrianthus" "Myristica" "Myrtus" "Männedorf"
 "Münters" "Nagel" "Nannamaliai" "NanoAg" "NanoLuc" "Nanobiosensors" "Nanobiotechnology"
 "Nanodiamonds" "Nanographene" "Nanoshuttle" "Nanotechnology" "Naphthalimide" "Natick" "Natur"
 "Nees" "Nelumbo" "Nereus" "Neuen" "Newcastle" "NiRAN" "Nicotiana" "Nidovirales" "Nikon" "Nimine"
 "Norcross" "Northampton" "Nortopsentins" "Norwalk" "Nostoc" "Novirhabdovirus" "Npy" "Nuaillé"
 "NucleofectorTM" "Nutricia" "Nuvelo" "Nyanja" "Náves" "OAc" "ODNs" "ODcompound" "ODof" "ODvirus"
 "OMePS" "Olea" "Olsztyn" "Olympus" "Omacetaxine" "Omniscript" "Onrubia" "OpenMM" "Ophiopogon"
 "Ophiopogonis" "Optec" "OptiLab" "Origanum" "OriginLab" "OriginPro" "Orthonairovirus" "Osaka"
 "Osbeck" "Oscillatoria" "Otsu" "Ouates" "Overhauser" "Ovid" "PCCCHaHb" "PCCHaHb" "PCHaHb" "PMOs"
 "PPBSs" "PSs" "Packard" "Palma" "Palo" "Panjwani" "Paolo" "ParSP" "Paraiba" "Paridis" "Parslow"
 "Particulate" "Peltier" "Pentaherb" "Pepitope" "Pepto" "Perfezionamento" "Perkin" "Persea"
 "Peschiera" "Peste" "Pette" "Peyer" "Pfaffl" "Pfizer" "PhBi" "Pharma" "Pharmacia" "Phaseolus"
 "Phaser" "Phellodendri" "PhiPhiLux" "Philadelphia" "Phlebotominae" "Phlebotomine" "Phlebotomus"
 "Phyllanthus" "PiCV" "Picard" "Pietermaritzburg" "Pimpinella" "Pintado" "Piscataway" "Pistacia"
 "Pistello" "Platycodonis" "Plazmatronika" "Pleasanton" "PnkRNA" "Po" "Pogostemon" "Poisson"
 "Polaris" "Polygalaceae" "Polygonatum" "Polygonum" "Polynesia" "Polysciences" "Pople" "Potocoki"
 "PrPSC" "Pratici" "Premix" "PremixExTaq" "PrimeScript" "PrimerExplorer" "Promega" "Proteintech"
 "Psammogeton" "PsycINFO" "Pterodon" "Pty" "Pune" "Punta" "Pylaiella" "Qiagen" "Qingdao" "Qualimap"
 "Quant" "QuantiNova" "Quanto" "Qubit" "QuikChangeII" "Quinazolinone" "RAFIs" "RCLs" "RMSDs"
 "RNAiso" "RNAseIIIb" "RNaseIIIa" "RNeasy" "ROHs" "RRj" "RSLuc" "RStudio" "Rabdosia" "Radic"
 "Radix" "Ralf" "Ranavirus" "Rancimat" "Ranunculaceae" "Rapak" "Rcom" "Refmac" "RegRNA" "Regio"
 "Reichenb" "Reihe" "Renilla" "Retama" "ReverTra" "Rheinstetten" "RiboBio" "Ricinus" "Rico" "Ridl"
 "Ridolfia" "Rio" "Risso" "Rockefeller" "Rockford" "Rockville" "Roscoe" "Rosmarinus" "Roswell"
 "Rotkreuz" "Roxb" "Rstudio" "Rudjer" "Russel" "SAMiRNA" "SAMtools" "SEMs" "SVMs" "SWCNTs" "Sabia"
 "Sabouraud" "Sabouroud" "SacI" "Sahara" "Sahel" "Sakura" "Salicylidenebenzylamine" "Salinispora"
 "Salisbury" "Salviae" "Samaritan" "Sanger" "Sangon" "Santiago" "Sanwu" "Saok" "Sardinia"
 "Satureja" "Saudi" "SbR" "Sbjct" "Scheelevägen" "Schisandra" "Schisandrae" "Schizosaccharomyces"
 "Schnelldorf" "Schoeller" "Schreber" "Schuurmann" "SciFinder" "Sciex" "Scopus" "Scrophulariaceae"
 "Scutellariae" "Scytonema" "Selleckchem" "Semliki" "Sendai" "Seongnam" "Seoul" "Serg"
 "Sergentomyia" "Serotec" "Setiu" "Shannon" "Shanyao" "Shengma" "Shiga" "Shimadzu" "SiNPs"
 "Siebold" "SigmaPlot" "Silberlocke" "Silybum" "Sinai" "Sindbis" "Siniša" "SiteLight" "Solarbio"
 "Solon" "Sowings" "Spearman" "SpectraMax" "Spectramax" "Spherox" "Spiegelmers" "Spondweni"
 "Spongosorites" "Spreng" "SpyH" "Ssurf" "Staffordshire" "Stamford" "Standardizer" "Stanković"
 "Stapf" "Starstedt" "StdSens" "StepOne" "StepOnePlus" "StepOneTM" "Stephania" "Stimvelis"
 "Stockholm" "Stockolm" "Studi" "Suan" "Succinum" "Sudanese" "Sungene" "Superdex" "Superiori"
 "Superscript" "Surrey" "Susscrofa" "Sussex" "Swizerland" "Synchrovax" "Systat" "Syzygium" "São"
 "Sörensen" "TALENs" "TIANgel" "TSchG" "TSchV" "Tacaribe" "TakaRa" "Takara" "Taq" "TaqMan" "TaqTM"
 "TargetScan" "Taxandria" "Tebu" "Tecan" "Technelysium" "Techno" "Tembusu" "Temecula" "Tenerife"
 "TentaGel" "Terengganu" "Teucrium" "Tewksbury" "Thermo" "ThermoFisher" "ThpR" "Thunbergii"
 "Thypimurium" "Tianjin" "Tibetans" "Tivorsan" "Tochigi" "Toona" "TopoPSA" "Topsentin" "Topsentins"
 "Toro" "Toronto" "Torrance" "Torreya" "Towne" "Toyobo" "Transcriptome" "Transformants" "Transwell"
 "Trasadingen" "Trichosanthes" "Trichosanthis" "Trigonella" "TruSeq" "Trypanosomatidae" "Tsukuba"
 "Tukey" "Tumbuka" "Tunicamycine" "Tunis" "Tunisians" "Tween" "Tygon" "Typanosomatidae" "Ugo"
 "Ultima" "UltraTM" "UltraTech" "Ultraflex" "Ultrasphere" "Ultrathin" "Ultrez" "UniProt"
 "Univariate" "Universidad" "Université" "Uppsala" "UreI" "Urtica" "Urticaceae" "Urticadioica"
 "Uukuniemi" "VIIa" "Valo" "Velcro" "Vellore" "Venenum" "Venerupis" "Venn" "Verlet" "Vernier"
 "Veterinärdienst" "ViTa" "Villeurbanne" "Vina" "Virola" "Visualizer" "VitroCol" "Waals" "Waldst"
 "Wallac" "Waltham" "WarmStart" "Warmia" "Wednesdays" "Weka" "Wesselsbron" "Wheller" "Wilcoxon"
 "Wiley" "Willowbrook" "Wilmington" "Winooski" "Witwatersrand" "WoS" "Worcester" "Wrocław" "Wöhler"
 "Wölher" "XIXth" "XLOrbitrap" "XVIIth" "XVIth" "XVth" "XXth" "Xaa" "Xe" "Xiaofeng" "Xuwen" "Yale"
 "Yantai" "Yilite" "Yongin" "ZFNs" "Zagreb" "Zalmoxis" "Zanthoxylum" "Zata" "Ze" "Zeiss" "Zhimu"
 "Zingiber" "ZnSe" "Zucc" "Zug" "Zurich" "aHRs" "aPTT" "antimiR" "bAPY" "badMIXTURE" "Bioaerosol"
 "cLogP" "cccDNA" "CrysAlisPro" "WinGX" "conceptualStructure" "dbSNP" "eQTL" "fMRI" "Fulminant"
 "guavaSoft" "hAECBs" "hCEF" "hDAF" "hPyV" "hTF" "hlyA" "iBLOT" "iMLDR" "iPTH" "iQ" "iScript"
 "lysoPE" "mHealth" "Methylenedioxyphenyl" "miRNeasy" "mirVana" "mosGCTL" "msHOT" "nPNA"
 "networkPlot" "oligoA" "oligoU" "oriP" "pKW" "pLysS" "pMWU" "pcDNA" "pgRNA" "piggyBac" "pmirGLO"
 "polyA" "rAAV" "rGO" "rNTP" "rZIKV" "sCD" "sDAF" "sfRNA" "sssCH" "uOR" "vdW" "xMAP")))
    :test #'equalp))


(defparameter *FirstNames*
    (remove-duplicates
      (append 
         (when (boundp '*FirstNames*) (symbol-value `*FirstNames*))
         '(
("Alexander" "Andrzej" "Anne" "Antonio" "Charles" "Cheng" "Cheryl" "Chris" "Chun" "Clara" "DAVID"
 "Ebrahim" "FEI" "Florette" "George" "Halima" "James" "Jens" "Jin" "Jose" "Joseph" "Kai" "Kathleen"
 "Lorenzo" "Marietjie" "Marta" "Marthi" "Meredith" "Michael" "Nicole" "Orienka" "Richard" "Shabir"
 "Shaohua" "Sibongile" "Stefano" "Thi" "Xue" "Yang" "Zhao")))
    :test #'equalp))


(defparameter *LastNames*
    (remove-duplicates
      (append 
         (when (boundp '*LastNames*) (symbol-value `*LastNames*))
         '(
("Abbott" "Alexander" "Allen" "Althaus" "Alton" "Alves" "Amadori" "Andersen" "Andrews" "Andrés"
 "Apgar" "Arabi" "Arauna" "Arn" "Atieh" "Aubry" "Austin" "Awale" "Bai" "Balannik" "Bandiera"
 "Banerjea" "Baran" "Bartenschlager" "Basler" "Bayer" "Bayindir" "Bellon" "Bersaglieri" "Berthelot"
 "Beurel" "Bezerra" "Bifolchi" "Bitko" "Booker" "Boratyn" "Bose" "Botigué" "Boyd" "Bradford"
 "Branche" "Bredius" "Briggs" "Brueton" "Buchner" "Bueno" "Bukh" "Burlingame" "Burm" "Cabrera"
 "Cadwell" "Camborde" "Campbell" "Cao" "Caplen" "Carraher" "Castella" "Castoldi" "Castro"
 "Ceballos" "Chai" "Chainy" "Chan" "Chang" "Chao" "Charrel" "Chatterjee" "Chen" "Cheng" "Cherel"
 "Chien" "Chimusa" "Chiow" "Choi" "Chou" "Christensen" "Christiansen" "Chun" "Cianci" "Ciechanover"
 "Cioranescu" "Cline" "Coffey" "Cohen" "Conde" "Contin" "Coombs" "Cosentino" "Covalciuc" "Crosby"
 "Cruz" "Cunningham" "DAVID" "Darby" "Davis" "Dawood" "DePristo" "Deardon" "Delaneau" "Delboy"
 "Demicheli" "Deng" "Denisova" "Dickinson" "Dignan" "Dixit" "Dixon" "Dong" "Drexler" "Du" "Duan"
 "Durbin" "Ebrahim" "Edgar" "Edmonton" "Ehrlich" "Elbashir" "Elechiguerra" "Eleftheratos"
 "Ellington" "Ellis" "Emerson" "Erard" "Esperandim" "Essex" "FEI" "Falkenburger" "Faraday"
 "Fattovich" "Fazekas" "Felgner" "Feng" "Ferraz" "Ferreira" "Feucht" "Feynman" "Finney"
 "Fitzsimmons" "Flores" "Fonseca" "Francois" "Fregel" "Frezard" "Friebolin" "Fujie" "Gadea"
 "Galanter" "Garcia" "Gardi" "Garske" "Gayday" "Gelman" "Genjiro" "George" "Geysen" "Ghani"
 "Giannakopoulos" "Gibson" "Gilliam" "Gleeson" "Glickman" "Goldberg" "Gorman" "Grasso" "Greene"
 "Gregoriadis" "Gu" "Guan" "Guazelli" "Gurdasani" "Gurunathan" "Gutenkunst" "HA" "Halperin"
 "Hampton" "Harki" "Harrison" "Harty" "Hashimoto" "Hatfield" "Hathaway" "Haworth" "Hayward" "Heim"
 "Hellferscee" "Henn" "Henriksen" "Hewlett" "Higgins" "Hirsch" "Holm" "Holmes" "Honkinen" "Hooton"
 "Hoppe" "Hosmer" "Hou" "Hrobowski" "Hu" "Huang" "Huebner" "Hugo" "Hutspardol" "Hyde" "Ikeda"
 "Ingallinella" "Inoue" "Ishiguro" "Ismail" "Iuchi" "Jackson" "Jagasia" "Jakobsdottir" "James"
 "Janssen" "Jayaraj" "Ji" "Jiang" "Jin" "Johnson" "Jope" "Joseph" "Kahn" "Kang" "Kanlaya" "Karpe"
 "Kaspari" "Katsuma" "Kawaguchi" "Keimatsu" "Kern" "Khattab" "Kiel" "Kim" "Kirin" "Kitamura"
 "Klostranec" "Kmeid" "Knowles" "Kollman" "Kondoh" "Koulman" "Krawiec" "Krebs" "Kucharski"
 "Kumamoto" "Kumar" "König" "Laemmli" "Lanford" "Lange" "Langley" "Largeron" "Larsen" "Laurikkala"
 "Lemeshow" "Lencz" "Lenman" "Lessa" "Leussink" "Lian" "Liao" "Liberman" "Librado" "Lindenbach"
 "Lipinski" "Liu" "Longenberger" "Lorenzo" "Lovestone" "Lucas" "Lumb" "Luna" "Lund" "Luscieti"
 "Luther" "Lwelamira" "Lyons" "MacLeod" "Machlin" "Madhi" "Madisch" "Maher" "Mai" "Makino"
 "Malakhov" "Malam" "Maldini" "Mameli" "Manrai" "Marchant" "Marciniak" "Marshall" "Marzano"
 "Mathieson" "Matsumura" "Matthews" "Mayrose" "McIntyre" "McLean" "McMorrow" "Medola" "Meijer"
 "Menendez" "Meng" "Meredith" "Michael" "Mighri" "Milo" "Miranda" "Mirkin" "Mkhatshwa" "Moe"
 "Moltke" "Monte" "Montgomery" "Moradpour" "Moreau" "Moris" "Moses" "Moucari" "Muench" "Mumey"
 "Mummert" "Murafuji" "Mutso" "Nagamine" "Najafzadeh" "Nakayama" "Narayanan" "Navarro" "Ndoja"
 "Negi" "Negro" "Nemerow" "Neubauer" "Newman" "Nicoletti" "Nikonov" "Nikoulina" "Nilsson"
 "Nishiura" "Niu" "Noguchi" "Nolan" "Notomi" "Odagaki" "Oka" "Okonechnikov" "Oksenberg" "Oliveira"
 "Olson" "Ono" "Papanastasiou" "Papp" "Parkinson" "Parvongnukul" "Patil" "Patin" "Pavia" "Pearson"
 "Pelak" "Peleg" "Pemberton" "Peng" "Perl" "Perschinka" "Petta" "Pezzuto" "Pickrell" "Pietschmann"
 "Pimenta" "Pinana" "Pitchford" "Porotto" "Prescott" "Pretorius" "Prieto" "Protsyuk" "Puerto"
 "Purcell" "Pécheur" "Qian" "Qiao" "Qiu" "ROH" "Raaben" "Rajendran" "Rajik" "Raman" "Ranciaro"
 "Rando" "Rayasam" "Rehder" "Renaud" "Resende" "Rhee" "Rhodes" "Ri" "Robinson" "Roche" "Rochow"
 "Rogers" "Rojek" "Rosa" "Rotbart" "Rozas" "Rudan" "Ryckmans" "Sadeghipour" "Sadler" "Sadozai"
 "Saeidi" "Sakthivel" "Salama" "Saleh" "Sall" "Sallovitz" "Salton" "Samad" "Santana" "Saraiva"
 "Sarhan" "Sartorelli" "Schiff" "Schmidt" "Schnell" "Schreiber" "Schrider" "Schrodinger" "Schwarz"
 "Seldin" "Seo" "Setoh" "Shaikh" "Shan" "Shedlock" "Shen" "Sheng" "Shintani" "Shou" "Shriner"
 "Silva" "Silvestre" "Simpson" "Siu" "Sloan" "Slovak" "Snell" "Souza" "Speshock" "Spiegel"
 "Spiegelman" "Stamatiou" "Staudinger" "Stefano" "Stein" "Stephens" "Stuart" "Suanarunsawat" "Suba"
 "Subramoney" "Sudmant" "Sueki" "Sullenger" "Suzuki" "Suárez" "Tajima" "Takaku" "Taratula"
 "Tataridis" "Teale" "Tempia" "Thapa" "Thi" "Thomas" "Thomsen" "Thomson" "Tian" "Timple" "Tomita"
 "Tramontano" "Treurnicht" "Troncarelli" "Tsetsarkin" "Turel" "Tuschl" "Usia" "Vaillant" "Variava"
 "Veesler" "Venter" "Versluys" "Vignuzzi" "Vu" "Waghmare" "Wagstaff" "Walaza" "Waldmann" "Warburg"
 "Watkins" "Webb" "Wertz" "Westbrook" "Wheeler" "Whitehead" "Widjaja" "Widman" "Wilms" "Wilson"
 "Wo" "Wolff" "Wolter" "Woodgett" "Wu" "Wyatt" "Wölfel" "Xia" "Xiao" "Xie" "Xiong" "Xu" "Xue"
 "Yanagawa" "Yang" "Yao" "Ye" "Yi" "Yoshiki" "Yoshizumi" "Yuen" "Zabner" "Zandvliet" "Zell" "Zeng"
 "Zhang" "Zhao" "Zheng" "Zhou" "Zhu" "Zolle" "Zou" "dU" "nIgG")))
    :test #'equalp))

;; 3590 defined as a bio-entity


(defparameter BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-7001-7100
    (remove-duplicates
      (append 
         (when (boundp 'BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-7001-7100) (symbol-value `BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-7001-7100))
         '(
("\"/C10" "#1" "#1-13-7490-G" "#115–035-044" "#14753" "#17853" "#2" "#2697T" "#29047" "#3" "#3950T"
 "#4" "#431143" "#44262×L" "#4814T" "#4970T" "#49851" "#5" "#6856T" "#83.1839.500" "#M0201S"
 "#MM-0165-P" "#NEL103E001EA" "$15" "$1900" "$3800" ") /7" ")/0.38" ")/0.48" ")/2" ")/AflII" ")/mL"
 ")/Tz" ")/μL" "**" "***" "++" "+++" "+0.02" "+0.03" "+10" "+1240~+1260nt" "+17.11" "+20.4" "+21.4"
 "+213~+233nt" "+221~+242nt" "+3" "+32" "+4" "+44" "+466~+486nt" "+6424T" "+7918" "+7~+27nt"
 "+863~+883nt" "+ξ" "-1,2-dihydro-3H-indol-3-ylidene" "-1,4,7,10-tetraazacyclododecane" "-1-"
 "-1-Cinnamoyl-4-" "-1-hydrazinecarbothioamide" "-1-receptor-associated" "-10-camphoryl"
 "-11-oxo-olean-12-en-30-oate" "-11-oxo-olean-12-en-30-oatehydrochloride"
 "-15,17-dimethoxybenzopyrano" "-16-methoxybenzopyrano" "-18-bromobenzopyrano"
 "-18-nitrobenzopyrano" "-1H-1,2,3-triazol-1-yl}-1-hydroxyethylphosphonate"
 "-1H-1,2,3-triazol-1-yl}-2-hydroxypropylphosphonate"
 "-1H-1,2,3-triazol-1-yl}acetamido-methylphosphonate" "-1H-1,2,3-triazol-1-yl}alkylphosphonates"
 "-1H-1,2,3-triazol-1-yl}butylphosphonate" "-1H-1,2,3-triazol-1-yl}ethoxy"
 "-1H-1,2,3-triazol-1-yl}ethoxy-methylphosphonate" "-1H-1,2,3-triazol-1-yl}ethylphosphonate"
 "-1H-1,2,3-triazol-1-yl}methylphosphonate" "-1H-1,2,3-triazol-1-yl}propylphosphonate"
 "-1H-pyrrole-3-carboxyl-ates" "-1H-pyrrole-3-carboxylate" "-1H-pyrrole-3-carboxylates"
 "-2,3-dihydroxypropyl" "-2-" "-2-hydroxyaniline" "-2-methyl-3-phenylacrylamide" "-2-methyl-5-"
 "-2-methylisoxazolidin-3-yl" "-2-pyridinecarboxylic" "-2-vinylquinazolin-4" "-2H-tetrazolium"
 "-3,4,5,4′-trans-tetramethoxy-stilbene" "-3,5-dihydroxy-4-oxo-4H-chromen-7-yl"
 "-3,5-dihydroxy-4H-chromen-4-one" "-3-" "-3-ethylcarbodiimide" "-3-phenylacrylamide"
 "-4,5-dihydro-1H-pyrrole-3-carboxylate" "-4-" "-4-hydroxycoumarin"
 "-4-oxo-3,4-dihydroquinazolin-2-yl" "-4H-chromen-4-one" "-5,7-dihydroxy-3-"
 "-5,7-dihydroxy-3-isopropoxy-4H-chromen-4-one" "-5,7-dihydroxy-3-methoxy-4H-chromen-4-one"
 "-5,7-dihydroxy-4-oxo-4H-chromen-3-yl" "-5,7-dihydroxy-4-oxo-4H-chromen-3-yloxy" "-5-"
 "-5-hydroxy-2-methyl-5-" "-5-methyl" "-5-pentyl" "-5-pentylchro" "-5-pentylchromone" "-7-" "-80°"
 "-AACCTGCCAAGTATGATGAC-3" "-aattcaaaaaggagcttctgctgattcaactaagcttagttgaatcagcagaagctcc-3"
 "-aattcaaaaagggcgttccaatcaacaccaaaagcttttggtgttgattggaacgccc-3"
 "-aattcaaaaagggtgactggcgggattgcgata-3" "-AATTGTCACCATAAGCAGCCA-3" "-ACGCAGAAAGCGTCTAGCCAT-3"
 "-agcttatcgcaatcccgccagtcacc-3" "-agcttgtccttaatgtcacagcgcc-3" "-amino-2" "-amino-modified"
 "-biotin-modified-21-nt" "-bis-" "-C-prM-E-NS1-NS2A-NS2B-NS3-NS4A-NS4B-NS5-3"
 "-CAATTCACTCGCTCCTA-3" "-CCTTGGCATGAGATGCAGGA-3" "-CGCCAGAGAGAAATTCGTGT-3" "-CH3-C=O" "-CH=N-"
 "-cyclohexyl-DTPA" "-deoxypyrimidine-modified" "-dioxol-5-yl-acrylic" "-fluoro-pyrimidine"
 "-GAAGATGGTGATGGGATTTC-3" "-GAAGGTGCTCCCTTACCGCCCGG-3"
 "-gataatggaccccaatcaaacaagcttgtttgattggggtccattatctttttg-3" "-GATTGATGGGATCGTTGCCTTA-3"
 "-GCGGCCGCTTTCTTTCTAAA-3" "-ggagcttctgctgattcaactaagcttagttgaatcagcagaagctcctttttg-3"
 "-GGGAATGGCGGGCCTCTTGGTTT-3" "-GGGAGTTGCTGTTGAAGT-3"
 "-gggcgttccaatcaacaccaaaagcttttggtgttgattggaacgccctttttg-3" "-ggtgactggcgggattgcgata-3"
 "-GTAGTCCTCCGGCCCCT-3" "-GTGGAAAGGCACATAACG-3" "-N-" "-N-phenyl-1-hydrazinecarbothioamide"
 "-non-translated" "-O-methyl" "-O-methyltransferase" "-O-MTase" "-pinene-containing"
 "-quinoline-3-carboxylic acid" "-receptor-associated" "-TAATGAGAATGGGGGAAGA-3"
 "-tatagaattctggcagacaacggtactatt-3" "-tataggtaccgtcacttactgtactagcaaagc-3"
 "-tataggtaccttatgcctgagttgaatcag-3" "-TCATTGACCTCAACTACATGGTTT-3" "-TCCTCAGTCACGATCAAGGAG-3"
 "-TCCTGGAGGCTGCACGACACTCA-3" "-TGAGATGTCCCGGATAGTGG-3" "-TGAGGCGGTTGTAGAAGAG-3"
 "-trans-caryophyllene" "-UA-3" "-UU-3" "-UUUA-3" "-UUUU-3" "-α-pinene" "-α-tocopherol"
 "-β-d-glucan" "-β-pinene" "-κB-mediated" "-κB-signaling pathway" "./msHOT" "0.0075~0.0214" "0.01×"
 "0.117g" "0.16/kg" "0.1×" "0.241g" "0.259x" "0.267x" "0.3μg/kg" "0.40-fold" "0.44/kg" "0.5H2O"
 "0.5~20.0" "0.61-fold" "0.9-fold" "0≤r≤r0" "0≤r≤r00" "0≤r≤r0β0" "0≤r≤rn0" "1+N+−−N−+N+"
 "1+N−+−N+−N−" "1,000~5,000" "1,1,3,3-tetraethoxypropane" "1,1-diphenyl-2-picrylhydrazyl"
 "1,2,3-triazole" "1,2,4-triazole" "1,2-diaza-1,3-diene" "1,3,8-trihydroxy-6-methylanthraquinone"
 "1,3-bis" "1,3-diaryl-2-propen-1-ones" "1,3-dihydroxy-2-propoxy" "1,3-Dioxo-1H-benzo"
 "1,3-dipolar" "1,4,7,10-tetraazacyclododecane-1,4,7,10-tetraacetic" "1,4,7,10-tetrakis"
 "1,4-dioxane" "1,4-triazole" "1,5-dimethyl-1H-indol-3-yl" "1,8-Cineole" "1,8-naphthalimic" "1-10#"
 "1-19#" "1-22#" "1-4}" "1-cyclopropyl-6-fluoro-4-oxo-7-" "1-ethyl-3-"
 "1-formyl-5-nitroisoquinoline" "1-methyl-1H-indol-3-yl" "1-methylpyrazole" "1-N-acyl" "1-nonene"
 "1-O-acylceramide" "1-thia-4-azaspiro" "1-undecene" "1.0 m/s" "1.0-fs" "1.0×10−3" "1.0×10−6"
 "1.18-fold" "1.2Uij" "1.4-fold" "1.5 m/s" "1.5-fold" "1.81-fold" "1.84-fold" "1/2/3" "1/20" "1/2b"
 "1/9" "1/IκB" "1/v" "1/γ" "1/κ" "10 h/session" "10,000×" "10-hydroxybenzopyran-7-yl" "10-times"
 "10/10" "10/15" "10/300" "10/331" "100,000/μL" "100/100" "100/200" "100/96" "100×" "101–106+AA"
 "101–106+AU" "101–106+UA" "101–106+UU" "102.9~103.7" "103.62/105.18" "103.69/105.25"
 "103.90/105.63" "104.80/106.32" "105/ml" "106.1 ± 7.6°" "106.1~106.8" "108/652" "109/813" "10a"
 "10a–10o" "10a–e" "10b" "10d" "10e" "10q11.2–10q21" "10°C" "10°C." "10×" "10μg/kg" "10μL"
 "11.5-fold" "11.6o" "11.7o" "11/12" "11/18" "11/204" "110°C" "111.1 ± 9.1°" "112.0 ± 5.7°"
 "116.33/116.67" "116.34/116.81" "11a" "11a–11d" "11a–11o" "11a–e" "11c" "11~20" "11≤μ≤15δμ−15"
 "11≤μ≤20" "12,000×" "12/155" "122bp" "123.61/123.63" "1240-1260nt" "1269nt" "127v" "12a" "12a–e"
 "12b" "12B7" "12c" "12~24" "12–107+4U" "13.5-fold" "13/114" "134.1 ± 4.0°" "135/133"
 "138.8 ± 6.4°" "13a" "13a–i" "13b" "13b–i" "13c" "13d" "13e" "13f" "13g" "13g–i" "13i" "13j" "13k"
 "14/331" "14/680" "147/186" "14a" "14a–i" "14a–i–17a–i" "14b" "14c" "14d" "14e" "14f" "14g" "14i"
 "15/137" "15/70" "15/813" "1500×" "150°C" "150–>250" "152.28/152.53" "152.29/152.53"
 "152.89/153.01" "157°C" "15a" "15a–i" "15b" "15c" "15d" "15e" "15f" "15g" "15i" "16,000×g" "16/"
 "16/144" "16/15" "16/4/1563" "16/600" "160.41/160.65" "163.96/164.03" "164.60/165.80"
 "164.64/166.03" "164.65/166.01" "164.76/164.93" "164.88/166.20" "166.84/169.21" "166.85/169.21"
 "166.87/169.31" "167.42/169.77" "16a–i" "16b" "16c" "16d" "16e" "16f" "16g" "16HBE14o" "16i"
 "16°C" "17/236" "17/28" "173/171" "177Lu" "177Lu-DOTA-PESIN" "17:30–19:00" "17a" "17a–i" "17b"
 "17c" "17d" "17e" "17f" "17g" "17i" "18.8°C" "18/15" "18/24" "18/60" "18/680" "180o" "189/187"
 "18a" "18b" "18α-GA" "18α-Glycyrrhetinic acid" "19/29" "19/47" "19/680" "1915×" "1957/H2N2"
 "1968/H3N2" "197/195" "198/196" "1988–2000bp" "199/197" "19b" "19c" "19d" "19e" "19g" "19p13"
 "1:1:1" "1:1→9:1" "1ab" "1A–C" "1a–c" "1a–i" "1c–h" "1EZ" "1f–g" "1GX6" "1IVD" "1KGP" "1LF3"
 "1Matrix" "1p36.11" "1{1-2}" "1{1}" "1~10" "1°" "1×" "1×104" "1×107" "1×10−6" "1×PBS" "1×reaction"
 "1–107+4U" "1–107+4U." "1″" "1−rr0" "1−rrn" "1−r−1rn−r0" "1≤μ≤5βμ−5" "2+" "2,2-azinobis"
 "2,2-diphenyl-1-picrylhydrazyl" "2,2’-azinobis" "2,3-Dioleoyloxy" "2,3-disubstitued"
 "2,4,6-mesityl" "2,4,6-trichloro" "2,4,6-trichlorophenyl" "2,4,6-trinitrobenzene"
 "2,4,6-tripyridyl-s-triazine" "2,4,6-trypyridyl-s-triazine" "2,4-alkadienals" "2,4-dichloro"
 "2,4-dichloro-5-ﬂuorophenyl" "2,4-Dichlorophenyl" "2,4-diF-C6H3-CH2" "2,4-difluorobenzyl"
 "2,4-Difluorobenzyl" "2,4-Difluorophenyl" "2,4-Dimethoxyphenyl" "2,6-diacetylpyridine"
 "2,6-Difluorophenyl" "2,6-dimethyloctane" "2,8-dioxabi" "2-3#" "2-5A" "2-acetyl-"
 "2-acetylpyrazine" "2-acetylpyridine" "2-alkenals" "2-aminobenzamide" "2-bromoanisole"
 "2-Bromobenzyl" "2-bromovinyl" "2-carboxyethyl" "2-Chlorobenzyl" "2-cyanobenzoate"
 "2-dimyristoyl-sn-glycero-3-phosphoethanolamine" "2-F-C6H4-CH2" "2-fluorobenzoate"
 "2-fluorobenzyl" "2-Fluorophenyl" "2-hydroxy-4-methoxybenzaldehyde" "2-hydroxybenzaldehyde"
 "2-hydroxyethoxy" "2-hydroxypropyl" "2-methoxybenzoate" "2-methyl-3-phenyl"
 "2-methyl-3-phenylacryloyl" "2-methyl-5-" "2-methylbenzyl" "2-nitrobenzyl" "2-nitrophenyl"
 "2-NO2-C6H4-CH2" "2-oxo-1,2-dihydro-3H-indol-3-ylidene" "2-Oxo-5-" "2-oxo-5-" "2-propenyl"
 "2-pyridyl" "2-pyridylmethyl" "2-vinyl-3H-quinazolin-4-one" "2-Vinyl-3H-quinazolin-4-ones"
 "2-vinyl-3H-quinazolin-4-ones" "2-vinyl-quinazolin-ones" "2-vinylquinazolinones" "2-ΔΔCT" "2.0Hz"
 "2.0×10−4" "2.17-fold" "2.2H2O}∞" "2.2×10−16" "2.42‒2.24" "2.4×10−3" "2.5-fold" "2.5×10−8"
 "2.7×10−3" "2/144" "2/3" "2/51" "2/610" "20,000×" "20/1" "20/20" "20/53" "20/680" "2000BB" "200×g"
 "201/680" "2011a" "2011b" "2013a" "2013b" "2014a" "2014b" "2016a" "2016b" "203/201" "204/668"
 "206/204" "208Tl" "209Bi" "20:1→1:1" "20b" "20f" "20×" "20×300" "21-25nt" "21/236" "21/52"
 "21/610" "21/c" "212Bi" "213-233nt" "213Bi" "213Bi-AMBA" "213Bi-DOTA-PESIN" "215/213" "216/214"
 "217/215" "21a" "21b" "21c" "21~40" "22/236" "221nt-242nt" "22°C" "23/236" "230/228" "230°C"
 "233/231" "239/237" "24-25cmH2O" "24/55" "24/680" "242.2Hz" "245/243" "247/245" "24–45×" "25 /min"
 "25-O-acetyl-7,8-didehydrocimigenol-3-O-β-D-xyloside"
 "25-O-acetylcycloartane-7-en-3-O-β-D-galactopyranoside" "25/680" "254/366" "254°C" "256/394"
 "259°C" "25D3" "25°C" "26,780/μL" "26/20" "260/280" "265°C" "27.2°C" "275°C" "27v" "28/30" "28/58"
 "28/680" "28622Twas" "29/299" "29/53" "293-6E" "293TT" "2:1:2:2:2" "2A1" "2Ac4Ph" "2ANL" "2Apro"
 "2A–C" "2a–c" "2A–D" "2a–e" "2B1g→2A1g" "2B1g→2A1g2" "2B1g→2B2g" "2B1g→2Eg" "2B2→2B1" "2B2→2E"
 "2Bi" "2Cl2" "2ClO4H2O" "2CO" "2d–e" "2Fo4Ph" "2G12" "2G12res" "2GEC" "2H-1-benzopyran-2-ones"
 "2JAB" "2j−1" "2M+Na" "2Multi-Mode" "2RLF" "2SO4" "2VBC" "2{1-2}" "2{1}" "2{2}" "2~3 fold" "2~4 h"
 "2·3H2O" "2·6H2O" "2×HBS" "2ξ+1" "2–3-fold" "2″-cyclic" "2−ΔΔCT" "2−△△T" "3,2-a:2"
 "3,3-dimethyl-1-hexene" "3,3’-(2-Nitrobenzylidene" "3,3’-(4-Chlorobenzylidene"
 "3,3’-(4-Methoxybenzylidene" "3,3′,4′,5,6-pentahydroxyflavone" "3,3′,5,5′-tetramethylbenzidine"
 "3,3′-(2,5-Dimethoxybenzylidene" "3,3′-(2-Methoxybenzylidene" "3,3′-(3,4-Dihydroxybenzylidene"
 "3,3′-(3-Bromobenzylidene" "3,3′-(4-Bromobenzylidene" "3,3′-(4-Dimethylaminobenzilidene"
 "3,3′-(4-Fluorobenzylidene" "3,3′-(4-Hydroxy-3-methoxy-5-nitrobenzylidene"
 "3,3′-(4-Methyltiobenzylidene" "3,3′-(4-Nitrobenzylidene" "3,3′-(4-Trifluoromethylbenzylidene"
 "3,3′-(Benzilidene" "3,4,5-trihydroxy" "3,4,5-trihydroxybenzoic" "3,4,5-Trihydroxybenzoic"
 "3,4,5-trimethoxycinnamic" "3,4,5-trimethoxyphenyl" "3,4-(methylenedioxy" "3,4-dichlorophenyl"
 "3,4-Dichlorophenyl" "3,4-dihydroxy" "3,4-dihydroxyphenyl" "3,4-dimethoxycinnamic"
 "3,4-Dimethoxyphenyl" "3,4-dimethoxyphenyl" "3,5-bis" "3,5-diacetamidobenzoic" "3,5-difluoro"
 "3,5-Difluorophenyl" "3-AcBAH" "3-Benzyl-2-vinylquinazolin-4"
 "3-benzyl-4-oxo-3,4-dihydroquinazolin-2-yl" "3-Bromobenzyl" "3-bromobenzylidene"
 "3-carboxymethoxy-phenyl" "3-chlorobenzoate" "3-chlorobenzyl" "3-Chlorobenzyl" "3-cyanobenzoate"
 "3-dimethylaminopropyl" "3-Ethyl-2-vinylquinazolin-4" "3-ethyl-4-oxo-3,4-dihydroquinazolin-2-yl"
 "3-ethylbenzothiazoline-6-sulfonate" "3-fluorobenzoate" "3-fluorobenzyl" "3-Fluorophenyl"
 "3-hydroxy-2-" "3-hydroxyethoxymethyl" "3-hydroxyguanidines" "3-methoxybenzoate"
 "3-methyl-2-vinyl-3H-quinazolin-4-one" "3-Methyl-2-vinylquinazolin-4"
 "3-methyl-4-oxo-3,4-dihydroquinazolin-2-yl" "3-methyl-oxiranyl" "3-methylbenzyl"
 "3-methylsulfinyl" "3-methyl­oxiranyl" "3-nitrobenzyl" "3.0×10−5" "3.0×10−8" "3.3-fold" "3.6-fold"
 "3.9×" "3/144" "30 m×0.32mm×0.25" "30:10:5" "30:10:7" "30α" "318/680" "3197.9930x" "31P-NMR"
 "326/537" "33/13" "333/331" "355/233" "36.5×" "360nt" "37/610" "37°" "37°C" "37°C." "381/379"
 "385/383" "388/386" "38°C" "39/100" "39/28" "39°C" "3`-Amino-modified" "3a-3u" "3AOX1" "3b-3d"
 "3BPF" "3C." "3c–e" "3D7-chloroquine" "3DEX" "3Ecto" "3f-3h" "3i-3l" "3i–k" "3L×3×2 h" "3MC"
 "3n-3q" "3p" "3p-C-DEPA" "3r-3u" "3T3-L1" "3Vpolyadenylated" "3{1-4}" "3{1}" "3°/min" "3·5H2O"
 "3×" "3β-hydroxy-11-oxo-olean-12-en-30-oate" "4,3-b" "4,5-dimethylthiazol-2-yl"
 "4,6-diamidino-2-phenylindole" "4-5-fold" "4-7-fold" "4-amino-3,5-dihydroxypentanoic"
 "4-amino-3-hydroxy-5-phenylpentanoic" "4-amino-3-hydroxynapthyl" "4-amino-5-hydroxypenta-2-enoic"
 "4-Bromo-2-fluorophenyl" "4-Bromobenzyl" "4-bromobenzylidene" "4-Bromophenyl"
 "4-Chloro-3-iodobenzotrifluoride" "4-chlorobenzoate" "4-Chlorobenzyl" "4-chlorophenyl"
 "4-Chlorophenyl" "4-cyanobenzoate" "4-dimethyl-amiopryidine" "4-Ethylphenyl" "4-F-C6H4-CH2"
 "4-fluorobenzoate" "4-fluorobenzyl" "4-Fluorophenyl" "4-hydroxy-alkenals" "4-hydroxybenzoyl"
 "4-hydroxybenzyl" "4-hydroxycoumarin" "4-hydroxysalicylaldehyde" "4-Iodophenyl"
 "4-isothiocyanatobenzyl" "4-methoxy-2-" "4-methoxybenzoate" "4-methoxychalcone" "4-methoxychalone"
 "4-Methoxyphenyl" "4-methylbenzyl" "4-methylchalcone" "4-metoxychalcone" "4-nitrobenzyl"
 "4-NO2-C6H4-CH2" "4-oxo-3,4-dihydroquinazolin-2-yl" "4-phenylthiosemicarbazone" "4-sulfophenyl"
 "4-trifluoromethylphenyl-" "4.0o" "4.4-fold" "4.5×10−3" "4.6-fold" "4/144" "4/15" "4/9" "40/1"
 "400×" "40×" "410nt" "416/414" "418/416" "422aa" "43/360" "430/428" "432/430" "440nt" "444/442"
 "448/446" "450/448" "45000×g" "450×" "451/449" "456/454" "460/458" "466nt-486nt" "478/476" "48d"
 "49/166" "499/854" "4Ac" "4a–4o" "4a–k" "4f145d106s26p3" "4G2" "4Hz" "4N-methylthiosemicarbazone"
 "4sig" "4{1,1}" "4{1,1}." "4{1-2" "4{1-4" "4~6" "4°C" "4°C." "4·" "4–6-week-old"
 "5-Amino-1,3-dioxo-1H-benzo" "5-aminonaphthyl" "5-bromo-1-methyl-1H-indol-3-yl"
 "5-bromoisatin-3-thiosemicabazones" "5-carbomethoxy" "5-chloro-1-methyl-1H-indol-3-yl"
 "5-Chloro-2-methylphenyl" "5-chlorosalicylaldehyde-Shiff" "5-formyl-2-furan"
 "5-formyl-2-furanylboronic" "5-isoquinolinyl" "5-methoxy-1-methyl-1H-indol-3-yl"
 "5-Nitro-1,3-dioxo-1H-benzo" "5-nitrocytidine" "5-nitroisatin-3-thiosemicabazones"
 "5-nitroisoquinolin-1-yl" "5-substituted-1,3-dioxo-1H-benzo" "5-sulfosalicylate"
 "5-trifluoromethoxyisatin" "5-Trifluoromethoxyisatin"
 "5-trifluoromethoxyisatin-3-thiosemicarbazones" "5.0×10−10" "5.6-fold" "5.6o" "5/5" "5/8" "50/1"
 "50°C" "51/678" "52/236" "52/280" "534/1111" "55/51" "55°C" "570/630" "5`UTR" "5E10" "5H2O"
 "5HVV-1" "5U51IP000155" "5V1M" "5Vcapped" "5{1,1}" "5{1,1}." "5{1-2" "5×" "6-18#"
 "6-amino-3-methoxyphenyl" "6-Bromo-1,3-dioxo-1H-benzo" "6-Diamidine-2"
 "6-diamidino-2-phenylindole" "6-Gingerolis"
 "6-hydroxy-2,5,7,8-tetramethylchroman-2-carboxylic acid" "6-maleimidocaproyloxy"
 "6-methoxyquinolin-8-ylamino" "6-Methoxyquinolin-8-ylamino" "6-Oxo-" "6-oxo-" "6.4×10−5"
 "6.7×10−3" "6/144" "6/204" "6/28" "6/6" "6/680" "60/85" "6000×" "600k" "60°C" "637-657nt"
 "64/2014" "642/1104" "666nt" "67,000×" "69/496" "6:4→9:1" "6A." "6A–C" "6D2Z" "6D30" "6D31" "6HB"
 "6p" "6s2" "6{1-4}" "6{1}" "6–8-week-old" "6–8-year-old" "6≤μ≤10λμ−10"
 "7,8-didehydro-24S-O-acetylhydroshengmanol-3-O-xyloside"
 "7,8-didehydro-24S-O-acetylhydroshengmanol-3-O-β-D-galactopyranoside"
 "7,8-didehydrocimigenol-3-O-β-D-galactopyranoside" "7-27nt" "7-amino-4-methyl"
 "7-amino-4-methylcoumarin" "7-Hydroxy-2-" "7-hydroxy-2-" "7-O-arylmethyl"
 "7-O-arylmethylquercetin" "7-O-arylmethylquercetins" "7-tri-O-benzylquercetin" "7/12" "7/14"
 "7/144" "7/20" "7/204" "7/25" "7/5" "7/8" "70-like" "70/2015" "70°C" "71/430" "72/189" "722/500"
 "72°C" "76/82" "79/147" "7:30–9:00" "7a–7s" "7a–k" "7c–e" "7i–k" "7{1,1,1}" "7{1,1,1}." "7{1-2"
 "7{1-32}" "7~8 fold" "7–8/11–12" "8-9cmH2O" "8/13" "8/144" "8/15" "8/204" "8/7" "80%~90%" "859nt"
 "85:15:0.05" "860nt" "863-883nt" "89–107+4U" "8a-e" "8cmH2O" "8HT" "8{1,1,1}" "8{1,1,1}." "8{1-2"
 "8°C." "8α+" "9,19-cycloartane" "9,19-cyclolanostane" "9/1" "9/144" "9/15" "9/22" "9/42" "9/9"
 "900×" "90°C" "93del" "94°C" "95%CI" "95°C" "95–100°C" "96®" "99.0/1.0" "99/556" "9a-e" "9AC"
 "9E10" "9HTEo" "9q34" "9{1,1,1}." "9{1,1,2}" "9{1,1,4}" "9{1,4,3}." "9{1-2" "9{2,1,3}" "9{2,1,3}."
 "9{2,4,1}" "9{2,4,1}," "9{2,4,3}" "9{2,4,3}," ":DNA:valP" "<$1900" "<0.01" "<0.05" "<1" "<10"
 "<10 µ" "<10%" "<18" "<2" "<2%" "<3" "<4" "<4.2%" "<5" "<6.25 µ" "<95%" "=167.25" "=2" "=3" "=CH2"
 "=Int" "=No" "=O" "=R−ξR−" "=S" "=Sall" "=Sall+" "=Ssurf+" "={αμ" "=β0"
 "=ℝξ⋯ℝ2ℝ1⇕R1R2⋯Rξ⋯Ri⋯RL−ξ+1⋯RL−1RL" "=∀k=17ℝF" ">1,000" ">1,400" ">1.1 µ" ">1.6" ">1.98" ">10.20"
 ">100 µ" ">100K" ">16" ">1Mb" ">1Å2" ">2" ">2.07" ">2.23" ">2.45" ">2.5 µ" ">2.51" ">20" ">25 µ"
 ">260" ">3.38" ">36%" ">4" ">4.96" ">5" ">5-fold" ">50%" ">500" ">6" ">64 µ" ">7" ">7.58" ">70"
 ">750" ">80%" ">85" ">90%" ">95%" "a chain-like" "a+b×Yt−1" "A-H1" "A-induced" "A-mediated"
 "A-particles" "A-type" "A/B" "A/H3N2" "A/J" "A175V" "A9-genolin" "AA+GA" "AAV1" "AAV2" "AAV5"
 "AAV6" "AAW30973.1" "Ab/Am" "Ab35958" "ABI3711" "ABTS+•" "AbXTL65" "AbXTL68" "acattaaggaca-3"
 "Acc=0" "Acc=0.5" "Acc=1" "acetone/dmso" "acid/aptamers" "AcOEt/CH2Cl2"
 "acrylamide:bis-acrylamide" "active-caspase-3" "active-caspase-8" "activities20,21."
 "adhesion molecule-3-grabbing" "ADV-like" "ADVAX™" "AF555" "Ag+" "AG/GG" "Ag10Ns" "AG129" "AG5"
 "Ag50Ns" "Ag800Ns" "agarose/growth" "agctttagcaaagcaatattgtcgtttttttg-3" "aggaca-3" "AgNO3"
 "Ahn-Yoon" "aids_hiv_program_sp-01a" "air/surface" "AirChek®" "Aix-Marseille" "AKT/endothelial"
 "Al-Gabel" "Al-Garbi" "Ala218Thr" "Ala258Ser" "AlaA33" "aldehydes/ketones" "alkaloid/imide"
 "allergen/antigen" "ALN-RSV01" "AM-300" "Amicon®" "amino acids/peptides" "AN58"
 "Ananthraquinone-containing" "andγ" "annexin V-FITC+" "Annexin V-FITC+" "Annexin V-FITC-"
 "Annexin-V/propidium" "anti-ageing" "anti-aging" "anti-allergic" "anti-allergy"
 "anti-angiogenesis" "anti-apoptotic" "anti-asthmatic" "anti-bacterial" "anti-bYEL1" "anti-C-Cas3"
 "anti-canine" "anti-carcinogenic" "anti-chicken" "anti-complement" "anti-convulsant"
 "anti-disposed" "anti-DNA" "anti-E." "anti-enteroviral" "anti-feline" "anti-Feline"
 "anti-ferromagnetically" "anti-fibrotic" "anti-FIPV" "anti-free" "anti-fungal" "anti-H. pylori"
 "anti-Helicobacter pylori" "anti-His" "anti-HIV1" "anti-human" "anti-hyperlipidemic"
 "anti-hypertensive" "anti-IAV" "anti-immunity" "anti-inflamatory" "anti-inflammation"
 "anti-inflammatiry" "anti-inflammatory" "anti-influenza A virus" "anti-influenza virus"
 "anti-invasive" "anti-inﬂuenza" "anti-L." "anti-leishmanial" "anti-leshmanial" "anti-lipid"
 "anti-mAG5" "anti-malarial" "anti-mentic" "anti-metastasis" "anti-microbial" "anti-mouse"
 "anti-mutagenic" "Anti-Myc" "anti-mycobacterial" "anti-Mycoplasma" "anti-mYEL1" "anti-N"
 "Anti-NDV" "anti-oedema" "anti-oxidants" "anti-oxidative" "anti-p-65" "anti-p-IKKα/β" "anti-P."
 "anti-parasital" "anti-parasite" "anti-parasitic" "anti-phlebotomine" "anti-picornaviral"
 "anti-PiCV" "anti-pigeon" "anti-PM2.5" "anti-pollution" "anti-porcine" "Anti-pressure"
 "anti-proliferation" "anti-proliferative" "anti-rabbit" "anti-radical" "anti-recombinant"
 "anti-retroviral" "anti-rSP03B" "anti-SGH" "anti-trypanosomal" "anti-tubercular" "anti-tumor"
 "anti-tumorigenic" "anti-tumour" "anti-ulcer" "anti-viral" "anti-Visna/Maedi" "anti-VP136"
 "anti-VP19" "anti-VP72" "anti-VP86" "antibiotic/antimycotic" "antibody-like"
 "antibody/combination" "antigen presentation/recognition" "anti‑neoplastic" "anti‑oxidant" "AP30"
 "April–June" "apta-beacon-coupled" "Aragón-Sánchez" "area/volume" "Arikace®" "ArkDPI11"
 "article/author" "article/million" "Asia1,2" "AspA138" "assays38–42" "Astier-Gi’s" "ATCC#"
 "ATCC19115" "ATCC49954" "attrition/retention" "Au10Ns" "authors/article" "AV42623" "avb3" "avian7"
 "AX-Tobra™" "AY274119" "AY278487" "AY278491" "AY283797" "AY297028" "AY338174" "AY345986"
 "AY350750" "AY394978" "AY394979" "AY394987" "AY394988" "AY394998.1" "AY395002.1" "AY463059"
 "AY463060" "AY512430.1" "AY599834" "AY95003" "Aθ-2θ" "A—acetonitrile" "B.P." "B/" "Bantu-speaking"
 "Baram-Pinto" "BAY11-7082" "BCIP/NBT" "bcl2fastq" "bD7" "be/webtools/Venn/" "BE88/14" "BEAS2-B"
 "beats/min" "BECN-1" "BEH819015" "BeH81915" "Bei-Mu" "beneficial/toxic" "Benjamini-Hochberg"
 "benzopyran-7-yl" "benzoyl-norleucine-lysine-arginine-arginine-7-amino-4-methyl"
 "benzoyl-norleucine-lysine-arginine-arginine-7-amino-4-methylcoumarin" "benzylidene-bis-"
 "Betaferon®" "BF157/08" "BF3Et2O" "Bfl-1/A1" "bi-chlorodibenzo" "Bi12O8" "Bi2Cl10" "Bi38O44"
 "Bi6O4" "Bi9O7" "BiCl3" "BiCl6" "BiF5" "BiHSal3" "BiL3" "BiL3·" "binding/inactivation"
 "BiNFeC-hTF" "Bio-Medicus" "Bio-pharm" "Bio-Plex" "Bio-Rad" "biodistribution/accumulation"
 "biotin-streptavidin" "BiPh3" "BiPh3/GA" "BiPh3/NF" "bipy-2,2-bipyridine" "bis-benzylisoquinoline"
 "bis-trimethylsilyltrifluoroacetamide" "BiV/BiIII" "Bi{C5H4NC" "Bi{R1C" "BJ02" "BLAST-Algorithmus"
 "BM-MSCs" "BMS-378806" "BMS-433771" "Bn-H-2" "Bn-H-3" "Bn-H-4" "Bn-H-5" "Bn-H-6" "Boc2O"
 "BP-caKII" "bPAR25" "BSL-2" "BX41" "bYEL1" "B|" "C*" "C*–C1" "C*–C3" "C++" "C-10a" "C-4a" "C-8a"
 "C-9a" "C-H···O" "C-lobe" "C-N=CH" "C10/C10" "C12=O" "C12H12N2O" "C15H10N2O2" "C15H8N2O4"
 "C16H10BrF3N4O2S" "C16H10ClF3N4O2S" "C16H10F3IN4O2S" "C16H10F4N4O2S" "C16H11F3N4O2S" "C16H22N3O5P"
 "C16H8Cl3F3N4O2S" "C16H9BrF4N4O2S" "C16H9Cl2F3N4O2S" "C16H9F5N4O2S" "C17H10F6N4O2S"
 "C17H10F6N4O3S" "C17H12ClF3N4O2S" "C17H12F2N2O" "C17H13FN2O" "C17H13N3O3" "C17H14N2O" "C17H17NO4"
 "C17H18CuNO9Cl" "C17H20CuN2O9" "C17H22O4" "C17H23O4" "C17H24N3O5P" "C18H15F3N4O2S" "C18H15F3N4O4S"
 "C18H26N3O5P" "C19H19CuNO6" "C1=O" "C20:4" "C20:5" "C20H20BrN4O5P" "C20H20N5O7P" "C20H21N4O5P"
 "C20H22N5O5P" "C21H22BrN4O5P" "C21H22BrN4O6P" "C21H22N4O7P" "C21H22N5O8P" "C21H23N4O5P"
 "C21H23N4O6P" "C21H24N5O5P" "C21H24N5O6P" "C22:6" "C22H23BrN5O6P" "C22H23N6O8P" "C22H24BrN4O5P"
 "C22H24BrN4O6P" "C22H24N5O6P" "C22H24N5O7P" "C22H24N5O8P" "C22H25N4O5P" "C22H25N4O6P"
 "C22H25N6O6P" "C22H26N5O5P" "C22H26N5O6P" "C23H26BrN4O5P" "C23H26BrN4O6P" "C23H26F2N3O5P"
 "C23H26N5O7P" "C23H26N5O8P" "C23H27FN3O5P" "C23H27N4O5P" "C23H27N4O6P" "C23H27N4O7P" "C23H28N3O5P"
 "C23H28N5O5P" "C23H28N5O6P" "C24H26ClN3O2" "C24H26FN3O2" "C24H27N3O2" "C25H13O6Br" "C25H13O8N"
 "C25H15O6Br" "C25H15O6Cl" "C25H15O8N" "C25H16O8N" "C25H26F3N3O2" "C25H27N3O4" "C25H28ClN5O3"
 "C25H28FN5O3" "C25H29N3O2" "C25H29N3O3" "C25H29N5O3" "C26H15O6F3" "C26H16O7" "C26H17O10N"
 "C26H18O7" "C26H25F6N3O2" "C26H28F3N5O3" "C26H29N5O5" "C26H31N3O4" "C26H31N5O3" "C26H31N5O4"
 "C27H18O8" "C27H20O8" "C27H21O6N" "C27H27F6N5O3" "C27H33N3O5" "C27H33N5O5" "C27H34O9" "C27H35O9"
 "C28H35N5O6" "C28H36O9" "C28H37O9" "C2a/C2b" "C2b" "C3-H" "C3-rutinose" "C3/C3" "C32H32Br2N4O5"
 "C32H32Cl2N4O5" "C32H34N4O5" "C34-Chol" "C34H32CuN2O8" "C34H38N4O5" "C34H38N4O7"
 "C34H40Cu2N2O12Cl2" "C36H55O9" "C36H56O10" "C36H56O10Na" "C38-PAC-2A-Rluc-2A-E30" "C38H57O10"
 "C38H58O11" "C38H58O11Na" "C38H59O11" "C38H60O12" "C4-N5-C6-C7" "C40H54O6" "C41H56O6" "C41H56O7"
 "C42H58O7" "C45H64ClNO7S" "C45H64ClNO7Se" "C46H66ClNO7S" "C46H66ClNO7Se" "C46H66ClNO8S"
 "C46H66ClNO8Se" "C47H68ClNO8S" "C47H68ClNO8Se" "C4a/C4b" "C4bC2a" "C50H71NO9S" "C50H71NO9Se"
 "C51H73NO10S" "C51H73NO10Se" "C51H73NO9S" "C51H73NO9Se" "C52H75NO10S" "C52H75NO10Se" "C5A" "C6/36"
 "C68H66Cl2Cu2N4O26S2" "C6H4" "C6H5-CH2" "C6H5}3" "C7=O" "C8/C8" "C9/C9" "C=C" "C=N" "C=O" "C=S"
 "ca.1600" "CaCl2" "CaH2" "calcium-STAT" "calcium/JNK" "Calmette-Guérin" "calnexin-like" "CaMKKβ"
 "CaMKKβ-AMPK-mTOR" "cancer/tackling" "capase-3-dependent" "capsule/tablet" "CAR4/7"
 "carbobenzoxy-L-leucyl-L-leucyl-L-leucinal" "carbohydrate-lectin" "carbohydrate-protein"
 "Carbopol®" "cardiomyopathy/death" "cash/voucher" "Casorla-Pérez" "CaspaLux8-L1D2"
 "CaspaLux9-M1D2" "caspas-8" "CC50" "CC50/EC50" "CCACGAGATCAAGGACAGCGGCC-TAMRA" "CCGGTTCCGCAGA-3"
 "CCID50" "CCL-23" "CCL-34" "CCL-81" "CCl3F" "CCl4-induced" "CCL81" "CD11b+" "CD133+" "CD172a+"
 "CD2Cl2" "CD3+" "CD4+/CD8+ T cell" "CD4+CD25+FoxP3+" "CD4+CD8α+" "CD4-CD8α-" "CD4bs" "CD8low+"
 "CD8α" "CD8α+" "CDK+PM6" "cell-like" "cell/mL" "cells/dish" "cells/ml" "cells/mL" "cells/ODof"
 "cells/well" "centroid-to-centroid" "CF3CO2H" "cfH2" "CFT1-LCFSN" "cfu/mL" "CFU/mL" "CFX96"
 "CFX96-C1000" "cf·HCl" "cgcaatcccgccagtcaccctttttg-3" "CH2CH2OCH2CH2" "CH2CH3" "CH2Cl2"
 "CH2Cl2/CH3OH" "CH2Cl2/EtOH" "CH2Cl2/MeOH" "CH2Cl2:/MeOH" "CH2N" "CH2NHC" "CH2OP" "CH3CH2"
 "CH3CH2OH" "CH3CH2OP" "CH3CN-H2O" "CH3CN/H2O" "CH3CO2H" "CH3COOH" "CH3N" "CH3O" "CH3OH" "CH=CH2"
 "CH=N" "CHAC1-V5eGFP" "CHCl3" "CHCl3-MeOH" "CHCl3/MeOH" "chemistry/electrolyte" "chitinase-like"
 "chloroform/methanol" "CHNS-9320" "chr11"
 "chr13_data_from_Canary_Islanders_MBE-Guillen-Guio-et-al"
 "chr3_data_from_Canary_Islanders_MBE-Guillen-Guio-et-al" "Chávez-Bueno" "Cid14" "cis-11d"
 "cis-11e" "cis-11f" "cis-11i" "cis-11k" "cis/trans" "citations/article" "cities26–28" "CL-2TM"
 "classical/alternative" "CLD-N-terminus" "Clevenger-type" "ClO4" "ClO4·H2O" "Clone69TRevEnv"
 "Clopper-Pearson" "cm3/mol" "cmH2O" "CMUH104-REC2–115" "cn/iPPBS-Opt" "CNS769_Laos_2009" "co-"
 "co-adjuvants" "co-administered" "co-complexes" "co-crystal" "co-cultivation" "co-delivery"
 "co-exposition" "co-infected" "co-infection" "co-morbidity/mortality" "co-payment" "co-populate"
 "co-prescribed" "co-segregation" "co-stimulatory" "co-transfected" "co-transfecting"
 "co-transfection" "co-workers" "coiled-coil" "cold-bi" "collagen-like" "college/"
 "colony forming units/mL" "COM+" "com/" "com/danjlawson/badMIXTURE" "com/rnaiexpress"
 "complications13,14;" "con1" "condensation/fragmentation" "control/s" "COOCH3" "copies/cells"
 "copy/paste" "correcting/compensating" "Cos-1" "cPLA2δ" "Crandell-Rees" "CRISPR/Cas9"
 "ctgattaggtcttggtccc-3" "ctgtctgataatggaccccaat-3" "CTL/Th1" "Cu1" "Cu2" "Cu2+" "CuCl2·2H2O"
 "CuCl2∙2H2O" "CUHK-AG01" "CuKα" "CuO-nanoparticles" "CuSO4" "CuSO4·5H2O" "CV777" "CVB1"
 "CVB1–CVB5" "CVB2" "CVB3" "CVB4" "CVB4-infected" "Cwh41p" "cyclohexane/EtOAc/MeOH" "CYP-3A4"
 "cysteine-rich domain" "Cα" "Cβ" "C–Br" "C−H···O" "C−H···π" "D-galacose" "d-mannopyranoside"
 "D.-C7C" "D/P" "D1320/1709A" "D1320A/D1709A" "D14E12" "D1D3" "D2O" "D30A" "D=−1.511" "D=−1.733"
 "D=−2.505" "daily/once" "daily/two" "dampness-bi" "DAS181" "data_request" "DC-SIGN+"
 "DC/macrophages" "DCM/Ethyl acetate" "De-Nol" "death7–9" "dec-RRLL-CMK" "decan-4-yl"
 "delta-13-prostaglandin" "delta-rAd" "DENV4" "deposit@ccdc" "desorption/ionization" "DF/V" "DFTB3"
 "DFTB3/3OB" "DH5α" "DHIS2" "dialysate-to-plasma" "diameter33" "dichloromethane/methanol"
 "Diels-Alder" "difference/Ct" "Digest-Eur" "Ding-Chuan-Tang" "dioxo-5-yl" "discovery/development"
 "disease/gastroenteritis" "disease/viral" "dmDicer-2" "DMEM/F12" "DMPE/Chol" "DMPE/DCP" "DMSO­-d6"
 "dn/dc" "DN59" "DNA-CaCl2" "DNA-damaging-agent-induced" "DNA17" "DNA2PRO" "DNA:valP" "DNApac-A"
 "DNApac-B" "DNAX-activating protein" "DNeasy®" "DO3A-CH2CO-8-aminooctanoyl-Q-W-A-V-G-H-L-M-NH2"
 "DP7" "DPPH/TLC" "DPX400" "Drosha/DCGR8" "drug-like" "dug-like" "DV4-F" "DV4-R" "dx2−y2"
 "Dylight®" "E-configurations" "E-isomer" "E.Z.N.A.®" "E/Z" "E1-E2" "E1/E2" "E1/E3" "E1E2" "E5–E20"
 "E:M" "EC50" "ECIL-4" "EcoRI/KpnI" "EcoRI/NotI" "ED45" "ED50" "EDEM1/3" "Ef-Tu" "effects/toxicity"
 "EID50" "EID50/100 µ" "EID50/mL" "eIF4E protein" "eIF4E-dependent" "eIF4E-S209A" "eIF4E."
 "El-Ghorab" "Eldar-Finkelman" "EmGFP-amiRNA" "EmGFP-miR" "encourage/" "Engerix®" "enhancer/"
 "Enshell-Seijffers" "Epaxal®" "epoxypseudoisoeugenol-2-methylbutyrate" "ERGIC-53CRD"
 "erosion/loss" "Ery5" "es/en" "et al.13" "Et2O" "Et3N" "ether/" "ether/EtOAc" "ether/EtOAc/MeOH"
 "ether/petrolether" "ether/petroleum" "ethical/IRB" "ethyl acetate/5%" "ethyl acetate/cyclohexane"
 "ethyl acetate/petroleum" "ethyl-4-aminobenzoate" "EtOAc/ether" "EtOAc/H2O" "EtOAc/Hex"
 "EtOAc/hexanes" "EtOAc/MeOH" "EtOAc/petroleum" "eukaryotic/viral" "EWI-2wint" "Excellair™"
 "exo-α-mannosidases" "F-distribution" "F/HN" "F23del" "F2···F2i" "F508del" "F508del/W1282X"
 "F5Tg83" "falcipain-2" "Fc-region" "fCD8" "FcεRI" "Fe2+-TPTZ" "Fe3+" "Fe3+-TPTZ"
 "Fe3+/ferricyanide" "Fe3O4" "Fe4" "FeCl3" "FEV1" "FFU/mL" "fg/mL" "fibrinogen-like"
 "ficoll-hystopaque–density" "Fig.1b" "FiO2" "FITC/PI" "FIV-Z2" "FJWT" "FL-74" "flu-like"
 "Fluidosomes®" "fluoridated/non" "Fmoc-OSu" "formyl-5-nitroisoquinoline" "forward/side"
 "four-grade-scoring" "FP635" "FP635-expressing" "Friedel-Crafts" "FSS13025" "FTIR-8400" "Fuzeon™"
 "F···F" "G-MEM" "g/" "g/1" "g/kg/d" "g/L" "g/liter" "g/ml" "g/mol" "G0/G1" "G1/G2" "G1/S phase"
 "G2/S phase" "G64S." "GAH2" "galectin-like" "galGal4" "galGal5" "García-Villarreal" "Gaussian09"
 "gb|AF033819.3|" "GC/EIMS" "gcttgtttgattggggtccattatc-3" "Generation/Discovery" "GEO2R" "GF254"
 "GG/AG" "GH31" "Gi3" "Gibco/BRL" "GIBCO®/Invitrogen" "Giemsa-stained" "Glc-α1,2-Glc"
 "Glc-α1,2-Glc-α1,3-Glc" "Glc-α1,3-Glc" "Glc-α1,3-Man" "Glc-α1,3-Man-α1,2-Man-α1,2-Man"
 "Glc3Man9GlcNAc2" "globally1" "GLOS2009Day1" "Glu119:OE2" "Gly-Xaa-Yaa" "GlyB147" "glycol-bis"
 "gov/index" "gov/variation/tools/1000genomes/" "gp64" "GQ385303" "graft-vs.-" "GRCh37" "GS115"
 "GSK2656157/PERK" "GTTTAG-3" "Gua-Lou-" "Guillain-Barré" "gun011" "GZ-B" "GZ-C" "GZ01" "g⊥" "H&E"
 "H*" "H+L" "H-6/H3-21" "H-7/H3-20" "H.E.J." "H/D" "H1N2" "H2-14/H2-15" "H2-17/H3-18"
 "H208Q-Usb1–UUUA" "H208Q-Usb1–UUUU" "H2Ac4Ph" "H2AcPh" "H2AcpNO2Ph" "H2Fo4Ph" "H2L" "H2L2S" "H2N2"
 "H2O" "H2Sal" "H2SO4" "H3-20/H3-21" "H3-28/H2-27" "H3-H4α" "H3-H4β" "H37Rv" "H3Ssal" "H4α-H5"
 "H4α-P" "H4α–H3" "H4α–H4β" "H4β-H5" "H4β-P" "H4β–H3" "H4β–H4α" "H5-H8" "H5/H5" "H5–H4α" "H5–H4β"
 "H6/H6" "H7/H7" "H7N2" "H7N4" "H7N7" "H7N9" "H8/H8" "H9N2" "h_index" "HA-DEST" "HA/receptor" "HA0"
 "HAcpNO2Ph" "Harbin04B" "Harbin17A" "Harbin17B" "Hardy-Weinberg" "HB-112" "HBTS" "hCAR:hDAF-Fc"
 "hCD4" "hCMEC/D3" "HCV-AB6865" "HCV-Trimera" "HC≡CCH2" "HDAd5-CFTR" "heat-bi" "HEK-293-EBNA1-6E"
 "HEK293-EBNA1" "HeLa/IC50" "Hemominas-Hemonúcleo" "HepG2/ADM" "heptyl-7-hydroxy" "herba-alba"
 "HEV71" "hg19" "Hg2Cl2" "HHA/GNA" "His3p" "HIV-1goes" "HIV1-IN" "HKU-39849" "hlyA-B3" "hlyA-FIP"
 "hlyA-LB" "hlyA-LF" "HMGB1A" "homo-octamer" "hospitals/" "host-vs.-" "hotels/guesthouses" "HO°"
 "HO•" "HP-5MS" "HPV-16" "hPyV‐WU" "Hs_00225520" "Hs_00234140" "Hs_174103" "Hs_2786624" "Hs_985639"
 "HSV-ICP8" "Ht=1" "Htm1p" "Htm1p-Pdi1p" "http://analysis" "http://anewmerckreviewed"
 "http://bioinformatics" "http://broadinstitute" "http://clinicaltrials" "http://cran"
 "http://hapmap" "http://home" "http://nodexl" "http://rnaidesigner" "http://sourceforge"
 "http://teidehpc" "http://www" "https://data" "https://genome-euro" "https://github"
 "https://gtexportal" "https://imagej" "https://www" "Huh7" "Hut/CCR5" "HxT/S" "Hy-Line" "Hy-line"
 "Hypersil-ODS" "hypoxanthine/xanthine oxidase" "HZS2-FB" "HαC4" "HβC4" "i-STAT®" "i.e.,3a"
 "I1167del" "I1839del" "I:C" "i=1" "i=110Sall" "Ibaraki" "IBV-Gray" "IC90" "ICP8"
 "identification/syndrome" "ID||" "IFI27L2" "IFI27L2-H03" "IFN-α/β" "IFN-λ3" "IFNAR-/-" "IFNα/β"
 "IFRD1_H01" "Ig-like" "IgG-Fc" "IgG1κ" "IgM+" "IgY+" "IgY-secreting" "IHR-2005" "III+" "IKKα/β"
 "IL-17A+" "IL-1bβ" "IL-22+" "IL-36α" "Illkirch-Graffenstaden" "imidazole-4,5-dicarboxamides"
 "imidazole-4,5-dicarboxylic" "immediate/early" "INCB009471" "indol-3-yl" "infection/replication"
 "infections/AIDS" "infections36" "inflammatory/immune responses" "INFLEXAL®" "influenza A virus2"
 "influenza-like" "INFβ" "insulin-like" "int/csr/en/" "inter-MASP" "intervention/prevention"
 "into/onto" "intpDHIS2" "io/picard" "ionization–time-of-flight" "IOZ20160047" "iPPBS-Opt" "iQ5"
 "IRF3/7" "ISA71" "ischemia/reperfusion" "ISG15-/-" "isoquinolin-2" "isoxazolidin-3-yl" "ITS1–ITS4"
 "ITX4520" "ITX5061" "ITZ+KI" "IU/mL" "IX70" "IκBa" "J399EM" "J774" "J774A" "J99" "j=1" "J=8.1"
 "JascoV-670" "Jc1" "JEM-1400" "Jensen-Jarolim" "JEV3" "JFH1" "Jie-Geng" "Jin-Tang" "JQ301891"
 "Juliá-Serdá" "JVE-WNV" "JX131374" "j×si" "j−1×pwi" "j∼Poisson" "K-fold" "K.Y." "K1/2"
 "K2-infected" "K2CO3" "K562/A02" "K562/adriamycin" "k=1" "KAPA-Biosystems" "Kaplan-Meier"
 "kappa-light-chain-enhancer" "Karl-Fischer" "kb/SNP" "KC196115.1" "kcal/kg" "kcal/mol" "kcat/Km"
 "Kernow-C1" "KF297916" "KF738860.1" "Klerksdorp‐Tshepong" "KM+" "km2" "KM91" "KM91-like"
 "Kolmogorov-Smirnoff" "KQ6" "Kruskal-Wallis" "Kruskall-Wallis" "Kt/V" "KT164776" "KT316240"
 "KT316241" "KT316242" "KT316243" "KT316244" "KT316245" "KT316249" "KT316250" "KT316251" "KT316252"
 "KT316253" "KT316254" "KT316256" "KT316257" "KT316258" "KT316259" "KT316260" "KT316278" "KT316279"
 "KT323979.1" "KUL0+" "KUL01+" "KwaZulu‐Natal" "K⊥" "L-configuration" "L-FCN" "L-ficolinlevels"
 "L-lactide-co-glycolic acid" "l-lactide-co-Glycolide" "L-nucleosides" "L-selectin/CD62" "L/"
 "L/chick" "L/h" "L/min" "L/well" "L1" "L2S" "L3" "LA-118" "lab-in-a-tube" "LaB6"
 "lactic-co-glycolic acid" "Lambkin-Williams" "LAS4000" "LC50" "LD174" "LD196" "LD201t1" "LD50"
 "lead-like" "lectin-like" "lectin/mannose" "lectins/Siglecs" "Legalon-SIL" "Legalon®" "Leningrad"
 "let-7a-1" "let-7b" "let-7c" "Levenberg—Marquardt" "LF2000" "Liebermann-Burchard"
 "ligand-receptor" "ligand/receptor" "LINC00355" "Lineweaver–Burk" "lipohilicity/hydrophilicity"
 "Lipoquin™" "LJ001" "LJM11" "LJM17" "Lloyd-Smith" "Lobo-Cabrera" "log10" "Loopamp®" "low-pH"
 "lowest-observed-adverse-effect" "LPS+flagellin" "LPS/D-GalN" "LS-Rg" "Lsm2–8" "LSM510" "LSUI2"
 "LTβR+/+" "LTβR−/−" "lum/m²" "Lund-Johansen" "Lunenfeld-Tanenbaum" "Luria-Bertani"
 "lymphocytopenia/neutropenia" "lymphocytpenia/neutropenia" "L×L" "m /z" "M+" "M+Na" "M-2H2O+H"
 "M-H2O+H" "M-H2O+Na" "M.p" "M.Sc" "M.wt" "M/mL" "m/V" "m/v" "m/z" "M2-like" "M5e" "M8B"
 "Ma-Xing-Gan-Shi-Tang" "Maca-Meyer" "Macherey-Nagel" "macrophage-like" "macrophage/neutrophil"
 "macrophages/monocytes" "Madin-Darby" "Madurahydroxylactone-derived" "mAG5" "Mai-Men-Dong"
 "Maldi-Biotyper" "Man-8" "Man-8/9" "Man-9" "Man-D1" "Man-D2" "Man-D3" "Man-Whitney" "Man-α1,2-Man"
 "Man-α1,2-Man-α1,2-Man" "Man-α1,6-Man-α1,6-Man" "Man8GlcNAc2" "Man9GlcNAc2" "Mann-Whitney" "Manα"
 "Marcelino-Rodríguez" "mass/volume" "MBC/MFC’s" "MBC=" "MCC=0" "MCC=1" "MCC=−1" "MCF-7/ADR"
 "MDEC-22—molecular" "MDEO-12" "mdx/utrn-/−" "Me2CO" "meanμt=" "MEDI-524" "MeOH/H2O" "MeSO3H"
 "Metallomic/metalloproteomic" "MetaSUB18" "Methyl-4-iodosalycilate"
 "methylether-methacrylate-ethyleneglycol" "Mexico15" "mg/100 µ" "mg/day" "mg/dL" "mg/kg" "mg/kg/d"
 "mg/kg/day" "mg/kg/dose" "mg/L" "mg/ml" "mg/mL" "mg·L−1" "MHC/peptide" "MI-60" "Michaelis-Menten"
 "Michaelis–Menten" "micro-dystrophin" "micro/molecular" "microbioma/virioma" "microbiome/virome"
 "mid-1990s" "MIL2" "milk/powdered" "min/5" "Ming-Xue" "miR-125b" "miR-199a-5p" "miR-221-5p"
 "miR-221-5p-binding" "miR-221-5p-mediated" "miR-221-5p-specific" "miR-221-5p-transfected"
 "miR-26a" "miR-302c" "miR-34a" "miRNA-5p" "mL/g" "ml/kg" "mL/kg" "mL/kg/min" "mL/min" "mmol/L."
 "MNK1/2" "Mns1p" "mobile/personal" "model:Yijk" "MoKα" "mol/L" "Molinos-Quintana" "mono-"
 "mono-deprotonated" "mono-negative" "mono-O-methyl" "mono-PEGylated" "monocyte/macrophage"
 "monocytes/macrophages" "MOPAC2009" "mosGCTL-1" "mosGCTL-virus" "mosPTP-1" "MOTIF1" "MOTIF2"
 "mPAR25" "MPGCPCPGCG-NH2" "Mpn1" "MR766" "Muller-Pebody" "multi-fold" "multivalent-protein"
 "mYEL1" "mYEL2" "M·min−1" "N+" "N-acetylmannosamine" "N-alkylsilyl" "N-Boc-l-selenomethionine"
 "N-CH2a" "N-CH2b" "N-cinnamoyl" "N-diethylaniline" "n-dodecyl-β-d-maltoside" "N-lobe"
 "N-methyl-2-pyrrolidone" "N-methyl-C-" "N-methyl-C-diethoxyphosphorylnitrone"
 "N-methyl-D-aspartate" "N-methylhydrazine" "N-methylindole" "N-methylindoles" "N-Phenyl-2-"
 "N-phenylbenzamide" "N-propargyl" "N-silylimine" "N-trialkylsilyl" "N-vinyl-2-pyrrolidone"
 "N1-N8-bis" "N1-substituted" "N2-C3-C4-N5" "N2-H" "N2S" "N3-substituted" "N3:5" "N3S2" "N4-aryl"
 "N4-H" "N5-C6-C7-N8" "N5-H" "N5:5" "Na2CO3" "Na2SO4" "NaBH4" "NaCl/KCl" "NaClO4" "Nanodrop1000"
 "nanomolar-picomolar" "NaVO4" "NCT00299897" "NCT01018615" "NCTC11637" "ND-1000" "NE2H120"
 "NE2H208-HE2H208-O5" "Neuro2a" "Nexrutine®" "ng/mg" "NH3/MeOH" "NH4SCN" "NH…O" "nIgG:ficolin"
 "NIH/MEN2A" "NITD-008" "NM_0010" "NM_001001303" "NM_009283" "NM_213659" "NN…"
 "no-observed-adverse-effect-level" "no/yes" "non-APC" "non-CM" "non-immunoglobulin" "non-integrin"
 "non-lectin" "non-lysosomal" "non-polar-sub-fraction" "non-PPBS" "non-receptor"
 "non-retention-focused" "non-RV" "non-vector-borne" "non‑specific" "North America-Mattson"
 "North America3,4" "NS2B" "NS3/4A" "NS3pro" "nsp16" "nt1128" "nt14-25" "nt203" "nt256" "nt384"
 "nt419-420" "nt74" "nt80" "NTCC11637" "NU-172" "nucleosides/nucleotides" "NX21909" "n→π*"
 "N−++N+−N++N−" "N−+=0" "N−+=N+" "N−+=N+−=0" "N−N+" "O-alkyldithiocarbanato" "o-aminonaphthyl"
 "O-H···N" "O-H···O" "o-MeOC6H4CO2" "o-nitro groups" "o-specific" "O157:H7" "O2and" "O2C" "O3A"
 "O3atom" "O3B" "O3S-Cam" "O3S-RN" "O3SMes" "O3SR" "O4NS" "OAS-like" "Oasl1" "Oasl2" "OD450"
 "OD570" "ODS-A" "Olex2" "on-time" "One-day-ahead" "one-time" "One-year-old" "only/ate"
 "only/children" "Ophiopogonin-D" "Opti-MEM" "optical/physicochemical" "ORF1b" "org/" "org/home/"
 "organic/inorganic" "OriginPro8.0" "OS-9/Yos9p" "Osterholz-Scharmbeck" "outbreak16" "output_file"
 "O−H···O" "P-388" "p-aminophenyl" "p-block" "p-choro-benzoylhydrazone" "p-Cl" "p-coumaric"
 "P-domain" "P-LPE" "p-toluene" "p-toluenesulphonate" "p-tolyl" "p-trifluoromethyl" "P-type"
 "P-type/mannose-6-phosphate" "P-type/MPRs" "p-value" "P-value" "p-values" "P.D.M." "P.li" "P/"
 "P388D1" "P=R1R2R3R4R5R6R7⋯RL" "PA-100" "PAC-2A-Rluc" "pACNR1180" "pACNR1811" "PaCO2" "pACYC177"
 "pan-sPLA2" "Panoskaltsis-Mortari" "PaO2" "PaO2/FiO2" "papain-like" "PAR25"
 "para-nitrobenzoylhydrazone" "Paraiba_01/2015" "parents/families" "ParSP25-related"
 "participant/proxy" "passengers/car" "patatin-like" "patchouli alcohol:O" "pathogen-like" "pax/m2"
 "pBeloBac11" "pBR322" "PBS-TWEEN" "pBS/U6" "pBS/U6-No16" "pBS/U6-siN1240" "PBS−/−" "PCCCCH2"
 "PCCCH2" "PCCH2" "PCCOCH2CH2" "pcDNA3.1" "pCDNA3.1+" "pcDNA6.2-GW" "pcDNA™6.2-GW" "PCH2CH2"
 "PCH2CH2CH2" "PCH2CH2O" "PCH2CH2OCH2CH2" "PCH2NH" "PCH2O" "PCH2OCH2CH2" "pCMV-HA" "pCMV-Myc"
 "pCMV-Myc-M." "PCO2" "PCOCH2CH2" "pCon1" "PCR43" "PCV2" "PCV2-SD" "PCV2-systemic" "Pd/C" "pdm09"
 "PE/EtOAc" "PEG-ALD-LCVN" "PEG-aldehyde-" "PEG4-bombesin" "pEGFP-M" "pEGFP-Np" "PegIFN/RBV"
 "pegylated-IFN" "pegylated-interferon" "people/km2" "peptide-like" "peptide-receptor"
 "peptidyl-prolyl" "Pepto-Bismol" "Perkin-Elmer" "pET30a" "pET3a" "PF-232,798" "PfEMP1"
 "pFK-JFH1J6C-846_dg" "pfu/mL" "PFU/mL" "pg/ml" "pGM169/GL67A" "Ph2Bi" "Ph3Bi" "Ph3BiCl2"
 "Ph3BiCO3" "Ph3ML2" "Ph3Sb" "Ph3SbCl2" "pHA-EcUb" "PhBiL2" "PheA137" "phi29" "PhiPhiLux-G1D1"
 "PI+" "PI3P" "pIC50" "Pierce®" "piggyBac/AAV" "piggyBac/Ad" "piggyBac/HDAd" "pin-yin" "Pino-Yanes"
 "Pip6" "piperazin-1-yl" "PixSys5500" "pJ201" "pJAZZ-OC" "PL53" "Pla2g2d+/+" "Pla2g2d−/−"
 "Pla2g2e−/−" "Pla2g2f-TG" "Pla2g2f−/−" "plaques/well" "plasmepsin-2" "plasmepsin-4" "PLR-Lc1"
 "PM10" "PM2.5" "PM3" "PM6" "pmirGLO-NFKBIA" "pmirGLO-NKIRAS" "pmirGLO-NSFL1C" "pmirGLO-PDLIM2"
 "pmirGLO-SOCS1" "pmirGLO-target-Mut" "pmirGLO-target-wild-type" "pmirGLO-target-WT" "PNA/PMO"
 "pneumonitis/ARDS" "PNiFty-luc" "PNPLA1" "POCH2CH3" "polymer/DNA" "polymerase-II-promoter-driven"
 "pore-like" "positive/negative" "positivity/negativity" "post-hoc" "pp1a/b" "PPARβ/δ" "PPBSPξ−"
 "pPICZαA" "pPICZαA-NS2B-NS3pro" "pre-HCT" "pre-let-7a-1" "pre-lysosomal" "pre-S1" "predictor=ℝF"
 "presence/absence" "present-day" "pressure/volume" "prevalence/densities" "Prion/virology"
 "PRJEB86458" "pro-caspase-8" "pro-oncoprotein" "pro-protein" "pro-thrombin" "ProA134" "ProB149"
 "processes/diseases" "product-like" "ProFection®" "promoter/vaccine" "prop-2-en-1-one"
 "propane-1,3-dione" "protein IκBα" "protein R-phycoerithrin" "protein/peptide" "proteins/genes"
 "Proteins/Peptides" "Prp24" "PRVABC59" "pS32/pS36" "psiCHECK-2" "psiCHECK2" "psoriasis-like"
 "PstDNV1" "pT180/pY182" "pT183/pY185" "PTC124" "Ptdlns3K" "pTT5" "pTT5SH8Q1" "pTT5SH8Q1-GFPq"
 "pUC19" "pUC19-HH-pre-let-7a-1-HDV" "pUC57" "PUL26" "Pulmaquin™" "PUMC01" "Puritan®UniTranz-RT®"
 "pX330" "PYR-41" "Pyr-41" "pyridin-2-yl" "pyridine-2-carbaldehyde" "pyridine-Ac2O" "Pξ" "Pξ={Φ1"
 "QIA-03342" "QIA-KR" "QIA-Q43" "QM/MM" "Qseph-A" "Qseph-B" "Qseph-B." "quercetin-3-O-benzoic acid"
 "quercetin-3-O-ester" "quercetin-3-O-ether" "quercetin-3-O-substituted" "quercetin-NS5B"
 "quinazolin-4" "quinazolin-4-one" "quinazoline-4-one" "quinazoline/quinazolinone"
 "quinoxaline-1,4-dioxides" "QX-like" "QX/T" "Qβ" "R&D" "R+ξ" "R-Biopharm" "R/S" "r0>2" "r0≤2"
 "r0≤r" "r0≤r≤rn" "R1R2⋯Rξ" "R2}3" "R2≥0.995" "R3R2C=NR1" "R3V6" "r=" "rAAV2/8" "rAAV2/AAV8"
 "rAAV6" "rAAV9" "random_thetas-rhos" "Rap22a" "rapidly29,30," "Ras-like" "rate33,34" "RCL2" "RCL3"
 "RecA1" "RecA2" "receptors/attachment" "RECOMBIVAX®HB" "Reed-Muench" "Reed–Muench"
 "ref|NC_001802.1|" "Reovirus-1" "replication/transcription"
 "REPLICorPresentationGLOS2009ver2public" "RETC634y" "Retrovirus/Sporothrix" "Rg3"
 "RGD-surface-modified" "Rhenistetten-Forchheim" "rhudson1" "ribozyme/aptamer" "RIDASCREEN®" "Ri|P"
 "Ri|PP" "rLinB-13" "Rluc-2A" "RL−ξ+1⋯RL−1RL" "rn=6r0" "RNA polymerase/transcriptase" "RNA/Protein"
 "RNA10.11:DNA:valP" "RNA33–35" "RNasin®" "rn≤r" "RO5" "rod-like" "Rodríguez-Esparragón"
 "Rodríguez-Varela" "Romero-Gómez" "ROO•" "Roque-Barreira" "rPpSP32" "rs10774671"
 "rs10774671genotypic" "rs11066453" "rs1131454" "rs12345" "rs12979860" "rs145946881" "rs2240190"
 "rs3741981" "rs41380347" "rs41525747" "rs4988235" "rSP03B" "RT-PCR/PCR" "RTC14" "RvD1" "S+" "S.A."
 "S/P" "S10A" "S10B" "S10C" "S1PLyase" "S1–S3" "S1–S54" "S2COR" "S2–S4" "S2–S5" "S5A" "S6K" "S:R"
 "SA14-14-2" "Saei-Dehkordi" "Saint-Quentin" "Sall+" "Sall=Sall+∪" "sample_stats" "Sanchez-Mazas"
 "SAR/QSAR" "Save®" "SbPh3/GA" "sc-2031" "SCC9" "sCD46" "sCD46-C4bpα" "score>|3|" "Scott-Moncrieff"
 "ScVO2" "SD2" "sDAF-Fc" "season37" "SeCH2" "SeCH3" "secreted/RANTES" "September–December"
 "Sequence-1" "Sequence-2" "Ser9/21" "SerA34" "Sero-strip" "Sero‐prevalence" "settings3"
 "several-fold" "SGWX-4" "shAkt1" "Shan-June" "ShanghaiQXC1" "ShanghaiQXC2" "SHELXL-93" "SHELXL-97"
 "SHELXL97" "Shine-Dalgarno" "shrimps/dilution" "si-IL-17RE" "si-IL-17RE#1" "si-IL17RE" "si-M1"
 "si-M2" "si-M2:M" "si-M3" "si-N#16" "si-N1240" "si-N213" "si-N863" "si-NFKBIA" "si-No16"
 "si-SOCS1" "Siliphos®" "Silipide®" "simulation/set" "SIMV+PS" "Sin2748" "Singapore36"
 "site—S1—near" "SL-Rg" "SMMC‑7721" "sn-2" "SN2-like" "Sn=0" "Sn=1" "SnCl4" "SNU-10043" "SNU-8067"
 "SNU-9106" "SNU9106" "sO2" "sodium/glucose" "solid-state" "SP01A" "SP25" "Sp=0" "Sp=1"
 "Specord-M80" "SPH2015" "spider-like" "sPLA2-IIA" "sPLA2-IIC" "sPLA2-IIF-directed"
 "sPLA2-IIF-driven" "sPLA2-IIF—play" "sPLA2-V" "sPLA2s—hair" "spoilage/quality"
 "Sporothrix/helminths" "SPR/QSPR" "ss-DNA" "SSM1" "SSM2" "SSM3" "Ssurf+" "Ssurf=Ssurf+∪"
 "St-Antoine" "STAT3/HIF‑1α" "Stata®" "State-of-the-art" "steady-state" "Sterling-Winthrop"
 "sterol regulatory element-binding protein 1c" "stimulatory/chemoattracting" "strains/serotypes"
 "StrepTagII/His8" "Students–Newman–Keuls" "study14" "sub-micromolar" "sub-Saharan"
 "substrate/Dicer" "subunit 3A" "survivors/total" "Survivors/total" "swine8" "SYBR®" "sYEL1"
 "sym/sub" "syrup-like" "systems20" "systems22–25" "SZ-WIV001" "SZ-WIV01" "Sánchez-Lerma"
 "Sánchez-Luque" "t-butyloxycarbonyl" "T-helper" "T/C" "T2A" "t=14" "TA97a" "Tamura-Nei"
 "target-protein" "TBZE-029" "TCAAGCACCT-3" "tcacagcgccctttttg-3"
 "tcagacaagcttgtctgattaggtcttggtccctttttg-3" "TCID50" "TCID50/cell" "TCID50/ml" "TCID50/mL"
 "TCID50s/ml" "TCO2" "TE2000U" "Teide-HPC" "term=SP01A" "tert-butoxycarbonyl"
 "tert-butyldimethylsilane" "tests30" "Th1/Th17" "Th17" "thermo-labile" "thiol/disulfide" "Ti<Tz"
 "Ti>/=Tz" "TiCl4" "times/day" "times/year" "TIP3P" "Tissue-Tek®" "tissues/organelles" "TK+"
 "TK+VZV" "TMC353121" "TOF-QII" "tool-like" "TopoPSA—topological" "trans-11a" "trans-11b"
 "trans-11d" "trans-11e" "trans-11e/cis-11e" "trans-11f" "trans-11f/cis-11f" "trans-11g"
 "trans-11i" "trans-11i/cis-11i" "trans-11j" "trans-11k" "trans-11k/cis-11k"
 "trans-3-hydroxycinnamic" "trans-3-phenyl-2-propenoic" "trans-4-hydroxycinnamic"
 "trans-activator protein" "transcriptional/translational" "transposon/viral" "traps/sinks"
 "tri-sialo-ganglioside" "triacrylate–spermine" "triazol-1-yl" "tricyclo-DNA" "triester-like"
 "TRIM30α" "Trimeric/tetrameric" "trimethylstanny1" "tris-carboxylato" "Triton X-100/PBS" "Trolox®"
 "TRPC3-/-" "Trx-like" "TS100" "Tsao-ko" "TSC1/2" "TSL-1-5-7-" "TSL-1-5-7-treated-UM1" "TSL‑1-5-7"
 "TTA1" "tttagcaaagcaatattgtcgtt-3" "type B1" "type/size" "Tyr406:OH" "TyrA92" "U/ml" "U16"
 "U16snoRNA" "U2/U6" "U251" "U4atac" "U6-siM1" "U6-siM2" "U6-siM3" "U6atac" "U6b" "u7-peptide"
 "Ube1L-/-" "UbE1l—the" "UDP-glucose:glycoprotein" "UGC-3" "UL12" "Ultra-4" "ultra-long chain"
 "UM2" "undiagnosed1" "units/mL" "up/down-regulated" "Up‑regulated" "Usb1" "Usb1–UU" "USD-$3800"
 "use/installation" "USP18-/-" "UV-1601" "UV/Vis" "UXNMR/XwinNMR" "U·L−1" "U·mg−1" "V.9.1" "v/v"
 "v/w" "Val136at" "vcf_" "Vectashield®" "Vector-borne" "vector/host" "VEGF165" "vehicles17,18."
 "ventilation/" "VIP36CRD" "Virus-like" "virus/cell" "virus12" "viruses19" "viruses31" "viruses35"
 "visits/questionnaires" "vitamin D1" "vo/" "vol/vol" "VP019" "VP136" "VP19" "VP6" "VP67" "VP72"
 "VP75" "VP86" "Vpg34" "VR-1238" "VR-1540" "VR-2018" "VR-3" "VR2001-TOPO" "w/v" "w/w" "Water-like"
 "water/phosphoric" "Weger-Lucarelli" "weight/body" "weight/volume" "WHO/FDI" "wild type/mutation"
 "wind-bi" "with/inhibit" "WN83" "WST-1" "Wu-Wei-Zi" "X-radiograph" "X-tremeGENE" "x1" "x2" "x2−x1"
 "Xcalibur2" "Xiao-Qing-Long-Tang" "Xin-Yi-Qing-Fei-Tang" "xi∼Poisson" "XWS02F40" "Y.H." "y/o"
 "y2−y1" "YEL1" "Yi-Qiao-San" "Yos9p" "Yu-Xing-" "YX10p90" "z-DEVD-FMK" "Z-EDVD-FMK" "Z-isomer"
 "Zeocin·mL−1" "ZJ01" "ZM4" "ZnCl2" "zones/districts" "ZS-C" "{4-" "{J" "{Pξ+"
 "{Sn=1−N−+N+0≤Sn≤1Sp=1−N+−N−0≤Sp≤1Acc=Λ=1−N−++N+−N++N−0≤Acc≤1Mcc=1−" "{Ssurf" "|A" "~1,600" "~1.5"
 "~10" "~106" "~106 fold" "~15" "~1–13 µ" "~23" "~26 µ" "~267" "~28" "~29.7" "~3–4" "~4.6" "~50"
 "~56%" "~60%" "~60,000" "~68%" "~7-nt" "~70" "~77%" hrix/helminths" "SPR/QSPR" "ss-DNA" "SSM1" "SSM2" "SSM3" "Ssurf+" "Ssurf=Ssurf+∪" "St-Antoine" "STAT3/HIF‑1α" "Stata®" "State-of-the-art" "steady-state" "Sterling-Winthrop" "sterol regulatory element-binding protein 1c" "stimulatory/chemoattracting" "strains/serotypes" "StrepTagII/His8" "Students–Newman–Keuls" "study14" "sub-micromolar" "sub-Saharan" "sub-type" "substrate/Dicer" "subunit 3A" "survivors/total" "Survivors/total" "swine8" "SWISS-PROT" "SYBR®" "sYEL1" "sym/sub" "syrup-like" "systems20" "systems22–25" "SZ-WIV001" "SZ-WIV01" "Sánchez-Lerma" "Sánchez-Luque" "t-butyloxycarbonyl" "T-helper" "T/C" "T2A" "t=14" "TA97a" "Tamura-Nei" "target-protein" "TBZE-029" "TCAAGCACCT-3" "tcacagcgccctttttg-3" "tcagacaagcttgtctgattaggtcttggtccctttttg-3" "TCID50" "TCID50/cell" "TCID50/ml" "TCID50/mL" "TCID50s/ml" "TCO2" "TE2000U" "Teide-HPC" "term=SP01A" "tert-butoxycarbonyl" "tert-butyldimethylsilane" "tests30" "Th1/Th17" "Th17" "thermo-labile" "thiol/disulfide" "Ti<Tz" "Ti>/=Tz" "TiCl4" "times/day" "times/year" "TIP3P" "Tissue-Tek®" "tissues/organelles" "TK+" "TK+VZV" "TMC353121" "TOF-QII" "tool-like" "TopoPSA—topological" "trans-11a" "trans-11b" "trans-11d" "trans-11e" "trans-11e/cis-11e" "trans-11f" "trans-11f/cis-11f" "trans-11g" "trans-11i" "trans-11i/cis-11i" "trans-11j" "trans-11k" "trans-11k/cis-11k" "trans-3-hydroxycinnamic" "trans-3-phenyl-2-propenoic" "trans-4-hydroxycinnamic" "trans-activator protein" "transcriptional/translational" "transposon/viral" "traps/sinks" "tri-sialo-ganglioside" "triacrylate–spermine" "triazol-1-yl" "tricyclo-DNA" "triester-like" "TRIM30α" "Trimeric/tetrameric" "trimethylstanny1" "tris-carboxylato" "Triton X-100/PBS" "Trolox®" "TRPC3-/-" "Trx-like" "TS100" "Tsao-ko" "TSC1/2" "TSL-1-5-7-" "TSL-1-5-7-treated-UM1" "TSL‑1-5-7" "TTA1" "tttagcaaagcaatattgtcgtt-3" "type B1" "type/size" "Tyr406:OH" "TyrA92" "U/ml" "U16" "U16snoRNA" "U2/U6" "U251" "U4atac" "U6-siM1" "U6-siM2" "U6-siM3" "U6atac" "U6b" "u7-peptide" "Ube1L-/-" "UbE1l—the" "UDP-glucose:glycoprotein" "UGC-3" "UL12" "Ultra-4" "ultra-long chain" "UM2" "undiagnosed1" "units/mL" "up/down-regulated" "Up‑regulated" "Usb1" "Usb1–UU" "USD-$3800" "use/installation" "USP18-/-" "UV-1601" "UV/Vis" "UXNMR/XwinNMR" "U·L−1" "U·mg−1" "V.9.1" "v/v" "v/w" "Val136at" "vcf_" "Vectashield®" "Vector-borne" "vector/host" "VEGF165" "vehicles17,18." "ventilation/" "VIP36CRD" "Virus-like" "virus/cell" "virus12" "viruses19" "viruses31" "viruses35" "visits/questionnaires" "vitamin D1" "vo/" "vol/vol" "VP019" "VP136" "VP19" "VP6" "VP67" "VP72" "VP75" "VP86" "Vpg34" "VR-1238" "VR-1540" "VR-2018" "VR-3" "VR2001-TOPO" "w/v" "w/w" "Water-like" "water/phosphoric" "Weger-Lucarelli" "weight/body" "weight/volume" "wheel-type" "WHO/FDI" "wild type/mutation" "wind-bi" "with/inhibit" "WN83" "WST-1" "Wu-Wei-Zi" "X-radiograph" "X-tremeGENE" "x1" "x2" "x2−x1" "Xcalibur2" "Xiao-Qing-Long-Tang" "Xin-Yi-Qing-Fei-Tang" "xi∼Poisson" "XWS02F40" "Y.H." "y/o" "y2−y1" "YEL1" "Yi-Qiao-San" "Yos9p" "Yu-Xing-" "YX10p90" "z-DEVD-FMK" "Z-EDVD-FMK" "Z-isomer" "Zeocin·mL−1" "ZJ01" "ZM4" "ZnCl2" "zones/districts" "ZS-C" "{4-" "{J" "{Pξ+" "{Sn=1−N−+N+0≤Sn≤1Sp=1−N+−N−0≤Sp≤1Acc=Λ=1−N−++N+−N++N−0≤Acc≤1Mcc=1−" "{Ssurf" "|A" "~1,600" "~1.5" "~10" "~106" "~106 fold" "~15" "~1–13 µ" "~23" "~26 µ" "~267" "~28" "~29.7" "~3–4" "~4.6" "~50" "~56%" "~60%" "~60,000" "~68%" "~7-nt" "~70" "~77%" "~78%" "~8" "~800" "~81%" "~82%" "~83%" "~97%" "~98%" "~99%" "°/min" "°C" "°C." "°C/min" "°C–124" "°C–125" "°C–127" "°C–132" "°C–59" "°C–68" "°C–87" "°C–91" "°C–93" "±1.5–2-fold" "±SD" "·2H2O" "ºC" "ºC." "×10−69" "×dHt−1and" "×g" "ß2" "á1-2-mannose" "â-galactose-specific" "Å-resolution" "ʋ1" "ʋ2" "ʋ3" "ʋ4" "ʋ5" "˃250" "α-bisabolol" "α-d-glucosyl" "α-humelene" "α-humulene" "α-mannosidase-like" "α-panasinsen" "α-radioimmunotherapy" "α-selinene" "α-terpineol" "α-thujene" "α-tocopheryl" "α/α" "α/β" "α1,2-linked" "α1,3-linked" "α1,6-linked" "α1β2" "α2β2" "α2δ2" "α>1" "αi" "αi∼Γ" "β-aminoethyl" "β-bisabolene" "β-cuben