;; covid-2020-04-03-0403-COM-PMC-2301-2400 sample of unknown words
;; created 5/10/20 12:38:46

(in-package :sparser)

;; 3275 extracted as unknown bio-entity


(defparameter *All-Upper-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*All-Upper-Unknown-Words*) (symbol-value `*All-Upper-Unknown-Words*))
         '(
("AAALAC" "AACV" "AAGCAGCACGACUUCUUCAAGU" "AATGAAAAGCTTCACCATGATTCACTCCGTGTTCCTC" "AAU" "ABX"
 "ACACTGACGCACACTGACGCACACTGACGCACACTGACGC" "ACCGCCGAGCACCTTCCAGG" "ACLF" "ACPYPE"
 "ACTGTCAAGGCTGAGAACGG" "ADV" "AEC" "AECI" "AFS" "AGCACACCAGCATCAACATGC" "AGGTGAGCATCCCGCTGCAC"
 "AGID" "AGM" "AHCC" "AHVLA" "AIC" "AIV" "ALEN" "ALFV" "ALV" "AMAXA" "AMNET" "AMV" "ANCOVA" "ANKA"
 "ANSI" "APMV" "APTT" "ARTI" "ASGPR" "ASLA" "ASLV" "ASPHER" "ATCC" "ATHL" "ATTTA" "AUA"
 "AUAUUAGGUUUUUACCUACCC" "AUAUUAGGUUUUUACCUACCCU" "AUG" "AURAV" "AUUUA" "AVANCE" "AVMA" "AVYNFATC"
 "ALEXA" "BALF" "BBB" "BCL" "BDCA" "BDV" "BEB" "BEV" "BFV" "BHI" "BLASTX" "BLV" "BMG" "BML" "BMV"
 "BN" "BRIG" "BRV" "BSE" "BVD" "BVDV" "BWYV" "BZ" "CAAGAACATGTGTAAGCTGC" "CAEV"
 "CAGGGCTGAAAGGTTCCAGG" "CASAVA" "CATAATGTAGCAGCAGGTTC" "CATI" "CAUGGGAGUUAUCCAUUGA" "CAZV" "CBPV"
 "CCACCAACTGCTTGGCCCCC" "CCCCACATGGGCAGGTTTCCAG" "CCCTGGAACTAATTTGTATAC" "CCTCGGCCATCACGCCACAG"
 "CCU" "CCUUGGGUUCGUCUACAAA" "CDPH" "CFAV" "CGATACTCGTCCGCTTTCTC" "CGC"
 "CGCCTCCACCTGGGGTCAGTGTGCTGGGGGT" "CGTCGCACTCCACGCCTTCTGCC" "CHIKV" "CHPV" "CHX" "CIL" "CIRE"
 "CLSM" "CLUSTALW" "CMI" "COE" "COK" "COPII" "CPMV" "CSFV" "CTACAGTGGAGCTGGCT"
 "CTACGAAGTCCTTGGCGATGA" "CTAGCCTTGCGCTAGATTTTTAACT" "CTCCACGTAATAAGGGTCTTC" "CTG"
 "CTGTAGATATTTAATCAATTGTAAATAGACAA" "CTT" "CUG" "CUUGAAGAAGUCGUGCUGCUUU" "CV" "CVMP" "CYV" "CZ"
 "DAKO" "DAVP" "DENV" "DIST" "DKO" "DMEM" "DMV" "DNAMAN" "DOJINDO" "DPBS" "DSB" "DTSC" "DVG" "DVM"
 "DXV" "EAV" "EBNA" "ECACC" "ECDC" "EFSA" "EIA" "EKG" "EMBL" "EMCDDA" "EMCV" "ENIVD" "EOPM" "EPFL"
 "EPOM" "EQEFYENMYRAPTTLQ" "ERRAT" "ESCRT" "ESV" "ETGL" "ETRL" "FASTA" "FASTQC" "FBG" "FCGS" "FCOV"
 "FECV" "FED" "FFU" "FHV" "FIPV" "FIRE" "FIRS" "FLISSSQDG" "FMC" "FMV" "FPV" "FQPQNGQFI"
 "FRNQASRPY" "FTE" "FUBAR" "FVFG" "FXB" "GAC" "GADPH" "GAGACTGGGAACAGC" "GAGAGGTACACGCGGGACAA"
 "GAGAGTGGATGAC" "GARLI" "GATTGCACTGGTCACCTCG" "GCAAAACA" "GCAACGCCTGGCCCTGAGT"
 "GCCACAACCATAATAGAATGTC" "GCGAAGTACCTGAACATCACG" "GCGAATTCTTAGCACAGGGACGCGT" "GCTGAGGGAGCTGAGATGA"
 "GCU" "GETV" "GFLV" "GGAGTCCCACCGTATGAAC" "GGCAGAAAAACAACTGGCCGAGGAA" "GGCGTCTCCACCGTCACCA"
 "GGGGC" "GGGGS" "GGGTCCTCCTTCCGAGACGGT" "GGSGDPPPPNPNDPPPPNPND" "GGSGDPPPPNPNDPPPPNPNDK" "GIBCO"
 "GISAID" "GJB" "GLNGPDIYKGVYQFKSVEFD" "GNU" "GOUV" "GPSS" "GRACE" "GROMACS" "GSGSGSGSGS" "GTAA"
 "GTAAATA" "GTAAGT" "GTC" "GTCACCCTGACTCTCTTCTG" "GUA" "GUG" "HAART" "HAC" "HAXP" "HBGC" "HBS"
 "HBSS" "HCW" "HEIDI" "HERV" "HIA" "HIVE" "HIVIG" "HKUST" "HMBG" "HPAIV" "HQ" "HTNV" "HVRI" "HWW"
 "IACUC" "IAV" "IBM" "IBV" "ICPI" "ICS" "ICTV" "ICU" "IDT" "IFV" "IGEPAL" "INR" "IPD" "IPG" "IQR"
 "IRB" "IRCCS" "IRD" "IRES" "IRSS" "ISRE" "IUHPE" "IVGG" "IVIG" "JDV" "JEOL" "JEV" "JFM" "JGZ"
 "JHMV" "JSRV" "KAPA" "KAVYNFATC" "KGE" "KRV" "LBV" "LDV" "LFB" "LFQ" "LHD" "LIIFKNQAS" "LINCS"
 "LJK" "LKRSFFALRDQIPELENNEKAPKVVILKKATAYILSVQAE" "LLB" "LLIS" "LOD" "LOQ" "LRT" "LRTI" "LTR" "LXS"
 "LZC" "MAXISORP" "MAYV" "MCCR" "MCLAB" "MCMC" "MDDC" "MDT" "MEM" "MEME" "MFE" "MFI" "MHCII" "MHV"
 "MICU" "MIDV" "MIQE" "MJU" "MMCT" "MMDS" "MMWR" "MNTA" "MOI" "MPER" "MPS" "MRFA" "MSRH" "MSSQL"
 "MTVB" "MUN" "MVEV" "MWCR" "MXV" "NACCHO" "NAKV" "NASBA" "NDUV" "NEDSS" "NEG" "NETSS" "NIG"
 "NQWAVGHLM" "NVD" "NVT" "NYASAAEA" "OADC" "OD" "OECD" "OIE" "OLAW" "OMX" "ONFH" "ONNV" "OPTIMA"
 "ORGN" "ORL" "PARRIS" "PCVAD" "PHAC" "PHENIX" "PHEP" "PIRO" "PLRV" "PMWS" "PROP" "PRRS" "PRRSV"
 "PSDP" "PVX" "QBV" "QIAGEN" "QRS" "QSR" "QTOF" "QTRL" "QUARK" "RAAS" "RABV" "RDOCK" "REMD" "RFU"
 "RFUDMSO" "RFUMOCK" "RGD" "RINS" "RMSD" "RNAL" "RPKM" "RPMM" "RRLC" "RSCU" "RVC" "RVFV" "SAIBK"
 "SANCO" "SAON" "SAPN" "SCID" "SELDI" "SELEX" "SEOV" "SEQUEST" "SESV" "SFRH" "SFTSV" "SFV" "SHAKE"
 "SHFV" "SHIFTX" "SHIV" "SINV" "SJC" "SLAC" "SLIC" "SMRU" "SNOSID" "SNV" "SOFA" "SPAFAS" "SPDV"
 "SPECT" "SPSS" "STEMCELL" "SVM" "SVV" "SWRD" "SYBR" "SYW" "TAAAT" "TAE" "TAGTTTTCTAGAACTTC"
 "TAGTTTTCTAGAACTTCCGCCTCCAC" "TAGTTTTCTAGAACTTCCGCCTCCACCATAA" "TAV" "TAVSPTTLR" "TBE" "TBLASTX"
 "TBST" "TCCATGCAGGAG" "TCID" "TCT" "TEU" "TEV" "TFEU" "TGCACCACCAACTGCTTAG" "TGCC"
 "TGCTATGTCAGTTCCCCTTGGTTCTCT" "TGEV" "TGG" "TIBCO" "TMV" "TMY" "TPB" "TSW" "TTA" "TTC" "TTVSTSTLA"
 "TVCV" "TVIPS" "UA" "UAAAU" "UAG" "UAU" "UCAAUGGAUAACUCCCAUG" "UCSC" "UCU" "UD" "UF" "UGA" "UGC"
 "UGFA" "UGFM" "UGU" "UPM" "URT" "USA" "USACDC" "USB" "USGS" "USUV" "UTM" "UUA"
 "UUCUCCGAACGUGUCACGUGU" "UUUGUAGACGAACCCAAGG" "UVP" "UX" "UZ" "VAED" "VCE" "VEEV" "VIDRL" "VIPS"
 "VMRD" "VR" "VRC" "VRDL" "VSVG" "VTI" "WAKO" "WARFS" "WBC" "WEEV" "WHAV" "WN" "WNVKUN" "WRD" "WSX"
 "WTSI" "XIV" "XJZ" "XXY" "YBZ" "YCC" "YPD" "YPFS" "YRL" "YYC" "YYY" "YYYTR" "YYZ" "ZB" "ZDOCK"
 "ZL" "ZNA" "ZORBAX" "ZTE" "ℙ" "ℤ" "傷寒論" "張仲景" "正虛證" "氣分熱證" "氣虛證" "溫熱論" "營分熱證" "葉天士" "血分熱證" "血虛證"
 "衛分熱證" "邪實證" "陰虛證" "陽虛證" "黃帝內經")))
    :test #'equalp))


(defparameter *All-Lower-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*All-Lower-Unknown-Words*) (symbol-value `*All-Lower-Unknown-Words*))
         '(
("aberrances" "abinitio" "abramus" "absorbance" "adducts" "adegenet" "adeno" "adenosylmethionine"
 "advisories" "aegypti" "aegyptiacus" "aeruginosa" "afeard" "africana" "aglycon" "agrarius" "ahabs"
 "alarmins" "albicans" "albopictus" "alecto" "algorithm" "alia" "aliquot" "aliquots"
 "alloantibodies" "alloantibody" "alloantigen" "allophycocyanin" "allotypes" "alphaherpesvirus"
 "alphanodavirus" "alternans" "alveoli" "ambigua" "aminoacid" "amplicon" "amplicons" "analytes"
 "anopheline" "antagomirs" "antennapedia" "antihistamines" "antineck" "antinucleoprotein"
 "antivaccinia" "antivirus" "apnoea" "aporc" "appendiculatus" "appropriateness" "arisen"
 "arrhythmia" "arrondissements" "arterivirus" "arthroplasty" "artificialities" "ascendens"
 "asialoglycoprotein" "aspirators" "assemblers" "assertiveness" "astragaloside" "atractylenolide"
 "atria" "atrium" "authorisations" "autoimmune" "autoloader" "autoradiograms" "autosampler" "axial"
 "b" "babraham" "backpack" "bafilomycin" "bandicoot" "barostat" "batacoronaviruses" "baumannii"
 "beamline" "begun" "bellman" "belongings" "benthamiana" "berghei" "bilayer" "bilayers" "bio"
 "bioaerosol" "bioassays" "biobank" "biocabin" "biodeme" "biodomes" "biomaterials" "biomolecules"
 "biopsies" "biopsy" "biosafety" "biosensors" "biostack" "bioterrorism" "bioterrorists" "biotypes"
 "birnavirus" "blastocyst" "blastx" "blocker" "blockers" "bloodmeals" "bluetongue" "bodyweight"
 "boldface" "boney" "bonferroni" "boranocarbonate" "borealis" "boringquense" "bracovirus"
 "brainstem" "breakpoint" "broken" "bromovirus" "bromoviruses" "bronchioli" "bronchiseptica"
 "browser" "brucei" "buffy" "burnout" "bursa" "bwa" "bwasw" "c" "cacodylate" "caecum" "calicivirus"
 "caliper" "cannula" "capita" "capsulatus" "carbamidomethyl" "carboxyl" "carboxypeptidases"
 "cardiology" "cardiomegalies" "cardiopathy" "caspius" "catarrhalis" "categorise" "catheters"
 "catus" "caulimovirus" "caveosome" "caveosomes" "cecal" "cecum" "cellulo" "cerebellum" "cerebrum"
 "cerevisiae" "cgi" "chem" "chemcials" "chilliness" "chironomid" "chironomids" "chloriquine"
 "chloromethyl" "chordates" "choriomeningitis" "chosen" "chromagen" "chromatograms" "chromatograph"
 "ci" "cilias" "cinereoargenteus" "cinereus" "circovirus" "cisternae" "clade" "classifier"
 "clinicaltrials" "clinicians" "cloven" "clínica" "codon" "coli" "collectin" "colostrum"
 "commensals" "commonalities" "commonest" "comorbid" "comovirus" "composites" "confounder"
 "congregata" "contig" "contigs" "contraindications" "cosavirus" "cosmid" "covariance" "covariate"
 "coworker" "coworkers" "cowpea" "coxsackie" "coxsackievirus" "cruzi" "cryo" "cryoelectron"
 "cryomolds" "cryostat" "cryovials" "cuboid" "culicine" "cuvettes" "cy" "cycler" "cytology"
 "cytometer" "cytospin" "cytotrophoblasts" "davidii" "decamer" "defluxions" "degasser" "der"
 "diaphorases" "dichlorofluorescein" "dichroism" "dicistrovirus" "difficile" "diffractometer"
 "difluoride" "dihydrochloride" "dihydrodichlorofluorescein" "dimensionless" "diploids" "dipteran"
 "dipterans" "discriminant" "dispanin" "displaystyle" "divaricata" "dormancy" "dounce" "dpinf"
 "drawn" "droplet" "dropwise" "duosets" "duplexes" "dwgsim" "dysphagia" "dysplasia" "dyspnea"
 "dyspnoea" "ealth" "easiness" "echocardiography" "ectocervix" "ectodomain" "ectopy" "edema"
 "edodes" "elaeasa" "electro" "electrocardiography" "electroencephalography" "electropherograms"
 "electrospray" "eluate" "eluates" "email" "embl" "emitter" "emitters" "enantiomer"
 "encefalopathie" "encephalomyocarditis" "endfeet" "endocervix" "endocrinology" "endotoxemia"
 "enhancer" "enhancers" "enterica" "entero" "enterobacteriophage" "enterviruse" "entomobirnavirus"
 "entomorbirnavirus" "eosin" "epibasket" "epicarditis" "epileptiform" "epinyctis" "epithelia"
 "epithelium" "epon" "epoxysilanes" "eppendorf" "epsilonretroviruses" "esosinophils" "etc"
 "etikprövningsnämnden" "exclusivè" "excreta" "exodontia" "exotoxins" "explants" "exsanguinations"
 "exudate" "exudates" "facemask" "facemasks" "facilitators" "faecalis" "fairs" "falciparum"
 "famers" "fasta" "fastq" "fava" "femora" "festinus" "ficolins" "fifo" "fittest" "flavivirueses"
 "flavivivirus" "flowchart" "flown" "flowrate" "fluorometry" "focusses" "followup" "forgotten"
 "formazan" "fowlpox" "framshift" "freeware" "frozen" "fugitivus" "fulminant" "fumigatus"
 "fundings" "funestus" "fuscus" "futher" "galactosaminyl" "gallus" "gambiae" "gammaherpesviruses"
 "garagara" "gavage" "gemones" "genbank" "genestone" "genogroup" "genome" "genomes" "germline"
 "gingivalis" "gingivostomatitis" "glabra" "glia" "globus" "glomerulum" "glomerulus"
 "gluteraldehyde" "gluteus" "glycaemia" "glycemia" "glycoconjugates" "glycophosphatidylinositol"
 "glycyrrhizate" "goes" "gondii" "gone" "gonorrhoeae" "goods" "grandiflorus" "granulomas"
 "grimshawi" "gyral" "haematology" "haemolyticus" "hannonlab" "haplotype" "headgroups" "heatmap"
 "helices" "helix" "hematology" "hematuria" "hemimembrane" "hemipteran" "hemolymph" "hendra"
 "hepialus" "heptanucleotide" "heptanucleotides" "hetero" "heterotetramer" "hexafluorophosphate"
 "hexamers" "hidden" "histochemistry" "histology" "histomorphometry" "histopathology" "holo"
 "homepage" "homogenate" "homogenates" "homogeniser" "homogenizer" "homologies" "homozygotes"
 "hotspot" "hpinf" "html" "hydropericardium" "hydroresorufin" "hyg" "hymenoptera" "hyper"
 "hyperbilirubinemia" "hyperimmune" "hyperintense" "hypermutations" "hyperpnea"
 "hyperresponsiveness" "hyphae" "hypointense" "hypoxemia" "ichnovirus" "identifiers" "idiotype"
 "iii" "ileum" "illb" "illumina" "immuno" "immunoassay" "immunoassays" "immunocytochemistry"
 "immunodominant" "immunohistochemistry" "immunophenotype" "incompleteness" "indel" "indolium"
 "inducers" "infectiousness" "infestans" "infodemiology" "infoveillance" "ingradients" "inkjet"
 "inocula" "inoculum" "instill" "intactness" "integrant" "interactors" "interconversions"
 "intercounty" "interferometry" "interhost" "internalizaiton" "internet" "interquartile"
 "interslice" "intra" "intrabodies" "intrabody" "intrahost" "intramembrane" "invaginations"
 "invariant" "investigació" "inﬂata" "iodoacetamide" "ionic" "iresite" "ischaemia" "islandicus"
 "isotype" "itb" "ix" "j" "jaagsiekte" "jackknife" "java" "jejunum" "jic" "k" "kabat" "kappa"
 "kinse" "koff" "krusei" "lactoside" "lacusprofundii" "lambda" "laticaudatus" "lato" "lavage"
 "lavages" "leucopenia" "leukocytopenia" "libitum" "ligustica" "limitans" "lineages"
 "lipopolysaccharides" "logarithms" "logit" "longipalpis" "lucifugus" "luminance" "luminometer"
 "lymphadenopathy" "lymphopenia" "macrocephala" "macrphage" "maculipennis" "manganism"
 "mannosidases" "mansoni" "manuals" "mapper" "mappings" "marismortui" "materials" "medulla"
 "melanogaster" "melena" "mellifera" "mellitus" "membranaceus" "membrance" "meningococcemia"
 "mephitis" "interspecies" "mesocarnivores" "methylcyclopentadienyl" "mexicana" "microarchitecture"
 "microautophagy" "microbeads" "microbiota" "microcentrifuge" "microdomains" "microgliocytes"
 "micrographs" "microparasites" "micropipette" "microplate" "microspheres" "microsyringe"
 "microtiter" "microtome" "microwell" "midbrain" "midheight" "midpoint" "millennia" "minima"
 "misassemblies" "mismatch" "missense" "mitovirus" "moi" "moldrzyki" "mongholicus" "monocytogenes"
 "monodisperse" "monolayer" "monolayers" "monopartite" "monophosphate" "monotherapy" "mortem"
 "motile" "mouthparts" "mpg" "msec" "msu" "mucoid" "mucosa" "mukohataei" "mulatta" "mullatta"
 "multi" "multianalyzer" "multicenter" "multidish" "multigene" "multilabel" "multilectin"
 "multilevel" "multiline" "multimaps" "multimembrane" "multiorgan" "multiprotein" "multiscreen"
 "multisubunit" "multivariate" "mya" "myocardium" "myofibroblasts" "nano" "nanoelectrospray"
 "nanofectin" "nanoflow" "nanogold" "narnavirus" "narnaviruses" "nasopharynx" "naïve" "nctu"
 "nearest" "nebulizer" "necropsy" "neoformans" "neurodynia" "neuropathology" "neutropenia"
 "neutrophilia" "nigerrima" "nimblegen" "nipah" "nnpar" "nodaviruses" "nonantibody" "nonframeshift"
 "nonhuman" "nonmalignant" "nonmannan" "nonnucleoside" "nonredundant" "nonrelevant" "nonself"
 "nonstandard" "nonsubtype" "nontelephone" "normalise" "norvegicus" "novo" "nth" "nucleoside"
 "nuocytes" "nyong" "o" "obex" "objectives" "obliqua" "oedema" "offlu" "oligoadenylate"
 "oligodeoxynucleotides" "oligosaccaride" "omic" "omics" "ones" "operon" "optometrists" "org"
 "ortho" "orthologues" "orthology" "osteotomy" "ourmiaviruses" "outages" "outreach" "overdose"
 "overtaken" "overview" "pachypus" "pachyrhizi" "pairwise" "pancreatitis" "pancytopenia"
 "panleukopenia" "papatasi" "paracrine" "parainfluenza" "paralogues" "parameterizations"
 "parenchyma" "particulates" "partitivirus" "pathobiology" "pathophysiology" "pathotypes" "payor"
 "pdf" "penile" "pentamer" "pentamers" "penton" "peptidyl" "peptone" "perfringens" "perhaps"
 "pericardium" "peripneumonies" "perisplenitis" "permissions" "pertechnetate" "pestis" "pestivirus"
 "pestiviruses" "petechia" "pharaohs" "pharmacosurveillance" "pharmacovigilance" "phenantroline"
 "phlebotomine" "phophoprotein" "phorbolmyristateacetate" "phosphopeptide" "phosphopeptides"
 "phosphoproteome" "photodiode" "photophobia" "phylogenies" "phylogeny" "pipiens" "pipistrellus"
 "pixel" "pixels" "plasmacytoid" "plex" "pneumococci" "pneumology" "polyanhydride" "polyarthralgia"
 "polyethylenimine" "polymorphism" "polymorphisms" "polyomaviridae" "polyphagia" "positives"
 "positron" "postburn" "postcollapse" "postexposure" "posthoc" "postings" "potyvirus" "potyviruses"
 "poutry" "pplab" "ppp" "pre" "preejaculate" "preproprotein" "pressors" "preterm" "priori"
 "procoagulant" "professionals" "progeny" "propriolactone" "protectant" "proteolipid" "proteome"
 "proven" "pruritis" "pseudogenes" "pseudoknot" "pseudotype" "pseudotypes" "pseudovirus" "pteropid"
 "punafcc" "pyralis" "pyrrolyridine" "quantikine" "quasi" "quasispecies" "quexml" "quexs"
 "quinquefasciatus" "radionuclide" "radionuclides" "ranks" "rapalogues" "rashes" "reactants"
 "readout" "realise" "reanalyse" "reassortant" "recognise" "recominant" "redirect" "reinhardtii"
 "relatedness" "repairmen" "replicon" "representativeness" "representatives" "responders"
 "reticulum" "retrotransposons" "rhinorrhoea" "rhodocytin" "ribos" "ringspot" "riparius"
 "rodentium" "rpm" "rugosa" "salinarum" "salmonis" "sanger" "sanitizer" "sanitizers" "saponins"
 "semi" "seminolus" "senesce" "sensu" "sequelae" "sero" "serocomplex" "seroepidemiology" "serology"
 "serosurvey" "serosurveys" "serotype" "serotypes" "serums" "shutoff" "sialosides" "silico"
 "silverleaf" "sinusoid" "socio" "solublities" "sown" "spaceflight" "spacer" "speciﬁc"
 "spectrometer" "spectrophotometer" "sphaeroides" "spherule" "spherules" "spirometry"
 "splenomegalies" "spongiform" "spongiforme" "stables" "stadtmanae" "stainings" "stakeholder"
 "stakeholders" "stali" "statewide" "stellate" "stent" "stents" "stepwise" "strepsipteran" "strewn"
 "striiformis" "styryl" "subcategories" "subclade" "subclass" "subclasses" "subconsensus"
 "subendocardium" "subepicardium" "subepithelium" "subnatant" "suborders" "subsite" "subtilis"
 "subtype" "succinimidyl" "suckler" "summarises" "supernatant" "synergism" "synteny" "tabaci"
 "tachypnea" "taken" "taxa" "tenellus" "teno" "tester" "tetrapods" "tetrasodium" "tetrazolium"
 "tetroxide" "thaliana" "thiazol" "thrips" "thrombocytes" "thymoid" "timeframe" "tissuelyser"
 "titer" "titers" "titre" "titres" "tju" "tobamovirus" "togaviruses" "toluidine" "topology"
 "torovirus" "tosylphenylalanyl" "totiviridae" "towne" "toxoid" "trabecula" "tracheas"
 "tracheotomy" "tradename" "tradeoff" "transcriptome" "transducers" "transformants" "transwell"
 "triage" "triatomines" "tricarbonyl" "trichrome" "tricuspid" "triethyl" "triphosphosphate"
 "triphosphosphates" "trisodiumcitrate" "tritaeniorhynchus" "tritherapy" "tryptose" "tubule"
 "tubules" "tumefaciens" "turbinate" "typhimurium" "u" "uera" "ugai" "uio" "ultracentrifuge"
 "ultramicrotome" "ultrapure" "ultrasonography" "ultrastructure" "un" "unawareness" "undergoes"
 "undergone" "undertaken" "ungulate" "uni" "uniprot" "univariate" "uranyl" "urethra" "utero"
 "uture" "vaccinologists" "vagal" "vaginalis" "vampyrus" "var" "variables" "veiller" "vena"
 "venules" "veronii" "veterinarians" "vii" "villi" "villus" "vinol" "viraemia" "viremia" "viruria"
 "visualise" "vitro" "vivo" "vocanii" "voicemail" "voltae" "vomitus" "walkway" "wavelet" "webpage"
 "webpages" "website" "wgsim" "wikipedia" "wisc" "withdrawn" "workflow" "workspace" "workup" "wpi"
 "written" "www" "x" "xcompare" "yellows" "zeo" "zeocin" "zeroes" "ziptip" "zoonoses" "zymography"
 "öarna" "ℙ" "ℤ" "傷寒論" "張仲景" "正虛證" "氣分熱證" "氣虛證" "溫熱論" "營分熱證" "葉天士" "血分熱證" "血虛證" "衛分熱證" "邪實證" "陰虛證"
 "陽虛證" "黃帝內經")))
    :test #'equalp))


(defparameter *MixedCase-Unknown-Words*
    (remove-duplicates
      (append 
         (when (boundp '*MixedCase-Unknown-Words*) (symbol-value `*MixedCase-Unknown-Words*))
         '(
("AAPair" "AARs" "ADVs" "AECIIs" "AECIs" "AGMs" "AITbiotech" "APMVs" "AbCam" "AbD" "Abcys"
 "Abelson" "AbiPrism" "Abnova" "Accelrys" "Accompt" "Accuprime" "Acidianus" "Acros" "Actilon"
 "Advate" "AeFV" "Aedes" "Aedimorphus" "Agastache" "Aime" "Akaike" "Akbaş" "Akv" "Aldrich" "Alexa"
 "Aliquots" "Allantoïc" "AmUAUUAGGUUUUUACCUACCC" "Ambroise" "Amersham" "Amicon" "Amira" "AnaSpec"
 "Anadys" "Anaspec" "Andover" "Anelloviridae" "Angelicae" "Ann" "Annum" "Anophelinae" "Anses"
 "Antonius" "Antwerpen" "Aperio" "Api" "Apis" "Apiven" "Apodemus" "Arcata" "ArchivePure"
 "Arenaviridae" "Argonaut" "Argonne" "ArrayIt" "ArrayScan" "Arteriviridae" "Arzneimittel" "AseI"
 "Ashland" "Asians" "Astragali" "Astragalus" "AtRAB" "Atractylodes" "Atractylodis" "Aujezsky"
 "Avicel" "Axioskop" "BALs" "BCPs" "BaEV" "Babinski" "Baizhu" "Banna" "Barcelona" "Barmah"
 "Basidiomycete" "Basler" "Baudette" "Bayes" "Bayesien" "Beckmann" "Beckton" "Becton" "Bedford"
 "Bemisia" "Benjamini" "Bergen" "Bergisch" "Berkeley" "Berne" "Beyotime" "Bialystok" "BigDye"
 "Billerica" "Binh" "Bio" "BioComp" "BioEdit" "BioFocus" "BioLayer" "BioProject" "BioRad"
 "BioSystems" "BioTools" "Bioanalyser" "Bioanalyzer" "Biochem" "Biochrom" "Bioetyki" "BiogenOuest"
 "Biolabs" "Bioline" "Biolyte" "Bioman" "Biomatters" "Biomedicals" "Biopharma" "Bioploymer"
 "Bioresources" "Biosafety" "Biosera" "Biosoft" "Biosystem" "Biosystems" "Biotec" "Biotech"
 "Biotechnologie" "Birbeck" "Bitplane" "BodyMap" "Boehringer" "Bonferonni" "Bonferroni" "Boson"
 "Bouin" "Bovidec" "Boviene" "Bovilis" "Brackney" "Bradford" "Brandeis" "Bratislava"
 "Bratislavskeho" "Brea" "Breda" "Bremen" "Bridger" "Brigham" "Brindley" "Broadwick" "Browser"
 "Bruijn" "Bruker" "Brunn" "Brussels" "Brüttisellen" "Buckinghamshire" "Bukreyev" "Bunge" "Burdur"
 "Burlingame" "Burlington" "Burnie" "Buxue" "CAGpuro" "CAGzeo" "CAstV" "CCSPneg" "CFCs" "CLRs"
 "CNBr" "CPVs" "CVp" "Calibur" "CamR" "CamShift" "Camargue" "Canini" "Canr" "Cantell" "Capo"
 "Cardiología" "Cardiovirus" "Carlo" "Carlsbad" "Carollia" "Carpinteria" "Carros" "Casio"
 "Caucasus" "Ccr" "CellGenix" "CellQuest" "CellScript" "Cellfectin" "Cellgro" "CenterValley"
 "Centrum" "Ceratopogonidae" "Cercopithecine" "Cestrum" "Ceva" "Chadwick" "Chandipura" "ChemGenes"
 "Chemicon" "ChemieTek" "Chendu" "Chironomidae" "Chironomus" "Chlamydomonas" "Chomczynski"
 "Christmas" "Christnings" "Chávez" "Cintiq" "Ciphergen" "Circulifer" "Ciência" "Clara" "ClearPAGE"
 "Cleveland" "Clontech" "ClustalW" "Clínica" "Cn" "Coccidiodes" "CodonW" "Coldamaris" "Coley"
 "Coliphage" "Coloc" "Combo" "Comitè" "Comité" "Comoro" "Consorci" "Coomassie" "Corbas" "Corman"
 "Cornell" "Corp" "Cotesia" "CounterStarTM" "Covaris" "CrPV" "Crandell" "Cretan" "Creutzfeldt"
 "Cripavirus" "Cttarget" "Cuchillo" "Culex" "Culicidae" "Culicinae" "Culicoides" "CxFV" "Cy"
 "CyBio" "Cycler" "Cynwyd" "CytD" "Cytocalsin" "Cytometer" "Cà" "DMVs" "DMcG" "DNAZol" "DPIs"
 "DTUs" "DVGs" "Dako" "Dallas" "Dalli" "Danvers" "Danxi" "Darby" "Dario" "Darmstadt" "Datamonkey"
 "DeRisi" "Deepwater" "Deitch" "Delano" "Delphi" "DengueNet" "Dhrubajyoti" "DiANNA" "DiNapoli"
 "Diaporthe" "Dicistroviridae" "Dickinson" "Dickson" "Diego" "DingGuo" "Dionex" "DreamTaqTM"
 "Dublin" "Dulbecco" "Dusseldorf" "Dynabeads" "Dynavax" "Düsseldorf" "EIDs" "EKGs" "EMBLdB"
 "EMStain" "Eastman" "EasySepTM" "Ebolavirus" "Eccles" "Ectropis" "Edward" "Edwin" "Eisai"
 "Eisenlohr" "Ektachem" "Elan" "Electromyography" "Elga" "Elmer" "Emory" "Empore"
 "Encephalomyocarditis" "Enders" "Entolimob" "EpiBasket" "EpiFlu" "Epizooties" "Eppelheim"
 "Eptesicus" "Eq" "Erlangen" "Erns" "Eskimo" "Eskişehir" "Espirito" "Essentials" "Ethiek" "Ethisch"
 "Ethische" "Euclidean" "Eugene" "Eugenia" "Euprosterna" "Eureka" "Evan" "ExcellairTM" "FACSAria"
 "FACSCalilbur" "FACSCanto" "FIBROSpect" "Fabricius" "Fakultät" "Fangfeng" "Faramount" "FastAP"
 "FeLV" "Felis" "Fermentas" "Ferreira" "Fetet" "FibroTest" "Ficoll" "FigTree" "Finetek" "Finetex"
 "Fisch" "Fischione" "Fleckvieh" "Flowjo" "FluA" "FluCAN" "FluNet" "FluoView" "Forevergen"
 "Fortuna" "Foucras" "Franca" "Frederick" "Freiburg" "Fremont" "Freund" "Fugizone" "Fujikura"
 "Fukuoka" "Fusim" "GBlocks" "GFMs" "GHz" "GMbiolab" "GaLV" "Gaithersburg" "Galab" "Galapagos"
 "Gallen" "Gallid" "Gammacell" "Gamunex" "GelSafe" "Gelcode" "Gelsinger" "GenBank" "GenScript"
 "Genbank" "GeneArt" "GeneJET" "Geneva" "Genome" "GenomeFingerprinter" "Genscript" "Georg" "Getah"
 "Gibco" "Gierer" "Gifhorn" "Gilead" "Gladbach" "Glostrup" "GmbH" "Google" "Gorp" "Gouléako"
 "GraBCas" "Granda" "Greek" "GreeneChip" "Greenland" "Greiner" "Greninger" "Guangdong" "Guangfu"
 "Guba" "Guha" "Guizhou" "HAdV" "HAdVs" "HAstV" "HCPro" "HORs" "Hagan" "Hainan" "Haloarcula"
 "Halobacteriaceae" "Halobacterium" "Haloferax" "Halogeometricum" "Halorubrum" "Hamamatsu"
 "Hamburg" "Hammoudeh" "Hangjinqi" "Hannover" "Hantaan" "Harbin" "Harhaj" "Harris" "Harvard"
 "Harvey" "Hatfield" "Haute" "HeNe" "HeVsG" "HealthMap" "Hebei" "Heidelberg" "Heilongjiang" "Hein"
 "Heine" "Heinrich" "Hematech" "Hematology" "Hemiptera" "Hemispherx" "Hendra" "Hepascore"
 "Hercules" "HiAP" "HiFi" "HiSeq" "Hilden" "Hillsboro" "Himetobi" "HindIII" "Hippocrates"
 "Hirayama" "HisPur" "Histomorphometry" "Hitachi" "Hochberg" "Hoechst" "Holstein" "Horvath"
 "Houston" "Hsiao" "Huangdi" "Huangqi" "Humboldt" "Huntington" "Hydesville" "Hyglos" "Hyogo"
 "HyperD" "Hyphy" "Hyposoter" "Hz" "IAb" "ICs" "IFab" "IIx" "IPLab" "IRESs" "ISFs" "Icahn"
 "Identifier" "Idera" "Ifit" "Ifitm" "IfitmDel" "IgMs" "Ignacio" "Illumina" "ImageJ" "Imaris"
 "ImmunoResearch" "Immunoelectron" "Immunologicals" "Immunoresearch" "Implen" "Indians" "Inertsil"
 "Infetrometry" "Ingelheim" "Ingenasa" "Inpros" "Instituto" "Interferometry" "Internationale"
 "Investigació" "InvivoGen" "Iobs" "Ioff" "Ionic" "Ipswich" "Irvine" "Isomet" "Isparta" "Istituto"
 "Jaap" "Jacob" "Jefferson" "Jembrana" "Jeoung" "Jestin" "JetPei" "Jiangsu" "Jilin" "Jim" "Johann"
 "Jolla" "Jose" "Jotun" "Jules" "Junichiro" "Kal" "Kaleidagraph" "Kamiti" "Kapa" "Kaposi" "Karel"
 "Karen" "Karolinska" "Kasei" "Katja" "Katrin" "Katrina" "Kekarainen" "Klenow" "Kobe" "Kodak"
 "Koidz" "Kolkata" "Komisia" "Komisija" "Komisja" "Konica" "Koninklijke" "Konya" "Kroes" "Kromasil"
 "Kumamoto" "LHDs" "LSVs" "LaSota" "LabTech" "Labtech" "Laemmli" "Lagos" "Lakewood" "Landgraaf"
 "Lassa" "Latin" "Legionnaires" "Leguminosae" "Leibovitz" "Leitz" "Lelystad" "Lemuel" "Lentinula"
 "Lepeophtheirus" "LightCycler" "Likert" "Linux" "Linyi" "Lisheng" "LoFreq" "Lodz" "Lofstrand"
 "Loleta" "Lonza" "Louis" "Lounsbury" "Lousanne" "Lowess" "Lowicryl" "Luminex" "Luna" "Luria"
 "Luteoviridae" "Luteoviruses" "Lutzomyia" "Luxol" "Lörrach" "Lübeck" "MAMPs" "MAstV" "MDDCs"
 "MIDs" "Maastricht" "Macgene" "Macrocephalae" "Madin" "Madrid" "Maedi" "Maela" "MagCore"
 "Magnetom" "Magnus" "Maisch" "Malassez" "Mallinckrodt" "Malvern" "Manassas" "Manetho" "Mannheim"
 "Mansonia" "Maplewood" "Marasco" "Marek" "Maresme" "Margaret" "Marianna" "Marin" "Marklewitz"
 "Markov" "Marseilles" "Mary" "MassHunter" "Masson" "Mastadenovirus" "Mataro" "Materia" "Materials"
 "MaxQuant" "Mayaro" "Mayonette" "Mays" "Mbp" "McCoy" "Mediatech" "Medica" "Medicinsko" "Medisch"
 "Medische" "Meditec" "Medizinischen" "Megascript" "Mekentosj" "Mekjarvik" "Melivenon"
 "Mellansverige" "Mempses" "Mengenilla" "Metamorph" "Methanococcus" "Methanosphaera" "Meunier"
 "Mexicana" "Mfold" "MiSeq" "MicRos" "Michel" "Microsoft" "Microsystems" "Microvirodae"
 "Middelburg" "Middeldorp" "Middlebrook" "Milano" "Mililitre" "Millex" "Millipore" "Miltenyi"
 "MinElute" "Minitab" "Minitel" "Minolta" "Minqin" "Minumum" "Mirus" "Misonix" "Mississauga"
 "Mitovirus" "Mlu" "ModRefiner" "Moloney" "Montanide" "Monte" "Montevideo" "Mounir" "Moyal"
 "Mucobovin" "Mucophysiology" "Mucosiffa" "Muench" "Muscovy" "Myotis" "Myoviridae" "Médicale"
 "NCBIs" "NIref" "NMRDraw" "NMRPipe" "NaBut" "NaOAc" "Nabel" "Nagel" "Nakiwogo" "NanoDropTM"
 "Nanocs" "Nanofectin" "Nanophotometer" "Nanoscale" "Nantes" "Nantou" "Narnaviridae" "Narnavirus"
 "Natricum" "Naya" "Ndumu" "Neelie" "Neosystem" "Neut" "Newbler" "Newcastle" "NheI" "Nicoll"
 "Nidovirales" "Nikon" "Ninoa" "Nipah" "Nizar" "Niño" "Nobel" "Noorden" "Noosaville" "Norma"
 "Norrland" "NovImmune" "Novartis" "Npro" "NucBuster" "Nuñez" "Nyctinomops" "Nycyteris" "OAstV"
 "ODNs" "ORPs" "Ochlerotatus" "Ohashi" "Ohaus" "Ohta" "Oka" "Okinawa" "Okinawan" "Olympus"
 "Oncology" "Oncovir" "Ophthalmies" "Opsona" "Opti" "OptimaTM" "Optiprep" "Orbitrap" "Orcu" "Ordos"
 "Orozyme" "Osaka" "Osterholzer" "Otorhinolaryngology" "Otorhinolounsburgology" "Ourmiavirus"
 "OvLV" "Oxoid" "PBl" "PBu" "PCPs" "PIVs" "PSMs" "Packard" "Paderborn" "Palo" "Pamela"
 "Panyasrivanit" "Parkinson" "Partitiviridae" "Partitiviruses" "Pasteur" "Pastoris" "PathSeq"
 "Peapack" "Pekin" "Pelltobarbitalum" "Pengfei" "Penh" "Penstrep" "Perkin" "PerkinElmer"
 "Personnes" "Pfizer" "Phakopsora" "Pharaoh" "Pharmacia" "Phaser" "Phenomenex" "Phenylarsinoxid"
 "Phenylmethanesulfonylfluoride" "Philadelphia" "Philips" "Phillipsburg" "Phlebotomus" "Photinus"
 "Photoshop" "Phytophthora" "PiSQRD" "Pico" "PicoTip" "PicoTiterPlate" "Piconavirus" "Pingtung"
 "Pioloform" "Pircher" "Piscataway" "Pittsburgh" "Plainfield" "Platycodon" "Plautia" "Pleurisies"
 "Pme" "Podoviridae" "Poehlmann" "Polaris" "Policlinico" "PolyJet" "Polyanhydride" "Polyplus"
 "Ponceau" "Porada" "PostgreSQL" "Postsurvey" "Poutanen" "PrPSc" "PrV" "PregSure" "Première"
 "PrestaShop" "PrimeScript" "Programa" "Promega" "ProteinChip" "ProteinMiner" "Proxeon"
 "Psychodidae" "Pteropus" "Pty" "Puccinia" "Puchheim" "Puerto" "Pulser" "Punta" "PureLink" "Purina"
 "Puteaux" "Putra" "QIAgen" "QIAquick" "QIAsymphony" "QIAxcel" "Qiagen" "Qingke" "Quang" "Quant"
 "Qubit" "Quesada" "QuickTiter" "RFUsample" "RLUs" "RNAiso" "RNaseP" "RNeasy" "Rabensburg"
 "Radiotracers" "Radix" "Rajalahti" "Ramachandran" "Rapitest" "Rasband" "ReWuMoD" "Realtime"
 "Redriffe" "Rees" "Regionala" "Reipert" "Renilla" "Republike" "Resende" "RevertAid" "Rfam"
 "Rhinolophus" "Rhodobacter" "Rhône" "Ribbens" "RiboLock" "Richmond" "Riems" "Riemser" "Riga"
 "RnaViz" "Roche" "Rochester" "Rockford" "Rockhopper" "Rockville" "Rolink" "Rome" "Ronchese"
 "Roswell" "Rotenburg" "Rous" "Rousettus" "SDoH" "SFb" "SIAs" "SIVagm" "SIVmac" "STUbLs"
 "Sacharomyces" "Sakura" "Salisbury" "SameSpot" "Samespot" "Samtools" "Sanford" "Sanger" "Sangon"
 "Sanitari" "Sankura" "Santo" "Saposhnikovia" "Saposhnikoviae" "Sarbassov" "ScYLV" "ScanScope"
 "Scanco" "Schaudien" "Schischk" "SciTools" "ScriptCap" "SeSp" "Selcuk" "Selleck" "Seluanov"
 "Semliki" "Sendai" "Sensys" "Seoul" "Sequencher" "Sequest" "Serotec" "SexAI" "Shaanxi"
 "Shanghanlun" "Shanxi" "Shattuck" "Sheffe" "Shiji" "Shoklo" "Shwartzman" "SigmaSpin" "SignalMap"
 "SignalP" "SilicaTip" "Simister" "Simmerman" "Simplex" "Sinai" "Sindbis" "Sino" "Siphovoridae"
 "Sipuleucel" "Sirius" "Slezak" "Slovenije" "Sluijs" "Sma" "Småland" "Snakehead" "Solna"
 "Somerville" "Southampton" "SouthernBiotech" "Spearman" "SpectraMax" "Spectrophotometer"
 "Spissistilus" "Spotfire" "Spraytec" "Stavanger" "Stegomyia" "StepOnePlus" "Stephanie" "Stephen"
 "Strasbourg" "Streicker" "Strep" "StrepR" "StrepS" "Streptactin" "Stäheli" "Suess" "Sulfolobus"
 "Sulzfeld" "SuperBlock" "SuperScript" "Superdex" "Superscript" "Sydsverige" "Symphogen" "Syncrip"
 "Systat" "Szapiel" "TAstV" "TSEs" "TTSuV" "TaKaRa" "Taab" "Tadarida" "Taichung" "Taira" "Takara"
 "Taken" "Taleris" "Tanganyika" "Tangdu" "Taq" "TaqMan" "Taqman" "TcSP" "Tconv" "Tecan" "Teijaro"
 "Telechem" "Tembusu" "TenBroeck" "Terre" "TetC" "Tetrametylbenzidine" "Theiler" "Themo" "Thermo"
 "Thermofisher" "Thoreen" "Thornwood" "Tianjin" "Tianshi" "Tissuelyser" "Toetsingscommissie"
 "Toledo" "Toro" "Toronto" "Torrance" "Tospovirus" "Totzke" "Toyobo" "Trimarchi" "Trinidad"
 "TruSeq" "Tröster" "TuMV" "Tucson" "Tukey" "Turcz" "Tuusula" "Tween" "Tylonycteris" "Typsin"
 "Ubuntu" "Ultima" "UltraView" "Ultracut" "Ultramark" "Ultratechnecow" "Ultrathin" "Ultrospec"
 "UniProt" "Universitair" "Universiti" "Universität" "Uniwersytetu" "Upjohn" "Uppsala"
 "Uranotaenia" "Urocyon" "Uromyces" "Usutu" "VIIIs" "VRCs" "Valencia" "Vanderven" "Vasseur"
 "Vectashield" "Vectastain" "Velasco" "Venezie" "Venice" "Ver" "VeriKine" "Veros" "Vesiculovirus"
 "Vespertilionidae" "Veterinarians" "Villermé" "Virana" "Virapin" "Virbac" "Virbagen" "Vries"
 "Västsverige" "Véronique" "Waals" "Wacom" "Wald" "Walleye" "Waltham" "Walthan" "Warrington"
 "WaterLOGSY" "Waukesha" "WelGene" "WellMate" "Wellcome" "Wellesley" "Wenrelun" "Wenzel" "Wenzhou"
 "Wesel" "Westbury" "Westchester" "Whataroa" "Wilcoxon" "Wilmanski" "Wilmington" "WizardTM"
 "Woburn" "Worcestershire" "Worthington" "XCorr" "XbaI" "Xcell" "Xho" "Xiamen" "Xtreme"
 "XtremeGENE" "Yangchiroptera" "Yate" "Yeastern" "Yingdaxigui" "Yinpterochiroptera" "Yocon"
 "Yunnan" "ZRank" "Zeiss" "Zeo" "Zetasizer" "Zhejiang" "Zhongahan" "Ziekenhuis" "Zinkernagel"
 "Zooprofilattico" "Zorbax" "Zplotter" "Zurich" "Zymo" "Zymonsan" "Zürich" "aAlso" "aLRT" "aRNA"
 "aVF" "amOR" "antimiR" "bDNA" "bHLHZip" "bIgM" "Babraham" "cIgM" "cKSL" "ceSCC" "chIFITM"
 "chIFITMs" "chemiluminesenceTM" "chimSegmentMin" "dAdG" "dIgA" "dTdA" "dTdT" "danJ" "dbEST"
 "duIFITM" "eHealth" "eMDMs" "emPAI" "gSeV" "Gallus" "gcaagAGGACACACGC" "hChr" "hCycB" "hIGHM"
 "hIGK" "hIGL" "hIgG" "hIgM" "hIgs" "hMGL" "hPEST" "hSLC" "hisDPm" "hmAbs" "hpAbs" "hsDNA"
 "huIFITM" "iNKT" "iScript" "iTRAQ" "jModelTest" "kBq" "kPa" "loxP" "loxPHyg" "luxAB" "mIAP" "mIgA"
 "Mephitis" "mirVana" "moDCs" "nanoLC" "oligoDNA" "oncomiRs" "pBCSP" "pBMSF" "pBluescript"
 "pCAGloxP" "pCMV" "pCSGW" "pEJSSA" "pLysS" "pNA" "pRISe" "pRISeCAGzeo" "pRISeCAGzeoE" "pRedET"
 "pSrc" "pTELCAGzeo" "pTELCAGzeoSLFR" "pTELpuro" "pVRC" "Phosphopeptide" "Pipistrellus" "pknotsRG"
 "pmAYSazeo" "pmAYSpB" "pmAYSpBPml" "polyA" "polydT" "pppRNA" "pppssRNA" "preM" "progressiveMauve"
 "rDVG" "rNDV" "rVV" "Rapalogues" "refGene" "rfbE" "rhMBL" "rpsL" "sRNA" "sRNAs" "sTNFR" "sTva"
 "seedSearchStartLmax" "sfRNA" "tenOever" "theF" "uA" "usingWNV" "vGifhorn" "vRiemser" "vTRV"
 "vanRSP" "vanYP" "varSelRF" "winAnchorMultimapNmax" "Ètica" "Östra" "Övre")))
    :test #'equalp))


(defparameter *FirstNames*
    (remove-duplicates
      (append 
         (when (boundp '*FirstNames*) (symbol-value `*FirstNames*))
         '(
("Alexander" "Antonio" "Bernard" "Brian" "Charles" "Chen" "Cheng" "Claudia" "David" "Davide"
 "Dennis" "Duncan" "FEI" "Feng" "Gary" "Gordon" "James" "Jesse" "Liang" "Megan" "Michael"
 "Mohammad" "Neil" "Olivier" "Ralph" "Richard" "Rui" "Ruth" "Samuel" "Thomas" "Tian" "Tina" "Wayne"
 "William" "Yang" "Zdenek" "Zheng" "Zhong")))
    :test #'equalp))


(defparameter *LastNames*
    (remove-duplicates
      (append 
         (when (boundp '*LastNames*) (symbol-value `*LastNames*))
         '(
("Ajami" "Albrecht" "Alexander" "Alonso" "Althoff" "Annunziato" "Antonio" "Atkins" "Baltimore"
 "Barr" "Bartel" "Bartmess" "Baxter" "Beatty" "Bechmann" "Beckman" "Beigi" "Benjamin" "Berend"
 "Bergmann" "Berkelman" "Bernard" "Berthold" "Beutler" "Bodenteich" "Bohnenkamp" "Bowen" "Buehler"
 "CUA" "Cahill" "Cao" "Capoluongo" "Carl" "Carroll" "Cervantes" "Chan" "Chang" "Chattopadhyay"
 "Chen" "Cheng" "Choi" "Chou" "Chung" "Clark" "Collison" "Corbett" "Corti" "Crocker" "Cruz" "Culp"
 "David" "Decaro" "Derakhshan" "Devergne" "Didier" "Dong" "Dougan" "Drescher" "Du" "Duarte"
 "Dubois" "Duncan" "Dunn" "Eisen" "Engelhardt" "Epstein" "Esmaeili" "Ezzie" "FEI" "Farr" "Feng"
 "Fernebro" "Fink" "Foege" "Forrester" "Fu" "Fujita" "Galea" "Gardner" "Gastaldello" "Gautier"
 "Gern" "Gershon" "Ghorpade" "Gibbs" "Gibson" "Gilbert" "Gordon" "Grassauer" "Graunt" "Greco"
 "Greter" "Guiguen" "Gür" "HA" "Hach" "Hamza" "Hanley" "Hansen" "Henkel" "Herfst" "Hickford"
 "Hidmark" "Hoffmann" "Holmes" "Hu" "Huang" "Ichinohe" "Imai" "Ito" "Iwasaki" "Jackson" "Jaffrey"
 "James" "Jamieson" "Janeway" "Jarjour" "Jefferis" "Johnson" "Judet" "Jung" "Kang" "Kapil" "Kaplan"
 "Kash" "Kayagaki" "Keshet" "Khuth" "Kilbourne" "Kim" "Kirchhoff" "Knott" "Kochanek" "Kondo"
 "Kosai" "Kozak" "Kubota" "Kudva" "Kung" "Kuri" "Lahiry" "Lang" "Langmuir" "Lanzavecchia"
 "Lapointe" "Lavoie" "Liang" "Lincoln" "Lipsitch" "Littmann" "Liu" "Lowry" "Ludwig" "Lugovskoy"
 "Macatonia" "Malakoff" "Mathew" "Matrosovich" "Maus" "McCandless" "McCullers" "McGahie"
 "Medzhitov" "Merck" "Merkel" "Metzger" "Miyake" "Mohsenzadeh" "Moldt" "Moltedo" "Montgomery"
 "Moore" "Moran" "Morens" "Morgan" "Muller" "Murray" "Nakamura" "Nanni" "Napolitani" "Negishi"
 "Neumann" "Niedbala" "Nishi" "Oelmann" "Okuyan" "Olivier" "Olson" "Openshaw" "Osterlund" "Owens"
 "Pagenstecher" "Palacios" "Pearson" "Pepys" "Pfistershammer" "Phares" "Ploix" "Poon" "Potestio"
 "Pulendran" "Ransohoff" "Raska" "Redmond" "Rehg" "Resman" "Rico" "Roderfeld" "Rodriguez" "Rogers"
 "Romagnani" "Ruprecht" "Saito" "Sakaguchi" "Sakakura" "Salemi" "Salio" "Samuel" "Sander" "Santos"
 "Sato" "Savarin" "Sawicki" "Schiller" "Schwartz" "Shackelton" "Shao" "Shen" "Siddell" "Siffrin"
 "Sittisombut" "Soloway" "Sorrell" "Spadaro" "Spibey" "Steinberg" "Steinman" "Stephenson" "Stewart"
 "Stohlman" "Stuart" "Sutherland" "Szostak" "Takahashi" "Takeda" "Tanimoto" "Tasher" "Thacker"
 "Thomas" "Tian" "Trinchieri" "Trono" "Trut" "Tsang" "Tu" "Uehara" "Uyeki" "Vargin" "Varnavski"
 "Verikios" "Viasus" "Viboud" "Vignali" "Volz" "Waldmann" "Walsh" "Welsch" "Whalen" "Whitney"
 "Wille" "Wong" "Woolford" "Worobey" "Wu" "Xiao" "Xu" "Xue" "Yang" "Yao" "Ye" "Yoo" "Yu" "Zaki"
 "Zaman" "Zavitz" "Zayas" "Zhang" "Zhao" "Zheng" "Zhong" "Zhou" "Zhu")))
    :test #'equalp))

;; 3328 defined as a bio-entity


(defparameter BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-2301-2400
    (remove-duplicates
      (append 
         (when (boundp 'BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-2301-2400) (symbol-value `BIO-ENTITY-covid-2020-04-03-0403-COM-PMC-2301-2400))
         '(
("#$DISEASE" "#$DRUG" "#$NUMBER" "#$PERIOD" "#$PLACE" "#$SOMEONE" "#001114" "#02" "#03" "#04" "#05"
 "#15" "#1729" "#1730" "#1731" "#18" "#19" "#2" "#23" "#26" "#29" "#30" "#32" "#9130" "#A4438-01"
 "#CCL7" "#DR-L2785" "$1" "$40 billion" "$500" "$\\end{document}F0+" "$\\end{document}F0−"
 "$\\end{document}F1+" "$\\end{document}F1−" "$\\end{document}SL+" "&&\\displaystyle" "&-M177R"
 "&\\displaystyle" ")/345" ")/42768" ")/acute respiratory distress syndrome" ")/amount" "**" "***"
 "***P" "**P" "*P" "+/−2%" "+/−3%" "+/−gentamicin" "+1" "+2" "+3×MPS" "-1,1-dimethyl-3-"
 "-1,3-dihydro-benzo" "-120°" "-1H-benzo" "-2-aminoethanesulphonic" "-2-phenylethyl"
 "-3,6-dioxaoctane" "-80°" "-AAGCATGAAGGCAGAAGAGAT-3" "-AAGCATGCATTTTCGATTGGA-3"
 "-AATCAGAAGAGGCAGCCATC-3" "-AATCATAATAATTAATAAATG-3" "-ACCGAGTTGAGACATACA-3"
 "-ACGCTTAGCATCACCCAGAAG-3" "-acgggtagaa-3" "-ACGGTGTGCGTGGATGCATCA-3" "-ACTCCTATTGAATTTGCCAGCAA-3"
 "-AGGAAAAGTAGACAGTGTTCAGGCTT-3" "-ATAGCCTTTGACTCCTTTGTCTCC-3" "-ATCCATCACCATTAAACGAA-3"
 "-ATCCCCAGGATGCCTTCTG-3" "-ATCCTTTGTCGTCCCGATACTT-3" "-ATGGTGGTCCGAGCAGAGAT-3"
 "-CAACTCCTACCCGCAAACCA-3" "-CACCACCAGAACCTGTCACCTC-6-carboxytetramethylrhodamine"
 "-CACCTTCGGTATGGCAACTT-3" "-CAGCAAGTTCCATCGTGTCATCAAGG-3" "-CAGGAAGATATCCAGAAGGA-3"
 "-CAGTCAAATGGGCTGATGCA-3" "-CATGGCTTCACTTGTGTTCC-3" "-CCACCACTCATTCTGAGGCA-3"
 "-CCAGAGCCGTCACTTTGCTT-3" "-CCATATGTACCAACGGGAACA-3" "-CCCTCAATTCCGCTGTATCC-3"
 "-CCCTCCTTCACCAGCTTCTTT-3" "-CCTCAGCTAATCGGCTTATAACACT-3" "-CCTGGTATTCGCTCTGATTGC-3"
 "-CCTTCACCAATGACTCCTATGAC-3" "-CCTTGAATACCAGGTCCAGGATA-3" "-CGAAAGTTTATGATCCAGAAC-3"
 "-CGATCTTCTTCACGGTTGCA-3" "-CTGAGTTTAAACGCTAAAAGACAAATTTGCATATACAG-3"
 "-CTGCACATAAACTGCCATTATTCC-3" "-CTTCTCTGGGTTGGCACACA-3" "-FAM-ACAAAGCAGGACAAGCA-MGB-NFQ-3"
 "-GACTGTTTAAACttagaaaaaaTacgggtagaaCgccaccATGGGCGTTACAGGAATATTGCAG-3" "-GCACAGGGTTTTCGCTCAA-3"
 "-GCCATGTTGTCACTGTCTATTG-3" "-GCCCGAGAGAGCAATGGA-3" "-GCCTCGCCAAAAGAGGACT-3"
 "-GCCTGGAGCCCAGATATTCGA-3" "-GCGAATTCTTAGCACAGGGACGCGTAGTCCGGGACGTCGTATGGGTAGGCCTGGCAGCTCT-3"
 "-GCTGCGAGGTCTTCAGACTT-3" "-GCTTCCCTATGGCCCTCATT-3" "-GCTTTTGAGCCTAGCGTT-3"
 "-GGAAGCGCTCACCATAGATGCTC-3" "-GGAATAGAACCGTTAGACAT-3" "-GGAGCTCACGGAGACTTCAACT-3"
 "-GGTGCTAGTTGATATGTAATAAACA-3" "-GTTTCCCAGTCACGATCNNNNNNNNN-3" "-HKU1-S" "-NL-63" "-NL63-S"
 "-nsP1-nsP2-nsP3-nsP4-junction" "-O-methyl-group" "-O-methyltransferase" "-O-Methyltransferase"
 "-O-methyltransferase-deficient" "-OC43-S" "-penta-1,3-dienyl" "-TAATACGACTCACTATAGGG-3"
 "-TAGTCCCTGTTTGTTGCAGG-3" "-TCAGCACCTGCTTCATCCAA-3" "-TCCCATTGTCATTCTCCCAAA-3"
 "-TCTATGCACTTCAGCCACTG-3" "-TGGGACAGCGAGTGATCTTG-3" "-TGGTCATGTGCCGTTACAGG-3" "-to-5"
 "-triphosphate-RNA" "-ttagaaaaaa-3" "-TTTAAAGGAAATCAGTTCTGGGCTATA-3" "-{F}_{0}^{-}" "-{F}_{1}^{-}"
 "-α-d-N-acetylneuraminic acid" ".0 m/mm3" ".1 m/mm3" ".24 m/mm3" ".5 m/mm3" ".6 m/mm3" ".61 m/mm3"
 "0-29GT" "0.05×10E9" "0.1%Tween 20" "0.15μg/g" "0.2×" "0.3~13%" "0.4mg/ml" "0.63}" "0.64}"
 "0.75∼1.81%" "0/0" "0/A" "000/mm3" "03-096A" "05066b" "05:00:00" "07:00-19:00 h" "0̸" "1 H5" "1+"
 "1+\\frac{{N}_{+}^{-}-{N}_{-}^{+}}{{N}^{+}}\\right"
 "1+\\frac{{N}_{-}^{+}-{N}_{+}^{-}}{{N}^{-}}\\right" "1,000-fold" "1,200g" "1,6-bis" "1,8-bis"
 "1-deoxymannojirimycin" "1.42q" "1.5-2x106" "1.5-fold" "1.95×105" "1.9X" "1/106" "1/2" "1/200"
 "1/3" "1/41" "1/7" "10%x" "10,000-fold" "10/10" "10/11" "10/678" "10/group" "100/" "1000rpm"
 "10058-F4" "100°C" "100×" "102.3/G" "102/102" "105/well" "10601-10621-rv-dv4" "10639-10661-rv-dv2"
 "10e5–10e7" "10×" "10−6×g" "11/03" "11/17" "110°C" "112/133" "118/203" "11c"
 "12-O-Tertadecanoylphorbol-13-Acetate" "12/126" "120/213" "12A12" "12pt" "13,200×g" "132B10"
 "132D7" "133/213" "135/" "1368GPRLQPY1374" "13C6" "14/16" "145/42768" "149/174" "14A7" "14CEN-F"
 "14CEN-R" "14pi" "150xg" "150×0.075" "15N2" "15N4" "15°" "16,000×" "16-18g" "16/16" "16/925"
 "165bp" "166,000/mm3" "17.8-fold" "1709-1/2007" "174/465" "1782-247aa" "17Cl1" "17Clone1"
 "181/mm3" "19/40" "1995/96" "19:00-07:00 h" "1:100-diluted" "1:40-diluted" "1a-b" "1A." "1A6"
 "1A8" "1beta" "1c–d" "1E–G" "1H11" "1H2O" "1LG7" "1RZ1" "1x106" "1~4" "1°" "1°C/second" "1×"
 "1×10-1" "1×101" "1×102" "1×103" "1×104" "1×105" "1×106" "1×107" "1×108" "1×LPS" "1∶2∶1"
 "1≤u≤20z1" "1≤u≤20z2" "1≤u≤20⋮z441" "2$\\end{document}N+−=N−" "2$\\end{document}N−+=N+" "2+"
 "2,000-fold" "2-chloro-4-fluorophenyl" "2-Gb" "2-hydroxyethyl" "2-N-morpholino" "2-to-3-week-old"
 "2-ylidene" "2-ΔΔCT" "2-△△Ct" "2.06×101" "2.2v-1" "2.4-fold" "2.5%/97.5%" "2.55E10" "2.5mg/kg"
 "2.5×105" "2.63×103" "2/176" "2/20" "2/6" "2/7" "2/9" "20%∼90%" "20/1025" "20/20" "200.000xg"
 "2000c" "2001a" "2001b" "2001c" "2001d" "2003/10" "2003/100/EC" "2005a" "2005b" "2008a" "2008b"
 "2009-September" "2009/10" "200×" "200×0.075" "2012_01" "2012_08" "2012a" "2012b" "20\\\\" "20C2"
 "20mg/kg" "20°C" "20×" "21/30" "21≤u≤39" "21≤u≤39z2" "21≤u≤39⋮z441" "22.7 ± 2.0°C" "229E/NL63"
 "229ENC_002645" "22°C" "23+" "23/102,22.54%" "2439/3096" "24°C." "250×4.60" "2526/3096" "25°C"
 "2622+220" "28/31" "28/708" "28pi" "28°C" "29/31" "293FT" "2a-V" "2B." "2BC" "2C." "2C10" "2F5"
 "2FQM" "2G12" "2G9" "2H2O" "2U/µ" "2×" "2×104" "2×106" "2×107" "2ΔlnL" "2−Δ"
 "3,3′-diaminobenzidine" "3-Chloro-5-" "3.36%∼36.42%" "3.5-fold" "3/4" "3/5" "3/6" "3/7" "3/group"
 "30+" "30,500xg" "30/70%" "300SB-C18" "300×109/litre" "30°C" "30°C." "31/126" "320×320" "325°C"
 "33.99%±7.51" "333/544" "336/mm3" "3378…6431" "33°–35°C" "33–35°C" "35°C" "35°C." "37.5°C" "37/40"
 "373XL" "37°" "37°C" "37°C." "38.36%±7.39" "38.5 ± 0.2°C" "380/708" "39.7°C" "39\\\\" "3B."
 "3BNC117" "3Citrate" "3D11" "3HHW" "3xFLAG" "3×106" "3∼4" "4,000-fold" "4,5-dimethylthiazol-2-yl"
 "4,6-diamidino-2-phenylindole" "4-methoxy-2-methylphenyl" "4-methylumbelliferyl" "4-tosylamido"
 "4.0c" "4.6×250" "4.6×50" "4/20" "400x" "400×g" "404/mm3" "407/mm3" "40~70%" "40°C" "40×" "40μl"
 "40–50°C" "410EQKLISEEDLLRKRREQLKHKLEQLRNS437" "42°C" "458/mm3" "45°C" "498/mm3" "4A-F" "4D–F"
 "4E10" "4G2" "4HOQ" "4Peaks" "4°" "4°C" "4°C." "4×" "4×105" "5,000/well" "5,7-dihydroxyflavones"
 "5-6x105" "5-GARAGAAGATTCTTCAGRGA-3" "5-O-methylvisammioside" "5.0-fold" "5.27×1011" "5/10" "5/2"
 "5/6" "5/7" "5/9" "500μl" "50°C" "50×" "51°C" "51≤" "531/572" "542/42768" "553-R3" "55°C" "56°C"
 "56°C." "57°C" "58°C" "59°C" "5A1" "5A2" "5B2" "5C2" "5E3" "5H10" "5H7" "5½" "5×103" "5×104"
 "5×105" "5×109/litre" "5∙106" "6-diamidino-2-phenylindole" "6-phosphogluconolactone" "6.3±1.0"
 "6.4-fold" "6/20" "6/7" "60%+" "600 m/z" "60°" "60°C" "60–80°C." "6102/7496" "61°C" "61°C."
 "63/70" "63x" "63×" "640/1,340" "647-NP396–404H2-DbTetramers" "64°C" "65°C" "664/702" "68/741"
 "68°C" "6A-D" "6F12" "6H12" "6K2" "6K2:mCherry" "6K2:mCherry//GFP-HDEL" "6K2mCherry//GFP-HDEL"
 "6×" "6×106" "7-aminoactinomycin" "7-Hydroxy-3H-phenoxazin-3-one" "7.5-fold" "70/30" "70/466"
 "700×g" "702/708" "70°C." "70×75" "72°C" "72°C." "742…3378" "748YSNIGVCK755" "764LQDGQVKI771"
 "79/444" "7900HT" "7A5-1" "7AAD" "7H11" "7SK" "7SK-as" "8.4-fold" "8.54×103" "8/10" "8/20"
 "80%/20%" "80.77±0.06°C" "80/2596" "800g" "80i" "80°C" "80μg/g" "81.20±0.17°C" "83/126" "83p-5"
 "83p-5-100" "84FLi" "84°C" "88–177aa" "8C1" "8nt" "8x106" "9,100×g" "90/95" "90°" "90°C" "95/"
 "95°C" "96-like" "96™" "97-like" "971/447861" "98°C" "99.5°F" "99mTc" "9×104" "<0.0001" "<0.001"
 "<0.01" "<0.05" "<0.1" "<0.8" "<1" "<1%" "<1,500/mm3" "<1.0" "<10" "<10%" "<100" "<100×109" "<104"
 "<14" "<15" "<150,000/mm3" "<1500%" "<150×109/litre" "<20" "<200" "<25" "<2…355" "<3 s" "<35%"
 "<3…>6566" "<4,000/mm3" "<5" "<50" "<500%" "<500/mm3" "<5000" "<50×109" "<5×109/litre" "<6 s"
 "<85,000/mm3" "<names" "=1.2pc" "=1.5pc" "=19.0 ±3.9%" "=1−N−+N++N+−N−1+N+−−N−+N+1+N−+−N+−N−"
 "=\\sqrt{\\sum" "=Aedes" "=∑u=1Ω" "=∑u=1Ωψu−ψ¯u−2" ">0.5" ">0.75" ">0.8" ">0.90" ">1" ">10" ">100"
 ">100-fold" ">1000" ">1000 fold" ">100×109" ">104.2" ">106" ">107copies/g" ">15" ">150" ">1500"
 ">1540" ">1:20" ">2" ">20" ">20%" ">200" ">23,000" ">25" ">25%" ">3 s" ">300" ">300×109/litre"
 ">38°C" ">4" ">40" ">5" ">50" ">50 µ" ">50%" ">50×109" ">5×109/litre" ">6 s" ">65" ">70%" ">75%"
 ">80%" ">90%" ">95%" ">96%" ">97%" ">99.9%" ">D" "\\\\" "\\begin{array}{@{}cccc@{}}"
 "\\begin{array}{@{}cccccc@{}}" "\\begin{array}{@{}cccccccc@{}}" "\\begin{array}{@{}l@{}}"
 "\\begin{document}" "\\ddots" "\\displaystyle" "\\documentclass" "\\end{array}\\right"
 "\\end{eqnarray*}\\end{document}D" "\\end{eqnarray*}\\end{document}D10=AA"
 "\\end{eqnarray*}\\end{document}P+=ψ¯1+ψ¯2+…ψ¯u+…ψ¯Ω+TP−=ψ¯1−ψ¯2−…ψ¯u−…ψ¯Ω−T"
 "\\end{eqnarray*}\\end{document}P=R1R2…R9R10R11R12…R20R21"
 "\\end{eqnarray*}\\end{document}P=R−ξR−" "\\end{eqnarray*}\\end{document}P=ψ1ψ2…ψu…ψΩT"
 "\\end{eqnarray*}\\end{document}P∈SNO" "\\end{eqnarray*}\\end{document}SL=SL+∪SL−"
 "\\end{eqnarray*}\\end{document}Sn=1−N−+N+Sp=1−N+−N−Acc=1−N−++N+−N++N−MCC"
 "\\end{eqnarray*}\\end{document}Sn=79.6%Sp=84.1%Acc=81.7%MCC"
 "\\end{eqnarray*}\\end{document}Sn=85.2%Sp=79.0%Acc=81.8%MCC"
 "\\end{eqnarray*}\\end{document}Sn=TPTP+FNSp=TNTN+FPAcc=TP"
 "\\end{eqnarray*}\\end{document}ST=ST+∪ST−"
 "\\end{eqnarray*}\\end{document}Z0=z1,10z1,20…z1,200z2,10z2,20…z2,200⋮⋮⋱⋮z441,10z441,20…z441,200"
 "\\end{eqnarray*}\\end{document}Z1=z1,11z1,21…z1,191z2,11z2,21…z2,191⋮⋮⋱⋮z441,11z441,21…z441,191"
 "\\end{eqnarray*}\\end{document}Z=Z0⊕Z1=z1,10z1,20…z1,200z1,11z1,21…z1,191z2,10z2,20…z2,200z2,11z2,21…z2,191⋮⋮⋱⋮⋮⋮⋱⋮z441,10z441,20…z441,200z441,11z441,21…z441,191"
 "\\end{eqnarray*}\\end{document}zi" "\\end{eqnarray*}\\end{document}ψu=z1"
 "\\end{eqnarray*}\\end{document}ψ¯u+=1N+∑k=1N+ψu"
 "\\frac{{N}_{-}^{+}}{{N}_{+}}+\\frac{{N}_{+}^{-}}{{N}^{-}}\\right" "\\gt" "\\hspace{5.5pc}"
 "\\ldots" "\\left" "\\left\\{\\begin{array}{@{}l@{}}" "\\left\\{\\extrarowheight" "\\mathbb{D}"
 "\\mathbb{Z}={\\mathbb{Z}}^{0}\\oplus" "\\mathbf{P}" "\\mathbf{P}={\\left"
 "\\mathbf{P}={\\mathrm{R}}_{-\\xi" "\\mathbf{P}={\\mathrm{R}}_{1}{\\mathrm{R}}_{2}\\ldots"
 "\\mathbf{P}\\in" "\\Omega" "\\quad" "\\setlength{\\oddsidemargin}{-69pt}"
 "\\text{Acc}=1-\\frac{{N}_{-}^{+}+{N}_{+}^{-}}{{N}^{+}+{N}^{-}}\\\\" "\\text{Acc}=81.7\\"
 "\\text{Acc}=81.8\\" "\\text{Acc}=\\frac{\\text{TP" "\\text{FN}" "\\text{FP}\\times" "\\text{if"
 "\\text{MCC" "\\text{MCC}=\\frac{" "\\text{non-SNO" "\\text{otherwise" "\\text{otherwise}"
 "\\text{SNO" "\\text{Sn}=1-\\frac{{N}_{-}^{+}}{{N}^{+}}\\\\" "\\text{Sn}=79.6\\"
 "\\text{Sn}=85.2\\" "\\text{Sn}=\\frac{\\text{TP}}{\\text{TP}+\\text{FN}}\\\\"
 "\\text{Sp}=1-\\frac{{N}_{+}^{-}}{{N}^{-}}\\\\" "\\text{Sp}=79.0\\" "\\text{Sp}=84.1\\"
 "\\text{Sp}=\\frac{\\text{TN}}{\\text{TN}+\\text{FP}}\\\\" "\\text{TN}" "\\text{TP}\\times"
 "\\text{when" "\\usepackage{amsbsy}" "\\usepackage{amsfonts}" "\\usepackage{amsmath}"
 "\\usepackage{amssymb}" "\\usepackage{mathrsfs}" "\\usepackage{upgreek}" "\\usepackage{wasysym}"
 "\\vdots" "\\xi" "]/ml" "^{2}}\\\\" "_{k=1}^{{N}^{+}}\\psi" "_{k=1}^{{N}^{-}}\\psi" "_{u"
 "_{u=1}^{\\Omega" "A-overhang" "A-site" "A-tailed" "A.D" "A.W." "A/A" "A/Anas" "A/B" "A/C" "A/D"
 "A/G" "A/H1N1" "A/H1N1pdm" "A/J" "A/Muscovy" "A/mute" "A/O" "A/S" "A/Viet" "A/whistling"
 "A/whooper" "A10432G" "A10436T" "A10438T" "A10440T" "A10665G" "A1417T" "A190-108F" "A260/A280"
 "A3C" "A3H" "A3S" "A549s" "A7209T" "A91A96MBP87-99" "A91MBP83-99" "A:B" "A_AAU_UUU" "AA1478"
 "AA155" "AA428" "aa499-638" "aa499–638" "AAAGGGCTATAAAGAGAATAAGGTATTCT-3" "AACV+CBPV"
 "AAGE02000678" "AAGGTCGGAGTCAACGGATT3" "AAPT01020539" "ab11591" "ab117513" "ab128193" "AB1488P"
 "ab16077" "ab1870" "ab20921" "ab25630" "ab2618" "ab32412" "ab33053" "ab40875" "ab41632" "ab41912"
 "ab53049" "ab62472" "ab62884" "ab6640" "ab72187" "ab96871" "ab96882" "abc/6" "ABD2"
 "abdominal/pleural effusion" "AC104134" "AC20" "acetonitrile/water"
 "ACTCGTTAATACGACTCACTATAGGGAGCCATCAGGCCAGTTCCATTG-3"
 "ACTCGTTAATACGACTCACTATAGGGAGGCACCGCATGTTTCCATTCT-3" "activation--either" "ACU65077.1"
 "acute/chronic" "AD-N1" "AD-N2" "AD-N3" "AD/BD" "adaptation/customisation" "adenosine-uridine"
 "advisor/advocate" "AF033822" "AF488-conjugated" "AFS88936" "Ag/FIV" "agent3" "Agilent®" "AGL1"
 "Agl1" "AGTCCGGGACGTCGTATGGGTAGGTCTGAAGGAC-3" "AGTTGGAGGA-CATCAAGCAGCCATGCAAAT" "AG|GT" "AH1"
 "Aichi" "Aichi2" "AJ1102" "AJ491720" "AJVK01006534" "AJWK01014410" "Akv-MuLV" "AL-118"
 "alcohol/ethanol" "aldosterone/MR" "ALI/ARDS" "align2d" "ALN-RSV01" "AM1-BCC" "AMBER99SB"
 "amino acid/nucleotide" "AMPV-9" "ANA773" "ANA975" "Anhui" "Anti-apolipoprotein J"
 "anti-apoptotic" "anti-autophagy" "anti-bacterial" "Anti-BDCA-2" "anti-BDV" "anti-bIgκ"
 "anti-bIgλ" "anti-biotin" "anti-chicken" "anti-CIRE" "anti-Clec9A" "anti-coagulated"
 "anti-CSFV/BVDV" "Anti-DC-ASGPR" "Anti-DC-SIGN" "Anti-DCIR" "Anti-Dectin-1" "Anti-Dectin-2"
 "anti-DNGR-1" "Anti-DNGR-1" "anti-dsRNA" "anti-DV-NS1" "anti-DV2-NS1" "Anti-Env" "Anti-FcRn"
 "anti-fibrotic" "Anti-FIRE" "anti-FIRE" "Anti-FLAG" "Anti-gp41" "Anti-GST" "Anti-HA"
 "anti-hepatotoxic" "anti-hIgG" "anti-hIgG1" "anti-hIgG2" "anti-hIgM" "anti-hIgκ" "anti-hIgλ"
 "anti-hlgλ" "anti-human" "anti-I-A" "anti-inflammation" "anti-inflammatory" "Anti-influenza"
 "anti-inﬂammatory" "Anti-Langerin" "Anti-LOX-1" "anti-miR-150" "anti-miRNA" "anti-miRNAs"
 "anti-mouse" "anti-nausea" "anti-NLDC-145" "Anti-nsp12" "anti-pestivirus" "anti-phosphor-IRF3"
 "anti-phosphor-NF-κB p65" "anti-proSP-C" "anti-pSrc" "anti-rabbit" "anti-rat" "anti-retroviral"
 "anti-rhesus" "anti-S" "anti-S." "anti-sheep" "anti-T." "anti-tumor" "anti-tussive" "anti-ulcer"
 "Anti-USP25" "anti-viral" "antibodies/antigens" "antisense#1" "antisense#2" "AO/OO" "AP-177"
 "AP000350" "AP000553" "AP124P" "AP132P" "AP1802a" "AP61" "APMV-2-like" "APMV-3-like" "APMV3"
 "APMV7" "apolipo-protein" "apoptosis/necrosis" "Arg-1" "arm/elbow" "ARVO™" "as-yet"
 "Asn-Gln-Trp-Ala-Val-Gly-His-Leu-Met" "assay25" "assays2021" "AST/ALT" "at25" "ATCC®"
 "ATCGTCAGAGGCATTTTTAA-3" "Atg14-like" "ATGTTGTGTTAGGCTTGTTG-3" "ATHL1" "AtRAB-F2b" "Atu027"
 "at−80°C" "autophagosome-like" "Avertin®" "Avicel™" "AY017064.1" "AY259122.1" "AY274504"
 "AY597011" "AY898809" "A↔G" "B.01.00" "B.04" "B.C." "B.M." "B2CT" "B2RA" "B4GALNT4"
 "B6.129-Ifnb1tm1Lky" "B6S2-S3" "B6S3" "backbone-RMSD" "Baculo-Gold" "Bal-tec" "Batxelli-Molina"
 "BCQ+" "BD-N1" "BD-N2" "BD-N3" "BD/AD" "BDCA-3+" "BeauR-hRluc-Δ5a" "before…" "Bermejo-Martin"
 "beta1,3" "beta1,6-linked" "BHK21" "bIGHM-/-" "bIGHML1-/-" "bIgk" "bIgα/Igβ" "bIgκ" "bIgλ"
 "Bio-rad" "Bio-Rad" "Bivas-Benita" "BLM+NS" "BLM+SP" "BM8" "BML-SA250" "Bo17" "BoHV-4" "BORF2"
 "Born/Surface Area" "BPLF1" "Br1/87" "breath/difficulty" "Brisbane" "BSL-2" "BSL-4" "BSL106-06"
 "BV/TV" "Bx51" "BX63" "BY4741" "BZ-9000" "BZLF1" "C-dv4-start-fw" "C-dv4-start-rv"
 "c-Myc/inhibitor" "C-strain_T7_Not1" "C.A.M" "C.B.S." "C/T" "C068C2" "C1000™" "C10435T" "C3-PI3K"
 "C3H/HeJ" "C3S" "C46H6" "C57BL/10ScCr" "C57BL/6" "C57BL/6J" "C57BL6" "C57BL6j" "C6/36" "CA-630"
 "CAAGTTTACAGCCAAGATTCA-3" "CaCl2" "CACTAACAGGCGTGTTGTAA-3" "CACTACCAGGTGCCTTTTGT3"
 "CACTCCTGCCCTTCCTCACC3" "CAG-lox2272-polyA-bsr" "CAG-lox511-polyA-hisD" "CAGpuro-F3R3"
 "Calbiochem-Merck4Biosciences" "calycosin-7-O-β-D-glucoside" "calycosin-7-β-D-glucoside"
 "Camp-Paulson" "CamR/TetR" "cancer stem cell-like" "CAP0-RNA" "CaPSID/RINS" "CARD-like"
 "case/control" "Cat#" "Caveola-like" "Caveolae-like" "caveolin-1-/-" "caveolin-1and" "CAY39406"
 "CBLB502" "CBPV-like" "CC50" "CC50/EC50" "CC50>100 µ" "CCA-VUMC"
 "CCACTAGTTAATACGACTCACTATAGGGACCAGACAAGAGTTTAAGAG-3" "CCATAGCGGAGGTGAATATC-3" "CCL-185" "CCL-81"
 "CCL-94™" "CCSPpos" "CCSPpos/CD34pos" "CD103+" "CD11+" "CD11b+" "CD11c+" "CD11c-PE-Cy7"
 "CD138+CD19lowCD45Rlow" "CD14+CD34+" "CD1a/CD11c+" "Cd2+" "CD20+IgD+CD27+" "CD20+IgD−CD27+"
 "CD209b" "CD25+foxp3+" "CD27+IgD+" "CD28+CD95+" "CD28−CD95+" "CD3+" "CD34+" "CD34neg/CCSPpos"
 "CD34pos" "CD3ε+CD8α+GP33+" "CD3ε+CD8α+NP396+" "CD4+CD25+" "CD4+CD25+Foxp3+" "CD4+CD39+"
 "CD4+CD39+CD25−Tregs" "CD4+Foxp3+" "CD4+IFNγ+" "CD4+T" "CD4+Vbeta6+" "CD4/total" "CD44+" "CD45hi"
 "CD8+CTLA-4+" "CD8+IFNγ+" "CD8α" "CD8β" "CD8−CD4−" "CDPH-VRDL" "CDR-H1" "CDR-H2" "CDR-H3" "CDR-L1"
 "CDRH3" "cell adhesion molecule 1a" "Cell/Tissue" "cells /mL" "cells/dish" "cells/dose"
 "cells/hour" "cells/L" "cells/ml" "cells/mm3" "cells/well" "cells/μl" "cells27" "cells3738"
 "CFT073" "CFU/ml" "CFX96" "cgi-bin" "cGy/minute" "CH/S" "CH2D" "CH2D4" "CH65" "chain40" "CHGD-01"
 "CHGD-1" "CHIAP34" "chicken0020serum" "chicken_GAPDH" "chicken_IFITM3" "chIFITM1" "chIFITM2"
 "chIFITM3" "chIFITM5" "child-year" "Chin-inmanu" "chloroform/isoamyl" "chr17" "chromosomes/two"
 "chronic granulomatous disease-like" "chronic/mature" "Ci/mmol" "cIAP1/2" "CIISA/" "CiTV1"
 "cKSL-HACΔ" "cKSL-HACΔ/DKO" "cKSLD22" "cKSLDH22" "CL097" "class II+" "CLB-Cag117"
 "clinical trials2" "CLL-1" "Clone13" "CM10" "cn:8080" "CND0335" "CND0364" "CND0366" "CND0415"
 "CND0545" "CND1611" "CND3514" "co-enzyme" "coiled-coil" "collagen-like" "Collu-Hextril"
 "complement C3d" "complex-FcRn" "complex/Dectin-1" "control/mean" "copies/g" "copies/ml"
 "copies/mL" "copies/mol" "copies/µ" "copies/μl" "copy/paste" "cos138" "count/clinical" "CPG10101"
 "CPMP/" "CPV-15" "CPV-2a" "CPV-2b" "CPV-2c" "CPV-39" "CPV-JS2" "CPV-JS60" "CPV-JS63" "CPV2a"
 "CPV2b" "CPV2c" "CPZ50 µ" "Cre/LoxP" "Criems-TAVfor" "Criems-TAVrev"
 "Criems_E2_gifF/Criems_E2_gifR" "Criems_E2_gifFlong/Criems_E2_gifRlong" "Crimean-Congo"
 "Crimean–Congo" "CRIP1" "CRL4A" "Cs137" "CSFV_Not1" "Cstrain_T7_Not1" "CT-VX765"
 "CTCCTGGAAGATGGTGATGG3" "CTCTTAAACTCTTGTCTGGTCCCTATAGTGAGTCGTATTAACTAGTGG-3" "CTGAPDH–CTgene"
 "CTGATTCTGGACAGTTGTTA-3" "CTTCGAGACATCTTTGACAA-3" "Cu4A" "cut/disrupted" "CV5RL" "CV6LL" "CV6LU"
 "CV777" "CVA16" "CVB3" "CVS-11" "CY014671" "CY028163" "CY098760" "Cy2-conjugated" "Cy3/Cy5"
 "Cybi-Well" "Cynomolgus/Rhesus" "Cytofix/Cytoperm" "Cα" "Cβ" "Cκ" "D-cutoff" "D20=AC" "D30=AD"
 "D4400=ZY" "D4410=ZZ" "dA:dT" "Dahm-Daphi" "Dana-Farber" "Data-Analysis&" "day1" "DBI865"
 "DC-ASGPR" "dead!" "Dectin-1+" "dehydrogenase/reductase" "delivery—DharmFECT" "delta-amino"
 "Delta-Delta" "DEN2" "Den3" "DENV4" "DENV4-H241" "Desorption/Ionization"
 "Desorption/Ionization-Time" "DExD/H" "DH10B cells" "DH5α" "DHF/DSS" "Di0|j" "Di1|j" "dIgA1"
 "dIgA2" "dIgA2HGN194" "dish/well" "Di|j" "dk/services/SignalP/" "DLV34" "DM6000" "dN/dS"
 "DNA damage/repair" "dnaJ homolog subfamily B member 11-like" "DNAJC14/RP11" "DNGR-1" "domain43"
 "DQ288927" "drift-time" "drug-like" "DS2" "DSP2a" "dT15" "duIFITM2" "duIFITM3" "during/after"
 "DV1" "DV2" "DV2+3MA" "DV2+Rapa" "DV2-6685-6709-fw" "DV2-6685-6709-rv" "DV4" "DV4-6671-6698-fw"
 "DVG-546" "E-dv4-end-fw" "E-dv4-end-rv" "E-dv4-start-fw" "E-dv4-start-rv" "E-G2163A" "E-T1442C."
 "E-utilities" "E-value" "E.coli" "E.d" "E1-like" "E1690-random-dv4-rv" "E1A" "E2-like" "E4orf3"
 "E6/7" "E6/well" "E600POL" "earlier2144" "EASY-nanoLC" "Ebi3−/−" "EBNA1/2" "Ebstein-Barr" "EC50"
 "EDTA-K2" "edu/fastx_toolkit" "edu/mauve/" "EEC" "EGFP+" "EIAVDLV34" "EIAVLN40" "EID50" "eIF2·GDP"
 "eIF2·GTP" "eIF2·GTP·Met·tRNAMET" "EIR1" "EL406" "Elite/3000" "ELR1" "embryonic stem cell-like"
 "EndoGrade®" "endosomal-like" "endosomal/lysosomal" "ENSGALG00000004239" "ENSGALG00000006478"
 "ENSGALG00000020497" "enterovirus/rhinovirus" "ephrin receptor/G" "epidemiology/surveillance"
 "Eq8D11C1" "equal-molar" "equivalents/mL" "ER/Golgi" "erythrocytes39" "ESA+"
 "estimated/calculated" "Ethik-Kommission" "EU/national" "EU352767" "Europe2020" "EV71"
 "EVL/European" "EX-F1" "excitation/emission" "existence/extension" "extraction/purification"
 "EZ920122" "EZ922704" "EZ941741" "EZ958863" "EZ959541" "F.J.M" "F/HN" "F10100-R10630" "F3x4"
 "F4/80+" "F4/80+CD11c+CD206+" "F4/80+CD11c-CD206-" "F4/80-like" "Fab/G-protein" "FACSCalibur™"
 "Factor 1γ" "FAO-OIE" "FAO/OIE" "farm/stables" "farming/fruit" "Fasta_format"
 "fastq_quality_filter" "fastq_quality_trimmer" "FASTX-Toolkit" "FB12" "Fc-BC" "FC500" "Fcs-5B"
 "Fcs-BC" "FcαlphaR1" "FcαlphaRI" "Fcγ-HRP" "FcγammaRIII" "FcγIII/II" "FCγRIIB" "FcεpsilonRII"
 "fgl2+/+" "fgl2+/+and" "fgl2+/+mice" "Fgl2−/−" "fgl2−/−" "fibrinogen-like" "Ficoll-Hypaque"
 "Ficoll-Paque™" "FJND-3" "flaviviral-like" "flavivirus-like" "floxed-Zeo" "flu-like" "FluMist®"
 "FLUOR®" "FMV-UTL" "foci/field" "for1-DE" "four-times" "Foxp3+" "FP×FN" "frog-leg" "FT/F1"
 "FTSJD2" "full-time" "FV1000" "Fx23" "Fx34" "Fx4" "Fx44" "Fx45" "Fx48" "Fx5" "g/cat" "g/kg" "g/L"
 "g/liter" "g/ml" "g/µ" "g/μl" "G10447T" "G186V." "G3S" "G_GAA_AAC_uaa" "G_GAA_AAC_uga" "G_GGA_AAC"
 "G_GUA_AAC" "ga-pol" "GACGGTCCGCTGCAACTG-3" "GACI01002802" "GACM01002912" "GAIR01011807"
 "GAIR01012025" "GAIR01012062" "GAIS01005902" "galactose/N-acetylgalactosamine" "gamma-globulin"
 "gamma-interferon" "GC3S" "GCAAGTGCTCCAATCTTGCA-3" "GCCCC-3" "GCGUGUGUCCU-3" "gene4" "gene5a"
 "genes/loci" "genome/μl" "genomes/μl" "Georg-August-Universität" "GFP-ABD2-GFP"
 "GFP-sELR1- -expressing" "GG-3" "GGACGTGGAGAACAGTCATC3" "GGATGCAGGGATGATGTTC-3"
 "GGCAGGACAATGTGCAAGAA-3" "GGGCCTCTCTTTCCAAAACAC-3" "ghs2" "GI:13095578" "GI:260063801"
 "GI:9626953" "GIBCO-Invitrogen" "Giemsa-stained" "GL533" "Glas-Col" "Go!" "gov/" "gov/Blast"
 "gov/genbank/" "gov/Genbank/" "gov/genome/" "GP33–41 H2-Db" "gp350/220" "gp45" "Gray-Owen"
 "GRCh37" "group1" "gsh1" "GSJIII" "GST-N1" "GST-N2" "GST-N3" "GST-P+Strep-G" "GST-P+Strep-M"
 "GST-P+Strep-N" "GTP/GDP" "GTR+G" "GU391" "Guiyang" "Gvin1" "Gö6976" "Gβ" "H&E" "H&E." "H+"
 "H+-ATPase" "H-2d" "H-2Db-restricted" "H.E." "H/L" "H00007356-M01" "H1/H3" "H1/Kentucky" "H10N1"
 "H11N9" "H12N5" "H13N6" "H14N5" "H15N9" "H16N2" "H1N1pdm" "H1N2" "H2-Db" "H2-Kb-binding" "H2DCF"
 "H2N2" "H2N3" "H2O" "H37Rv" "H3N2v" "H3N8" "H5-H7" "H5-HPAI" "H5-mCl2.2" "H5-positive"
 "H5N2/Mexico" "H5N3" "H6N1" "H7/human" "H7/Human" "H7/teal" "H7/Teal" "H7N1" "H7N2" "H7N3" "H7N7"
 "H7N9" "H7Nx" "H8N4" "H9N2" "H_sapiens" "hACE2" "half-time" "hand-foot-and-mouth"
 "Hand-foot-and-mouth" "HB2151" "hCAND1" "hCGbeta+" "hChr14" "hChr2" "hChr22" "HCV229E" "hCμ-FR"
 "HDV-fw-dv2" "HDV-fw-dv4" "Heavy/light" "heavy/light" "HEC-1A" "HEC1-1A" "heIF2α"
 "Heilongjiang-SYXK-2006-032" "HeLa-USU-ephrin-B2" "HeLa-USU-ephrin-B3" "helix-loop-helix" "HER2+"
 "HERV-K/HML-2" "HERV-K10" "HERVK11DI" "HERVK11I" "HERVK13I" "HERVK22I" "HERVK3I" "HERVK9I"
 "HERVKC4" "HF16" "hg19" "HGN194" "hIgG/bIgκ" "hIgG/hIgκ" "hIgG/hlgλ" "hIgG1" "hIgG1/hIgG2" "hIgG2"
 "highCD11c+" "hIGLL1" "hIgκ" "hIgλ" "HIP12467" "his3∆1" "hisDpurolox2272" "hisDpurolox2272F9R9"
 "HIV-1gag" "HIV-1HT593" "HIV-1HT599" "HIV-1JR-FL" "HIV-1JRFL" "HIV-1JRLF" "HIV-1US657"
 "HIV-1US712" "HIV1" "HIVUS657" "HJ16" "HKCI-5" "HKD08" "HKL2000" "HKU-39849" "HKU1NC_006577"
 "HLA-A2" "HLA-DRB1*0701/*1501" "HLA-DRB1*1501" "HLJHG" "HM20" "HM623779" "host-like"
 "host/pathogen" "HP643964" "HPAI H5N1viruses" "hPIV3" "HPM010" "HPM100" "HPRS-103" "HPV-16"
 "HTK888" "HTLV-I" "http://app" "http://blast" "http://cbr" "http://codonw" "http://dbsno"
 "http://en" "http://gel" "http://hiv" "http://ictvonline" "http://mpi-inf" "http://pfam"
 "http://rdp" "http://res" "http://rfam" "http://tree" "http://tubic" "http://www" "Huh7"
 "huIFITM1" "huIFITM10" "huIFITM2" "huIFITM2/3" "huIFITM3" "huIFITM5"
 "human immunodeficiency virus/acquired" "human-like" "Hung-Yao" "hVPREB1" "hVPREB1/hIGLL1" "HXB2"
 "HxN9" "hyg-loxP" "hygiene/cough" "hygpurolox511DT" "Hygro" "Hα" "i-iii" "I-Swa" "I-TASSER" "i-th"
 "I.D." "I/II" "I/Sma" "I:C" "I:C12U" "i=1,2,\\ldots" "i=1,2,…,441;j=1,2,…,19"
 "i=1,2,…,441;j=1,2,…,20" "IBV5" "IC50∼6 µ" "IC50∼7 µ" "IC90" "icarapin-like" "ice/ethanol" "ICH/"
 "ID-24" "ID-Δ13" "ID/g" "ID21bd-07" "ID28bd-07" "IDN5" "iDV2" "Ifi205b" "Ifit1+/+" "Ifit1c"
 "Ifit1−/−" "IFITM-like" "IFITM1-like" "IFITM10" "IFITM2/3" "Ifitm3-/-" "Ifitm3-deficient"
 "IFITM3-like" "Ifitm6" "Ifitm7" "IFN-alpha/beta" "IFN-α/β" "Ifnar-/-" "Ifnar1−/−" "Ifngr-/-"
 "IFNγ+" "IFNγ−/−" "IgA2" "IgG1PE" "IgG2c" "IgG3" "IGHA1*01" "IGHA2*01" "IgM+" "IgM+/CD21+" "Igλ"
 "IL-12a−/−" "IL-15β-R" "IL-35+" "immunized/infected" "ImmunoComb®" "immunoglobulin-like"
 "IMO-2125" "inclusion/exclusion" "inflammatory cells/field" "influenza-like"
 "influenza-like-illness" "information/evidence" "Ingelvac®" "insertion/deletion" "Inspect3D"
 "insulin-glargine" "insult/infection" "intention-to-treat-population" "inter-day" "interleukin 1β"
 "Interleukin 1β" "internal-ribosome-entry-site" "intra-" "intra-abdomen" "intra-abdominal"
 "intra-assay" "intra-cassette" "intra-cytosolic" "intra-day" "intra-genotypic" "intra-host"
 "intra-lesional" "intra-species" "Iobs/" "Ioff–Ion" "IPA3" "IPA3-pretreated" "iQ5"
 "ischemia/reperfusion" "ISF-like" "iSNAO-PseAAPair" "iSNO-AAPair" "iSNO-PseAAC" "ISRE-1" "iTr35"
 "IU/cat" "IU/kg" "IU/mL" "IVA-12" "J.C.F.M.D." "J.D." "J.T.Baker" "J00220" "J00221" "J01998"
 "J09-11" "j0=F0+" "j1=F1+" "J774E" "j=1,2,\\ldots" "JCRB0403" "jelly-roll-fold" "Jiangxi" "JM109"
 "Johnson®" "JP089782" "JP306102" "JSM-6300" "June–October" "JX073928" "j}^{0}={F}_{0}^{+}"
 "j}^{1}={F}_{1}^{+}" "K+channel" "k+ψ¯u−=1N−∑k=1N−ψu" "K-fold" "K2HPO4" "K3Fe" "K3PO4" "K48-Ub2-7"
 "K562-mb15-41BBL" "K63-Ub2-7" "KA183058" "kappa-light-chain-enhancer" "Kbp∼4" "KC556927"
 "kcal/mol" "KF298264" "KF298265" "KF298266" "KF298267" "KF298268" "KF298269" "KF298270" "KF298271"
 "KF298273" "KF298274" "KF298275" "KF298276" "KF298277" "KF298278" "KF298284" "Kg/L" "KH2PO4"
 "KHCO3" "kilo-∼5" "Kishino-Hasegawa" "KK4604" "KLRL1" "km/h" "km2" "KO2" "Kolmogorov-Smirnov"
 "Kolmogorov-Smirnov-Test" "Krijnse-Locker" "Kruskal-Wallis" "Kukavica-Ibrulj" "Kunitachi" "Kwon3D"
 "k}^{+}$\\end{document}ψu" "k}^{+}\\\\" "k}^{-}" "k}^{-}$\\end{document}ψu" "L-1-"
 "L-lactide-co-glycolic acid" "L/min" "L/min·m2" "L12Q" "L=250" "Lab-Tech™" "lambda5" "LC16mO"
 "LC3II" "lead-time" "lectin-like" "Lennard-Jones" "lente-insulin" "LEP100" "let-7d" "leu2∆0"
 "Level-4" "level/correct" "linkages35" "Lipofectinamine2000" "lipophilicity/hydrophilicity"
 "liposome-LexLeB" "LJB/03" "LLCMK2" "LNA-antimiR" "LNA-antimiRs" "LOC408666" "LOC422993"
 "LOC770612" "log10" "loop1" "loop2" "loop3" "Louis-René" "lox2272" "lox511" "LPS+MPS" "LSM510"
 "LSV-like" "LSV1" "LTQ-Orbitrap" "Luc2" "luc2P" "Luc2P" "lucR-E-" "Lumi-Light" "Ly-5" "Ly49a"
 "Ly6C" "Ly6C-FITC" "Ly6Chi" "Ly6Clo" "Ly6G-CD11b+" "M-dv4-start-fw" "M-dv4-start-rv" "M.14.25"
 "M.16.4" "M.H.V." "M.O.I." "M.O.M" "m/z" "M1-like" "M1/70" "m101–m107" "m102.1-8" "m102.3"
 "m102.3/4" "m102.3/G protein" "m102.4" "M13rev" "M14626.1" "M1a" "M2-like" "M2a"
 "m7Gppp-oligoribonucleotides" "m=∑i=mnCMiCN−Mn−iCNn" "mAb/G" "Macherey-Nagel" "macrophage-like"
 "macropinocytosis-like" "Madin-Darby" "Man9GlcNAc2" "Manalpha-6" "mannan-MUC1" "Mantel-Haenszel"
 "Mantel-Haenzel" "March–May" "match/mismatch" "Match/Mismatch" "May–October" "MCA4466Z"
 "mCEACAM1a" "mcg/mL" "means±S.E.M." "mean±SEM" "mechanism/s" "MEM/EBSS" "member 11-like"
 "MERS-like" "MessageAmp™" "met15∆0" "metallo-protease" "methanol/acetone" "Met·tRNAMET" "mg/day"
 "mg/dL" "mg/g" "mg/kg" "mg/L" "mg/ml" "MGL+" "mGyday-1" "MHOM" "MHV-59" "MHV-68"
 "microglia/macrophages" "Microsoft®" "micrOTOF-Q" "Microtubule-associated protein 1A/1B"
 "mid-1990s" "mid-2000s" "mid-year" "midE-dv4-1587-1610-fw" "midE-dv4-1587-1610-rv" "mIfit1"
 "mIfit1c" "mIfit2" "mIfit3" "mIFN-β" "Milliplex®" "MILLIPLEX®MAP" "min30" "miR-1274a" "miR-146a"
 "miR-34a" "mitovirus-like" "mixture/4" "mL/10" "ml/animal" "ml/min" "mL/well" "MM/PBSA" "mm/s"
 "MMHAR-2" "mmol/L" "mmol/l" "mmol/L." "mm×4.6" "Mn+2" "Mn/Fe" "Mn3+" "MnCl2-4H2O" "MNG3" "MOI=100"
 "mol/L" "mono-" "mono-antibody" "monocyte/macrophage" "mouth/nose" "MR+" "MRJP8" "MSBVN1210"
 "MTS510" "MU/kg" "mU/ml" "mV/cm" "MVB/PVCs" "MVP5180" "MW/WN06" "MZ-like" "M×3000ptm" "MβCD"
 "MΦP9" "MΦs" "N+" "N-acetylgiucosamine" "N-hydroxylsuccinimide" "N.V." "N9/human" "N9/teal" "n=1"
 "n=10" "n=125" "n=2" "n=4" "n=5" "n=6" "n=8" "Na2CO3" "Na2EDTA" "Na2S2O3" "NaCO3"
 "NAD(P)H:quinone oxidoreductase" "NADPH/NADP+" "NaH2PO4" "Nanjing08-1" "narna-like"
 "narnavirus-like" "NC_000858" "NC_000943" "NC_001278" "NC_001362" "NC_001408" "NC_001413"
 "NC_001414" "NC_001437" "NC_001449" "NC_001463" "NC_001477" "NC_001494" "NC_001511" "NC_001512"
 "NC_001514" "NC_001544" "NC_001547" "NC_001550" "NC_001655" "NC_001722" "NC_001786" "NC_001906"
 "NC_002306" "NC_002469" "NC_002470" "NC_002532" "NC_002534" "NC_002607" "NC_002607_RC" "NC_002645"
 "NC_002686" "NC_002728" "NC_003045" "NC_003092" "NC_003215" "NC_003417" "NC_003433" "NC_003436"
 "NC_003782" "NC_003790" "NC_003899" "NC_003900" "NC_003908" "NC_003930" "NC_004162" "NC_004455"
 "NC_004579" "NC_004718" "NC_004915" "NC_005147" "NC_006551" "NC_006558" "NC_007447" "NC_009942"
 "NC_009996" "NC_010364" "NC_010436" "NC_012561" "NC_012802" "NC_013114" "NC_013202" "NC_014729"
 "net/" "Netherland" "ng/reaction" "ng/well" "ng/µ" "ng/μl" "NH4HCO3" "NI-0101" "NIG56-RV1"
 "Nigeria/95" "NIH45-46" "Ninoa" "NIoff/Iref" "nl/min" "NL63NC_005831" "NLDC-145" "NM_008361"
 "NM_013693" "NM_031168" "no-antibody" "no-go" "NOD-like" "non-" "non-alcohol-based" "non-BNP"
 "non-CAP" "non-coding" "non-communicable" "non-compliance" "Non-consensus" "non-COPD" "non-CpG"
 "non-DNase" "non-eligible" "non-enveloped" "non-expanding" "non-fat" "non-fatal"
 "non-FcRn-dependent" "non-governmental" "non-H5" "non-HIV-1-specific" "non-hospitalised"
 "non-human" "non-identical" "non-immunoglobulin" "non-inclusion" "non-infected" "non-infectious"
 "non-influenza" "non-invasive" "non-inversion" "non-neutralizing" "Non-normally" "non-overlapping"
 "non-paired" "non-parametric" "non-pharmaceutical" "non-pharmacological" "non-pneumonia"
 "non-primate" "non-professional" "non-PrPSc" "non-public" "non-random" "non-real time"
 "non-redundant" "non-representative" "non-reservoir" "non-responders" "non-response" "non-SARS"
 "non-scrapie" "non-self" "non-severe" "non-significant" "non-silent" "non-smokers" "non-SNO"
 "non-specific" "non-statistical" "non-target" "non-TLR" "non-toxic" "non-toxin" "non-toxins"
 "non-transfected" "non-venom" "non-viral" "non-zero" "Nonidet-P40" "November–February" "NO．"
 "NP_653247" "NPI/CE" "NR_0215885" "NS1-dv4-end-fw" "NS1-dv4-end-rv" "NS2A-dv4-end-fw"
 "NS2A-dv4-end-rw" "NS2A/2B" "NS2A/2B." "NS2B" "NS3-dv4-end-fw" "NS3-dv4-end-rv" "NS3-dv4-start-fw"
 "NS3-dv4-start-rv" "NS4A-2K-dv4-end-fw" "NS4A-2K-dv4-end-rv" "NS4A-A6761G" "NS4A-A85T"
 "NS4B-A7558T" "NS4B-S215C." "NS4B7016" "NS5-A10149G" "NS5-A9060G" "NS5-dv4-end-fw"
 "NS5-dv4-end-rv" "NS5-dv4-start-fw" "NS5-dv4-start-rv" "NS5-T10142C" "NS5-T10144C" "NSP1β" "nu/nu"
 "Nunc-Maxisorp" "NY-ESO-1" "NY-ESO-1-anti-DEC-205" "NY-ESO-1-antiMR" "NΔI" "NΔI/ΔI"
 "o-phenylenediamine•2HCl" "O.D.A600" "O.D.A600=0.6" "O/N" "O111:B4" "obstetrics/gynecology"
 "OC43/HKU1" "OC43NC_005147" "occasionally…" "occurrence/frequency" "OD260" "OD450" "OD600" "OD620"
 "OH-r" "OIE-559" "OIE-FAO" "OIE559" "ON+" "on/off" "one-quarter" "One-year-old" "only21" "OptEIA™"
 "Opti-MEM1" "orbivirus-like" "ORF10" "ORF1b" "ORF22" "ORF31" "ORF62/71" "ORF7" "org/"
 "org/Gallus_gallus/" "org/index" "org/iSNO-AAPair/" "org/virusTaxonomy" "OsO4" "osteo-like"
 "osteon-like" "OTI/OTII" "out-of-hours" "OVA+" "oxidized-LDL" "P+" "p-arm" "p-carboxyphenoxy"
 "P-class" "P-GFMs" "P-R" "P-site" "p-value" "P-value" "p-value<0.0001" "p-values" "P-values"
 "P.D." "P.J.M.R." "P.K." "P/Q" "p14CEN" "p24/well" "P3N-PIPO" "P3U1" "p3xFLAG-CMV"
 "p553CAGlox2272bsrDT" "p553loxPHyg" "P6c" "P6c-BN" "P6c-PbK" "P6cPbK" "p<" "P<0.0001" "P<0.001"
 "p<0.01" "P<0.05" "p=" "p=0.009" "p=0.018" "p=0.023" "p=0.038" "p=0.443" "Pam3CSK4"
 "Pam3CSK4-induced" "pandemic/seasonal" "pandemic36" "panels/consensus" "PaO2" "PaO2/FiO2" "PAP004"
 "parasites/mL" "parent/legal" "Parrinello-Rahamn" "partial-thromboplastin" "partitivirus-like"
 "pBCSSP4" "pBCμAY37-95" "pBCμAY37-95was" "pBeloBAC11" "pBeloR26" "pBeloR26_E2gif"
 "pBeloR26_E2rpsLneo" "pBeloR26_TAV" "PbGFP-LUCCON" "pBIN" "pBMSF7C" "pBMSF7C-mCl2.2" "PBS-Hoechst"
 "PBS/0.5%BSA" "PBS/2" "pCAGGS-HA" "pCAGGS-HA-USP25" "pCAGGS-MCS" "pCAGGS-Myc" "pCAGGS-Myc-USP25"
 "pCAGlox511hisD" "pCAGloxP2272bsr" "pCambiaTuMV" "pCambiaTuMV/6K2:mCherry"
 "pCambiaTuMV/6K2:mCherry//GFP-HDEL" "PCaP1" "pCDNA-REN-NT-GW" "pcDNA3.1" "pCH1CAGzeo" "pCH1S"
 "pCH1SL" "pCH1SSP" "pCH1zeo" "pCH2CAGzeo" "pCH2CAGzeoDT" "pCH2LS" "pCH2S" "pCI-neo" "pCMV-Δ8.91"
 "PCV2" "pdm09" "pDsRed2-N1" "PE-Cy7" "peaks/proteins" "pEF-Flag-RIG-I-N" "PEMV-1" "penicilin/mL"
 "penicillin/streptomycin" "PepMap100" "peptide-MHC" "Peptide/Protein" "peptide}"
 "percent-transcytosed:percent-infectious" "PerCP-Cy5" "Perkin-Elmer" "person-days" "pET33b"
 "pETG10A-GW" "PF-04878691" "pfu/cell" "pfu/mL" "pfu/mouse" "PfUCH54" "pG1546" "PG9" "pGADT7"
 "pGBKT7" "pGEX-4T3" "pGFP-N3" "pGHL6" "pGL4.32" "pGP67" "pH6.8" "pH7-8" "pH7.0" "pH7.5" "pH=7.4"
 "pHA-H3" "pHA-H7" "phages/two" "pHCF2loxPHyg" "phenol/chloroform" "phi-x174" "phi-X174"
 "Phipps-Yonas" "phlebovirus-like" "PHP5" "PHP5-based" "phRL-TK" "pHygPurolox511" "picorna-like"
 "PiSQRD—an" "pISRE-Luc" "Pit-Oct-Unc" "PIV3" "pi≥m|N" "PK15" "PKR-like" "PLA2-like" "plague…"
 "plant-virus-like" "plants/construct" "plasma/serum" "pLenti-GFP-Luc" "Ploufragan/Plouzané"
 "PLU03982" "PLV-14" "pMD18-T" "pNF-κB-Luc" "PO4/pH" "points/day" "Poisson-Boltzmann" "poly-ICLC"
 "Poly-ICLC" "Polyuria/polidipsia" "polyuria/polydipsia" "Polη" "positive/negative" "post-hoc"
 "pp-NT" "pp1a/pp1b" "PP1c" "PPP-r" "PPP-RNA" "pPURlox2272" "pPURlox511" "PRDIII-I" "pre-cast"
 "pre-DCs" "precipitation/inactivation" "PregSure®BVD" "presence/absence" "previously2021"
 "previously202122" "previously24" "Prieschl-Grassauer" "prim-O-glucosylcimifugin" "primates4"
 "Primer3" "primer3plus" "primers/Taqman" "Primescript®" "PRJEB4441" "PRJEB4561" "PRJNA206059"
 "PRJNA216100" "prM-dv4-start-fw" "prM-dv4-start-rv" "prM550" "prM847" "pRNR2loxPbsr"
 "pRNR2loxPbsrDT" "PRNT50" "PRNT90" "pro-caspase" "pro-pol" "probability-proportional-to-size"
 "Probe/ROX" "probes/primers" "ProFluor®" "progenitor-like" "proSP-C" "protein 1H" "protein A+G"
 "protein IκBα" "ProteinChip®" "proton-ATPases" "PROWESS-SHOCK" "pSC355CAGlox511hisDDT"
 "pSC355F3R3" "pSIN-BNHA" "pSL1180" "psPAX2" "pSVV-BAC" "PT/INR" "PT3247-1" "pTELCAGzeoSLF2R2"
 "pTRV1" "pTRV2" "Pu/Pd" "pUC19" "pVP2-VP4-VP3" "pVP2-VP4-VP3-frame" "pVRC8304" "pYFP-RAB-F2b"
 "pγ1HC" "pκLC" "P–M" "P≤0.05" "Q500MC" "QH1A" "Qiagen®" "QIAquick®" "Qinghai" "QQQ-MS"
 "QT00996415" "Quantum286" "questions>" "R&D" "R+ξ" "R-E-" "R/K" "r/min" "R30K" "R91A96MBP87-99"
 "R=" "RAB-E1d" "rad27a" "Rag1−/−" "rAPMV-2" "rAPMV-3" "rAPMV-4" "rAPMV-4/Fc-BC" "rAPMV-7"
 "rAPMV-7/Fcs-5B" "rAPMV/4Fc-BC" "rAPMV2" "rAPMV7/Fcs-5B" "rAPVM-2" "RD-like" "RDKY3590"
 "Real-Time" "receptor/mAb" "receptors41" "receptors42" "Red/ET" "redα" "redβ" "redγ" "refseq_rna"
 "region-C-E3-E2-6k-E1-poly" "Reichert-Jung" "Renografin-76" "Reprosil-Pur"
 "resistance/susceptibility" "respectively2124" "rFeIFN-ω" "RFUCC100" "rhabdovirus-like"
 "Riems_TAV_Gifhorn" "RIG-I-like" "RIG-like" "risk-factor" "rL-EBOVGP" "rLa-EBOVGP"
 "rLa-EBOVGP-infected" "rLa-ZEBOVGP" "RLU/mL" "RMgm-28" "rN-based" "RNA2" "RNeasy®"
 "Rodriguez-Madoz" "RosetteSep™" "rota/coronavirus" "RP0115c" "RP11-22M5" "RP11-316G9"
 "RP11-417P24" "rpm/15" "RPMI/5%" "rps11:27207" "rpsL-neo" "RRKKR↓F" "RRKKR↓FI" "rRNA28S_3674"
 "RRQKR↓F" "RRRRR↓F" "rRT-PCR" "rs12252" "rs3888188" "rs3888188-G" "RSCUij=Xij1ni∑j=1niXij"
 "RT/Platinum" "RTK2758" "RTK4174" "RTK4530" "RT‑PCR" "RT‑PCR/LDR" "run_pknotsRG" "RuRu+1=AA"
 "RuRu+1=AC" "RuRu+1=ZZ" "RuRu+2=AA" "RuRu+2=AC" "RuRu+2=ZZ" "RV16" "RV1B" "RVV-Flu" "Rξ" "R↓"
 "S-GFMs" "S.A." "S/B" "S/S" "S/TEM" "S1-1L" "S1-1U" "S1-2U" "S1-L2" "S1/S2" "S1C" "S1D" "S2-L1"
 "S2A" "S2a" "S2A." "S2B" "S2b" "S2B." "S2c" "S2C." "S3C" "S3C." "S3D–F" "S3G" "S3H" "S4b" "S4C"
 "S4D" "S4E" "S5A" "S5C" "S6A" "S6C" "S6D" "SA-OMVV" "saline–PBS" "SARS-like" "sc-11427" "sc-21757"
 "sc-28262" "sc-47778" "sc-500" "sc-53094" "sc-56979" "sc-7157" "sc-8036" "SC355-F3" "SC355-R3"
 "SDF-1α" "SDS/PAGE" "seasonal/pandemic" "sELR1" "sense#1" "sense#2" "SensiFAST™" "Seogu-Dong"
 "sepsis/septic" "sepsis1" "Ser32/36" "SG09/92" "SG11/06" "SG11/10" "SH-like" "Shapiro-Wilks"
 "Shapiro–Wilk" "Shimane" "SHIV1157ipEL-p" "shock-like" "short/medium" "SHRiMP2" "SHRT-PCR" "SHT75"
 "sHyal2" "sialosides30313233" "SIAs23" "SIAs24" "SIEVE™" "SIGN-R1" "SIGN-R2" "SIGN-R3" "SIGN-R4"
 "SIGN-R5" "signal/background" "siRNA-lipoplex" "sites25" "Six-day-old" "six-week-old" "SJC1200"
 "SK431" "SK462" "SL-F2" "SL-R2" "sleeve/arm" "SLK2" "SLKD18" "SLKH6" "slt-1" "SM98" "SMRV-H"
 "SNAP®" "societal/individual" "SP-Cneg" "SP-Cneg/CCSPpos" "space-time" "SPARTA+"
 "specific-protein" "SpFV1" "spherule-like" "srcdb_refseq" "SS6" "Start_analyze" "STDobs/STDmax"
 "steady-state" "stem cell/" "stem cells/progenitors" "stem/progenitor" "stem1" "stem2"
 "Stetler-Stevenson" "STL54" "strain/species" "Street…" "Strep-G" "Strep-M" "Strep-N" "Strep-P"
 "Strep-P+GST-P" "Strep-tag" "Streptactin-coated" "streptomycin/mL" "sub-Saharan" "substitution42"
 "sub‑tropical" "sucrose-MBS" "sucrose-MBS-" "Sud-Méditerranée" "suffice13" "Supermix-UDG" "SV40PA"
 "SVVΔORF61" "SW/WN03" "SW41" "Swiss-Prot" "Synagis/Palivizumab" "SΔ16" "SΔ19" "S∆16" "S∆19" "T&A"
 "T-helper" "T-like" "T2-weighted" "T2.5" "T3S" "Takano-Murakami" "target/decoy" "TB1Lu" "TCID50"
 "TCID50/100" "TCID50/cell" "TCID50/ml" "TCID50/mouse" "TCID50/reaction" "TCRβ−/−" "TCRδ−/−"
 "TcSSP4" "technote_phixcontrolv3" "tet+CD8+ T cells" "tetravirus-like" "TGAGG3" "TGBp3" "TGG-3"
 "Th1-like" "Th17" "Th22" "Theiler’s-like" "thiazol-4-carboxamide" "three-quarters" "Ti4+-IMAC"
 "Tick‑borne" "TIM3+G" "TIM3+I+G" "TIMP-1−/−" "TIMP1−/−" "TIP4P-EW" "tissues282930" "TLR-7/8"
 "TLR2/1" "TLR2/6" "TLR7/8" "TMEV-like" "TMPRSS-2" "TMPRSS-4" "TNTP+TN+FP+FNMCC="
 "TN}}{\\text{TP}+\\text{TN}+\\text{FP}+\\text{FN}}\\\\" "Toft-Hansen" "tools/processes" "Top10"
 "TOPO®" "TPM2uf+I+G" "TP×TN" "TRAF2/6" "trans-sialidase" "transcription-polymerase"
 "transition/transversion" "transmitted/founder" "TritonX-100" "TrypLE™" "trypsin-like"
 "trypsin/EDTA" "TS100" "TTC-3" "TTGGACAGCATCCAAAGACA-3" "TTSuV1" "TTSuV2" "TURBO™" "tw/"
 "Tween-20" "Two-fold" "two-week" "txid10239" "txid81077" "txid9606" "Type-1" "U.K." "U/L" "U/l"
 "U/ml" "u/µ" "U/μL" "u0when" "u1when" "U21603" "U2900" "U51113" "u=1,2,\\ldots" "u=1,2,…,Ω"
 "u\\leq" "U_CCU_UUU" "U_UUU_UUA" "UC-230" "UC-330" "UC2" "UGUUUUGC-3" "uk/"
 "uk/dicks/software/RAT/" "uk/mouseportal/" "uk/projects/fastqc/" "uk/Software/Rfam/"
 "uk/Tools/msa/clustalw2/" "UL-803" "uncapped/unmethylated" "Unit/plate" "units/well"
 "untransfected/uninfected" "ura3∆0" "US$490.80" "US$99.26" "USP25m" "UT189" "UTR2SQ" "utr_dp"
 "UUU_CGU" "UV/Visible" "u}^{0}&\\displaystyle" "u}^{1}&\\displaystyle" "U↔C" "V-rescale"
 "V.10.2.2.2317" "V.M.D." "v/v" "v/w" "V136R154Q171" "V2.0" "V5-HIS" "V=π" "vacuoles/lysosomes"
 "Vacutainer®" "vaginal/ectocervical" "varicella-like" "Verify3D" "VeriKine-HS™" "Version17"
 "version=2012" "vesicle-membrane-protein-associated" "vice-versa" "Victor3" "VIDISCA-454"
 "viral/bacterial" "virus-Alfuy" "Virus-Like" "Virus/Bacteria" "virus313334" "VN1194" "vol/vol"
 "VP2" "VP4N-X" "VR-2126™" "vR26" "vR26/P-12" "vR26/P-4" "vR26_E2gif" "vR26_E2gif/P-12"
 "vR26_E2gif/P-4" "vR26_TAV" "VRC-CH31" "VRC-PG04" "VRC01" "VX-765" "Vγ1+" "Vγ4+" "w/v"
 "Wain-Hobson" "washer/dispenser" "Watson-Crick" "WB103/105" "WB166" "week…" "weight/total"
 "West Nile virus-Kunjin" "WH211" "WH303" "WHO-EUR" "Wilcoxon-Mann–Whitney-U" "withdrawn/discarded"
 "WN02" "Wolcott-Rallison" "WSN/33" "wt/vol" "wx2" "X-axis" "X-OMAT" "x100" "x108" "X31" "X3400"
 "X4/R5" "X52374" "X63-GM-CSF" "X74312.1" "X87335" "XI-2" "XI-F" "XI-K" "Xigris®" "XL10"
 "XM_001233949.3" "XM_420925.4" "xn∼n" "xn∼yn" "xn∼zn" "Y-axis" "Y.G" "Y.N" "Y/X" "Y2H"
 "Y91MBP83-99" "Yat-sen" "YC29" "yes/no" "YFP+" "yn∼n" "yn∼zn" "YuanPingHao-bio" "Yucaipa"
 "YVAD-CHO" "Z-axis" "Zhejiang-08" "ZNF48" "zn∼n" "zone-like" "Zostavax®" "ZVAD-FMK" "{\\bar"
 "{\\mathbb{P}}^{+}" "{\\mathbb{P}}^{+}={\\left" "{\\mathbb{P}}^{-}" "{\\mathbb{P}}^{-}={\\left"
 "{\\mathbb{S}}_{\\mathrm{L}}={\\mathbb{S}}_{\\mathrm{L}}^{+}\\cup"
 "{\\mathbb{S}}_{\\mathrm{L}}^{-}&&\\displaystyle"
 "{\\mathbb{S}}_{\\mathrm{T}}={\\mathbb{S}}_{\\mathrm{T}}^{+}\\cup"
 "{\\mathbb{S}}_{\\mathrm{T}}^{-}&&\\displaystyle" "{\\mathbb{Z}}^{0}=\\left"
 "{\\mathbb{Z}}^{1}=\\left" "{\\mathrm{D}}_{1}^{0}=\\mathrm{AA}"
 "{\\mathrm{D}}_{2}^{0}=\\mathrm{AC}" "{\\mathrm{D}}_{3}^{0}=\\mathrm{AD}"
 "{\\mathrm{D}}_{440}^{0}=\\mathrm{ZY}" "{\\mathrm{D}}_{441}^{0}=\\mathrm{ZZ}"
 "{\\mathrm{D}}_{i}\\vert" "{\\mathrm{D}}_{i}^{0}\\vert" "{\\mathrm{D}}_{i}^{1}\\vert"
 "{\\mathrm{R}}_{+"
 "{\\mathrm{R}}_{-2}{\\mathrm{R}}_{-1}\\mathbf{C}~{\\mathrm{R}}_{+1}{\\mathrm{R}}_{+2}\\ldots"
 "{\\mathrm{R}}_{20}{\\mathrm{R}}_{21}&&\\displaystyle"
 "{\\mathrm{R}}_{9}{\\mathrm{R}}_{10}{\\mathrm{R}}_{11}{\\mathrm{R}}_{12}\\ldots" "{\\psi"
 "{minimal}" "{z}_{1" "{z}_{1,19}^{1}\\\\" "{z}_{1,1}^{0}&\\displaystyle"
 "{z}_hbb{S}}_{\\mathrm{L}}^{+}\\cup" "{\\mathbb{S}}_{\\mathrm{L}}^{-}&&\\displaystyle" "{\\mathbb{S}}_{\\mathrm{T}}={\\mathbb{S}}_{\\mathrm{T}}^{+}\\cup" "{\\mathbb{S}}_{\\mathrm{T}}^{-}&&\\displaystyle" "{\\mathbb{Z}}^{0}=\\left" "{\\mathbb{Z}}^{1}=\\left" "{\\mathrm{D}}_{1}^{0}=\\mathrm{AA}" "{\\mathrm{D}}_{2}^{0}=\\mathrm{AC}" "{\\mathrm{D}}_{3}^{0}=\\mathrm{AD}" "{\\mathrm{D}}_{440}^{0}=\\mathrm{ZY}" "{\\mathrm{D}}_{441}^{0}=\\mathrm{ZZ}" "{\\mathrm{D}}_{i}\\vert" "{\\mathrm{D}}_{i}^{0}\\vert" "{\\mathrm{D}}_{i}^{1}\\vert" "{\\mathrm{R}}_{+" "{\\mathrm{R}}_{-2}{\\mathrm{R}}_{-1}\\mathbf{C}~{\\mathrm{R}}_{+1}{\\mathrm{R}}_{+2}\\ldots" "{\\mathrm{R}}_{20}{\\mathrm{R}}_{21}&&\\displaystyle" "{\\mathrm{R}}_{9}{\\mathrm{R}}_{10}{\\mathrm{R}}_{11}{\\mathrm{R}}_{12}\\ldots" "{\\psi" "{minimal}" "{z}_{1" "{z}_{1,19}^{1}\\\\" "{z}_{1,1}^{0}&\\displaystyle" "{z}_{1,1}^{1}&\\displaystyle" "{z}_{1,20}^{0}&\\displaystyle" "{z}_{1,20}^{0}\\\\" "{z}_{1,2}^{0}&\\displaystyle" "{z}_{1,2}^{1}&\\displaystyle" "{z}_{2" "{z}_{2,19}^{1}\\\\" "{z}_{2,1}^{0}&\\displaystyle" "{z}_{2,1}^{1}&\\displaystyle" "{z}_{2,20}^{0}&\\displaystyle" "{z}_{2,20}^{0}\\\\" "{z}_{2,2}^{0}&\\displaystyle" "{z}_{2,2}^{1}&\\displaystyle" "{z}_{441" "{z}_{441,19}^{1}" "{z}_{441,1}^{0}&\\displaystyle" "{z}_{441,1}^{1}&\\displaystyle" "{z}_{441,20}^{0}" "{z}_{441,20}^{0}&\\displaystyle" "{z}_{441,2}^{0}&\\displaystyle" "{z}_{441,2}^{1}&\\displaystyle" "{z}_{i" "}&&\\displaystyle" "}1\\leq" "}21\\leq" "}=\\frac{1-\\left" "}\\\\" "}\\ldots" "}\\mathbb{D}" "}^{+}" "}^{-}" "}^{2}}\\" "}^{\\mathbf{T}}&&\\displaystyle" "}^{T}" "}^{T}\\\\" "}_{1}&\\displaystyle" "}_{2}&\\displaystyle" "}_{\\Omega" "}_{u" "}_{u}&\\displaystyle" "}_{u}-{\\bar" "}_{u}=\\left\\{\\begin{array}{@{}ll@{}}" "}{\\left" "}{\\mathrm{R}}_{+\\xi" "}{\\mathrm{R}}_{-" "}{\\mathrm{R}}_{u}{\\mathrm{R}}_{u+1}=\\mathrm{AA}\\text{" "}{\\mathrm{R}}_{u}{\\mathrm{R}}_{u+1}=\\mathrm{AC}\\text{" "}{\\mathrm{R}}_{u}{\\mathrm{R}}_{u+1}=\\mathrm{ZZ}\\text{" "}{\\mathrm{R}}_{u}{\\mathrm{R}}_{u+2}=\\mathrm{AA}\\text{" "}{\\mathrm{R}}_{u}{\\mathrm{R}}_{u+2}=\\mathrm{AC}\\text{" "}{\\mathrm{R}}_{u}{\\mathrm{R}}_{u+2}=\\mathrm{ZZ}\\text{" "}{\\sqrt{\\left" "}{\\sqrt{\\text{" "}{}${\\mathbb{S}}_{\\mathrm{L}}^{+}" "}{}${\\mathbb{S}}_{\\mathrm{L}}^{+}$\\end{document}SL+" "}{}${\\mathbb{S}}_{\\mathrm{L}}^{-}$\\end{document}SL−" "}{}${\\mathbb{S}}_{\\mathrm{T}}^{+}$\\end{document}ST+" "}{}${\\mathbb{S}}_{\\mathrm{T}}^{-}$\\end{document}ST−" "}{}${\\mathrm{D}}_{i}^{0}$\\end{document}Di0" "}{}${\\mathrm{D}}_{i}^{1}$\\end{document}Di1" "}{}${\\psi" "}{}${F}_{0}^{+}" "}{}${F}_{0}^{-}" "}{}${F}_{1}^{+}" "}{}${F}_{1}^{-}" "}{}${N}_{+}^{-}$\\end{document}N+−" "}{}${N}_{+}^{-}=0$\\end{document}N+−=0" "}{}${N}_{+}^{-}={N}^{-}" "}{}${N}_{+}^{-}={N}^{-}$\\end{document}N+−=N−" "}{}${N}_{-}^{+}$\\end{document}N−+" "}{}${N}_{-}^{+}=0$\\end{document}N−+=0" "}{}${N}_{-}^{+}={N}^{+}" "}{}${N}_{-}^{+}={N}^{+}$\\end{document}N−+=N+" "}{}${N}_{-}^{+}={N}_{+}^{-}=0$\\end{document}N−+=N+−=0" "}{}\\begin{eqnarray*}" "}}" "}}_{1}^{+}&\\displaystyle" "}}_{1}^{-}&\\displaystyle" "}}_{2}^{+}&\\displaystyle" "}}_{2}^{-}&\\displaystyle" "}}_{\\Omega" "}}_{u}^{+}" "}}_{u}^{+}&\\displaystyle" "}}_{u}^{+}=\\frac{1}{{N}^{+}}\\sum" "}}_{u}^{-}&\\displaystyle" "}}_{u}^{-}=\\frac{1}{{N}^{-}}\\sum" "}}_{u}^{-}\\right" "}}}" "~0.3%" "~0.5" "~1%" "~1.53" "~10" "~100" "~100-fold" "~11" "~130" "~140,000" "~16" "~200" "~200kDa" "~20–30" "~210" "~25" "~250" "~3 million" "~4 million" "~4-fold" "~5%" "~50%" "~5500" "~65kDa" "~78%" "~8-hour" "~80%" "~80-140nm" "~90%" "~93 million" "~day" "°C" "°C." "±60°" "×10" "×103" "×104" "×106" "×8" "·103" "α/β" "α2" "α2-3" "α2-6" "α2-6/α2-8" "α2-8" "α2-8-linked" "α2–6" "α3" "αE" "αT2ib" "αVβ1" "β-D-thiogalactopyranoside" "β1" "ΔCT" "ΔCt" "ΔCtcontrol" "ΔCtinduced" "ΔG" "ΔH" "ΔI" "ΔI/Ioff" "ΔI/Iref" "ΔSASA" "ΔΔCt" "κB" "κHAC" "κHAC/DKO" "κTL1" "λ5" "λFIX" "μ+4σ" "μ2" "μF" "μg" "μg/1" "μg/30" "μg/kg" "μg/ml" "μg/μl" "μl" "μL" "μl/min" "μmol/l" "μn" "μp" "σB" "σn" "σp" "ΤCRδ−/−" "χ2" "ψu" "ψu−ψu"))))
