;;; -*- Mode:LISP; Syntax:Common-Lisp; Package:(SPARSER COMMON-LISP) -*-
;;; Copyright (c) 2017 SIFT LLC. All Rights Reserved
;;;
;;;    File: "loader"
;;;  Module: "grammar/model/sl/biology/
;;; version: February 2017

;; Broken out from terms 2/27/17
;; contains: cell lines, cell lines with IDs, cell types, and cell types with IDs

(in-package :sparser)

;;;------------
;;; cell lines
;;;------------
; were expressed in HEK293T cells
; BRAF mutant thyroid cell lines
; HER2-amplified breast cancer cell lines
; breast carcinoma cell lines
; all six BRAF-mutant thyroid cancer cell lines
; increased basal HER3 in 8505C cells
; confirmed in a second cell line
; our panel of cancer cell lines (Figure 6A).
; the HCC827 NSCLC cell line


(def-synonym cell-line (:noun "line"))
(def-synonym cell-line (:noun "cell line"))
(def-synonym cell-line (:noun "cell"))
(def-synonym cell-line (:noun "cultured cell"))
(def-synonym cell-line (:noun "cultured cell line"))

(defun def-cell-line (line)
  (def-bio/expr line 'cell-line :takes-plurals nil))


(noun "keratin" :super cell-type) ;; NOT SURE THIS IS HOW IT IS BEING USED
(noun "keratinocyte" :super cell-type)
(def-cell-line "cancer cell")


(def-cell-line "A375")
(def-cell-line "A431D")
(def-cell-line "A431")
(def-cell-line "C140")
(def-cell-line "D04")
(def-cell-line "D25")
(def-cell-line "DU-145")
(def-cell-line "MM415")
(def-cell-line "MM485")
(def-cell-line "OUMS-23")
(def-cell-line "PC12") ;; want to get effect of  :synonyms ("PC 12") as well
(def-cell-line "RPMI-7951")
(def-cell-line "SkMel24")
(def-cell-line "SkMel28")
(def-cell-line "WM266.4")
(def-cell-line "WM852")
(def-cell-line "HeLa")
(def-cell-line "hBRIE")
(def-cell-line "HEK293")
(def-cell-line "HEK293T")
(def-cell-line "HKe3 ER:HRASV12")
(def-cell-line "HKe3 ER:HRAS12")
(def-cell-line "HKe3")
(def-cell-line "KNRK")
(def-cell-line "LAT-3YF")
(def-cell-line "LAT3YF")
(def-cell-line "MDCK")
(def-cell-line "MDA-MB-468")
(def-cell-line "NIH-3T3")
(def-cell-line "Saos2")
(def-cell-line "VMM12")
(def-cell-line "VMM18")
(def-cell-line "VMM39")
(def-cell-line "VMM5A")

;;;--------------------
;;; cell lines with IDs
;;;--------------------

(def-ided-indiv cell-line "143B" "CVCL_2270" :no-plural t) 
(def-ided-indiv cell-line "293T" "CVCL_0063" :no-plural t) 
(def-ided-indiv cell-line "A-427" "CVCL:1055" :name "A-427" :no-plural t) 
(def-ided-indiv cell-line "A-549" "EFO:0001086" :name "A549" :no-plural t) 
(def-ided-indiv cell-line "A172" "CVCL_0131" :no-plural t) 
(def-ided-indiv cell-line "A2.1" "CVCL:E303" :name "A2.1" :no-plural t) 
(def-ided-indiv cell-line "A2780cp" "CVCL:0135" :name "A2780/CP70" :no-plural t) 
(def-ided-indiv cell-line "A2780s" "CVCL:0134" :name "A2780" :no-plural t) 
(def-ided-indiv cell-line "A375S2" "CVCL:0136" :name "A375.S2" :no-plural t) 
(def-ided-indiv cell-line "A375SM" "CVCL:5649" :name "A375-SM" :no-plural t) 
(def-ided-indiv cell-line "A7R5" "CVCL:0137" :name "A7r5" :no-plural t) 
(def-ided-indiv cell-line "ABC1" "CVCL:1066" :name "ABC-1" :no-plural t) 
(def-ided-indiv cell-line "AC16" "CVCL:4U18" :name "AC16" :no-plural t) 
(def-ided-indiv cell-line "ACC-MESO-4" "CVCL:5114" :name "ACC-MESO-4" :no-plural t) 
(def-ided-indiv cell-line "ACHN" "CVCL:1067" :name "ACHN" :no-plural t) 
(def-ided-indiv cell-line "AD-293" "CVCL:9804" :name "AD-293" :no-plural t) 
(def-ided-indiv cell-line "AD293" "CVCL:9804" :name "AD-293" :no-plural t) 
(def-ided-indiv cell-line "AF-5" "CVCL:8831" :name "AF5" :no-plural t) 
(def-ided-indiv cell-line "AF-6" "CVCL:U801" :name "AF-6" :no-plural t) 
(def-ided-indiv cell-line "AG14412" "CVCL:0P02" :name "AG14412" :no-plural t) 
(def-ided-indiv cell-line "AG16409" "CVCL:V978" :name "AG16409" :no-plural t) 
(def-ided-indiv cell-line "AG18371" "CVCL:X816" :name "AG18371" :no-plural t) 
(def-ided-indiv cell-line "AG1879" "CVCL:V557" :name "AG01879" :no-plural t) 
(def-ided-indiv cell-line "AKI" "CVCL:8170" :name "AKI" :no-plural t) 
(def-ided-indiv cell-line "AM-38" "CVCL:1070" :name "AM-38" :no-plural t) 
(def-ided-indiv cell-line "AML-12" "CVCL:0140" :name "AML12" :no-plural t) 
(def-ided-indiv cell-line "AN3CA" "CVCL:0028" :name "AN3-CA" :no-plural t) 
(def-ided-indiv cell-line "ANBL-6" "CVCL:5425" :name "ANBL-6" :no-plural t) 
(def-ided-indiv cell-line "AP-3" "CVCL:J157" :name "AP-3" :no-plural t) 
(def-ided-indiv cell-line "AP18" "CVCL:X041" :name "AP-18" :no-plural t) 
(def-ided-indiv cell-line "AP2" "CVCL:W419" :name "AP2" :no-plural t) 
(def-ided-indiv cell-line "APE1" "CVCL:Z272" :name "APE1" :no-plural t) 
(def-ided-indiv cell-line "AR3" "CVCL:0I24" :name "Ar-3" :no-plural t) 
(def-ided-indiv cell-line "AR4-2J" "CVCL:0143" :name "AR42J" :no-plural t) 
(def-ided-indiv cell-line "ARPE-19" "EFO:0006271" :name "ARPE-19" :no-plural t) 
(def-ided-indiv cell-line "AS-1" "CVCL:DC71" :name "AS-1" :no-plural t) 
(def-ided-indiv cell-line "AS-E2" "CVCL:6769" :name "AS-E2" :no-plural t) 
(def-ided-indiv cell-line "ASE2" "CVCL:6769" :name "AS-E2" :no-plural t) 
(def-ided-indiv cell-line "ASO" "CVCL:R967" :name "ASO" :no-plural t) 
(def-ided-indiv cell-line "ASPC-1" "CVCL_0152" :no-plural t) 
(def-ided-indiv cell-line "ASTC-a-1" "CVCL:C867" :name "ASTC-a-1" :no-plural t) 
(def-ided-indiv cell-line "AT-2SF" "CVCL:V575" :name "AT2SF" :no-plural t) 
(def-ided-indiv cell-line "AT-II" "CVCL:DI26" :name "AT-2" :no-plural t) 
(def-ided-indiv cell-line "AT3-2" "CVCL:DE19" :name "CHO-AT3-2" :no-plural t) 
(def-ided-indiv cell-line "AT5BIVA" "CVCL:7442" :name "AT5BIVA" :no-plural t) 
(def-ided-indiv cell-line "ATDC5" "CVCL:3894" :name "ATDC-5" :no-plural t) 
(def-ided-indiv cell-line "ATL-2" "CVCL:8338" :name "ATL-2" :no-plural t) 
(def-ided-indiv cell-line "ATL2" "CVCL:8338" :name "ATL-2" :no-plural t) 
(def-ided-indiv cell-line "AZ521" "CVCL:2862" :name "AZ-521" :no-plural t) 
(def-ided-indiv cell-line "Act1" "CVCL:6291" :name "ACT-1 [Human thyroid carcinoma]" :no-plural t) 
(def-ided-indiv cell-line "AtT20" "CVCL:2300" :name "AtT-20" :no-plural t) 
(def-ided-indiv cell-line "Au565" "EFO:0001087" :name "AU565" :no-plural t) 
(def-ided-indiv cell-line "B16F0" "CVCL:0604" :name "B16-F0" :no-plural t) 
(def-ided-indiv cell-line "B16F1" "CVCL:0158" :name "B16-F1" :no-plural t) 
(def-ided-indiv cell-line "B16F10" "CVCL:0159" :name "B16-F10" :no-plural t) 
(def-ided-indiv cell-line "B6SUtA1" "CVCL:D635" :name "B6SUtA1" :no-plural t) 
(def-ided-indiv cell-line "B6Tert-1" "CVCL:6880" :name "B6Tert-1" :no-plural t) 
(def-ided-indiv cell-line "B95-8" "CVCL:1953" :name "B95-8" :no-plural t) 
(def-ided-indiv cell-line "BAF-B03" "CVCL:0072" :name "BaF-B03" :no-plural t) 
(def-ided-indiv cell-line "BAS" "CVCL:U803" :name "BA" :no-plural t) 
(def-ided-indiv cell-line "BBM" "CVCL:4400" :name "BBM" :no-plural t) 
(def-ided-indiv cell-line "BC3" "CVCL:1080" :name "BC-3" :no-plural t) 
(def-ided-indiv cell-line "BCBL-1" "EFO:0002048" :name "BCBL-1" :no-plural t) 
(def-ided-indiv cell-line "BCPAP" "CVCL:0153" :name "B-CPAP" :no-plural t) 
(def-ided-indiv cell-line "BCS-TC2" "CVCL:B041" :name "BCS-TC2" :no-plural t) 
(def-ided-indiv cell-line "BCWM1" "CVCL:A035" :name "BCWM.1" :no-plural t) 
(def-ided-indiv cell-line "BCap37" "CVCL:0164" :name "Bcap37" :no-plural t) 
(def-ided-indiv cell-line "BEAS2B" "EFO:0001089" :name "BEAS-2B" :no-plural t) 
(def-ided-indiv cell-line "BEL-7402" "CVCL:5492" :name "BEL-7402" :no-plural t) 
(def-ided-indiv cell-line "BEL-7404" "CVCL:6568" :name "BEL-7404" :no-plural t) 
(def-ided-indiv cell-line "BEP2D" "CVCL:6E77" :name "BEP2D" :no-plural t) 
(def-ided-indiv cell-line "BFA" "CVCL:4124" :name "BFA" :no-plural t) 
(def-ided-indiv cell-line "BG-1" "CVCL:6570" :name "BG1" :no-plural t) 
(def-ided-indiv cell-line "BGC-823" "CVCL:3360" :name "BGC-823" :no-plural t) 
(def-ided-indiv cell-line "BGC823" "CVCL:3360" :name "BGC-823" :no-plural t) 
(def-ided-indiv cell-line "BHK-21" "CVCL:1914" :name "BHK-21" :no-plural t) 
(def-ided-indiv cell-line "BPH-1" "CVCL:1091" :name "BPH-1" :no-plural t) 
(def-ided-indiv cell-line "BR-N1" "CVCL:0U15" :name "BRN-1" :no-plural t) 
(def-ided-indiv cell-line "BRC3" "CVCL:B980" :name "BRC3" :no-plural t) 
(def-ided-indiv cell-line "BRC7" "CVCL:B984" :name "BRC7" :no-plural t) 
(def-ided-indiv cell-line "BRC8" "CVCL:B985" :name "BRC8" :no-plural t) 
(def-ided-indiv cell-line "BRN2" "CVCL:0U16" :name "BRN-2" :no-plural t) 
(def-ided-indiv cell-line "BT-20" "CVCL_0178" :no-plural t) 
(def-ided-indiv cell-line "BT-474" "CVCL:0179" :name "BT-474" :no-plural t) 
(def-ided-indiv cell-line "BT-483" "CVCL:2319" :name "BT-483" :no-plural t) 
(def-ided-indiv cell-line "BT-549" "NCIT:C117227" :name "BT-549" :no-plural t) 
(def-ided-indiv cell-line "BT474" "CVCL:0179" :name "BT-474" :no-plural t) 
(def-ided-indiv cell-line "BT549" "CVCL:1092" :name "BT-549" :no-plural t) 
(def-ided-indiv cell-line "BV173" "CVCL:0181" :name "BV-173" :no-plural t) 
(def-ided-indiv cell-line "BV2" "CVCL:0182" :name "BV-2" :no-plural t) 
(def-ided-indiv cell-line "BVR" "CVCL:1M70" :name "BVR" :no-plural t) 
(def-ided-indiv cell-line "Ba/F3" "CVCL:0161" :name "Ba/F3" :no-plural t) 
(def-ided-indiv cell-line "BaF3" "CVCL:0161" :name "Ba/F3" :no-plural t) 
(def-ided-indiv cell-line "Bc12" "CVCL:U335" :name "BC12" :no-plural t) 
(def-ided-indiv cell-line "BeWo" "EFO:0002050" :name "BeWo" :no-plural t) 
(def-ided-indiv cell-line "Beas-2B cells" "BTO:0002923" :name "BEAS-2B cell" :no-plural t) 
(def-ided-indiv cell-line "Bel7402" "CVCL:5492" :name "BEL-7402" :no-plural t) 
(def-ided-indiv cell-line "Bic-1" "CVCL:8092" :name "BIC-1" :no-plural t) 
(def-ided-indiv cell-line "Bl21" "CVCL:M639" :name "BL-21" :no-plural t) 
(def-ided-indiv cell-line "Bon-1" "CVCL:3985" :name "BON-1" :no-plural t) 
(def-ided-indiv cell-line "Br2" "CVCL:AU04" :name "BR-2" :no-plural t) 
(def-ided-indiv cell-line "Br4" "CVCL:AU02" :name "BR-4" :no-plural t) 
(def-ided-indiv cell-line "Br5" "CVCL:AU03" :name "BR-5" :no-plural t) 
(def-ided-indiv cell-line "BxPC3" "EFO:0002709" :name "BxPC-3" :no-plural t) 
;;(def-ided-indiv cell-line "B–E" "CVCL:AT71" :name "R1192" :no-plural t) ;; more like to be referring to figures
(def-ided-indiv cell-line "BV2" "CVCL:0182" :name "BV-2" :no-plural t) ;; manually added
(def-ided-indiv cell-line "C 21" "CVCL_2323" :no-plural t) 
(def-ided-indiv cell-line "C1R-B7" "CVCL:6373" :name "C1R-B7" :no-plural t) 
(def-ided-indiv cell-line "C2BBe1" "EFO:0006546" :name "C2BBe1" :no-plural t) 
(def-ided-indiv cell-line "C2C12" "EFO:0001098" :name "C2C12" :no-plural t) 
(def-ided-indiv cell-line "C33a" "EFO:0002120" :name "C33A" :no-plural t) 
(def-ided-indiv cell-line "C3ABR" "CVCL:M914" :name "C3ABR" :no-plural t) 
(def-ided-indiv cell-line "C4-2" "CVCL:4782" :name "LNCaP C4-2" :no-plural t) 
(def-ided-indiv cell-line "C4-2b" "EFO:0006365" :name "C4-2B" :no-plural t) 
(def-ided-indiv cell-line "C5.2" "CVCL:J984" :name "C5.2" :no-plural t) 
(def-ided-indiv cell-line "C666-1" "CVCL:7949" :name "C666-1" :no-plural t) 
(def-ided-indiv cell-line "C75" "CVCL_5248" :no-plural t) 
(def-ided-indiv cell-line "CA2" "CVCL:B845" :name "CA2" :no-plural t) 
(def-ided-indiv cell-line "CA9-22" "CVCL:1102" :name "Ca9-22" :no-plural t) 
(def-ided-indiv cell-line "CAC1" "CVCL:A421" :name "CAC-1" :no-plural t) 
(def-ided-indiv cell-line "CAD" "CVCL:0199" :name "CAD" :no-plural t) 
(def-ided-indiv cell-line "CAF" "CVCL:R883" :name "CAF" :no-plural t) 
(def-ided-indiv cell-line "CAL-27" "CVCL:1107" :name "CAL-27" :no-plural t) 
(def-ided-indiv cell-line "CAL27" "CVCL:1107" :name "CAL-27" :no-plural t) 
(def-ided-indiv cell-line "CAL51" "CVCL:1110" :name "CAL-51" :no-plural t) 
(def-ided-indiv cell-line "CAOV-3" "CVCL:0201" :name "Caov-3" :no-plural t) 
(def-ided-indiv cell-line "CAOV3" "EFO:0002148" :name "CaOv3" :no-plural t) 
(def-ided-indiv cell-line "CAPAN2" "EFO:0002154" :name "Capan2" :no-plural t) 
(def-ided-indiv cell-line "CB1" "CVCL:U652" :name "CB1" :no-plural t) 
(def-ided-indiv cell-line "CC-3" "CVCL:C639" :name "CC3" :no-plural t) 
(def-ided-indiv cell-line "CC1" "CVCL:4141" :name "CC-1" :no-plural t) 
(def-ided-indiv cell-line "CC2" "CVCL:ER23" :name "RECA" :no-plural t) 
(def-ided-indiv cell-line "CCK81" "CVCL:2873" :name "CCK-81" :no-plural t) 
(def-ided-indiv cell-line "CCL3" "CVCL:M023" :name "CCL3" :no-plural t) 
(def-ided-indiv cell-line "CCL39" "CVCL:2886" :name "Dede" :no-plural t) 
(def-ided-indiv cell-line "CCL4" "CVCL:M024" :name "CCL4" :no-plural t) 
(def-ided-indiv cell-line "CCLP-1" "CVCL:0205" :name "CC-LP-1" :no-plural t) 
(def-ided-indiv cell-line "CCLP1" "CVCL:0205" :name "CC-LP-1" :no-plural t) 
(def-ided-indiv cell-line "CCRF-CEM" "NCIT:C117114" :name "CCRF-CEM" :no-plural t) 
(def-ided-indiv cell-line "CCRF-HSB-2" "CVCL:1859" :name "CCRF-HSB-2" :no-plural t) 
(def-ided-indiv cell-line "CCSW1" "CVCL:A429" :name "CC-SW-1" :no-plural t) 
(def-ided-indiv cell-line "CE3" "CVCL:8950" :name "CE-3" :no-plural t) 
(def-ided-indiv cell-line "CEM-C7H2" "CVCL:EP75" :name "CCRF-CEM C7H2" :no-plural t) 
(def-ided-indiv cell-line "CFPac1" "EFO:0006551" :name "CFPAC-1" :no-plural t) 
(def-ided-indiv cell-line "CGR8" "EFO:0006273" :name "CGR8" :no-plural t) 
(def-ided-indiv cell-line "CGTH-W3" "CVCL_3898" :no-plural t) 
(def-ided-indiv cell-line "CH1" "CVCL:M602" :name "Ch-1" :no-plural t) 
(def-ided-indiv cell-line "CH2879" "CVCL:9921" :name "ch-2879" :no-plural t) 
(def-ided-indiv cell-line "CHLA-255" "CVCL:AQ27" :name "CHLA-255" :no-plural t) 
(def-ided-indiv cell-line "CHME5" "CVCL:5J53" :name "CHME-5" :no-plural t) 
(def-ided-indiv cell-line "CHO-IR" "CVCL:R864" :name "CHO/IR" :no-plural t) 
(def-ided-indiv cell-line "CHO-K1" "CVCL:0214" :name "CHO-K1" :no-plural t) 
(def-ided-indiv cell-line "CHO-m3" "CVCL:U011" :name "T02J-7/10" :no-plural t) 
(def-ided-indiv cell-line "CHP134" "CVCL:1124" :name "CHP-134" :no-plural t) 
(def-ided-indiv cell-line "CHP3" "CVCL:2778" :name "CHP 3 (M.W.)" :no-plural t) 
(def-ided-indiv cell-line "CHRF-288-11" "CVCL:A280" :name "CHRF-288-11" :no-plural t) 
(def-ided-indiv cell-line "CL-A" "CVCL:E529" :name "CLA" :no-plural t) 
(def-ided-indiv cell-line "CL1-0" "CVCL:3871" :name "CL1-0" :no-plural t) 
(def-ided-indiv cell-line "CL1-5" "CVCL:D521" :name "CL1-5" :no-plural t) 
(def-ided-indiv cell-line "CL100" "CVCL:Y428" :name "CL100" :no-plural t) 
(def-ided-indiv cell-line "CL97" "CVCL:N826" :name "CL97" :no-plural t) 
(def-ided-indiv cell-line "CM1" "CVCL:Y613" :name "CM-1" :no-plural t) 
(def-ided-indiv cell-line "CM5" "CVCL:Y622" :name "CM-5 [Human ESC]" :no-plural t) 
(def-ided-indiv cell-line "CNE-1" "CVCL:6888" :name "CNE-1" :no-plural t) 
(def-ided-indiv cell-line "CNE-2" "CVCL:6889" :name "CNE-2" :no-plural t) 
(def-ided-indiv cell-line "CNE1" "CVCL:6888" :name "CNE-1" :no-plural t) 
(def-ided-indiv cell-line "CNE2" "CVCL:6889" :name "CNE-2" :no-plural t) 
(def-ided-indiv cell-line "COC1" "CVCL:6891" :name "CoC1" :no-plural t) 
(def-ided-indiv cell-line "COL-1" "CVCL:2A40" :name "Col-1" :no-plural t) 
(def-ided-indiv cell-line "COL1" "CVCL:2A40" :name "Col-1" :no-plural t) 
(def-ided-indiv cell-line "COLO201" "CVCL:F399" :name "COLO201" :no-plural t) 
(def-ided-indiv cell-line "COLO201-AR" "CVCL:4V91" :name "COLO201-AR" :no-plural t) 
(def-ided-indiv cell-line "COLO205" "CVCL:F402" :name "COLO205" :no-plural t) 
(def-ided-indiv cell-line "COLO320" "CVCL:1989" :name "COLO 320" :no-plural t) 
(def-ided-indiv cell-line "COS-7" "CVCL:0224" :name "COS-7" :no-plural t) 
(def-ided-indiv cell-line "COS7" "CVCL:0224" :name "COS-7" :no-plural t) 
(def-ided-indiv cell-line "CP5" "CVCL:X511" :name "CP5" :no-plural t) 
(def-ided-indiv cell-line "CP70" "CVCL:0135" :name "A2780/CP70" :no-plural t) 
(def-ided-indiv cell-line "CS-1" "CVCL:H245" :name "RPMI-3460/CS1" :no-plural t) 
(def-ided-indiv cell-line "CS1AN" "CVCL:L471" :name "GM00739" :no-plural t) 
(def-ided-indiv cell-line "CT-3" "CVCL:B848" :name "CT-3" :no-plural t) 
(def-ided-indiv cell-line "CT26" "CVCL:7254" :name "CT26" :no-plural t) 
(def-ided-indiv cell-line "CTLL-2" "EFO:0002821" :name "CTLL-2" :no-plural t) 
(def-ided-indiv cell-line "CV1" "CVCL:0229" :name "CV-1" :no-plural t) 
(def-ided-indiv cell-line "CWR-R1" "CVCL:4833" :name "CWR-R1" :no-plural t) 
(def-ided-indiv cell-line "CWR22" "CVCL:3967" :name "CWR22" :no-plural t) 
(def-ided-indiv cell-line "CWR22R" "CVCL:1045" :name "22Rv1" :no-plural t) 
(def-ided-indiv cell-line "CWR22Rv1" "CVCL:1045" :name "22Rv1" :no-plural t) 
(def-ided-indiv cell-line "Caco-2" "EFO:0001099" :name "Caco-2" :no-plural t) 
(def-ided-indiv cell-line "Caco2" "EFO:0001099" :name "Caco-2" :no-plural t) 
(def-ided-indiv cell-line "Caki-2" "CVCL:0235" :name "Caki-2" :no-plural t) 
(def-ided-indiv cell-line "Cal-78" "CVCL:1809" :name "CAL-78" :no-plural t) 
(def-ided-indiv cell-line "Calu-1" "EFO:0002151" :name "Calu1" :no-plural t) 
(def-ided-indiv cell-line "Calu-3" "EFO:0002819" :name "Calu3" :no-plural t) 
(def-ided-indiv cell-line "Calu-6" "EFO:0002152" :name "Calu6" :no-plural t) 
(def-ided-indiv cell-line "Cama-1" "CVCL:1115" :name "CAMA-1" :no-plural t) 
(def-ided-indiv cell-line "Capan-1" "EFO:0002153" :name "Capan1" :no-plural t) 
(def-ided-indiv cell-line "Carb" "CVCL:5715" :name "CarB" :no-plural t) 
(def-ided-indiv cell-line "Cas9" "CVCL:8537" :name "CAS-9" :no-plural t) 
(def-ided-indiv cell-line "Che-1" "CVCL:C111" :name "CHE-1" :no-plural t) 
(def-ided-indiv cell-line "Che1" "CVCL:C111" :name "CHE-1" :no-plural t) 
(def-ided-indiv cell-line "Co115" "CVCL:D102" :name "Co-115" :no-plural t) 
(def-ided-indiv cell-line "Con8" "CVCL:9U76" :name "CON8" :no-plural t) 
(def-ided-indiv cell-line "Cos-1" "NCIT:C17968" :name "COS-1" :no-plural t) 
(def-ided-indiv cell-line "Cy3" "CVCL:1P99" :name "CY3" :no-plural t) 
(def-ided-indiv cell-line "Cy5" "CVCL:1Q01" :name "CY5" :no-plural t) 
(def-ided-indiv cell-line "D407" "CVCL_8183" :no-plural t) 
(def-ided-indiv cell-line "DAPT" "CVCL:D279" :name "DAPT" :no-plural t) 
(def-ided-indiv cell-line "DBTRG-05MG" "CVCL:1169" :name "DBTRG-05MG" :no-plural t) 
(def-ided-indiv cell-line "DEC-205" "CVCL:9171" :name "DEC-205" :no-plural t) 
(def-ided-indiv cell-line "DEC205" "CVCL:9171" :name "DEC-205" :no-plural t) 
(def-ided-indiv cell-line "DG2" "CVCL:L853" :name "DG2" :no-plural t) 
(def-ided-indiv cell-line "DG75" "CVCL:0244" :name "DG-75" :no-plural t) 
(def-ided-indiv cell-line "DL1" "CVCL:Z231" :name "Schneider 1" :no-plural t) 
(def-ided-indiv cell-line "DL3" "CVCL:J397" :name "DL-3" :no-plural t) 
(def-ided-indiv cell-line "DLD-1" "EFO:0006389" :name "DLD1" :no-plural t) 
(def-ided-indiv cell-line "DM1" "CVCL:Z231" :name "Schneider 1" :no-plural t) 
(def-ided-indiv cell-line "DM331" "CVCL:6626" :name "DM331" :no-plural t) 
(def-ided-indiv cell-line "DM4" "CVCL:5644" :name "DM-4" :no-plural t) 
(def-ided-indiv cell-line "DM93" "CVCL:6629" :name "DM93" :no-plural t) 
(def-ided-indiv cell-line "DMS114" "EFO:0002162" :name "DMS114" :no-plural t) 
(def-ided-indiv cell-line "DND39" "CVCL:2021" :name "DND-39" :no-plural t) 
(def-ided-indiv cell-line "DND41" "CVCL:2022" :name "DND-41" :no-plural t) 
(def-ided-indiv cell-line "DOHH2" "CVCL_1179" :no-plural t) 
(def-ided-indiv cell-line "DT-40" "CVCL:0249" :name "DT40" :no-plural t) 
(def-ided-indiv cell-line "DX2" "CVCL:5652" :name "SK-MEL-93 DX-2" :no-plural t) 
(def-ided-indiv cell-line "Daoy" "CVCL:1167" :name "Daoy" :no-plural t) 
(def-ided-indiv cell-line "Difi" "CVCL:6895" :name "DiFi" :no-plural t) 
(def-ided-indiv cell-line "Dsh1" "CVCL:1182" :name "DSH1" :no-plural t) 
(def-ided-indiv cell-line "Dx5" "CVCL:2598" :name "MES-SA/Dx5" :no-plural t) 
(def-ided-indiv cell-line "E006AA" "CVCL:4834" :name "E006AA" :no-plural t) 
(def-ided-indiv cell-line "E1C3" "CVCL:6969" :name "E1C3" :no-plural t) 
(def-ided-indiv cell-line "EAA" "CVCL:Z253" :name "BTI-EAA" :no-plural t) 
(def-ided-indiv cell-line "EBC1" "CVCL_2891" :no-plural t) 
(def-ided-indiv cell-line "EC9706" "CVCL:E307" :name "EC9706" :no-plural t) 
(def-ided-indiv cell-line "ECC-1" "EFO:0005231" :name "ECC-1" :no-plural t) 
(def-ided-indiv cell-line "ECC1" "CVCL:7260" :name "ECC-1" :no-plural t) 
(def-ided-indiv cell-line "ECV304" "CVCL:2029" :name "ECV-304" :no-plural t) 
(def-ided-indiv cell-line "EFO-21" "CVCL:0029" :name "EFO-21" :no-plural t) 
(def-ided-indiv cell-line "EGI-1" "CVCL:1193" :name "EGI-1" :no-plural t) 
(def-ided-indiv cell-line "EL-4" "CVCL:0255" :name "EL4" :no-plural t) 
(def-ided-indiv cell-line "ELT-3" "CVCL:4616" :name "ELT3" :no-plural t) 
(def-ided-indiv cell-line "EOL-1" "CVCL:0258" :name "EoL-1" :no-plural t) 
(def-ided-indiv cell-line "EP-1" "CVCL:8350" :name "EP-1" :no-plural t) 
(def-ided-indiv cell-line "ER1" "CVCL:L896" :name "ER-1" :no-plural t) 
(def-ided-indiv cell-line "ER3" "CVCL:EJ09" :name "HCC827 ER3" :no-plural t) 
(def-ided-indiv cell-line "ER36" "CVCL:Z907" :name "E-r[36]" :no-plural t) 
(def-ided-indiv cell-line "ES-2" "CVCL:AX39" :name "ES2" :no-plural t) 
(def-ided-indiv cell-line "EU-4" "CVCL:8862" :name "EU-4" :no-plural t) 
(def-ided-indiv cell-line "EW-8" "CVCL:V618" :name "EW-8" :no-plural t) 
(def-ided-indiv cell-line "Eca109" "CVCL:6898" :name "Eca-109" :no-plural t) 
(def-ided-indiv cell-line "Ena" "CVCL:E584" :name "ENA" :no-plural t) 
(def-ided-indiv cell-line "F-36P" "CVCL:2037" :name "F-36P" :no-plural t) 
(def-ided-indiv cell-line "F-B1" "CVCL:A603" :name "FB-1" :no-plural t) 
(def-ided-indiv cell-line "F4/80" "CVCL:7263" :name "F4/80" :no-plural t) 
(def-ided-indiv cell-line "F5M2" "CVCL:4V83" :name "SOSP-9607/F5M2" :no-plural t) 
(def-ided-indiv cell-line "FB-2" "CVCL:9917" :name "FB-2" :no-plural t) 
(def-ided-indiv cell-line "FDC-P1" "CVCL:2039" :name "FDC-P1" :no-plural t) 
(def-ided-indiv cell-line "FDCP-MixA4" "CVCL:2040" :name "FDCP-Mix cl.A4" :no-plural t) 
(def-ided-indiv cell-line "FHL124" "CVCL:S908" :name "FHL124" :no-plural t) 
(def-ided-indiv cell-line "FL5.12" "CVCL:0262" :name "FL5.12" :no-plural t) 
(def-ided-indiv cell-line "FM88" "CVCL:9679" :name "FM88" :no-plural t) 
(def-ided-indiv cell-line "FRTL-5" "CVCL:0265" :name "FRTL-5" :no-plural t) 
(def-ided-indiv cell-line "FT210" "CVCL:H224" :name "FT210" :no-plural t) 
(def-ided-indiv cell-line "FTC-133" "CVCL:1219" :name "FTC-133" :no-plural t) 
(def-ided-indiv cell-line "FTC133" "CVCL:1219" :name "FTC-133" :no-plural t) 
(def-ided-indiv cell-line "Fc4" "CVCL:K170" :name "FC4.K" :no-plural t) 
(def-ided-indiv cell-line "Fer" "CVCL:4200" :name "FER" :no-plural t) 
(def-ided-indiv cell-line "Fkh1" "CVCL:2041" :name "FKH-1" :no-plural t) 
(def-ided-indiv cell-line "Flo-1" "CVCL:2045" :name "FLO-1" :no-plural t) 
(def-ided-indiv cell-line "GAK" "CVCL:1225" :name "GAK" :no-plural t) 
(def-ided-indiv cell-line "GB1" "CVCL:1227" :name "GB-1" :no-plural t) 
(def-ided-indiv cell-line "GBM6" "CVCL:DG62" :name "GBM6" :no-plural t) 
(def-ided-indiv cell-line "GBM8401" "CVCL:B051" :name "GBM8401" :no-plural t) 
(def-ided-indiv cell-line "GBS1" "CVCL:M818" :name "GBS-1" :no-plural t) 
(def-ided-indiv cell-line "GC7" "CVCL:5757" :name "GC7" :no-plural t) 
(def-ided-indiv cell-line "GD25" "CVCL:7264" :name "GD25" :no-plural t) 
(def-ided-indiv cell-line "GE11" "CVCL:8873" :name "GE11" :no-plural t) 
(def-ided-indiv cell-line "GES-1" "CVCL:EQ22" :name "GES-1" :no-plural t) 
(def-ided-indiv cell-line "GH3" "CVCL:0273" :name "GH3" :no-plural t) 
(def-ided-indiv cell-line "GHFT-1" "CVCL:J506" :name "GHFT1-5" :no-plural t) 
(def-ided-indiv cell-line "GIST-T1" "CVCL:4976" :name "GIST-T-1" :no-plural t) 
(def-ided-indiv cell-line "GIST430" "CVCL:7040" :name "GIST430" :no-plural t) 
(def-ided-indiv cell-line "GIST48" "CVCL:7041" :name "GIST48" :no-plural t) 
(def-ided-indiv cell-line "GIST48B" "CVCL:M441" :name "GIST48B" :no-plural t) 
(def-ided-indiv cell-line "GIST882" "CVCL:7044" :name "GIST882" :no-plural t) 
(def-ided-indiv cell-line "GL261" "CVCL:Y003" :name "GL261" :no-plural t) 
(def-ided-indiv cell-line "GLE" "CVCL:0C11" :name "GL-E" :no-plural t) 
(def-ided-indiv cell-line "GM05823" "CVCL:7441" :name "AT5BI" :no-plural t) 
(def-ided-indiv cell-line "GM1" "CVCL:Z794" :name "GM1" :no-plural t) 
(def-ided-indiv cell-line "GM130" "CVCL:7274" :name "GM00130" :no-plural t) 
(def-ided-indiv cell-line "GM1526" "CVCL:7322" :name "GM01526" :no-plural t) 
(def-ided-indiv cell-line "GM18366" "CVCL:6G80" :name "GM18366" :no-plural t) 
(def-ided-indiv cell-line "GM2" "CVCL:Z795" :name "GM2" :no-plural t) 
(def-ided-indiv cell-line "GM3" "CVCL:Z796" :name "GM3" :no-plural t) 
(def-ided-indiv cell-line "GN4" "CVCL:DN37" :name "GN4" :no-plural t) 
(def-ided-indiv cell-line "GP220" "CVCL:S968" :name "GP220" :no-plural t) 
(def-ided-indiv cell-line "GS-1" "CVCL:0H90" :name "GS1" :no-plural t) 
(def-ided-indiv cell-line "GSC" "CVCL:M752" :name "GSC" :no-plural t) 
(def-ided-indiv cell-line "GSC11" "CVCL:DR55" :name "GSC11" :no-plural t) 
(def-ided-indiv cell-line "GSC23" "CVCL:DR59" :name "GSC23" :no-plural t) 
(def-ided-indiv cell-line "GT1-7" "CVCL:0281" :name "GT1-7" :no-plural t) 
(def-ided-indiv cell-line "Gb3" "CVCL:S827" :name "GB-3" :no-plural t) 
(def-ided-indiv cell-line "Gef-R" "CVCL_4V04" :no-plural t) 
(def-ided-indiv cell-line "Glc-82" "CVCL:3371" :name "GLC-82" :no-plural t) 
(def-ided-indiv cell-line "Granta-519" "CVCL:1818" :name "Granta-519" :no-plural t) 
(def-ided-indiv cell-line "H1299" "CVCL_0060" :no-plural t) 
(def-ided-indiv cell-line "H1650" "CVCL_1483" :no-plural t) 
(def-ided-indiv cell-line "H1703" "CVCL_1490" :no-plural t) 
(def-ided-indiv cell-line "H19-7" "CVCL:H781" :name "H19-7" :no-plural t) 
(def-ided-indiv cell-line "H23" "CVCL_1547" :no-plural t) 
(def-ided-indiv cell-line "H3.1" "CVCL:L520" :name "H3.1" :no-plural t) 
(def-ided-indiv cell-line "H4-C99" "CVCL:U993" :name "H4-C99" :no-plural t) 
(def-ided-indiv cell-line "H446" "CVCL_1562" :no-plural t) 
(def-ided-indiv cell-line "H460" "CVCL_0459" :no-plural t) 
(def-ided-indiv cell-line "H4IIE" "CVCL:0284" :name "H4-II-E" :no-plural t) 
(def-ided-indiv cell-line "H4IIEC3" "CVCL:0285" :name "H4-II-E-C3" :no-plural t) 
(def-ided-indiv cell-line "H4TG" "CVCL:3512" :name "H4TG" :no-plural t) 
(def-ided-indiv cell-line "H9c2" "CVCL:0286" :name "H9c2(2-1)" :no-plural t) 
(def-ided-indiv cell-line "HA-A1" "CVCL:8960" :name "HAA1" :no-plural t) 
(def-ided-indiv cell-line "HA22T" "CVCL:7046" :name "HA22T/VGH" :no-plural t) 
(def-ided-indiv cell-line "HB4a" "CVCL:J982" :name "HB4a" :no-plural t) 
(def-ided-indiv cell-line "HBEC-3" "CVCL:X491" :name "HBEC3-KT" :no-plural t) 
(def-ided-indiv cell-line "HBEc14-KT" "CVCL:EQ83" :name "HBEC14-KT" :no-plural t) 
(def-ided-indiv cell-line "HBL-1" "CVCL:4213" :name "HBL-1 [Human diffuse large B-cell lymphoma]" :no-plural t) 
(def-ided-indiv cell-line "HBL-100" "CVCL:4362" :name "HBL-100" :no-plural t) 
(def-ided-indiv cell-line "HC-11" "CVCL:0288" :name "HC11" :no-plural t) 
(def-ided-indiv cell-line "HC20" "CVCL:W518" :name "C-HC-20" :no-plural t) 
(def-ided-indiv cell-line "HCA-7" "CVCL:0289" :name "HCA7" :no-plural t) 
(def-ided-indiv cell-line "HCC-1428" "CVCL:1252" :name "HCC1428" :no-plural t) 
(def-ided-indiv cell-line "HCC-1588" "CVCL:A351" :name "HCC1588" :no-plural t) 
(def-ided-indiv cell-line "HCC-1937" "CVCL:0290" :name "HCC1937" :no-plural t) 
(def-ided-indiv cell-line "HCC1143" "CVCL:1245" :name "HCC1143" :no-plural t) 
(def-ided-indiv cell-line "HCC1419" "CVCL:1251" :name "HCC1419" :no-plural t) 
(def-ided-indiv cell-line "HCC1569" "CVCL:1255" :name "HCC1569" :no-plural t) 
(def-ided-indiv cell-line "HCC1806" "EFO:0005373" :name "HCC1806" :no-plural t) 
(def-ided-indiv cell-line "HCC1954" "CVCL:1259" :name "HCC1954" :no-plural t) 
(def-ided-indiv cell-line "HCC202" "CVCL:2062" :name "HCC202" :no-plural t) 
(def-ided-indiv cell-line "HCC2429" "CVCL:5132" :name "HCC2429" :no-plural t) 
(def-ided-indiv cell-line "HCC38" "EFO:0001180" :name "HCC38" :no-plural t) 
(def-ided-indiv cell-line "HCC827" "CVCL:2063" :name "HCC827" :no-plural t) 
(def-ided-indiv cell-line "HCC827EPR" "CVCL:V407" :name "HCC827EPR" :no-plural t) 
(def-ided-indiv cell-line "HCCLM3" "CVCL:6832" :name "HCCLM3" :no-plural t) 
(def-ided-indiv cell-line "HCD57" "CVCL:5289" :name "HCD-57" :no-plural t) 
(def-ided-indiv cell-line "HCE7" "CVCL:5138" :name "HCE-7" :no-plural t) 
(def-ided-indiv cell-line "HCEC-1CT" "CVCL:AQ45" :name "HCEC 1CT" :no-plural t) 
(def-ided-indiv cell-line "HCS-2" "CVCL:2918" :name "HCS-2" :no-plural t) 
(def-ided-indiv cell-line "HCT 116" "CVCL_0291" :no-plural t) 
(def-ided-indiv cell-line "HCT-116" "NCIT:C117161" :name "HCT-116" :no-plural t) 
(def-ided-indiv cell-line "HCT-15" "EFO:0002188" :name "HCT15" :no-plural t) 
(def-ided-indiv cell-line "HCT116" "EFO:0002824" :name "HCT116" :no-plural t) 
(def-ided-indiv cell-line "HCT116p53" "CVCL:S744" :name "p53HCT116" :no-plural t) 
(def-ided-indiv cell-line "HCT8" "EFO:0002189" :name "HCT8" :no-plural t) 
(def-ided-indiv cell-line "HCV29" "CVCL:8228" :name "HCV-29" :no-plural t) 
(def-ided-indiv cell-line "HEC-1-A" "EFO:0002191" :name "HEC1A" :no-plural t) 
(def-ided-indiv cell-line "HEC-1B" "EFO:0002192" :name "HEC1B" :no-plural t) 
(def-ided-indiv cell-line "HEC59" "CVCL:2930" :name "HEC-59" :no-plural t) 
(def-ided-indiv cell-line "HEK 293" "CVCL_0045" :no-plural t) 
(def-ided-indiv cell-line "HEK-293FT" "CVCL:6911" :name "HEK293-FT" :no-plural t) 
(def-ided-indiv cell-line "HEK-TERV" "CVCL:D122" :name "HEK-TERV" :no-plural t) 
(def-ided-indiv cell-line "HEK293A" "CVCL:6910" :name "HEK293-A" :no-plural t) 
(def-ided-indiv cell-line "HEK293E" "CVCL:6974" :name "HEK293-EBNA" :no-plural t) 
(def-ided-indiv cell-line "HEK293F" "CVCL:6642" :name "HEK293-F" :no-plural t) 
(def-ided-indiv cell-line "HES4" "CVCL:D094" :name "HES-4" :no-plural t) 
(def-ided-indiv cell-line "HEYC2" "CVCL:X009" :name "HEY C2" :no-plural t) 
(def-ided-indiv cell-line "HEp2" "EFO:0006438" :name "HEp-2" :no-plural t) 
(def-ided-indiv cell-line "HF1A3" "CVCL:M662" :name "HF-1A3" :no-plural t) 
(def-ided-indiv cell-line "HGC27" "CVCL:1279" :name "HGC-27" :no-plural t) 
(def-ided-indiv cell-line "HHT" "CVCL:Y541" :name "iPS-HHT" :no-plural t) 
(def-ided-indiv cell-line "HIG-82" "CVCL:3439" :name "HIG-82" :no-plural t) 
(def-ided-indiv cell-line "HKC-8" "CVCL:Y910" :name "HKC-8" :no-plural t) 
(def-ided-indiv cell-line "HKh-2" "CVCL:9797" :name "HKh-2" :no-plural t) 
(def-ided-indiv cell-line "HL-1" "CVCL:0303" :name "HL-1" :no-plural t) 
(def-ided-indiv cell-line "HL-60" "NCIT:C19433" :name "HL60" :no-plural t) 
(def-ided-indiv cell-line "HLE-B3" "CVCL:6367" :name "B-3" :no-plural t) 
(def-ided-indiv cell-line "HM3" "CVCL:9V24" :name "HM-3" :no-plural t) 
(def-ided-indiv cell-line "HM3KO" "CVCL:5620" :name "HM3KO" :no-plural t) 
(def-ided-indiv cell-line "HMC-1" "CVCL:0003" :name "HMC-1" :no-plural t) 
(def-ided-indiv cell-line "HMC-1.1" "CVCL:H206" :name "HMC-1.1" :no-plural t) 
(def-ided-indiv cell-line "HMC-1.2" "CVCL:H205" :name "HMC-1.2" :no-plural t) 
(def-ided-indiv cell-line "HMEC-1" "EFO:0005383" :name "HMEC1" :no-plural t) 
(def-ided-indiv cell-line "HMEEC-1" "CVCL:0E44" :name "HMEEC-1" :no-plural t) 
(def-ided-indiv cell-line "HMSC1" "CVCL:AX71" :name "HMSc1" :no-plural t) 
(def-ided-indiv cell-line "HMSC2" "CVCL:AX72" :name "HMSc2" :no-plural t) 
(def-ided-indiv cell-line "HMV-I" "CVCL:8233" :name "HMV-I" :no-plural t) 
(def-ided-indiv cell-line "HN1" "CVCL:8123" :name "HN-1" :no-plural t) 
(def-ided-indiv cell-line "HN10" "CVCL:8124" :name "HN-10" :no-plural t) 
(def-ided-indiv cell-line "HN12" "CVCL:5518" :name "WSU-HN12" :no-plural t) 
(def-ided-indiv cell-line "HN13" "CVCL:5519" :name "WSU-HN13" :no-plural t) 
(def-ided-indiv cell-line "HN2" "CVCL:8125" :name "HN-2" :no-plural t) 
(def-ided-indiv cell-line "HN30" "CVCL:5525" :name "WSU-HN30" :no-plural t) 
(def-ided-indiv cell-line "HN4" "CVCL:8127" :name "HN-4" :no-plural t) 
(def-ided-indiv cell-line "HN5" "CVCL:8128" :name "HN-5" :no-plural t) 
(def-ided-indiv cell-line "HN6" "CVCL:8129" :name "HN-6" :no-plural t) 
(def-ided-indiv cell-line "HN9" "CVCL:8132" :name "HN-9" :no-plural t) 
(def-ided-indiv cell-line "HNE2" "CVCL:FA07" :name "HNE-2" :no-plural t) 
(def-ided-indiv cell-line "HO-8910pm" "BTO:0005772" :name "HO-8910PM" :no-plural t) 
(def-ided-indiv cell-line "HO15.19" "CVCL:0311" :name "HO15.19" :no-plural t) 
(def-ided-indiv cell-line "HO8910-pm" "CVCL:0310" :name "HO-8910PM" :no-plural t) 
(def-ided-indiv cell-line "HPA" "CVCL:W418" :name "HPA" :no-plural t) 
(def-ided-indiv cell-line "HPAF-II" "CVCL_0313" :no-plural t) 
(def-ided-indiv cell-line "HPB-ALL" "CVCL:1820" :name "HPB-ALL" :no-plural t) 
(def-ided-indiv cell-line "HS-24" "CVCL:Y110" :name "HS-24" :no-plural t) 
(def-ided-indiv cell-line "HS5" "CVCL:3720" :name "HS-5" :no-plural t) 
(def-ided-indiv cell-line "HS68" "CVCL:0839" :name "Hs 68" :no-plural t) 
(def-ided-indiv cell-line "HSB-2" "CVCL:1859" :name "CCRF-HSB-2" :no-plural t) 
(def-ided-indiv cell-line "HSC-2" "CVCL:1287" :name "HSC-2" :no-plural t) 
(def-ided-indiv cell-line "HSC-3" "CVCL:1288" :name "HSC-3" :no-plural t) 
(def-ided-indiv cell-line "HSC-39" "CVCL:A385" :name "HSC-39" :no-plural t) 
(def-ided-indiv cell-line "HSC-4" "CVCL:1289" :name "HSC-4" :no-plural t) 
(def-ided-indiv cell-line "HSC-T6" "CVCL:0315" :name "HSC-T6" :no-plural t) 
(def-ided-indiv cell-line "HSC2" "CVCL:1287" :name "HSC-2" :no-plural t) 
(def-ided-indiv cell-line "HT-1080" "EFO:0002059" :name "HT1080" :no-plural t) 
(def-ided-indiv cell-line "HT-22" "CVCL:0321" :name "HT22" :no-plural t) 
(def-ided-indiv cell-line "HT-29" "EFO:0001193" :name "HT-29" :no-plural t) 
(def-ided-indiv cell-line "HT1376" "CVCL:1292" :name "HT-1376" :no-plural t) 
(def-ided-indiv cell-line "HT144" "CVCL:0318" :name "HT-144" :no-plural t) 
(def-ided-indiv cell-line "HT29" "CVCL:0320" :name "HT-29" :no-plural t) 
(def-ided-indiv cell-line "HT55" "CVCL:1294" :name "HT-55" :no-plural t) 
(def-ided-indiv cell-line "HTR-8" "CVCL:D728" :name "HTR-8" :no-plural t) 
(def-ided-indiv cell-line "HTR8" "CVCL:D728" :name "HTR-8" :no-plural t) 
(def-ided-indiv cell-line "HUC-F2" "CVCL:4682" :name "HUC-F2" :no-plural t) 
(def-ided-indiv cell-line "HUT78" "EFO:0002209" :name "HuT78" :no-plural t) 
(def-ided-indiv cell-line "HUVEC" "BTO:0001949" :name "HUVEC cell" :no-plural t) 
(def-ided-indiv cell-line "HaCaT" "EFO:0002056" :name "HaCaT" :no-plural t) 
(def-ided-indiv cell-line "Hct1" "CVCL:M747" :name "HCT-1" :no-plural t) 
(def-ided-indiv cell-line "HeLaS3" "EFO:0002791" :name "HeLa-S3" :no-plural t) 
(def-ided-indiv cell-line "Hec-1A" "EFO:0002191" :name "HEC1A" :no-plural t) 
(def-ided-indiv cell-line "Hec50co" "CVCL:4Y59" :name "Hec50Co" :no-plural t) 
(def-ided-indiv cell-line "Hep3B" "EFO:0002205" :name "Hep3B" :no-plural t) 
(def-ided-indiv cell-line "HepG2" "CVCL:0027" :name "Hep-G2" :no-plural t) 
(def-ided-indiv cell-line "HepG3" "CVCL:Y479" :name "HepG3" :no-plural t) 
(def-ided-indiv cell-line "Hepa-1" "CVCL:S550" :name "Hepa-1" :no-plural t) 
(def-ided-indiv cell-line "Hepa1-6" "CVCL:0327" :name "Hepa 1-6" :no-plural t) 
(def-ided-indiv cell-line "Het-1A" "CVCL_3702" :no-plural t) 
(def-ided-indiv cell-line "HeyA8" "CVCL:8878" :name "HEY A8" :no-plural t) 
(def-ided-indiv cell-line "Hkh2" "CVCL:9797" :name "HKh-2" :no-plural t) 
(def-ided-indiv cell-line "Hs 578T" "CVCL_0332" :no-plural t) 
(def-ided-indiv cell-line "Hs683" "CVCL:0844" :name "Hs 683" :no-plural t) 
(def-ided-indiv cell-line "Hs766T" "CVCL:0334" :name "Hs 766T" :no-plural t) 
(def-ided-indiv cell-line "HuCCA-1" "CVCL:M255" :name "HuCC-A1" :no-plural t) 
(def-ided-indiv cell-line "HuCCT-1" "CVCL_0324" :no-plural t) 
(def-ided-indiv cell-line "HuTu80" "CVCL:1301" :name "HuTu 80" :no-plural t) 
(def-ided-indiv cell-line "Huh-1" "CVCL:2956" :name "HuH-1" :no-plural t) 
(def-ided-indiv cell-line "Huh-7" "EFO:0005384" :name "HuH-7" :no-plural t) 
(def-ided-indiv cell-line "Huh6" "CVCL:4381" :name "HuH-6" :no-plural t) 
(def-ided-indiv cell-line "Huh7" "EFO:0005384" :name "HuH-7" :no-plural t) 
(def-ided-indiv cell-line "IB3" "CVCL:0338" :name "IB3-1" :no-plural t) 
(def-ided-indiv cell-line "IB4" "CVCL:0339" :name "IB4" :no-plural t) 
(def-ided-indiv cell-line "IC-2" "CVCL:0341" :name "IC-2" :no-plural t) 
(def-ided-indiv cell-line "ICG" "CVCL:1G91" :name "ICG" :no-plural t) 
(def-ided-indiv cell-line "IEC-18" "CVCL:0342" :name "IEC-18" :no-plural t) 
(def-ided-indiv cell-line "IEC-6" "CVCL:0343" :name "IEC-6" :no-plural t) 
(def-ided-indiv cell-line "IGR-OV1" "NCIT:C117204" :name "IGR-OV1" :no-plural t) 
(def-ided-indiv cell-line "IGROV1" "CVCL:1304" :name "IGROV-1" :no-plural t) 
(def-ided-indiv cell-line "IM-9" "CVCL:1305" :name "IM-9" :no-plural t) 
(def-ided-indiv cell-line "IMR-32" "EFO:0001195" :name "IMR-32" :no-plural t) 
(def-ided-indiv cell-line "IMR-90" "CVCL:0347" :name "IMR-90" :no-plural t) 
(def-ided-indiv cell-line "IMR5" "CVCL:1306" :name "IMR-5" :no-plural t) 
(def-ided-indiv cell-line "IMR90" "CVCL:0347" :name "IMR-90" :no-plural t) 
(def-ided-indiv cell-line "INA-6" "EFO:0005386" :name "INA-6" :no-plural t) 
(def-ided-indiv cell-line "INS-1" "EFO:0002529" :name "INS-1" :no-plural t) 
(def-ided-indiv cell-line "INS-1E" "CVCL:0351" :name "INS-1E" :no-plural t) 
(def-ided-indiv cell-line "INS1" "CVCL:0352" :name "INS-1" :no-plural t) 
(def-ided-indiv cell-line "IOMM-Lee" "CVCL:5779" :name "IOMM-Lee" :no-plural t) 
(def-ided-indiv cell-line "IOSE-29" "CVCL:5535" :name "IOSE-29" :no-plural t) 
(def-ided-indiv cell-line "IOSE-80PC" "CVCL:5547" :name "IOSE-80PC" :no-plural t) 
(def-ided-indiv cell-line "IOSE397" "CVCL:5541" :name "IOSE-397" :no-plural t) 
(def-ided-indiv cell-line "IPH-926" "CVCL:A625" :name "IPH-926" :no-plural t) 
(def-ided-indiv cell-line "IRS-3" "CVCL:1N53" :name "irs3" :no-plural t) 
(def-ided-indiv cell-line "Ins2" "CVCL:J993" :name "INS-2" :no-plural t) 
(def-ided-indiv cell-line "Ishikawa" "CVCL:2529" :name "Ishikawa" :no-plural t) 
(def-ided-indiv cell-line "JAR" "EFO:0002211" :name "JAR" :no-plural t) 
(def-ided-indiv cell-line "JB6" "CVCL:H633" :name "JB6 [Human anaplastic large cell lymphoma]" :no-plural t) 
(def-ided-indiv cell-line "JCaM1" "CVCL:0354" :name "J.CaM1.6" :no-plural t) 
(def-ided-indiv cell-line "JCaM1.6" "CVCL:0354" :name "J.CaM1.6" :no-plural t) 
(def-ided-indiv cell-line "JEG-3" "EFO:0002066" :name "JEG3" :no-plural t) 
(def-ided-indiv cell-line "JH2" "CVCL:V634" :name "JH-2/TPA" :no-plural t) 
(def-ided-indiv cell-line "JHH6" "CVCL:2788" :name "JHH-6" :no-plural t) 
(def-ided-indiv cell-line "JHUEM7" "CVCL:4658" :name "JHUEM-7" :no-plural t) 
(def-ided-indiv cell-line "JIMT-1" "CVCL:2077" :name "JIMT-1" :no-plural t) 
(def-ided-indiv cell-line "JM1" "CVCL:3532" :name "JM-1" :no-plural t) 
(def-ided-indiv cell-line "Jeko-1" "EFO:0005387" :name "JeKo-1" :no-plural t) 
(def-ided-indiv cell-line "J–L" "CVCL:F563" :name "JL" :no-plural t) 
(def-ided-indiv cell-line "K562" "CVCL_0004" :no-plural t) 
(def-ided-indiv cell-line "KARPAS-299" "CVCL:1324" :name "Karpas-299" :no-plural t) 
(def-ided-indiv cell-line "KARPAS422" "CVCL:1325" :name "Karpas-422" :no-plural t) 
(def-ided-indiv cell-line "KAT-10" "CVCL:6302" :name "KAT-10" :no-plural t) 
(def-ided-indiv cell-line "KCL22" "CVCL:2091" :name "KCL-22" :no-plural t) 
(def-ided-indiv cell-line "KCP-4" "CVCL:M123" :name "KCP-4" :no-plural t) 
(def-ided-indiv cell-line "KG-1" "CVCL:0374" :name "KG-1" :no-plural t) 
(def-ided-indiv cell-line "KG1" "CVCL:0374" :name "KG-1" :no-plural t) 
(def-ided-indiv cell-line "KG1a" "CVCL:1824" :name "KG-1a" :no-plural t) 
(def-ided-indiv cell-line "KH2" "CVCL:C317" :name "KH2" :no-plural t) 
(def-ided-indiv cell-line "KK47" "CVCL:8253" :name "KK47" :no-plural t) 
(def-ided-indiv cell-line "KM12C" "CVCL:9547" :name "KM12-C" :no-plural t) 
(def-ided-indiv cell-line "KM12L4A" "CVCL:W220" :name "KM12-L4A" :no-plural t) 
(def-ided-indiv cell-line "KM12SM" "CVCL:9548" :name "KM12-SM" :no-plural t) 
(def-ided-indiv cell-line "KM20" "CVCL:L095" :name "KM20" :no-plural t) 
(def-ided-indiv cell-line "KO1" "CVCL:J425" :name "KO-1" :no-plural t) 
(def-ided-indiv cell-line "KOPTK1" "EFO:0006283" :name "KOPT-K1" :no-plural t) 
(def-ided-indiv cell-line "KP2" "CVCL:3004" :name "KP-2" :no-plural t) 
(def-ided-indiv cell-line "KPD" "CVCL:B412" :name "KPD" :no-plural t) 
(def-ided-indiv cell-line "KT-1" "CVCL:F690" :name "K-T1" :no-plural t) 
(def-ided-indiv cell-line "KT-3" "CVCL:6293" :name "KT-3" :no-plural t) 
(def-ided-indiv cell-line "KU812" "CVCL:0379" :name "Ku812" :no-plural t) 
(def-ided-indiv cell-line "KVL-1" "CVCL:0380" :name "KVL-1" :no-plural t) 
(def-ided-indiv cell-line "KYSE-30" "CVCL:1351" :name "KYSE-30" :no-plural t) 
(def-ided-indiv cell-line "KYSE150" "CVCL:1348" :name "KYSE-150" :no-plural t) 
(def-ided-indiv cell-line "KYSE410" "CVCL:1352" :name "KYSE-410" :no-plural t) 
(def-ided-indiv cell-line "KYSE450" "CVCL:1353" :name "KYSE-450" :no-plural t) 
(def-ided-indiv cell-line "KYSE510" "CVCL:1354" :name "KYSE-510" :no-plural t) 
(def-ided-indiv cell-line "Kasumi-1" "CVCL:0589" :name "Kasumi-1" :no-plural t) 
(def-ided-indiv cell-line "Kyse30" "CVCL:1351" :name "KYSE-30" :no-plural t) 
(def-ided-indiv cell-line "L-cell" "CVCL:0462" :name "NCTC clone 929" :no-plural t) 
(def-ided-indiv cell-line "L-cells" "BTO:0000331" :name "L-929 cell" :no-plural t) 
(def-ided-indiv cell-line "LA-N-5" "CVCL:0389" :name "LA-N-5" :no-plural t) 
(def-ided-indiv cell-line "LA1" "CVCL:J832" :name "La1" :no-plural t) 
(def-ided-indiv cell-line "LA1-55N" "CVCL:2548" :name "LA1-55n" :no-plural t) 
(def-ided-indiv cell-line "LAD-2" "CVCL:0387" :name "LAD 2" :no-plural t) 
(def-ided-indiv cell-line "LAD2" "CVCL:0387" :name "LAD 2" :no-plural t) 
(def-ided-indiv cell-line "LAN-1" "CVCL:1827" :name "LA-N-1" :no-plural t) 
(def-ided-indiv cell-line "LAPC-4" "CVCL:4744" :name "LAPC-4" :no-plural t) 
(def-ided-indiv cell-line "LAPC4" "CVCL:4744" :name "LAPC-4" :no-plural t) 
(def-ided-indiv cell-line "LC-MS" "CVCL:1655" :name "RERF-LC-MS" :no-plural t) 
(def-ided-indiv cell-line "LCC1" "CVCL:DP50" :name "MCF7/LCC1" :no-plural t) 
(def-ided-indiv cell-line "LCC2" "CVCL:DP51" :name "MCF7/LCC2" :no-plural t) 
(def-ided-indiv cell-line "LCC9" "CVCL:DP52" :name "MCF7/LCC9" :no-plural t) 
(def-ided-indiv cell-line "LI90" "CVCL:0390" :name "LI90" :no-plural t) 
(def-ided-indiv cell-line "LIM-2405" "CVCL:4437" :name "LIM2405" :no-plural t) 
(def-ided-indiv cell-line "LIM1215" "CVCL:2574" :name "LIM1215" :no-plural t) 
(def-ided-indiv cell-line "LIM1899" "CVCL:4435" :name "LIM1899" :no-plural t) 
(def-ided-indiv cell-line "LM-5" "CVCL:9567" :name "SaOS-LM5" :no-plural t) 
(def-ided-indiv cell-line "LM8" "CVCL:6669" :name "LM8" :no-plural t) 
(def-ided-indiv cell-line "LN-18" "EFO:0006636" :name "LN-18" :no-plural t) 
(def-ided-indiv cell-line "LN-229" "EFO:0006637" :name "LN-229" :no-plural t) 
(def-ided-indiv cell-line "LN-382" "CVCL:3956" :name "LN-382" :no-plural t) 
(def-ided-indiv cell-line "LN229" "CVCL:0393" :name "LN-229" :no-plural t) 
(def-ided-indiv cell-line "LN428" "CVCL:3959" :name "LN-428" :no-plural t) 
(def-ided-indiv cell-line "LN444" "CVCL:3961" :name "LN-444" :no-plural t) 
(def-ided-indiv cell-line "LNCaP-AI" "CVCL:4791" :name "LNCaP-AI" :no-plural t) 
(def-ided-indiv cell-line "LNCaP-FGC" "CVCL:1379" :name "LNCaP clone FGC" :no-plural t) 
(def-ided-indiv cell-line "LNCaP-cl1" "CVCL:3872" :name "LNCaP-CL1" :no-plural t) 
(def-ided-indiv cell-line "LO2" "CVCL:6926" :name "L-02" :no-plural t) 
(def-ided-indiv cell-line "LP4" "CVCL:J835" :name "LP4.4" :no-plural t) 
(def-ided-indiv cell-line "LP6" "CVCL:V413" :name "LP6" :no-plural t) 
(def-ided-indiv cell-line "LPS141" "CVCL:M823" :name "LPS141" :no-plural t) 
(def-ided-indiv cell-line "LS-180" "CVCL:0397" :name "LS180" :no-plural t) 
(def-ided-indiv cell-line "LU1205" "CVCL:5239" :name "1205Lu" :no-plural t) 
(def-ided-indiv cell-line "LX-2" "CVCL:5792" :name "LX-2" :no-plural t) 
(def-ided-indiv cell-line "Lag" "CVCL:B950" :name "LAG" :no-plural t) 
(def-ided-indiv cell-line "LbetaT2" "EFO:0002070" :name "LbetaT2" :no-plural t) 
(def-ided-indiv cell-line "Lovo" "CVCL:0399" :name "LoVo" :no-plural t) 
(def-ided-indiv cell-line "Ls174T" "EFO:0002227" :name "LS174T" :no-plural t) 
(def-ided-indiv cell-line "Ly3" "CVCL:8800" :name "OCI-Ly3" :no-plural t) 
(def-ided-indiv cell-line "M059J" "CVCL:0400" :name "M059J" :no-plural t) 
(def-ided-indiv cell-line "M2-10B4" "CVCL:5794" :name "M2-10B4" :no-plural t) 
(def-ided-indiv cell-line "MA-10" "CVCL:D789" :name "MA-10" :no-plural t) 
(def-ided-indiv cell-line "MA-3" "CVCL:7068" :name "Ma-3" :no-plural t) 
(def-ided-indiv cell-line "MAC-2A" "CVCL:H637" :name "Mac-2A" :no-plural t) 
(def-ided-indiv cell-line "MB-02" "CVCL:7075" :name "MB-02" :no-plural t) 
(def-ided-indiv cell-line "MB-231" "CVCL:0062" :name "MDA-MB-231" :no-plural t) 
(def-ided-indiv cell-line "MB231" "CVCL:0062" :name "MDA-MB-231" :no-plural t) 
(def-ided-indiv cell-line "MB49" "CVCL:7076" :name "MB49" :no-plural t) 
(def-ided-indiv cell-line "MC3T3-E1" "CVCL:0409" :name "MC3T3-E1" :no-plural t) 
(def-ided-indiv cell-line "MC3T3E1" "CVCL:0409" :name "MC3T3-E1" :no-plural t) 
(def-ided-indiv cell-line "MC5" "CVCL:1N49" :name "MC5" :no-plural t) 
(def-ided-indiv cell-line "MCC-1" "CVCL:D730" :name "MCC-1" :no-plural t) 
(def-ided-indiv cell-line "MCF-10-2A" "CVCL:3743" :name "MCF-10-2A" :no-plural t) 
(def-ided-indiv cell-line "MCF-12A" "CVCL:3744" :name "MCF-12A" :no-plural t) 
(def-ided-indiv cell-line "MCF-7" "CVCL:0031" :name "MCF-7" :no-plural t) 
(def-ided-indiv cell-line "MCF10A" "CVCL:0598" :name "MCF-10A" :no-plural t) 
(def-ided-indiv cell-line "MCF10DCIS" "CVCL:5552" :name "MCF10DCIS.com" :no-plural t) 
(def-ided-indiv cell-line "MCF12A" "CVCL:3744" :name "MCF-12A" :no-plural t) 
(def-ided-indiv cell-line "MCF7" "CVCL:0031" :name "MCF-7" :no-plural t) 
(def-ided-indiv cell-line "MCF7-ADR" "CVCL:1452" :name "NCI-ADR-RES" :no-plural t) 
(def-ided-indiv cell-line "MCF7r" "CVCL:Y493" :name "MCF-7R" :no-plural t) 
(def-ided-indiv cell-line "MD-2" "CVCL:9220" :name "MD2" :no-plural t) 
(def-ided-indiv cell-line "MDA-231" "CVCL:0062" :name "MDA-MB-231" :no-plural t) 
(def-ided-indiv cell-line "MDA-361" "CVCL:0620" :name "MDA-MB-361" :no-plural t) 
(def-ided-indiv cell-line "MDA-435" "CVCL:0417" :name "MDA-MB-435" :no-plural t) 
(def-ided-indiv cell-line "MDA-453" "CVCL:0418" :name "MDA-MB-453" :no-plural t) 
(def-ided-indiv cell-line "MDA-468" "CVCL:0419" :name "MDA-MB-468" :no-plural t) 
(def-ided-indiv cell-line "MDA-IBC-3" "CVCL:HC47" :name "MDA-IBC-3" :no-plural t) 
(def-ided-indiv cell-line "MDA-MB-134" "CVCL:0617" :name "MDA-MB-134-VI" :no-plural t) 
(def-ided-indiv cell-line "MDA-MB-175" "CVCL:1400" :name "MDA-MB-175-VII" :no-plural t) 
(def-ided-indiv cell-line "MDA-MB-415" "EFO:0001212" :name "MDAMB415" :no-plural t) 
(def-ided-indiv cell-line "MDA-MB-436" "EFO:0001214" :name "MDAMB436" :no-plural t) 
(def-ided-indiv cell-line "MDA-MB157" "CVCL:0618" :name "MDA-MB-157" :no-plural t) 
(def-ided-indiv cell-line "MDA-MB231" "CVCL:0062" :name "MDA-MB-231" :no-plural t) 
(def-ided-indiv cell-line "MDA-PCa-2b" "CVCL:4748" :name "MDA-PCa-2b" :no-plural t) 
(def-ided-indiv cell-line "MDA231" "CVCL:0062" :name "MDA-MB-231" :no-plural t) 
(def-ided-indiv cell-line "MDAH2774" "CVCL:0420" :name "MDAH 2774" :no-plural t) 
(def-ided-indiv cell-line "MDAMB-231" "EFO:0001209" :name "MDAMB231" :no-plural t) 
(def-ided-indiv cell-line "MDAMB468" "EFO:0001216" :name "MDAMB468" :no-plural t) 
(def-ided-indiv cell-line "MDBK" "CVCL:0421" :name "MDBK" :no-plural t) 
(def-ided-indiv cell-line "MDPC-23" "CVCL:0E50" :name "MDPC-23" :no-plural t) 
(def-ided-indiv cell-line "MEF1" "CVCL:G312" :name "ME-F1" :no-plural t) 
(def-ided-indiv cell-line "MES-13" "CVCL:5368" :name "SV40 MES 13" :no-plural t) 
(def-ided-indiv cell-line "MES-SA" "CVCL:1404" :name "MES-SA" :no-plural t) 
(def-ided-indiv cell-line "MES23.5" "CVCL:J351" :name "MES23.5" :no-plural t) 
(def-ided-indiv cell-line "MFE-296" "CVCL:1406" :name "MFE-296" :no-plural t) 
(def-ided-indiv cell-line "MG-63" "EFO:0002234" :name "MG63" :no-plural t) 
(def-ided-indiv cell-line "MGC-803" "CVCL:5334" :name "MGC-803" :no-plural t) 
(def-ided-indiv cell-line "MH2" "CVCL:AT89" :name "MH-2" :no-plural t) 
(def-ided-indiv cell-line "MHCC-97H" "CVCL:4972" :name "MHCC97-H" :no-plural t) 
(def-ided-indiv cell-line "MHCC97H" "CVCL:4972" :name "MHCC97-H" :no-plural t) 
(def-ided-indiv cell-line "MIA-PaCa-2" "CVCL:0428" :name "MIA PaCa-2" :no-plural t) 
(def-ided-indiv cell-line "MIN-6" "EFO:0002829" :name "MIN6" :no-plural t) 
(def-ided-indiv cell-line "MKN-1" "CVCL:1415" :name "MKN1" :no-plural t) 
(def-ided-indiv cell-line "MKN-28" "CVCL:1416" :name "MKN28" :no-plural t) 
(def-ided-indiv cell-line "MKN-45" "CVCL:0434" :name "MKN45" :no-plural t) 
(def-ided-indiv cell-line "MKN-7" "CVCL:1417" :name "MKN7" :no-plural t) 
(def-ided-indiv cell-line "MKN-74" "CVCL:2791" :name "MKN74" :no-plural t) 
(def-ided-indiv cell-line "MLE-12" "CVCL:3751" :name "MLE-12" :no-plural t) 
(def-ided-indiv cell-line "MLO-Y4" "EFO:0005394" :name "MLO-Y4" :no-plural t) 
(def-ided-indiv cell-line "MLP1" "CVCL:W533" :name "MLP-1" :no-plural t) 
(def-ided-indiv cell-line "MM1" "EFO:0001219" :name "MM1" :no-plural t) 
(def-ided-indiv cell-line "MM2" "CVCL:B428" :name "MM2" :no-plural t) 
(def-ided-indiv cell-line "MM200" "CVCL:C836" :name "MM200" :no-plural t) 
(def-ided-indiv cell-line "MM608" "CVCL:4453" :name "MM608" :no-plural t) 
(def-ided-indiv cell-line "MMNK-1" "CVCL:M266" :name "MMNK-1" :no-plural t) 
(def-ided-indiv cell-line "MN-1" "CVCL:W126" :name "MN-1" :no-plural t) 
(def-ided-indiv cell-line "MNNG" "CVCL:0439" :name "MNNG/HOS Cl #5" :no-plural t) 
(def-ided-indiv cell-line "MNT-1" "CVCL:5624" :name "MNT-1" :no-plural t) 
(def-ided-indiv cell-line "MO59J" "CVCL:0400" :name "M059J" :no-plural t) 
(def-ided-indiv cell-line "MO7" "CVCL:D630" :name "M-07" :no-plural t) 
(def-ided-indiv cell-line "MOLM-13" "CVCL:2119" :name "MOLM-13" :no-plural t) 
(def-ided-indiv cell-line "MOLM13" "CVCL:2119" :name "MOLM-13" :no-plural t) 
(def-ided-indiv cell-line "MOLM14" "CVCL:7916" :name "MOLM-14" :no-plural t) 
(def-ided-indiv cell-line "MOLT-4" "NCIT:C117119" :name "MOLT-4" :no-plural t) 
(def-ided-indiv cell-line "MOLT16" "EFO:0002239" :name "MOLT16" :no-plural t) 
(def-ided-indiv cell-line "MOLT3" "EFO:0005265" :name "MOLT-3" :no-plural t) 
(def-ided-indiv cell-line "MOR" "CVCL:2618" :name "MOR" :no-plural t) 
(def-ided-indiv cell-line "MPC5" "CVCL:AS87" :name "MPC-5" :no-plural t) 
(def-ided-indiv cell-line "MPM-2" "CVCL:D528" :name "MPM2" :no-plural t) 
(def-ided-indiv cell-line "MR-1" "CVCL:8964" :name "MR1" :no-plural t) 
(def-ided-indiv cell-line "MRC-5" "EFO:0002835" :name "MRC5" :no-plural t) 
(def-ided-indiv cell-line "MRC5CV1" "CVCL:E260" :name "MRC-5 CV1" :no-plural t) 
(def-ided-indiv cell-line "MS-1" "EFO:0002836" :name "MS-1" :no-plural t) 
(def-ided-indiv cell-line "MS1" "CVCL:6502" :name "MS1" :no-plural t) 
(def-ided-indiv cell-line "MS5" "CVCL:2128" :name "MS-5" :no-plural t) 
(def-ided-indiv cell-line "MST1" "CVCL:0J34" :name "MST-1" :no-plural t) 
(def-ided-indiv cell-line "MST3" "CVCL:0J36" :name "MST-3" :no-plural t) 
(def-ided-indiv cell-line "MSTO-211H" "EFO:0002839" :name "MSTO-211H" :no-plural t) 
(def-ided-indiv cell-line "MT-CHC01" "CVCL:4Z41" :name "MT-CHC01" :no-plural t) 
(def-ided-indiv cell-line "MTLn3" "CVCL:8136" :name "MTLn3" :no-plural t) 
(def-ided-indiv cell-line "MV3" "CVCL:W280" :name "MV3" :no-plural t) 
(def-ided-indiv cell-line "MV4-11" "CVCL:0064" :name "MV4-11" :no-plural t) 
(def-ided-indiv cell-line "MV4–11" "CVCL:0064" :name "MV4-11" :no-plural t) 
(def-ided-indiv cell-line "MWCL-1" "CVCL:M086" :name "MWCL-1" :no-plural t) 
(def-ided-indiv cell-line "MX-1" "EFO:0006457" :name "MX-1" :no-plural t) 
(def-ided-indiv cell-line "Ma-Mel-65" "CVCL:A200" :name "Ma-Mel-65" :no-plural t) 
(def-ided-indiv cell-line "Malme-3M" "CVCL:1438" :name "Malme-3M" :no-plural t) 
(def-ided-indiv cell-line "Malme3M" "EFO:0002243" :name "Malme3M" :no-plural t) 
(def-ided-indiv cell-line "Maver-1" "CVCL:1831" :name "MAVER-1" :no-plural t) 
(def-ided-indiv cell-line "Mel-18" "CVCL:H201" :name "Mel-18" :no-plural t) 
(def-ided-indiv cell-line "Mel-CV" "CVCL:S996" :name "Mel-CV" :no-plural t) 
(def-ided-indiv cell-line "Mel202" "CVCL:C301" :name "Mel202" :no-plural t) 
(def-ided-indiv cell-line "Melan-a" "CVCL:4624" :name "Melan-a" :no-plural t) 
(def-ided-indiv cell-line "Mero-41" "CVCL:2592" :name "Mero-41" :no-plural t) 
(def-ided-indiv cell-line "Mero-48a" "CVCL:2593" :name "Mero-48a" :no-plural t) 
(def-ided-indiv cell-line "Met5A" "EFO:0001218" :name "Met5A" :no-plural t) 
(def-ided-indiv cell-line "MiaPaCa2" "CVCL:0428" :name "MIA PaCa-2" :no-plural t) 
(def-ided-indiv cell-line "Mit" "CVCL:D526" :name "MIT" :no-plural t) 
(def-ided-indiv cell-line "Mo-7e" "CVCL:2106" :name "M-07e" :no-plural t) 
(def-ided-indiv cell-line "Mo7e" "CVCL:2106" :name "M-07e" :no-plural t) 
(def-ided-indiv cell-line "MonoMac-6" "CVCL:1426" :name "Mono-Mac-6" :no-plural t) 
(def-ided-indiv cell-line "Mst2" "CVCL:0J35" :name "MST-2" :no-plural t) 
(def-ided-indiv cell-line "Mv1Lu" "CVCL:0593" :name "Mv1Lu" :no-plural t) 
(def-ided-indiv cell-line "Mz-Cha-1" "CVCL:6932" :name "Mz-ChA-1" :no-plural t) 
(def-ided-indiv cell-line "N-IC" "CVCL:F577" :name "NIC" :no-plural t) 
(def-ided-indiv cell-line "N15C6" "CVCL:4749" :name "N15C6" :no-plural t) 
(def-ided-indiv cell-line "N1E-115" "CVCL:0451" :name "N1E-115" :no-plural t) 
(def-ided-indiv cell-line "N2a" "CVCL:0470" :name "Neuro-2a" :no-plural t) 
(def-ided-indiv cell-line "N2aSW" "CVCL:D650" :name "N2aSW" :no-plural t) 
(def-ided-indiv cell-line "N87" "CVCL_1603" :no-plural t) 
(def-ided-indiv cell-line "NALM6" "CVCL_0092" :no-plural t) 
(def-ided-indiv cell-line "NAP" "CVCL:HF46" :name "NAP" :no-plural t) 
(def-ided-indiv cell-line "NB-1691" "CVCL:5628" :name "NB-1691" :no-plural t) 
(def-ided-indiv cell-line "NB2a" "CVCL:0470" :name "Neuro-2a" :no-plural t) 
(def-ided-indiv cell-line "NB4-R1" "CVCL:U085" :name "NB4-DR1" :no-plural t) 
(def-ided-indiv cell-line "NB69" "CVCL:1448" :name "NB69" :no-plural t) 
(def-ided-indiv cell-line "NB7" "CVCL:8824" :name "SJNB-7" :no-plural t) 
(def-ided-indiv cell-line "NBL-S" "CVCL:2136" :name "NBL-S" :no-plural t) 
(def-ided-indiv cell-line "NBT-II" "CVCL:0453" :name "NBT-II" :no-plural t) 
(def-ided-indiv cell-line "NC03" "NCIT:C20283" :name "NC03" :no-plural t) 
(def-ided-indiv cell-line "NCI-H1299" "EFO:0003043" :name "NCI-H1299" :no-plural t) 
(def-ided-indiv cell-line "NCI-H1975" "CVCL:1511" :name "NCI-H1975" :no-plural t) 
(def-ided-indiv cell-line "NCI-H1993" "CVCL:1512" :name "NCI-H1993" :no-plural t) 
(def-ided-indiv cell-line "NCI-H2052" "CVCL:1518" :name "NCI-H2052" :no-plural t) 
(def-ided-indiv cell-line "NCI-H226" "EFO:0002285" :name "NCI-H226" :no-plural t) 
(def-ided-indiv cell-line "NCI-H23" "EFO:0002286" :name "NCI-H23" :no-plural t) 
(def-ided-indiv cell-line "NCI-H28" "CVCL:1555" :name "NCI-H28" :no-plural t) 
(def-ided-indiv cell-line "NCI-H292" "CVCL_0455" :no-plural t) 
(def-ided-indiv cell-line "NCI-H322M" "CVCL:1557" :name "NCI-H322M" :no-plural t) 
(def-ided-indiv cell-line "NCI-H446" "EFO:0002293" :name "NCI-H446" :no-plural t) 
(def-ided-indiv cell-line "NCI-H460" "EFO:0003044" :name "NCI-H460" :no-plural t) 
(def-ided-indiv cell-line "NCI-H596" "EFO:0006694" :name "NCI-H596" :no-plural t) 
(def-ided-indiv cell-line "NCI-N87" "EFO:0002841" :name "NCI-N87" :no-plural t) 
(def-ided-indiv cell-line "NCM460" "CVCL:0460" :name "NCM460" :no-plural t) 
(def-ided-indiv cell-line "NG108-15" "CVCL:0464" :name "108CC15" :no-plural t) 
(def-ided-indiv cell-line "NHEKs" "EFO:0002799" :name "NHEK" :no-plural t) 
(def-ided-indiv cell-line "NIE-115" "CVCL:0451" :name "N1E-115" :no-plural t) 
(def-ided-indiv cell-line "NIH-OVCAR3" "CVCL:0465" :name "OVCAR-3" :no-plural t) 
(def-ided-indiv cell-line "NIH/3T3" "EFO:0001222" :name "NIH3T3" :no-plural t) 
(def-ided-indiv cell-line "NIM-1" "CVCL:5344" :name "NIM-1" :no-plural t) 
(def-ided-indiv cell-line "NJF" "CVCL_8822" :no-plural t) 
(def-ided-indiv cell-line "NK-92" "CVCL:2142" :name "NK-92" :no-plural t) 
(def-ided-indiv cell-line "NK3.3" "CVCL:7994" :name "NK3.3" :no-plural t) 
(def-ided-indiv cell-line "NM1" "CVCL:3074" :name "NM-1" :no-plural t) 
(def-ided-indiv cell-line "NOS2" "CVCL:3351" :name "NOS-2" :no-plural t) 
(def-ided-indiv cell-line "NSC34" "CVCL:D356" :name "NSC-34" :no-plural t) 
(def-ided-indiv cell-line "NT1" "EFO:0002707" :name "NT-1" :no-plural t) 
(def-ided-indiv cell-line "NT2" "CVCL:GZ03" :name "NT-2" :no-plural t) 
(def-ided-indiv cell-line "NTERA2" "EFO:0002959" :name "NTera2" :no-plural t) 
(def-ided-indiv cell-line "Nalm-6" "CVCL:0092" :name "NALM-6" :no-plural t) 
(def-ided-indiv cell-line "Nb2" "CVCL:G705" :name "Nb2" :no-plural t) 
(def-ided-indiv cell-line "Neuro2a" "CVCL:0470" :name "Neuro-2a" :no-plural t) 
(def-ided-indiv cell-line "NuTu-19" "CVCL:HA28" :name "NuTu-19" :no-plural t) 
(def-ided-indiv cell-line "OAW42" "EFO:0006705" :name "OAW42" :no-plural t) 
(def-ided-indiv cell-line "OC3" "CVCL:D859" :name "OC3" :no-plural t) 
(def-ided-indiv cell-line "OC314" "CVCL:1616" :name "OC 314" :no-plural t) 
(def-ided-indiv cell-line "OCI-AML-3" "CVCL:1844" :name "OCI-AML3" :no-plural t) 
(def-ided-indiv cell-line "OCI-Ly10" "CVCL:8795" :name "OCI-Ly10" :no-plural t) 
(def-ided-indiv cell-line "OCM1A" "CVCL:6935" :name "OCM-1A" :no-plural t) 
(def-ided-indiv cell-line "OCM3" "CVCL:6937" :name "OCM-3" :no-plural t) 
(def-ided-indiv cell-line "ODA" "CVCL_0G09" :no-plural t) 
(def-ided-indiv cell-line "OE19" "EFO:0002308" :name "OE19" :no-plural t) 
(def-ided-indiv cell-line "OE21" "EFO:0002309" :name "OE21" :no-plural t) 
(def-ided-indiv cell-line "OE33" "EFO:0002310" :name "OE33" :no-plural t) 
(def-ided-indiv cell-line "OEC-M1" "CVCL:6782" :name "OECM-1" :no-plural t) 
(def-ided-indiv cell-line "OECM1" "CVCL:6782" :name "OECM-1" :no-plural t) 
(def-ided-indiv cell-line "OKF6" "CVCL:L222" :name "OKF6" :no-plural t) 
(def-ided-indiv cell-line "OKT-3" "CVCL:2665" :name "OKT 3" :no-plural t) 
(def-ided-indiv cell-line "ONS-76" "CVCL:1624" :name "ONS-76" :no-plural t) 
(def-ided-indiv cell-line "OP9" "CVCL:4398" :name "OP9" :no-plural t) 
(def-ided-indiv cell-line "OPM-2" "EFO:0006716" :name "OPM-2" :no-plural t) 
(def-ided-indiv cell-line "ORs" "CVCL:U565" :name "ORS" :no-plural t) 
(def-ided-indiv cell-line "OS-RC-2" "CVCL:1626" :name "OS-RC-2" :no-plural t) 
(def-ided-indiv cell-line "OSC19" "CVCL:3086" :name "OSC-19" :no-plural t) 
(def-ided-indiv cell-line "OSRC-2" "CVCL:1626" :name "OS-RC-2" :no-plural t) 
(def-ided-indiv cell-line "OUMS27" "CVCL:3090" :name "OUMS-27" :no-plural t) 
(def-ided-indiv cell-line "OV167" "CVCL:A402" :name "OV167" :no-plural t) 
(def-ided-indiv cell-line "OV202" "CVCL:4067" :name "OV202" :no-plural t) 
(def-ided-indiv cell-line "OV207" "CVCL:A404" :name "OV207" :no-plural t) 
(def-ided-indiv cell-line "OV90" "CVCL:3768" :name "OV-90" :no-plural t) 
(def-ided-indiv cell-line "OVCA420" "EFO:0006720" :name "OVCA420" :no-plural t) 
(def-ided-indiv cell-line "OVCA433" "EFO:0006723" :name "OVCA433" :no-plural t) 
(def-ided-indiv cell-line "OVCAR3" "EFO:0003061" :name "OVCAR3" :no-plural t) 
(def-ided-indiv cell-line "OVCAR4" "CVCL:1627" :name "OVCAR-4" :no-plural t) 
(def-ided-indiv cell-line "OVCAR5" "CVCL:1628" :name "OVCAR-5" :no-plural t) 
(def-ided-indiv cell-line "OVCAR8" "CVCL:1629" :name "OVCAR-8" :no-plural t) 
(def-ided-indiv cell-line "OVK18" "CVCL:3770" :name "OVK18" :no-plural t) 
(def-ided-indiv cell-line "Ox-1" "CVCL:G677" :name "OX-1" :no-plural t) 
(def-ided-indiv cell-line "P3HR-1" "CVCL:2676" :name "P3HR-1" :no-plural t) 
(def-ided-indiv cell-line "P493-6" "CVCL:6783" :name "P493-6" :no-plural t) 
(def-ided-indiv cell-line "P4E6" "CVCL:2677" :name "P4E6" :no-plural t) 
(def-ided-indiv cell-line "PA-1" "CVCL:0479" :name "PA-1" :no-plural t) 
(def-ided-indiv cell-line "PA1" "CVCL:0479" :name "PA-1" :no-plural t) 
(def-ided-indiv cell-line "PAC-1" "CVCL:U511" :name "PAC1" :no-plural t) 
(def-ided-indiv cell-line "PAM212" "CVCL:7694" :name "Pam 212" :no-plural t) 
(def-ided-indiv cell-line "PAS" "CVCL:R914" :name "PAS" :no-plural t) 
(def-ided-indiv cell-line "PB-1" "CVCL:T881" :name "PB1" :no-plural t) 
(def-ided-indiv cell-line "PB5" "CVCL:C347" :name "PB05" :no-plural t) 
(def-ided-indiv cell-line "PBA" "CVCL:4T88" :name "Patas-BARF1" :no-plural t) 
(def-ided-indiv cell-line "PC-2" "CVCL:0483" :name "PC2" :no-plural t) 
(def-ided-indiv cell-line "PC-3M" "CVCL:9555" :name "PC-3M" :no-plural t) 
(def-ided-indiv cell-line "PC-3MM2" "CVCL:4885" :name "PC3-MM2" :no-plural t) 
(def-ided-indiv cell-line "PC-9" "EFO:0002847" :name "PC-9" :no-plural t) 
(def-ided-indiv cell-line "PC.3" "CVCL_0035" :no-plural t) 
(def-ided-indiv cell-line "PC12nnr5" "CVCL:C128" :name "PC12nnr5" :no-plural t) 
(def-ided-indiv cell-line "PC14PE6" "CVCL:9W70" :name "PC14PE6" :no-plural t) 
(def-ided-indiv cell-line "PC3" "CVCL:0035" :name "PC-3" :no-plural t) 
(def-ided-indiv cell-line "PC3-M" "CVCL:9555" :name "PC-3M" :no-plural t) 
(def-ided-indiv cell-line "PC3M" "CVCL:9555" :name "PC-3M" :no-plural t) 
(def-ided-indiv cell-line "PC4" "CVCL:7090" :name "PC4" :no-plural t) 
(def-ided-indiv cell-line "PC7" "CVCL:A786" :name "PC-7" :no-plural t) 
(def-ided-indiv cell-line "PC9" "EFO:0002847" :name "PC-9" :no-plural t) 
(def-ided-indiv cell-line "PC9/R" "CVCL:S750" :name "PC-9/R" :no-plural t) 
(def-ided-indiv cell-line "PCCL3" "CVCL:6712" :name "PCCL3" :no-plural t) 
(def-ided-indiv cell-line "PDH" "CVCL:1G98" :name "PDH" :no-plural t) 
(def-ided-indiv cell-line "PE-1" "CVCL:6G49" :name "PE-1" :no-plural t) 
(def-ided-indiv cell-line "PE1" "CVCL:6G49" :name "PE-1" :no-plural t) 
(def-ided-indiv cell-line "PEO-14" "CVCL:2687" :name "PEO14" :no-plural t) 
(def-ided-indiv cell-line "PF382" "CVCL:1641" :name "PF-382" :no-plural t) 
(def-ided-indiv cell-line "PFC" "CVCL:6F45" :name "PFC" :no-plural t) 
(def-ided-indiv cell-line "PFSK-1" "CVCL:1642" :name "PFSK-1" :no-plural t) 
(def-ided-indiv cell-line "PGF" "CVCL:E806" :name "PGF" :no-plural t) 
(def-ided-indiv cell-line "PIG1" "CVCL:S410" :name "PIG1" :no-plural t) 
(def-ided-indiv cell-line "PK-15" "CVCL:2160" :name "PK-15" :no-plural t) 
(def-ided-indiv cell-line "PKR" "CVCL:2693" :name "PKR" :no-plural t) 
(def-ided-indiv cell-line "PL-21" "EFO:0006473" :name "PL-21" :no-plural t) 
(def-ided-indiv cell-line "PMo" "CVCL:V647" :name "PMO" :no-plural t) 
(def-ided-indiv cell-line "PNT1-a" "CVCL:2163" :name "PNT1A" :no-plural t) 
(def-ided-indiv cell-line "PNT2-C2" "CVCL:4889" :name "PNT2-C2" :no-plural t) 
(def-ided-indiv cell-line "PPC1" "CVCL:4778" :name "PPC-1" :no-plural t) 
(def-ided-indiv cell-line "PR-2" "CVCL:T644" :name "LSCC-PR2" :no-plural t) 
(def-ided-indiv cell-line "PR2" "CVCL:T644" :name "LSCC-PR2" :no-plural t) 
(def-ided-indiv cell-line "PS120" "CVCL:0488" :name "PS120" :no-plural t) 
(def-ided-indiv cell-line "PSC" "CVCL:6G33" :name "P-SC(1)" :no-plural t) 
(def-ided-indiv cell-line "Pa4" "CVCL:D695" :name "Par-C5" :no-plural t) 
(def-ided-indiv cell-line "PanC1" "EFO:0002713" :name "Panc1" :no-plural t) 
(def-ided-indiv cell-line "Panc-Tu-1" "CVCL:4012" :name "PancTu-I" :no-plural t) 
(def-ided-indiv cell-line "Panc-Tu-I" "CVCL:4012" :name "PancTu-I" :no-plural t) 
(def-ided-indiv cell-line "Pnt-2" "CVCL:2164" :name "PNT2" :no-plural t) 
(def-ided-indiv cell-line "QGY-7703" "CVCL:6715" :name "QGY-7703" :no-plural t) 
(def-ided-indiv cell-line "QGY7701" "CVCL:6859" :name "QGY-7701" :no-plural t) 
(def-ided-indiv cell-line "QSG-7701" "CVCL:6944" :name "QSG-7701" :no-plural t) 
(def-ided-indiv cell-line "RAW264" "CVCL:0493" :name "RAW 264.7" :no-plural t) 
(def-ided-indiv cell-line "RAW264.7" "EFO:0001231" :name "RAW264.7" :no-plural t) 
(def-ided-indiv cell-line "RBE" "CVCL:4896" :name "RBE" :no-plural t) 
(def-ided-indiv cell-line "RBL-2H3" "CVCL:0591" :name "RBL-2H3" :no-plural t) 
(def-ided-indiv cell-line "RBL2H3" "CVCL:0591" :name "RBL-2H3" :no-plural t) 
(def-ided-indiv cell-line "RCC4" "CVCL:0498" :name "RCC4" :no-plural t) 
(def-ided-indiv cell-line "RD-ES" "CVCL:2169" :name "RD-ES" :no-plural t) 
(def-ided-indiv cell-line "REF-52" "CVCL:6848" :name "REF52" :no-plural t) 
(def-ided-indiv cell-line "RGC-5" "CVCL:4059" :name "RGC-5" :no-plural t) 
(def-ided-indiv cell-line "RGM1" "CVCL:0499" :name "RGM1" :no-plural t) 
(def-ided-indiv cell-line "RGS" "CVCL:1G60" :name "RGS" :no-plural t) 
(def-ided-indiv cell-line "RH4" "CVCL:5916" :name "Rh4" :no-plural t) 
(def-ided-indiv cell-line "RIE-1" "CVCL:6723" :name "RIE-1" :no-plural t) 
(def-ided-indiv cell-line "RIN-m5F" "CVCL:0501" :name "RIN-m5F" :no-plural t) 
(def-ided-indiv cell-line "RINm5F" "CVCL:0501" :name "RIN-m5F" :no-plural t) 
(def-ided-indiv cell-line "RK3E" "CVCL:0503" :name "RK3E" :no-plural t) 
(def-ided-indiv cell-line "RKO" "CVCL:0504" :name "RKO" :no-plural t) 
(def-ided-indiv cell-line "RL95–2" "CVCL:0505" :name "RL95-2" :no-plural t) 
(def-ided-indiv cell-line "RPE-1" "CVCL:4388" :name "hTERT-RPE1" :no-plural t) 
(def-ided-indiv cell-line "RPE1" "CVCL:4388" :name "hTERT-RPE1" :no-plural t) 
(def-ided-indiv cell-line "RS-1" "CVCL:8423" :name "RS-1" :no-plural t) 
(def-ided-indiv cell-line "RSF" "CVCL:R984" :name "RSF" :no-plural t) 
(def-ided-indiv cell-line "RT112" "CVCL:1670" :name "RT-112" :no-plural t) 
(def-ided-indiv cell-line "RT4" "CVCL:0036" :name "RT-4" :no-plural t) 
(def-ided-indiv cell-line "RWPE-1" "CVCL:3791" :name "RWPE-1" :no-plural t) 
(def-ided-indiv cell-line "RWPE1" "CVCL:3791" :name "RWPE-1" :no-plural t) 
(def-ided-indiv cell-line "Rat-1" "NCIT:C19584" :name "rat-1" :no-plural t) 
(def-ided-indiv cell-line "Rat1" "NCIT:C19584" :name "rat-1" :no-plural t) 
(def-ided-indiv cell-line "Rat1a" "CVCL:0512" :name "Rat1A" :no-plural t) 
(def-ided-indiv cell-line "Rat2" "CVCL:0513" :name "Rat2" :no-plural t) 
(def-ided-indiv cell-line "Rcho-1" "CVCL:7996" :name "Rcho-1" :no-plural t) 
(def-ided-indiv cell-line "Rec-1" "EFO:0002317" :name "REC1" :no-plural t) 
(def-ided-indiv cell-line "Rh1" "CVCL:1658" :name "Rh1" :no-plural t) 
(def-ided-indiv cell-line "Rh18" "CVCL:1659" :name "Rh18" :no-plural t) 
(def-ided-indiv cell-line "Rh2" "CVCL:A460" :name "Rh2" :no-plural t) 
(def-ided-indiv cell-line "Rh30" "CVCL:0041" :name "Rh30" :no-plural t) 
(def-ided-indiv cell-line "S2R+" "CVCL:Z831" :name "S2R+" :no-plural t) 
(def-ided-indiv cell-line "SAKA-T" "CVCL:HA37" :name "Saka-tert" :no-plural t) 
(def-ided-indiv cell-line "SBC-3" "EFO:0002854" :name "SBC-3" :no-plural t) 
(def-ided-indiv cell-line "SBF-1" "CVCL:R985" :name "SBF-1" :no-plural t) 
(def-ided-indiv cell-line "SBcl2" "CVCL:D732" :name "SBcl2" :no-plural t) 
(def-ided-indiv cell-line "SC1" "CVCL:6F19" :name "SC1" :no-plural t) 
(def-ided-indiv cell-line "SC5" "CVCL:6F24" :name "SC5" :no-plural t) 
(def-ided-indiv cell-line "SCC" "CVCL:1R13" :name "SCC-TC" :no-plural t) 
(def-ided-indiv cell-line "SCC-25" "EFO:0006483" :name "SCC-25" :no-plural t) 
(def-ided-indiv cell-line "SCC-9" "EFO:0006485" :name "SCC-9" :no-plural t) 
(def-ided-indiv cell-line "SCC12" "CVCL:4026" :name "SCC-12" :no-plural t) 
(def-ided-indiv cell-line "SCC13" "CVCL:4029" :name "SCC-13" :no-plural t) 
(def-ided-indiv cell-line "SCC25" "CVCL:1682" :name "SCC-25" :no-plural t) 
(def-ided-indiv cell-line "SCC40" "CVCL:M666" :name "SCC-40" :no-plural t) 
(def-ided-indiv cell-line "SCC61" "CVCL:7118" :name "SCC-61" :no-plural t) 
(def-ided-indiv cell-line "SCC9" "CVCL:1685" :name "SCC-9" :no-plural t) 
(def-ided-indiv cell-line "SCP" "CVCL:4298" :name "SCP" :no-plural t) 
(def-ided-indiv cell-line "SET-2" "EFO:0006486" :name "SET-2" :no-plural t) 
(def-ided-indiv cell-line "SF126" "CVCL:1688" :name "SF126" :no-plural t) 
(def-ided-indiv cell-line "SFK" "CVCL:R925" :name "SFK" :no-plural t) 
(def-ided-indiv cell-line "SG231" "CVCL:0519" :name "SG231" :no-plural t) 
(def-ided-indiv cell-line "SGC-996" "CVCL:M737" :name "SGC-996" :no-plural t) 
(def-ided-indiv cell-line "SGC7901" "CVCL:0520" :name "SGC-7901" :no-plural t) 
(def-ided-indiv cell-line "SH-SY-5Y" "CVCL:0019" :name "SH-SY5Y" :no-plural t) 
(def-ided-indiv cell-line "SH1" "CVCL:C722" :name "SH1" :no-plural t) 
(def-ided-indiv cell-line "SH4" "CVCL:1692" :name "SH-4" :no-plural t) 
(def-ided-indiv cell-line "SHS" "CVCL:6F94" :name "SHS" :no-plural t) 
(def-ided-indiv cell-line "SHSY5Y" "CVCL:0019" :name "SH-SY5Y" :no-plural t) 
(def-ided-indiv cell-line "SJN-B1" "CVCL:8812" :name "SJNB-1" :no-plural t) 
(def-ided-indiv cell-line "SK-BR-3" "EFO:0001236" :name "SKBR3" :no-plural t) 
(def-ided-indiv cell-line "SK-CO15" "CVCL:A337" :name "SK-CO-15" :no-plural t) 
(def-ided-indiv cell-line "SK-Hep-1" "CVCL:0525" :name "SK-HEP-1" :no-plural t) 
(def-ided-indiv cell-line "SK-Hep1" "CVCL:0525" :name "SK-HEP-1" :no-plural t) 
(def-ided-indiv cell-line "SK-LC-5" "CVCL:5473" :name "SK-LC-5" :no-plural t) 
(def-ided-indiv cell-line "SK-MEL 28" "CVCL_0526" :no-plural t) 
(def-ided-indiv cell-line "SK-MEL-1" "EFO:0002332" :name "SKMEL1" :no-plural t) 
(def-ided-indiv cell-line "SK-MEL-30" "CVCL:0039" :name "SK-MEL-30" :no-plural t) 
(def-ided-indiv cell-line "SK-MEL-5" "NCIT:C117190" :name "SK-MEL-5" :no-plural t) 
(def-ided-indiv cell-line "SK-MEL147" "CVCL:3876" :name "SK-MEL-147" :no-plural t) 
(def-ided-indiv cell-line "SK-MEL31" "CVCL:0600" :name "SK-MEL-31" :no-plural t) 
(def-ided-indiv cell-line "SK-MES-1" "CVCL:0630" :name "SK-MES-1" :no-plural t) 
(def-ided-indiv cell-line "SK-MG-4" "CVCL:8577" :name "SK-MG-4" :no-plural t) 
(def-ided-indiv cell-line "SK-Mel-13" "CVCL:6022" :name "SK-MEL-13" :no-plural t) 
(def-ided-indiv cell-line "SK-Mel173" "CVCL:6090" :name "SK-MEL-173" :no-plural t) 
(def-ided-indiv cell-line "SK-N-AS" "CVCL:1700" :name "SK-N-AS" :no-plural t) 
(def-ided-indiv cell-line "SK-N-BE" "CVCL:0528" :name "SK-N-BE(2)" :no-plural t) 
(def-ided-indiv cell-line "SK-N-MC" "CVCL:0530" :name "SK-N-MC" :no-plural t) 
(def-ided-indiv cell-line "SK-N-SH" "CVCL:0531" :name "SK-N-SH" :no-plural t) 
(def-ided-indiv cell-line "SK-NSH" "EFO:0003072" :name "SK-N-SH" :no-plural t) 
(def-ided-indiv cell-line "SK-OV3" "NCIT:C117210" :name "SK-OV-3" :no-plural t) 
(def-ided-indiv cell-line "SK-RC-26B" "CVCL:3120" :name "SK-RC-26B" :no-plural t) 
(def-ided-indiv cell-line "SK-RC-45" "CVCL:4016" :name "SK-RC-45" :no-plural t) 
(def-ided-indiv cell-line "SKCO15" "CVCL:A337" :name "SK-CO-15" :no-plural t) 
(def-ided-indiv cell-line "SKES1" "EFO:0002858" :name "SK-ES-1" :no-plural t) 
(def-ided-indiv cell-line "SKGT-4" "CVCL:2195" :name "SK-GT-4" :no-plural t) 
(def-ided-indiv cell-line "SKH-1" "CVCL:C124" :name "SKH1" :no-plural t) 
(def-ided-indiv cell-line "SKM-1" "EFO:0006753" :name "SKM-1" :no-plural t) 
(def-ided-indiv cell-line "SKMes1" "EFO:0002334" :name "SKMES1" :no-plural t) 
(def-ided-indiv cell-line "SKOV-3" "CVCL:0532" :name "SK-OV-3" :no-plural t) 
(def-ided-indiv cell-line "SKOV3" "EFO:0002340" :name "SKOV3" :no-plural t) 
(def-ided-indiv cell-line "SKmel23" "CVCL:6027" :name "SK-MEL-23" :no-plural t) 
(def-ided-indiv cell-line "SLN" "CVCL:S948" :name "SLN" :no-plural t) 
(def-ided-indiv cell-line "SM3" "CVCL:H202" :name "SM3" :no-plural t) 
(def-ided-indiv cell-line "SMMC-7721" "CVCL:0534" :name "SMMC-7721" :no-plural t) 
(def-ided-indiv cell-line "SMMC7721" "CVCL:0534" :name "SMMC-7721" :no-plural t) 
(def-ided-indiv cell-line "SN12C" "NCIT:C117216" :name "SN12C" :no-plural t) 
(def-ided-indiv cell-line "SNA" "CVCL:E831" :name "SNA-BLL" :no-plural t) 
(def-ided-indiv cell-line "SNB19" "CVCL:0535" :name "SNB-19" :no-plural t) 
(def-ided-indiv cell-line "SNU-1" "CVCL:0099" :name "SNU-1" :no-plural t) 
(def-ided-indiv cell-line "SNU-1079" "CVCL:5008" :name "SNU-1079" :no-plural t) 
(def-ided-indiv cell-line "SNU-1196" "CVCL:5015" :name "SNU-1196" :no-plural t) 
(def-ided-indiv cell-line "SNU-16" "CVCL:0076" :name "SNU-16" :no-plural t) 
(def-ided-indiv cell-line "SNU-182" "CVCL:0090" :name "SNU-182" :no-plural t) 
(def-ided-indiv cell-line "SNU-216" "EFO:0006754" :name "SNU-216" :no-plural t) 
(def-ided-indiv cell-line "SNU-245" "CVCL:5038" :name "SNU-245" :no-plural t) 
(def-ided-indiv cell-line "SNU-251" "CVCL:5040" :name "SNU-251" :no-plural t) 
(def-ided-indiv cell-line "SNU-407" "CVCL:5058" :name "SNU-407" :no-plural t) 
(def-ided-indiv cell-line "SNU-449" "CVCL:0454" :name "SNU-449" :no-plural t) 
(def-ided-indiv cell-line "SNU-5" "CVCL:0078" :name "SNU-5" :no-plural t) 
(def-ided-indiv cell-line "SNU-638" "EFO:0006758" :name "SNU-638" :no-plural t) 
(def-ided-indiv cell-line "SNU349" "CVCL:5054" :name "SNU-349" :no-plural t) 
(def-ided-indiv cell-line "SNU398" "CVCL:0077" :name "SNU-398" :no-plural t) 
(def-ided-indiv cell-line "SNU449" "CVCL:0454" :name "SNU-449" :no-plural t) 
(def-ided-indiv cell-line "SNU475" "CVCL:0497" :name "SNU-475" :no-plural t) 
(def-ided-indiv cell-line "SNU761" "CVCL:5089" :name "SNU-761" :no-plural t) 
(def-ided-indiv cell-line "SNU790" "CVCL:5093" :name "SNU-790" :no-plural t) 
(def-ided-indiv cell-line "SO-RB50" "CVCL:D543" :name "SO-Rb50" :no-plural t) 
(def-ided-indiv cell-line "SP53" "CVCL:C122" :name "SP-53" :no-plural t) 
(def-ided-indiv cell-line "SPC-A1" "CVCL:6955" :name "SPC-A1" :no-plural t) 
(def-ided-indiv cell-line "SQ20B" "CVCL:7138" :name "SQ-20B" :no-plural t) 
(def-ided-indiv cell-line "SR-786" "CVCL:2203" :name "SR-786" :no-plural t) 
(def-ided-indiv cell-line "ST-2" "CVCL:2205" :name "ST-2" :no-plural t) 
(def-ided-indiv cell-line "ST14A" "CVCL:M588" :name "ST14A" :no-plural t) 
(def-ided-indiv cell-line "ST88-14" "EFO:0006295" :name "ST88-14" :no-plural t) 
(def-ided-indiv cell-line "STKM2" "CVCL:M570" :name "STKM-2" :no-plural t) 
(def-ided-indiv cell-line "SU-DHL-5" "EFO:0002356" :name "SUDHL5" :no-plural t) 
(def-ided-indiv cell-line "SU-DHL-6" "EFO:0002357" :name "SUDHL6" :no-plural t) 
(def-ided-indiv cell-line "SUM-149" "EFO:0001240" :name "SUM149PT" :no-plural t) 
(def-ided-indiv cell-line "SUM-159" "CVCL:5423" :name "SUM159PT" :no-plural t) 
(def-ided-indiv cell-line "SUM-44-PE" "CVCL:3424" :name "SUM44PE" :no-plural t) 
(def-ided-indiv cell-line "SUM102" "CVCL:3421" :name "SUM102PT" :no-plural t) 
(def-ided-indiv cell-line "SUM1315" "CVCL:5589" :name "SUM1315MO2" :no-plural t) 
(def-ided-indiv cell-line "SUM149" "CVCL:3422" :name "SUM149PT" :no-plural t) 
(def-ided-indiv cell-line "SUM159" "CVCL:5423" :name "SUM159PT" :no-plural t) 
(def-ided-indiv cell-line "SUM185PE" "CVCL:5591" :name "SUM185PE" :no-plural t) 
(def-ided-indiv cell-line "SUM190" "CVCL:3423" :name "SUM190PT" :no-plural t) 
(def-ided-indiv cell-line "SUM229" "CVCL:5594" :name "SUM229PE" :no-plural t) 
(def-ided-indiv cell-line "SUM52" "CVCL:3425" :name "SUM52PE" :no-plural t) 
(def-ided-indiv cell-line "SUP-M2" "CVCL:2209" :name "SUP-M2" :no-plural t) 
(def-ided-indiv cell-line "SUPT-11" "CVCL:2210" :name "SUP-T11" :no-plural t) 
(def-ided-indiv cell-line "SW-13" "CVCL:0542" :name "SW13" :no-plural t) 
(def-ided-indiv cell-line "SW-839" "CVCL:3604" :name "SW839" :no-plural t) 
(def-ided-indiv cell-line "SW1088" "EFO:0002358" :name "SW1088" :no-plural t) 
(def-ided-indiv cell-line "SW1116" "EFO:0002359" :name "SW1116" :no-plural t) 
(def-ided-indiv cell-line "SW1353" "EFO:0002360" :name "SW1353" :no-plural t) 
(def-ided-indiv cell-line "SW1417" "EFO:0002361" :name "SW1417" :no-plural t) 
(def-ided-indiv cell-line "SW1736" "CVCL:3883" :name "SW1736" :no-plural t) 
(def-ided-indiv cell-line "SW1783" "EFO:0002364" :name "SW1783" :no-plural t) 
(def-ided-indiv cell-line "SW1990" "EFO:0002365" :name "SW1990" :no-plural t) 
(def-ided-indiv cell-line "SW48" "EFO:0002367" :name "SW48" :no-plural t) 
(def-ided-indiv cell-line "SW579" "CVCL:3603" :name "SW579" :no-plural t) 
(def-ided-indiv cell-line "SW620" "EFO:0002368" :name "SW620" :no-plural t) 
(def-ided-indiv cell-line "SWISS3T3" "CVCL:0120" :name "3T3-Swiss albino" :no-plural t) 
(def-ided-indiv cell-line "SY-5Y" "CVCL:0019" :name "SH-SY5Y" :no-plural t) 
(def-ided-indiv cell-line "Sal2" "CVCL:F122" :name "SAL2" :no-plural t) 
(def-ided-indiv cell-line "Scar" "CVCL:D621" :name "SK-OV-3/CBP" :no-plural t) 
(def-ided-indiv cell-line "Seg-1" "CVCL:8113" :name "SEG-1" :no-plural t) 
(def-ided-indiv cell-line "Sf9" "CVCL:0549" :name "Sf9" :no-plural t) 
(def-ided-indiv cell-line "Sim" "CVCL:0097" :name "SIM/EW27" :no-plural t) 
(def-ided-indiv cell-line "Sk-Mel-2" "CVCL:0069" :name "SK-MEL-2" :no-plural t) 
(def-ided-indiv cell-line "Skmel2" "EFO:0002079" :name "SK-MEL-2" :no-plural t) 
(def-ided-indiv cell-line "SupT1" "CVCL:1714" :name "SUP-T1" :no-plural t) 
(def-ided-indiv cell-line "Swan-71" "CVCL:D855" :name "Swan 71" :no-plural t) 
(def-ided-indiv cell-line "T-47D" "NCIT:C117228" :name "T-47D" :no-plural t) 
(def-ided-indiv cell-line "T-REx-293" "CVCL:D585" :name "T-REx-293" :no-plural t) 
(def-ided-indiv cell-line "T4-2" "CVCL:2501" :name "HMT-3522 T4-2" :no-plural t) 
(def-ided-indiv cell-line "T47D" "CVCL_0553" :no-plural t) 
(def-ided-indiv cell-line "TANK" "CVCL:0E95" :name "Tank" :no-plural t) 
(def-ided-indiv cell-line "TC-71" "CVCL:2213" :name "TC-71" :no-plural t) 
(def-ided-indiv cell-line "TC7" "CVCL:S881" :name "TC7" :no-plural t) 
(def-ided-indiv cell-line "TC71" "CVCL:2213" :name "TC-71" :no-plural t) 
(def-ided-indiv cell-line "TE-1" "CVCL:1759" :name "TE-1" :no-plural t) 
(def-ided-indiv cell-line "TE-13" "CVCL:4463" :name "TE-13" :no-plural t) 
(def-ided-indiv cell-line "TE-6" "CVCL:1765" :name "TE-6" :no-plural t) 
(def-ided-indiv cell-line "TE1" "CVCL:1759" :name "TE-1" :no-plural t) 
(def-ided-indiv cell-line "TE10" "CVCL:1760" :name "TE-10" :no-plural t) 
(def-ided-indiv cell-line "TE15" "CVCL:1763" :name "TE-15" :no-plural t) 
(def-ided-indiv cell-line "TE2" "CVCL:4455" :name "TE-2" :no-plural t) 
(def-ided-indiv cell-line "TE671" "CVCL:1756" :name "TE 671" :no-plural t) 
(def-ided-indiv cell-line "TE7" "CVCL:9972" :name "TE-7" :no-plural t) 
(def-ided-indiv cell-line "TE8" "CVCL:1766" :name "TE-8" :no-plural t) 
(def-ided-indiv cell-line "TG-2" "CVCL:F231" :name "TG2" :no-plural t) 
(def-ided-indiv cell-line "THLE-2" "CVCL:3803" :name "THLE-2" :no-plural t) 
(def-ided-indiv cell-line "THLE-5b" "CVCL:M209" :name "THLE-5" :no-plural t) 
(def-ided-indiv cell-line "THP-1" "CVCL:0006" :name "THP-1" :no-plural t) 
(def-ided-indiv cell-line "THP1" "CVCL:0006" :name "THP-1" :no-plural t) 
(def-ided-indiv cell-line "TK6" "CVCL:X907" :name "TK-6" :no-plural t) 
(def-ided-indiv cell-line "TLR1" "CVCL:F955" :name "TLR1" :no-plural t) 
(def-ided-indiv cell-line "TMK-1" "CVCL:4384" :name "TMK-1" :no-plural t) 
(def-ided-indiv cell-line "TMK1" "CVCL:4384" :name "TMK-1" :no-plural t) 
(def-ided-indiv cell-line "TMX2-28" "CVCL:6957" :name "MCF-7/TMX2-28" :no-plural t) 
(def-ided-indiv cell-line "TOV-21G" "CVCL:3613" :name "TOV-21G" :no-plural t) 
(def-ided-indiv cell-line "TOV112D" "EFO:0005263" :name "TOV-112D" :no-plural t) 
(def-ided-indiv cell-line "TPC-1" "CVCL_6298" :no-plural t) 
(def-ided-indiv cell-line "TRAMP-C1" "CVCL:3614" :name "TRAMP-C1" :no-plural t) 
(def-ided-indiv cell-line "TRAMP-C2" "CVCL:3615" :name "TRAMP-C2" :no-plural t) 
(def-ided-indiv cell-line "TS/A" "CVCL:F736" :name "TS/A" :no-plural t) 
(def-ided-indiv cell-line "TS2" "CVCL:A323" :name "TS-2" :no-plural t) 
(def-ided-indiv cell-line "TSA-201" "CVCL:2737" :name "tsA201" :no-plural t) 
(def-ided-indiv cell-line "TSG-6" "CVCL:S861" :name "TSG6" :no-plural t) 
(def-ided-indiv cell-line "TSM1" "CVCL:U157" :name "TSM1" :no-plural t) 
(def-ided-indiv cell-line "TTC642" "CVCL:8006" :name "TTC-642" :no-plural t) 
(def-ided-indiv cell-line "TUHR10TKB" "CVCL:5952" :name "TUHR10TKB" :no-plural t) 
(def-ided-indiv cell-line "TW-01" "CVCL:6008" :name "NPC-TW01" :no-plural t) 
(def-ided-indiv cell-line "Tca8113" "CVCL:6851" :name "Tca8113" :no-plural t) 
(def-ided-indiv cell-line "Te11" "CVCL:1761" :name "TE-11" :no-plural t) 
(def-ided-indiv cell-line "Tet21N" "CVCL:9812" :name "Tet21N" :no-plural t) 
(def-ided-indiv cell-line "Tm4" "CVCL:4327" :name "TM4" :no-plural t) 
(def-ided-indiv cell-line "Tu138" "CVCL:4910" :name "Tu 138" :no-plural t) 
(def-ided-indiv cell-line "Tu167" "CVCL:4912" :name "Tu 167" :no-plural t) 
(def-ided-indiv cell-line "Tu212" "CVCL:4915" :name "Tu 212" :no-plural t) 
(def-ided-indiv cell-line "Tu686" "CVCL:4916" :name "Tu 686" :no-plural t) 
(def-ided-indiv cell-line "U-20S" "CVCL:0042" :name "U2OS" :no-plural t) 
(def-ided-indiv cell-line "U-251" "CVCL_0021" :no-plural t) 
(def-ided-indiv cell-line "U-251MG" "CVCL:0021" :name "U-251MG" :no-plural t) 
(def-ided-indiv cell-line "U-2932" "EFO:0006499" :name "U-2932" :no-plural t) 
(def-ided-indiv cell-line "U-937" "CVCL:0007" :name "U-937" :no-plural t) 
(def-ided-indiv cell-line "U118MG" "CVCL:0633" :name "U-118MG" :no-plural t) 
(def-ided-indiv cell-line "U251-N" "CVCL:0021" :name "U-251MG" :no-plural t) 
(def-ided-indiv cell-line "U251MG" "CVCL:0021" :name "U-251MG" :no-plural t) 
(def-ided-indiv cell-line "U266" "CVCL_0566" :no-plural t) 
(def-ided-indiv cell-line "U343MGa" "CVCL:4773" :name "U-343MGa" :no-plural t) 
(def-ided-indiv cell-line "U373-MG" "CVCL:2219" :name "U-373MG ATCC" :no-plural t) 
(def-ided-indiv cell-line "U373MG" "CVCL:2219" :name "U-373MG ATCC" :no-plural t) 
(def-ided-indiv cell-line "U937" "CVCL_0007" :no-plural t) 
(def-ided-indiv cell-line "UACC893" "CVCL:1782" :name "UACC-893" :no-plural t) 
(def-ided-indiv cell-line "UKE-1" "EFO:0006307" :name "UKE1" :no-plural t) 
(def-ided-indiv cell-line "UM-SCC-22A" "CVCL:7731" :name "UM-SCC-22A" :no-plural t) 
(def-ided-indiv cell-line "UM-SCC-22B" "CVCL:7732" :name "UM-SCC-22B" :no-plural t) 
(def-ided-indiv cell-line "UM-SCC1" "CVCL:7707" :name "UM-SCC-1" :no-plural t) 
(def-ided-indiv cell-line "UM-SCC46" "CVCL:7758" :name "UM-SCC-46" :no-plural t) 
(def-ided-indiv cell-line "UM-UC-3" "CVCL:1783" :name "UM-UC-3" :no-plural t) 
(def-ided-indiv cell-line "UM1" "CVCL:W392" :name "UM-1" :no-plural t) 
(def-ided-indiv cell-line "UMR-106" "CVCL:3617" :name "UMR-106" :no-plural t) 
(def-ided-indiv cell-line "UMR106" "CVCL:3617" :name "UMR-106" :no-plural t) 
(def-ided-indiv cell-line "UMRC2" "CVCL:2739" :name "UM-RC-2" :no-plural t) 
(def-ided-indiv cell-line "UMSCC1" "CVCL:7707" :name "UM-SCC-1" :no-plural t) 
(def-ided-indiv cell-line "UMUC-3" "CVCL:1783" :name "UM-UC-3" :no-plural t) 
(def-ided-indiv cell-line "UMUC14" "CVCL:2747" :name "UM-UC-14" :no-plural t) 
(def-ided-indiv cell-line "UMUC2" "CVCL:8155" :name "UM-UC-2" :no-plural t) 
(def-ided-indiv cell-line "UMUC3" "EFO:0006771" :name "UM-UC-3" :no-plural t) 
(def-ided-indiv cell-line "UMUC6" "CVCL:2751" :name "UM-UC-6" :no-plural t) 
(def-ided-indiv cell-line "UPN-1" "CVCL:A795" :name "UPN1" :no-plural t) 
(def-ided-indiv cell-line "UT-7" "CVCL:2233" :name "UT-7" :no-plural t) 
(def-ided-indiv cell-line "UVL-10" "CVCL:DE21" :name "UVL-10" :no-plural t) 
(def-ided-indiv cell-line "UW-228-1" "CVCL:4460" :name "UW228-1" :no-plural t) 
(def-ided-indiv cell-line "UW228" "CVCL:8585" :name "UW228" :no-plural t) 
(def-ided-indiv cell-line "UW228-3" "CVCL:0573" :name "UW228-3" :no-plural t) 
(def-ided-indiv cell-line "VA-13" "CVCL:2759" :name "WI-38 VA13 subline 2RA" :no-plural t) 
(def-ided-indiv cell-line "VA13" "CVCL:2759" :name "WI-38 VA13 subline 2RA" :no-plural t) 
(def-ided-indiv cell-line "VC5" "CVCL:M545" :name "VC5" :no-plural t) 
(def-ided-indiv cell-line "VG1" "CVCL:0106" :name "VG-1" :no-plural t) 
(def-ided-indiv cell-line "VH1" "CVCL:V247" :name "V-H1" :no-plural t) 
(def-ided-indiv cell-line "VMM1" "CVCL:A732" :name "VMM1" :no-plural t) 
(def-ided-indiv cell-line "Vp1" "CVCL:5623" :name "INER-51/VP-1" :no-plural t) 
(def-ided-indiv cell-line "WA01" "CVCL:9771" :name "WA01" :no-plural t) 
(def-ided-indiv cell-line "WB-F344" "EFO:0002871" :name "WB-F344" :no-plural t) 
(def-ided-indiv cell-line "WCL2" "CVCL:DC12" :name "WCL2" :no-plural t) 
(def-ided-indiv cell-line "WEHI7.2" "CVCL:3950" :name "WEHI-7.2" :no-plural t) 
(def-ided-indiv cell-line "WI-38" "CVCL:0579" :name "WI-38" :no-plural t) 
(def-ided-indiv cell-line "WM115" "EFO:0002390" :name "WM115" :no-plural t) 
(def-ided-indiv cell-line "WM1205Lu" "CVCL:5239" :name "1205Lu" :no-plural t) 
(def-ided-indiv cell-line "WM1346" "CVCL:W886" :name "WM1346" :no-plural t) 
(def-ided-indiv cell-line "WM1361A" "CVCL:6788" :name "WM1361A" :no-plural t) 
(def-ided-indiv cell-line "WM1366" "CVCL:6789" :name "WM1366" :no-plural t) 
(def-ided-indiv cell-line "WM1552C" "CVCL:6472" :name "WM1552C" :no-plural t) 
(def-ided-indiv cell-line "WM164" "CVCL:7928" :name "WM164" :no-plural t) 
(def-ided-indiv cell-line "WM266" "CVCL:2765" :name "WM266-4" :no-plural t) 
(def-ided-indiv cell-line "WM278" "CVCL:6473" :name "WM278" :no-plural t) 
(def-ided-indiv cell-line "WM35" "CVCL:0580" :name "WM35" :no-plural t) 
(def-ided-indiv cell-line "WM3629" "CVCL:C275" :name "WM3629" :no-plural t) 
(def-ided-indiv cell-line "WM3854" "CVCL:6801" :name "WM3854" :no-plural t) 
(def-ided-indiv cell-line "WM793" "EFO:0002873" :name "WM793" :no-plural t) 
(def-ided-indiv cell-line "WM9" "CVCL:6806" :name "WM9" :no-plural t) 
(def-ided-indiv cell-line "WPMY-1" "CVCL:3814" :name "WPMY-1" :no-plural t) 
(def-ided-indiv cell-line "WRL68" "CVCL:0581" :name "WRL 68" :no-plural t) 
(def-ided-indiv cell-line "WSU-FSCCL" "CVCL:1903" :name "WSU-FSCCL" :no-plural t) 
(def-ided-indiv cell-line "WSU-HN6" "CVCL:5516" :name "WSU-HN6" :no-plural t) 
(def-ided-indiv cell-line "WT8" "CVCL:E889" :name "WT8" :no-plural t) 
(def-ided-indiv cell-line "WW1" "CVCL:N782" :name "WW1" :no-plural t) 
(def-ided-indiv cell-line "Wa2" "CVCL:M847" :name "Wa-2" :no-plural t) 
(def-ided-indiv cell-line "Wi38" "CVCL:0579" :name "WI-38" :no-plural t) 
(def-ided-indiv cell-line "Wt11" "CVCL:3539" :name "LNZTA3WT11" :no-plural t) 
(def-ided-indiv cell-line "X02" "CVCL:C657" :name "X-02" :no-plural t) 
(def-ided-indiv cell-line "XP30RO" "CVCL:7395" :name "XP30RO" :no-plural t) 
(def-ided-indiv cell-line "Y79" "CVCL_1893" :no-plural t) 
(def-ided-indiv cell-line "YAP" "CVCL:8467" :name "YAP" :no-plural t) 
(def-ided-indiv cell-line "YTS1" "CVCL:6746" :name "YTS-1" :no-plural t) 
(def-ided-indiv cell-line "ZEB2" "CVCL:6E09" :name "ZEB2" :no-plural t) 
(def-ided-indiv cell-line "ZK58" "CVCL:9920" :name "ZK-58" :no-plural t) 
(def-ided-indiv cell-line "ZL55" "CVCL:5908" :name "ZL55" :no-plural t) 
(def-ided-indiv cell-line "ZR751" "CVCL:0588" :name "ZR-75-1" :no-plural t) 
(def-ided-indiv cell-line "ZS-1" "CVCL:9R46" :name "ZS-1" :no-plural t) 
(def-ided-indiv cell-line "and-2" "CVCL:B527" :name "AND-2" :no-plural t) 
(def-ided-indiv cell-line "bc1" "CVCL:1079" :name "BC-1" :no-plural t) 
(def-ided-indiv cell-line "bl6" "CVCL:M564" :name "BL-6" :no-plural t) 
(def-ided-indiv cell-line "c26" "CVCL:J690" :name "HT 29/26" :no-plural t) 
(def-ided-indiv cell-line "caki-1" "CVCL:0234" :name "Caki-1" :no-plural t) 
(def-ided-indiv cell-line "cdr2" "CVCL:H172" :name "CDR2" :no-plural t) 
(def-ided-indiv cell-line "colo-357" "EFO:0002710" :name "COLO357" :no-plural t) 
(def-ided-indiv cell-line "ctb" "CVCL:9W61" :name "CTb" :no-plural t) 
(def-ided-indiv cell-line "cy18" "CVCL:1Q10" :name "CY18" :no-plural t) 
(def-ided-indiv cell-line "human keratinocyte" "CVCL_9T09" :no-plural t) 
(def-ided-indiv cell-line "human mammary 7" "CVCL_Y905" :no-plural t) 
(def-ided-indiv cell-line "mec1" "CVCL:1870" :name "MEC-1" :no-plural t) 
(def-ided-indiv cell-line "mt5" "CVCL:U900" :name "MT-5" :no-plural t) 
(def-ided-indiv cell-line "mul" "CVCL:E784" :name "MUL" :no-plural t) 
(def-ided-indiv cell-line "p15" "CVCL:6G55" :name "GEM-81 clone P15" :no-plural t) 
(def-ided-indiv cell-line "pG19" "CVCL:S409" :name "PG19" :no-plural t) 
(def-ided-indiv cell-line "pR8" "CVCL:Z909" :name "PR8" :no-plural t) 
(def-ided-indiv cell-line "pRNS-1-1" "CVCL:4890" :name "pRNS-1-1" :no-plural t) 
(def-ided-indiv cell-line "pS46" "CVCL:0E48" :name "PS 46" :no-plural t) 
(def-ided-indiv cell-line "rH3" "CVCL:L415" :name "Rh3" :no-plural t) 
(def-ided-indiv cell-line "sEH" "CVCL:R855" :name "SEH" :no-plural t) 
(def-ided-indiv cell-line "sHPT-1" "CVCL:0I22" :name "sHPT-1" :no-plural t) 
(def-ided-indiv cell-line "si60" "CVCL:B791" :name "RG-60" :no-plural t) 
(def-ided-indiv cell-line "s–2" "CVCL:4719" :name "S-2" :no-plural t) 
(def-ided-indiv cell-line "ts20" "CVCL:D594" :name "Ts20" :no-plural t) 
(def-ided-indiv cell-line "xrs6" "CVCL:4340" :name "CHO-xrs-6" :no-plural t) 

;;;------------
;;; cell types
;;;------------

;;(def-cell-type "mouse embryo fibroblast") ;; CORRECTED -- was not sure this is right -- it is a type of cell, but...
;;A fibroblast is a type of cell that synthesizes the extracellular matrix and collagen,[1] 
;; the structural framework (stroma) for animal tissues, and plays a critical role in wound healing. 
;; Fibroblasts are the most common cells of connective tissue in animals.
(noun "fibroblast" :super cell-type)
(noun "leukocyte" :super cell-type)
(noun "astrocyte" :super cell-type) ; fixed -- was "astroocyte"
(noun "neuron" :super cell-type)

(noun "MenSC" :super cell-type) ;; TRIPS wanted to define this as a protein domain going from MANSC -> MENSC, but that's clearly not right in context -- it's really "Menstrual Stem Cell" but, unfortunately for some reason that isn't in either cellosaurus or cell ontology, so I can't give it an ID

(noun "induced pluripotent stem cell" :super cell-type)
(def-synonym induced-pluripotent-stem-cell (:noun "iPSC"))
(def-synonym induced-pluripotent-stem-cell (:noun "iPS cell"))

;; added "iPSC" as "induced pluripotent stem cell" and "iPS cell" for synonym -- unfortunately there's no induced version in cell ontology CL_0002248 is pluripotent, while cellosaurus has many specific cell lines but no aggregate term

;;;--------------------
;;; cell types with IDs
;;;--------------------
;; note: could be differentiated so that neurons are of category
;; neuron rather than cell type, etc note: beta-cell and β-cell get
;; different definitions from TRIPS -- may want to sort out if they're
;; accurate at some point

(def-ided-indiv cell-type "B lymphocyte" "CL:0000236") 
(def-ided-indiv cell-type "B-cell" "CO:0000236" :name "B cell") 
(def-ided-indiv cell-type "B-lymphoblast" "BTO:0001528" :name "B-lymphoblast") 
(def-ided-indiv cell-type "B-lymphocyte" "BTO:0000776" :name "B-lymphocyte") 
(def-ided-indiv cell-type "BMDC" "BTO:0003857" :name "bone marrow-derived dendritic cell") 
(def-ided-indiv cell-type "BMSC" "CO:0000134" :name "mesenchymal stem cell") 
(def-ided-indiv cell-type "CFU-E" "CO:0000038" :name "erythroid progenitor cell") 
(def-ided-indiv cell-type "CFU-GM" "CO:0000557" :name "granulocyte monocyte progenitor cell") 
(def-ided-indiv cell-type "CLP" "CO:0000051" :name "common lymphoid progenitor") 
(def-ided-indiv cell-type "CML cell" "TS-0147") 
(def-ided-indiv cell-type "EPC" "CO:0002619" :name "adult endothelial progenitor cell") 
(def-ided-indiv cell-type "ESC" "CO:0002322" :name "embryonic stem cell") 
(def-ided-indiv cell-type "HeLa cell" "TS-0136") 
(def-ided-indiv cell-type "ICC" "CO:0002088" :name "interstitial cell of Cajal") 
(def-ided-indiv cell-type "Immune Cell" "CL:0000738") 
(def-ided-indiv cell-type "Kupffer cell" "CL:0000091") 
(def-ided-indiv cell-type "LEC" "CO:0002138" :name "endothelial cell of lymphatic vessel") 
(def-ided-indiv cell-type "LT-HSC" "CO:0002034" :name "long term hematopoietic stem cell") 
(def-ided-indiv cell-type "M-cell" "BTO:0003600" :name "M cell") 
(def-ided-indiv cell-type "Muller cell" "CL:0011107") 
(def-ided-indiv cell-type "NK cell" "CL:0000623") 
(def-ided-indiv cell-type "Natural Killer cell" "CL:0000623") 
(def-ided-indiv cell-type "OVA" "BTO:0003801" :name "ovum") 
(def-ided-indiv cell-type "PBMC" "BTO:0001025" :name "peripheral blood mononuclear cell") 
(def-ided-indiv cell-type "PMN" "BTO:0003473" :name "polymorphonuclear neutrophil") 
(def-ided-indiv cell-type "RGC" "CO:0000740" :name "retinal ganglion cell") 
(def-ided-indiv cell-type "Stromal cell" "TS-0984") 
(def-ided-indiv cell-type "T cell" "TS-1001") 
(def-ided-indiv cell-type "T-lymphocyte" "BTO:0000782" :name "T-lymphocyte") 
(def-ided-indiv cell-type "Tcell" "BTO:0000782" :name "T-lymphocyte") 
(def-ided-indiv cell-type "Th1 cell" "CL:0000545") 
(def-ided-indiv cell-type "Th17 cell" "CL:0000899") 
(def-ided-indiv cell-type "Treg" "CO:0000792" :name "CD4-positive, CD25-positive, alpha-beta regulatory T cell") 
(def-ided-indiv cell-type "VSMC" "CO:0000359" :name "vascular associated smooth muscle cell") 
(def-ided-indiv cell-type "acinar cell" "CL:0000622") 
(def-ided-indiv cell-type "airway epithelial cell" "TS-0023") 
(def-ided-indiv cell-type "alveolar epithelial cell" "CL:0000322") 
(def-ided-indiv cell-type "alveolar macrophage" "CL:0000583") 
(def-ided-indiv cell-type "antibody secreting cell" "CL:0000946") 
(def-ided-indiv cell-type "aortic endothelial cell" "CL:0002544") 
(def-ided-indiv cell-type "aortic smooth muscle cell" "CL:0002539") 
(def-ided-indiv cell-type "basal cell" "CL:0000646") 
(def-ided-indiv cell-type "basophil" "BTO:0000129" :name "basophil") 
(def-ided-indiv cell-type "be cell" "CL:0000968") 
(def-ided-indiv cell-type "beta-cell" "BTO:0000783" :name "pancreatic beta cell") 
(def-ided-indiv cell-type "bone marrow cell" "CL:0002092") 
(def-ided-indiv cell-type "bone marrow macrophage" "CL:0002476") 
(def-ided-indiv cell-type "bone marrow mononuclear cell" "CL:0010004") 
(def-ided-indiv cell-type "bone marrow stromal cell" "CL:0010001") 
(def-ided-indiv cell-type "breast epithelial cell" "CL:0002327") 
(def-ided-indiv cell-type "bronchial epithelial cell" "CL:0002328") 
(def-ided-indiv cell-type "capillary endothelial cell" "CL:0002144") 
(def-ided-indiv cell-type "cardiac cell" "TS-0115") 
(def-ided-indiv cell-type "cardiac fibroblast" "CL:0002548") 
(def-ided-indiv cell-type "cardiac neuron" "CL:0010022") 
(def-ided-indiv cell-type "cardiomyocyte" "CO:0000746" :name "cardiac muscle cell") 
(def-ided-indiv cell-type "cerebellar granule cell" "CL:0001031") 
(def-ided-indiv cell-type "cerebellar neuron" "CL:1001611") 
(def-ided-indiv cell-type "colonic epithelial cell" "CL:0011108") 
(def-ided-indiv cell-type "cortical neuron" "CL:0002609") 
(def-ided-indiv cell-type "crypt cell" "CL:0000849") 
(def-ided-indiv cell-type "cumulus cell" "CL:0000711") 
(def-ided-indiv cell-type "cytotoxic T cell" "CL:0000910") 
(def-ided-indiv cell-type "DC" "CL:0000451" :name "dendritic cell") ;; manually added DC
(def-ided-indiv cell-type "dopaminergic cell" "CL:0000700") 
(def-ided-indiv cell-type "dopaminergic neuron" "CL:0000700") 
(def-ided-indiv cell-type "embryonic fibroblast" "CL:2000042") 
(def-ided-indiv cell-type "endothelial cell" "TS-0278") 
(def-ided-indiv cell-type "enterocyte" "CO:0000584" :name "enterocyte") 
(def-ided-indiv cell-type "eosinophil" "BTO:0000399" :name "eosinophil") 
(def-ided-indiv cell-type "epithelial cell" "TS-0288") 
(def-ided-indiv cell-type "erythrocyte" "BTO:0000424" :name "erythrocyte") 
(def-ided-indiv cell-type "eukaryotic cell" "CL:0000255") 
(def-ided-indiv cell-type "foam cell" "CL:0000891") 
(def-ided-indiv cell-type "gamete" "CL:0000300") 
(def-ided-indiv cell-type "germ-cell" "BTO:0000535" :name "germ cell") 
(def-ided-indiv cell-type "glioma cell" "TS-0416") 
(def-ided-indiv cell-type "glomerular cell" "CL:1000746") 
(def-ided-indiv cell-type "goblet-cell" "BTO:0001540" :name "goblet cell") 
(def-ided-indiv cell-type "granulocytes" "BTO:0000539" :name "granulocyte") 
(def-ided-indiv cell-type "granulosa cell" "CL:0000501") 
(def-ided-indiv cell-type "helper T cell" "CL:0000912") 
(def-ided-indiv cell-type "hematopoietic cell" "CL:0000988") 
(def-ided-indiv cell-type "hematopoietic stem cell" "CL:0000037") 
(def-ided-indiv cell-type "hepatic stellate cell" "CL:0000632") 
(def-ided-indiv cell-type "hippocampal neuron" "CL:0002608") 
(def-ided-indiv cell-type "inflammatory cell" "CL:0009002") 
(def-ided-indiv cell-type "interneuron" "CO:0000099" :name "interneuron") 
(def-ided-indiv cell-type "intestinal epithelial cell" "CL:0002563") 
(def-ided-indiv cell-type "kidney cell" "CL:1000497") 
(def-ided-indiv cell-type "leukemia cell" "TS-0547") 
(def-ided-indiv cell-type "lung endothelial cell" "CL:1001567") 
(def-ided-indiv cell-type "lung epithelial cell" "CL:0000082") 
(def-ided-indiv cell-type "lung fibroblast" "TS-0575") 
(def-ided-indiv cell-type "mammary epithelial cell" "CL:0002327") 
(def-ided-indiv cell-type "mammary gland epithelial cell" "CL:0002327") 
(def-ided-indiv cell-type "mast cell" "TS-0603") 
(def-ided-indiv cell-type "mature B cell" "CL:0000785") 
(def-ided-indiv cell-type "mature oocyte" "CL:0000025") 
(def-ided-indiv cell-type "melanoblast" "CL:0000541") 
(def-ided-indiv cell-type "mesangial cell" "CL:0000650") 
(def-ided-indiv cell-type "microglial cell" "TS-0627") 
(def-ided-indiv cell-type "microvascular endothelial cell" "CL:2000008") 
(def-ided-indiv cell-type "mononuclear cell" "CL:0000842") 
(def-ided-indiv cell-type "motoneuron" "CO:0000100" :name "motor neuron") 
(def-ided-indiv cell-type "muscle cell" "CL:0000187") 
(def-ided-indiv cell-type "myeloid cell" "TS-0647") 
(def-ided-indiv cell-type "neural stem cell" "CL:0000047") 
(def-ided-indiv cell-type "neuronal cell" "TS-0683") 
(def-ided-indiv cell-type "odontoblast" "CL:0000060") 
(def-ided-indiv cell-type "oocyte" "BTO:0000964" :name "oocyte") 
(def-ided-indiv cell-type "osteo-blast" "BTO:0001593" :name "osteoblast") 
(def-ided-indiv cell-type "osteoclast" "BTO:0000968" :name "osteoclast") 
(def-ided-indiv cell-type "pancreatic epithelial cell" "CL:0000083") 
(def-ided-indiv cell-type "pericyte" "CO:0000669" :name "pericyte cell") 
(def-ided-indiv cell-type "peritoneal macrophage" "CL:0000581") 
(def-ided-indiv cell-type "podocyte" "CL:0000653") 
(def-ided-indiv cell-type "pre-B cell" "TS-0819") 
(def-ided-indiv cell-type "pre-B-cell" "BTO:0001133" :name "pre-B-lymphocyte") 
(def-ided-indiv cell-type "pre-osteoblast" "BTO:0002051" :name "preosteoblast") 
(def-ided-indiv cell-type "precursor cell" "CL:0011115") 
(def-ided-indiv cell-type "primary neuron" "CL:0000530") 
(def-ided-indiv cell-type "primary sensory neuron" "CL:0000531") 
(def-ided-indiv cell-type "prostate epithelial cell" "CL:0002231") 
(def-ided-indiv cell-type "pyramidal neuron" "CL:0000598") 
(def-ided-indiv cell-type "renal epithelial cell" "TS-0505") 
(def-ided-indiv cell-type "retinal cell" "CL:0009004") 
(def-ided-indiv cell-type "retinal pigment epithelial cell" "CL:0002586") 
(def-ided-indiv cell-type "satellite cell" "TS-1205") 
(def-ided-indiv cell-type "skin epidermal cell" "TS-0283") 
(def-ided-indiv cell-type "smooth muscle cell" "CL:0000192") 
(def-ided-indiv cell-type "spermatogonia" "BTO:0000958" :name "spermatogonium") 
(def-ided-indiv cell-type "splenocyte" "CO:2000074" :name "splenocyte") 
(def-ided-indiv cell-type "squamous cell" "TS-1249") 
(def-ided-indiv cell-type "stem cell" "CL:0000034") 
(def-ided-indiv cell-type "synoviocyte" "CO:0000214" :name "synovial cell") 
(def-ided-indiv cell-type "thymocyte" "BTO:0001372" :name "thymocyte") 
(def-ided-indiv cell-type "transitional B cell" "CL:0000818") 
(def-ided-indiv cell-type "type II alveolar epithelial cell" "CL:0002063") 
(def-ided-indiv cell-type "umbilical vein endothelial cell" "TS-1081") 
(def-ided-indiv cell-type "vascular endothelial cell" "TS-1106") 
(def-ided-indiv cell-type "vascular smooth muscle cell" "CL:0000359") 
(def-ided-indiv cell-type "venous endothelial cell" "CL:0002543") 
(def-ided-indiv cell-type "ventricular myocyte" "CL:0002131") 
(def-ided-indiv cell-type "yolk cell" "CL:0000428") 
(def-ided-indiv cell-type "β-cell" "CO:0000639" :name "basophil cell of pars distalis of adenohypophysis") 