(in-package :sparser)


(def-family-with-id "zinc-finger domain" "XFAM:PF10276") 
(def-family-with-id "zinc-binding RING-finger" "XFAM:PF14569") 
(def-family-with-id "xylosyltransferase" "IPR024448") 
(def-family-with-id "voltage-gated potassium channel" "IPR028325") 
(def-family-with-id "voltage-dependent anion channel" "XFAM:PF03595") 
(def-family-with-id "vitamin D receptor" "IPR000324") 
(def-family-with-id "vascular endothelial growth factor receptor 2 (VEGFR2)" "IPR009136") 
(def-family-with-id "vacA" "XFAM:PF02691") 
(def-family-with-id "ubiquitin-binding domain" "XFAM:PF16455") 
(def-family-with-id "ubiquitin-associated" "XFAM:PF09145") 
(def-family-with-id "ubiquilin" "IPR015496") 
(def-family-with-id "tudor domain" "XFAM:PF00567") 
;(def-family-with-id "troponin T" "BE:Troponin_T") 
(def-family-with-id "transmembrane glycoprotein" "XFAM:PF03409") 
(def-family-with-id "transducer of regulated CREB activity" "IPR024786") 
(def-family-with-id "transcription regulator" "XFAM:PF14998") 
(def-family-with-id "tissue inhibitor of metalloproteinase" "XFAM:PF00965") 
(def-family-with-id "suppressor of fused" "IPR007768") 
(def-family-with-id "suppressor of cytokine signalling" "XFAM:PF12610") 
(def-family-with-id "steroid receptor coactivator" "XFAM:PF08832") 
(def-family-with-id "steroid hormone receptor" "IPR001723") 
(def-family-with-id "site-specific recombinase" "XFAM:PF10136") 
(def-family-with-id "sialyltransferase" "IPR012163") 
;(def-family-with-id "sensor" "XFAM:PF13796") 
(def-family-with-id "selenophosphate synthetase" "IPR004536") 
(def-family-with-id "ribonucleotide reductase inhibitor" "XFAM:PF08591") 
;(def-family-with-id "rhoGAP" "XFAM:PF00620") 
(def-family-with-id "nuclear receptor coactivator" "XFAM:PF08815") 
;(def-family-with-id "nuclear receptor co-repressor" "BE:NCOR") 
(def-family-with-id "rRNA processing" "XFAM:PF08524") 
(def-family-with-id "rDD" "XFAM:PF06271") 
(def-family-with-id "protease-activated receptor-4" "IPR003944") 
(def-family-with-id "prostate apoptosis response-4" "IPR026117") 
(def-family-with-id "prostaglandin D synthase" "IPR002972") 
(def-family-with-id "poxvirus" "XFAM:PF06227") 
(def-family-with-id "poly(ADP-ribose) glycohydrolase (PARG)" "XFAM:PF05028") 
(def-family-with-id "poly(A) polymerase" "IPR014492") 
(def-family-with-id "photodynamic therapy" "XFAM:PF00800") 
(def-family-with-id "phosphotyrosine binding domain" "XFAM:PF08416") 
;(def-family-with-id "phosphatidylinositol-3'-kinase" "BE:PI3K") 
;(def-family-with-id "phosphatidylinositol-3' kinase" "BE:PI3K") 
;(def-family-with-id "phosphatidylinositol-3 kinase" "BE:PI3K") 
;(def-family-with-id "phosphatidyli- nositol-3 kinase" "BE:PI3K") 
(def-family-with-id "p53 tumour suppressor" "IPR002117") 
;(def-family-with-id "p53 DNA-binding domain" "BE:p53_family") 
;(def-family-with-id "p38MAPKs" "BE:p38") 
;(def-family-with-id "p38MAPK" "BE:p38") 
;(def-family-with-id "p38  MAPK" "BE:p38") 
(def-family-with-id "oxysterol binding" "XFAM:PF01237") 
(def-family-with-id "osteo" "IPR002038") 
;(def-family-with-id "notch" "BE:Notch") 
(def-family-with-id "neurokinin" "IPR003635") 
;(def-family-with-id "mitogen-activated protein  kinase" "BE:MAPK") 
(def-family-with-id "mitochondrial antiviral-signalling" "IPR026148") 
(def-family-with-id "microtubule-associated protein 1" "IPR026074") 
(def-family-with-id "methyltransferase-like" "IPR026113") 
(def-family-with-id "melatonin receptor" "IPR000025") 
(def-family-with-id "melanocortin receptor" "IPR001908") 
(def-family-with-id "melanocortin" "IPR001941") 
(def-family-with-id "matrix protein VP40" "XFAM:PF07447") 
;(def-family-with-id "mTorc1" "BE:mTORC1") 
;(def-family-with-id "mTorC2" "BE:mTORC2") 
(def-family-with-id "mP" "XFAM:PF01107") 
(def-family-with-id "lysophosphatidic acid receptor" "IPR004065") 
(def-family-with-id "lumen area" "XFAM:PF05383") 
(def-family-with-id "liver x receptor" "IPR023257") 
(def-family-with-id "liver X receptor" "IPR023257") 
(def-family-with-id "liga" "XFAM:PF07746") 
(def-family-with-id "ligB" "XFAM:PF02900") 
;(def-family-with-id "laminin-332" "BE:Laminin_332") 
;(def-family-with-id "laminin 332 chains" "BE:Laminin_332") 
(def-family-with-id "kringle domain" "XFAM:PF00051") 
(def-family-with-id "kinesin-like" "IPR027640") 
(def-family-with-id "kinesin-associated" "XFAM:PF16183") 
(def-family-with-id "kinesin motor" "XFAM:PF12711") 
;(def-family-with-id "kinase A catalytic subunit" "BE:PRKAC") 
;(def-family-with-id "kinase A" "BE:PKA") 
;(def-family-with-id "kappa B" "BE:NFkappaB") 
(def-family-with-id "interleukin 17" "XFAM:PF06083") 
;(def-family-with-id "insulin-like growth factor-binding" "BE:IGFBP") 
(def-family-with-id "inositol hexakisphosphate" "XFAM:PF14566") 
;(def-family-with-id "hypoxia-inducible factor-1" "BE:HIF1") 
(def-family-with-id "hyaluronidase PH20" "IPR001439") 
(def-family-with-id "homing endonuclease" "XFAM:PF05204") 
(def-family-with-id "homeobox" "XFAM:PF12407" :members ("UP:O43186" "UP:P37275" "UP:Q03014" "UP:Q9BPY8" "UP:P39880")) 
(def-family-with-id "hepatitis B X-interacting" "IPR024135") 
;(def-family-with-id "heme oxygenase" "BE:HMOX") 
;(def-family-with-id "heat shock protein Hsp90" "IPR001404") 
;(def-family-with-id "haem oxygenase" "BE:HMOX") 
(def-family-with-id "formyl transferase" "XFAM:PF00551") 
(def-family-with-id "forkhead domain" "XFAM:PF00250") 
;(def-family-with-id "follicle-stimulating hormone" "BE:FSH") 
(def-family-with-id "flavodoxin" "XFAM:PF12682")
(def-family-with-id "fascin-1" "IPR030146") 
;(def-family-with-id "fibrinogen" "BE:Fibrinogen" :members ("UP:P02671" "UP:P22775"))  
;(def-family-with-id "nuclear factor kappa-b" "BE:NFkappaB") 
;(def-family-with-id "factor erythroid 2-related factor 2" "IPR029845") 
;(def-family-with-id "eukaryotic translation initiation factor 4E-binding" "IPR008606") 
(def-family-with-id "eukaryotic translation initiation factor 2 alpha subunit" "XFAM:PF07541") 
(def-family-with-id "espF" "XFAM:PF04806") 
;(def-family-with-id "EAR" "XFAM:PF07897") 
(def-family-with-id "dynein heavy chain" "IPR026983") 
(def-family-with-id "dotA" "XFAM:PF11388") 
;(def-family-with-id "dopamine receptor" "BE:DRD") 
(def-family-with-id "dexamethasone-induced" "XFAM:PF15198") 
;(def-family-with-id "death receptor" "BE:Death_receptor" :members ("UP:O00220" "UP:O14763")) 
(def-family-with-id "death-associated" "XFAM:PF15228") 
(def-family-with-id "cytotoxic T-lymphocyte antigen-4" "IPR008096") 
;(def-family-with-id "cytochrome p450" "XFAM:PF00067") 
(def-family-with-id "cytidylyltransferase" "XFAM:PF02348") 
;(def-family-with-id "cyclophilin" "BE:Cyclophilin" :members ("UP:P34887" "UP:Q27450")) 
(def-family-with-id "cyclin dependent kinase inhibitor" "XFAM:PF02234") 
(def-family-with-id "cyclic nucleotide phosphodiesterase" "IPR008431") 
(def-family-with-id "cycle inhibiting factor (Cif)" "XFAM:PF16374") 
;(def-family-with-id "competence" "XFAM:PF03772") 
(def-family-with-id "clathrin light chain" "XFAM:PF01086") 
;(def-family-with-id "class III HDACs" "BE:HDAC_III") 
;(def-family-with-id "class II HDACs" "BE:HDAC_II") 
;(def-family-with-id "checkpoint kinase" "BE:CHEK") 
(def-family-with-id "cavin" "IPR026752") 
;(def-family-with-id "caspase domain" "BE:Caspase")
;(def-family-with-id "calpain" "BE:CAPN" :members ("UP:P04632" "UP:P07384")) 
(def-family-with-id "calmodulin-binding" "XFAM:PF13864") 
;(def-family-with-id "cTnC" "BE:Troponin_C") 
;(def-family-with-id "c-Jun N-terminal Kinase" "BE:JNK") 
;(def-family-with-id "c-JUN N-terminal kinase" "BE:JNK") 
(def-family-with-id "bombesin-like peptide" "XFAM:PF02044") 
;(def-family-with-id "betaAR" "BE:ADRB") 
(def-family-with-id "beta-defensin" "XFAM:PF13841") 
;(def-family-with-id "beta-adrenergic receptor" "BE:ADRB") 
(def-family-with-id "aspartyl protease" "XFAM:PF13650") 
(def-family-with-id "arrestin" "IPR000698") 
(def-family-with-id "arf GTPase-activating" "IPR001164") 
(def-family-with-id "aquaporin3" "IPR023275") 
;(def-family-with-id "alpha2beta2gamma3" "BE:AMPK_A2B2G3") 
;(def-family-with-id "alpha2beta1gamma1" "BE:AMPK_A2B1G1")
;(def-family-with-id "aldehyde dehydrogenase" "BE:ALDH" :members ("UP:O94788" "UP:P00352" "UP:P05091" "UP:P30038" "UP:P30837" "UP:P30838" "UP:P43353""UP:P47895" "UP:P48448" "UP:P49189" "UP:P49419" "UP:O75891")) ; others
(def-family-with-id "adrenoceptor" "IPR002233") 
(def-family-with-id "adenosine receptor" "IPR001634") 
(def-family-with-id "adaptor protein CBL" "IPR024162") 
(def-family-with-id "acyl transferase" "XFAM:PF02273") 
;(def-family-with-id "actinin" "BE:ACTN") 
(def-family-with-id "acid phosphatase" "XFAM:PF12689") 
(def-family-with-id "ZZ" "XFAM:PF00569") 
;(def-family-with-id "Wnt family" "BE:Wnt") 
(def-family-with-id "Wave" "XFAM:PF07507") 
(def-family-with-id "W2" "XFAM:PF02020") 
(def-family-with-id "Us2" "XFAM:PF02476") 
(def-family-with-id "Ubiquitin-activating enzyme, E1" "IPR018075") 
(def-family-with-id "ULD" "XFAM:PF16534") 
(def-family-with-id "UL45" "XFAM:PF05473") 
(def-family-with-id "Transducer of regulated CREB activity" "IPR024786") 
(def-family-with-id "Toll-like receptor" "IPR017241") 
(def-family-with-id "Toll-like Receptor" "IPR017241") 
(def-family-with-id "Toll like receptor" "IPR017241") 
(def-family-with-id "Tnfalpha" "IPR002959") 
(def-family-with-id "Tissue plasminogen activator" "IPR026280") 
(def-family-with-id "Tgfbeta2" "IPR003940") 
;(def-family-with-id "Tcf/Lef" "BE:TCF_LEF") 
(def-family-with-id "TRAs" "XFAM:PF10624") 
;(def-family-with-id "TIAM" "BE:TIAM") 
;(def-family-with-id "TGF-beta receptors" "BE:TGFBR") 
;(def-family-with-id "TGF-Beta" "BE:TGFB") 
;(def-family-with-id "TGF beta receptor" "BE:TGFBR") 
(def-family-with-id "Steroid receptor coactivator" "XFAM:PF08832") 
;(def-family-with-id "Stearoyl-CoA desaturase" "BE:SCD") 
;(def-family-with-id "Src-kinases" "BE:SRC") 
;(def-family-with-id "Smad2/3" "BE:SMAD2_3") 
(def-family-with-id "Smad anchor for receptor activation (SARA)" "XFAM:PF11409") 
;(def-family-with-id "Smad 2/3" "BE:SMAD2_3") 
(def-family-with-id "Ski-interacting protein, SKIP" "IPR017862") 
(def-family-with-id "Shprintzen-Goldberg Syndrome" "XFAM:PF05002") 
(def-family-with-id "Sh2" "XFAM:PF00017") 
(def-family-with-id "Sensor" "XFAM:PF13796") 
(def-family-with-id "Semaphorin 3E" "IPR015513") 
(def-family-with-id "Scramblase" "XFAM:PF03803") 
(def-family-with-id "Sar" "IPR006687") 
;(def-family-with-id "SWI/SNF complex" "BE:SWI_SNF") 
;(def-family-with-id "STAT-5" "BE:STAT5") 
;(def-family-with-id "SPROUTY" "XFAM:PF05210") 
(def-family-with-id "SOCS Box" "XFAM:PF07525") 
;(def-family-with-id "SMAD2/3" "BE:SMAD2_3") 
;(def-family-with-id "SMAD 2/3" "BE:SMAD2_3") 
(def-family-with-id "SAR" "IPR006687") 
;(def-family-with-id "S1" "XFAM:PF00575") 
(def-family-with-id "Runt domain" "XFAM:PF00853") 
(def-family-with-id "Rimm" "XFAM:PF01782") 
(def-family-with-id "Ribosomal protein S14" "IPR001209") 
(def-family-with-id "Ribosomal Protein S6" "XFAM:PF01250") 
(def-family-with-id "Ribosomal Protein L31" "XFAM:PF01197") 
;(def-family-with-id "RhoGDIs" "BE:RhoGDI") 
(def-family-with-id "Rho-binding" "XFAM:PF08912") 
;(def-family-with-id "Rassf" "BE:RASSF") 
(def-family-with-id "Ras association (RalGDS/AF-6) domain" "XFAM:PF00788") 
(def-family-with-id "Rap 1" "XFAM:PF03085") 
(def-family-with-id "RWD" "XFAM:PF05773") 
(def-family-with-id "RTEC" "XFAM:PF09357") 
(def-family-with-id "RNA-dependent RNA polymerase" "XFAM:PF00680") 
(def-family-with-id "RNA-binding" "XFAM:PF01877") 
(def-family-with-id "RNA-Binding" "XFAM:PF01877") 
(def-family-with-id "RNA recognition motif" "XFAM:PF10567") 
(def-family-with-id "RNA binding motif" "XFAM:PF08777") 
(def-family-with-id "RIIA" "XFAM:PF02197") 
;(def-family-with-id "RHOGDI" "BE:RhoGDI") 
(def-family-with-id "RAD3" "IPR013020") 
(def-family-with-id "Protein-tyrosine phosphatase" "XFAM:PF00102") 
(def-family-with-id "Protein   kinase C" "IPR012233") 
(def-family-with-id "Poxvirus" "XFAM:PF06227") 
;(def-family-with-id "Polycomb Repressive Complexes 2" "BE:PRC2_complex") 
(def-family-with-id "Pk" "XFAM:PF00224") 
(def-family-with-id "Phosphoprotein Associated with Glycosphingolipid-Enriched" "XFAM:PF15347") 
;(def-family-with-id "Phosphatidyl Inositol-3-Kinase" "BE:PI3K") 
;(def-family-with-id "PPP1c" "BE:PPP1C") 
(def-family-with-id "PLCC" "XFAM:PF14466") 
;(def-family-with-id "PKI" "BE:PKI") 
;(def-family-with-id "PKA catalytic subunits" "BE:PRKAC") 
;(def-family-with-id "PKA catalytic subunit" "BE:PRKAC") 
;(def-family-with-id "PK-A" "BE:PKA") 
;(def-family-with-id "PI3K/AKT/mTOR" "BE:PI3K") 
;(def-family-with-id "PI3K-SH2" "BE:PI3K") 
;(def-family-with-id "PI3K p110 subunit" "BE:PI3K_p110") 
;(def-family-with-id "PI-3k" "BE:PI3K") 
;(def-family-with-id "PI 3" "BE:PI3K") 
(def-family-with-id "PH Domain" "XFAM:PF16453") 
(def-family-with-id "PDZ-like domain" "XFAM:PF12812") 
(def-family-with-id "Oestrogen receptor" "XFAM:PF02159") 
(def-family-with-id "Nuclear receptor coactivator" "XFAM:PF08815") 
;(def-family-with-id "Nuclear factor-kappaB" "BE:NFkappaB") 
(def-family-with-id "Nuclear Factor of Activated T Cells (NFAT)" "IPR008366") 
(def-family-with-id "Na+/H+ exchanger" "IPR004709") 
;(def-family-with-id "NCOA" "BE:NCOA") 
;(def-family-with-id "Mlc" "BE:MYL") 
(def-family-with-id "Mitogen-activated protein (MAP) kinase phosphatase" "IPR008343") 
;(def-family-with-id "Mek1/2" "BE:MEK") 
;(def-family-with-id "Mek" "BE:MEK") 
;(def-family-with-id "MeK1/2" "BE:MEK") 
(def-family-with-id "Mdm2-binding" "XFAM:PF14920") 
(def-family-with-id "Macrophage Scavenger Receptor" "XFAM:PF03523") 
(def-family-with-id "METH" "IPR011822") 
;(def-family-with-id "MEK-1/2" "BE:MEK") 
(def-family-with-id "MDM2-binding" "XFAM:PF14920") 
;(def-family-with-id "MAPK p38" "BE:p38") 
(def-family-with-id "Liver X Receptor" "IPR023257") 
(def-family-with-id "Linker for Activation of T-cells" "XFAM:PF15234") 
(def-family-with-id "Lef-4" "XFAM:PF05098") 
(def-family-with-id "LIC" "IPR006201") 
(def-family-with-id "Interleukin-1 receptor" "IPR015621") 
(def-family-with-id "Integrin alpha" "XFAM:PF08441") 
;(def-family-with-id "Insulin-like growth factor binding" "BE:IGFBP") 
;(def-family-with-id "IkK" "BE:IKK_family") 
(def-family-with-id "Ig" "XFAM:PF00047") 
(def-family-with-id "IQ" "XFAM:PF00612") 
(def-family-with-id "ING" "XFAM:PF12998") 
(def-family-with-id "IMPDH" "XFAM:PF00478") 
(def-family-with-id "Hsp20" "XFAM:PF00011") 
(def-family-with-id "Hepatitis C virus core" "XFAM:PF01542") 
(def-family-with-id "Hepatitis C Virus Core" "XFAM:PF01542") 
(def-family-with-id "Heme oxygenase" "XFAM:PF01126") 
(def-family-with-id "Harakiri" "XFAM:PF15196") 
(def-family-with-id "Hantavirus nucleocapsid" "XFAM:PF00846") 
(def-family-with-id "HEAT-like repeat" "XFAM:PF13513") 
(def-family-with-id "Groucho/transducin-like enhancer" "IPR009146") 
;(def-family-with-id "GrK" "BE:GRK") 
(def-family-with-id "Gonadotropin-releasing hormone" "XFAM:PF00446") 
(def-family-with-id "GTPase-binding" "XFAM:PF09027") 
(def-family-with-id "GTPase binding" "XFAM:PF09027") 
(def-family-with-id "GRIN" "IPR026646") 
;(def-family-with-id "GPIb-IX-V" "BE:GPIb_IX_V") 
;(def-family-with-id "GABA receptor" "BE:GABR") 
;(def-family-with-id "G alphai" "BE:G_i_alpha") 
(def-family-with-id "G Protein-regulated inducer of neurite outgrowth" "IPR026646") 
;(def-family-with-id "Follicle-stimulating hormone" "BE:FSH") 
(def-family-with-id "Flag" "XFAM:PF03646") 
(def-family-with-id "Fascin-1" "IPR030146") 
(def-family-with-id "Fas receptor" "IPR008063") 
(def-family-with-id "Fas Receptor" "IPR008063") 
(def-family-with-id "FF" "XFAM:PF01846") 
(def-family-with-id "FEN" "IPR023426") 
(def-family-with-id "FAS receptor" "IPR008063") 
(def-family-with-id "F-actin binding" "XFAM:PF08919") 
;(def-family-with-id "Eif2b" "BE:EIF2B") 
;(def-family-with-id "Egr" "BE:EGR") 
;(def-family-with-id "HES" "BE:HES") 
(def-family-with-id "ERa" "IPR001292") 
(def-family-with-id "ERA" "IPR001292") 
(def-family-with-id "EGF-like domain" "XFAM:PF07974") 
(def-family-with-id "ECL1" "XFAM:PF12855") 
(def-family-with-id "E4" "XFAM:PF02711") 
(def-family-with-id "E3 ubiquitin  ligase" "XFAM:PF12483") 
(def-family-with-id "Docking" "XFAM:PF08990") 
;;(def-family-with-id "Death Effector Domain" "XFAM:PF01335") 
(def-family-with-id "Death Domain" "XFAM:PF00531") 
(def-family-with-id "DUF1669" "XFAM:PF07894") 
(def-family-with-id "DNAseI" "IPR016202") 
(def-family-with-id "DNA-Binding Domain" "XFAM:PF14848") 
(def-family-with-id "DNA polymerase processivity factor" "XFAM:PF02916") 
(def-family-with-id "DEGs" "XFAM:PF05384") 
(def-family-with-id "DCM" "IPR001525") 
(def-family-with-id "Cytochrome P450" "XFAM:PF00067") 
(def-family-with-id "Cyclin-dependent kinase inhibitor" "XFAM:PF02234") 
(def-family-with-id "Cyclin Y" "IPR012399") 
(def-family-with-id "Cyclin E" "IPR028858") 
(def-family-with-id "Cycle inhibiting factor (Cif)" "XFAM:PF16374") 
(def-family-with-id "Cullin binding" "XFAM:PF03556") 
(def-family-with-id "CpT" "XFAM:PF07931") 
(def-family-with-id "Coronin 1b" "IPR027340") 
(def-family-with-id "Coronin 1C" "IPR027333") 
(def-family-with-id "CoR" "XFAM:PF16095") 
;(def-family-with-id "Class III HDACs" "BE:HDAC_III") 
(def-family-with-id "Cif" "XFAM:PF16374") 
(def-family-with-id "Cdc42 effector" "XFAM:PF14957") 
;(def-family-with-id "Caspase-3/7" "BE:Caspase_3_7") 
(def-family-with-id "Calpain-2" "IPR029539") 
(def-family-with-id "CXC chemokine receptor 4" "IPR001277") 
(def-family-with-id "CXC chemokine receptor 2" "IPR000057") 
(def-family-with-id "CX" "XFAM:PF01705") 
(def-family-with-id "COBRA" "XFAM:PF04833") 
(def-family-with-id "CCAAT/enhancer binding" "IPR016468") 
(def-family-with-id "C2 Domain" "XFAM:PF00168") 
;(def-family-with-id "C1" "BE:C1") 
;(def-family-with-id "BrCa" "BE:BRCA") 
(def-family-with-id "BicD" "XFAM:PF09730") 
(def-family-with-id "BTB-Kelch" "IPR017096") 
;(def-family-with-id "BMP receptor type I" "BE:BMP_receptor_type_I") 
(def-family-with-id "BCP1" "IPR025602") 
(def-family-with-id "Aurora-A binding" "XFAM:PF09041") 
(def-family-with-id "Arfaptin" "XFAM:PF06456") 
;(def-family-with-id "Ampk" "BE:AMPK") 
;(def-family-with-id "Alzheimer disease" "XFAM:PF09793") 
(def-family-with-id "Agouti" "XFAM:PF05039") 
(def-family-with-id "Adenomatous polyposis coli (APC)" "IPR026818") 
(def-family-with-id "ATPR" "XFAM:PF12966") 
(def-family-with-id "ATP Synthase" "XFAM:PF00231") 
(def-family-with-id "ASMA" "XFAM:PF05170") 
;(def-family-with-id "APC/c" "BE:APC_C") 
;(def-family-with-id "APC/C" "BE:APC_C") 
;(def-family-with-id "AP-3" "BE:Adaptor_protein_III") 
(def-family-with-id "AMP deaminase" "IPR006329") 
(def-family-with-id "AKR" "IPR020471") 
(def-family-with-id "AE" "IPR003020") 
(def-family-with-id "ADP-ribosyl cyclase" "XFAM:PF02267") 
(def-family-with-id "ABM" "XFAM:PF03992") 
(def-family-with-id "6PF2K" "XFAM:PF01591") 
(def-family-with-id "6-phosphogluconate dehydrogenase" "IPR006183") 
;(def-family-with-id "5ng/ml" "IPR003939") 
;(def-family-with-id "3h" "XFAM:PF02829") ; more likely to be 3hours
;(def-family-with-id "3D" "XFAM:PF06725") 
(def-family-with-id "3A" "XFAM:PF00803") 
(def-family-with-id "zinc binding" "XFAM:PF12907") 
(def-family-with-id "viral oncogene" "XFAM:PF02246") 
(def-family-with-id "viral RNA-dependent RNA polymerase" "XFAM:PF00998") 
(def-family-with-id "vascular cell adhesion molecule 1" "IPR003989") 
(def-family-with-id "ubiquitin binding domain" "XFAM:PF16455") 
(def-family-with-id "type ATPase" "IPR001757") 
(def-family-with-id "tubulin-binding" "XFAM:PF00418") 
;(def-family-with-id "tubulin binding" "XFAM:PF00418") 
(def-family-with-id "transient receptor potential channel" "IPR004729") 
(def-family-with-id "transferase" "XFAM:PF02458") 
(def-family-with-id "toll-like receptor" "IPR017241") 
(def-family-with-id "tissue plasminogen activator" "IPR026280") 
;(def-family-with-id "three-dimensional" "XFAM:PF06725") 
(def-family-with-id "tetraspanin family" "XFAM:PF00335") 
;(def-family-with-id "tenascin" "BE:TN" :members ("UP:P24821" "UP:Q92752" "UP:Q9UQP3"))
;(def-family-with-id "syntaxin" "XFAM:PF00804" :members ("UP:P61266" "UP:Q12846" "UP:Q13190" "UP:Q13277" "UP:Q16623" "UP:Q9UNK0" "UP:O14662" "UP:O15400" "UP:O43752" "UP:O60499" "UP:O75558" "UP:P32856")) 
(def-family-with-id "sulfotransferase" "IPR005331") 
(def-family-with-id "striatin family" "XFAM:PF08232") 
(def-family-with-id "steroidogenic acute regulatory" "IPR029866") 
(def-family-with-id "staphylokinase" "XFAM:PF02821") 
(def-family-with-id "sortase" "XFAM:PF04203") 
;(def-family-with-id "smad2/3" "BE:SMAD2_3" :name "SMAD-2/3" :members ("UP:Q15796" "UP:P84022")) 
(def-family-with-id "sh2" "XFAM:PF00017") 
(def-family-with-id "second mitochondria-derived activator of caspases" "XFAM:PF09057") 
(def-family-with-id "ryanodine receptor" "IPR013333") 
(def-family-with-id "runt domain" "XFAM:PF00853") 
(def-family-with-id "ribosomal protein s6" "XFAM:PF01250") 
;(def-family-with-id "rheumatoid arthritis" "XFAM:PF00788") 
(def-family-with-id "retinoic acid receptor" "IPR003078") 
(def-family-with-id "replication initiation factor" "XFAM:PF02486") 
(def-family-with-id "receptor serine/threonine kinase" "XFAM:PF12398") 
;(def-family-with-id "receptor corepressor" "BE:NCOR")
(def-family-with-id "recombinase" "XFAM:PF07508")
;(def-family-with-id "rasGAP" "BE:RasGAP") 
;(def-family-with-id "ras family" "BE:RAS") 
(def-family-with-id "rad3" "IPR013020") 
(def-family-with-id "protein-tyrosine phosphatase" "XFAM:PF00102") 
(def-family-with-id "proteasome subunit" "XFAM:PF00227") 
(def-family-with-id "protease-activated receptor 4" "IPR003944") 
(def-family-with-id "protease-activated receptor 2" "IPR002281") 
(def-family-with-id "prostanoid receptor" "IPR008365") 
;(def-family-with-id "plug" "XFAM:PF07715") 
(def-family-with-id "phosphotyrosine-binding domain" "XFAM:PF08416") 
(def-family-with-id "phosphoribosyltransferase" "XFAM:PF02277") 
(def-family-with-id "phospholipase A2 inhibitor" "XFAM:PF02988") 
(def-family-with-id "phosphoenolpyruvate carboxykinase" "XFAM:PF01293") 
(def-family-with-id "phosphatidylinositol kinase" "IPR015433") 
(def-family-with-id "phosphatidylethanolamine-binding" "XFAM:PF01161") 
;(def-family-with-id "phosphatidyl inositol-3-kinase" "BE:PI3K") 
;(def-family-with-id "phosphati- dylinositol 3-kinase" "BE:PI3K") 
;(def-family-with-id "pertussis toxin" "BE:Pertussis_toxin") 
(def-family-with-id "peroxisome proliferator-activated receptor" "IPR003074") 
(def-family-with-id "peptide hormone" "XFAM:PF00123") 
;(def-family-with-id "pde3" "BE:PDE3") 
(def-family-with-id "pathogenicity factor" "XFAM:PF11725") 
(def-family-with-id "pardaxin" "XFAM:PF07425") 
(def-family-with-id "parvalbumin" "IPR008080" :members ("UP:P20472" "UP:P0CE72")) 
(def-family-with-id "papillomavirus E7" "IPR000148") 
(def-family-with-id "pannexin" "IPR000990") 
;(def-family-with-id "p90rsk" "BE:P90RSK") 
;(def-family-with-id "p53 DNA binding domain" "BE:p53_family") 
(def-family-with-id "p450" "XFAM:PF00067") 
;(def-family-with-id "p38 mitogen-activated protein kinase" "BE:ERK") 
;(def-family-with-id "p38 Mitogen-activated protein kinase" "BE:p38") 
(def-family-with-id "p2" "XFAM:PF07194") 
;(def-family-with-id "p160/SRC" "BE:NCOA") 
;(def-family-with-id "nicotinic acetylcholine receptor" "BE:CHRN") 
(def-family-with-id "muscarinic acetylcholine receptor" "IPR000995") 
(def-family-with-id "mug" "IPR003310") 
(def-family-with-id "muHD" "XFAM:PF10291") 
(def-family-with-id "monocarboxylate transporter" "IPR004743") 
(def-family-with-id "microtubule binding" "XFAM:PF16796") 
(def-family-with-id "membrane-binding" "XFAM:PF14564") 
(def-family-with-id "metallothionein" "XFAM:PF05522" :synonyms ("metallothioneine") :members ("UP:P47944" "UP:P80294" "UP:P80297" "UP:Q8N339" "UP:Q93083" "UP:P02795" "UP:P04731" "UP:P04732" "UP:P04733" "UP:P07438" "UP:P13640" "UP:P25713")) 
;(def-family-with-id "mate" "XFAM:PF01554") 
(def-family-with-id "mastoparan" "XFAM:PF08249") 
(def-family-with-id "macrophage scavenger receptor" "XFAM:PF03523") 
(def-family-with-id "macrophage migration inhibitory factor (MIF)" "XFAM:PF01187") 
;(def-family-with-id "mTORc1" "BE:mTORC1") 
;(def-family-with-id "mTORC-2" "BE:mTORC2") 
;(def-family-with-id "mTORC 2" "BE:mTORC2") 
(def-family-with-id "m3" "XFAM:PF09213") 
;(def-family-with-id "luteinizing hormone" "BE:LH") 
;(def-family-with-id "long-chain acyl-CoA synthetase" "BE:ACSL") 
(def-family-with-id "lecithin:cholesterol acyltransferase" "XFAM:PF02450") 
(def-family-with-id "kringle" "XFAM:PF00051") 
(def-family-with-id "jacalin" "XFAM:PF01419") 
(def-family-with-id "iodothyronine deiodinase" "XFAM:PF00837") 
;(def-family-with-id "interferon" "BE:Interferon") 
(def-family-with-id "integrin beta subunit" "IPR015812") 
(def-family-with-id "integrin alpha" "XFAM:PF08441") 
;(def-family-with-id "insulin-like growth factor binding" "BE:IGFBP") 
(def-family-with-id "inosine-5'-monophosphate dehydrogenase" "IPR005990") 
(def-family-with-id "hypoxia-inducible factor-1 alpha" "IPR001321") 
(def-family-with-id "hypoxia inducible factor-1 alpha" "IPR001321") 
(def-family-with-id "hook" "XFAM:PF05622") 
(def-family-with-id "hnRNP C" "IPR017347") 
(def-family-with-id "histone-fold" "XFAM:PF17027") 
;(def-family-with-id "histone H3" "BE:Histone_H3") 
;(def-family-with-id "hif-1" "BE:HIF1") 
;(def-family-with-id "help" "XFAM:PF03451") 
(def-family-with-id "heat shock protein HSP90" "IPR001404") 
(def-family-with-id "hantavirus nucleocapsid" "XFAM:PF00846") 
;(def-family-with-id "guanylyl cyclase" "BE:GUCY") 
(def-family-with-id "growth differentiation factor-9" "IPR015617") 
(def-family-with-id "glycophorin A" "XFAM:PF01102") 
(def-family-with-id "folate receptor" "IPR004269") 
;(def-family-with-id "flag" "XFAM:PF03646") 
;(def-family-with-id "factor-kappaB" "BE:NFkappaB") 
(def-family-with-id "ezrin/radixin/moesin" "IPR011174") 
(def-family-with-id "extracellular sulfatase" "IPR014615") 
;(def-family-with-id "extracellular signal regulated kinase" "BE:ERK") 
(def-family-with-id "eukaryotic translation-initiation factor 4E-binding" "IPR008606") 
(def-family-with-id "eukaryotic initiation factor 4e" "XFAM:PF01652") 
(def-family-with-id "epidermal growth factor receptor ligand" "IPR015497") 
(def-family-with-id "envelope glycoprotein gp120" "XFAM:PF00516") 
;(def-family-with-id "eno" "BE:ENO") 
(def-family-with-id "endothelin receptor" "IPR000499") 
(def-family-with-id "ecTbetaR2" "XFAM:PF08917") 
(def-family-with-id "dynein 1 light intermediate chain" "IPR008467") 
;(def-family-with-id "dusp" "BE:DUSP") 
;(def-family-with-id "dopamine receptors" "BE:DRD") 
(def-family-with-id "disulphide isomerase" "IPR005792") 
;(def-family-with-id "discoidin domain receptors" "BE:DDR") 
(def-family-with-id "desmosomal cadherin" "IPR009122") 
(def-family-with-id "della" "XFAM:PF12041") 
(def-family-with-id "dedicator of cytokinesis" "IPR026791") 
(def-family-with-id "death  domain" "XFAM:PF00531") 
(def-family-with-id "dUs" "XFAM:PF01207") 
;(def-family-with-id "cyclin-dependent kinase inhibitor" "BE:CDKN") 
;(def-family-with-id "ctD" "XFAM:PF12815")  ;; weak match
(def-family-with-id "cornifin" "XFAM:PF02389") 
(def-family-with-id "claudin1" "IPR003548") 
(def-family-with-id "citrate transporter" "XFAM:PF03600") 
(def-family-with-id "chloramphenicol acetyltransferase" "XFAM:PF00302") 
(def-family-with-id "chips" "XFAM:PF11434") 
;(def-family-with-id "chaperonin" "BE:CCT_complex") 
;(def-family-with-id "caspase-3/7" "BE:Caspase_3_7") 
(def-family-with-id "caspase recruitment domain" "XFAM:PF16739") 
(def-family-with-id "cannabinoid receptor" "IPR002230") 
(def-family-with-id "calpain-2" "IPR029539") 
(def-family-with-id "calpain-1" "IPR029643") 
(def-family-with-id "calcium-binding" "XFAM:PF11535") 
(def-family-with-id "calcium binding" "XFAM:PF11535") 
;(def-family-with-id "cAMP-dependent protein kinase inhibitor" "BE:PKI") 
(def-family-with-id "cAMP response element-binding (CREB)" "IPR001630") 
;(def-family-with-id "c-jun NH2-terminal kinase" "BE:JNK") 
;(def-family-with-id "c-jun N-terminal kinase" "BE:JNK") 
(def-family-with-id "brachyury" "IPR002070") 
;(def-family-with-id "betaARK" "BE:ADRBK") 
(def-family-with-id "beta-propeller repeat" "XFAM:PF06739") 
(def-family-with-id "bZIP transcription factor" "XFAM:PF00170") 
;(def-family-with-id "avirulence" "XFAM:PF03377") 
(def-family-with-id "aurora kinase" "IPR030616") 
(def-family-with-id "apyrase" "XFAM:PF06079") 
;(def-family-with-id "alpha2-AR" "BE:ADRA2") 
;(def-family-with-id "alpha1beta1gamma1" "BE:AMPK_A1B1G1") 
;(def-family-with-id "alpha-adrenergic receptor" "BE:ADRA") 
(def-family-with-id "alpha-L-fucosidase" "XFAM:PF01120") 
(def-family-with-id "aldo-keto reductase" "IPR001395") 
(def-family-with-id "ae" "IPR003020") 
;(def-family-with-id "activin-B" "BE:Activin_B") 
;(def-family-with-id "activin A" "BE:Activin_A") 
;(def-family-with-id "activated receptor" "IPR003912") 
(def-family-with-id "Yfh1p" "IPR002908") 
(def-family-with-id "Vitamin D receptor" "IPR000324") 
(def-family-with-id "VWC" "XFAM:PF00093") 
(def-family-with-id "UTRa" "XFAM:PF07702") 
(def-family-with-id "UT" "XFAM:PF03253") 
(def-family-with-id "U-box domain" "XFAM:PF04564") 
(def-family-with-id "U-box" "XFAM:PF04564") 
;(def-family-with-id "Trk receptors" "BE:NTRK") 
(def-family-with-id "Transferase" "XFAM:PF02458") 
;(def-family-with-id "TpYERK" "BE:ERK") 
(def-family-with-id "Toll-Like Receptor" "IPR017241") 
;(def-family-with-id "Tlr" "BE:TLR") 
(def-family-with-id "Tipalpha" "XFAM:PF16753") 
;(def-family-with-id "Tgf-beta" "BE:TGFB") 
(def-family-with-id "Taga" "XFAM:PF12561") 
(def-family-with-id "TRM" "XFAM:PF02005") 
(def-family-with-id "TRAL" "XFAM:PF07178") 
;(def-family-with-id "TNFR superfamily receptors" "BE:TNFRSF") 
;(def-family-with-id "TNFR family" "BE:TNFRSF") 
(def-family-with-id "TIP41" "XFAM:PF04176") 
;(def-family-with-id "TGFb" "BE:TGFB") 
(def-family-with-id "TCP" "XFAM:PF03634") 
(def-family-with-id "TATc" "XFAM:PF00902") 
(def-family-with-id "TATT" "XFAM:PF16811") 
(def-family-with-id "TATA-box binding" "IPR000814") 
(def-family-with-id "T-box transcription factor" "XFAM:PF12598") 
(def-family-with-id "Suppressor of fused" "IPR007768") 
;(def-family-with-id "Spry" "BE:SPRY") 
;(def-family-with-id "Sos" "BE:SOS") 
;(def-family-with-id "SoS" "BE:SOS") 
(def-family-with-id "SIMPL" "XFAM:PF04402") 
(def-family-with-id "SH3 Domain" "XFAM:PF00018") 
(def-family-with-id "SGS" "XFAM:PF05002") 
(def-family-with-id "SCAR/WAVE" "IPR028288") 
(def-family-with-id "SASA" "XFAM:PF03629") 
(def-family-with-id "S16" "IPR000307") 
;(def-family-with-id "RoR" "BE:ROR") 
(def-family-with-id "Ribosomal protein L23" "XFAM:PF00276") 
(def-family-with-id "RhoGAP domain" "XFAM:PF00620") 
;(def-family-with-id "Relish" "BE:NFkappaB") 
(def-family-with-id "Rb C-terminal domain" "XFAM:PF08934") 
;(def-family-with-id "Ras Family" "BE:RAS") 
(def-family-with-id "Ran GTPase" "IPR002041") 
(def-family-with-id "RYR" "XFAM:PF02026") 
;(def-family-with-id "RNAP II" "BE:RNApo_II") 
(def-family-with-id "RNA-binding motif" "XFAM:PF08777") 
(def-family-with-id "RNA-binding domain" "XFAM:PF08675") 
(def-family-with-id "RHS" "XFAM:PF03527") 
;(def-family-with-id "REL1096" "BE:NFkappaB") 
(def-family-with-id "RB C-terminal domain" "XFAM:PF08934") 
;(def-family-with-id "RASGAPs" "BE:RasGAP") 
(def-family-with-id "Purine-Rich Element-Binding" "IPR006628") 
(def-family-with-id "Pt" "XFAM:PF04886") 
(def-family-with-id "Protease-activated receptor-2" "IPR002281") 
(def-family-with-id "Protease-activated Receptor-2" "IPR002281") 
(def-family-with-id "Pregnancy-associated plasma protein-A" "XFAM:PF05572") 
;(def-family-with-id "Pol delta" "BE:DNA_polymerase_delta") 
;(def-family-with-id "Pl-3K" "BE:PI3K") 
;(def-family-with-id "Pi" "BE:PI3K") 
(def-family-with-id "Photodynamic Therapy" "XFAM:PF00800") 
;(def-family-with-id "Phospholipase D" "BE:PLD") 
;(def-family-with-id "Phosphatidyl-inositol-3-kinase" "BE:PI3K") 
;(def-family-with-id "Phosphatidyl-inositol-3 kinase" "BE:PI3K") 
;(def-family-with-id "Phosphatidyl-inositol 3-kinase" "BE:PI3K") 
(def-family-with-id "Peptide hormone" "XFAM:PF00123") 
(def-family-with-id "Pellino" "XFAM:PF04710") 
;(def-family-with-id "Pdgf" "BE:PDGF") 
(def-family-with-id "Pardaxin" "XFAM:PF07425") 
;(def-family-with-id "PP1R" "BE:PPP1R") 
;(def-family-with-id "PLC-gamma" "BE:PLCG") 
(def-family-with-id "PINIT" "XFAM:PF14324") 
;(def-family-with-id "P2X receptors" "BE:P2RX") 
;(def-family-with-id "P/I" "BE:PI3K") 
(def-family-with-id "Orphan nuclear receptor" "IPR003070") 
(def-family-with-id "Nod" "XFAM:PF06816") 
;(def-family-with-id "NfkappaB" "BE:NFkappaB") 
(def-family-with-id "Neural Cell Adhesion" "IPR009138") 
;(def-family-with-id "NcoR" "BE:NCOR") 
;(def-family-with-id "Na/K-ATPase" "BE:Na_K_ATPase") 
(def-family-with-id "NSs" "XFAM:PF11073") 
;(def-family-with-id "NRGs" "BE:NRG") 
(def-family-with-id "NPM1-c" "XFAM:PF16276") 
(def-family-with-id "NPA" "XFAM:PF16469") 
;(def-family-with-id "NOTCH" "BE:Notch") 
(def-family-with-id "NGFbeta" "IPR020425") 
;(def-family-with-id "NF- kappaB" "BE:NFkappaB") 
(def-family-with-id "Membrane binding" "XFAM:PF14564") 
(def-family-with-id "Mdm2 binding" "XFAM:PF14920") 
(def-family-with-id "Mbt" "XFAM:PF02820") 
(def-family-with-id "Macrophage migration inhibitory factor (MIF)" "XFAM:PF01187") 
(def-family-with-id "MIT (Microtubule Interacting and Transport) domain" "XFAM:PF04212") 
(def-family-with-id "Lysophosphatidic acid receptor" "IPR004065") 
(def-family-with-id "Liver X receptor" "IPR023257") 
(def-family-with-id "LepA" "IPR006297") 
;(def-family-with-id "Laminin-5" "BE:Laminin_332") 
(def-family-with-id "La" "XFAM:PF05383") 
(def-family-with-id "Ku" "XFAM:PF02735") 
(def-family-with-id "Kringle" "XFAM:PF00051") 
(def-family-with-id "KAT11" "IPR013178") 
(def-family-with-id "Interleukin 17" "XFAM:PF06083") 
;(def-family-with-id "Interferon" "BE:Interferon") 
;(def-family-with-id "IRX" "BE:IRX") 
;(def-family-with-id "IFN-a" "BE:IFNA") 
(def-family-with-id "IER" "XFAM:PF05760") 
;(def-family-with-id "I3K" "BE:PI3K") 
;(def-family-with-id "Hypoxia-inducible factor-1" "BE:HIF1") 
(def-family-with-id "Hypotonic stress" "XFAM:PF04204") 
;(def-family-with-id "Hsp-90" "BE:HSP90") 
(def-family-with-id "HmuY" "XFAM:PF14064") 
(def-family-with-id "Heterogeneous nuclear ribonucleoprotein C" "IPR017347") 
(def-family-with-id "HEMC" "IPR000860") 
(def-family-with-id "HELP motif" "XFAM:PF03451") 
;(def-family-with-id "Gst" "BE:GST") 
;(def-family-with-id "Gsk3" "BE:GSK3") 
(def-family-with-id "GDP dissociation inhibitor" "XFAM:PF00996") 
(def-family-with-id "GASDERMIN" "XFAM:PF04598") 
;(def-family-with-id "GABA receptors" "BE:GABR") 
;(def-family-with-id "G12" "BE:G_12") 
(def-family-with-id "G-protein alpha subunit" "XFAM:PF00503") 
(def-family-with-id "G-protein alpha" "XFAM:PF00503") 
(def-family-with-id "G-alpha" "XFAM:PF00503") 
;(def-family-with-id "G alphaq" "BE:G_q_alpha") 
;(def-family-with-id "Foxo" "BE:FOXO") 
;(def-family-with-id "Fn" "BE:PFN") 
(def-family-with-id "FliM" "XFAM:PF02154") 
;(def-family-with-id "Fibroblast Growth Factor" "BE:FGF") 
;(def-family-with-id "FLRT" "BE:FLRT") 
(def-family-with-id "FHA" "XFAM:PF00498") 
(def-family-with-id "FDF" "XFAM:PF09532") 
(def-family-with-id "FAM150" "XFAM:PF15129") 
(def-family-with-id "Eve" "XFAM:PF01878") 
(def-family-with-id "EspG" "XFAM:PF06872") 
(def-family-with-id "Ero1" "XFAM:PF04137") 
(def-family-with-id "Eosinophil major basic" "IPR002352") 
;(def-family-with-id "EXOC" "BE:EXOC") 
;(def-family-with-id "ETS-domain" "BE:ETS") 
(def-family-with-id "ETRAMP" "XFAM:PF09716") 
(def-family-with-id "ESSs" "XFAM:PF10183") 
;(def-family-with-id "ERK 1/2" "BE:ERK") 
(def-family-with-id "ER-b" "IPR028355") 
(def-family-with-id "EGF like domain" "XFAM:PF07974") 
;(def-family-with-id "EGF Receptor" "IPR016245") 
;(def-family-with-id "EGF  RECEPTOR" "IPR016245") 
(def-family-with-id "EF hand" "XFAM:PF13202") 
(def-family-with-id "E4" "XFAM:PF02711") 
(def-family-with-id "E3 Ubiquitin Ligase" "XFAM:PF12483") 
(def-family-with-id "Dx" "XFAM:PF01666") 
(def-family-with-id "DnaJ" "XFAM:PF00226") 
(def-family-with-id "DiM" "XFAM:PF08194") 
(def-family-with-id "DX" "XFAM:PF01666") 
(def-family-with-id "DNA-dependent RNA polymerase" "XFAM:PF00940") 
(def-family-with-id "DNA-binding domain" "XFAM:PF14848") 
;(def-family-with-id "DNA polymerase delta" "BE:DNA_polymerase_delta") 
(def-family-with-id "DNA helicase" "IPR003840") 
(def-family-with-id "DNA Topoisomerase" "XFAM:PF01131") 
;(def-family-with-id "DC" "BE:PDC") 
(def-family-with-id "CxC chemokine" "IPR001089") 
;(def-family-with-id "Cut" "XFAM:PF02376") 
(def-family-with-id "Cdc48" "IPR005938") 
(def-family-with-id "Calpain-1" "IPR029643") 
;(def-family-with-id "CSNK2" "BE:CSNK2") 
(def-family-with-id "CRIM" "XFAM:PF16978") 
(def-family-with-id "CREB-binding" "XFAM:PF09030") 
(def-family-with-id "CLZ" "XFAM:PF16526") 
(def-family-with-id "CLCA" "XFAM:PF08434") 
(def-family-with-id "CH" "XFAM:PF00307") 
;(def-family-with-id "CC" "XFAM:PF04942") 
(def-family-with-id "CAMs" "XFAM:PF07537") 
;(def-family-with-id "CAMKII" "BE:CAMK2_family") 
(def-family-with-id "C2H2-type zinc finger" "XFAM:PF13894") 
;(def-family-with-id "C-jun N-terminal kinase" "BE:JNK") 
;(def-family-with-id "C-Jun NH2-terminal kinase" "BE:JNK") 
;(def-family-with-id "C-Jun NH2-Terminal Kinase" "BE:JNK") 
;(def-family-with-id "C-Jun N-terminal kinase" "BE:JNK") 
(def-family-with-id "Brachyury" "IPR002070") 
(def-family-with-id "Bombesin Receptor" "IPR001556") 
(def-family-with-id "Beach" "XFAM:PF02138") 
(def-family-with-id "BMC" "XFAM:PF00936") 
;(def-family-with-id "BIRC" "BE:BIRC") 
(def-family-with-id "BH4" "XFAM:PF02180") 
(def-family-with-id "BCL2-like" "IPR002475") 
(def-family-with-id "BCIP" "XFAM:PF13862") 
(def-family-with-id "B9" "IPR010796") 
(def-family-with-id "B56" "XFAM:PF01603") 
;(def-family-with-id "As60A" "BE:TGFB") 
(def-family-with-id "Apyrase" "XFAM:PF06079") 
(def-family-with-id "Angiotensin II receptor" "IPR000248") 
(def-family-with-id "AhpC" "IPR024706") 
;(def-family-with-id "Activating protein-1" "BE:AP1") 
;(def-family-with-id "Acad" "BE:ACAD") 
;(def-family-with-id "APC-C" "BE:APC_C") 
;(def-family-with-id "AMPKalpha1beta1gamma1" "BE:AMPK_A1B1G1") 
;(def-family-with-id "AMPK-CA" "BE:AMPK") 
;(def-family-with-id "AMPAR" "BE:GRIA") 
;(def-family-with-id "AKt" "BE:AKT") 
;(def-family-with-id "AD-DN-AMPK" "BE:AMPK") 
(def-family-with-id "3a" "XFAM:PF00803") 
(def-family-with-id "3H" "XFAM:PF02829") 
;(def-family-with-id "p-38" "BE:p38") 
(def-family-with-id "3'-5' exonuclease" "XFAM:PF01612") 
(def-family-with-id "10-formyltetrahydrofolate dehydrogenase" "IPR011407") 
;(def-family-with-id "wave" "XFAM:PF07507") 
(def-family-with-id "ubiquitin-conjugating enzyme" "XFAM:PF00179") 
(def-family-with-id "tumour suppressor" "XFAM:PF10158") 
(def-family-with-id "tumour necrosis factor alpha" "IPR002959") 
;(def-family-with-id "tuberous sclerosis" "BE:TSC") 
(def-family-with-id "tropomodulin" "XFAM:PF03250") 
(def-family-with-id "translocator" "IPR001067") 
(def-family-with-id "translation initiation factor 2" "XFAM:PF11987") 
(def-family-with-id "tower" "XFAM:PF09121") 
;(def-family-with-id "thyroid hormone receptor" "BE:THR") 
;(def-family-with-id "this family" "XFAM:PF02597") 
(def-family-with-id "tetratricopeptide repeat" "XFAM:PF13424") 
(def-family-with-id "tetraspannin" "XFAM:PF00335") 
(def-family-with-id "telomere recombination" "XFAM:PF01300") 
(def-family-with-id "surface antigen" "XFAM:PF01103") 
(def-family-with-id "ssDNA-binding" "XFAM:PF00747") 
(def-family-with-id "ssDNA binding" "XFAM:PF00747") 
;(def-family-with-id "sprouty" "XFAM:PF05210") 
;(def-family-with-id "sphingosine 1-phosphate receptor" "IPR004061") 
;(def-family-with-id "span" "XFAM:PF02510") 
(def-family-with-id "sialidase" "XFAM:PF02973") 
(def-family-with-id "sclerostin (SOST)" "XFAM:PF05463") 
(def-family-with-id "rich domain" "XFAM:PF05062") 
(def-family-with-id "ribosomal protein S6 kinase II" "IPR016239") 
;(def-family-with-id "retinoic acid receptors" "BE:RAR") 
;(def-family-with-id "regulatory myosin light chain" "BE:MYL_regulatory") 
(def-family-with-id "reduced folate carrier" "XFAM:PF01770") 
(def-family-with-id "rapamycin-binding domain" "XFAM:PF08771") 
(def-family-with-id "pyruvate kinase" "IPR001697") 
(def-family-with-id "protease-activated receptor" "IPR003912") 
(def-family-with-id "prostaglandin d synthase" "IPR002972") 
(def-family-with-id "pre-mRNA splicing factor" "XFAM:PF12542") 
(def-family-with-id "polyproline motif" "XFAM:PF07194") 
;(def-family-with-id "polycomb repressive complex 1" "BE:PRC1_complex") 
;(def-family-with-id "pol delta" "BE:DNA_polymerase_delta") 
;(def-family-with-id "pi" "BE:PI3K") 
(def-family-with-id "phosphoprotein associated with glycosphingolipid-enriched" "XFAM:PF15347") 
;(def-family-with-id "phospholipase-C" "BE:PLC") 
(def-family-with-id "phosphoglycerate kinase" "XFAM:PF00162") 
;(def-family-with-id "phosphatidylinositol3-kinase" "BE:PI3K") 
;(def-family-with-id "phosphatidyl-inositol-3-kinase" "BE:PI3K") 
;(def-family-with-id "phosphatidyl-inositol-3 kinase" "BE:PI3K") 
;(def-family-with-id "phosphatidyl-inositol 3-kinase" "BE:PI3K") 
(def-family-with-id "phosphatase inhibitor" "XFAM:PF07491") 
(def-family-with-id "peroxisome proliferator activated receptor" "IPR003074") 
(def-family-with-id "pepsin" "IPR001461") 
;(def-family-with-id "p90Rsk" "BE:P90RSK") 
(def-family-with-id "p53 induced" "IPR015664") 
;(def-family-with-id "p53 DNA-Binding Domain" "BE:p53_family") 
;(def-family-with-id "p38mapk" "BE:p38") 
(def-family-with-id "orphan nuclear receptor" "IPR003070") 
(def-family-with-id "oestrogen receptor" "XFAM:PF02159") 
(def-family-with-id "octamer-binding transcription factor" "IPR000972") 
(def-family-with-id "neurotensin receptor" "IPR003984") 
(def-family-with-id "neuroligin" "IPR000460") 
;(def-family-with-id "neuregulins" "BE:NRG") 
(def-family-with-id "neural cell adhesion" "IPR009138") 
;(def-family-with-id "nAChR" "BE:CHRN") 
(def-family-with-id "n-SET" "XFAM:PF11764") 
(def-family-with-id "mitotic checkpoint" "XFAM:PF05557") 
(def-family-with-id "mitochondrial carrier" "XFAM:PF00153") 
(def-family-with-id "microtubule-binding" "XFAM:PF16796") 
(def-family-with-id "meth" "IPR011822") 
(def-family-with-id "meprin" "IPR008294") 
(def-family-with-id "membrane binding" "XFAM:PF14564") 
;(def-family-with-id "mTorC1" "BE:mTORC1") 
;(def-family-with-id "mTORc2" "BE:mTORC2") 
;(def-family-with-id "mTORC 1" "BE:mTORC1") 
(def-family-with-id "leukocidin" "XFAM:PF07968") 
;(def-family-with-id "laminin-5" "BE:Laminin_332") 
;(def-family-with-id "laminin 332" "BE:Laminin_332") 
(def-family-with-id "kinesin light chain" "IPR002151") 
(def-family-with-id "kinase like" "XFAM:PF14531") 
(def-family-with-id "kinase domain" "XFAM:PF00069") 
;(def-family-with-id "protein kinase G" "BE:PRKG") 
;(def-family-with-id "protein kinase C" "BE:PKC") 
(def-family-with-id "ipgD" "XFAM:PF05925") 
(def-family-with-id "intermediate filament" "XFAM:PF00038") 
(def-family-with-id "interleukin-1 receptor" "IPR015621") 
(def-family-with-id "interferon-regulatory factor 3" "XFAM:PF10401") 
(def-family-with-id "interferon lambda" "IPR029177") 
(def-family-with-id "inositol phosphatase" "XFAM:PF12456") 
(def-family-with-id "importin beta binding domain" "XFAM:PF01749") 
(def-family-with-id "iER" "XFAM:PF05760") 
(def-family-with-id "hepatitis C virus core" "XFAM:PF01542") 
(def-family-with-id "gonadotropin-releasing hormone" "XFAM:PF00446") 
(def-family-with-id "glia maturation factor" "IPR011171") 
;(def-family-with-id "gene family" "BE:RAS") 
;(def-family-with-id "fibroblast growth factor" "BE:FGF") 
;(def-family-with-id "farnesyltransferase" "BE:FNT") 
(def-family-with-id "nuclear factor of activated T cells (NFAT)" "IPR008366") 
;(def-family-with-id "nuclear factor kappaB" "BE:NFkappaB") 
(def-family-with-id "ezrin-radixin-moesin" "IPR011174") 
;(def-family-with-id "exocyst complex" "BE:EXOC") 
(def-family-with-id "eukaryotic translation initiation factor 3 subunit b" "IPR011400") 
;(def-family-with-id "erk1/2" "BE:ERK") 
(def-family-with-id "era" "IPR001292") 
(def-family-with-id "endothelin receptor B" "IPR001112") 
(def-family-with-id "eB" "XFAM:PF01683") 
(def-family-with-id "dioxygenase" "XFAM:PF00775") 
;(def-family-with-id "desmoglein" "BE:Desmoglein") 
(def-family-with-id "death effector domain" "XFAM:PF01335") 
(def-family-with-id "death domain" "XFAM:PF00531") 
(def-family-with-id "dCTP" "XFAM:PF03480") 
(def-family-with-id "cyclin e" "IPR028858") 
(def-family-with-id "coiled coil" "XFAM:PF05710") 
(def-family-with-id "cofactor of BRCA1 (COBRA1)" "XFAM:PF06209") 
(def-family-with-id "chord" "XFAM:PF04968") 
;(def-family-with-id "cholangiocarcinoma" "XFAM:PF04942") 
(def-family-with-id "chase" "XFAM:PF03924") 
(def-family-with-id "cdc48" "IPR005938") 
(def-family-with-id "calmodulin-binding domain" "XFAM:PF02888") 
(def-family-with-id "cAMP-dependent protein   kinase regulatory   subunit" "IPR012198") 
(def-family-with-id "c4" "XFAM:PF01413") 
;(def-family-with-id "c-Jun NH2-Terminal Kinase" "BE:JNK") 
;(def-family-with-id "c-Jun N-Terminal Kinase" "BE:JNK") 
;(def-family-with-id "c-Jun  N-terminal kinase" "BE:JNK") 
(def-family-with-id "c-Cbl associated" "IPR028506") 
;(def-family-with-id "branch" "XFAM:PF02485") 
(def-family-with-id "bombesin receptor" "IPR001556") 
(def-family-with-id "blip" "XFAM:PF07467") 
(def-family-with-id "beta-protein" "XFAM:PF14350") 
(def-family-with-id "beta-CASP" "XFAM:PF10996") 
(def-family-with-id "arsC" "XFAM:PF03960") 
(def-family-with-id "angiotensin II receptor" "IPR000248") 
(def-family-with-id "amphiphysin1" "IPR003017") 
(def-family-with-id "agouti" "XFAM:PF05039") 
;(def-family-with-id "adenylate cyclase" "BE:ADCY") 
(def-family-with-id "adenosine A2B receptor" "IPR001435") 
(def-family-with-id "adenomatous polyposis coli (APC)" "IPR026818") 
(def-family-with-id "acyl-CoA thioesterase" "XFAM:PF02551") 
;(def-family-with-id "aP2" "XFAM:PF00847") 
(def-family-with-id "WWP" "XFAM:PF00855") 
(def-family-with-id "WW" "XFAM:PF00397") 
(def-family-with-id "Ufd1" "XFAM:PF03152") 
;(def-family-with-id "Ubiquitin-conjugating enzyme" "XFAM:PF00179") 
(def-family-with-id "Uba domain" "XFAM:PF16577") 
(def-family-with-id "Tudor domain" "XFAM:PF00567") 
(def-family-with-id "Tuberculin" "XFAM:PF12198") 
;(def-family-with-id "Tuba" "BE:TUBA") 
;(def-family-with-id "Trk receptor" "BE:NTRK") 
(def-family-with-id "Trat" "XFAM:PF05818") 
;(def-family-with-id "Torc 1" "BE:mTORC1") 
(def-family-with-id "THiS family" "XFAM:PF02597" :maintain-case t) 
;(def-family-with-id "Thbs" "BE:THBS") 
(def-family-with-id "Tgfbeta1" "IPR003939") 
(def-family-with-id "Tetratricopeptide Repeat" "XFAM:PF13424") 
;(def-family-with-id "Tcf" "BE:TCF_LEF") 
(def-family-with-id "TNFbeta" "IPR002960") 
;(def-family-with-id "TNF-receptor family" "BE:TNFRSF") 
(def-family-with-id "TGFRII" "IPR017194") 
;(def-family-with-id "TGF-beta receptor" "BE:TGFBR") 
;(def-family-with-id "TGF-B" "BE:TGFB") 
(def-family-with-id "TBP binding" "XFAM:PF09247") 
;(def-family-with-id "Smad2/3-T220/T179" "BE:SMAD2_3") 
(def-family-with-id "Sec7 domain" "XFAM:PF01369") 
(def-family-with-id "Sea" "XFAM:PF01390") 
(def-family-with-id "STAg" "XFAM:PF08514") 
(def-family-with-id "SOCS box" "XFAM:PF07525") 
(def-family-with-id "SH2 Domain" "XFAM:PF00017") 
(def-family-with-id "Rotavirus non-structural" "XFAM:PF01452") 
(def-family-with-id "Ribosomal protein S6" "XFAM:PF01250") 
(def-family-with-id "Ribosomal Protein S6 Kinase" "IPR016238") 
;(def-family-with-id "RasGAPS" "BE:RasGAP") 
;(def-family-with-id "Ras family" "BE:RAS") 
(def-family-with-id "Rad3" "IPR013020") 
(def-family-with-id "RTX" "XFAM:PF02382") 
;(def-family-with-id "RNA polymerase 1" "BE:RNApo_I") 
(def-family-with-id "RNA binding domain" "XFAM:PF08675") 
(def-family-with-id "RHIM" "XFAM:PF12721") 
;(def-family-with-id "RAS family" "BE:RAS") 
(def-family-with-id "RAN binding" "XFAM:PF05508") 
(def-family-with-id "RAN GTPase" "IPR002041") 
(def-family-with-id "Pyruvate kinase" "IPR001697") 
;(def-family-with-id "Protein kinase C" "IPR012233") 
(def-family-with-id "Protease-activated receptor" "IPR003912") 
(def-family-with-id "Pif" "XFAM:PF05092") 
(def-family-with-id "Phosphotyrosine binding domain" "XFAM:PF08416") 
(def-family-with-id "Phosphatidylinositol kinase" "IPR015433") 
;(def-family-with-id "Phosphatidy-linositol 3-kinase" "BE:PI3K") 
;(def-family-with-id "Pertussis toxin" "BE:Pertussis_toxin") 
(def-family-with-id "Peroxisome proliferator-activated receptor" "IPR003074") 
;(def-family-with-id "Pak" "BE:PAK") 
;(def-family-with-id "PRKAG" "BE:AMPK_gamma") 
(def-family-with-id "PNRC" "XFAM:PF15365") 
;(def-family-with-id "PKA regulatory subunits" "BE:PRKAR") 
;(def-family-with-id "PI-3-kinase" "BE:PI3K") 
(def-family-with-id "PETN" "XFAM:PF03742") 
;(def-family-with-id "PDGFbb" "BE:PDGF_BB") 
(def-family-with-id "PAD" "XFAM:PF03068") 
;(def-family-with-id "P38MAPK" "BE:p38") 
;(def-family-with-id "P38 MAPK" "BE:p38") 
;(def-family-with-id "P2X" "BE:P2RX") 
(def-family-with-id "P2" "XFAM:PF07194") 
(def-family-with-id "OMPA" "XFAM:PF00691") 
;(def-family-with-id "Nf-kappaB" "BE:NFkappaB") 
;(def-family-with-id "Neuregulins" "BE:NRG") 
;(def-family-with-id "NcoA" "BE:NCOA") 
(def-family-with-id "NadA" "XFAM:PF02445") 
;(def-family-with-id "Na,K-ATPase" "BE:Na_K_ATPase") 
(def-family-with-id "NH" "IPR000981") 
;(def-family-with-id "NFkappa-B" "BE:NFkappaB") 
;(def-family-with-id "NF-KappaB" "BE:NFkappaB") 
;(def-family-with-id "NDR-family" "BE:NDRG") 
;(def-family-with-id "NDR family" "BE:NDRG") 
(def-family-with-id "NADH:ubiquinone oxidoreductase" "IPR003918") 
(def-family-with-id "Mitochondrial Pyruvate Carrier" "IPR005336") 
;(def-family-with-id "Mek" "BE:MEK") 
;(def-family-with-id "MEK 1/2" "BE:MEK") 
(def-family-with-id "MDM2 binding" "XFAM:PF14920") 
(def-family-with-id "MBT repeat" "XFAM:PF02820") 
(def-family-with-id "MATE" "XFAM:PF01554") 
;(def-family-with-id "MAC" "BE:MAC") 
(def-family-with-id "LSPR" "XFAM:PF06049") 
(def-family-with-id "LSm" "XFAM:PF01423" :maintain-case t) 
;(def-family-with-id "PLCG" "BE:PLCG") 
(def-family-with-id "protein Kinase C" "IPR012233") 
(def-family-with-id "KU" "XFAM:PF02735") 
;(def-family-with-id "Irx" "BE:IRX") 
(def-family-with-id "IPK" "XFAM:PF03770") 
(def-family-with-id "INFc" "IPR001288") 
;(def-family-with-id "IGFBPs" "BE:IGFBP") 
;(def-family-with-id "IGFBP" "BE:IGFBP") 
(def-family-with-id "IG" "XFAM:PF00047") 
(def-family-with-id "IF-2" "XFAM:PF11987") 
(def-family-with-id "HRPE" "XFAM:PF06188") 
(def-family-with-id "HMGA" "IPR005708") 
(def-family-with-id "HIT" "XFAM:PF01230") 
;(def-family-with-id "HIFalpha" "BE:HIF_alpha") 
(def-family-with-id "H4" "IPR001951") 
(def-family-with-id "H domain" "XFAM:PF16453") 
;(def-family-with-id "Gucy" "BE:GUCY") 
;(def-family-with-id "Gq/11" "BE:G_q") 
(def-family-with-id "GoLoco motif" "XFAM:PF02188") 
(def-family-with-id "GINS complex" "IPR021151") 
(def-family-with-id "G protein alpha" "XFAM:PF00503") 
(def-family-with-id "G alpha" "XFAM:PF00503") 
(def-family-with-id "Fragile X Mental Retardation Protein" "IPR022034") 
;(def-family-with-id "Fgfr" "BE:FGFR") 
(def-family-with-id "Fanconi anemia-associated" "XFAM:PF15146") 
(def-family-with-id "Fa" "XFAM:PF08736") 
(def-family-with-id "FNIP" "XFAM:PF05725") 
;(def-family-with-id "FGFr" "BE:FGFR") 
(def-family-with-id "FCD" "XFAM:PF07729") 
(def-family-with-id "Ezrin/Radixin/Moesin" "IPR011174") 
;(def-family-with-id "Extracellular signal regulated kinase" "BE:ERK") 
(def-family-with-id "Eukaryotic translation initiation factor 4E binding" "IPR008606") 
(def-family-with-id "Eukaryotic initiation factor 4E" "XFAM:PF01652") 
(def-family-with-id "Eukaryotic Initiation Factor 4E" "XFAM:PF01652") 
;(def-family-with-id "Erk1/2" "BE:ERK") 
;(def-family-with-id "Erk 1/2" "BE:ERK") 
;(def-family-with-id "Eph receptors" "BE:Ephrin_receptor") 
;(def-family-with-id "Eph receptor" "BE:Ephrin_receptor") 
(def-family-with-id "Elongation factor Tu GTP-binding domain" "XFAM:PF00009") 
(def-family-with-id "Eiger" "IPR002959") 
(def-family-with-id "ETF" "XFAM:PF01012") 
(def-family-with-id "ENaC" "IPR004724") 
;(def-family-with-id "ENO" "BE:ENO") 
(def-family-with-id "ECSC" "XFAM:PF12787") 
(def-family-with-id "EAR" "XFAM:PF07897") 
(def-family-with-id "E2 binding domain" "XFAM:PF08825") 
(def-family-with-id "DnaK" "IPR012725") 
(def-family-with-id "Death-associated" "XFAM:PF15228") 
(def-family-with-id "DcR" "XFAM:PF14047") 
(def-family-with-id "DNaseI" "IPR016202") 
(def-family-with-id "DNAJ" "XFAM:PF00226") 
(def-family-with-id "DNA polymerase a" "IPR002298") 
(def-family-with-id "DNA polymerase  processivity factor" "XFAM:PF02916") 
(def-family-with-id "Cytotoxic T-lymphocyte antigen-4" "IPR008096") 
(def-family-with-id "Cyclin-dependent Kinase Inhibitor" "XFAM:PF02234") 
(def-family-with-id "Cyclin-Dependent Kinase inhibitor" "XFAM:PF02234") 
;(def-family-with-id "Cyclin D" "BE:Cyclin_D") 
(def-family-with-id "Cx" "XFAM:PF01705") 
(def-family-with-id "Cue domain" "XFAM:PF02845") 
(def-family-with-id "Cpt" "XFAM:PF07931") 
(def-family-with-id "Coronin 1B" "IPR027340") 
(def-family-with-id "Claudin1" "IPR003548") 
;(def-family-with-id "Class I HDACs" "BE:HDAC_I") 
;(def-family-with-id "Cc" "XFAM:PF04942") 
(def-family-with-id "Cavin" "IPR026752") 
(def-family-with-id "Cannabinoid receptor type 1" "IPR000810") 
(def-family-with-id "Cannabinoid receptor" "IPR002230") 
(def-family-with-id "Calcium binding" "XFAM:PF11535") 
(def-family-with-id "CXC chemokine" "IPR001089") 
(def-family-with-id "CXC Chemokine" "IPR001089") 
(def-family-with-id "CGS" "IPR000277") 
(def-family-with-id "CCAAT/enhancer-binding" "IPR016468") 
(def-family-with-id "CC2-LZ" "XFAM:PF16516") 
;(def-family-with-id "C1" "BE:C1") 
;(def-family-with-id "C-jun NH2-terminal kinase" "BE:JNK") 
;(def-family-with-id "C-JNK" "BE:JNK") 
(def-family-with-id "Branch" "XFAM:PF02485" :maintain-case t) 
;(def-family-with-id "Basic" "XFAM:PF01586") 
(def-family-with-id "BON" "XFAM:PF04972") 
(def-family-with-id "BBS" "XFAM:PF02044") 
(def-family-with-id "Aurora kinase" "IPR030616") 
(def-family-with-id "Asp5" "XFAM:PF17000") 
;(def-family-with-id "Aldh" "BE:ALDH") 
(def-family-with-id "Adenosine Receptor" "IPR001634") 
(def-family-with-id "Adenomatous polyposis coli" "IPR026836") 
(def-family-with-id "Ad" "XFAM:PF09793") 
;(def-family-with-id "Activin B" "BE:Activin_B") 
(def-family-with-id "Abi" "XFAM:PF02517") 
(def-family-with-id "AW" "XFAM:PF04721") 
(def-family-with-id "ATG22" "XFAM:PF11700") 
;(def-family-with-id "APC/C" "BE:APC_C") 
;(def-family-with-id "AMPK alpha1beta1gamma2" "BE:AMPK_A1B1G2") 
;(def-family-with-id "AMPA receptor" "BE:GRIA") 
(def-family-with-id "AMP binding" "XFAM:PF00501") 
;(def-family-with-id "ACSL" "BE:ACSL") 
;(def-family-with-id "ACCs" "BE:ACC") 
(def-family-with-id "ABI" "XFAM:PF02517") 
;(def-family-with-id "3d" "XFAM:PF06725") 
;(def-family-with-id "1ng/ml" "BE:TGFB") 
;(def-family-with-id "1mM" "XFAM:PF05383") 
(def-family-with-id "17beta-HSD" "IPR011348") 
;(def-family-with-id "100U/ml" "IPR002959") 
