(in-package :sparser)

(defun define-reach-term (term)
  (eval (trips/reach-term->def-bio term #'reach-class->krisp)))



(defun simplify-colons (x)
  (if (search "::" x)
      (concatenate 'string
                   (subseq x 0 (search "::" x) )
                   ":"
                   (subseq x (+ 2 (search "::" x) )))
      x))

(defparameter *reach-phrases* nil)
    
(defun reach-class->krisp (term)
  (if (or
       (search "inhibitor" (car term))
       (search "receptor" (car term))
       (search "/" (car term))
       (search " site" (car term))
       (search "anti-" (car term))
       (search "RNA" (car term)))
      (then ;;(format t "~% rejecting REACH UAZ definition of ~s" (car term))
            (push (concatenate 'string (car term) ".") *reach-phrases*)
            nil)
      (ecase (intern (string-upcase (second term))) ;; drop the ONT:
        (cellosaurus 'cell-line)
        ((cl tissuelist) 'cell-type)
        ((go mesh) 'cellular-process)
        ((interpro uniprot) 'protein)
        (pfam 'protein-family)
        ;;"pfam"
        (pubchem 'molecule)
        (taxonomy 'organism)
        (uberon 'bio-organ)
        (uaz (ecase (intern (string-upcase (fourth term)))
               (cellline 'cell-line)
               (simple-chemical 'molecule)
               (family 'protein-family)
               (site nil) ;; drop this
               ((gene gene-or-gene-product) 'gene)
               (protein 'protein)
               )))))


(defparameter *reach-cancers-or-tissues*
  '(("B-cell lymphoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0067") 
    ("Ewing Sarcoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0302") 
    ("breast carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0592") 
    ("colon adenocarcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0159") 
    ("colorectal adenocarcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0159") 
    ("colorectal carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0161") 
    ("esophageal carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0697") 
    ("hepatocellular carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0455") 
    ("lung adenocarcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0569") 
    ("lung carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0572") 
    ("malignant melanoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0614") 
    ("mammary carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0592") 
    ("nasopharyngeal carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0661") 
    ("non small cell lung carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0572") 
    ("osteosarcoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0723")
    ("ovarian carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0725") 
    ("pancreatic carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-0740") 
    ("papillary thyroid carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-1045") 
    ("thyroid carcinoma" "tissuelist" :TYPE "tissuetype" :ID "TS-1044")
    ("breast cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0591")
    ("cervical cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1221") 
    ("colon cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0160") 
    ("colorectal cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0160") 
    ("endometrial cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1222") 
    ("gastric cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0978") 
    ("head and neck cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1232") 
    ("lung cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0571") 
    ("oral cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0714") 
    ("ovarian cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1223") 
    ("pancreatic cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-0739") 
    ("prostate cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1224") 
    ("renal cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1225") 
    ("skin cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1227") 
    ("thyroid cancer" "tissuelist" :TYPE "tissuetype" :ID "TS-1226") 
    ))


(defparameter *reach-cells*
  '(
    ("podocyte" "cl" :TYPE "celltype" :ID "CL:0000653")
    ("B cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0068") 
    ("CML cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0147") 
    ("Ewing '" "tissuelist" :TYPE "tissuetype" :ID "TS-0302") 
    ("HeLa cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0136") 
    ("Hela cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0136") 
    ("Stromal cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0984") 
    ("T cell" "tissuelist" :TYPE "tissuetype" :ID "TS-1001") 
    ("adipose tissue" "tissuelist" :TYPE "tissuetype" :ID "TS-0013") 
    ("airway epithelial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0023") 
    ("airway smooth muscle" "tissuelist" :TYPE "tissuetype" :ID "TS-0024") 
    ("ascite" "tissuelist" :TYPE "tissuetype" :ID "TS-0058") 
    ("bone marrow" "tissuelist" :TYPE "tissuetype" :ID "TS-0087") 
    ("bowel" "tissuelist" :TYPE "tissuetype" :ID "TS-0490") 
    ("breast tumor" "tissuelist" :TYPE "tissuetype" :ID "TS-0597") 
    ("cardiac cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0115") 
    ("cervical ganglia" "tissuelist" :TYPE "tissuetype" :ID "TS-0132") 
    ("chorioallantoic membrane" "tissuelist" :TYPE "tissuetype" :ID "TS-0140") 
    ("colonic epithelium" "tissuelist" :TYPE "tissuetype" :ID "TS-0163") 
    ("coronary artery" "tissuelist" :TYPE "tissuetype" :ID "TS-0176") 
    ("corpus striatum" "tissuelist" :TYPE "tissuetype" :ID "TS-0183") 
    ("dental pulp" "tissuelist" :TYPE "tissuetype" :ID "TS-0195") 
    ("dorsal root ganglia" "tissuelist" :TYPE "tissuetype" :ID "TS-0954") 
    ("embryonic ectoderm" "tissuelist" :TYPE "tissuetype" :ID "TS-0216") 
    ("embryonic stem cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0263") 
    ("endothelial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0278") 
    ("endothelium" "tissuelist" :TYPE "tissuetype" :ID "TS-0278") 
    ("epidermi" "tissuelist" :TYPE "tissuetype" :ID "TS-0283") 
    ("epithelial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0288") 
    ("gastric corpu" "tissuelist" :TYPE "tissuetype" :ID "TS-0401") 
    ("gastric mucosa" "tissuelist" :TYPE "tissuetype" :ID "TS-0404") 
    ("glioma cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0416") 
    ("hair follicle" "tissuelist" :TYPE "tissuetype" :ID "TS-0432") 
    ("head kidney" "tissuelist" :TYPE "tissuetype" :ID "TS-1206") 
    ("hippocampus" "tissuelist" :TYPE "tissuetype" :ID "TS-0460") 
    ("hypothalamu" "tissuelist" :TYPE "tissuetype" :ID "TS-0469") 
    ("intestinal mucosa" "tissuelist" :TYPE "tissuetype" :ID "TS-0488") 
    ("leukemia cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0547") 
    ("liver tumor" "tissuelist" :TYPE "tissuetype" :ID "TS-0563") 
    ("lung fibroblast" "tissuelist" :TYPE "tissuetype" :ID "TS-0575") 
    ("lung tumour" "tissuelist" :TYPE "tissuetype" :ID "TS-0577") 
    ("lymph node" "tissuelist" :TYPE "tissuetype" :ID "TS-0579") 
    ("mammary tumor" "tissuelist" :TYPE "tissuetype" :ID "TS-0597") 
    ("mast cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0603") 
    ("mesenchymal stem cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0618") 
    ("microglial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0627") 
    ("myeloid cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0647") 
    ("myeloid leukemia" "tissuelist" :TYPE "tissuetype" :ID "TS-0147") 
    ("neural crest" "tissuelist" :TYPE "tissuetype" :ID "TS-0676") 
    ("neuronal cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0683") 
    ("organ of Corti" "tissuelist" :TYPE "tissuetype" :ID "TS-0717") 
    ("oviduct epithelium" "tissuelist" :TYPE "tissuetype" :ID "TS-1316") 
    ("pancreatic tumor" "tissuelist" :TYPE "tissuetype" :ID "TS-0742") 
    ("periodontal ligament" "tissuelist" :TYPE "tissuetype" :ID "TS-0763") 
    ("peripheral blood" "tissuelist" :TYPE "tissuetype" :ID "TS-0771") 
    ("peripheral nerve" "tissuelist" :TYPE "tissuetype" :ID "TS-0772") 
    ("peripheral nervous system" "tissuelist" :TYPE "tissuetype" :ID "TS-0808") 
    ("pre-B cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0819") 
    ("prefrontal cortex" "tissuelist" :TYPE "tissuetype" :ID "TS-1219") 
    ("pulmonary artery" "tissuelist" :TYPE "tissuetype" :ID "TS-0839") 
    ("renal epithelial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0505") 
    ("satellite cell" "tissuelist" :TYPE "tissuetype" :ID "TS-1205") 
    ("shell" "tissuelist" :TYPE "tissuetype" :ID "TS-0925") 
    ("skeletal muscle" "tissuelist" :TYPE "tissuetype" :ID "TS-0933") 
    ("skin epidermal cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0283") 
    ("small intestine" "tissuelist" :TYPE "tissuetype" :ID "TS-0942") 
    ("smooth muscle" "tissuelist" :TYPE "tissuetype" :ID "TS-0943") 
    ("spinal cord" "tissuelist" :TYPE "tissuetype" :ID "TS-0953") 
    ("squamous cell" "tissuelist" :TYPE "tissuetype" :ID "TS-1249") 
    ("stromal cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0984") 
    ("substantia nigra" "tissuelist" :TYPE "tissuetype" :ID "TS-0990") 
    ("synovial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-0995") 
    ("testi" "tissuelist" :TYPE "tissuetype" :ID "TS-1030") 
    ("thyroid tumor" "tissuelist" :TYPE "tissuetype" :ID "TS-1046") 
    ("umbilical vein endothelial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-1081") 
    ("umbilical vein" "tissuelist" :TYPE "tissuetype" :ID "TS-1082") 
    ("uteru" "tissuelist" :TYPE "tissuetype" :ID "TS-1102") 
    ("vascular endothelial cell" "tissuelist" :TYPE "tissuetype" :ID "TS-1106") 
    ))

(defparameter *reach-proteins*
  '(
    ("3-phosphoinositide-dependent protein kinase-1" "uniprot" :TYPE "protein" :ID "O15530") 
    ("5-LOX" "uniprot" :TYPE "protein" :ID "P28300") 
    ("ADAM protein" "uniprot" :TYPE "protein" :ID "B3MF39") 
    ("API-2" "uniprot" :TYPE "protein" :ID "Q13489") 
    ("AQP-4" "uniprot" :TYPE "protein" :ID "P55087") 
    ("Akt-mTOR" "uniprot" :TYPE "protein" :ID "P42345") 
    ("Ang II" "uniprot" :TYPE "protein" :ID "P01019") 
    ("Annexin V" "uniprot" :TYPE "protein" :ID "P08758") 
    ("Apoptosis signal regulating kinase 1" "uniprot" :TYPE "protein" :ID "Q99683") 
    ("BCL-2" "uniprot" :TYPE "protein" :ID "P10415") 
    ("BCL-XL" "uniprot" :TYPE "protein" :ID "Q07817") 
    ("BH3 interacting domain death agonist" "uniprot" :TYPE "protein" :ID "P55957") 
    ("BIM" "uniprot" :TYPE "protein" :ID "O43521") 
    ("BRAF-KSR1" "uniprot" :TYPE "protein" :ID "Q8IVT5") 
    ("Bcl -2" "uniprot" :TYPE "protein" :ID "P10415") 
    ("Bcl-2" "uniprot" :TYPE "protein" :ID "P10415") 
    ("Bcl-x protein" "uniprot" :TYPE "protein" :ID "Q07817") 
    ("Bcl-xL" "uniprot" :TYPE "protein" :ID "Q07817") 
    ("Beclin 1" "uniprot" :TYPE "protein" :ID "Q14457") 
    ("BxPC-ER" "uniprot" :TYPE "protein" :ID "P03372") 
    ("C-TAK1" "uniprot" :TYPE "protein" :ID "P27448") 
    ("C/EBP homologous protein" "uniprot" :TYPE "protein" :ID "P35638") 
    ("CA-AKT" "uniprot" :TYPE "protein" :ID "P54644") 
    ("CCAAT and enhancer binding protein delta" "uniprot" :TYPE "protein" :ID "P49716") 
    ("CDK4/6" "uniprot" :TYPE "protein" :ID "Q9XTR1") 
    ("CDK6" "uniprot" :TYPE "protein" :ID "Q00534") 
    ("CEBP-beta" "uniprot" :TYPE "protein" :ID "P17676") 
    ("CORE protein" "uniprot" :TYPE "protein" :ID "Q64897") 
    ("CRC" "uniprot" :TYPE "protein" :ID "Q8L925") 
    ("CRY2-CIB1" "uniprot" :TYPE "protein" :ID "Q99828") 
    ("CUL4B" "uniprot" :TYPE "protein" :ID "Q13620") 
    ("Ca-ATPase" "uniprot" :TYPE "protein" :ID "Q9SIY3") 
    ("Cab45-G" "uniprot" :TYPE "protein" :ID "Q8JTH0") 
    ("Calcium/calmodulin dependent protein kinase IV" "uniprot" :TYPE "protein" :ID "Q16566") 
    ("Cd-" "uniprot" :TYPE "protein" :ID "P00814") 
    ("Cdc25C associated protein kinase 1" "uniprot" :TYPE "protein" :ID "P27448") 
    ("Cdc42" "uniprot" :TYPE "protein" :ID "P60953") 
    ("Chk1" "uniprot" :TYPE "protein" :ID "O14757") 
    ("Constitutive Androstane Receptor" "uniprot" :TYPE "protein" :ID "Q14994") 
    ("DKK-1" "uniprot" :TYPE "protein" :ID "O94907") 
    ("DMP-1" "uniprot" :TYPE "protein" :ID "Q13316") 
    ("DNA-damage-inducible transcript 3" "uniprot" :TYPE "protein" :ID "P35638") 
    ("DS" "uniprot" :TYPE "protein" :ID "P49366") 
    ("Dclk1" "uniprot" :TYPE "protein" :ID "O15075") 
    ("DeltaRaf-1" "uniprot" :TYPE "protein" :ID "P03679") 
    ("Double Minute 2 Homolog" "uniprot" :TYPE "protein" :ID "Q00987") 
    ("E2-ERalpha" "uniprot" :TYPE "protein" :ID "P03372") 
    ("E3-ubiquitin ligase" "uniprot" :TYPE "protein" :ID "Q8GUH1") 
    ("EGFR-2" "uniprot" :TYPE "protein" :ID "Q9T1U6") 
    ("EGFR-C" "uniprot" :TYPE "protein" :ID "Q64896") 
    ("EGFR-TKI" "uniprot" :TYPE "protein" :ID "P16223") 
    ("EPS-8" "uniprot" :TYPE "protein" :ID "Q12929") 
    ("ERK-CREB" "uniprot" :TYPE "protein" :ID "A1CIL1") 
    ("ERK2-CA" "uniprot" :TYPE "protein" :ID "P28482") 
    ("ET-1-" "uniprot" :TYPE "protein" :ID "P05305") 
    ("ETV6-PDGFR" "uniprot" :TYPE "protein" :ID "P09619") 
    ("EpCAM" "uniprot" :TYPE "protein" :ID "P16422") 
    ("EphA2-SA" "uniprot" :TYPE "protein" :ID "O82265") 
    ("Epidermal Growth Factor Receptor" "uniprot" :TYPE "protein" :ID "P00533") 
    ("Epidermal growth factor receptor" "uniprot" :TYPE "protein" :ID "P00533") 
    ("ErbB2" "uniprot" :TYPE "protein" :ID "P04626") 
    ("EsA" "uniprot" :TYPE "protein" :ID "Q14254") 
    ("Extracellular signal Regulated Kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("Extracellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("FLAG-BRAF" "uniprot" :TYPE "protein" :ID "P15056") 
    ("FLAG-KRAS" "uniprot" :TYPE "protein" :ID "P01116") 
    ("FMS" "uniprot" :TYPE "protein" :ID "P07333") 
    ("FSH receptor" "uniprot" :TYPE "protein" :ID "P23945") 
    ("Fapp1-PH" "uniprot" :TYPE "protein" :ID "Q9HB20") 
    ("FasL-Fas" "uniprot" :TYPE "protein" :ID "P25445") 
    ("Flotillin-I" "uniprot" :TYPE "protein" :ID "P03657") 
    ("Fo" "uniprot" :TYPE "protein" :ID "P01100") 
    ("Follicle stimulating hormone" "uniprot" :TYPE "protein" :ID "P13709") 
    ("G protein coupled receptor 34" "uniprot" :TYPE "protein" :ID "Q9UPC5") 
    ("G protein coupled receptor" "uniprot" :TYPE "protein" :ID "Q18LE5") 
    ("G protein" "uniprot" :TYPE "protein" :ID "P31281") 
    ("G-protein-coupled receptor kinase" "uniprot" :TYPE "protein" :ID "P25098") 
    ("GFP-LC3" "uniprot" :TYPE "protein" :ID "P82160") 
    ("GH receptor" "uniprot" :TYPE "protein" :ID "P10912") 
    ("GIP receptor" "uniprot" :TYPE "protein" :ID "P48546") 
    ("GLI1" "uniprot" :TYPE "protein" :ID "P08151") 
    ("GLP-1" "uniprot" :TYPE "protein" :ID "P01275") 
    ("GMD" "uniprot" :TYPE "protein" :ID "O60547") 
    ("GPI-AP" "uniprot" :TYPE "protein" :ID "O14492") 
    ("GSEA" "uniprot" :TYPE "protein" :ID "Q46222") 
    ("GST-VRK3" "uniprot" :TYPE "protein" :ID "Q8IV63") 
    ("GTPase Activating Protein" "uniprot" :TYPE "protein" :ID "P20936") 
    ("GTPase activating protein" "uniprot" :TYPE "protein" :ID "P20936") 
    ("Ga" "uniprot" :TYPE "protein" :ID "Q9UI32") 
    ("Gab1-Akt" "uniprot" :TYPE "protein" :ID "P54644") 
    ("Grammostola spatulata mechanotoxin 4" "uniprot" :TYPE "protein" :ID "Q7YT39") 
    ("Grb10" "uniprot" :TYPE "protein" :ID "Q13322") 
    ("H-ra" "uniprot" :TYPE "protein" :ID "P01112") 
    ("H/R" "uniprot" :TYPE "protein" :ID "O43593") 
    ("HA-CD44" "uniprot" :TYPE "protein" :ID "P16070") 
    ("HA-RSK2" "uniprot" :TYPE "protein" :ID "P51812") 
    ("HA-p25" "uniprot" :TYPE "protein" :ID "P13985") 
    ("HBZY-1" "uniprot" :TYPE "protein" :ID "P03679") 
    ("HBs protein" "uniprot" :TYPE "protein" :ID "P0A3H1") 
    ("HCRP-1" "uniprot" :TYPE "protein" :ID "Q8NEZ2") 
    ("HR38 protein" "uniprot" :TYPE "protein" :ID "P49870") 
    ("HSP90 co-chaperone" "uniprot" :TYPE "protein" :ID "Q15185") 
    ("Hnf-4alpha" "uniprot" :TYPE "protein" :ID "P41235") 
    ("Hra" "uniprot" :TYPE "protein" :ID "P01112") 
    ("Hsc70 interacting protein" "uniprot" :TYPE "protein" :ID "P50502") 
    ("IFN inducible protein-10" "uniprot" :TYPE "protein" :ID "P02778") 
    ("IGF binding protein 3" "uniprot" :TYPE "protein" :ID "P17936") 
    ("IGF-1-" "uniprot" :TYPE "protein" :ID "P05019") 
    ("IIIE-IPR1" "uniprot" :TYPE "protein" :ID "Q8BVK9") 
    ("IL-1" "pfam" :TYPE "protein" :ID "PF00340") 
    ("IL-12" "uniprot" :TYPE "protein" :ID "Q9T1T6") 
    ("IL-1R-associated kinase 1" "uniprot" :TYPE "protein" :ID "P51617") 
    ("IL-1beta" "uniprot" :TYPE "protein" :ID "P01584") 
    ("IL-23" "uniprot" :TYPE "protein" :ID "O36373") 
    ("IL-29" "uniprot" :TYPE "protein" :ID "Q8IU54") 
    ("IL-31" "uniprot" :TYPE "protein" :ID "Q6EBC2") 
    ("IL-6 receptor" "uniprot" :TYPE "protein" :ID "P40189") 
    ("INSR-A" "uniprot" :TYPE "protein" :ID "P41064") 
    ("INSR-B" "uniprot" :TYPE "protein" :ID "P08711") 
    ("IkappaB-alpha" "uniprot" :TYPE "protein" :ID "P25963") 
    ("JAK-STAT" "uniprot" :TYPE "protein" :ID "P35610") 
    ("JNK protein" "uniprot" :TYPE "protein" :ID "P92208") 
    ("JNK1-1" "uniprot" :TYPE "protein" :ID "P03679") 
    ("JNK1-2" "uniprot" :TYPE "protein" :ID "Q9T1U6") 
    ("Jak-STAT" "uniprot" :TYPE "protein" :ID "P35610") 
    ("K-ra" "uniprot" :TYPE "protein" :ID "P01116") 
    ("KSR-1" "uniprot" :TYPE "protein" :ID "Q8IVT5") 
    ("Kra" "uniprot" :TYPE "protein" :ID "P01116") 
    ("LC3-II" "uniprot" :TYPE "protein" :ID "P04233") 
    ("LHB" "uniprot" :TYPE "protein" :ID "P01229") 
    ("LIN-12" "uniprot" :TYPE "protein" :ID "P14585") 
    ("LKB1-AMPK" "uniprot" :TYPE "protein" :ID "P54646") 
    ("LLC-PK1" "uniprot" :TYPE "protein" :ID "P30613") 
    ("LZ-EGFR" "uniprot" :TYPE "protein" :ID "P00533") 
    ("Light" "uniprot" :TYPE "protein" :ID "O43557") 
    ("Luciferase" "uniprot" :TYPE "protein" :ID "P08659") 
    ("Lysosomal sialidase" "uniprot" :TYPE "protein" :ID "Q99519") 
    ("M/L" "uniprot" :TYPE "protein" :ID "P40225") 
    ("MAK-2" "uniprot" :TYPE "protein" :ID "O14002") 
    ("MAPK and ERK kinase 1" "uniprot" :TYPE "protein" :ID "Q02750") 
    ("MAPK kinase" "uniprot" :TYPE "protein" :ID "P10506") 
    ("MAPK)/extracellular activating kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("MAPK)/extracellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("MCL-1" "uniprot" :TYPE "protein" :ID "Q07820") 
    ("MIG-6" "uniprot" :TYPE "protein" :ID "Q9UJM3") 
    ("MNK-1" "uniprot" :TYPE "protein" :ID "Q9BUB5") 
    ("MPR-Ag" "uniprot" :TYPE "protein" :ID "P55868") 
    ("MPS-Pho" "uniprot" :TYPE "protein" :ID "P0AG82") 
    ("Mcl-1 protein" "uniprot" :TYPE "protein" :ID "Q07820") 
    ("Mdm2" "uniprot" :TYPE "protein" :ID "Q00987") 
    ("MeCP2" "uniprot" :TYPE "protein" :ID "P51608") 
    ("Mitogen inducible gene-6" "uniprot" :TYPE "protein" :ID "Q9UJM3") 
    ("N protein" "uniprot" :TYPE "protein" :ID "P0C796") 
    ("N-Methyl-D-Aspartate receptor" "uniprot" :TYPE "protein" :ID "Q9R1M7") 
    ("NBM CD34cell" "uniprot" :TYPE "protein" :ID "Q13510") 
    ("NHS" "uniprot" :TYPE "protein" :ID "Q6T4R5") 
    ("NKD1-" "uniprot" :TYPE "protein" :ID "Q969G9") 
    ("NTSR1" "uniprot" :TYPE "protein" :ID "P30989") 
    ("Na-K-2Cl co-transporter" "uniprot" :TYPE "protein" :ID "P55011") 
    ("NaV1" "uniprot" :TYPE "protein" :ID "Q8NEY1") 
    ("Nano-S" "uniprot" :TYPE "protein" :ID "P05135") 
    ("Neil1" "uniprot" :TYPE "protein" :ID "Q96FI4") 
    ("Neuropeptide Y" "uniprot" :TYPE "protein" :ID "P01303") 
    ("Nm23-H1" "uniprot" :TYPE "protein" :ID "P15531") 
    ("Nra" "uniprot" :TYPE "protein" :ID "P01111") 
    ("Ntsr1" "uniprot" :TYPE "protein" :ID "P30989") 
    ("OSBP-PH" "uniprot" :TYPE "protein" :ID "P22059") 
    ("OSM" "uniprot" :TYPE "protein" :ID "P13725") 
    ("Ogg1" "uniprot" :TYPE "protein" :ID "O15527") 
    ("P-ERK1/2" "uniprot" :TYPE "protein" :ID "Q9ZUE0") 
    ("P21" "uniprot" :TYPE "protein" :ID "P38936") 
    ("P3" "uniprot" :TYPE "protein" :ID "P09131") 
    ("P75" "uniprot" :TYPE "protein" :ID "P14317") 
    ("PAC1 receptor" "uniprot" :TYPE "protein" :ID "P41586") 
    ("PACAP-" "uniprot" :TYPE "protein" :ID "P18509") 
    ("PANC-ER" "uniprot" :TYPE "protein" :ID "P03372") 
    ("PCCG-4" "uniprot" :TYPE "protein" :ID "Q9T1U4") 
    ("PD-L1" "uniprot" :TYPE "protein" :ID "Q9NZQ7") 
    ("PDGF receptor" "uniprot" :TYPE "protein" :ID "P16234") 
    ("PDGFRbeta" "uniprot" :TYPE "protein" :ID "P09619") 
    ("PFF-B" "uniprot" :TYPE "protein" :ID "P08711") 
    ("PI3-Kinase" "uniprot" :TYPE "protein" :ID "P54673") 
    ("PI3K regulatory subunit beta" "uniprot" :TYPE "protein" :ID "O00459") 
    ("PI3K-AKT" "uniprot" :TYPE "protein" :ID "P54644") 
    ("PI3K-AKT-mTOR" "uniprot" :TYPE "protein" :ID "P54644") 
    ("PI3K-Akt" "uniprot" :TYPE "protein" :ID "P54644") 
    ("PI3K-mTOR" "uniprot" :TYPE "protein" :ID "P42345") 
    ("PLCdelta1-PH" "uniprot" :TYPE "protein" :ID "P51178") 
    ("PLD1-PH" "uniprot" :TYPE "protein" :ID "Q13393") 
    ("PLK1" "uniprot" :TYPE "protein" :ID "P53350") 
    ("Pak2" "uniprot" :TYPE "protein" :ID "Q13177") 
    ("Panax ginseng extract" "uniprot" :TYPE "protein" :ID "Q15014") 
    ("Pi3k" "uniprot" :TYPE "protein" :ID "P42336") 
    ("Prism" "uniprot" :TYPE "protein" :ID "Q96FA3") 
    ("Protein Kinase" "uniprot" :TYPE "protein" :ID "P25848") 
    ("Pten" "uniprot" :TYPE "protein" :ID "P60484") 
    ("RAF-1" "uniprot" :TYPE "protein" :ID "P04049") 
    ("RAF-RBD" "uniprot" :TYPE "protein" :ID "P04049") 
    ("RAL guanine nucleotide dissociation stimulator" "uniprot" :TYPE "protein" :ID "Q12967") 
    ("REH" "uniprot" :TYPE "protein" :ID "P23141") 
    ("ROCK-FAK" "uniprot" :TYPE "protein" :ID "Q05397") 
    ("RR-P" "uniprot" :TYPE "protein" :ID "O75783") 
    ("RacGAP1" "uniprot" :TYPE "protein" :ID "Q9H0H5") 
    ("Raf-Erk" "uniprot" :TYPE "protein" :ID "P29323") 
    ("Rap1" "uniprot" :TYPE "protein" :ID "Q9NYB0") 
    ("Ras-extracellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("Ras/p42/p44 mitogen activated protein kinase" "uniprot" :TYPE "protein" :ID "P27638") 
    ("Recombinant PTTH" "uniprot" :TYPE "protein" :ID "P17219") 
    ("SA-beta-gal" "uniprot" :TYPE "protein" :ID "P16278") 
    ("SAMSN-1" "uniprot" :TYPE "protein" :ID "Q9NSI8") 
    ("SERPINE1" "uniprot" :TYPE "protein" :ID "P05121") 
    ("SKAR" "uniprot" :TYPE "protein" :ID "Q9BY77") 
    ("SOD-1" "uniprot" :TYPE "protein" :ID "P00441") 
    ("SR-A" "uniprot" :TYPE "protein" :ID "Q9XZL8") 
    ("SR-B1 protein" "uniprot" :TYPE "protein" :ID "Q8WTV0") 
    ("SS18-SSX1" "uniprot" :TYPE "protein" :ID "Q16384") 
    ("STR" "uniprot" :TYPE "protein" :ID "P13082") 
    ("SVCT-2 protein" "uniprot" :TYPE "protein" :ID "Q9UGH3") 
    ("SVCT-2" "uniprot" :TYPE "protein" :ID "Q9UGH3") 
    ("Smad 6" "uniprot" :TYPE "protein" :ID "O43541") 
    ("Smad 7" "uniprot" :TYPE "protein" :ID "O15105") 
    ("Son" "uniprot" :TYPE "protein" :ID "P18583") 
    ("Sp1" "uniprot" :TYPE "protein" :ID "P08047") 
    ("SphK1" "uniprot" :TYPE "protein" :ID "Q9NYA1") 
    ("Sr" "uniprot" :TYPE "protein" :ID "O76070") 
    ("TAK1 binding protein 1" "uniprot" :TYPE "protein" :ID "Q15750") 
    ("TGF-beta1 protein" "uniprot" :TYPE "protein" :ID "P01137") 
    ("TMI-2" "uniprot" :TYPE "protein" :ID "Q9T1U6") 
    ("TNF receptor associated factor 6" "uniprot" :TYPE "protein" :ID "Q9Y4K3") 
    ("TNF related apoptosis inducing ligand" "uniprot" :TYPE "protein" :ID "P50591") 
    ("TSST-1" "uniprot" :TYPE "protein" :ID "P06886") 
    ("TbetaR II" "uniprot" :TYPE "protein" :ID "P37173") 
    ("Tensin 3" "uniprot" :TYPE "protein" :ID "Q68CZ2") 
    ("Tgf-beta type I receptor" "uniprot" :TYPE "protein" :ID "P36897") 
    ("Toll like receptor 4" "uniprot" :TYPE "protein" :ID "O00206") 
    ("Tpl2" "uniprot" :TYPE "protein" :ID "P41279") 
    ("Tpm3" "uniprot" :TYPE "protein" :ID "P06753") 
    ("Transforming growth factor-beta1" "uniprot" :TYPE "protein" :ID "P01137")
    ("Transforming growth factor-beta1" "uniprot" :TYPE "protein" :ID "P01137") 
    ("Tri" "uniprot" :TYPE "protein" :ID "Q9NQV6") 
    ("TrkB-Fc" "uniprot" :TYPE "protein" :ID "Q06529") 
    ("Tumor Necrosis Factor" "uniprot" :TYPE "protein" :ID "P01375") 
    ("UCP2" "uniprot" :TYPE "protein" :ID "P55851") 
    ("VEGFa" "uniprot" :TYPE "protein" :ID "P15692") 
    ("Vaccinia related kinase 3" "uniprot" :TYPE "protein" :ID "Q8IV63") 
    ("Vascular endothelial-cadherin" "uniprot" :TYPE "protein" :ID "P33151") 
    ("WNK1-SPAK" "uniprot" :TYPE "protein" :ID "Q9UEW8") 
    ("Wart" "uniprot" :TYPE "protein" :ID "O95835") 
    ("XpJNK-p42" "uniprot" :TYPE "protein" :ID "Q8NFH3") 
    ("activator protein 1" "uniprot" :TYPE "protein" :ID "P05412") 
    ("alpha-ENaC" "uniprot" :TYPE "protein" :ID "P37088") 
    ("alpha-synuclein" "uniprot" :TYPE "protein" :ID "P37840") 
    ("alpha-toxin" "uniprot" :TYPE "protein" :ID "P0C911") 
    ("alpha-tubulin" "uniprot" :TYPE "protein" :ID "Q71G51") 
    ("amyloid precursor protein" "uniprot" :TYPE "protein" :ID "P05067") 
    ("amyloid-beta" "uniprot" :TYPE "protein" :ID "B7I895") 
    ("anaplastic lymphoma kinase" "uniprot" :TYPE "protein" :ID "Q9UM73") 
    ("androgen receptor" "uniprot" :TYPE "protein" :ID "P10275") 
    ("angiotensin II" "uniprot" :TYPE "protein" :ID "P01019") 
    ("angiotensin-II" "uniprot" :TYPE "protein" :ID "P01019") 
    ("annexin V" "uniprot" :TYPE "protein" :ID "P08758") 
    ("anti-CD28" "uniprot" :TYPE "protein" :ID "P10747") 
    ("anti-EGFR" "uniprot" :TYPE "protein" :ID "P00533") 
    ("anti-ERK" "uniprot" :TYPE "protein" :ID "P29323") 
    ("apolipoprotein E receptor 2" "uniprot" :TYPE "protein" :ID "Q14114") 
    ("apoptosis signal regulating kinase 1" "uniprot" :TYPE "protein" :ID "Q99683") 
    ("aquaporin-4" "uniprot" :TYPE "protein" :ID "P55087") 
    ("aurora kinase A" "uniprot" :TYPE "protein" :ID "O14965") 
    ("basic fibroblast growth factor" "uniprot" :TYPE "protein" :ID "P09038") 
    ("beta catenin" "uniprot" :TYPE "protein" :ID "P35222") 
    ("beta-ENaC" "uniprot" :TYPE "protein" :ID "P51168") 
    ("beta-MHC" "uniprot" :TYPE "protein" :ID "P05661") 
    ("beta-Raf" "uniprot" :TYPE "protein" :ID "P04049") 
    ("beta-TrCP" "uniprot" :TYPE "protein" :ID "Q91854") 
    ("beta-actin" "uniprot" :TYPE "protein" :ID "P60709") 
    ("beta-arrestin 1" "uniprot" :TYPE "protein" :ID "P49407") 
    ("beta-arrestin 2" "uniprot" :TYPE "protein" :ID "P32121") 
    ("beta-arrestin" "uniprot" :TYPE "protein" :ID "Q28281") 
    ("beta-catenin" "uniprot" :TYPE "protein" :ID "P35222") 
    ("beta-gal" "uniprot" :TYPE "protein" :ID "P70753") 
    ("beta-galactosidase" "uniprot" :TYPE "protein" :ID "P16278") 
    ("beta-myosin heavy chain" "uniprot" :TYPE "protein" :ID "P05661") 
    ("beta3 protein" "uniprot" :TYPE "protein" :ID "O09029") 
    ("betaAR-EGFR" "uniprot" :TYPE "protein" :ID "P00533") 
    ("c-Abl" "uniprot" :TYPE "protein" :ID "P00519") 
    ("c-CBL" "uniprot" :TYPE "protein" :ID "Q54KM6") 
    ("c-Cbl" "uniprot" :TYPE "protein" :ID "Q54KM6") 
    ("c-FOS" "uniprot" :TYPE "protein" :ID "P01100") 
    ("c-Fo" "uniprot" :TYPE "protein" :ID "P01100") 
    ("c-JNK" "uniprot" :TYPE "protein" :ID "P92208") 
    ("c-JUN" "uniprot" :TYPE "protein" :ID "P05412") 
    ("c-Jun N-terminal kinase" "uniprot" :TYPE "protein" :ID "P92208") 
    ("c-Jun N-terminal protein kinase" "uniprot" :TYPE "protein" :ID "P92208") 
    ("c-Jun NH2-terminal kinase" "uniprot" :TYPE "protein" :ID "P92208") 
    ("c-Jun" "uniprot" :TYPE "protein" :ID "P05412") 
    ("c-MET" "uniprot" :TYPE "protein" :ID "P08581") 
    ("c-MYC" "uniprot" :TYPE "protein" :ID "Q17103") 
    ("c-Myc" "uniprot" :TYPE "protein" :ID "Q17103") 
    ("c-RAF" "uniprot" :TYPE "protein" :ID "P04049") 
    ("c-Raf" "uniprot" :TYPE "protein" :ID "P04049") 
    ("c-fos" "uniprot" :TYPE "protein" :ID "P01100") 
    ("c-jun-NH2-terminal kinase" "uniprot" :TYPE "protein" :ID "P92208") 
    ("c-kit ligand" "uniprot" :TYPE "protein" :ID "P21583") 
    ("c-kit" "uniprot" :TYPE "protein" :ID "P10721") 
    ("ca-Raf" "uniprot" :TYPE "protein" :ID "P04049") 
    ("calcium/calmodulin dependent protein kinase I" "uniprot" :TYPE "protein" :ID "P27466") 
    ("calcium/calmodulin dependent protein kinase kinase-beta" "uniprot" :TYPE "protein" :ID "Q96RR4") 
    ("cancer-1" "uniprot" :TYPE "protein" :ID "P03679") 
    ("cardiac hypertrophy related gene Myosin light chain-2v" "uniprot" :TYPE "protein" :ID "P10916") 
    ("caspase 9" "uniprot" :TYPE "protein" :ID "P55211") 
    ("caspase-12" "uniprot" :TYPE "protein" :ID "Q075B4") 
    ("caspase-14" "uniprot" :TYPE "protein" :ID "P31944") 
    ("caspase-8" "uniprot" :TYPE "protein" :ID "Q14790") 
    ("caspase-9" "uniprot" :TYPE "protein" :ID "P55211") 
    ("cav-1" "uniprot" :TYPE "protein" :ID "Q03135") 
    ("cell cycle checkpoint kinase" "uniprot" :TYPE "protein" :ID "O14757") 
    ("chemoattractant protein-1" "uniprot" :TYPE "protein" :ID "P0CW71") 
    ("collagen-I" "uniprot" :TYPE "protein" :ID "P03657") 
    ("core protein" "uniprot" :TYPE "protein" :ID "Q64897") 
    ("cullin-5" "uniprot" :TYPE "protein" :ID "Q93034") 
    ("cyclooxygenase-2" "uniprot" :TYPE "protein" :ID "P35354") 
    ("cytochrome C" "uniprot" :TYPE "protein" :ID "P99999") 
    ("cytochrome c" "uniprot" :TYPE "protein" :ID "P99999") 
    ("cytokeratin 18" "uniprot" :TYPE "protein" :ID "P05783") 
    ("d -1" "uniprot" :TYPE "protein" :ID "P22058") 
    ("death receptor 5" "uniprot" :TYPE "protein" :ID "O14763") 
    ("death receptor-4" "uniprot" :TYPE "protein" :ID "O00220") 
    ("decoy receptor" "uniprot" :TYPE "protein" :ID "Q9UBN6") 
    ("dual-luciferase" "uniprot" :TYPE "protein" :ID "P08659") 
    ("ecdysone receptor" "uniprot" :TYPE "protein" :ID "P49880") 
    ("elongation factor 2" "uniprot" :TYPE "protein" :ID "P13639") 
    ("endothelial protein C receptor" "uniprot" :TYPE "protein" :ID "Q9UNN8") 
    ("erythroid related factor 2" "uniprot" :TYPE "protein" :ID "Q16236") 
    ("estrogen receptor" "uniprot" :TYPE "protein" :ID "P03372") 
    ("executive caspase" "uniprot" :TYPE "protein" :ID "P42574") 
    ("extra-cellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular regulated protein kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular regulating kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular signal regulated kinase 1/2" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "Q16539") 
    ("extracellular signal regulated kinase" "uniprot" :TYPE "protein" :ID "Q9NZJ5") 
    ("extracellular signal regulated kinase1/2" "uniprot" :TYPE "protein" :ID "Q9ZUE0") 
    ("extracellular signal regulated kinases 1 and 2" "uniprot" :TYPE "protein" :ID "P27361") 
    ("extracellular signal regulated protein kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular signal related kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("extracellular-signal-regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("fatty acid binding protein" "uniprot" :TYPE "protein" :ID "P00505") 
    ("fatty acid synthase" "uniprot" :TYPE "protein" :ID "P49327") 
    ("fibroblast growth factor 1" "uniprot" :TYPE "protein" :ID "P05230") 
    ("fibroblast growth factor receptor" "uniprot" :TYPE "protein" :ID "Q4H3K6") 
    ("gamma-glutamate-cysteine ligase catalytic subunit" "uniprot" :TYPE "protein" :ID "P48506") 
    ("glial fibrillary acidic protein" "uniprot" :TYPE "protein" :ID "P14136") 
    ("glucocorticoid receptor" "uniprot" :TYPE "protein" :ID "P04150") 
    ("glutathione S-transferase" "uniprot" :TYPE "protein" :ID "O60760") 
    ("goat" "uniprot" :TYPE "protein" :ID "Q96T53") 
    ("green fluorescent protein-microtubule-associated protein 1-light chain 3" "uniprot" :TYPE "protein" :ID "P82160") 
    ("growth associated protein 43" "uniprot" :TYPE "protein" :ID "P17677") 
    ("growth hormone" "uniprot" :TYPE "protein" :ID "P01241") 
    ("hematopoietic cell kinase" "uniprot" :TYPE "protein" :ID "P08631") 
    ("heme oxygenase 1" "uniprot" :TYPE "protein" :ID "P09601") 
    ("heme regulated inhibitor" "uniprot" :TYPE "protein" :ID "Q9BQI3") 
    ("heparin binding EGF like growth factor" "uniprot" :TYPE "protein" :ID "Q99075") 
    ("heparin binding protein" "uniprot" :TYPE "protein" :ID "P20160") 
    ("hnRNP F" "uniprot" :TYPE "protein" :ID "P52597") 
    ("hypoxia inducible factor 1-alpha" "uniprot" :TYPE "protein" :ID "Q16665") 
    ("hypoxia inducible factor-1alpha" "uniprot" :TYPE "protein" :ID "Q16665") 
    ("incretin hormone" "uniprot" :TYPE "protein" :ID "P01275") 
    ("inducible NOS" "uniprot" :TYPE "protein" :ID "P35228") 
    ("inflammatory protein-3alpha" "uniprot" :TYPE "protein" :ID "P78556") 
    ("inositol 1,4,5-trisphosphate receptor" "uniprot" :TYPE "protein" :ID "Q8WSR4") 
    ("insulin receptor" "uniprot" :TYPE "protein" :ID "P06213") 
    ("integrin-beta1" "uniprot" :TYPE "protein" :ID "P05556") 
    ("interferon gamma" "uniprot" :TYPE "protein" :ID "P01579") 
    ("interleukin-10" "uniprot" :TYPE "protein" :ID "P22301") 
    ("its receptor" "uniprot" :TYPE "protein" :ID "P00533") 
    ("janus kinase 2" "uniprot" :TYPE "protein" :ID "O60674") 
    ("kelch like ECH associated protein 1" "uniprot" :TYPE "protein" :ID "Q14145") 
    ("leukemia inhibitory factor" "uniprot" :TYPE "protein" :ID "P15018") 
    ("lipid dehydrogenase" "uniprot" :TYPE "protein" :ID "P00338") 
    ("lipoprotein receptor" "uniprot" :TYPE "protein" :ID "P98155") 
    ("mCitrine-KRas" "uniprot" :TYPE "protein" :ID "P01116") 
    ("mL-1" "uniprot" :TYPE "protein" :ID "Q9NTI2") 
    ("mPGES-1" "uniprot" :TYPE "protein" :ID "O14684") 
    ("major histocompatibility complex-class II" "uniprot" :TYPE "protein" :ID "P04233") 
    ("mammalian target of rapamycin" "uniprot" :TYPE "protein" :ID "P42345") 
    ("matrix metalloproteinase-12" "uniprot" :TYPE "protein" :ID "P39900") 
    ("matrix metalloproteinase-13" "uniprot" :TYPE "protein" :ID "P45452") 
    ("matrix metalloproteinase-7" "uniprot" :TYPE "protein" :ID "P09237") 
    ("methyl-CpG-binding protein 2" "uniprot" :TYPE "protein" :ID "P51608") 
    ("miR-29" "uniprot" :TYPE "protein" :ID "Q9T1R9") 
    ("microphthalmia associated transcription factor" "uniprot" :TYPE "protein" :ID "O75030") 
    ("microsomal prostaglandin synthetase-1" "uniprot" :TYPE "protein" :ID "O14684") 
    ("mitogen activated protein kinase (MAPK) kinase1" "uniprot" :TYPE "protein" :ID "Q02750") 
    ("mitogen activated protein kinase 14" "uniprot" :TYPE "protein" :ID "Q16539") 
    ("mitogen activated protein kinase integrating kinase 1" "uniprot" :TYPE "protein" :ID "Q9BUB5") 
    ("mitogen activated protein kinase kinase kinase 7" "uniprot" :TYPE "protein")
    ("mitogen actived protein kinase" "uniprot" :TYPE "protein" :ID "P27638") 
    ("monocyte chemotactic protein 1" "uniprot" :TYPE "protein" :ID "P13500") 
    ("multidrug resistance 1" "uniprot" :TYPE "protein" :ID "P08183") 
    ("myosin light chain" "uniprot" :TYPE "protein" :ID "P86703") 
    ("myosin phosphatase target subunit 1" "uniprot" :TYPE "protein" :ID "O14974") 
    ("nec-1" "uniprot" :TYPE "protein" :ID "P29120") 
    ("neurotrophic factor" "uniprot" :TYPE "protein" :ID "P20783") 
    ("neutrophil elastase" "uniprot" :TYPE "protein" :ID "P08246") 
    ("nuclear factor erythroid 2 related factor2" "uniprot" :TYPE "protein" :ID "Q16236") 
    ("opto-AKT" "uniprot" :TYPE "protein" :ID "P54644") 
    ("opto-Raf" "uniprot" :TYPE "protein" :ID "P04049") 
    ("osteoclast associated receptor" "uniprot" :TYPE "protein" :ID "Q8IYS5") 
    ("p15 protein" "uniprot" :TYPE "protein" :ID "P41478") 
    ("p21 activated kinase 4" "uniprot" :TYPE "protein" :ID "O96013") 
    ("p27 Kip1" "uniprot" :TYPE "protein" :ID "P46527") 
    ("p38 mitogen activated protein kinase" "uniprot" :TYPE "protein" :ID "P27638") 
    ("p38 mitogen activated protein kinase" "uniprot" :TYPE "protein" :ID "Q16539") 
    ("p38MAPK protein" "uniprot" :TYPE "protein" :ID "O62618") 
    ("pErk" "uniprot" :TYPE "protein" :ID "Q9NZJ5") 
    ("pErk1/2" "uniprot" :TYPE "protein" :ID "Q9ZUE0") 
    ("pJNK antibodies" "uniprot" :TYPE "protein" :ID "Q8NFH3") 
    ("pJNK antibody" "uniprot" :TYPE "protein" :ID "Q8NFH3") 
    ("pSER" "uniprot" :TYPE "protein" :ID "P18168") 
    ("pSPS-pERK" "uniprot" :TYPE "protein" :ID "Q9NZJ5") 
    ("pSmad4" "uniprot" :TYPE "protein" :ID "Q13485") 
    ("pY-ErbB2" "uniprot" :TYPE "protein" :ID "P04626") 
    ("pY-ErbB3" "uniprot" :TYPE "protein" :ID "P21860") 
    ("patients.Phosphoinositide 3-kinase" "uniprot" :TYPE "protein" :ID "P42336") 
    ("phosphatidyl-inositol 3-kinase" "pfam" :TYPE "protein" :ID "PF00454")
    ("phosphatidylinositol-3 kinase" "pfam" :TYPE "protein" :ID "PF00454")
    ("phospho-ERK" "uniprot" :TYPE "protein" :ID "P29323") 
    ("phosphoinositide 3-kinase" "uniprot" :TYPE "protein" :ID "P42336") 
    ("phosphoinositide dependent kinase 1" "uniprot" :TYPE "protein" :ID "Q15118") 
    ("phosphoinositide interacting protein" "uniprot" :TYPE "protein" :ID "P0C851") 
    ("phosphoserine aminotransferase" "uniprot" :TYPE "protein" :ID "Q9Y617") 
    ("phosphoserine phosphatase" "uniprot" :TYPE "protein" :ID "P78330") 
    ("plasminogen activator inhibitor 1" "uniprot" :TYPE "protein" :ID "P05121") 
    ("polycomb repressive complex 2" "uniprot" :TYPE "protein" :ID "P21243") 
    ("pregnane X receptor" "uniprot" :TYPE "protein" :ID "O75469") 
    ("prolyl hydroxylase" "uniprot" :TYPE "protein" :ID "P20941") 
    ("protein 3" "uniprot" :TYPE "protein" :ID "Q12988") 
    ("protein A" "uniprot" :TYPE "protein" :ID "P02810") 
    ("protein C" "uniprot" :TYPE "protein" :ID "P02810") 
    ("protein FADD" "uniprot" :TYPE "protein" :ID "Q13158") 
    ("protein HS1" "uniprot" :TYPE "protein" :ID "P27348") 
    ("protein can" "uniprot" :TYPE "protein" :ID "P35658") 
    ("protein kinase B" "uniprot" :TYPE "protein" :ID "P31749") 
    ("protein kinase R" "uniprot" :TYPE "protein" :ID "P19525") 
    ("protein p19" "uniprot" :TYPE "protein" :ID "Q9Y328") 
    ("protein set" "uniprot" :TYPE "protein" :ID "Q01105") 
    ("rabaptin-5" "uniprot" :TYPE "protein" :ID "Q15276") 
    ("reverse transcriptase" "uniprot" :TYPE "protein" :ID "O00370") 
    ("runt related transcription factor 2" "uniprot" :TYPE "protein" :ID "Q13950") 
    ("scaffolding protein" "uniprot" :TYPE "protein" :ID "P26748") 
    ("sclerosis complex 2" "uniprot" :TYPE "protein" :ID "P49815") 
    ("serine/threonine protein kinase" "uniprot" :TYPE "protein" :ID "O75460") 
    ("serum albumin" "uniprot" :TYPE "protein" :ID "P02768") 
    ("signal regulated kinase" "uniprot" :TYPE "protein" :ID "P29323") 
    ("sirtuin-1" "uniprot" :TYPE "protein" :ID "P03679") 
    ("small GTPase Rhoptery associated protein 1" "uniprot" :TYPE "protein" :ID "Q9NYB0") 
    ("sortilin-NTSR1" "uniprot" :TYPE "protein" :ID "P30989") 
    ("stem cell factor" "uniprot" :TYPE "protein" :ID "P21583") 
    ("substance p" "uniprot" :TYPE "protein" :ID "P20366") 
    ("suppressor of cytokine signaling" "uniprot" :TYPE "protein" :ID "Q9NSE2") 
    ("synapsin I" "uniprot" :TYPE "protein" :ID "P17600") 
    ("thrombin receptor" "uniprot" :TYPE "protein" :ID "P25116") 
    ("toxic shock syndrome toxin-1" "uniprot" :TYPE "protein" :ID "P06886") 
    ("transcription factor E2F1" "uniprot" :TYPE "protein" :ID "Q01094") 
    ("transcription factor GATA-4" "uniprot" :TYPE "protein" :ID "P43694") 
    ("transforming growth factor alpha" "uniprot" :TYPE "protein" :ID "P01135") 
    ("transforming growth factor-alpha" "uniprot" :TYPE "protein" :ID "P01135") 
    ("transforming growth factor-beta-activated kinase 1" "uniprot" :TYPE "protein" :ID "O43318") 
    ("transmembrane protein" "uniprot" :TYPE "protein" :ID "O42043") 
    ("tumor necrosis factor" "uniprot" :TYPE "protein" :ID "P01375") 
    ("tumor suppressor protein" "uniprot" :TYPE "protein" :ID "Q9BT92") 
    ("unique G-protein-coupled receptor" "uniprot" :TYPE "protein" :ID "F4IEM5") 
    ("urokinase-type plasminogen activator" "uniprot" :TYPE "protein" :ID "P00749") 
    ("vasoactive intestinal polypeptide" "uniprot" :TYPE "protein" :ID "P01282") 
    ;;("ANOVA" "uniprot" :TYPE "protein" :ID "Q9UNW9") ("wt-IPR1" "uniprot" :TYPE "protein" :ID "Q8BVK9")
    ))

(defparameter *reach-terms*
  '(
    ("stage" "uberon" :TYPE "organ" :ID "UBERON:0000105") 
    ("backbone" "uberon" :TYPE "organ" :ID "UBERON:0001130") 
    ("stroma" "uberon" :TYPE "organ" :ID "UBERON:0003891") 
    ("Life" "uberon" :TYPE "organ" :ID "UBERON:0000104")
    ("mucosa associated lymphoid tissue" "uberon" :TYPE "organ" :ID "UBERON:0001961")
    ("neural tissue" "uberon" :TYPE "organ" :ID "UBERON:0003714")
    ("pancreatic secretion" "uberon" :TYPE "organ" :ID "UBERON:0004795")
    ("vaginal mucosa" "uberon" :TYPE "organ" :ID "UBERON:0004983")
    ("hind paw" "uberon" :TYPE "organ" :ID "UBERON:0002387")
    ("R6" "uberon" :TYPE "organ" :ID "UBERON:0005519")
    ("pleural effusion" "uberon" :TYPE "organ" :ID "UBERON:0000175")
    ("cerebrovascular system" "uberon" :TYPE "organ" :ID "UBERON:0008998")
    ("follicular fluid" "uberon" :TYPE "organ" :ID "UBERON:0000038")
    ("ganglionic eminence" "uberon" :TYPE "organ" :ID "UBERON:0004023")
    ("cortical plate" "uberon" :TYPE "organ" :ID "UBERON:0005343")
    ("white matter" "uberon" :TYPE "organ" :ID "UBERON:0002316")
    ("radiu" "uberon" :TYPE "organ" :ID "UBERON:0001423")
    ("renin-angiotensin system" "uberon" :TYPE "organ" :ID "UBERON:0018229")
    ("cardiac mesoderm" "uberon" :TYPE "organ" :ID "UBERON:0007005")
    ("fece" "uberon" :TYPE "organ" :ID "UBERON:0001988")
    ("respiratory tract" "uberon" :TYPE "organ" :ID "UBERON:0000065")
    ("body fluid" "uberon" :TYPE "organ" :ID "UBERON:0006314")
    ("cervical spinal cord" "uberon" :TYPE "organ" :ID "UBERON:0002726")
    ("nape of neck" "uberon" :TYPE "organ" :ID "UBERON:0012477")
    ("subventricular zone" "uberon" :TYPE "organ" :ID "UBERON:0004922")
    ("tail vein" "uberon" :TYPE "organ" :ID "UBERON:0003481")
    ("granulation tissue" "uberon" :TYPE "organ" :ID "UBERON:0010211")
    ("immune system" "uberon" :TYPE "organ" :ID "UBERON:0002405")
    ("lamina propria" "uberon" :TYPE "organ" :ID "UBERON:0000030")
    ("dermi" "uberon" :TYPE "organ" :ID "UBERON:0002067")
    ("sex specific" "uberon" :TYPE "organ" :ID "UBERON:0014402")
    ("hematopoietic system" "uberon" :TYPE "organ" :ID "UBERON:0002390")
    ("Atla" "uberon" :TYPE "organ" :ID "UBERON:0001092")
    
    
    ("homeostasis" "go" :TYPE "bioprocess" :ID "GO:0042592") 
    ("endocytosis" "go" :TYPE "bioprocess" :ID "GO:0006897") 
    ("metabolism" "go" :TYPE "bioprocess" :ID "GO:0008152") 
    ("ruffle" "go" :TYPE "cellular-component" :ID "GO:0001726") 
    ("cytokinesis" "go" :TYPE "bioprocess" :ID "GO:0000910") 
    ("dedifferentiation" "go" :TYPE "bioprocess" :ID "GO:0043696") 
    ("BMMC" "uaz" :TYPE "cellline" :ID "UA-CLine-100011") 
    ("VPC" "uaz" :TYPE "cellline" :ID "UA-CLine-100113") 
    ("293T" "cellosaurus" :TYPE "cellline" :ID "CVCL_0063") 
    ("MDA-MB-435" "cellosaurus" :TYPE "cellline" :ID "CVCL_0417") 
    ("U937" "cellosaurus" :TYPE "cellline" :ID "CVCL_0007") 
    ("ZR75-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_0588") 
    ("NJ" "cellosaurus" :TYPE "cellline" :ID "CVCL_8822") 
    ("Panc-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_0480") 
    ("OD" "cellosaurus" :TYPE "cellline" :ID "CVCL_0G09") 
    ("143B" "cellosaurus" :TYPE "cellline" :ID "CVCL_2270") 
    ("U266" "cellosaurus" :TYPE "cellline" :ID "CVCL_0566") 
    ("T47D" "cellosaurus" :TYPE "cellline" :ID "CVCL_0553") 
    ("EBC1" "cellosaurus" :TYPE "cellline" :ID "CVCL_2891") 

    
    ("invasiveness" "mesh" :TYPE "bioprocess" :ID "D009361") 
    ("infiltration" "mesh" :TYPE "bioprocess" :ID "D009361") 
    ("smoke" "uaz" :TYPE "simple-chemical" :ID "UA-BP-SC-00380") 
    ("NAD (P) H" "uaz" :TYPE "simple-chemical" :ID "UA-BP-SC-00370") 
    ("diacetate" "pubchem" :TYPE "simple-chemical" :ID "96") 
    ("MPEP" "pubchem" :TYPE "simple-chemical" :ID "3025961") 
    ("vitamin D" "pubchem" :TYPE "simple-chemical" :ID "12895043") 
    ("1,25-dihydroxyvitamin D" "pubchem" :TYPE "simple-chemical" :ID "5280453") 
    ("nitric oxide" "pubchem" :TYPE "simple-chemical" :ID "145068") 
    ("ITT" "pubchem" :TYPE "simple-chemical" :ID "8583") 
    ("E3" "pubchem" :TYPE "simple-chemical" :ID "5756") 
    ("agarose" "pubchem" :TYPE "simple-chemical" :ID "11966311") 
    ("M2" "pubchem" :TYPE "simple-chemical" :ID "25058172") 
    ("LY 294002" "pubchem" :TYPE "simple-chemical" :ID "3973") 
    ("protoporphyrin-IX" "pubchem" :TYPE "simple-chemical" :ID "4971") 
    ("carbon monoxide" "pubchem" :TYPE "simple-chemical" :ID "281") 
    ("iron" "pubchem" :TYPE "simple-chemical" :ID "23925") 
    ("M1" "pubchem" :TYPE "simple-chemical" :ID "13019211") 
    ("gold" "pubchem" :TYPE "simple-chemical" :ID "46878529") 
    ("quinolinic acid" "pubchem" :TYPE "simple-chemical" :ID "1066") 
    ("N-methyl-D-aspartate" "pubchem" :TYPE "simple-chemical" :ID "22880") 
    ("galactosamine" "pubchem" :TYPE "simple-chemical" :ID "24154") 
    ("phalloidin" "pubchem" :TYPE "simple-chemical" :ID "441542") 
    ("Y-27632" "pubchem" :TYPE "simple-chemical" :ID "448042") 
    ("propionate" "pubchem" :TYPE "simple-chemical" :ID "104745") 
    ("morphine" "pubchem" :TYPE "simple-chemical" :ID "23253564") 
    ("Adenosine monophosphate" "pubchem" :TYPE "simple-chemical" :ID "6083") 
    ("sugar" "pubchem" :TYPE "simple-chemical" :ID "5988") 
    ("parthenolide" "pubchem" :TYPE "simple-chemical" :ID "7251185") 
    ("FCCP" "pubchem" :TYPE "simple-chemical" :ID "3330") 
    ("I-BET151" "pubchem" :TYPE "simple-chemical" :ID "52912189") 
    ("15d-PGJ2" "pubchem" :TYPE "simple-chemical" :ID "5311211") 
    ("guanidine" "pubchem" :TYPE "simple-chemical" :ID "3520") 
    ("Polyglutamine" "pubchem" :TYPE "simple-chemical" :ID "5961") 
    ("AAD" "pubchem" :TYPE "simple-chemical" :ID "469") 
    ("T antigen" "pubchem" :TYPE "simple-chemical" :ID "6857385") 
    ("HAA" "pubchem" :TYPE "simple-chemical" :ID "547") 
    ("DMSO" "pubchem" :TYPE "simple-chemical" :ID "679") 
    ("PHA665752" "pubchem" :TYPE "simple-chemical" :ID "10461815") 
    ("DOPAquinone" "pubchem" :TYPE "simple-chemical" :ID "439316") 
    ("gallic acid" "pubchem" :TYPE "simple-chemical" :ID "370") 
    ("compound C" "pubchem" :TYPE "simple-chemical" :ID "11524144") 
    ("palmitic acid" "pubchem" :TYPE "simple-chemical" :ID "985") 
    ("malondialdehyde" "pubchem" :TYPE "simple-chemical" :ID "10964") 
    ("5-hydroxyindoleacetic acid" "pubchem" :TYPE "simple-chemical" :ID "9061") 
    ("5-HIAA" "pubchem" :TYPE "simple-chemical" :ID "1826") 
    ("E1" "pubchem" :TYPE "simple-chemical" :ID "5870") 
    ("TAK-165" "pubchem" :TYPE "simple-chemical" :ID "644692") 
    ("SV" "pubchem" :TYPE "simple-chemical" :ID "7020159") 
    ("iodine" "pubchem" :TYPE "simple-chemical" :ID "807") 
    ("Fe (III)" "pubchem" :TYPE "simple-chemical" :ID "29936") 
    ("arsenic trioxide" "pubchem" :TYPE "simple-chemical" :ID "545") 
    ("GppNHp" "pubchem" :TYPE "simple-chemical" :ID "86289562") 
    ("dimethyl sulfoxide" "pubchem" :TYPE "simple-chemical" :ID "679") 
    ("NU7441" "pubchem" :TYPE "simple-chemical" :ID "11327430") 
    ("rosmarinic acid" "pubchem" :TYPE "simple-chemical" :ID "5281792") 
    ;; HUH ("water" "pubchem" :TYPE "simple-chemical" :ID "962") 
    ("sodium sulfate" "pubchem" :TYPE "simple-chemical" :ID "24436") 
    ("PD 98059" "pubchem" :TYPE "simple-chemical" :ID "4713") 
    ;; HUH ("Atlantic" "pubchem" :TYPE "simple-chemical" :ID "297") 
    ("oleic acid" "pubchem" :TYPE "simple-chemical" :ID "445639") 
    ("photoreceptor cell" "cl" :TYPE "celltype" :ID "CL:0000210") 
    ("SV40" "taxonomy" :TYPE "species" :ID "10633")

    ("Haemophilus influenzae" "taxonomy" :TYPE "species" :ID "727") 
    ("Sprague-Dawley rat" "taxonomy" :TYPE "species" :ID "10116") 
    ("Caenorhabditis elegans" "taxonomy" :TYPE "species" :ID "6239") 
    ("Epstein-Barr virus" "taxonomy" :TYPE "species" :ID "10376") 
    ("guinea pig" "taxonomy" :TYPE "species" :ID "10141") 
    ("Helicobacter pylori" "taxonomy" :TYPE "species" :ID "210") 
    ("transgenic mice" "taxonomy" :TYPE "species" :ID "10090") 
    ("Wistar rat" "taxonomy" :TYPE "species" :ID "10116") 
    ("nude mice" "taxonomy" :TYPE "species" :ID "10090") 
    ("S. aureus" "taxonomy" :TYPE "species" :ID "1280")

    ("Cox-2" "uniprot" :TYPE "gene" :ID "P35354") 
    ("Sp1" "uniprot" :TYPE "gene" :ID "P08047") 
    ("Grb10" "uniprot" :TYPE "gene" :ID "Q13322") 
    ("Grb10" "uniprot" :TYPE "gene-or-gene-product" :ID "Q13322") 
    ("E3 ubiquitin ligase" "pfam" :TYPE "family" :ID "PF12483") 
    ("clamp" "pfam" :TYPE "family" :ID "PF14769") 
    ("nucleoside diphosphate kinase" "pfam" :TYPE "family" :ID "PF00334") 
    ("glycogen synthase" "pfam" :TYPE "family" :ID "PF05693") 
    ("3D" "pfam" :TYPE "family" :ID "PF06725") 
    ("il12" "pfam" :TYPE "family" :ID "PF03039") 
    ("amino acid synthesis" "pfam" :TYPE "family" :ID "PF06684") 
    ("BH3" "pfam" :TYPE "family" :ID "PF15285") 
    ("glutathione peroxidase" "pfam" :TYPE "family" :ID "PF00255") 
    ("S4" "pfam" :TYPE "family" :ID "PF01479") 
    ("EF-hand domain" "pfam" :TYPE "family" :ID "PF08976") 
    ("EF-hand" "pfam" :TYPE "family" :ID "PF09068") 
    ;; bad ("calcium binding" "pfam" :TYPE "family" :ID "PF11535") 
    ;; bad ("nine protein" "pfam" :TYPE "family" :ID "PF05322") 
    ("BTG family" "pfam" :TYPE "family" :ID "PF07742") 
    ;; bad ("RNA binding" "pfam" :TYPE "family" :ID "PF01877")
    ("innate immune response" "go" :TYPE "bioprocess" :ID "GO:0045087")
    ("bioenergetic" "go" :TYPE "bioprocess" :ID "GO:0006091")
    ("programmed cell death" "go" :TYPE "bioprocess" :ID "GO:0006915")
    ("energy metabolism" "go" :TYPE "bioprocess" :ID "GO:0006091")
    ("Cell Cycle" "go" :TYPE "bioprocess" :ID "GO:0007049")
    ("glycolysi" "go" :TYPE "bioprocess" :ID "GO:0006096")
    ("autophagic cell death" "go" :TYPE "bioprocess" :ID "GO:0048102")
    ("DNA replication" "go" :TYPE "bioprocess" :ID "GO:0006260")
    ("DNA damage checkpoint" "go" :TYPE "bioprocess" :ID "GO:0000077")
    ("cell-cell adhesion" "go" :TYPE "bioprocess" :ID "GO:0016337")
    ("mitochondrial membrane potential" "go" :TYPE "bioprocess" :ID "GO:0051881")
    ("adaptive immunity" "go" :TYPE "bioprocess" :ID "GO:0002250")
    ("necrotic cell death" "mesh" :TYPE "bioprocess" :ID "D009336")
    ("tumor microenvironment" "mesh" :TYPE "bioprocess" :ID "D059016")
    ("catabolic process" "go" :TYPE "bioprocess" :ID "GO:0009056")
    ("protein folding" "go" :TYPE "bioprocess" :ID "GO:0006457")
    ("stress response" "go" :TYPE "bioprocess" :ID "GO:0006950")
    ("response to stress" "go" :TYPE "bioprocess" :ID "GO:0006950")
    ("Programmed cell death" "go" :TYPE "bioprocess" :ID "GO:0006915")
    ("epithelial to mesenchymal transition" "go" :TYPE "bioprocess" :ID "GO:0001837")
    ("subcellular localization" "go" :TYPE "bioprocess" :ID "GO:0051179")
    ("TCA cycle" "go" :TYPE "bioprocess" :ID "GO:0006099")
    ("oxidative phosphorylation" "go" :TYPE "bioprocess" :ID "GO:0006119")
    ("OxPho" "go" :TYPE "bioprocess" :ID "GO:0006119")
    ("cytokine production" "go" :TYPE "bioprocess" :ID "GO:0001816")
    ("cell differentiation" "go" :TYPE "bioprocess" :ID "GO:0030154")
    ("inflammatory response" "go" :TYPE "bioprocess" :ID "GO:0006954")
    ("immune response" "go" :TYPE "bioprocess" :ID "GO:0006955")
    ("cell viability" "mesh" :TYPE "bioprocess" :ID "D002470")
    ("signal transduction" "go" :TYPE "bioprocess" :ID "GO:0007165")
    ("signalling pathway" "go" :TYPE "bioprocess" :ID "GO:0007165")
    ("proteolysi" "go" :TYPE "bioprocess" :ID "GO:0006508")
    ("signalling cascade" "go" :TYPE "bioprocess" :ID "GO:0007165")
    ("protein degradation" "go" :TYPE "bioprocess" :ID "GO:0006508")
    ("cell migration" "go" :TYPE "bioprocess" :ID "GO:0016477")
    ("DNA repair" "go" :TYPE "bioprocess" :ID "GO:0006281")
    ("cell cycle" "go" :TYPE "bioprocess" :ID "GO:0007049")
    ("DNA damage response" "go" :TYPE "bioprocess" :ID "GO:0000077")
    ("PC." "cellosaurus" :TYPE "cellline" :ID "CVCL_0035")
    ("ASPC-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_0152")
    ("HCT 116" "cellosaurus" :TYPE "cellline" :ID "CVCL_0291")
    ("H1650" "cellosaurus" :TYPE "cellline" :ID "CVCL_1483")
    ("C75" "cellosaurus" :TYPE "cellline" :ID "CVCL_5248")
    ("HEK 293" "cellosaurus" :TYPE "cellline" :ID "CVCL_0045")
    ("Y79" "cellosaurus" :TYPE "cellline" :ID "CVCL_1893")
    ("human keratinocyte" "cellosaurus" :TYPE "cellline" :ID "CVCL_9T09")
    ("BT-20" "cellosaurus" :TYPE "cellline" :ID "CVCL_0178")
    ("human mammary" "cellosaurus" :TYPE "cellline" :ID "CVCL_Y905")
    ("HS-5" "cellosaurus" :TYPE "cellline" :ID "CVCL_0809")
    ("PLC/PRF/5" "cellosaurus" :TYPE "cellline" :ID "CVCL_0485")
    ("N87" "cellosaurus" :TYPE "cellline" :ID "CVCL_1603")
    ("GEF-" "cellosaurus" :TYPE "cellline" :ID "CVCL_4V04")
    ("CGTH-W3" "cellosaurus" :TYPE "cellline" :ID "CVCL_3898")
    ("H23" "cellosaurus" :TYPE "cellline" :ID "CVCL_1547")
    ("H1703" "cellosaurus" :TYPE "cellline" :ID "CVCL_1490")
    ("C 21" "cellosaurus" :TYPE "cellline" :ID "CVCL_2323")
    ("SK-MEL 28" "cellosaurus" :TYPE "cellline" :ID "CVCL_0526")
    ("A172" "cellosaurus" :TYPE "cellline" :ID "CVCL_0131")
    ("U-251" "cellosaurus" :TYPE "cellline" :ID "CVCL_0021")
    ("ZR-75-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_0588")
    ("H460" "cellosaurus" :TYPE "cellline" :ID "CVCL_0459")
    ("MCF-7" "cellosaurus" :TYPE "cellline" :ID "CVCL_0031")
    ("Het-1A" "cellosaurus" :TYPE "cellline" :ID "CVCL_3702")
    ("Hs 578T" "cellosaurus" :TYPE "cellline" :ID "CVCL_0332")
    ("NALM6" "cellosaurus" :TYPE "cellline" :ID "CVCL_0092")
    ("DOHH2" "cellosaurus" :TYPE "cellline" :ID "CVCL_1179")
    ("Beas-2B" "cellosaurus" :TYPE "cellline" :ID "CVCL_0168")
    ("T-ALL" "cellosaurus" :TYPE "cellline" :ID "CVCL_1736")
    ("Colo-205" "cellosaurus" :TYPE "cellline" :ID "CVCL_0218")
    ("MiaPACA-2" "cellosaurus" :TYPE "cellline" :ID "CVCL_0428")
    ("CFPAC-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_1119")
    ("D407" "cellosaurus" :TYPE "cellline" :ID "CVCL_8183")
    ("HuCCT-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_0324")
    ("BXPC-3" "cellosaurus" :TYPE "cellline" :ID "CVCL_0186")
    ("D1" "cellosaurus" :TYPE "cellline" :ID "CVCL_3502")
    ("K562" "cellosaurus" :TYPE "cellline" :ID "CVCL_0004")
    ("BAT ," "cellosaurus" :TYPE "cellline" :ID "CVCL_E470")
    ("MIA PaCa-2" "cellosaurus" :TYPE "cellline" :ID "CVCL_0428")
    ("HPAF-II" "cellosaurus" :TYPE "cellline" :ID "CVCL_0313")
    ("TPC-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_6298")
    ("UMSCC-1" "cellosaurus" :TYPE "cellline" :ID "CVCL_7707")
    ("NCI-H292" "cellosaurus" :TYPE "cellline" :ID "CVCL_0455")
    ("H446" "cellosaurus" :TYPE "cellline" :ID "CVCL_1562")
    ("L-02" "cellosaurus" :TYPE "cellline" :ID "CVCL_6926")
    ("H1299" "cellosaurus" :TYPE "cellline" :ID "CVCL_0060")
    ("A549" "cellosaurus" :TYPE "cellline" :ID "CVCL_0023")
    ("B lymphocyte" "cl" :TYPE "celltype" :ID "CL:0000236")
    ("pancreatic beta cell" "cl" :TYPE "celltype" :ID "CL:0000169")
    ("basal cell" "cl" :TYPE "celltype" :ID "CL:0000646")
    ("bone marrow cell" "cl" :TYPE "celltype" :ID "CL:0002092")
    ("foam cell" "cl" :TYPE "celltype" :ID "CL:0000891")
    ("cardiac fibroblast" "cl" :TYPE "celltype" :ID "CL:0002548")
    ("colonic epithelial cell" "cl" :TYPE "celltype" :ID "CL:0011108")
    ("aortic endothelial cell" "cl" :TYPE "celltype" :ID "CL:0002544")
    ("cardiac muscle cell" "cl" :TYPE "celltype" :ID "CL:0000746")
    ("NK cell" "cl" :TYPE "celltype" :ID "CL:0000623")
    ("mononuclear cell" "cl" :TYPE "celltype" :ID "CL:0000842")
    ("Natural Killer cell" "cl" :TYPE "celltype" :ID "CL:0000623")
    ("dendritic cell" "cl" :TYPE "celltype" :ID "CL:0000451")
    ("alveolar epithelial cell" "cl" :TYPE "celltype" :ID "CL:0000322")
    ("bronchial epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002328")
    ("cerebellar neuron" "cl" :TYPE "celltype" :ID "CL:1001611")
    ("hematopoietic stem cell" "cl" :TYPE "celltype" :ID "CL:0000037")
    ("aortic smooth muscle cell" "cl" :TYPE "celltype" :ID "CL:0002539")
    ("cerebellar granule cell" "cl" :TYPE "celltype" :ID "CL:0001031")
    ("cumulus cell" "cl" :TYPE "celltype" :ID "CL:0000711")
    ("transitional B cell" "cl" :TYPE "celltype" :ID "CL:0000818")
    ("antibody secreting cell" "cl" :TYPE "celltype" :ID "CL:0000946")
    ("mature B cell" "cl" :TYPE "celltype" :ID "CL:0000785")
    ("bone marrow macrophage" "cl" :TYPE "celltype" :ID "CL:0002476")
    ("bone marrow stromal cell" "cl" :TYPE "celltype" :ID "CL:0010001")
    ("bone marrow mononuclear cell" "cl" :TYPE "celltype" :ID "CL:0010004")
    ("capillary endothelial cell" "cl" :TYPE "celltype" :ID "CL:0002144")
    ("glomerular cell" "cl" :TYPE "celltype" :ID "CL:1000746")
    ("hepatic stellate cell" "cl" :TYPE "celltype" :ID "CL:0000632")
    ("alveolar macrophage" "cl" :TYPE "celltype" :ID "CL:0000583")
    ("helper T cell" "cl" :TYPE "celltype" :ID "CL:0000912")
    ("cytotoxic T cell" "cl" :TYPE "celltype" :ID "CL:0000910")
    ("granulosa cell" "cl" :TYPE "celltype" :ID "CL:0000501")
    ("retinal cell" "cl" :TYPE "celltype" :ID "CL:0009004")
    ("prostate epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002231")
    ("muscle cell" "cl" :TYPE "celltype" :ID "CL:0000187")
    ("precursor cell" "cl" :TYPE "celltype" :ID "CL:0011115")
    ("mammary epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002327")
    ("mature oocyte" "cl" :TYPE "celltype" :ID "CL:0000025")
    ("Muller cell" "cl" :TYPE "celltype" :ID "CL:0011107")
    ("mesangial cell" "cl" :TYPE "celltype" :ID "CL:0000650")
    ("vascular smooth muscle cell" "cl" :TYPE "celltype" :ID "CL:0000359")
    ("be cell" "cl" :TYPE "celltype" :ID "CL:0000968")
    ("odontoblast" "cl" :TYPE "celltype" :ID "CL:0000060")
    ("retinal pigment epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002586")
    ("Kupffer cell" "cl" :TYPE "celltype" :ID "CL:0000091")
    ("yolk cell" "cl" :TYPE "celltype" :ID "CL:0000428")
    ("cortical neuron" "cl" :TYPE "celltype" :ID "CL:0002609")
    ("Synoviocyte" "cl" :TYPE "celltype" :ID "CL:0000214")
    ("Immune Cell" "cl" :TYPE "celltype" :ID "CL:0000738")
    ("synoviocyte" "cl" :TYPE "celltype" :ID "CL:0000214")
    ("pyramidal neuron" "cl" :TYPE "celltype" :ID "CL:0000598")
    ("venous endothelial cell" "cl" :TYPE "celltype" :ID "CL:0002543")
    ("Th17 cell" "cl" :TYPE "celltype" :ID "CL:0000899")
    ("kidney cell" "cl" :TYPE "celltype" :ID "CL:1000497")
    ("microvascular endothelial cell" "cl" :TYPE "celltype" :ID "CL:2000008")
    ("hippocampal neuron" "cl" :TYPE "celltype" :ID "CL:0002608")
    ("peritoneal macrophage" "cl" :TYPE "celltype" :ID "CL:0000581")
    ("smooth muscle cell" "cl" :TYPE "celltype" :ID "CL:0000192")
    ("photoreceptor cell" "cl" :TYPE "celltype" :ID "CL:0000210")
    ("breast epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002327")
    ("gamete" "cl" :TYPE "celltype" :ID "CL:0000300")
    ("cardiac neuron" "cl" :TYPE "celltype" :ID "CL:0010022")
    ("neural stem cell" "cl" :TYPE "celltype" :ID "CL:0000047")
    ("melanoblast" "cl" :TYPE "celltype" :ID "CL:0000541")
    ("Th1 cell" "cl" :TYPE "celltype" :ID "CL:0000545")
    ("goblet cell" "cl" :TYPE "celltype" :ID "CL:0000160")
    ("retinal ganglion cell" "cl" :TYPE "celltype" :ID "CL:0000740")
    ("inflammatory cell" "cl" :TYPE "celltype" :ID "CL:0009002")
    ("dopaminergic cell" "cl" :TYPE "celltype" :ID "CL:0000700")
    ("primary sensory neuron" "cl" :TYPE "celltype" :ID "CL:0000531")
    ("ventricular myocyte" "cl" :TYPE "celltype" :ID "CL:0002131")
    ("embryonic fibroblast" "cl" :TYPE "celltype" :ID "CL:2000042")
    ("dopaminergic neuron" "cl" :TYPE "celltype" :ID "CL:0000700")
    ("eukaryotic cell" "cl" :TYPE "celltype" :ID "CL:0000255")
    ("intestinal epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002563")
    ("crypt cell" "cl" :TYPE "celltype" :ID "CL:0000849")
    ("stem cell" "cl" :TYPE "celltype" :ID "CL:0000034")
    ("immune cell" "cl" :TYPE "celltype" :ID "CL:0000738")
    ("hematopoietic cell" "cl" :TYPE "celltype" :ID "CL:0000988")
    ("acinar cell" "cl" :TYPE "celltype" :ID "CL:0000622")
    ("pancreatic epithelial cell" "cl" :TYPE "celltype" :ID "CL:0000083")
    ("primary neuron" "cl" :TYPE "celltype" :ID "CL:0000530")
    ("peripheral blood mononuclear cell" "cl" :TYPE "celltype" :ID "CL:2000001")
    ("mammary gland epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002327")
    ("type II alveolar epithelial cell" "cl" :TYPE "celltype" :ID "CL:0002063")
    ("lung epithelial cell" "cl" :TYPE "celltype" :ID "CL:0000082")
    ("lung endothelial cell" "cl" :TYPE "celltype" :ID "CL:1001567")
    ("neurofibrillary tangle" "go" :TYPE "cellular-component" :ID "GO:0097418")
    ("adherens junction" "go" :TYPE "cellular-component" :ID "GO:0005912")
    ("mitochondrial outer membrane" "go" :TYPE "cellular-component" :ID "GO:0005741")
    ("aggresome" "go" :TYPE "cellular-component" :ID "GO:0016235")
    ("cell wall" "go" :TYPE "cellular-component" :ID "GO:0005618")
    ("basal lamina" "go" :TYPE "cellular-component" :ID "GO:0005605")
    ("basement membrane" "go" :TYPE "cellular-component" :ID "GO:0005604")
    ("stress fibers" "go" :TYPE "cellular-component" :ID "GO:0001725")
    ("primary cilium" "go" :TYPE "cellular-component" :ID "GO:0072372")
    ("mitochondrial respiratory chain" "go" :TYPE "cellular-component" :ID "GO:0005746")
    ("endocytic vesicle" "go" :TYPE "cellular-component" :ID "GO:0030139")
    ("perinuclear region" "uniprot" :TYPE "cellular-component" :ID "SL-0198")
    ("clathrin coated pit" "uniprot" :TYPE "cellular-component" :ID "SL-0069")
    ("multivesicular bodies" "go" :TYPE "cellular-component" :ID "GO:0005771")
    ("stress fiber" "go" :TYPE "cellular-component" :ID "GO:0001725")
    ("actin cytoskeleton" "go" :TYPE "cellular-component" :ID "GO:0015629")
    ("mitotic spindle" "go" :TYPE "cellular-component" :ID "GO:0072686")
    ("sarcomere" "go" :TYPE "cellular-component" :ID "GO:0030017")
    ("extracellular space" "go" :TYPE "cellular-component" :ID "GO:0005615")
    ("replication fork" "go" :TYPE "cellular-component" :ID "GO:0005657")
    ("late endosome" "go" :TYPE "cellular-component" :ID "GO:0005770")
    ("microsome" "uniprot" :TYPE "cellular-component" :ID "SL-0166")
    ("recycling endosome" "go" :TYPE "cellular-component" :ID "GO:0055037")
    ("lipid droplet" "uniprot" :TYPE "cellular-component" :ID "SL-0154")
    ("nucleolu" "go" :TYPE "cellular-component" :ID "GO:0005730")
    ("cell surface" "go" :TYPE "cellular-component" :ID "GO:0009986")
    ("tight junction" "uniprot" :TYPE "cellular-component" :ID "SL-0265")
    ("target cell" "uniprot" :TYPE "cellular-component" :ID "SL-0487")
    ("immunological synapse" "go" :TYPE "cellular-component" :ID "GO:0001772")
    ("cell membrane" "uniprot" :TYPE "cellular-component" :ID "SL-0039")
    ("mitochondrial membrane" "go" :TYPE "cellular-component" :ID "GO:0031966")
    ("Toll Like Receptor" "interpro" :TYPE "family" :ID "IPR017241")
    ("ubiquitin conjugating enzyme" "pfam" :TYPE "family" :ID "PF00179")
    ("transcriptional regulator" "pfam" :TYPE "family" :ID "PF02082")
    ("Fibroblast growth factor" "pfam" :TYPE "family" :ID "PF00167")
    ("steroid receptor co-activator" "pfam" :TYPE "family" :ID "PF08832")
    ("BTB-Kelch protein" "interpro" :TYPE "family" :ID "IPR017096")
    ("protein kinase domain" "pfam" :TYPE "family" :ID "PF00069")
    ("virulence factor" "pfam" :TYPE "family" :ID "PF13769")
    ("calcitonin gene related peptide" "interpro" :TYPE "family" :ID "IPR015476")
    ("ion channel" "pfam" :TYPE "family" :ID "PF07885")
    ("phospholipase D" "interpro" :TYPE "family" :ID "IPR015679")
    ("vascular cell adhesion molecule-1" "interpro" :TYPE "family" :ID "IPR003989")
    ("alkaline phosphatase" "pfam" :TYPE "family" :ID "PF00245")
    ("cullin family" "pfam" :TYPE "family" :ID "PF00888")
    ("AP-1 transcription factor" "interpro" :TYPE "family" :ID "IPR000837")
    ("steroidogenic acute regulatory protein" "interpro" :TYPE "family" :ID "IPR029866")
    ("heat shock protein 70" "interpro" :TYPE "family" :ID "IPR013126")
    ("second mitochondria derived activator of caspase" "pfam" :TYPE "family"
     :ID "PF09057")
    ("retinoblastoma protein" "interpro" :TYPE "family" :ID "IPR028309")
    ("E7" "pfam" :TYPE "family" :ID "PF00527")
    ("retinoic acid receptor" "interpro" :TYPE "family" :ID "IPR003078")
    ("liver X receptor" "interpro" :TYPE "family" :ID "IPR023257")
    ("cytochrome P450" "pfam" :TYPE "family" :ID "PF00067")
    ("P450" "pfam" :TYPE "family" :ID "PF00067")
    ("aquaporin 1" "interpro" :TYPE "family" :ID "IPR023274")
    ("cyclin E" "interpro" :TYPE "family" :ID "IPR028858")
    ("F-box domain" "pfam" :TYPE "family" :ID "PF00646")
    ("Tgf-beta" "interpro" :TYPE "family" :ID "IPR015615")
    ("adipokinetic hormone" "pfam" :TYPE "family" :ID "PF06377")
    ("cyclin D" "interpro" :TYPE "family" :ID "IPR015451")
    ("fibroblast growth factor" "pfam" :TYPE "family" :ID "PF00167")
    ("Retinoic acid receptor" "interpro" :TYPE "family" :ID "IPR003078")
    ;;("S1" "pfam" :TYPE "family" :ID "PF00575")
    ("eukaryotic translation initiation factor 4E binding" "interpro" :TYPE "family" :ID "IPR008606")
    ("Cyclin E" "interpro" :TYPE "family" :ID "IPR028858")
    ("tumour necrosis factor" "interpro" :TYPE "family" :ID "IPR006053")
    ("interleukin-1 receptor" "interpro" :TYPE "family" :ID "IPR015621")
    ("bacterial lipoprotein" "pfam" :TYPE "family" :ID "PF12182")
    ("transforming growth factor-beta" "interpro" :TYPE "family" :ID "IPR016319")
    ("immediate early response" "interpro" :TYPE "family" :ID "IPR008653")
    ("Protein Kinase C" "interpro" :TYPE "family" :ID "IPR012233")
    ("interleukin 31" "pfam" :TYPE "family" :ID "PF15209")
    ("natriuretic peptide" "interpro" :TYPE "family" :ID "IPR000663")
    ("epithelial sodium channel" "interpro" :TYPE "family" :ID "IPR004724")
    ("dual specificity phosphatase" "interpro" :TYPE "family" :ID "IPR024950")
    ("MAGE family" "pfam" :TYPE "family" :ID "PF01454")
    ("adenosine A1 receptor" "interpro" :TYPE "family" :ID "IPR001068")
;; bad    ("Dexamethasone Induced" "pfam" :TYPE "family" :ID "PF15198")
;; bad    ("dexamethasone induced" "pfam" :TYPE "family" :ID "PF15198")
    ("eukaryotic initiation factor 4E" "pfam" :TYPE "family" :ID "PF01652")
    ("CREB binding" "pfam" :TYPE "family" :ID "PF09030")
    ("nuclear factor erythroid 2 related factor 2" "interpro" :TYPE "family"
     :ID "IPR029845")
    ("Toll like receptor" "interpro" :TYPE "family" :ID "IPR017241")
    ("insulin like growth factor" "interpro" :TYPE "family" :ID "IPR022350")
    ("protein kinase C" "interpro" :TYPE "family" :ID "IPR012233")
    ("transcriptional activator" "pfam" :TYPE "family" :ID "PF04949")
    ("TGF-beta" "interpro" :TYPE "family" :ID "IPR015615")
    ("Transforming growth factor-beta1 protein" "uniprot" :TYPE "gene" :ID "P01137")
    ("TbetaR I" "uniprot" :TYPE "gene" :ID "P36897")
    ("CAII protein" "uniprot" :TYPE "gene" :ID "P00918")
    ("cyclooxygenase 2" "uniprot" :TYPE "gene" :ID "P35354")
    ("surface protein" "uniprot" :TYPE "gene" :ID "O42043")
    ("p16 protein" "uniprot" :TYPE "gene" :ID "Q96518")
    ("purine nucleoside phosphorylase" "uniprot" :TYPE "gene" :ID "P00491")
    ("beta3 integrin" "uaz" :TYPE "gene" :ID "UA-BP-GGP-00176")
    ("suppressor of cytokine signaling-1" "uniprot" :TYPE "gene-or-gene-product" :ID "O15524")

    ("guanosine monophosphate" "pubchem" :TYPE "simple-chemical" :ID "6804")
    ("adenosine triphosphate" "pubchem" :TYPE "simple-chemical" :ID "5957")
    ("oroxylin A" "pubchem" :TYPE "simple-chemical" :ID "86289424")
    ("poly I : C" "pubchem" :TYPE "simple-chemical" :ID "86583374")
    ("G418" "pubchem" :TYPE "simple-chemical" :ID "2733531")
    ("(3) H" "pubchem" :TYPE "simple-chemical" :ID "119434")
    ("valproic acid" "pubchem" :TYPE "simple-chemical" :ID "3121")
    ("2-APB" "pubchem" :TYPE "simple-chemical" :ID "1598")
    ("phosphatidylinositol 3-phosphate" "pubchem" :TYPE "simple-chemical" :ID "6857403")
    ("CMXRo" "pubchem" :TYPE "simple-chemical" :ID "22613925")
    ("guanosine triphosphate" "pubchem" :TYPE "simple-chemical" :ID "6830")
    ("Suberoylanilide Hydroxamic Acid" "pubchem" :TYPE "simple-chemical" :ID "5311")
    ("Everolimu" "pubchem" :TYPE "simple-chemical" :ID "6442177")
    ("sialic acid" "pubchem" :TYPE "simple-chemical" :ID "445063")
    ("oleanolic acid" "pubchem" :TYPE "simple-chemical" :ID "10494")
    ("5-HMF" "pubchem" :TYPE "simple-chemical" :ID "237332")
    ("5-(Hydroxymethyl)-2-furaldehyde" "pubchem" :TYPE "simple-chemical" :ID "237332")
    ("ursolic acid" "pubchem" :TYPE "simple-chemical" :ID "64945")
    ("sodium iodide" "pubchem" :TYPE "simple-chemical" :ID "5238")
    ("vitamin A" "pubchem" :TYPE "simple-chemical" :ID "445354")
    ("thromboxane B2" "pubchem" :TYPE "simple-chemical" :ID "5283137")
    ("Poly I : C" "pubchem" :TYPE "simple-chemical" :ID "86583374")
    ("heparan sulfate" "pubchem" :TYPE "simple-chemical" :ID "53477714")
    ("sphingosine 1-phosphate" "pubchem" :TYPE "simple-chemical" :ID "5353956")
    ("exendin-4" "pubchem" :TYPE "simple-chemical" :ID "56927919")
    ("ADP-ribose" "pubchem" :TYPE "simple-chemical" :ID "192")
    ("Kn-93" "pubchem" :TYPE "simple-chemical" :ID "3837")
    ("Vitamin K2" "pubchem" :TYPE "simple-chemical" :ID "5282367")
    ("uric acid" "pubchem" :TYPE "simple-chemical" :ID "1175")
    ("superoxide anion" "pubchem" :TYPE "simple-chemical" :ID "5359597")
    ("Phytanic acid" "pubchem" :TYPE "simple-chemical" :ID "26840")
    ("uridine triphosphate" "pubchem" :TYPE "simple-chemical" :ID "6133")
    ("acridine orange" "pubchem" :TYPE "simple-chemical" :ID "62344")
    ("hyaluronic acid" "pubchem" :TYPE "simple-chemical" :ID "24759")
    ("ganglioside GD3" "pubchem" :TYPE "simple-chemical" :ID "20057331")
    ("S2" "pubchem" :TYPE "simple-chemical" :ID "5460602")
    ("glucose-6-phosphate" "pubchem" :TYPE "simple-chemical" :ID "5958")
    ("retinoic acid" "pubchem" :TYPE "simple-chemical" :ID "5282379")
    ("butyric acid" "pubchem" :TYPE "simple-chemical" :ID "264")
    ("oxidized glutathione" "pubchem" :TYPE "simple-chemical" :ID "975")
    ("thiobarbituric acid" "pubchem" :TYPE "simple-chemical" :ID "2723628")
    ("docosahexaenoic acid" "pubchem" :TYPE "simple-chemical" :ID "445580")
    ("Hydrogen peroxide" "pubchem" :TYPE "simple-chemical" :ID "784")
    ("tea polyphenol" "pubchem" :TYPE "simple-chemical" :ID "996")
    ("Retinoic acid" "pubchem" :TYPE "simple-chemical" :ID "5282379")
    ("BI-D1870" "pubchem" :TYPE "simple-chemical" :ID "25023738")
    ("inositol 1,4,5-trisphosphate" "pubchem" :TYPE "simple-chemical" :ID "439456")
    ("nicotinamide adenine dinucleotide" "pubchem" :TYPE "simple-chemical" :ID "5893")
    ("hydrogen peroxide" "pubchem" :TYPE "simple-chemical" :ID "784")
    ("(35) S" "pubchem" :TYPE "simple-chemical" :ID "61783")
    ("L-glutamine" "pubchem" :TYPE "simple-chemical" :ID "5961")
    ("penicillin G" "pubchem" :TYPE "simple-chemical" :ID "640429")
    ("1,25-dihydroxycholecalciferol" "pubchem" :TYPE "simple-chemical" :ID "5280453")
    ("vitamin C" "pubchem" :TYPE "simple-chemical" :ID "54690394")
    ("E2" "pubchem" :TYPE "simple-chemical" :ID "5757")
    ("necrostatin-1" "pubchem" :TYPE "simple-chemical" :ID "2828334")
    ("S5" "pubchem" :TYPE "simple-chemical" :ID "139341")
    ("hydroxyl radical" "pubchem" :TYPE "simple-chemical" :ID "961")
    ("6-hydroxydopamine" "pubchem" :TYPE "simple-chemical" :ID "4624")
    ("sulforhodamine B" "pubchem" :TYPE "simple-chemical" :ID "62500")
    ("prostaglandin E2" "pubchem" :TYPE "simple-chemical" :ID "5280360")
    ("ML-7" "pubchem" :TYPE "simple-chemical" :ID "4216")
    ("biochanin A" "pubchem" :TYPE "simple-chemical" :ID "5280373")
    ("lactic acid" "pubchem" :TYPE "simple-chemical" :ID "107689")
    ("C646" "pubchem" :TYPE "simple-chemical" :ID "2871948")
    ("kappa-carrageenan" "pubchem" :TYPE "simple-chemical" :ID "11966249")
    ("Cyclosporin A" "pubchem" :TYPE "simple-chemical" :ID "5284373")
    ("6-OHDA" "pubchem" :TYPE "simple-chemical" :ID "4624")
    ("Triton X-100" "pubchem" :TYPE "simple-chemical" :ID "5590")
    ("Tween 20" "pubchem" :TYPE "simple-chemical" :ID "86289077")
    ("deoxyuridine triphosphate" "pubchem" :TYPE "simple-chemical" :ID "65070")
    ("Brefeldin A" "pubchem" :TYPE "simple-chemical" :ID "5287620")
    ("NVP-AUY922" "pubchem" :TYPE "simple-chemical" :ID "10096043")))

(defparameter *pubchem-and-pfam* ;; look these up individually
  '(
    ("E3 ubiquitin ligase" "pfam" :ID "PF12483") 
    ("clamp" "pfam" :ID "PF14769") 
    ("nucleoside diphosphate kinase" "pfam" :ID "PF00334") 
    ("Galpha" "pfam" :ID "PF00503") 
    ("glycogen synthase" "pfam" :ID "PF05693") 
;;    ("S1" "pfam" :ID "PF00575") 
    ("3D" "pfam" :ID "PF06725") 
    ("IL-1" "pfam" :ID "PF00340") 
    ("il12" "pfam" :ID "PF03039") 
    ("amino acid synthesis" "pfam" :ID "PF06684") 
    ("glutathione peroxidase" "pfam" :ID "PF00255") 
    ("S4" "pfam" :ID "PF01479") 
    ("EF-hand domain" "pfam" :ID "PF08976") 
    ("EF-hand" "pfam" :ID "PF09068") 
    ("P2" "pfam" :ID "PF07194") 
    ("calcium binding" "pfam" :ID "PF11535") 
    ("nine protein" "pfam" :ID "PF05322") 
    ("BTG family" "pfam" :ID "PF07742") 

    ("MPEP" "pubchem" :ID "3025961") 
    ("DHPG" "pubchem" :ID "91528") 
    ("vitamin D" "pubchem" :ID "12895043") 
    ("1,25-dihydroxyvitamin D" "pubchem" :ID "5280453") 
    ("nitric oxide" "pubchem" :ID "145068") 
    ("ITT" "pubchem" :ID "8583") 
    ("pravastatin" "pubchem" :ID "54687") 
    ("E3" "pubchem" :ID "5756") 
    ("M2" "pubchem" :ID "25058172") 
    ("LY 294002" "pubchem" :ID "3973") 
    ("protoporphyrin-IX" "pubchem" :ID "4971") 
    ("carbon monoxide" "pubchem" :ID "281") 
    ("BMS345541" "pubchem" :ID "9813758") 
    ("M1" "pubchem" :ID "13019211") 
    ("quinolinic acid" "pubchem" :ID "1066") 
    ("N-methyl-D-aspartate" "pubchem" :ID "22880") 
    ("DBA" "pubchem" :ID "5889") 
    ("galactosamine" "pubchem" :ID "24154") 
    ("SCH772984" "pubchem" :ID "24866313") 
    ("Y-27632" "pubchem" :ID "448042") 
    ("propionate" "pubchem" :ID "104745") 
    ("morphine" "pubchem" :ID "23253564") 
    ("Adenosine monophosphate" "pubchem" :ID "6083") 
    ("sugar" "pubchem" :ID "5988") 
    ("BCG" "pubchem" :ID "448223") 
    ("parthenolide" "pubchem" :ID "7251185") 
    ("FCCP" "pubchem" :ID "3330") 
    ("I-BET151" "pubchem" :ID "52912189") 
    ("rosiglitazone" "pubchem" :ID "77999") 
    ("15d-PGJ2" "pubchem" :ID "5311211") 
    ("LGG" "pubchem" :ID "70910") 
    ("guanidine" "pubchem" :ID "3520") 
    ("Polyglutamine" "pubchem" :ID "5961") 
    ("T antigen" "pubchem" :ID "6857385") 
    ("tunicamycin" "pubchem" :ID "56927680") 
    ("HAA" "pubchem" :ID "547") 
    ("Mithramycin" "pubchem" :ID "163659") 
    ("PHA665752" "pubchem" :ID "10461815") 
    ("baicalin" "pubchem" :ID "64982") 
    ("DOPA" "pubchem" :ID "836") 
    ("DOPAquinone" "pubchem" :ID "439316") 
    ("gallic acid" "pubchem" :ID "370") 
    ("compound C" "pubchem" :ID "11524144") 
    ("palmitic acid" "pubchem" :ID "985") 
    ("malondialdehyde" "pubchem" :ID "10964") 
    ("5-hydroxyindoleacetic acid" "pubchem" :ID "9061") 
    ("5-HIAA" "pubchem" :ID "1826") 
    ("E1" "pubchem" :ID "5870") 
    ("AZD-6244" "pubchem" :ID "10127622") 
    ("TAK-165" "pubchem" :ID "644692") 
    ("HKI-272" "pubchem" :ID "50909854") 
    ("iodine" "pubchem" :ID "807") 
    ("Fe (III)" "pubchem" :ID "29936") 
    ("arsenic trioxide" "pubchem" :ID "545") 
    ("GppNHp" "pubchem" :ID "86289562") 
    ("dimethyl sulfoxide" "pubchem" :ID "679") 
    ("NU7441" "pubchem" :ID "11327430") 
    ("rosmarinic acid" "pubchem" :ID "5281792") 
    ("sodium sulfate" "pubchem" :ID "24436") 
    ("ZSTK474" "pubchem" :ID "11647372") 
    ("PD 98059" "pubchem" :ID "4713") 
    ("LBH589" "pubchem" :ID "6918837") 
    ("Atlantic" "pubchem" :ID "297") 
    ("DEHP" "pubchem" :ID "8343") 
    ("ICI" "pubchem" :ID "5318532") 
    ("oleic acid" "pubchem" :ID "445639") ))

(defparameter *all-reach-terms* (append *reach-cells* ;;*reach-proteins*
                                        *reach-terms*))
(loop for term in *all-reach-terms* do (define-reach-term term))

