
("tgD" "ONT:GENE" :id "NCIT:C116409" :name "ABCA1") 
("sopC" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027891" :name "1-stearoyl-2-oleoyl-sn-glycero-3-phosphocholine") 
("scoC" "ONT:GENE-PROTEIN" :id "HGNC:20335" :name "short coiled-coil protein") 
("sHsp" "ONT:PROTEIN-FAMILY" :id "NCIT:C136829" :name "small heat shock protein") 
("rDC" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1462" :name "radicicol") 
("polA" "ONT:GENE" :id "HGNC:9173" :name "DNA polymerase alpha 1, catalytic subunit") 
("pagA" "ONT:GENE" :id "HGNC:9352" :name "peroxiredoxin 1") 
("pFL" "ONT:GENE-PROTEIN" :id "GO:0008861" :name "formate C-acetyltransferase activity") 
("nPCR" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C141462" :name "national program of cancer registries") 
("nAAA" "ONT:GENE" :id "HGNC:736" :name "N-acylethanolamine acid amidase") 
("mMAb" "ONT:GENE" :id "HGNC:19331" :name "metabolism of cobalamin associated B") 
("lysoPC" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C006065" :name "We 201") 
("Lycorine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C015330" :name "lycorine") 
("hLFA" "ONT:CELL-LINE" :id "CVCL:2255" :name "HLF-a") 
("fNS" "ONT:CELL-LINE" :id "CVCL:6392" :name "FNS") 
("fHC" "ONT:CELL-LINE" :id "CVCL:3688" :name "FHC") 
("cspC" "ONT:CANCER" :id "NCIT:C153336" :name "castration-sensitive prostate carcinoma") 
("bSI" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:100976" :name "Bathing suit ichthyosis") 
("Avarol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C023663" :name "avarol") 
("argK" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF03308" :name "MeaB") 
("aNI" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C100229" :name "amphetaminil") 
("Zovirax" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C205" :name "acyclovir") 
("Zostavax" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77799" :name "varicella-zoster virus strain oka/Merck live antigen") 
("Zenon" "ONT:PROTEIN" :id "UP:Q5EXX3" :name "Zinc finger and BTB domain-containing protein 38") 
("Yamato" "ONT:CELL-LINE" :id "CVCL:6C44" :name "Yamato-SS") 
("Yaba" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0007225" :name "cowpox") 
("Wuchereria" "ONT:INVERTEBRATE" :id "NCIT:C122013" :name "wuchereria") 
("Whrn" "ONT:GENE" :id "HGNC:16361" :name "whirlin") 
("ViteX" "ONT:PLANT" :id "NCIT:C72243" :name "angus castus") 
("Vistide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1600" :name "cidofovir") 
("Vip" "ONT:GENE-PROTEIN" :id "HGNC:12693" :name "vasoactive intestinal peptide") 
("Vidarabine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C929" :name "vidarabine") 
("Vaxfectin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C460866" :name "vaxfectin") 
("Varicellovirus" "ONT:VIRUS" :id "NCIT:C112426" :name "varicellovirus") 
("VRs" "ONT:CHEMICAL" :id "CHEBI:140422" :name "VR nerve agent") 
("Tweety" "ONT:PROTEIN-FAMILY" :id "FA:04246" :name "tweety family") 
("Tropheryma" "ONT:BACTERIUM" :id "NCIT:C86826" :name "tropheryma") 
("Triethanolamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C009546" :name "triethanolamine") 
("Trichinella" "ONT:INVERTEBRATE" :id "NCIT:C125928" :name "trichinella") 
("Tox" "ONT:GENE-PROTEIN" :id "HGNC:18988" :name "thymocyte selection associated high mobility group box") 
("Togaviridae" "ONT:VIRUS" :id "NCIT:C77197" :name "togaviridae") 
("Tobramycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62082" :name "tobramycin") 
("TncRNA" "ONT:RNA" :id "HGNC:30815" :name "nuclear paraspeckle assembly transcript 1") 
("Thermanox" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C500874" :name "Thermanox") 
("Tbn" "ONT:GENE-PROTEIN" :id "NCIT:C30070" :name "transcription initiation factor TFIID subunit 8") 
("Taenia" "ONT:INVERTEBRATE" :id "NCIT:C125925" :name "taenia") 
("TZMbl" "ONT:CELL-LINE" :id "CVCL:B478" :name "TZM-bl") 
("TMDs" "ONT:CANCER" :id "NCIT:C27722" :name "therapy-related myelodysplastic syndrome") 
("Suid" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14322" :name "suidae") 
("Styrofoam" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C024075" :name "styrofoam") 
("Strepsils" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C526824" :name "Strepsils") 
("Stimuvax" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2195" :name "emepepimut-S") 
("Stenotrophomonas" "ONT:BACTERIUM" :id "NCIT:C86776" :name "stenotrophomonas") 
("Solexa" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "PUBCHEM:2662" :name "Celecoxib") 
("Solanum" "ONT:PLANT" :id "NCIT:C72445" :name "solanum nigrum") 
("SmaI" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:83330" :name "Proximal spinal muscular atrophy type 1") 
("Sirna" "ONT:RNA" :id "NCIT:C2191" :name "small interfering RNA") 
("Sig" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19782" :name "surveillance implementation group") 
("Sct" "ONT:GENE-PROTEIN" :id "HGNC:10607" :name "secretin") 
("Sca" "ONT:PROTEIN" :id "UP:Q10992" :name "Cysteine proteinase inhibitor A") 
("SbfI" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C061665" :name "sodium-binding benzofuran isophthalate") 
("SacI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39511" :name "cancer therapy and research center") 
("SPdb" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF05122" :name "SpdB") 
("SPase" "ONT:PROTEIN" :id "UP:A0ZZH6" :name "Sucrose phosphorylase {ECO:0000303|PubMed:14740189, ECO:0000303|PubMed:14756551, ECO:0000303|PubMed:20691225}") 
("SLOs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:818" :name "Smith-Lemli-Opitz syndrome") 
("Ruminococcus" "ONT:BACTERIUM" :id "NCIT:C86729" :name "ruminococcus") 
("Rubulavirus" "ONT:VIRUS" :id "NCIT:C14326" :name "rubulavirus") 
("Rothia" "ONT:BACTERIUM" :id "NCIT:C86727" :name "rothia") 
("Roseolovirus" "ONT:VIRUS" :id "NCIT:C112410" :name "roseolovirus") 
("Rodentia" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14270" :name "rodentia") 
("Rickettsiaceae" "ONT:BACTERIUM" :id "NCIT:C86007" :name "rickettsiaceae") 
("Rhizobiaceae" "ONT:BACTERIUM" :id "NCIT:C85959" :name "rhizobiaceae") 
("RhV" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00073" :name "rhv") 
("Req" "ONT:GENE" :id "NCIT:C157308" :name "DPF2") 
("Relenza" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47786" :name "zanamivir") 
("Ralstonia" "ONT:BACTERIUM" :id "NCIT:C86712" :name "ralstonia") 
("RRs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1507" :name "Autosomal recessive Robinow syndrome") 
("RNs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1001838" :name "renal nutcracker syndrome") 
("RBs" "ONT:GENE" :id "HGNC:27230" :name "establishment of sister chromatid cohesion N-acetyltransferase 2") 
("Pyrenees" "ONT:ORGANISM" :id "NCIT:C53766" :name "great pyrenees") 
("PxE" "ONT:CELL-LINE" :id "CVCL:Z679" :name "BCIRL/AMCY-PxE-CLG") 
("PvK" "ONT:MOLECULE" :id "CHEBI:53427" :name "poly(vinylcarbazole) macromolecule") 
("Ptprg" "ONT:GENE-PROTEIN" :id "HGNC:9671" :name "protein tyrosine phosphatase receptor type G") 
("Providencia" "ONT:BACTERIUM" :id "NCIT:C86690" :name "providencia") 
("Prot" "ONT:GENE" :id "HGNC:11054" :name "solute carrier family 6 member 7") 
("Progen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29883" :name "arsanilic acid") 
("Pregnane" "ONT:MOLECULE" :id "CHEBI:8386" :name "pregnane") 
("PoE" "ONT:CELL-LINE" :id "CVCL:EJ01" :name "POE") 
("Pneumovirinae" "ONT:VIRUS" :id "NCIT:C14308" :name "pneumovirinae") 
("PmeI" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF04043" :name "PMEI") 
("Plc" "ONT:GENE-PROTEIN" :id "FPLX:PLC" :name "PLC") 
("Pichia" "ONT:FUNGUS" :id "NCIT:C123544" :name "pichia") 
("Phlebovirus" "ONT:VIRUS" :id "NCIT:C112397" :name "phlebovirus") 
("Peramivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81611" :name "peramivir") 
("Penicillium" "ONT:FUNGUS" :id "NCIT:C123540" :name "penicillium") 
("Pdx" "ONT:PROTEIN" :id "UP:P00259" :name "Putidaredoxin") 
("Pbf" "ONT:GENE-PROTEIN" :id "NCIT:C117259" :name "ZNF395") 
("Pasteurella" "ONT:BACTERIUM" :id "NCIT:C86636" :name "pasteurella") 
("Parvoviridae" "ONT:VIRUS" :id "NCIT:C14299" :name "parvovirus") 
("Paramyxovirinae" "ONT:VIRUS" :id "NCIT:C14307" :name "paramyxovirinae") 
("Papio" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14252" :name "baboon") 
("PRTs" "ONT:GENE" :id "NCIT:C74969" :name "ARX") 
("PCNs" "ONT:PROTEIN" :id "UP:Q7SZN0" :name "Venom prothrombin activator pseutarin-C non-catalytic subunit") 
("Orion" "ONT:CELL-LINE" :id "CVCL:D997" :name "MRC-iPS-8") 
("Orbivirus" "ONT:VIRUS" :id "NCIT:C112365" :name "orbivirus") 
("Onchocerca" "ONT:INVERTEBRATE" :id "NCIT:C124282" :name "onchocerca") 
("Oca" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:55" :name "Oculocutaneous albinism") 
("ORs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C116333" :name "oculo-respiratory syndrome") 
("Nphi" "ONT:PROTEIN" :id "UP:Q98267" :name "Nucleoside triphosphatase I") 
("Nono" "ONT:GENE-PROTEIN" :id "HGNC:7871" :name "non-POU domain containing octamer binding") 
("NiV" "ONT:VIRUS" :id "NCIT:C29902" :name "nodule-inducing virus") 
("Nhe" "ONT:GENE-PROTEIN" :id "UP:P81242" :name "Non-hemolytic enterotoxin 105 kDa component") 
("Nha" "ONT:CELL-LINE" :id "EFO:0002777" :name "Normal Human Astrocytes") 
("Ngu" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C27079" :name "non-gonococcal urethritis") 
("Ncs" "ONT:PROTEIN" :id "UP:P0A3R9" :name "Neocarzinostatin") 
("Namalva" "ONT:CELL-LINE" :id "CVCL:0067" :name "Namalwa") 
("Nairovirus" "ONT:VIRUS" :id "NCIT:C112358" :name "nairovirus") 
("NaSCN" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C024553" :name "sodium thiocyanate") 
("NNs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2615" :name "Nakajo-Nishimura syndrome") 
("NCs" "ONT:PROTEIN" :id "UP:P0A3R9" :name "Neocarzinostatin") 
("Mvi" "ONT:PROTEIN" :id "UP:Q9I834" :name "Basic phospholipase A2 homolog 2") 
("MuA" "ONT:PROTEIN" :id "UP:P07636" :name "DDE-recombinase A") 
("Mpp" "ONT:CELL" :id "CO:0000837" :name "hematopoietic multipotent progenitor cell") 
("Morganella" "ONT:BACTERIUM" :id "NCIT:C86531" :name "morganella") 
("Morbillivirus" "ONT:VIRUS" :id "NCIT:C14309" :name "morbillivirus") 
("Moraxellaceae" "ONT:BACTERIUM" :id "NCIT:C85948" :name "moraxellaceae") 
("Molluscipoxvirus" "ONT:VIRUS" :id "NCIT:C112356" :name "molluscipoxvirus") 
("Moellerella" "ONT:BACTERIUM" :id "NCIT:C86520" :name "moellerella") 
("MenC" "ONT:MOLECULE" :id "CHEBI:143712" :name "N. meningitidis group C polysaccharide") 
("Mbp" "ONT:GENE-PROTEIN" :id "HGNC:6925" :name "myelin basic protein") 
("Marburgvirus" "ONT:VIRUS" :id "NCIT:C112331" :name "marburgvirus") 
("Mansonella" "ONT:INVERTEBRATE" :id "NCIT:C118942" :name "mansonella") 
("Macacus" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14231" :name "macaque") 
("Macaca" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14231" :name "macaque") 
("MScl" "ONT:PROTEIN" :id "UP:Q9JLI6" :name "Selenocysteine lyase") 
("MSAs" "ONT:PROTEIN" :id "GO:0050641" :name "6-methylsalicylic acid synthase activity") 
("MDCKs" "ONT:CELL-LINE" :id "CVCL:IQ72" :name "MDCK-S") 
("Lymphocryptovirus" "ONT:VIRUS" :id "NCIT:C14204" :name "epstein-barr virus") 
("Listeria" "ONT:BACTERIUM" :id "NCIT:C76359" :name "listeria") 
("LYMErix" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C072045" :name "OspA protein") 
("LOCs" "ONT:GENE" :id "NCIT:C137976" :name "LAMA3") 
("LCs" "ONT:CHEMICAL" :id "CHEBI:75592" :name "L-cycloserine") 
("Klee" "ONT:PROTEIN-FAMILY" :id "XFAM:PF17394" :name "KleE") 
("Kkm" "ONT:CELL-LINE" :id "CVCL:HF89" :name "KK-m") 
("Kda" "ONT:WEIGHT-UNIT" :id "UO:0000222" :name "kilodalton") 
("KVh" "ONT:MEASURE-UNIT" :id "UO:0000230" :name "kilovolt-hour") 
("Joe" "ONT:CELL-LINE" :id "CVCL:0C16" :name "JO-E") 
("Iik" "ONT:PROTEIN" :id "UP:P01080" :name "Proteinase inhibitor type-2 K") 
("IIa" "ONT:CANCER" :id "NCIT:C88135" :name "stage IIA uveal melanoma AJCC v7") 
("IIIc" "ONT:CANCER" :id "NCIT:C88139" :name "stage IIIC uveal melanoma AJCC v7") 
("IIIa" "ONT:CANCER" :id "NCIT:C88137" :name "stage IIIA uveal melanoma AJCC v7") 
("HvEM" "ONT:GENE" :id "NCIT:C97844" :name "TNFRSF14") 
("HrC" "ONT:GENE-PROTEIN" :id "HGNC:5178" :name "histidine rich calcium binding protein") 
("Hokkaido" "ONT:CELL-LINE" :id "CVCL:E702" :name "HOKKAIDO") 
("Hoi" "ONT:CHEMICAL" :id "CHEBI:29231" :name "hypoiodous acid") 
("Hfq" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF17209" :name "hfq") 
("Hes" "ONT:GENE-PROTEIN" :id "FPLX:HES" :name "HES") 
("Herceptin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1647" :name "trastuzumab") 
("HADs" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C018209" :name "4-amino-4'-hydroxylaminodiphenylsulfone") 
("Göttingen" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C77102" :name "gottingen pig") 
("Gtx" "ONT:GENE-PROTEIN" :id "UP:P43685" :name "Gilatoxin") 
("Gottingen" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C77102" :name "gottingen pig") 
("Gne" "ONT:GENE" :id "HGNC:23657" :name "glucosamine (UDP-N-acetyl)-2-epimerase/N-acetylmannosamine kinase") 
("Glycyrrhiza" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61436" :name "licorice") 
("Glrb" "ONT:GENE-PROTEIN" :id "HGNC:4329" :name "glycine receptor beta") 
("Giardia" "ONT:ORGANISM" :id "NCIT:C77213" :name "giardia") 
("Gardnerella" "ONT:BACTERIUM" :id "NCIT:C86409" :name "gardnerella") 
("Gardasil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61087" :name "quadrivalent human papillomavirus (types 6, 11, 16, 18) recombinant vaccine") 
("Gapdh" "ONT:GENE-PROTEIN" :id "HGNC:4141" :name "glyceraldehyde-3-phosphate dehydrogenase") 
("Gamendazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C530949" :name "gamendazole") 
("GAii" "ONT:PROTEIN" :id "UP:P29760" :name "Glucoamylase S2") 
("Fuzeon" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2105" :name "enfuvirtide") 
("Fusobacterium" "ONT:BACTERIUM" :id "NCIT:C76323" :name "fusobacterium") 
("Fluvirin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2643" :name "trivalent influenza vaccine") 
("Flavobacterium" "ONT:BACTERIUM" :id "NCIT:C76320" :name "flavobacterium") 
("Fenix" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C518694" :name "fenix") 
("Felidae" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14321" :name "felidae") 
("Fdx" "ONT:GENE" :id "HGNC:3638" :name "ferredoxin 1") 
("Fasciola" "ONT:INVERTEBRATE" :id "NCIT:C122021" :name "fasciola") 
("Erythrocebus" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C161036" :name "erythrocebus") 
("Ependymin" "ONT:GENE-PROTEIN" :id "UP:P32187" :name "Ependymin") 
("Enterobacter" "ONT:BACTERIUM" :id "NCIT:C76310" :name "enterobacter") 
("Entamoeba" "ONT:ORGANISM" :id "NCIT:C122048" :name "entamoeba") 
("Ehrlichia" "ONT:BACTERIUM" :id "NCIT:C122292" :name "ehrlichia") 
("Effectene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C498175" :name "Effectene") 
("Edwardsiella" "ONT:BACTERIUM" :id "NCIT:C86344" :name "edwardsiella") 
("Eda" "ONT:GENE" :id "HGNC:3157" :name "ectodysplasin A") 
("EcoR" "ONT:PROTEIN" :id "UP:P30823" :name "High affinity cationic amino acid transporter 1") 
("Echinococcus" "ONT:INVERTEBRATE" :id "NCIT:C122025" :name "echinococcus") 
("EOCa" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1177" :name "Early-onset cerebellar ataxia with retained tendon reflexes") 
("DpnI" "ONT:PROTEIN-FAMILY" :id "XFAM:PF06044" :name "DpnI") 
("Doxil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1555" :name "pegylated liposomal doxorubicin hydrochloride") 
("Dolosigranulum" "ONT:BACTERIUM" :id "NCIT:C122020" :name "dolosigranulum") 
("Dis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:94064" :name "Deafness-infertility syndrome") 
("Dilauroylphosphatidylcholine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C015153" :name "1,2-dilauroylphosphatidylcholine") 
("Diisopropyl" "ONT:MOLECULE" :id "CHEBI:141560" :name "2,3-dimethylbutane") 
("Didemnin" "ONT:CHEMICAL" :id "CHEBI:90209" :name "didemnin") 
("Dem" "ONT:CELL-LINE" :id "CVCL:E559" :name "DEM") 
("Dali" "ONT:RNA" :id "HGNC:51429" :name "DNMT1-associated long intergenic non-coding RNA") 
("DLPs" "ONT:MOLECULE" :id "CHEBI:65224" :name "1,2-dilauroyl-sn-glycero-3-phosphoserine(1-)") 
("Cynomolgus" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14232" :name "cynomolgus monkey") 
("Ctsd" "ONT:GENE-PROTEIN" :id "HGNC:2529" :name "cathepsin D") 
("CspE" "ONT:PROTEIN" :id "UP:P63237" :name "Cold shock-like protein CspE") 
("Crea" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05981" :name "CreA") 
("Cpp" "ONT:CHEMICAL" :id "CHEBI:34603" :name "CPP") 
("Combivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C109078" :name "lamivudine, zidovudine drug combination") 
("Cologne" "ONT:FISH" :id "NCIT:C79955" :name "cologne zebrafish") 
("Clint" "ONT:CELL-LINE" :id "CVCL:V933" :name "S006006") 
("Cladosporium" "ONT:FUNGUS" :id "NCIT:C122261" :name "cladosporium") 
("Citrobacter" "ONT:BACTERIUM" :id "NCIT:C76273" :name "citrobacter") 
("Chlorocebus" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C161031" :name "chlorocebus") 
("Chlamydophila" "ONT:BACTERIUM" :id "NCIT:C86254" :name "chlamydophila") 
("Chlamydiae" "ONT:BACTERIUM" :id "NCIT:C76270" :name "chlamydiae") 
("Chlamydiaceae" "ONT:BACTERIUM" :id "NCIT:C85978" :name "chlamydiaceae") 
("Chiron" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C409203" :name "chiron") 
("Chester" "ONT:CELL-LINE" :id "CVCL:D967" :name "MRC-iPS-52") 
("Canarypox" "ONT:VIRUS" :id "NCIT:C14315" :name "canarypox virus") 
("Caelyx" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1555" :name "pegylated liposomal doxorubicin hydrochloride") 
("CEMss" "ONT:CELL-LINE" :id "CVCL:J318" :name "CEM-SS") 
("Bunyaviridae" "ONT:VIRUS" :id "NCIT:C112028" :name "bunyaviridae") 
("Bsa" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39333" :name "board of scientific advisors NCI") 
("Brucellaceae" "ONT:BACTERIUM" :id "NCIT:C85919" :name "brucellaceae") 
("Bronopol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77031" :name "bronopol") 
("Brevibacillus" "ONT:BACTERIUM" :id "NCIT:C86207" :name "brevibacillus") 
("Brant" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C099521" :name "2-aminobenzoic acid 2-(bromoacetyl)hydrazide") 
("Blebbistatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C472645" :name "blebbistatin") 
("Biopharmaceuticals" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C307" :name "biological agent") 
("BglII" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF09195" :name "endonuc-BglII") 
("Bevasiranib" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C554088" :name "bevasiranib") 
("Betamethasone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C303" :name "betamethasone") 
("Bartonellaceae" "ONT:BACTERIUM" :id "NCIT:C85904" :name "bartonellaceae") 
("Bartonella" "ONT:BACTERIUM" :id "NCIT:C86184" :name "bartonella") 
("Bacteroidetes" "ONT:BACTERIUM" :id "NCIT:C76203" :name "bacteroidetes") 
("BGas" "ONT:RNA" :id "HGNC:40144" :name "CFTR antisense RNA 1") 
("Avastin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2039" :name "bevacizumab") 
("Augmentin" "ONT:CHEMICAL" :id "CHEBI:2677" :name "Augmentin") 
("Atipamezole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72921" :name "atipamezole") 
("Aqua" "ONT:MOLECULE" :id "CHEBI:15377" :name "water") 
("Antisedan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72921" :name "atipamezole") 
("Andrographis" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61637" :name "andrographolide") 
("AmiGO" "ONT:GENE-PROTEIN" :id "FA:01834" :name "AMIGO family") 
("Alameda" "ONT:CELL-LINE" :id "CVCL:D946" :name "MRC-iPS-33") 
("Ahx" "ONT:GENE" :id "NCIT:C75865" :name "NR0B1") 
("Aeromonas" "ONT:BACTERIUM" :id "NCIT:C86124" :name "aeromonas") 
("AdoHcy" "ONT:CHEMICAL" :id "CHEBI:16680" :name "S-adenosyl-L-homocysteine") 
("Adenoviridae" "ONT:VIRUS" :id "NCIT:C14179" :name "adenoviridae") 
("Actinomyces" "ONT:BACTERIUM" :id "NCIT:C76201" :name "actinomyces") 
("Actb" "ONT:GENE-PROTEIN" :id "HGNC:132" :name "actin beta") 
("Acidovorax" "ONT:BACTERIUM" :id "NCIT:C86085" :name "acidovorax") 
("Achromobacter" "ONT:BACTERIUM" :id "NCIT:C86079" :name "achromobacter") 
("Abiotrophia" "ONT:BACTERIUM" :id "NCIT:C86077" :name "abiotrophia") 
("AONs" "ONT:PROTEIN" :id "UP:Q8GW43" :name "8-amino-7-oxononanoate synthase") 
("AATf" "ONT:GENE-PROTEIN" :id "HGNC:19235" :name "apoptosis antagonizing transcription factor") 
("zolazepam" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C84252" :name "zolazepam") 
("zanamivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47786" :name "zanamivir") 
("xls" "ONT:GENE" :id "HGNC:27849" :name "PAXX non-homologous end joining factor") 
("woodchuck" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C124252" :name "eastern woodchuck") 
("wiskostatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C489942" :name "wiskostatin") 
("niaid" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19753" :name "national institute of allergy and infectious disease") 
("epg" "ONT:CELL-LINE" :id "CVCL:R841" :name "EPG") 
("voriconazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1707" :name "voriconazole") 
("volvulus" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1000989" :name "intestinal volvulus") 
("vitamine" "ONT:CHEMICAL" :id "CHEBI:33234" :name "vitamin E") 
("viroid" "ONT:VIRUS" :id "NCIT:C95945" :name "viroid") 
("virgo" "ONT:CELL-LINE" :id "CVCL:E027" :name "PAE-iPS-6") 
("viii" "ONT:GENE" :id "HGNC:2294" :name "cytochrome c oxidase subunit 8A") 
("vidarabine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C929" :name "vidarabine") 
("victorin" "ONT:CHEMICAL" :id "CHEBI:73154" :name "victorin C") 
("vaginitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26911" :name "vaginitis") 
("uropod" "ONT:CELL-PART" :id "GO:0001931" :name "uropod") 
("urethritis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003878" :name "urethritis") 
("unk" "ONT:GENE" :id "HGNC:29369" :name "unk zinc finger") 
("tularemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C85208" :name "tularemia") 
("tuberculin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C85502" :name "tuberculin") 
("tryptophane" "ONT:CHEMICAL" :id "CHEBI:27897" :name "tryptophan") 
("trityl" "ONT:MOLECULE" :id "CHEBI:52341" :name "trityl group") 
("tripeptide" "ONT:CHEMICAL" :id "CHEBI:47923" :name "tripeptide") 
("trinitrophenol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C80865" :name "picric acid") 
("tricaine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C84658" :name "tricaine") 
("trans" "ONT:PROTEIN-FAMILY" :id "XFAM:PF06986" :name "TraN") 
("tracheobronchitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C122784" :name "tracheobronchitis") 
("tracheitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C78643" :name "tracheitis") 
("tonsillopharyngitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C128436" :name "tonsillopharyngitis") 
("tomatine" "ONT:CHEMICAL" :id "CHEBI:9630" :name "tomatine") 
("tof" "ONT:GENE" :id "HGNC:13506" :name "FEZ family zinc finger 2") 
("tmc" "ONT:GENE-PROTEIN" :id "FA:04030" :name "TMC family") 
("tiletamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C84211" :name "tiletamine") 
("thiram" "ONT:MOLECULE" :id "CHEBI:9495" :name "thiram") 
("thiosulfate" "ONT:MOLECULE" :id "CHEBI:26977" :name "thiosulfate") 
("thionin" "ONT:PROTEIN" :id "UP:Q9SBK8" :name "Thionin") 
("thioflavine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C009462" :name "thioflavin T") 
("thioether" "ONT:MOLECULE" :id "CHEBI:16385" :name "organic sulfide") 
("tga" "ONT:GENE" :id "NCIT:C75412" :name "TBX1") 
("tetrathionate" "ONT:MOLECULE" :id "CHEBI:15226" :name "tetrathionate(2-)") 
("tetrapeptide" "ONT:CHEMICAL" :id "CHEBI:48030" :name "tetrapeptide") 
("tetrahydrofuran" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C018674" :name "tetrahydrofuran") 
("tetracyclines" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C865" :name "tetracycline") 
("tenofovir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29490" :name "tenofovir") 
("tellurite" "ONT:MOLECULE" :id "CHEBI:30477" :name "tellurite") 
("tele" "ONT:GENE" :id "HGNC:11610" :name "titin-cap") 
("telavancin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C87603" :name "telavancin") 
("tazobactam" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62079" :name "tazobactam") 
("taxon" "ONT:ORGANISM" :id "NCIT:C14250" :name "organism") 
("synovitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C50766" :name "synovitis") 
("sulphite" "ONT:MOLECULE" :id "CHEBI:17359" :name "sulfite") 
("sulfobetaine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C483727" :name "sulfobetaine") 
("sulfisoxazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47740" :name "sulfisoxazole") 
("sterol" "ONT:MOLECULE" :id "CHEBI:15889" :name "sterol") 
("std" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C3365" :name "sexually transmitted disorder") 
("squalane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C019556" :name "squalane") 
("spongouridine" "ONT:CHEMICAL" :id "CHEBI:68346" :name "arauridine") 
("spongothymidine" "ONT:MOLECULE" :id "CHEBI:80699" :name "Spongothymidine") 
("spectinomycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61951" :name "spectinomycin") 
("solexa" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "PUBCHEM:2662" :name "Celecoxib") 
("sinefungin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73041" :name "sinefungin") 
("schizont" "ONT:INTERNAL-BODY-PART" :id "BTO:0001002" :name "schizont") 
("sars" "ONT:GENE" :id "NCIT:C127843" :name "NR1I2") 
("salpingitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26880" :name "salpingitis") 
("sakuranetin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C099724" :name "sakuranetin") 
("saimiri" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C160934" :name "saimiri") 
("rimantadine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61927" :name "rimantadine") 
("rifampin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C811" :name "rifampin") 
("rhinitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34986" :name "rhinitis") 
("pyrimidines" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C030986" :name "pyrimidine") 
("pullulan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C009109" :name "pullulan") 
("psu" "ONT:PROTEIN-FAMILY" :id "XFAM:PF07455" :name "psu") 
("pseudolycorine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027861" :name "pseudolycorine") 
("proteoliposomes" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C020485" :name "proteoliposomes") 
("prix" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF18689" :name "PriX") 
("preset" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05033" :name "pre-SET") 
("pregnane" "ONT:MOLECULE" :id "CHEBI:8386" :name "pregnane") 
("posaconazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61500" :name "posaconazole") 
("pos" "ONT:PROTEIN" :id "UP:Q8VCZ9" :name "Hydroxyproline dehydrogenase") 
("popg" "ONT:CHEMICAL" :id "CHEBI:34080" :name "1-palmitoyl-2-oleoyl-sn-glycero-3-phosphoglycerol") 
("polyvinylamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C534904" :name "polyvinylamine") 
("polypyrrole" "ONT:MOLECULE" :id "CHEBI:38077" :name "polypyrrole") 
("polypropyleneimine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C443641" :name "poly(propyleneimine)") 
("polyoxymethylene" "ONT:MOLECULE" :id "CHEBI:53421" :name "poly(oxymethylene) macromolecule") 
("polylysine" "ONT:MOLECULE" :id "CHEBI:53411" :name "poly(lysine) macromolecule") 
("polyglycolide" "ONT:MOLECULE" :id "CHEBI:53492" :name "poly(glycolic acid)") 
("polyamidoamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C531249" :name "Poly(amidoamine)") 
("polonium" "ONT:MOLECULE" :id "CHEBI:33313" :name "polonium atom") 
("pmf" "ONT:GENE" :id "HGNC:9337" :name "proline rich protein BstNI subfamily 1 (gene/pseudogene)") 
("plastid" "ONT:CELL-PART" :id "UP:SL-0209" :name "Plastid") 
("pika" "ONT:GENE" :id "HGNC:26810" :name "EGF like, fibronectin type III and laminin G domains") 
("picolitre" "ONT:VOLUME-UNIT" :id "UO:0000103" :name "picoliter") 
("phytosterols" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28178" :name "phytosterol") 
("phytosterol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28178" :name "phytosterol") 
("phosphatidylinositol" "ONT:MOLECULE" :id "CHEBI:28874" :name "phosphatidylinositol") 
("phosphatidylglycerol" "ONT:CHEMICAL" :id "CHEBI:17517" :name "phosphatidylglycerol") 
("phosphatidyl" "ONT:MOLECULE" :id "CHEBI:26025" :name "phosphatidyl group") 
("phenylthio" "ONT:MOLECULE" :id "CHEBI:48499" :name "phenylsulfanyl group") 
("pheno" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C739" :name "phenobarbital") 
("phaseolotoxin" "ONT:CHEMICAL" :id "CHEBI:8047" :name "phaseolotoxin") 
("phagosome" "ONT:CELL-PART" :id "UP:SL-0206" :name "Phagosome") 
("pgm" "ONT:GENE-PROTEIN" :id "UP:Q9SCY0" :name "Phosphoglucomutase, chloroplastic") 
("pfma" "ONT:PROTEIN" :id "UP:Q8IDR3" :name "Myosin-A") 
("petechiae" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "HP:0000979" :name "Purpura") 
("peridinin" "ONT:MOLECULE" :id "CHEBI:44882" :name "peridinin") 
("pericarditis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34915" :name "pericarditis") 
("perfluoropropane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C042852" :name "perflutren") 
("peramivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81611" :name "peramivir") 
("pepo" "ONT:PROTEIN" :id "UP:Q06902" :name "Aspergillopepsin-1") 
("pentylenetetrazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81054" :name "pentetrazol") 
("penem" "ONT:CHEMICAL" :id "CHEBI:35994" :name "penem") 
("pci" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF01399" :name "PCI") 
("paradimethylaminobenzaldehyde" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C510241" :name "p-dimethylaminobenzaldehyde") 
("oxytetracycline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61872" :name "oxytetracycline") 
("oxacillin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62063" :name "oxacillin") 
("osteomyelitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003102" :name "osteomyelitis") 
("org" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19711" :name "professional organization or group") 
("ora" "ONT:PROTEIN" :id "UP:P16405" :name "Octapeptide-repeat antigen") 
("optochin" "ONT:CHEMICAL" :id "CHEBI:86455" :name "optochin") 
("oophoritis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1001071" :name "oophoritis") 
("oooh" "ONT:MOLECULE" :id "CHEBI:29791" :name "trioxidanyl group") 
("omphalitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C116008" :name "omphalitis") 
("oligopeptide" "ONT:CHEMICAL" :id "CHEBI:25676" :name "oligopeptide") 
("nucleoside" "ONT:MOLECULE" :id "CHEBI:33838" :name "nucleoside") 
("nphi" "ONT:PROTEIN" :id "UP:Q98267" :name "Nucleoside triphosphatase I") 
("nsf" "ONT:GENE" :id "HGNC:8016" :name "N-ethylmaleimide sensitive factor, vesicle fusing ATPase") 
("nojirimycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C013626" :name "nojirimycin") 
("nlm" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C82620" :name "national library of medicine") 
("niob" "ONT:MOLECULE" :id "CHEBI:33344" :name "niobium atom") 
("nido" "ONT:PROTEIN-FAMILY" :id "XFAM:PF06119" :name "NIDO") 
("nhs" "ONT:GENE-PROTEIN" :id "HGNC:7820" :name "NHS actin remodeling regulator") 
("neuronophagia" "ONT:BIOLOGICAL-PROCESS" :id "NCIT:C120901" :name "neuronophagia") 
("neokauluamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C436388" :name "neo-kauluamine") 
("ncbi" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C45799" :name "national center for biotechnology information") 
("nanosecond" "ONT:TIME-UNIT" :id "UO:0000150" :name "nanosecond") 
("nanolitre" "ONT:VOLUME-UNIT" :id "UO:0000102" :name "nanoliter") 
("nadroparin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61320" :name "nadroparin calcium") 
("myositis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000783" :name "myositis") 
("msu" "ONT:GENE" :id "HGNC:986" :name "branched chain keto acid dehydrogenase E1 subunit alpha") 
("motavizumab" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C88584" :name "motavizumab") 
("morpholine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C037574" :name "morpholine") 
("morbillivirus" "ONT:VIRUS" :id "NCIT:C14309" :name "morbillivirus") 
("monosialotetrahexosylganglioside" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C107389" :name "monosialotetrahexosylganglioside") 
("monobactam" "ONT:CHEMICAL" :id "CHEBI:50695" :name "monobactam") 
("milli" "ONT:WEIGHT-UNIT" :id "UO:0010009" :name "milli") 
("microspinosamide" "ONT:CHEMICAL" :id "CHEBI:66388" :name "microspinosamide") 
("microsecond" "ONT:TIME-UNIT" :id "UO:0000029" :name "microsecond") 
("microparticle" "ONT:CELL-PART" :id "UP:SL-0499" :name "Extracellular vesicle") 
("microlitre" "ONT:VOLUME-UNIT" :id "UO:0000101" :name "microliter") 
("methylammonium" "ONT:CHEMICAL" :id "CHEBI:59338" :name "methylammonium") 
("methoxyflurane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C75098" :name "methoxyflurane") 
("metacestode" "ONT:INTERNAL-BODY-PART" :id "BTO:0000859" :name "metacestode") 
("metacaine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:81494" :name "tricaine") 
("mefloquine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61827" :name "mefloquine") 
("mastitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C53662" :name "mastitis") 
("lymphadenitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "HP:0002840" :name "lymphadenitis") 
("lycorine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C015330" :name "lycorine") 
("lycorane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C412290" :name "lycorane") 
("lumefantrine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81541" :name "lumefantrine") 
("lipofectin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C020888" :name "1,2-dielaidoylphosphatidylethanolamine") 
("lignocaine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C614" :name "lidocaine") 
("leuprorelin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62042" :name "leuprolide") 
("lentivirinae" "ONT:VIRUS" :id "NCIT:C14290" :name "lentivirus") 
("lanosterol" "ONT:CHEMICAL" :id "CHEBI:16521" :name "lanosterol") 
("lactide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C091880" :name "dilactide") 
("lac" "ONT:PROTEIN" :id "NCIT:C70620" :name "lupus anticoagulant antibody") 
("kvh" "ONT:MEASURE-UNIT" :id "UO:0000230" :name "kilovolt-hour") 
("krc" "ONT:GENE" :id "HGNC:13561" :name "HIVEP zinc finger 3") 
("kma" "ONT:CELL-LINE" :id "CVCL:6413" :name "KMA") 
("jma" "ONT:CELL-LINE" :id "CVCL:HA40" :name "JMA") 
("isoprinosine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C601" :name "inosine pranobex") 
("isoprenoid" "ONT:MOLECULE" :id "CHEBI:24913" :name "isoprenoid") 
("isoaaptamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C417553" :name "isoaaptamine") 
("influenzavirus" "ONT:VIRUS" :id "NCIT:C53469" :name "influenzavirus") 
("indotricarbocyanine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C501744" :name "indotricarbocyanine") 
("indoles" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C030374" :name "indole") 
("inca" "ONT:GENE-PROTEIN" :id "FA:01853" :name "INCA family") 
("immunomodulators" "ONT:CHEMICAL" :id "CHEBI:50846" :name "immunomodulator") 
("immunochromatography" "ONT:PROCEDURE" :id "NCIT:C154792" :name "immunochromatography") 
("immunoadjuvant" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C210" :name "immunoadjuvant") 
("imipenem" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C570" :name "imipenem") 
("ifnar" "ONT:GENE" :id "NCIT:C51352" :name "IFNAR1") 
("ictacalcin" "ONT:PROTEIN" :id "UP:Q91061" :name "Ictacalcin") 
("hyperglycemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "HP:0003074" :name "Hyperglycemia") 
("hydroxylapatite" "ONT:CHEMICAL" :id "CHEBI:52255" :name "hydroxylapatite") 
("hsp" "ONT:CELL-LINE" :id "CVCL:5291" :name "HS-P") 
("homoproline" "ONT:CHEMICAL" :id "CHEBI:17964" :name "pipecolic acid") 
("hominid" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C79740" :name "hominidae") 
("hemisuccinate" "ONT:CHEMICAL" :id "CHEBI:138979" :name "hemisuccinate") 
("gravid" "ONT:INTERNAL-BODY-PART" :id "BTO:0004733" :name "gravid adult") 
("gne" "ONT:GENE" :id "HGNC:23657" :name "glucosamine (UDP-N-acetyl)-2-epimerase/N-acetylmannosamine kinase") 
("glyphosate" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C010974" :name "glyphosate") 
("glossitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1000951" :name "glossitis") 
("ggd" "ONT:CELL-LINE" :id "CVCL:6G51" :name "GGD") 
("gentamycin" "ONT:CHEMICAL" :id "CHEBI:17833" :name "gentamycin") 
("gapdh" "ONT:GENE-PROTEIN" :id "HGNC:4141" :name "glyceraldehyde-3-phosphate dehydrogenase") 
("fungizone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62201" :name "amphotericin B deoxycholate") 
("fructosamine" "ONT:MOLECULE" :id "CHEBI:24103" :name "fructosamine") 
("fomivirsen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C091346" :name "fomivirsen") 
("fluoresceine" "ONT:CHEMICAL" :id "CHEBI:31624" :name "fluorescein") 
("flunixin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65721" :name "flunixin") 
("flavonolignan" "ONT:MOLECULE" :id "CHEBI:72709" :name "flavonolignan") 
("fibritin" "ONT:PROTEIN" :id "UP:P10104" :name "Fibritin") 
("fetuin" "ONT:PROTEIN-FAMILY" :id "FA:01341" :name "fetuin family") 
("fenpiclonil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C437165" :name "fenpiclonil") 
("fenbendazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C75218" :name "fenbendazole") 
("exanthem" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1000697" :name "exanthem") 
("ethylenimine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1009" :name "ethyleneimine") 
("etc" "ONT:PROTEIN" :id "UP:P32940" :name "Endothelin-3 receptor") 
("esfenvalerate" "ONT:CHEMICAL" :id "CHEBI:39346" :name "esfenvalerate") 
("epistaxis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003895" :name "epistaxis") 
("enrofloxacin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72660" :name "enrofloxacin") 
("enfuvirtide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2105" :name "enfuvirtide") 
("emtricitabine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47509" :name "emtricitabine") 
("ectoparasiticide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:38956" :name "ectoparasiticide") 
("echinacea" "ONT:PLANT" :id "NCIT:C54160" :name "echinacea") 
("eae" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0001066" :name "experimental autoimmune encephalomyelitis") 
("dynasore" "ONT:CHEMICAL" :id "CHEBI:132754" :name "dynasore") 
("drimane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C437376" :name "drimane") 
("dpt" "ONT:GENE" :id "HGNC:3011" :name "dermatopontin") 
("dpm" "ONT:CELL-LINE" :id "CVCL:0P21" :name "DPM") 
("dpd" "ONT:GENE-PROTEIN" :id "UP:Q12882" :name "Dihydropyrimidine dehydrogenase [NADP(+)]") 
("doxycyclin" "ONT:MOLECULE" :id "CHEBI:50845" :name "doxycycline") 
("dmax" "ONT:PROTEIN" :id "UP:P91664" :name "Protein max") 
("dioleoylphosphatidylethanolamine" "ONT:MOLECULE" :id "CHEBI:60285" :name "dioleoyl phosphatidylethanolamine") 
("dimethyldichlorosilane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C040863" :name "dichlorodimethylsilane") 
("dimethylallyl" "ONT:MOLECULE" :id "CHEBI:26248" :name "prenyl group") 
("diethylcarbamazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65378" :name "diethylcarbamazine") 
("diethanolamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C020283" :name "diethanolamine") 
("dicysteine" "ONT:CHEMICAL" :id "CHEBI:17376" :name "cystine") 
("diclazuril" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76418" :name "diclazuril") 
("dichloromethylene" "ONT:MOLECULE" :id "CHEBI:51370" :name "dichlorocarbene") 
("diacetylchitobiose" "ONT:CHEMICAL" :id "CHEBI:28681" :name "N,N'-diacetylchitobiose") 
("dfr" "ONT:PROTEIN" :id "UP:P51102" :name "Dihydroflavonol 4-reductase") 
("detox" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1799" :name "detox") 
("deoxyribonucleotide" "ONT:MOLECULE" :id "CHEBI:4431" :name "deoxyribonucleotide") 
("deoxynucleoside" "ONT:MOLECULE" :id "CHEBI:18274" :name "2'-deoxyribonucleoside") 
("deoxyadenosine" "ONT:CHEMICAL" :id "CHEBI:16335" :name "adenosine") 
("decanoyl" "ONT:MOLECULE" :id "CHEBI:23574" :name "decanoyl group") 
("dbb" "ONT:CELL-LINE" :id "CVCL:E544" :name "DBB") 
("cystein" "ONT:CHEMICAL" :id "CHEBI:15356" :name "cysteine") 
("cynomolgus" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14232" :name "cynomolgus monkey") 
("cycline" "ONT:PROTEIN-FAMILY" :id "FPLX:Cyclin_E" :name "Cyclin-E") 
("cotrimoxazole" "ONT:CHEMICAL" :id "CHEBI:3770" :name "co-trimoxazole") 
("colistin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65350" :name "colistin") 
("cnb" "ONT:GENE" :id "NCIT:C52097" :name "PPP3R1") 
("clorgyline" "ONT:CHEMICAL" :id "CHEBI:3763" :name "clorgyline") 
("clindamycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C377" :name "clindamycin") 
("clevudine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C95210" :name "clevudine") 
("clavulanate" "ONT:MOLECULE" :id "CHEBI:487869" :name "clavulanate") 
("cilastatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61679" :name "cilastatin") 
("chorea" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0004152" :name "chorea") 
("chondramide" "ONT:CHEMICAL" :id "CHEBI:84384" :name "chondramide") 
("cholecystitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34465" :name "cholecystitis") 
("chlorophenol" "ONT:MOLECULE" :id "CHEBI:23150" :name "chlorophenol") 
("chloromycetin" "ONT:CHEMICAL" :id "CHEBI:17698" :name "chloramphenicol") 
("chlorhexidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C364" :name "chlorhexidine") 
("chlamydiae" "ONT:BACTERIUM" :id "NCIT:C76270" :name "chlamydiae") 
;("chemokines" "ONT:GENE-PROTEIN" :id "FPLX:Chemokine" :name "Chemokine") 
("chemokine" "ONT:GENE-PROTEIN" :id "FPLX:Chemokine" :name "Chemokine") 
("chancre" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1001247" :name "chancre") 
("cfu" "ONT:MEASURE-UNIT" :id "UO:0000210" :name "colony forming unit") 
("cephradine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47441" :name "cephradine") 
("cefuroxime" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61669" :name "cefuroxime") 
("ceftobiprole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65306" :name "ceftobiprole") 
("ceftiofur" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81036" :name "ceftiofur") 
("ceftazidime" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C66868" :name "ceftazidime") 
("cefixime" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1100" :name "cefixime") 
("cefepime" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65294" :name "cefepime") 
("cefadroxil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28912" :name "cefadroxil") 
("cdki" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2185" :name "cyclin-dependent kinase inhibitor") 
("cco" "ONT:CELL-LINE" :id "CVCL:4142" :name "CCO") 
("cbil" "ONT:PROTEIN" :id "GO:0043781" :name "cobalt-factor II C20-methyltransferase activity") 
("caveolae" "ONT:CELL-PART" :id "UP:SL-0035" :name "Caveola") 
("carboxyfluorescein" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C024098" :name "6-carboxyfluorescein") 
("carbofuran" "ONT:CHEMICAL" :id "CHEBI:34611" :name "carbofuran") 
("caprylyl" "ONT:MOLECULE" :id "CHEBI:25650" :name "octanoyl group") 
("canid" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14331" :name "canidae") 
("candidemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1001282" :name "Candidemia") 
("cand" "ONT:PROTEIN-FAMILY" :id "FA:00453" :name "CAND family") 
("canarypox" "ONT:VIRUS" :id "NCIT:C14315" :name "canarypox virus") 
("california" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C76364" :name "california rabbit") 
("caa" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0006790" :name "cerebral amyloid angiopathy") 
("bunyaviridae" "ONT:VIRUS" :id "NCIT:C112028" :name "bunyaviridae") 
("bronchopneumonia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26710" :name "bronchopneumonia") 
("bromoindole" "ONT:MOLECULE" :id "CHEBI:52514" :name "bromoindole") 
("bromelain" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28134" :name "bromelains") 
("brome" "ONT:CHEMICAL" :id "CHEBI:22927" :name "bromine atom") 
("bradyzoite" "ONT:INTERNAL-BODY-PART" :id "BTO:0002342" :name "bradyzoite") 
("bpq" "ONT:CHEMICAL" :id "CHEBI:87752" :name "benzo[a]pyrene-7,8-dione") 
("bornavirus" "ONT:PROTEIN-FAMILY" :id "XFAM:PF06208" :name "BDV G") 
("biopharmaceuticals" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C307" :name "biological agent") 
("benzathine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C010044" :name "benzathine") 
("benzamil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C013407" :name "benzamil") 
("benzamidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C032157" :name "benzamidine") 
("bcm" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1154" :name "carbendazim") 
("bacitracin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C295" :name "bacitracin") 
("avertin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C062527" :name "tribromoethanol") 
("avarone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C046374" :name "avarone") 
("avarol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C023663" :name "avarol") 
("atc" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2354" :name "timonacic") 
("arteritis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34399" :name "arteritis") 
("artemether" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73001" :name "artemether") 
("arabinoside" "ONT:MOLECULE" :id "CHEBI:22601" :name "arabinoside") 
("antitussives" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:51177" :name "antitussive") 
("antisedan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72921" :name "atipamezole") 
("antimalarials" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:38068" :name "antimalarial") 
("antidepressants" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:35469" :name "antidepressant") 
("anthrone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C004522" :name "anthrone") 
("andrographolide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61637" :name "andrographolide") 
("amoxicillin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C237" :name "amoxicillin") 
("ammonio" "ONT:MOLECULE" :id "CHEBI:48284" :name "azaniumyl group") 
("aminopropyltriethoxysilane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C477625" :name "amino-propyl-triethoxysilane") 
("amantidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61632" :name "amantadine") 
("aldicarb" "ONT:CHEMICAL" :id "CHEBI:2555" :name "aldicarb") 
("albuterol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C215" :name "albuterol") 
("adamantanes" "ONT:MOLECULE" :id "CHEBI:40519" :name "adamantane") 
("adamantane" "ONT:MOLECULE" :id "CHEBI:40519" :name "adamantane") 
("aciclovir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C205" :name "acyclovir") 
("acg" "ONT:GENE-PROTEIN" :id "HGNC:23483" :name "dedicator of cytokinesis 11") 
("acepromazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77568" :name "acepromazine") 
("VLF" "ONT:PROTEIN" :id "UP:P83255" :name "Snake venom metalloproteinase fibrolase") 
("YSL" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77856" :name "tyroserleutide") 
("XDR" "ONT:BIOLOGICAL-PROCESS" :id "NCIT:C102633" :name "extensively drug resistance process") 
("WTA" "ONT:CELL-LINE" :id "CVCL:RN16" :name "UTA.00112.hFF") 
("WRW" "ONT:PROTEIN-FAMILY" :id "XFAM:PF10206" :name "WRW") 
("WLW" "ONT:CELL-LINE" :id "CVCL:UJ51" :name "NF-HFO-3") 
("WLL" "ONT:CHEMICAL" :id "CHEBI:91269" :name "Trp-Leu-Leu") 
("WIL" "ONT:CELL-LINE" :id "CVCL:1645" :name "QIMR-WIL") 
("WHV" "ONT:VIRUS" :id "NCIT:C124253" :name "woodchuck hepatitis virus") 
("VELVET" "ONT:PROTEIN-FAMILY" :id "XFAM:PF11754" :name "velvet") 
("VDBP" "ONT:GENE" :id "NCIT:C52279" :name "GC") 
("USDA" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C68708" :name "united states department of agriculture") 
("UCA" "ONT:CELL-LINE" :id "CVCL:1M77" :name "UCA") 
("UAA" "ONT:PROTEIN-FAMILY" :id "XFAM:PF08449" :name "UAA") 
("TTT" "ONT:CHEMICAL" :id "CHEBI:144905" :name "Thr-Thr-Thr") 
("TRICOM" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2192" :name "TRICOM") 
("TGT" "ONT:GENE-PROTEIN" :id "XFAM:PF01702" :name "TGT") 
("TEPA" "ONT:CHEMICAL" :id "CHEBI:49798" :name "tetraethylenepentamine") 
("TCAD" "ONT:PROTEIN" :id "NCIT:C21022" :name "cadherin-13") 
("TBEV" "ONT:VIRUS" :id "NCIT:C112422" :name "tick-borne encephalitis virus") 
("SWT" "ONT:CELL-LINE" :id "CVCL:S951" :name "SWT") 
("SUS" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C160990" :name "sus") 
("SSPE" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C85171" :name "subacute sclerosing panencephalitis") 
("SRD" "ONT:PROTEIN-FAMILY" :id "XFAM:PF10317" :name "7TM GPCR Srd") 
("SNHL" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26739" :name "sensorineural hearing loss") 
("SMJ" "ONT:CELL-LINE" :id "CVCL:E827" :name "SHJO") 
("SJO" "ONT:CELL-LINE" :id "CVCL:0T73" :name "SJO") 
("SECA" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF01043" :name "SecA PP bind") 
("SCID" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:183660" :name "Severe combined immunodeficiency") 
("SCI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C105626" :name "stanford cancer institute") 
("RXN" "ONT:PROTEIN" :id "UP:Q9MYK8" :name "Prorelaxin") 
("RVF" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C128419" :name "rift valley fever") 
("RODS" "ONT:GENE-PROTEIN" :id "UP:P50748" :name "Kinetochore-associated protein 1") 
("ROCT" "ONT:PROTEIN" :id "UP:P68747" :name "Ornithine carbamoyltransferase 2, anabolic") 
("RMC" "ONT:CELL-LINE" :id "CVCL:0506" :name "RMC") 
("RHV" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00073" :name "rhv") 
("RDH" "ONT:PROTEIN" :id "UP:P00335" :name "Ribitol 2-dehydrogenase") 
("RDF" "ONT:PROTEIN" :id "UP:Q9T216" :name "Recombination directionality factor") 
("PVB" "ONT:MOLECULE" :id "CHEBI:53285" :name "poly(vinyl benzoate)") 
("PROTEC" "ONT:CHEMICAL" :id "CHEBI:143527" :name "(R)-lisofylline") 
("PROSTVAC" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C38681" :name "rilimogene galvacirepvec") 
("PRNT" "ONT:RNA" :id "HGNC:18046" :name "prion locus lncRNA, testis expressed") 
("PPQ" "ONT:MEASURE-UNIT" :id "UO:0000172" :name "parts per quadrillion") 
("PMED" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:352596" :name "Progressive myoclonic epilepsy with dystonia") 
("PLH" "ONT:CELL-LINE" :id "CVCL:E810" :name "PLH") 
("PKU" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:716" :name "Phenylketonuria") 
("PISD" "ONT:GENE" :id "HGNC:8999" :name "phosphatidylserine decarboxylase") 
("PFA" "ONT:MOLECULE" :id "CHEBI:53371" :name "omega-hydroxypoly(furan-2,5-diylmethylene) macromolecule") 
("PEEP" "ONT:MOLECULE" :id "CHEBI:53359" :name "poly(ethyl ethoxyethylene phosphate) macromolecule") 
("PDV" "ONT:CELL-LINE" :id "CVCL:5858" :name "PDV") 
("PCT" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:101330" :name "Porphyria cutanea tarda") 
("PCMC" "ONT:CELL-PART" :id "GO:1990075" :name "periciliary membrane compartment") 
("PCCF" "ONT:GENE" :id "NCIT:C91333" :name "F5") 
("PARV" "ONT:PROTEIN-FAMILY" :id "FPLX:PARV" :name "PARV") 
("ORFV" "ONT:PROTEIN" :id "UP:P17958" :name "Uncharacterized 25.6 kDa protein in aldolase locus") 
("OPV" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C96401" :name "oral polio vaccine") 
("OPC" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C131333" :name "oligomeric procyanidin complex") 
("NTI" "ONT:GENE" :id "NCIT:C54312" :name "MGP") 
("NRS" "ONT:GENE" :id "HGNC:30621" :name "sphingolipid transporter 1 (putative)") 
("NPI" "ONT:GENE-PROTEIN" :id "HGNC:218" :name "ADAM metallopeptidase with thrombospondin type 1 motif 2") 
("NPHII" "ONT:PROTEIN-FAMILY" :id "XFAM:PF12011" :name "NPH-II") 
("NIV" "ONT:VIRUS" :id "NCIT:C29902" :name "nodule-inducing virus") 
("NIAID" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19753" :name "national institute of allergy and infectious disease") 
("NHLBI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C82613" :name "national heart, lung, and blood institute") 
("NFP" "ONT:PROTEIN" :id "UP:P09142" :name "Non-fluorescent flavoprotein") 
("NDP" "ONT:GENE" :id "HGNC:7678" :name "norrin cystine knot growth factor NDP") 
("NCR" "ONT:PROTEIN-FAMILY" :id "NCIT:C129776" :name "natural cytotoxicity receptor family") 
("NCI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19202" :name "national cancer institute") 
("NCBI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C45799" :name "national center for biotechnology information") 
("NAAT" "ONT:PROCEDURE" :id "NCIT:C20055" :name "nucleic acid amplification test") 
("MVI" "ONT:PROTEIN" :id "UP:Q9I834" :name "Basic phospholipase A2 homolog 2") 
("MTOC" "ONT:CELL-PART" :id "GO:0005815" :name "microtubule organizing center") 
("MSV" "ONT:GENE" :id "NCIT:C51245" :name "MOS") 
("MSKCC" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39457" :name "memorial sloan-kettering cancer center") 
("MSB" "ONT:CELL-PART" :id "GO:0150086" :name "multiple synapse bouton") 
("MOVAS" "ONT:CELL-LINE" :id "CVCL:0F08" :name "MOVAS-1") 
("MOEA" "ONT:PROTEIN-FAMILY" :id "FA:02340" :name "moeA family") 
("MOCV" "ONT:VIRUS" :id "NCIT:C112357" :name "molluscum contagiosum virus") 
("MMTS" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C014674" :name "methyl methanethiosulfonate") 
("MHO" "ONT:MEASURE-UNIT" :id "UO:0000264" :name "siemens") 
("MGD" "ONT:MOLECULE" :id "CHEBI:50161" :name "motexafin gadolinium") 
("MAGUK" "ONT:PROTEIN-FAMILY" :id "FA:02147" :name "MAGUK family") 
("LNV" "ONT:CELL-LINE" :id "CVCL:VI00" :name "LN-V") 
("LMWH" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2578" :name "low molecular weight heparin") 
("LMD" "ONT:PROCEDURE" :id "NCIT:C19263" :name "laser capture microdissection") 
("LIBRA" "ONT:CELL-LINE" :id "CVCL:E028" :name "PAE-iPS-7") 
("LHC" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00556" :name "LHC") 
("LCD" "ONT:CELL-LINE" :id "CVCL:1787" :name "VMRC-LCD") 
("KYY" "ONT:PROTEIN-FAMILY" :id "XFAM:PF10199" :name "adaptin binding") 
("KLS" "ONT:GENE" :id "HGNC:10437" :name "ribosomal protein S6 kinase B2") 
("KHR" "ONT:CELL-LINE" :id "CVCL:G348" :name "KH-R") 
("JYS" "ONT:CELL-LINE" :id "CVCL:0108" :name "JY") 
("JVC" "ONT:CELL-LINE" :id "CVCL:R734" :name "JVC") 
("JPS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2929" :name "Juvenile polyposis syndrome") 
("JPG" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2801" :name "Juvenile Paget disease") 
("JMN" "ONT:CELL-LINE" :id "CVCL:M005" :name "JMN") 
("JME" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:307" :name "Juvenile myoclonic epilepsy") 
("JHC" "ONT:CELL-LINE" :id "CVCL:M093" :name "JHC") 
("JCV" "ONT:VIRUS" :id "NCIT:C14229" :name "JC virus") 
("IUPAC" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C82878" :name "international union of pure and applied chemistry") 
("IUGR" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C114875" :name "fetus small for gestational age") 
("ITSM" "ONT:CELL-LINE" :id "CVCL:JF86" :name "ITSM") 
("IRB" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C16741" :name "institutional review board") 
("IPD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:238455" :name "Infantile dystonia-parkinsonism") 
("IPCC" "ONT:MOLECULE" :id "CHEBI:62701" :name "Ins-1-P-Cer(t20:0/2-OH-26:0)") 
("IOO" "ONT:MOLECULE" :id "CHEBI:29902" :name "iodidodioxygen(.)") 
("IMOD" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C555145" :name "setarud") 
("IIIA" "ONT:CANCER" :id "NCIT:C88137" :name "stage IIIA uveal melanoma AJCC v7") 
("IIA" "ONT:CANCER" :id "NCIT:C88135" :name "stage IIA uveal melanoma AJCC v7") 
("IHD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C50625" :name "ischemic heart disease") 
("IGO" "ONT:GENE" :id "NCIT:C118231" :name "IGLL1") 
("IFNK" "ONT:GENE" :id "HGNC:21714" :name "interferon kappa") 
("IFNGR" "ONT:GENE-PROTEIN" :id "FPLX:Interferon_gamma_receptor" :name "Interferon-gamma-receptor") 
("IFNE" "ONT:GENE" :id "HGNC:18163" :name "interferon epsilon") 
("IFI" "ONT:GENE" :id "NCIT:C52798" :name "IFNG") 
("ICH" "ONT:GENE" :id "NCIT:C152982" :name "COL4A2") 
("ICF" "ONT:CELL-LINE" :id "CVCL:M423" :name "ICF") 
("IBS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000555" :name "irritable bowel syndrome") 
("IAH" "ONT:PROTEIN" :id "UP:Q04557" :name "Indoleacetamide hydrolase") 
("IACUC" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19487" :name "institutional animal care and use committee") 
("HYPD" "ONT:GENE-PROTEIN" :id "NCIT:C54307" :name "MAGEA3") 
("HUS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C75545" :name "hemolytic uremic syndrome") 
("HTLVI" "ONT:VIRUS" :id "NCIT:C14223" :name "HTLV-1") 
("HMAF" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1717" :name "irofulven") 
("HKC" "ONT:CELL-LINE" :id "CVCL:WZ51" :name "HKC") 
("HIBM" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0007323" :name "inclusion body myositis") 
("HFF" "ONT:CELL-LINE" :id "CVCL:XB54" :name "HFF") 
("HERCEPTIN" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1647" :name "trastuzumab") 
("HCM" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000538" :name "hypertrophic cardiomyopathy") 
("HCG" "ONT:GENE-PROTEIN" :id "FPLX:hCG" :name "hCG") 
("HCB" "ONT:PROTEIN" :id "UP:Q9NFH9" :name "Hemocyanin B chain") 
("HAV" "ONT:VIRUS" :id "NCIT:C14325" :name "hepatitis A virus") 
("HADS" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C018209" :name "4-amino-4'-hydroxylaminodiphenylsulfone") 
("GUA" "ONT:CHEMICAL" :id "CHEBI:16235" :name "guanine") 
("GJR" "ONT:CELL-LINE" :id "CVCL:Z599" :name "GJR") 
("GATAN" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05349" :name "GATA-N") 
("FMD" "ONT:GENE" :id "NCIT:C113586" :name "FLNA") 
("FLUBV" "ONT:VIRUS" :id "NCIT:C53468" :name "influenza B virus") 
("FLUAV" "ONT:VIRUS" :id "NCIT:C53454" :name "influenza A virus") 
("FIGO" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C89808" :name "federation of gynecology and obstetrics") 
("FFS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1988" :name "Femoral-facial syndrome") 
;("FDA" "ONT:PROTEIN" :id "UP:P81543" :name "Zinc-containing ferredoxin A") 
("FCR" "ONT:PROTEIN-FAMILY" :id "NCIT:C17070" :name "Fc receptor") 
("FAO" "ONT:CELL-LINE" :id "CVCL:0269" :name "Fao") 
("EXFABP" "ONT:PROTEIN" :id "UP:P21760" :name "Extracellular fatty acid-binding protein") 
("EVE" "ONT:PROTEIN" :id "UP:A1YPR3" :name "2-epi-5-epi-valiolone epimerase") 
("ETV" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65513" :name "entecavir") 
("ERV" "ONT:VIRUS" :id "NCIT:C14334" :name "endogenous retrovirus") 
("ERGIC" "ONT:PROTEIN-FAMILY" :id "FA:01131" :name "ERGIC family") 
("ERAD" "ONT:BIOLOGICAL-PROCESS" :id "GO:0030433" :name "ubiquitin-dependent ERAD pathway") 
("ENCAD" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C031373" :name "ENKAD") 
("EMJH" "ONT:CELL-LINE" :id "CVCL:E583" :name "EMJ") 
("ELR" "ONT:CELL-LINE" :id "EFO:0007750" :name "ELR") 
("EJM" "ONT:CELL-LINE" :id "CVCL:2030" :name "EJM") 
("EJC" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0035145" :name "exon-exon junction complex") 
("EDSS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:247820" :name "Ectodermal dysplasia - syndactyly syndrome") 
("EDIM" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C009680" :name "VX") 
("EBA" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1000691" :name "epidermolysis bullosa acquisita") 
("DXP" "ONT:CELL-LINE" :id "CVCL:4T94" :name "MES-SA/DxP5002") 
("DVT" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C49343" :name "deep vein thrombosis") 
("DSPC" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00782" :name "DSPc") 
("DSMB" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C94204" :name "data and safety monitoring board") 
("DPTP" "ONT:PROTEIN" :id "UP:P16620" :name "Tyrosine-protein phosphatase 69D") 
("DOTAP" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C070046" :name "1,2-dioleoyloxy-3-(trimethylammonium)propane") 
("DOPG" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C051388" :name "1,2-dioleoyl-sn-glycero-3-phosphoglycerol") 
("DNP" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2478" :name "dinitrophenyl") 
("DMY" "ONT:PROTEIN" :id "UP:Q8JIR6" :name "Doublesex- and mab-3-related transcription factor 1Y") 
("DMXAA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2504" :name "vadimezan") 
("DMAPP" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C043060" :name "3,3-dimethylallyl pyrophosphate") 
("DJS" "ONT:CELL-LINE" :id "CVCL:E564" :name "DJS") 
("DGP" "ONT:CHEMICAL" :id "CHEBI:73291" :name "Asp-Gly-Pro") 
("DGE" "ONT:CELL-LINE" :id "CVCL:Z423" :name "UMC-DgE") 
("DGCR" "ONT:GENE" :id "NCIT:C75412" :name "TBX1") 
("DEHS" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C037634" :name "di-2-ethylhexyl sebacate") 
("DEAE" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C007369" :name "2-diethylaminoethanol") 
("DCBA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C064515" :name "2',4'-dichlorobenzamil amiloride") 
("DALT" "ONT:MOLECULE" :id "CHEBI:28385" :name "D-altrose") 
("DALI" "ONT:RNA" :id "HGNC:51429" :name "DNMT1-associated long intergenic non-coding RNA") 
("CXC" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF03638" :name "TCR") 
("CVS" "ONT:CELL-LINE" :id "CVCL:DE07" :name "CV-S") 
("CTPA" "ONT:GENE-PROTEIN" :id "NCIT:C51755" :name "EPHA2") 
("CTE" "ONT:CELL-LINE" :id "CVCL:R826" :name "CTE") 
("CSS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1465" :name "Coffin-Siris syndrome") 
("CSI" "ONT:PROTEIN" :id "UP:P07469" :name "Corticostatin 1") 
("COOT" "ONT:PROTEIN-FAMILY" :id "XFAM:PF10133" :name "CooT") 
("COG" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39353" :name "children's oncology group") 
("CMY" "ONT:CELL-LINE" :id "CVCL:A602" :name "CMY") 
("CMV" "ONT:VIRUS" :id "NCIT:C14196" :name "cytomegalovirus") 
("CMC" "ONT:PROTEIN-FAMILY" :id "FA:04991" :name "CMC family") 
("CLY" "ONT:CELL-LINE" :id "CVCL:IQ58" :name "CLY") 
("CLAC" "ONT:CELL-LINE" :id "CVCL:J360" :name "CLAC") 
("CLAB" "ONT:CELL-LINE" :id "CVCL:6A78" :name "CLAB") 
("CIEB" "ONT:CELL-LINE" :id "CVCL:6A77" :name "CIEB") 
("CHCA" "ONT:CHEMICAL" :id "CHEBI:64340" :name "alpha-cyano-4-hydroxycinnamic acid") 
("CHAPSO" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C048531" :name "chapso") 
("CGAT" "ONT:GENE" :id "NCIT:C107578" :name "SLC18A1") 
("CFSE" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C087165" :name "5-(6)-carboxyfluorescein diacetate succinimidyl ester") 
("CESA" "ONT:PROTEIN-FAMILY" :id "XFAM:PF11439" :name "T3SchapCesA") 
("CEP" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:79277" :name "Congenital erythropoietic porphyria") 
("CEG" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C17879" :name "cisplatin-E therapeutic implant") 
("CCV" "ONT:CELL-PART" :id "UP:SL-0070" :name "Clathrin-coated vesicle") 
("CCM" "ONT:CELL-LINE" :id "CVCL:R825" :name "CCM") 
("CCH" "ONT:CELL-LINE" :id "CVCL:RL59" :name "CCH") 
("CALB" "ONT:GENE-PROTEIN" :id "UP:P41365" :name "Lipase B") 
("BSS" "ONT:GENE" :id "NCIT:C126547" :name "GP1BA") 
("BSI" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:100976" :name "Bathing suit ichthyosis") 
("BPL" "ONT:PROTEIN" :id "UP:P86970" :name "C-type lectin BpLec") 
("BPA" "ONT:GENE-PROTEIN" :id "NCIT:C104890" :name "DST") 
("BMA" "ONT:CELL-LINE" :id "CVCL:IW58" :name "BMA3.1A7") 
("BLN" "ONT:CELL-LINE" :id "CVCL:3655" :name "BLn") 
("BKV" "ONT:VIRUS" :id "NCIT:C89820" :name "BK virus") 
("BJAB" "ONT:CELL-LINE" :id "EFO:0002815" :name "BJAB") 
("BES" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C012210" :name "BES") 
("BEI" "ONT:CELL-LINE" :id "CVCL:E474" :name "BEI") 
("BDE" "ONT:GENE" :id "NCIT:C97584" :name "HOXD13") 
("BCV" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73198" :name "buciclovir") 
("BCS" "ONT:GENE" :id "HGNC:1020" :name "BCS1 homolog, ubiquinol-cytochrome c reductase complex chaperone") 
("BASC" "ONT:CELL" :id "CO:0002638" :name "bronchioalveolar stem cell") 
("BADH" "ONT:PROTEIN" :id "UP:Q9S795" :name "Betaine aldehyde dehydrogenase 1, chloroplastic") 
("AZC" "ONT:CHEMICAL" :id "CHEBI:53088" :name "alizarin complexone") 
("AVL" "ONT:CELL-LINE" :id "CVCL:E464" :name "AVL") 
("ATG" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C278" :name "anti-thymocyte globulin") 
("ASPA" "ONT:GENE" :id "HGNC:756" :name "aspartoacylase") 
("ARMC" "ONT:CELL-LINE" :id "CVCL:IW83" :name "ARM-C") 
("APEC" "ONT:PROTEIN-FAMILY" :id "XFAM:PF16977" :name "ApeC") 
("AMC" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1037" :name "Arthrogryposis multiplex congenita") 
("AHX" "ONT:GENE" :id "NCIT:C75865" :name "NR0B1") 
("AGR" "ONT:PROTEIN-FAMILY" :id "FA:00127" :name "AGR family") 
("AADD" "ONT:CHEMICAL" :id "CHEBI:73314" :name "Ala-Ala-Asp-Asp") 
