(in-package :sparser)

(defparameter *no-texttagger-defs*
 '("ABV" "AMV" "APBS" "APTT" "ATCC" "BCL" "BMI" "CABS" "CBB" "CBE" "CGF" "CIV"
    "CLIA" "CPAS" "DTI" "DUA" "DWI" "ELISA" "ELISPOT" "EMR" "ENSEMBL" "ESM"
    "FAQ" "FASTA" "FFPE" "FFU" "FOV" "FVC" "FWHM" "GAC" "GGO" "GMB" "HAART"
    "HIPAA" "HKG" "HRV" "ICU" "ICV" "IHC" "INDEL" "IRES" "IRQ" "ISH" "ISI"
    "ISL" "ISR" "IVIG" "LBS" "LOD" "LTR" "MFI" "MGI" "MISC" "MLI" "MNA" "MNI"
    "NPV" "NZO" "ONS" "PBM" "PHN" "PNS" "QIAGEN" "QTL" "QUARK" "RFU" "RGD"
    "RLT" "RSI" "SMILES" "SNR" "SOT" "SVC" "SWISS" "TAE" "TCGA" "TCID" "TCT"
    "TIFF" "TMHMM" "UCSC" "UMI" "URL" "WBC" "YPD" "ZEBOV" "absorbance" "agar"
    "algorithm" "alveoli" "amygdala" "analyte" "aneuploidy" "annum" "anorexia"
    "apnea" "archenteron" "arrhythmia" "asian" "autoimmune" "autoradiography"
    "ave" "axial" "bandwidth" "biomedicine" "biopsy" "biospecimen"
    "birthweight" "blastula" "bpm" "bronchoscope" "bronchoscopy" "browser"
    "bwa" "cannula" "carboxyl" "catheter" "cecal" "cecum" "cellphone"
    "centroid" "cerebellum" "cgi" "chemo" "chemoradiotherapy" "chosen" "codon"
    "colostrum" "commissure" "comorbid" "conc" "conjunctiva" "contig"
    "crossover" "cysteinyl" "dataset" "daycare" "decidua" "der" "diploid"
    "divider" "doi" "dorsum" "drc" "dropper" "dyskinesia" "dysplasia" "dyspnea"
    "echocardiography" "ecotype" "ectoderm" "edema" "electrocardiography"
    "electrophysiology" "email" "emitter" "encoder" "endoderm" "endometrium"
    "endoscopy" "endpoint" "enhancer" "ensembl" "epithelium" "exome" "facto"
    "faeces" "fasciculus" "fasta" "fastq" "fecal" "flowchart" "fna" "follicles"
    "followup" "footpad" "frozen" "funder" "gastro" "gastrocnemius" "gastrula"
    "gavage" "genome" "glia" "globus" "glomerulus" "glutamyl" "gracilis"
    "greater" "greatest" "haplotype" "heatmap" "helix" "hematocrit"
    "hematology" "hemi" "hemolymph" "hey" "hidden" "hindlimb" "histology"
    "histopathology" "homogenate" "hotspot" "html" "hyperpyrexia" "hyposmia"
    "hypothermia" "hypoxemia" "identifier" "ileum" "imager" "immunoassay"
    "immunohistochemistry" "immunopathology" "indel" "infundibulum" "inhouse"
    "internet" "intracardiac" "intron" "iodoacetamide" "isotype" "japanese"
    "kappa" "karyotype" "kcal" "lambda" "lavage" "lifespan" "likeliness"
    "liposome" "lobule" "loge" "lumen" "lymphadenopathy" "lymphocytopenia"
    "lymphopenia" "math" "mbi" "mediterranean" "mesenchyme" "mesoderm"
    "metadata" "metagenome" "micelle" "microplate" "microsatellite"
    "microsphere" "microtome" "mismatch" "monocytopenia" "monotherapy"
    "morpholino" "msec" "multi" "myocardium" "nano" "nanopore" "nanotechnology"
    "nasopharynx" "nearest" "nebulizer" "neg" "neuropathology" "niger"
    "nonmalignant" "nucleo" "odorant" "opioid" "ortholog" "overdose" "oximetry"
    "pallidum" "pancreatitis" "parenchyma" "parkinsonism" "pathophysiology"
    "pdf" "penetrance" "pericardium" "pharmacotherapy" "photomultiplier" "pico"
    "pixel" "plethysmography" "ploidy" "poi" "polymorphism" "postmortem"
    "postpartum" "ppp" "pre" "preterm" "proband" "procalcitonin" "progeny"
    "proteome" "pseudogene" "psychopathology" "pubchem" "putamen" "pvalue"
    "quadriceps" "quadrupole" "raphe" "replicate" "retest" "retro" "reuse"
    "rpm" "rumen" "seq" "sequelae" "serostatus" "serotype" "sinusoid" "soleus"
    "somite" "spacer" "spanish" "spectrometer" "spectrophotometer" "spirometry"
    "stereochemistry" "stereotypy" "subclass" "subgenus" "submitter" "suborder"
    "subsite" "subspecies" "subtype" "supernatant" "superscript" "swiss"
    "synthesizer" "tachycardia" "taken" "tapetum" "telehealth" "telemedicine"
    "tenesmus" "tetrad" "tetrahedron" "thalamus" "theta" "tibialis" "timeline"
    "timepoint" "timespan" "titer" "titre" "topology" "transcriptome"
    "transducer" "transposon" "trimester" "triploid" "tubulointerstitium"
    "tuple" "ucsc" "unmet" "vegan" "venipuncture" "villus" "viremia" "viscera"
    "voxel" "website" "wildtype" "withdrawn" "workflow" "www" "xylem"
    "Affymetrix" "Africa" "African" "Americas" "Arab" "Asian" "Atto"
    "Bangladeshi" "Bcl" "BiPAP" "BioAssay" "Boolean" "Brighton" "Browser"
    "Caribbean" "Celsius" "Columbia" "Congo" "Copenhagen" "Cum" "Delaware"
    "Dev" "Diag" "Digitizer" "Dura" "Endy" "Entrez" "Europe" "Exome" "FastQ"
    "Finnish" "FoV" "GTEx" "Gauss" "Gini" "Glutamyl" "Gquadruplex" "Hematocrit"
    "Hematology" "Hypoproteinemia" "ImmunoChemistry" "Java" "KAc" "Korean"
    "Laguna" "LoD" "MHz" "Martinique" "MeV" "Metadata" "MiSeq" "Microplate"
    "Miseq" "Nanopore" "Neutrophilia" "Oceania" "Odorant" "Oncology" "Ottawa"
    "PFam" "Pau" "Pfam" "Piscataway" "Progeny" "Pulser" "QIAgen" "Qiagen"
    "Québec" "RefSeq" "SNr" "Sandia" "Sartorius" "Sequest" "SignalP"
    "Singaporean" "Spanish" "Stan" "SuperScript" "Taiwanese" "Tetraploid"
    "Tibetan" "Tli" "Tmax" "Twentytwo" "UniProtKB" "Unigene" "Urology"
    "Vacutainer" "Vmax" "Xray" "Zaire" "Zetasizer" "dsDNA" "gDNA" "Helix"
    "Immunohistochemistry" "kHz" "keV" "mefA" "pDNA" "pdU" "ssDNA"
    "Telemedicine" "Villus"))
