(in-package :sparser)

(defparameter *trips-defs*
  '(("vSIR" "ONT:GENE-PROTEIN" :id "HGNC:30085" :name "V-set immunoregulatory receptor") 
("vRNA" "ONT:RNA" :id "HGNC:12654" :name "vault RNA 1-1") 
("Tilorone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73335" :name "tilorone") 
("sCAI" "ONT:GENE-PROTEIN" :id "HGNC:26709" :name "suppressor of cancer cell invasion") 
("repC" "ONT:CELL-LINE" :id "CVCL:W815" :name "REPC") 
("qPCR" "ONT:PROCEDURE" :id "NCIT:C51962" :name "real time PCR") 
("psaA" "ONT:PROTEIN" :id "UP:Q9MTQ4" :name "Photosystem I P700 chlorophyll a apoprotein A1") 
("nsP" "ONT:GENE-PROTEIN" :id "NCIT:C17692" :name "reticulon-1") 
("nanA" "ONT:PROTEIN-FAMILY" :id "FA:00943" :name "nanA subfamily") 
("nRCs" "ONT:CELL-LINE" :id "CVCL:WJ27" :name "NRCs") 
("nCBE" "ONT:GENE" :id "HGNC:13811" :name "solute carrier family 4 member 10") 
("miRNASeq" "ONT:PROCEDURE" :id "NCIT:C156057" :name "microRNA sequencing") 
("lnP" "ONT:GENE" :id "NCIT:C126504" :name "NUSAP1") 
("hRSV" "ONT:VIRUS" :id "NCIT:C14267" :name "human respiratory syncytial virus") 
("hAPN" "ONT:PROTEIN" :id "UP:P15144" :name "Aminopeptidase N") 
("ePCR" "ONT:GENE" :id "NCIT:C118583" :name "PROCR") 
("dREG" "ONT:GENE" :id "NCIT:C153051" :name "ADGRG6") 
("crRNA" "ONT:CELL-PART" :id "CHEBI:134528" :name "CRISPR RNA") 
("compB" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C402921" :name "J 113397") 
("Fosaprepitant" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72787" :name "fosaprepitant") 
("Clocortolone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61684" :name "clocortolone") 
("attR" "ONT:GENE-PROTEIN" :id "NCIT:C79963" :name "TTR") 
("Zika" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C128423" :name "zika virus infection") 
;("Yucatan" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C77108" :name "yucatan pig") 
("ViPR" "ONT:GENE-PROTEIN" :id "UP:Q90308" :name "Vasoactive intestinal polypeptide receptor") 
("Vero" "ONT:CELL-LINE" :id "CVCL:0059" :name "Vero") 
("Urso" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1818" :name "ursodiol") 
("Ureaplasma" "ONT:BACTERIUM" :id "NCIT:C86832" :name "ureaplasma") 
("Ubx" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00789" :name "UBX") 
("Trt" "ONT:GENE" :id "NCIT:C52497" :name "TERT") 
("Trizol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C411644" :name "trizol") 
("Treponema" "ONT:BACTERIUM" :id "NCIT:C76385" :name "treponema") 
("Toxoplasma" "ONT:ORGANISM" :id "NCIT:C75538" :name "toxoplasma") 
("Toremifene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1256" :name "toremifene") 
("Tgt" "ONT:GENE-PROTEIN" :id "XFAM:PF01702" :name "TGT") 
("Tenericutes" "ONT:BACTERIUM" :id "NCIT:C85860" :name "tenericutes") 
("Telazol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C006131" :name "tiletamine, zolazepam drug combination") 
("Teck" "ONT:GENE" :id "NCIT:C49742" :name "CCL25") 
("Tbp" "ONT:GENE-PROTEIN" :id "HGNC:11588" :name "TATA-box binding protein") 
("TRIzol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C411644" :name "trizol") 
;("TMDs" "ONT:CANCER" :id "NCIT:C27722" :name "therapy-related myelodysplastic syndrome") 
;("Sumatran" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:10650" :name "sumatriptan") 
("Strongyloides" "ONT:INVERTEBRATE" :id "NCIT:C125924" :name "strongyloides") 
;("Std" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C3365" :name "sexually transmitted disorder") 
("Sprotein" "ONT:PROTEIN" :id "NCIT:C17283" :name "vitronectin") 
("Spirochaetes" "ONT:BACTERIUM" :id "NCIT:C76206" :name "spirochaetes") 
("Sphingomonadaceae" "ONT:BACTERIUM" :id "NCIT:C85964" :name "sphingomonadaceae") 
("Sia" "ONT:CELL-LINE" :id "CVCL:F582" :name "SIA") 
("Sci" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C105626" :name "stanford cancer institute") 
("Sapovirus" "ONT:VIRUS" :id "NCIT:C112029" :name "sapovirus") 
("SapI" "ONT:PROTEIN-FAMILY" :id "XFAM:PF16560" :name "SAPI") 
;("SacI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39511" :name "cancer therapy and research center") 
;("SRs" "ONT:GENE" :id "HGNC:11123" :name "spermine synthase") 
("SARSCoV" "ONT:VIRUS" :id "NCIT:C112432" :name "SARS coronavirus") 
("Rxn" "ONT:PROTEIN" :id "UP:Q9MYK8" :name "Prorelaxin") 
("Rubella" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C85051" :name "rubella infection") 
("Rotavirus" "ONT:VIRUS" :id "NCIT:C77199" :name "rotavirus") 
("Rifabutin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1408" :name "rifabutin") 
("Rhodococcus" "ONT:BACTERIUM" :id "NCIT:C76378" :name "rhodococcus") 
("Rhodobacteraceae" "ONT:BACTERIUM" :id "NCIT:C118931" :name "rhodobacteraceae") 
("Reston" "ONT:MOLECULE" :id "CHEBI:6820" :name "methapyrilene") 
("RTx" "ONT:CANCER" :id "NCIT:C82594" :name "refractory thrombocytopenia") 
("RNAseq" "ONT:PROCESS" :id "EFO:0002770" :name "transcription profiling by high throughput sequencing") 
("Queuosine" "ONT:MOLECULE" :id "CHEBI:60193" :name "queuosine") 
("Pyridostatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C567962" :name "pyridostatin") 
("Pseudomonas" "ONT:BACTERIUM" :id "NCIT:C76375" :name "pseudomonas") 
("Prkaca" "ONT:GENE-PROTEIN" :id "HGNC:9380" :name "protein kinase cAMP-activated catalytic subunit alpha") 
("Prec" "ONT:CELL-LINE" :id "CVCL:0061" :name "NPrEC") 
("Poxviridae" "ONT:VIRUS" :id "NCIT:C14261" :name "poxvirus") 
("Porphyromonas" "ONT:BACTERIUM" :id "NCIT:C86653" :name "porphyromonas") 
("Polytetrafluoroethylene" "ONT:MOLECULE" :id "CHEBI:53251" :name "poly(tetrafluoroethylene)") 
("Plexiglas" "ONT:CHEMICAL" :id "CHEBI:61369" :name "poly(methyl methacrylate) polymer") 
("Phy" "ONT:PROTEIN-FAMILY" :id "XFAM:PF00360" :name "PHY") 
("PfCRT" "ONT:PROTEIN" :id "UP:Q9N623" :name "Chloroquine resistance transporter") 
("Pefabloc" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C002010" :name "4-(2-aminoethyl)benzenesulfonylfluoride") 
("Parvoviridae" "ONT:VIRUS" :id "NCIT:C14299" :name "parvovirus") 
("Paramethasone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C66309" :name "paramethasone") 
("Paracoccus" "ONT:BACTERIUM" :id "NCIT:C123337" :name "paracoccus") 
("Pantoea" "ONT:BACTERIUM" :id "NCIT:C86631" :name "pantoea") 
("PaKi" "ONT:PROTEIN" :id "UP:Q29502" :name "Serine/threonine-protein kinase PAK 2") 
("POs" "ONT:PROTEIN" :id "UP:Q8VCZ9" :name "Hydroxyproline dehydrogenase") 
("PHAs" "ONT:MOLECULE" :id "CHEBI:53387" :name "poly(hydroxyalkanoate)") 
("Orthomyxoviridae" "ONT:VIRUS" :id "NCIT:C53453" :name "orthomyxoviridae") 
("Orfs" "ONT:GENE" :id "NCIT:C106210" :name "ATP6AP1") 
("Oligofectamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C484027" :name "oligofectamine") 
;("ORs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C116333" :name "oculo-respiratory syndrome") 
("OASs" "ONT:PROTEIN" :id "UP:P0A535" :name "O-acetylserine sulfhydrylase") 
("Novus" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C076789" :name "polyphosphazene fluoroelastomer") 
("Nosema" "ONT:FUNGUS" :id "NCIT:C123530" :name "nosema") 
("Norvir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1609" :name "ritonavir") 
("NeuAc" "ONT:MOLECULE" :id "CHEBI:17012" :name "N-acetylneuraminic acid") 
("Nes" "ONT:GENE" :id "HGNC:7756" :name "nestin") 
("Neisseria" "ONT:BACTERIUM" :id "NCIT:C76371" :name "neisseria") 
("NTproBNP" "ONT:PROTEIN" :id "NCIT:C88524" :name "N-terminal fragment brain natriuretic protein") 
("Mycoplasma" "ONT:BACTERIUM" :id "NCIT:C73540" :name "mycoplasma") 
("MxB" "ONT:GENE" :id "NCIT:C101553" :name "MX2") 
("Mprotein" "ONT:PROTEIN" :id "NCIT:C17788" :name "M protein") 
("Mpro" "ONT:CELL-LINE" :id "CVCL:5430" :name "MPRO clone 2.1") 
("Moraxella" "ONT:BACTERIUM" :id "NCIT:C86009" :name "moraxella") 
("MonoQ" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C042855" :name "Mono Q") 
("MkI" "ONT:PROTEIN" :id "UP:P16388" :name "Potassium voltage-gated channel subfamily A member 1") 
("Microbacterium" "ONT:BACTERIUM" :id "NCIT:C85511" :name "microbacterium") 
("Microbacteriaceae" "ONT:BACTERIUM" :id "NCIT:C85945" :name "microbacteriaceae") 
("Mesalazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29249" :name "mesalamine") 
("MeOH" "ONT:MOLECULE" :id "CHEBI:17790" :name "methanol") 
("Mav" "ONT:GENE" :id "HGNC:6353" :name "kelch like family member 2") 
("Mannheimia" "ONT:BACTERIUM" :id "NCIT:C86507" :name "mannheimia") 
("Macrogen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77591" :name "molgramostim") 
("MHCs" "ONT:PROTEIN-FAMILY" :id "NCIT:C121977" :name "HLA complex") 
("Luce" "ONT:CELL-LINE" :id "CVCL:E760" :name "LUCE") 
("Lse" "ONT:GENE" :id "NCIT:C91283" :name "SIAE") 
("Lpo" "ONT:GENE-PROTEIN" :id "HGNC:6678" :name "lactoperoxidase") 
("Lipofectamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C086724" :name "Lipofectamine") 
("Lglutamine" "ONT:MOLECULE" :id "CHEBI:18050" :name "L-glutamine") 
("Leuconostoc" "ONT:BACTERIUM" :id "NCIT:C76357" :name "leuconostoc") 
("Leptospiraceae" "ONT:BACTERIUM" :id "NCIT:C86000" :name "leptospiraceae") 
("Leifsonia" "ONT:BACTERIUM" :id "NCIT:C86490" :name "leifsonia") 
("Leh" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF07858" :name "LEH") 
("Lactobacillus" "ONT:BACTERIUM" :id "NCIT:C76352" :name "lactobacillus") 
("KsgA" "ONT:PROTEIN-FAMILY" :id "FA:02277" :name "ksgA subfamily") 
("Kluyveromyces" "ONT:FUNGUS" :id "NCIT:C114123" :name "kluyveromyces") 
("Kaletra" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2096" :name "lopinavir/Ritonavir") 
("KOAc" "ONT:CHEMICAL" :id "CHEBI:32029" :name "potassium acetate") 
("Juno" "ONT:GENE" :id "HGNC:32565" :name "IZUMO1 receptor, JUNO") 
("Iswi" "ONT:GENE-PROTEIN" :id "FA:03705" :name "ISWI subfamily") 
;("Inc" "ONT:CELL-LINE" :id "CVCL:QX03" :name "INC") 
("Ifnar" "ONT:GENE" :id "NCIT:C51352" :name "IFNAR1") 
;("IIc" "ONT:CANCER" :id "NCIT:C140168" :name "stage IIC prostate cancer AJCC v8") 
;("IIIc" "ONT:CANCER" :id "NCIT:C88139" :name "stage IIIC uveal melanoma AJCC v7") 
("IFNaB" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C076799" :name "interferon-alpha 8") 
("IFNa" "ONT:GENE-PROTEIN" :id "FPLX:IFNA" :name "IFNA") 
("IDi" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:363300" :name "Genetic intractable diarrhea of infancy") 
;("IARs" "ONT:GENE" :id "HGNC:5330" :name "isoleucyl-tRNA synthetase 1") 
("Hottip" "ONT:RNA" :id "HGNC:37461" :name "HOXA distal transcript antisense RNA") 
("Herpesviridae" "ONT:VIRUS" :id "NCIT:C14217" :name "herpesvirus") 
("Hepacivirus" "ONT:VIRUS" :id "NCIT:C113202" :name "hepacivirus") 
("Henipavirus" "ONT:VIRUS" :id "NCIT:C112290" :name "henipavirus") 
("Helicobacter" "ONT:BACTERIUM" :id "NCIT:C14296" :name "helicobacter") 
("HeLaM" "ONT:CELL-LINE" :id "CVCL:R965" :name "HeLa M") 
;("HSAs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2182" :name "Hydrocephalus with stenosis of the aqueduct of Sylvius") 
("GxGxG" "ONT:PROTEIN-FAMILY" :id "XFAM:PF01493" :name "GXGXG") 
("Gsx" "ONT:GENE" :id "NCIT:C52275" :name "ABCC1") 
("Glutamyl" "ONT:RESIDUE" :id "CHEBI:32483" :name "glutamic acid residue") 
("Glc" "ONT:CHEMICAL" :id "CHEBI:17234" :name "glucose") 
("Gideon" "ONT:CELL-LINE" :id "CVCL:D978" :name "MRC-iPS-62") 
("Genotype" "ONT:PROCEDURE" :id "NCIT:C45447" :name "genotyping") 
("Gemini" "ONT:CELL-LINE" :id "CVCL:E024" :name "PAE-iPS-3") 
("Gemella" "ONT:BACTERIUM" :id "NCIT:C86889" :name "gemella") 
("Gedunin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C106014" :name "gedunin") 
("Gdf" "ONT:GENE" :id "HGNC:8573" :name "progestagen associated endometrial protein") 
("Gatan" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05349" :name "GATA-N") 
("Gammacoronavirus" "ONT:VIRUS" :id "NCIT:C122313" :name "gammacoronavirus") 
("GPe" "ONT:GENE-PROTEIN" :id "HGNC:4705" :name "glycophorin E (MNS blood group)") 
("Fugene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C411955" :name "FuGene") 
("Fuc" "ONT:MOLECULE" :id "CHEBI:33984" :name "fucose") 
("FuGENE" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C411955" :name "FuGene") 
("Flurazepam" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62030" :name "flurazepam") 
("Filoviridae" "ONT:VIRUS" :id "NCIT:C112031" :name "filoviridae") 
("Fabs" "ONT:GENE" :id "NCIT:C86023" :name "FANCB") 
("Eubacterium" "ONT:BACTERIUM" :id "NCIT:C86383" :name "eubacterium") 
("Est" "ONT:GENE" :id "NCIT:C51214" :name "MAP3K8") 
("Escherichia" "ONT:BACTERIUM" :id "NCIT:C77208" :name "escherichia") 
("Epsin" "ONT:GENE-PROTEIN" :id "FPLX:EPN" :name "EPN") 
("Enterococcus" "ONT:BACTERIUM" :id "NCIT:C76311" :name "enterococcus") 
("Endpoint" "ONT:PROCEDURE" :id "NCIT:C82866" :name "endpoint value derivation technique") 
("EndoU" "ONT:GENE-PROTEIN" :id "HGNC:14369" :name "endonuclease, poly(U) specific") 
("Encephalitozoon" "ONT:FUNGUS" :id "NCIT:C122293" :name "encephalitozoon") 
("EcoRI" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF02963" :name "EcoRI") 
("Dscam" "ONT:GENE" :id "HGNC:3039" :name "DS cell adhesion molecule") 
("Ditan" "ONT:MOLECULE" :id "CHEBI:38884" :name "diphenylmethane") 
("Deltacoronavirus" "ONT:VIRUS" :id "NCIT:C122279" :name "deltacoronavirus") 
("Darunavir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65364" :name "darunavir") 
;("Dakar" "ONT:GENE" :id "NCIT:C84305" :name "CARD8") 
("DNAseq" "ONT:PROCESS" :id "EFO:0002693" :name "DNA-seq") 
;("Cuban" "ONT:MOLECULE" :id "CHEBI:33014" :name "cubane") 
("CspA" "ONT:PROTEIN" :id "UP:P0A9Y1" :name "Cold shock protein CspA") 
("CsI" "ONT:PROTEIN" :id "UP:P07469" :name "Corticostatin 1") 
("Cryptococcus" "ONT:FUNGUS" :id "NCIT:C77184" :name "cryptococcus") 
("CrI" "ONT:PROCEDURE" :id "NCIT:C123799" :name "cell response index") 
("Coulomb" "ONT:MEASURE-UNIT" :id "UO:0000220" :name "coulomb") 
("Corynebacterium" "ONT:BACTERIUM" :id "NCIT:C76308" :name "corynebacterium") 
("Copan" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:397725" :name "COASY protein-associated neurodegeneration") 
("Cmn" "ONT:CANCER" :id "NCIT:C6569" :name "congenital mesoblastic nephroma") 
("Clostripain" "ONT:PROTEIN" :id "UP:P09870" :name "Clostripain") 
("Clostridium" "ONT:BACTERIUM" :id "NCIT:C76275" :name "clostridium") 
("Clevidipine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72727" :name "clevidipine") 
("Cinolazepam" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77635" :name "cinolazepam") 
("Chemokine" "ONT:GENE-PROTEIN" :id "FPLX:Chemokine" :name "Chemokine") 
("Celite" "ONT:CHEMICAL" :id "CHEBI:82661" :name "diatomaceous earth") 
("Carnobacteriaceae" "ONT:BACTERIUM" :id "NCIT:C85922" :name "carnobacteriaceae") 
("Carnivora" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C79104" :name "carnivora") 
("Candida" "ONT:FUNGUS" :id "NCIT:C77163" :name "candida") 
("Calu" "ONT:GENE" :id "HGNC:1458" :name "calumenin") 
("Caliciviridae" "ONT:VIRUS" :id "NCIT:C14304" :name "caliciviridae") 
("CSis" "ONT:GENE" :id "NCIT:C51520" :name "PDGFB") 
;("CPEs" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF09367" :name "CpeS") 
("CLx" "ONT:PROTEIN" :id "UP:P14531" :name "Delta-hormotoxin-Cpt1b") 
("CLIPseq" "ONT:PROCESS" :id "EFO:0003143" :name "CLIP-seq") 
("Burkholderiaceae" "ONT:BACTERIUM" :id "NCIT:C85920" :name "burkholderiaceae") 
("BlpI" "ONT:GENE-PROTEIN" :id "NCIT:C29979" :name "antileukoproteinase") 
("BisTris" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C026272" :name "Bistris") 
("Biologicals" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C307" :name "biological agent") 
("Bifidobacterium" "ONT:BACTERIUM" :id "NCIT:C86194" :name "bifidobacterium") 
("Bcell" "ONT:CELL" :id "CO:0000236" :name "B cell") 
("BamHI" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF02923" :name "BamHI") 
("Babesia" "ONT:ORGANISM" :id "NCIT:C122040" :name "babesia") 
("BBSome" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0034464" :name "BBSome") 
("Aves" "ONT:BIRD" :id "NCIT:C14189" :name "aves") 
("Artesunate" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73005" :name "artesunate") 
("Arcobacter" "ONT:BACTERIUM" :id "NCIT:C86152" :name "arcobacter") 
("Aluvia" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C558899" :name "lopinavir-ritonavir drug combination") 
("Alternaria" "ONT:FUNGUS" :id "NCIT:C119320" :name "alternaria") 
("Alphacoronavirus" "ONT:VIRUS" :id "NCIT:C119319" :name "alphacoronavirus") 
("Alg" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62577" :name "antilymphocyte serum") 
("Actinobacteria" "ONT:BACTERIUM" :id "NCIT:C76195" :name "actinobacteria") 
("Actinobacillus" "ONT:BACTERIUM" :id "NCIT:C86097" :name "actinobacillus") 
("Acaca" "ONT:GENE-PROTEIN" :id "HGNC:84" :name "acetyl-CoA carboxylase alpha") 
("AcOH" "ONT:CHEMICAL" :id "CHEBI:15366" :name "acetic acid") 
("zopiclone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C80279" :name "zopiclone") 
("zolmitriptan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47789" :name "zolmitriptan") 
("zika" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C128423" :name "zika virus infection") 
("xylose" "ONT:CHEMICAL" :id "CHEBI:18222" :name "xylose") 
("villitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003110" :name "villitis") 
("vcf" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C2989" :name "DiGeorge syndrome") 
("vars" "ONT:GENE" :id "HGNC:12651" :name "valyl-tRNA synthetase 1") 
("valerate" "ONT:CHEMICAL" :id "CHEBI:31011" :name "valerate") 
("vaccinia" "ONT:VIRUS" :id "NCIT:C14281" :name "vaccinia virus") 
("umifenovir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C152799" :name "umifenovir") 
("uci" "ONT:PROTEIN" :id "UP:P0CG44" :name "Cytolysin Uc-1") 
("ttest" "ONT:PROCEDURE" :id "NCIT:C53231" :name "t-test") 
("tripolyphosphate" "ONT:CHEMICAL" :id "CHEBI:18036" :name "triphosphate(5-)") 
("triethylamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C016162" :name "triethylamine") 
("triamine" "ONT:CHEMICAL" :id "CHEBI:38751" :name "triamine") 
;("trans" "ONT:PROTEIN-FAMILY" :id "XFAM:PF06986" :name "TraN") 
("toremifene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1256" :name "toremifene") 
("tonoplast" "ONT:CELL-PART" :id "GO:0009705" :name "plant-type vacuole membrane") 
("tinct" "ONT:GENE-PROTEIN" :id "UP:P02786" :name "Transferrin receptor protein 1") 
("tilorone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73335" :name "tilorone") 
("tigecycline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72865" :name "tigecycline") 
("tif" "ONT:GENE" :id "HGNC:12446" :name "TYRO3 protein tyrosine kinase") 
("thioglycolate" "ONT:MOLECULE" :id "CHEBI:30066" :name "thioglycolate(1-)") 
("tetramethylsilane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C073196" :name "tetramethylsilane") 
("tert" "ONT:GENE-PROTEIN" :id "HGNC:11730" :name "telomerase reverse transcriptase") 
("taxon" "ONT:ORGANISM" :id "NCIT:C14250" :name "organism") 
("sym" "ONT:GENE" :id "HGNC:22935" :name "symplekin") 
("sulfonyl" "ONT:MOLECULE" :id "CHEBI:29825" :name "sulfonyl group") 
("sulbactam" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61957" :name "sulbactam") 
("stl" "ONT:GENE" :id "NCIT:C97904" :name "RNF217-AS1") 
("stk" "ONT:GENE-PROTEIN" :id "NCIT:C17325" :name "serine/Threonine protein kinase") 
("srv" "ONT:PROTEIN-FAMILY" :id "XFAM:PF10323" :name "7TM GPCR Srv") 
("spermatids" "ONT:CELL" :id "CO:0000018" :name "spermatid") 
("siderophore" "ONT:CHEMICAL" :id "CHEBI:26672" :name "siderophore") 
("sialate" "ONT:CHEMICAL" :id "CHEBI:35418" :name "N-acetylneuraminate") 
("sequencer" "ONT:MEDICAL-INSTRUMENT" :id "EFO:0003739" :name "sequencer") 
("sarkosyl" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C025231" :name "sarkosyl") 
("salmochelin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C000630262" :name "salmochelin") 
("rupintrivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C82255" :name "rupintrivir") 
("rubella" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C85051" :name "rubella infection") 
("rst" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF12174" :name "RST") 
("rotavirus" "ONT:VIRUS" :id "NCIT:C77199" :name "rotavirus") 
;("rna" "ONT:RNA" :id "NCIT:C812" :name "ribonucleic acid") 
("rms" "ONT:CELL-LINE" :id "CVCL:W527" :name "RMS") 
("ribozyme" "ONT:RNA" :id "NCIT:C1292" :name "ribozyme") 
("reversine" "ONT:CHEMICAL" :id "CHEBI:70723" :name "reversine") 
("respirovirus" "ONT:VIRUS" :id "NCIT:C117721" :name "respirovirus") 
("remdesivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C152185" :name "remdesivir") 
("reg" "ONT:GENE-PROTEIN" :id "NCIT:C50964" :name "EXTL3") 
("rdrp" "ONT:GENE-PROTEIN" :id "UP:Q8AZL8" :name "RNA-directed RNA polymerase") 
("protoplasts" "ONT:CELL" :id "CO:0000371" :name "protoplast") 
("protista" "ONT:ORGANISM" :id "NCIT:C77914" :name "protista") 
("propionamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C034666" :name "propionamide") 
("propanoate" "ONT:CHEMICAL" :id "CHEBI:17272" :name "propionate") 
("prokaryote" "ONT:ORGANISM" :id "NCIT:C14263" :name "prokaryote") 
("prodrug" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:50266" :name "prodrug") 
("preset" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05033" :name "pre-SET") 
("preprocess" "ONT:PROCEDURE" :id "NCIT:C64201" :name "preprocess") 
("pos" "ONT:PROTEIN" :id "UP:Q8VCZ9" :name "Hydroxyproline dehydrogenase") 
("polysulfone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C017662" :name "polysulfone P 1700") 
("polyprotein" "ONT:PROTEIN" :id "UP:C1JCT1" :name "Polyprotein") 
("pneumovirus" "ONT:VIRUS" :id "NCIT:C112398" :name "pneumovirus") 
("plasmodesmata" "ONT:CELL-PART" :id "UP:SL-0208" :name "Plasmodesma") 
("pivalate" "ONT:MOLECULE" :id "CHEBI:63894" :name "pivalate") 
("pirlindole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C66428" :name "pirlindole") 
("piperaquine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C87634" :name "piperaquine") 
("piperacillin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62069" :name "piperacillin") 
("pinene" "ONT:MOLECULE" :id "CHEBI:17187" :name "pinene") 
("picosecond" "ONT:TIME-UNIT" :id "UO:0000030" :name "picosecond") 
("phosphocreatine" "ONT:CHEMICAL" :id "CHEBI:17287" :name "N-phosphocreatine") 
("phosphine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C044646" :name "phosphine") 
("phosphide" "ONT:MOLECULE" :id "CHEBI:33468" :name "phosphide(3-)") 
("phenylalanin" "ONT:CHEMICAL" :id "CHEBI:28044" :name "phenylalanine") 
("pgrp" "ONT:GENE" :id "HGNC:8904" :name "peptidoglycan recognition protein 1") 
("percentile" "ONT:PROCEDURE" :id "NCIT:C48919" :name "percentile") 
("perampanel" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C75029" :name "perampanel") 
("pentanedioate" "ONT:CHEMICAL" :id "CHEBI:30921" :name "glutarate(2-)") 
("parvovirus" "ONT:VIRUS" :id "NCIT:C14299" :name "parvovirus") 
("parasitemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0001067" :name "parasitic infection") 
("palivizumab" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2625" :name "palivizumab") 
("ovotransferrin" "ONT:PROTEIN" :id "UP:P56410" :name "Ovotransferrin") 
("ovine" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14273" :name "sheep") 
("oseltamivir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62061" :name "oseltamivir") 
("orthovanadate" "ONT:CHEMICAL" :id "CHEBI:46442" :name "vanadate(3-)") 
("oritavancin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C100708" :name "oritavancin") 
("ophthalaldehyde" "ONT:CHEMICAL" :id "CHEBI:70851" :name "phthalaldehyde") 
("nwk" "ONT:PROTEIN" :id "UP:X2JAU8" :name "Protein nervous wreck {ECO:0000303|PubMed:14980202, ECO:0000303|PubMed:18701694, ECO:0000303|PubMed:21464232}") 
("nucleoside" "ONT:MOLECULE" :id "CHEBI:33838" :name "nucleoside") 
("nucleophile" "ONT:CHEMICAL" :id "CHEBI:59740" :name "nucleophilic reagent") 
("nucleoli" "ONT:CELL-PART" :id "UP:SL-0188" :name "Nucleolus") 
("nsp" "ONT:GENE-PROTEIN" :id "NCIT:C17692" :name "reticulon-1") 
("nos" "ONT:GENE-PROTEIN" :id "FPLX:NOS" :name "NOS") 
("nonactin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C050476" :name "nonactin") 
("nlm" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C82620" :name "national library of medicine") 
("nitroimidazole" "ONT:CHEMICAL" :id "CHEBI:67135" :name "2-nitroimidazole") 
("nitrocefin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76562" :name "nitrocefin") 
("nitazoxanide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47637" :name "nitazoxanide") 
("ninhydrin" "ONT:CHEMICAL" :id "CHEBI:86374" :name "ninhydrin") 
("nelarabine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1704" :name "nelarabine") 
("ncbi" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C45799" :name "national center for biotechnology information") 
("nanostructure" "ONT:MOLECULE" :id "CHEBI:50795" :name "nanostructure") 
("nanosheet" "ONT:MOLECULE" :id "CHEBI:52531" :name "nanosheet") 
("nanomaterials" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C53671" :name "nanomaterials") 
("nae" "ONT:PROTEIN" :id "NCIT:C95815" :name "NEDD8 activating enzyme") 
("mycoplasma" "ONT:BACTERIUM" :id "NCIT:C73540" :name "mycoplasma") 
("mutagen" "ONT:CHEMICAL" :id "CHEBI:25435" :name "mutagen") 
("mssm" "ONT:MOLECULE" :id "CHEBI:16086" :name "mycothione") 
("monad" "ONT:GENE" :id "HGNC:25176" :name "WD repeat domain 92") 
("mle" "ONT:PROTEIN" :id "UP:Q43931" :name "Muconate cycloisomerase 1") 
("microsporidia" "ONT:FUNGUS" :id "NCIT:C123335" :name "microsporidia") 
("microliter" "ONT:VOLUME-UNIT" :id "UO:0000101" :name "microliter") 
("microflora" "ONT:MICROORGANISM" :id "NCIT:C93019" :name "intestinal flora") 
("microbiome" "ONT:MICROORGANISM" :id "NCIT:C68564" :name "microbiome") 
("metronidazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C651" :name "metronidazole") 
("methylamines" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027451" :name "methylamine") 
("methyladenosine" "ONT:MOLECULE" :id "CHEBI:25273" :name "methyladenosine") 
("methicillin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61842" :name "methicillin") 
("metazoan" "ONT:PROTEIN-FAMILY" :id "FA:00289" :name "metazoan subfamily") 
("metazoa" "ONT:INTERNAL-BODY-PART" :id "BTO:0000042" :name "animal") 
("mesalazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29249" :name "mesalamine") 
("meropenem" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1160" :name "meropenem") 
("mblm" "ONT:PROTEIN" :id "UP:O88700" :name "Bloom syndrome protein homolog") 
("mbar" "ONT:GENE-PROTEIN" :id "HGNC:19680" :name "G protein-coupled bile acid receptor 1") 
("maltotriose" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C008317" :name "maltotriose") 
("maltodextrin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C008315" :name "maltodextrin") 
("macrolide" "ONT:MOLECULE" :id "CHEBI:25106" :name "macrolide") 
("lyssavirus" "ONT:VIRUS" :id "NCIT:C112330" :name "lyssavirus") 
("lysostaphin" "ONT:PROTEIN" :id "UP:P10547" :name "Lysostaphin") 
("linezolid" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29158" :name "linezolid") 
("lignocellulose" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C036909" :name "lignocellulose") 
("leishmanin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C032127" :name "leishmanin") 
("lcf" "ONT:CELL-LINE" :id "CVCL:S938" :name "LCF") 
("lat" "ONT:CELL-LINE" :id "CVCL:2101" :name "LAT") 
("laryngotracheitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26735" :name "croup") 
("lapachol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C008252" :name "lapachol") 
("lamina" "ONT:PROTEIN" :id "UP:P13648" :name "Lamin-A") 
("lactimidomycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C077633" :name "lactimidomycin") 
("kaletra" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2096" :name "lopinavir/Ritonavir") 
("jsp" "ONT:CELL-LINE" :id "CVCL:RG68" :name "JSP") 
("jax" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39529" :name "the jackson laboratory cancer center") 
("ivermectin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61796" :name "ivermectin") 
("isopropanol" "ONT:CHEMICAL" :id "CHEBI:17824" :name "propan-2-ol") 
("isopentane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C067038" :name "isopentane") 
("isomaltose" "ONT:CHEMICAL" :id "CHEBI:28189" :name "isomaltose") 
("isocyanide" "ONT:MOLECULE" :id "CHEBI:35353" :name "isocyanide") 
("ing" "ONT:PROTEIN-FAMILY" :id "FA:01856" :name "ING family") 
("immunotherapy" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C308" :name "immunotherapeutic agent") 
("immunosuppressant" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C574" :name "immunosuppressant") 
("igb" "ONT:GENE" :id "NCIT:C97425" :name "CD79B") 
("hyponatremia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "HP:0002902" :name "Hyponatremia") 
("hydrobromide" "ONT:MOLECULE" :id "CHEBI:48367" :name "hydrobromide") 
("hpe" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2162" :name "Holoprosencephaly") 
("hpd" "ONT:GENE-PROTEIN" :id "HGNC:5147" :name "4-hydroxyphenylpyruvate dioxygenase") 
("homoserine" "ONT:CHEMICAL" :id "CHEBI:30653" :name "homoserine") 
("homeodomain" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00046" :name "homeodomain") 
("hoc" "ONT:PROTEIN" :id "UP:P18056" :name "Highly immunogenic outer capsid protein {ECO:0000255|HAMAP-Rule:MF_04116}") 
("herpesviridae" "ONT:VIRUS" :id "NCIT:C14217" :name "herpesvirus") 
("heparins" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C539" :name "heparin") 
("hayfever" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003956" :name "seasonal allergic rhinitis") 
("gtf" "ONT:PROTEIN" :id "GO:0140223" :name "general transcription initiation factor activity") 
("gravitropism" "ONT:BIOLOGICAL-PROCESS" :id "GO:0009630" :name "gravitropism") 
("gov" "ONT:GENE" :id "HGNC:9779" :name "RAB3D, member RAS oncogene family") 
("gonad" "ONT:CELL-LINE" :id "CVCL:WY78" :name "GON") 
("gmt" "ONT:PROTEIN" :id "UP:Q753T9" :name "GDP-mannose transporter") 
("gml" "ONT:GENE" :id "HGNC:4375" :name "glycosylphosphatidylinositol anchored molecule like") 
("glutamyl" "ONT:RESIDUE" :id "CHEBI:32483" :name "glutamic acid residue") 
("genotype" "ONT:PROCEDURE" :id "NCIT:C45447" :name "genotyping") 
("gatan" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05349" :name "GATA-N") 
("gammacoronavirus" "ONT:VIRUS" :id "NCIT:C122313" :name "gammacoronavirus") 
("gallium" "ONT:MOLECULE" :id "CHEBI:49631" :name "gallium atom") 
("galactomannan" "ONT:MOLECULE" :id "CHEBI:27680" :name "galactomannan") 
("furinlike" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00757" :name "furin-like") 
("funisitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C97077" :name "funisitis") 
("ftp" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF07504" :name "FTP") 
("frovatriptan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65772" :name "frovatriptan") 
("fluphenazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47536" :name "fluphenazine") 
("fluorobenzene" "ONT:MOLECULE" :id "CHEBI:5115" :name "monofluorobenzene") 
("firststrand" "ONT:PROCEDURE" :id "NCIT:C150428" :name "first-strand library sequencing") 
("filovirus" "ONT:VIRUS" :id "NCIT:C112031" :name "filoviridae") 
("ferrocyanide" "ONT:MOLECULE" :id "CHEBI:5032" :name "ferrocyanide") 
;("fda" "ONT:PROTEIN" :id "UP:P81543" :name "Zinc-containing ferredoxin A") 
("fasciculin" "ONT:PROTEIN" :id "UP:P25681" :name "Acetylcholinesterase toxin C") 
("eukaryote" "ONT:ORGANISM" :id "NCIT:C25796" :name "eukaryota") 
("eugenol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C75095" :name "eugenol") 
("eubacteria" "ONT:BACTERIUM" :id "NCIT:C86383" :name "eubacterium") 
("ethanedithiol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C031854" :name "1,2-ethanedithiol") 
("etc" "ONT:PROTEIN" :id "UP:P32940" :name "Endothelin-3 receptor") 
("eszopiclone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65545" :name "eszopiclone") 
("est" "ONT:GENE" :id "NCIT:C51214" :name "MAP3K8") 
("erythroleukemia" "ONT:CANCER" :id "EFO:1001955" :name "erythroleukemia") 
("equilin" "ONT:MOLECULE" :id "CHEBI:42309" :name "equilin") 
("enterovirus" "ONT:VIRUS" :id "NCIT:C14203" :name "enterovirus") 
("enterocolitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1001481" :name "enterocolitis") 
("enterobactin" "ONT:CHEMICAL" :id "CHEBI:28855" :name "enterobactin") 
("ele" "ONT:CELL-LINE" :id "CVCL:0C08" :name "EL-E") 
;("edu" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C87662" :name "edoxudine") 
("eclampsia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C87167" :name "eclampsia") 
("echovirus" "ONT:VIRUS" :id "NCIT:C112272" :name "echovirus") 
("dta" "ONT:PROTEIN" :id "GO:0043876" :name "D-threonine aldolase activity") 
("dodecyl" "ONT:MOLECULE" :id "CHEBI:23870" :name "dodecyl group") 
("dna" "ONT:PROCEDURE" :id "NCIT:C135409" :name "deoxyribonucleic acid measurement") 
("dipeptide" "ONT:CHEMICAL" :id "CHEBI:46761" :name "dipeptide") 
("dimetridazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76419" :name "dimetridazole") 
("dichloromethane" "ONT:CHEMICAL" :id "CHEBI:15767" :name "dichloromethane") 
("dibucaine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28984" :name "dibucaine") 
("diazepine" "ONT:MOLECULE" :id "CHEBI:47918" :name "diazepine") 
("desthiobiotin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C004749" :name "desthiobiotin") 
("dengue" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34528" :name "dengue fever") 
("deltacoronavirus" "ONT:VIRUS" :id "NCIT:C122279" :name "deltacoronavirus") 
("daptomycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47470" :name "daptomycin") 
("cysteinyl" "ONT:RESIDUE" :id "CHEBI:32460" :name "cysteine residue") 
("cshl" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C39335" :name "cold spring harbor laboratory cancer center") 
("cpt" "ONT:GENE-PROTEIN" :id "UP:Q56148" :name "Chloramphenicol 3-O phosphotransferase") 
("coronaviridae" "ONT:VIRUS" :id "NCIT:C113205" :name "coronaviridae") 
("comp" "ONT:GENE-PROTEIN" :id "HGNC:2227" :name "cartilage oligomeric matrix protein") 
("collidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C007106" :name "gamma-collidine") 
("coi" "ONT:GENE" :id "NCIT:C128942" :name "MT-CO1") 
("coagulopathy" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C2902" :name "coagulation disorder") 
("clocortolone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61684" :name "clocortolone") 
("citronellol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C007078" :name "citronellol") 
("cinanserin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C83624" :name "cinanserin") 
("cilia" "ONT:CELL-PART" :id "UP:SL-0066" :name "Cilium") 
("chromone" "ONT:MOLECULE" :id "CHEBI:72013" :name "chromone") 
("chorismate" "ONT:CHEMICAL" :id "CHEBI:29748" :name "chorismate(2-)") 
("chemokine" "ONT:GENE-PROTEIN" :id "FPLX:Chemokine" :name "Chemokine") 
("chemoattractant" "ONT:PROTEIN" :id "GO:0042056" :name "chemoattractant activity") 
("cephalosporin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:23066" :name "cephalosporin") 
("cefotaxime" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C354" :name "cefotaxime") 
("cefoperazone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61663" :name "cefoperazone") 
("ccmb" "ONT:PROTEIN-FAMILY" :id "XFAM:PF03379" :name "CcmB") 
("cbs" "ONT:CELL-LINE" :id "CVCL:D298" :name "CBS") 
("cbr" "ONT:GENE-PROTEIN" :id "UP:P21554" :name "Cannabinoid receptor 1") 
("catecholate" "ONT:CHEMICAL" :id "CHEBI:32402" :name "catecholate(2-)") 
("carmofur" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C955" :name "carmofur") 
("carbenicillin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C343" :name "carbenicillin") 
("carbapenem" "ONT:CHEMICAL" :id "CHEBI:46765" :name "carbapenem") 
("capsid" "ONT:PROTEIN" :id "NCIT:C16383" :name "capsid protein") 
("camostat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C73213" :name "camostat") 
("calpeptin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C071482" :name "calpeptin") 
("callose" "ONT:CHEMICAL" :id "CHEBI:37671" :name "(1->3)-beta-D-glucan") 
("cal" "ONT:CELL-LINE" :id "CVCL:E514" :name "CAL") 
("bromoacetonitrile" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C000624721" :name "bromoacetonitrile") 
("bovid" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14323" :name "bovidae") 
("bocavirus" "ONT:VIRUS" :id "NCIT:C127691" :name "bocaparvovirus") 
("bgi" "ONT:CELL-LINE" :id "CVCL:6570" :name "BG1") 
("betamercaptoethanol" "ONT:MOLECULE" :id "CHEBI:41218" :name "mercaptoethanol") 
("betacoronavirus" "ONT:VIRUS" :id "NCIT:C113207" :name "betacoronavirus") 
("betacitronellol" "ONT:CHEMICAL" :id "CHEBI:50462" :name "citronellol") 
("betaamyloid" "ONT:CHEMICAL" :id "CHEBI:64645" :name "amyloid-beta") 
("benzyl" "ONT:MOLECULE" :id "CHEBI:22744" :name "benzyl group") 
("benzodiazepine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:22720" :name "benzodiazepine") 
("bam" "ONT:GENE-PROTEIN" :id "NCIT:C21195" :name "bcl-2-like protein 11") 
("bacteriocin" "ONT:GENE-PROTEIN" :id "UP:P84703" :name "Bacteriocin") 
("bactericide" "ONT:CHEMICAL" :id "CHEBI:33282" :name "antibacterial agent") 
("bacteraemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003033" :name "bacteriemia") 
("azole" "ONT:MOLECULE" :id "CHEBI:68452" :name "azole") 
("azobenzene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C009850" :name "azobenzene") 
("azauridine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C291" :name "6-azauridine") 
("avulavirus" "ONT:VIRUS" :id "NCIT:C117722" :name "avulavirus") 
("ato" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1005" :name "arsenic trioxide") 
("asc" "ONT:GENE-PROTEIN" :id "XFAM:PF00858" :name "ASC") 
("arsenide" "ONT:MOLECULE" :id "CHEBI:29752" :name "arsenide(3-)") 
("archaellum" "ONT:CELL-PART" :id "GO:0097589" :name "archaeal-type flagellum") 
("arbidol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C086979" :name "arbidol") 
("arb" "ONT:PROTEIN" :id "UP:Q54NZ7" :name "Aldose reductase B") 
("aortitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C97085" :name "aortitis") 
("antiserum" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C571" :name "antiserum") 
("antigen" "ONT:CHEMICAL" :id "CHEBI:59132" :name "antigen") 
("anhydrotetracycline" "ONT:CHEMICAL" :id "CHEBI:17146" :name "anhydrotetracycline") 
("aminomethane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027451" :name "methylamine") 
("alphavirus" "ONT:VIRUS" :id "NCIT:C112030" :name "alphavirus") 
("alphacoronavirus" "ONT:VIRUS" :id "NCIT:C119319" :name "alphacoronavirus") 
("allyl" "ONT:MOLECULE" :id "CHEBI:30361" :name "allyl group") 
("allantoin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C74277" :name "allantoin") 
("adipocytokine" "ONT:PROTEIN-FAMILY" :id "NCIT:C123810" :name "adipokine") 
("acetosyringone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C051667" :name "acetosyringone") 
("abaecin" "ONT:PROTEIN" :id "UP:P15450" :name "Abaecin") 
("BGI" "ONT:CELL-LINE" :id "CVCL:6570" :name "BG1") 
("ZIKV" "ONT:VIRUS" :id "NCIT:C128553" :name "zika virus") 
("ZIKA" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C128423" :name "zika virus infection") 
("YFV" "ONT:VIRUS" :id "NCIT:C97156" :name "yellow fever virus") 
("XML" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C157492" :name "xinmailong") 
("WAG" "ONT:CELL-LINE" :id "CVCL:1H01" :name "WAG") 
("VZV" "ONT:VIRUS" :id "NCIT:C71091" :name "varicella zoster virus") 
("VIPR" "ONT:GENE-PROTEIN" :id "UP:Q90308" :name "Vasoactive intestinal polypeptide receptor") 
("VERO" "ONT:CELL-LINE" :id "CVCL:0059" :name "Vero") 
("VCAP" "ONT:CELL-LINE" :id "CVCL:2235" :name "VCaP") 
("UUU" "ONT:MOLECULE" :id "CHEBI:33368" :name "roentgenium atom") 
("UTI" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C50791" :name "urinary tract infection") 
("URD" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C922" :name "uridine") 
("TSV" "ONT:PROTEIN" :id "UP:P46115" :name "Alpha-toxin Ts5") 
("TRIZOL" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C411644" :name "trizol") 
("TREX" "ONT:PROTEIN-FAMILY" :id "FA:01185" :name "TREX family") 
("TMM" "ONT:CELL-LINE" :id "CVCL:1894" :name "TMM") 
("SWNT" "ONT:MOLECULE" :id "CHEBI:50595" :name "single-walled carbon nanotube") 
("SVR" "ONT:CELL-LINE" :id "CVCL:6455" :name "SVR") 
("SSV" "ONT:GENE" :id "NCIT:C51520" :name "PDGFB") 
("SMK" "ONT:PROTEIN" :id "UP:E2S063" :name "Kappa-stichotoxin-Smt1a") 
("SILAC" "ONT:PROCEDURE" :id "NCIT:C161804" :name "stable isotope labeling with amino acids in cell culture") 
("SIAE" "ONT:GENE" :id "HGNC:18187" :name "sialic acid acetylesterase") 
("SHAPE" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C97513" :name "remetinostat") 
("SERM" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1821" :name "selective estrogen receptor modulator") 
("RTI" "ONT:PROTEIN" :id "UP:P80301" :name "Defensin-like protein 4") 
("RNN" "ONT:RNA" :id "HGNC:12324" :name "tRNA-Asn (anticodon GTT) 2-1") 
("RMS" "ONT:CELL-LINE" :id "CVCL:W527" :name "RMS") 
("RCT" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF01137" :name "RTC") 
("PXI" "ONT:PROTEIN" :id "UP:P81863" :name "Pardaxin-1") 
("PWK" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C37429" :name "PWK mouse") 
("PVDF" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C024865" :name "polyvinylidene fluoride") 
("PTFE" "ONT:MOLECULE" :id "CHEBI:53251" :name "poly(tetrafluoroethylene)") 
("PRKN" "ONT:GENE-PROTEIN" :id "HGNC:8607" :name "parkin RBR E3 ubiquitin protein ligase") 
("PRISM" "ONT:GENE" :id "HGNC:9350" :name "PR/SET domain 6") 
("POCA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C033891" :name "ethyl 2-(5-(4-chlorophenyl)pentyl)oxiran-2-carboxylate") 
("PME" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:98261" :name "Progressive myoclonic epilepsy") 
("PKDL" "ONT:GENE" :id "HGNC:9011" :name "polycystin 2 like 1, transient receptor potential cation channel") 
("PISCES" "ONT:CELL-LINE" :id "CVCL:E022" :name "PAE-iPS-12") 
("PIPES" "ONT:CHEMICAL" :id "CHEBI:39033" :name "PIPES") 
("PEF" "ONT:MOLECULE" :id "CHEBI:55310" :name "poly(2,5-ethylene furandicarboxylate)") 
("PBCA" "ONT:CHEMICAL" :id "CHEBI:61239" :name "poly(butyl 2-cyanoacrylate) polymer") 
("PBB" "ONT:CHEMICAL" :id "CHEBI:134049" :name "polybromobiphenyl") 
("PASTA" "ONT:PROTEIN" :id "UP:Q9Y2W3" :name "Proton-associated sugar transporter A") 
("OTOGL" "ONT:GENE" :id "HGNC:26901" :name "otogelin like") 
("OSD" "ONT:PROTEIN-FAMILY" :id "XFAM:PF03392" :name "OS-D") 
("ORI" "ONT:CELL-LINE" :id "CVCL:JE64" :name "Ori-") 
("ORFY" "ONT:PROTEIN" :id "UP:P38943" :name "Uncharacterized transporter CKL_3017") 
("ORFX" "ONT:GENE-PROTEIN" :id "NCIT:C97398" :name "BRD3") 
("NRON" "ONT:RNA" :id "HGNC:37079" :name "non-coding repressor of NFAT") 
("NRCE" "ONT:CELL-LINE" :id "CVCL:9Y58" :name "NRCE") 
("NNN" "ONT:CHEMICAL" :id "NCIT:C44414" :name "nitrosonornicotine") 
("NLLS" "ONT:CHEMICAL" :id "CHEBI:73409" :name "Asn-Leu-Leu-Ser") 
("NICHD" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19754" :name "national institute of child health and human development") 
("NHLBI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C82613" :name "national heart, lung, and blood institute") 
("NEM" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:607" :name "Nemaline myopathy") 
("NDV" "ONT:VIRUS" :id "NCIT:C93023" :name "newcastle disease virus") 
("NCI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19202" :name "national cancer institute") 
("NCBI" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C45799" :name "national center for biotechnology information") 
("MTS" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF05175" :name "MTS") 
("MTK" "ONT:PROTEIN" :id "UP:P25860" :name "Metallothionein-like protein 2A") 
("MSSM" "ONT:MOLECULE" :id "CHEBI:16086" :name "mycothione") 
("MSIR" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C669" :name "morphine sulfate") 
("MSA" "ONT:GENE-PROTEIN" :id "UP:P08997" :name "Malate synthase A") 
("MKS" "ONT:GENE" :id "HGNC:7121" :name "MKS transition zone complex subunit 1") 
("MIAT" "ONT:RNA" :id "HGNC:33425" :name "myocardial infarction associated transcript") 
("MFR" "ONT:GENE-PROTEIN" :id "NCIT:C37271" :name "tyrosine-protein phosphatase non-receptor type substrate 1") 
("MFA" "ONT:PROTEIN-FAMILY" :id "XFAM:PF08842" :name "mfa2") 
("MDMA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61081" :name "3,4-methylenedioxymethamphetamine") 
("MAPE" "ONT:GENE" :id "NCIT:C127929" :name "PRAME") 
("LLI" "ONT:PROTEIN" :id "UP:C0HK42" :name "Lasioglossin-1") 
("LIMD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:254857" :name "Lethal infantile mitochondrial myopathy") 
("LFD" "ONT:CHEMICAL" :id "CHEBI:73571" :name "Leu-Phe-Asp") 
("LDD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:65285" :name "Lhermitte-Duclos disease") 
("LCMS" "ONT:CELL-LINE" :id "CVCL:1655" :name "RERF-LC-MS") 
("LACT" "ONT:PROTEIN-FAMILY" :id "XFAM:PF02450" :name "LCAT") 
("LAC" "ONT:PROTEIN" :id "NCIT:C70620" :name "lupus anticoagulant antibody") 
("KEMI" "ONT:CELL-LINE" :id "CVCL:7199" :name "Kem-BL") 
("IVA" "ONT:CANCER" :id "NCIT:C133425" :name "pathologic stage IVA esophageal adenocarcinoma AJCC v8") 
("IUPAC" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C82878" :name "international union of pure and applied chemistry") 
("IRD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:772" :name "Infantile Refsum disease") 
("IRB" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C16741" :name "institutional review board") 
("IRAV" "ONT:GENE-PROTEIN" :id "HGNC:25649" :name "shiftless antiviral inhibitor of ribosomal frameshifting") 
("INC" "ONT:CELL-LINE" :id "CVCL:QX03" :name "INC") 
("IMG" "ONT:CELL-LINE" :id "CVCL:HC49" :name "IMG") 
("IFIT" "ONT:PROTEIN-FAMILY" :id "FA:01813" :name "IFIT family") 
("IACUC" "ONT:PROFESSIONAL-ORGANIZATION" :id "NCIT:C19487" :name "institutional animal care and use committee") 
("HUCL" "ONT:GENE" :id "HGNC:3314" :name "ELAV like RNA binding protein 3") 
("HTD" "ONT:CELL-LINE" :id "CVCL:C524" :name "1218E") 
("HSV" "ONT:VIRUS" :id "NCIT:C112419" :name "herpes simplex virus") 
("HPIV" "ONT:VIRUS" :id "NCIT:C125641" :name "human parainfluenza virus") 
("HPAI" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C016679" :name "polyacrylamide") 
("HND" "ONT:PROTEIN" :id "UP:P17059" :name "Hydroxyneurosporene desaturase") 
("HHPA" "ONT:CHEMICAL" :id "CHEBI:103210" :name "hexahydrophthalic anhydride") 
("HDV" "ONT:VIRUS" :id "NCIT:C93324" :name "hepatitis D virus") 
("HCOOH" "ONT:CHEMICAL" :id "CHEBI:30751" :name "formic acid") 
("HCC" "ONT:GENE-PROTEIN" :id "UP:Q9NFL6" :name "Hemocyanin C chain") 
("HABA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C001413" :name "HABA") 
("GWAS" "ONT:PROCEDURE" :id "NCIT:C93020" :name "whole genome association study") 
("GLIDE" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C148500" :name "anti-minor histocompatibility complex donor T-lymphocytes") 
("GHA" "ONT:PROTEIN" :id "UP:P12855" :name "Somatotropin-A") 
("GFT" "ONT:CELL-LINE" :id "CVCL:S936" :name "GFT") 
("GDD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:53697" :name "Gnathodiaphyseal dysplasia") 
("GARD" "ONT:CELL-LINE" :id "CVCL:V418" :name "Gard") 
("FSS" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C74029" :name "fentanyl sublingual spray") 
("FSHD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:269" :name "Facioscapulohumeral dystrophy") 
("FPLC" "ONT:PROCEDURE" :id "NCIT:C80368" :name "fast protein liquid chromatography") 
("FNZ" "ONT:GENE-PROTEIN" :id "NCIT:C16581" :name "fibronectin") 
("FCV" "ONT:CHEMICAL" :id "CHEBI:4974" :name "famciclovir") 
("FABD" "ONT:GENE" :id "HGNC:29622" :name "malonyl-CoA-acyl carrier protein transacylase") 
("EVS" "ONT:PROTEIN" :id "UP:C6WFL3" :name "2-epi-valiolone synthase") 
("ERCC" "ONT:PROTEIN-FAMILY" :id "NCIT:C105959" :name "excision repair cross-complementing family") 
("EPYC" "ONT:GENE" :id "HGNC:3053" :name "epiphycan") 
("EDDHA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C011813" :name "ethylenediamine-N,N'-bis(2-hydroxyphenylacetic acid)") 
("EBV" "ONT:VIRUS" :id "NCIT:C14204" :name "epstein-barr virus") 
("EBOV" "ONT:VIRUS" :id "NCIT:C112271" :name "ebola virus") 
("DXB" "ONT:CELL-LINE" :id "CVCL:A435" :name "SK-MEL-93 DX-B") 
("DTP" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C97122" :name "diphtheria toxoid/Tetanus toxoid/Inactivated pertussis vaccine") 
("DTA" "ONT:PROTEIN" :id "GO:0043876" :name "D-threonine aldolase activity") 
("DPSS" "ONT:CHEMICAL" :id "CHEBI:73439" :name "Asp-Pro-Ser-Ser") 
("DPPS" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C038694" :name "dipalmitoylphosphatidylserine") 
("DOPE" "ONT:MOLECULE" :id "CHEBI:60285" :name "dioleoyl phosphatidylethanolamine") 
("DNJ" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:44369" :name "duvoglustat") 
("DMF" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C63670" :name "dimethyl fumarate") 
("DLS" "ONT:PROCEDURE" :id "NCIT:C62329" :name "photon correlation spectroscopy") 
("DIPEA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027070" :name "N,N-diisopropylethylamine") 
("DIEA" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027070" :name "N,N-diisopropylethylamine") 
("DHO" "ONT:CELL-LINE" :id "CVCL:E562" :name "DHO") 
("DFA" "ONT:CHEMICAL" :id "CHEBI:23716" :name "difluoroacetic acid") 
("DCV" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C114981" :name "daclatasvir") 
("DAPI" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C007293" :name "DAPI") 
("DABCO" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C007306" :name "triethylenediamine") 
("CVD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000319" :name "cardiovascular disease") 
("CPS" "ONT:PROTEIN" :id "GO:0004088" :name "carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity") 
("CPMP" "ONT:MOLECULE" :id "CHEBI:59648" :name "precursor Z(1-)") 
("COPAN" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:397725" :name "COASY protein-associated neurodegeneration") 
("CMOS" "ONT:PROTEIN" :id "NCIT:C17327" :name "proto-oncogene serine/Threonine-protein kinase mos") 
("CME" "ONT:CELL-LINE" :id "CVCL:N586" :name "CME-1") 
("CMD" "ONT:GENE-PROTEIN" :id "UP:P20370" :name "4-carboxymuconolactone decarboxylase") 
("CIRB" "ONT:PROTEIN" :id "UP:P56879" :name "Circulin-B") 
("CIGAR" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1813" :name "cigar") 
("CEM" "ONT:CELL-LINE" :id "CVCL:0207" :name "CCRF-CEM") 
("CDV" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1600" :name "cidofovir") 
("CDG" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:137" :name "Congenital disorder of glycosylation") 
("CCC" "ONT:CELL-LINE" :id "CVCL:2426" :name "CRFK") 
("CCB" "ONT:CELL-LINE" :id "CVCL:W096" :name "CCB") 
("CADASIL" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:136" :name "CADASIL") 
("BSR" "ONT:RNA" :id "HGNC:14574" :name "maternally expressed 8, small nucleolar RNA host gene") 
("BSO" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1029" :name "buthionine sulfoximine") 
("BSM" "ONT:CELL-LINE" :id "CVCL:E504" :name "BSM") 
("BSB" "ONT:CELL-LINE" :id "CVCL:S927" :name "BSB") 
("BHK" "ONT:CELL-LINE" :id "CVCL:1914" :name "BHK-21") 
("BHE" "ONT:CELL-LINE" :id "CVCL:0C06" :name "BH-E") 
("BEH" "ONT:MOLECULE" :id "CHEBI:22696" :name "behenoyl group") 
("beagle" "ONT:ORGANISM" :id "NCIT:C53897" :name "beagle") 
("AUC" "ONT:CELL-LINE" :id "CVCL:AV82" :name "AUC") 
("ATV" "ONT:GENE-PROTEIN" :id "NCIT:C21171" :name "nibrin") 
("ASPM" "ONT:GENE" :id "HGNC:19048" :name "abnormal spindle microtubule assembly") 
("APACHE" "ONT:GENE-PROTEIN" :id "UP:Q9UPP5" :name "AP2-interacting clathrin-endocytosis protein") 
("AGI" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C139651" :name "alpha-glucosidase inhibitor") 
("AGB" "ONT:PROTEIN" :id "UP:P35418" :name "Paramyosin") 
("AENA" "ONT:PROTEIN" :id "UP:Q9NJQ2" :name "Delta-actitoxin-Aeq2a") 
("AEG" "ONT:PROTEIN" :id "UP:Q9XSD3" :name "Cysteine-rich secretory protein 1") 
("ABBA" "ONT:GENE" :id "HGNC:25094" :name "MTSS I-BAR domain containing 2") 
))
