(in-package :sparser)


(def-indiv-with-id bio-method "DIGE" "NCIT:C70654" :name "differential In-gel electrophoresis") 
(def-indiv-with-id bio-method "FdR" "NCIT:C64214" :name "false discovery rate") 
(def-indiv-with-id bio-method "Gaussian" "NCIT:C53215" :name "normal distribution") 
(def-indiv-with-id bio-method "LSC" "NCIT:C122170" :name "liquid scintillation counting") 
(def-indiv-with-id bio-method "MACS" "NCIT:C116641" :name "magnetic affinity cell sorting") 
(def-indiv-with-id bio-method "Passage" "NCIT:C54573" :name "passage") 
(def-indiv-with-id bio-method "Page" "NCIT:C16539" :name "polyacrylamide gel electrophoresis") 
(def-indiv-with-id bio-method "Rose" "NCIT:C121991" :name "recognition of outliers by sampling ends") 
(def-indiv-with-id bio-method "XpS" "NCIT:C78871" :name "X-ray photoelectron spectroscopy") 
(def-indiv-with-id bio-method "computational" "NCIT:C19233" :name "computational technique") 
(def-indiv-with-id bio-method "clusterings" "NCIT:C63918" :name "cluster analysis") 
(def-indiv-with-id bio-method "cloning" "NCIT:C16442" :name "cloning") 
(def-indiv-with-id bio-method "centrifugation" "NCIT:C16410" :name "centrifugation") 
(def-indiv-with-id bio-method "electrophoresis" "NCIT:C16536" :name "electrophoresis") 
(def-indiv-with-id bio-method "eigenvalue" "NCIT:C61068" :name "eigenvalue") 
(def-indiv-with-id bio-method "dPCR" "NCIT:C116158" :name "digital array") 
(def-indiv-with-id bio-method "crystallography" "NCIT:C16476" :name "crystallography") 
(def-indiv-with-id bio-method "fluorimetry" "NCIT:C62322" :name "fluorimetry") 
(def-indiv-with-id bio-method "imputation" "NCIT:C80304" :name "statistical imputation") 
(def-indiv-with-id bio-method "hybridization" "NCIT:C16924" :name "nucleic acid hybridization") 
(def-indiv-with-id bio-method "median" "NCIT:C28007" :name "median") 
(def-indiv-with-id bio-method "moth" "NCIT:C81204" :name "mean of other group imputation technique") 
(def-indiv-with-id bio-method "microdissection" "NCIT:C18124" :name "microdissection") 
(def-indiv-with-id bio-method "permutation" "NCIT:C64219" :name "permutation") 
(def-indiv-with-id bio-method "penia" "NCIT:C125952" :name "particle-enhanced nephelometric immunoassay") 
(def-indiv-with-id bio-method "pellet" "NCIT:C45813" :name "pellet formation") 
(def-indiv-with-id bio-method "protonation" "NCIT:C54165" :name "protonation") 
(def-indiv-with-id bio-method "sedimentation" "NCIT:C54178" :name "sedimentation") 
(def-indiv-with-id bio-method "spectrophotometry" "NCIT:C116701" :name "spectrophotometry") 
(def-indiv-with-id bio-method "variance" "NCIT:C48918" :name "variance") 
(def-indiv-with-id bio-method "unmixing" "NCIT:C84381" :name "spectral unmixing") 
(def-indiv-with-id bio-method "HCSs" "EFO:0007550" :name "high content screen") 
(def-indiv-with-id bio-method "RAPD" "EFO:0004167" :name "RAPD") 
(def-indiv-with-id bio-method "cage" "EFO:0004181" :name "cap analysis gene expression") 
(def-indiv-with-id bio-method "genotyping" "EFO:0000750" :name "genotyping") 
(def-indiv-with-id bio-method "inv" "EFO:0004017" :name "inversion") 
(def-indiv-with-id bio-method "pancreatectomy" "EFO:0002581" :name "pancreatectomy") 
(def-indiv-with-id bio-method "vaccination" "EFO:0004292" :name "vaccination") 
(def-indiv-with-id bio-method "transposition" "EFO:0004021" :name "transposition") 
(def-indiv-with-id bio-method "dispersion" "NCIT:C53321" :name "statistical dispersion") 
(def-indiv-with-id bio-method "dosimetry" "NCIT:C15312" :name "radiation dosimetry") 
(def-indiv-with-id bio-method "F-test" "NCIT:C53234" :name "F-test") 
(def-indiv-with-id bio-method "MALLS" "NCIT:C62324" :name "multi-angle laser light scattering") 
(def-indiv-with-id bio-method "alpha-1" "NCIT:C67050" :name "affy alpha1 significance") 
(def-indiv-with-id bio-method "MLPA" "NCIT:C116161" :name "multiplex ligation-dependent probe amplification") 
(def-indiv-with-id bio-method "SDS–PAGE" "NCIT:C18150" :name "sodium dodecylsulfate-polyacrylamide gel electrophoresis") 
(def-indiv-with-id bio-method "alpha2" "NCIT:C67051" :name "affy alpha2 significance") 
(def-indiv-with-id bio-method "cross-correlation" "NCIT:C68833" :name "cross-correlation") 
(def-indiv-with-id bio-method "ESI" "NCIT:C19363" :name "electrospray ionization") 
(def-synonym rt-pcr (:noun "RTPCR")) 
(def-indiv-with-id bio-method "immortalization" "NCIT:C82424" :name "immortalization") 
(def-indiv-with-id bio-method "maxima" "NCIT:C82868" :name "maximum value derivation technique") 
(def-indiv-with-id bio-method "quantile" "NCIT:C48920" :name "quantile") 
(def-indiv-with-id bio-method "quartile" "NCIT:C87306" :name "quartile") 
(def-indiv-with-id bio-method "root-mean-square" "NCIT:C73485" :name "root mean square") 
(def-indiv-with-id bio-method "transgenic" "EFO:0004020" :name "transgenic") 
(def-indiv-with-id bio-method "CABG" "EFO:0003776" :name "coronary artery bypass") 
(def-indiv-with-id bio-method "Transfection" "EFO:0000726" :name "transfection") 
(def-indiv-with-id bio-method "MNase" "EFO:0004177" :name "Micrococcal Nuclease digestion") 
(def-indiv-with-id bio-method "duplication" "EFO:0004015" :name "duplication") 
(def-indiv-with-id bio-method "hysterectomy" "EFO:0003881" :name "hysterectomy") 