(in-package :sparser)


(def-family-with-id "PMG" "FA:02893" :name "PMG family") 
(def-family-with-id "RRXRR" "XFAM:PF14239" :name "RRXRR") 
(def-family-with-id "GLOX" "GO:0046569" :name "glyoxal oxidase activity") 
(def-family-with-id "RABGGTASE" "GO:0004663" :name "Rab geranylgeranyltransferase activity") 
(def-family-with-id "HPAT" "GO:1990585" :name "hydroxyproline O-arabinosyltransferase activity") 
(def-family-with-id "HEPN" "XFAM:PF05168" :name "HEPN") 
(def-family-with-id "SEFIR" "XFAM:PF08357" :name "SEFIR") 
(def-family-with-id "SLY" "XFAM:PF12485" :name "SLY") 
(def-family-with-id "TRAO" "XFAM:PF10626" :name "TraO") 
(def-family-with-id "CAMS" "XFAM:PF07537" :name "CamS") 
(def-family-with-id "DART" "XFAM:PF14487" :name "DarT") 
(def-family-with-id "DAX" "XFAM:PF00778" :name "DIX") 
(def-family-with-id "PSIA" "XFAM:PF06952" :name "PsiA") 
(def-family-with-id "HLADR" "FPLX:HLA_DR" :name "HLA-DR") 
(def-family-with-id "ISPA" "XFAM:PF04279" :name "IspA") 
(def-family-with-id "MRJP" "XFAM:PF03022" :name "MRJP") 
(def-family-with-id "OGRE" "XFAM:PF00876" :name "innexin") 
(def-family-with-id "NMUR" "GO:0001607" :name "neuromedin U receptor activity") 
(def-family-with-id "CRISP" "FPLX:CRISP" :name "CRISP") 
(def-family-with-id "HRCA" "XFAM:PF01628" :name "HrcA") 
(def-family-with-id "DMRT" "FA:00964" :name "DMRT family") 
(def-family-with-id "ABCF" "FA:00054" :name "ABCF family") 
(def-family-with-id "ACDC" "XFAM:PF14733" :name "ACDC") 
(def-family-with-id "TAPS" "FPLX:TAP" :name "TAP") 
(def-family-with-id "YIDD" "XFAM:PF01809" :name "YidD") 
(def-family-with-id "SAND" "XFAM:PF01342" :name "SAND") 
(def-family-with-id "ODH" "GO:0047830" :name "D-octopine dehydrogenase activity") 
(def-family-with-id "TRAV" "XFAM:PF09676" :name "TraV") 
(def-family-with-id "PWI" "XFAM:PF01480" :name "PWI") 
(def-family-with-id "SPOV" "XFAM:PF08183" :name "SpoV") 
(def-family-with-id "CSGA" "XFAM:PF17334" :name "CsgA") 
(def-family-with-id "LTRA" "XFAM:PF06772" :name "LtrA") 
(def-family-with-id "NIFT" "XFAM:PF06988" :name "NifT") 
(def-family-with-id "NODS" "XFAM:PF05401" :name "NodS") 
(def-family-with-id "STBA" "XFAM:PF06406" :name "StbA") 
(def-family-with-id "TRAE" "XFAM:PF05309" :name "TraE") 
(def-family-with-id "WTF" "XFAM:PF03303" :name "WTF") 
(def-family-with-id "CTNI" "FPLX:Troponin_C" :name "Troponin-C") 
(def-family-with-id "EPHA" "NCIT:C123797" :name "ephA receptor family") 
(def-family-with-id "PNMA" "FA:02896" :name "PNMA family") 
(def-family-with-id "PALP" "XFAM:PF00291" :name "PALP") 
(def-family-with-id "DEHI" "XFAM:PF10778" :name "DehI") 
(def-family-with-id "PYG" "FPLX:PYG" :name "PYG") 
(def-family-with-id "SUF" "XFAM:PF05843" :name "suf") 
(def-family-with-id "AMIGO" "FA:01834" :name "AMIGO family") 
(def-family-with-id "CTI" "XFAM:PF06934" :name "CTI") 
(def-family-with-id "LPAR" "FPLX:LPAR" :name "LPAR") 
(def-family-with-id "ACDP" "FA:00064" :name "ACDP family") 
(def-family-with-id "GATS" "FA:01477" :name "GATS family") 
(def-family-with-id "IRG" "FA:01883" :name "IRG family") 
(def-family-with-id "NAO" "GO:0052664" :name "nitroalkane oxidase activity") 
(def-family-with-id "SRU" "XFAM:PF10322" :name "7TM GPCR Sru") 
(def-family-with-id "SAPK" "GO:0016909" :name "SAP kinase activity") 
(def-family-with-id "CRED" "XFAM:PF06123" :name "CreD") 
(def-family-with-id "RVT" "XFAM:PF00078" :name "RVT 1") 
(def-family-with-id "DAAD" "XFAM:PF18752" :name "DAAD") 
(def-family-with-id "ZUFSP" "FA:05525" :name "ZUFSP subfamily") 
(def-family-with-id "NIND" "XFAM:PF17466" :name "NinD") 
(def-family-with-id "ESCRTIII" "XFAM:PF03357" :name "snf7") 
(def-family-with-id "STG" "XFAM:PF15809" :name "STG") 
(def-family-with-id "DZR" "XFAM:PF12773" :name "DZR") 
(def-family-with-id "OEH" "GO:0008684" :name "2-oxopent-4-enoate hydratase activity") 
(def-family-with-id "CREA" "XFAM:PF05981" :name "CreA") 
(def-family-with-id "EHD" "FA:05284" :name "EHD subfamily") 
(def-family-with-id "MMPL" "XFAM:PF03176" :name "MMPL") 
(def-family-with-id "TYA" "XFAM:PF01021" :name "TYA") 
(def-family-with-id "CAPRIN" "FA:00458" :name "caprin family") 
(def-family-with-id "STEAP" "FA:03847" :name "STEAP family") 
(def-family-with-id "CALCOCO" "FA:00438" :name "CALCOCO family") 
(def-family-with-id "MAPEG" "FA:02175" :name "MAPEG family") 
(def-family-with-id "SERINC" "XFAM:PF03348" :name "serinc") 
(def-family-with-id "SIRA" "XFAM:PF10747" :name "SirA") 
(def-family-with-id "DCTM" "XFAM:PF06808" :name "DctM") 
(def-family-with-id "UPL" "FA:04525" :name "UPL family") 
(def-family-with-id "FXYD" "FA:01399" :name "FXYD family") 
(def-family-with-id "ABCD" "FA:00051" :name "ABCD family") 
(def-family-with-id "DHHC" "XFAM:PF01529" :name "DHHC") 
(def-family-with-id "DSRB" "XFAM:PF10781" :name "DSRB") 
(def-family-with-id "NBPF" "FA:02423" :name "NBPF family") 
(def-family-with-id "CIF" "XFAM:PF16374" :name "CIF") 
(def-family-with-id "DCU" "XFAM:PF03605" :name "DcuA DcuB") 
(def-family-with-id "NADC" "FA:03637" :name "NADC subfamily") 
(def-family-with-id "PCG" "NCIT:C118479" :name "polycomb-group protein") 
(def-family-with-id "MUSTANG" "FA:02384" :name "MUSTANG family") 
(def-family-with-id "SOI" "GO:0018846" :name "styrene-oxide isomerase activity") 
(def-family-with-id "AMOC" "XFAM:PF04896" :name "AmoC") 
(def-family-with-id "MCM" "FPLX:MCM" :name "MCM") 
(def-family-with-id "ROR" "FPLX:ROR" :name "ROR") 
(def-family-with-id "VWD" "XFAM:PF00094" :name "VWD") 
(def-family-with-id "SERCA" "FPLX:SERCA" :name "SERCA") 
(def-family-with-id "SLCO" "NCIT:C107150" :name "organic anion transporter protein") 
(def-family-with-id "calcipressin" "XFAM:PF04847" :name "calcipressin") 
(def-family-with-id "sumt" "GO:0004851" :name "uroporphyrin-III C-methyltransferase activity") 
(def-family-with-id "tela" "XFAM:PF05816" :name "TelA") 
(def-family-with-id "multipass" "UP:SL-9909" :name "Multi-pass membrane protein") 
(def-family-with-id "nfe" "FPLX:NFE" :name "NFE") 
(def-family-with-id "multiubiquitin" "XFAM:PF14452" :name "multi ubiq") 
(def-family-with-id "pertactin" "XFAM:PF03212" :name "pertactin") 
(def-family-with-id "gastrokine" "FA:01473" :name "gastrokine family") 
(def-family-with-id "gliadin" "XFAM:PF13016" :name "gliadin") 
(def-family-with-id "apamin" "XFAM:PF17454" :name "bee toxin") 
(def-family-with-id "ano" "FPLX:ANO" :name "ANO") 
(def-family-with-id "carboxylesterases" "FPLX:Carboxylesterase" :name "Carboxylesterase") 
(def-family-with-id "mitoribosome" "FPLX:Mitochondrial_Ribosome" :name "Mitochondrial-Ribosome") 
(def-family-with-id "eurl" "FA:01177" :name "EURL family") 
(def-family-with-id "satd" "XFAM:PF16264" :name "SatD") 
(def-family-with-id "epsin" "FPLX:EPN" :name "EPN") 
(def-family-with-id "nana" "FA:00943" :name "nanA subfamily") 
(def-family-with-id "rrmj" "FA:02275" :name "rrmJ family") 
(def-family-with-id "lunapark" "FA:02129" :name "lunapark family") 
(def-family-with-id "otubain" "XFAM:PF10275" :name "peptidase C65") 
(def-family-with-id "chemorepellant" "GO:0045499" :name "chemorepellent activity") 
(def-family-with-id "lipin" "FA:02100" :name "lipin family") 
(def-family-with-id "dtw" "FA:01020" :name "DTW family") 
(def-family-with-id "secretoglobin" "FA:03544" :name "secretoglobin family") 
(def-family-with-id "olf" "XFAM:PF02191" :name "OLF") 
(def-family-with-id "zein" "XFAM:PF01559" :name "zein") 
(def-family-with-id "sidekick" "FA:05345" :name "sidekick family") 
(def-family-with-id "veg" "XFAM:PF06257" :name "VEG") 
(def-family-with-id "dddd" "XFAM:PF10161" :name "DDDD") 
(def-family-with-id "tantalus" "XFAM:PF15386" :name "tantalus") 
(def-family-with-id "metalloenzyme" "XFAM:PF01676" :name "metalloenzyme") 
(def-family-with-id "frigida" "XFAM:PF07899" :name "frigida") 
(def-family-with-id "amylases" "GO:0016160" :name "amylase activity") 
(def-family-with-id "baseplate" "XFAM:PF16774" :name "baseplate") 
(def-family-with-id "MobC" "XFAM:PF05713" :name "MobC") 
(def-family-with-id "NqrA" "XFAM:PF05896" :name "NQRA") 
(def-family-with-id "TroA" "XFAM:PF01297" :name "ZnuA") 
(def-family-with-id "Yihi" "XFAM:PF04220" :name "YihI") 
(def-family-with-id "ZnuA" "XFAM:PF01297" :name "ZnuA") 
(def-family-with-id "EnvZ" "GO:0004673" :name "protein histidine kinase activity") 
(def-family-with-id "Dispanin" "XFAM:PF04505" :name "CD225") 
(def-family-with-id "pmoA" "XFAM:PF14100" :name "PmoA") 
(def-family-with-id "citG" "XFAM:PF01874" :name "CitG") 
(def-family-with-id "spoIIE" "XFAM:PF07228" :name "SpoIIE") 
(def-family-with-id "spoVG" "XFAM:PF04026" :name "SpoVG") 
(def-family-with-id "Smaug" "FA:03683" :name "SMAUG family") 
(def-family-with-id "LptC" "XFAM:PF06835" :name "LptC") 
(def-family-with-id "LptD" "XFAM:PF04453" :name "LptD") 
(def-family-with-id "LptE" "XFAM:PF04390" :name "LptE") 
(def-family-with-id "Elo" "FA:01093" :name "ELO family") 
(def-family-with-id "orfA" "XFAM:PF17495" :name "OrfA") 
(def-family-with-id "McrBC" "XFAM:PF10117" :name "McrBC") 
(def-family-with-id "SmpB" "XFAM:PF01668" :name "SmpB") 
(def-family-with-id "Coe" "FA:00663" :name "COE family") 
(def-family-with-id "Gbeta" "FPLX:G_beta" :name "G-beta") 
(def-family-with-id "pETG" "XFAM:PF02529" :name "PetG") 
(def-family-with-id "vanZ" "XFAM:PF04892" :name "VanZ") 
(def-family-with-id "GidA" "XFAM:PF01134" :name "GIDA") 
(def-family-with-id "Vaca" "XFAM:PF02691" :name "VacA") 
(def-family-with-id "rplB" "XFAM:PF04390" :name "LptE") 
(def-family-with-id "Sula" "XFAM:PF03846" :name "SulA") 
(def-family-with-id "cAPN" "FPLX:CAPN" :name "CAPN") 
(def-family-with-id "TRAb" "XFAM:PF01963" :name "TraB") 
(def-family-with-id "pspB" "XFAM:PF06667" :name "PspB") 
(def-family-with-id "CsIV" "XFAM:PF10972" :name "CsiV") 
(def-family-with-id "waaY" "XFAM:PF06176" :name "WaaY") 
(def-family-with-id "LcrV" "XFAM:PF04792" :name "LcrV") 
(def-family-with-id "XylT" "FPLX:GCNT" :name "GCNT") 
(def-family-with-id "DsbC" "XFAM:PF11412" :name "DsbC") 
(def-family-with-id "DsbD" "XFAM:PF02683" :name "DsbD") 
(def-family-with-id "Kdo" "XFAM:PF06293" :name "kdo") 
(def-family-with-id "uspB" "XFAM:PF10625" :name "UspB") 
(def-family-with-id "UvsY" "XFAM:PF11056" :name "UvsY") 
(def-family-with-id "DapA" "FA:05125" :name "dapA family") 
(def-family-with-id "Maue" "XFAM:PF07291" :name "MauE") 
(def-family-with-id "yjbH" "XFAM:PF06082" :name "YjbH") 
(def-family-with-id "ermC" "XFAM:PF06308" :name "ErmC") 
(def-family-with-id "secM" "XFAM:PF06558" :name "SecM") 
(def-family-with-id "Parm" "FA:02658" :name "PARM family") 
(def-family-with-id "Dil" "XFAM:PF01843" :name "DIL") 
(def-family-with-id "RyDEN" "FA:04414" :name "RyDEN family") 
(def-family-with-id "psaF" "XFAM:PF17550" :name "PsaF") 
(def-family-with-id "TrmB" "FA:02286" :name "trmB family") 
(def-family-with-id "Ulp" "GO:0016929" :name "SUMO-specific protease activity") 
(def-family-with-id "fPL" "XFAM:PF09758" :name "FPL") 
(def-family-with-id "DsrD" "XFAM:PF08679" :name "DsrD") 
(def-family-with-id "PrtP" "XFAM:PF01366" :name "PRTP") 
(def-family-with-id "Vmethyltransf" "XFAM:PF01660" :name "vmethyltransf") 
(def-family-with-id "hlyC" "XFAM:PF02794" :name "HlyC") 
(def-family-with-id "traT" "XFAM:PF05818" :name "TraT") 
(def-family-with-id "XFp" "XFAM:PF03894" :name "XFP") 
(def-family-with-id "Gypsy" "XFAM:PF07253" :name "gypsy") 
(def-family-with-id "XendoU" "XFAM:PF09412" :name "XendoU") 
(def-family-with-id "tRBC" "XFAM:PF04956" :name "TrbC") 
(def-family-with-id "FliW" "XFAM:PF02623" :name "FliW") 
(def-family-with-id "VacJ" "XFAM:PF04333" :name "MlaA") 
(def-family-with-id "RecD" "FA:05373" :name "recD family") 
(def-family-with-id "CsgG" "XFAM:PF03783" :name "CsgG") 
(def-family-with-id "Ftsj" "XFAM:PF01728" :name "FtsJ") 
(def-family-with-id "LuxS" "XFAM:PF02664" :name "LuxS") 
(def-family-with-id "Hmd" "XFAM:PF03201" :name "HMD") 
(def-family-with-id "Sarg" "FA:03500" :name "SARG family") 
(def-family-with-id "asIc" "FPLX:ASIC" :name "ASIC") 
(def-family-with-id "AspRS" "XFAM:PF17641" :name "ASPRs") 
(def-family-with-id "Wal" "FA:04611" :name "WAL family") 
(def-family-with-id "igaA" "XFAM:PF07095" :name "IgaA") 
(def-family-with-id "sMAP" "FA:03680" :name "SMAP family") 
(def-family-with-id "Chek" "FPLX:CHEK" :name "CHEK") 
(def-family-with-id "TssC" "XFAM:PF17541" :name "TssC") 
(def-family-with-id "ubiA" "XFAM:PF01040" :name "UbiA") 
(def-family-with-id "DOCs" "GO:0016210" :name "naringenin-chalcone synthase activity") 
(def-family-with-id "Rhat" "XFAM:PF06379" :name "RhaT") 
(def-family-with-id "rOmpB" "XFAM:PF12334" :name "rOmpB") 
(def-family-with-id "bSSS" "XFAM:PF13991" :name "BssS") 
(def-family-with-id "Tetr" "XFAM:PF13972" :name "TetR") 
(def-family-with-id "Merc" "XFAM:PF03203" :name "MerC") 
(def-family-with-id "MoAA" "FA:02332" :name "moaA family") 
(def-family-with-id "mgrB" "XFAM:PF13998" :name "MgrB") 
(def-family-with-id "HAUs" "FPLX:Augmin" :name "Augmin") 
(def-family-with-id "Merr" "XFAM:PF00376" :name "MerR") 
(def-family-with-id "Birnaviridae" "XFAM:PF04197" :name "birna RdRp") 
(def-family-with-id "Schlafen" "FA:03514" :name "schlafen family") 
(def-family-with-id "Cornichon" "FA:00740" :name "cornichon family") 
(def-family-with-id "FlaA" "XFAM:PF04620" :name "FlaA") 
(def-family-with-id "Theta" "FA:01676" :name "theta family") 
(def-family-with-id "MQo" "XFAM:PF06039" :name "mqo") 
(def-family-with-id "cCn" "FA:00517" :name "CCN family") 
(def-family-with-id "BiMC" "FA:01966" :name "bimC subfamily") 
(def-family-with-id "CAGs" "XFAM:PF16707" :name "CagS") 
(def-family-with-id "Popeye" "FA:02917" :name "popeye family") 
(def-family-with-id "Ppase" "FA:02995" :name "PPase family") 
(def-family-with-id "tSNARE" "GO:0005484" :name "SNAP receptor activity") 
(def-family-with-id "Alex" "FA:00152" :name "ALEX family") 
(def-family-with-id "FimA" "XFAM:PF16970" :name "FimA") 