(in-package :sparser)


(def-indiv-with-id rna "sgRNA" "NCIT:C95952" :name "guide RNA") 
(def-indiv-with-id rna "pGADT" "HGNC:53266" :name "PCCA divergent transcript") 
(def-indiv-with-id rna "ncsiRNA" "NCIT:C26549" :name "untranslated RNA") 
(def-indiv-with-id rna "nTTT" "HGNC:7499" :name "mitochondrially encoded tRNA-Thr (ACN)") 
(def-indiv-with-id rna "Trang" "HGNC:7486" :name "mitochondrially encoded tRNA-Gly (GGN)") 
(def-indiv-with-id rna "SymAtlas" "HGNC:25811" :name "ASMTL antisense RNA 1") 
(def-indiv-with-id rna "Sanaria" "HGNC:34330" :name "small NF90 (ILF3) associated RNA I") 
(def-indiv-with-id rna "Linbro" "HGNC:43773" :name "long intergenic non-protein coding RNA, regulator of reprogramming") 
(def-indiv-with-id rna "Larisa" "HGNC:40992" :name "lncRNA upregulator of antiviral response interferon signaling") 
(def-indiv-with-id rna "Bokusui" "HGNC:35125" :name "BOK antisense RNA 1") 
(def-indiv-with-id rna "Bagos" "HGNC:40144" :name "CFTR antisense RNA 1") 
(def-indiv-with-id rna "limma" "HGNC:7499" :name "mitochondrially encoded tRNA-Thr (ACN)") 
(def-indiv-with-id rna "VRN" "HGNC:12654" :name "vault RNA 1-1") 
(def-indiv-with-id rna "SYSRA" "NCIT:C95954" :name "transfer-messenger RNA") 
(def-indiv-with-id rna "SNG" "HGNC:24872" :name "GNAS antisense RNA 1") 
(def-indiv-with-id rna "PCSIRT" "HGNC:54485" :name "prostate cancer expressed EZH2 associated transcript") 
(def-indiv-with-id rna "PARSRR" "HGNC:50552" :name "PTGS2 antisense NFKB1 complex-mediated expression regulator RNA") 
(def-indiv-with-id rna "HANV" "HGNC:37192" :name "long intergenic non-protein coding RNA 184") 
(def-indiv-with-id rna "ECLIA" "HGNC:54482" :name "EGFR interacting lncRNA") 