(in-package :sparser)


(def-indiv-with-id unit-of-measure "angstrom" "UO:0000019" :name "angstrom") 
(def-indiv-with-id unit-of-measure "nanometer" "UO:0000018" :name "nanometer") 
(def-indiv-with-id unit-of-measure "micrometer" "UO:0000017" :name "micrometer") 
(def-indiv-with-id unit-of-measure "Gray" "UO:0000134" :name "Gray") 
(def-indiv-with-id unit-of-measure "NSV" "UO:0000144" :name "nanosievert" :maintain-case t) 
(def-indiv-with-id unit-of-measure "Pascal" "UO:0000110" :name "pascal") 
(def-indiv-with-id unit-of-measure "Tesla" "UO:0000228" :name "tesla") 
(def-indiv-with-id unit-of-measure "Weber" "UO:0000226" :name "weber") 
(def-indiv-with-id unit-of-measure "amol" "UO:0000044" :name "attomole") 
(def-indiv-with-id unit-of-measure "mGy" "UO:0000142" :name "milligray" :maintain-case t) 
(def-indiv-with-id unit-of-measure "mCi" "UO:0000145" :name "millicurie" :maintain-case t) 
(def-indiv-with-id unit-of-measure "lux" "UO:0000116" :name "lux" :maintain-case t) 
(def-indiv-with-id unit-of-measure "kbps" "UO:0000328" :name "kilobasepair") 
(def-indiv-with-id unit-of-measure "nanomolar" "UO:0000065" :name "nanomolar") 
(def-indiv-with-id unit-of-measure "molar" "UO:0000062" :name "molar") 
(def-indiv-with-id unit-of-measure "millimolar" "UO:0000063" :name "millimolar") 
(def-indiv-with-id unit-of-measure "micromolar" "UO:0000064" :name "micromolar") 
(def-indiv-with-id unit-of-measure "rad" "UO:0000135" :name "rad" :maintain-case t) 
(def-indiv-with-id unit-of-measure "ppm" "UO:0000169" :name "parts per million" :maintain-case t) 
(def-indiv-with-id unit-of-measure "ppb" "UO:0000170" :name "parts per billion" :maintain-case t) 
(def-indiv-with-id unit-of-measure "picomolar" "UO:0000066" :name "picomolar") 
(def-indiv-with-id unit-of-measure "umol" "UO:0000039" :name "micromole") 
(def-indiv-with-id unit-of-measure "femtoliter" "UO:0000104" :name "femtoliter") 
(def-indiv-with-id unit-of-measure "nanoliter" "UO:0000102" :name "nanoliter") 
(def-indiv-with-id unit-of-measure "picoliter" "UO:0000103" :name "picoliter") 
(def-indiv-with-id unit-of-measure "picogram" "UO:0000025" :name "picogram") 
(def-indiv-with-id unit-of-measure "Gram" "UO:0000021" :name "gram") 
(def-indiv-with-id unit-of-measure "nanogram" "UO:0000024" :name "nanogram") 
(def-indiv-with-id unit-of-measure "Siemens" "UO:0000264" :name "siemens") 
(def-indiv-with-id unit-of-measure "fmol" "UO:0000043" :name "femtomole") 
(def-indiv-with-id unit-of-measure "mmHg" "UO:0000272" :name "millimetres of mercury") 
(def-indiv-with-id unit-of-measure "picomole" "UO:0000042" :name "picomole") 