(in-package :sparser)


(def-indiv-with-id unit-of-measure "VOLT" "UO:0000218" :name "volt") 
(def-indiv-with-id unit-of-measure "CWT" "UO:0010037" :name "hundredweight" :maintain-case t) 
(def-indiv-with-id unit-of-measure "NGY" "UO:0000143" :name "nanogray" :maintain-case t) 
(def-indiv-with-id unit-of-measure "USV" "UO:0000139" :name "microsievert" :maintain-case t) 
(def-indiv-with-id unit-of-measure "DPS" "UO:0000216" :name "disintegrations per second" :maintain-case t) 
(def-indiv-with-id unit-of-measure "PERCH" "UO:0010023" :name "perch") 
(def-indiv-with-id unit-of-measure "tbsp" "UO:0010042" :name "tablespoon") 
(def-indiv-with-id unit-of-measure "micrometre" "UO:0000017" :name "micrometer") 
(def-indiv-with-id unit-of-measure "millisiemens" "UO:0010002" :name "millisiemens") 
(def-indiv-with-id unit-of-measure "kda" "UO:0000222" :name "kilodalton" :maintain-case t) 
(def-indiv-with-id unit-of-measure "kvh" "UO:0000230" :name "kilovolt-hour" :maintain-case t) 
(def-indiv-with-id unit-of-measure "femtolitre" "UO:0000104" :name "femtoliter") 
(def-indiv-with-id unit-of-measure "nanometre" "UO:0000018" :name "nanometer") 
(def-indiv-with-id unit-of-measure "deciliter" "UO:0000209" :name "deciliter") 
(def-indiv-with-id unit-of-measure "nls" "UO:0000102" :name "nanoliter" :maintain-case t) 
(def-indiv-with-id unit-of-measure "Becquerel" "UO:0000132" :name "becquerel") 
(def-indiv-with-id unit-of-measure "Amu" "UO:0000221" :name "dalton" :maintain-case t) 
(def-indiv-with-id unit-of-measure "Curie" "UO:0000133" :name "curie") 
(def-indiv-with-id unit-of-measure "Mil" "UO:0010012" :name "thou" :maintain-case t) 