(in-package :sparser)


(def-indiv-with-id drug "AGI" "NCIT:C139651" :name "alpha-glucosidase inhibitor" :no-plural t) 
(def-indiv-with-id drug "CIGAR" "NCIT:C1813" :name "cigar" :no-plural t) 
(def-indiv-with-id drug "DABCO" "MESH:C007306" :name "triethylenediamine" :no-plural t) 
(def-indiv-with-id drug "DAPI" "MESH:C007293" :name "DAPI" :no-plural t) 
(def-indiv-with-id drug "DCV" "NCIT:C114981" :name "daclatasvir" :no-plural t) 
(def-indiv-with-id drug "DIEA" "MESH:C027070" :name "N,N-diisopropylethylamine" :no-plural t) 
(def-indiv-with-id drug "DIPEA" "MESH:C027070" :name "N,N-diisopropylethylamine" :no-plural t) 
(def-indiv-with-id drug "DMF" "NCIT:C63670" :name "dimethyl fumarate" :no-plural t) 
(def-indiv-with-id drug "DNJ" "CHEBI:44369" :name "duvoglustat" :no-plural t) 
(def-indiv-with-id drug "DPPS" "MESH:C038694" :name "dipalmitoylphosphatidylserine" :no-plural t) 
(def-indiv-with-id drug "DTP" "NCIT:C97122" :name "diphtheria toxoid/Tetanus toxoid/Inactivated pertussis vaccine" :no-plural t) 
(def-indiv-with-id drug "EDDHA" "MESH:C011813" :name "ethylenediamine-N,N'-bis(2-hydroxyphenylacetic acid)" :no-plural t) 
(def-indiv-with-id drug "FSS" "NCIT:C74029" :name "fentanyl sublingual spray" :no-plural t) 
(def-indiv-with-id drug "GLIDE" "NCIT:C148500" :name "anti-minor histocompatibility complex donor T-lymphocytes" :no-plural t) 
(def-indiv-with-id drug "HABA" "MESH:C001413" :name "HABA" :no-plural t) 
(def-indiv-with-id drug "HPAI" "MESH:C016679" :name "polyacrylamide" :no-plural t) 
(def-indiv-with-id drug "MDMA" "NCIT:C61081" :name "3,4-methylenedioxymethamphetamine" :no-plural t) 
(def-indiv-with-id drug "MSIR" "NCIT:C669" :name "morphine sulfate" :no-plural t) 
(def-indiv-with-id drug "POCA" "MESH:C033891" :name "ethyl 2-(5-(4-chlorophenyl)pentyl)oxiran-2-carboxylate" :no-plural t) 
(def-indiv-with-id drug "PVDF" "MESH:C024865" :name "polyvinylidene fluoride" :no-plural t) 
(def-indiv-with-id drug "SERM" "NCIT:C1821" :name "selective estrogen receptor modulator" :no-plural t) 
(def-indiv-with-id drug "SHAPE" "NCIT:C97513" :name "remetinostat" :no-plural t) 
(def-indiv-with-id drug "URD" "NCIT:C922" :name "uridine" :no-plural t) 
(def-indiv-with-id drug "XML" "NCIT:C157492" :name "xinmailong" :no-plural t) 
(def-indiv-with-id drug "acetosyringone" "MESH:C051667" :name "acetosyringone" :no-plural t) 
(def-indiv-with-id drug "allantoin" "NCIT:C74277" :name "allantoin" :no-plural t) 
(def-indiv-with-id drug "aminomethane" "MESH:C027451" :name "methylamine" :no-plural t) 
(def-indiv-with-id drug "antiserum" "NCIT:C571" :name "antiserum" :no-plural t) 
(def-indiv-with-id drug "arbidol" "MESH:C086979" :name "arbidol" :no-plural t) 
(def-indiv-with-id drug "azauridine" "NCIT:C291" :name "6-azauridine" :no-plural t) 
(def-indiv-with-id drug "azobenzene" "MESH:C009850" :name "azobenzene" :no-plural t) 
(def-indiv-with-id drug "benzodiazepine" "CHEBI:22720" :name "benzodiazepine" :no-plural t) 
(def-indiv-with-id drug "bromoacetonitrile" "MESH:C000624721" :name "bromoacetonitrile" :no-plural t) 
(def-indiv-with-id drug "calpeptin" "MESH:C071482" :name "calpeptin" :no-plural t) 
(def-indiv-with-id drug "camostat" "NCIT:C73213" :name "camostat" :no-plural t) 
(def-indiv-with-id drug "carbenicillin" "NCIT:C343" :name "carbenicillin" :no-plural t) 
(def-indiv-with-id drug "carmofur" "NCIT:C955" :name "carmofur" :no-plural t) 
(def-indiv-with-id drug "cefoperazone" "NCIT:C61663" :name "cefoperazone" :no-plural t) 
(def-indiv-with-id drug "cefotaxime" "NCIT:C354" :name "cefotaxime" :no-plural t) 
(def-indiv-with-id drug "cephalosporin" "CHEBI:23066" :name "cephalosporin" :no-plural t) 
(def-indiv-with-id drug "cinanserin" "NCIT:C83624" :name "cinanserin" :no-plural t) 
(def-indiv-with-id drug "citronellol" "MESH:C007078" :name "citronellol" :no-plural t) 
(def-indiv-with-id drug "collidine" "MESH:C007106" :name "gamma-collidine" :no-plural t) 
(def-indiv-with-id drug "daptomycin" "NCIT:C47470" :name "daptomycin" :no-plural t) 
(def-indiv-with-id drug "desthiobiotin" "MESH:C004749" :name "desthiobiotin" :no-plural t) 
(def-indiv-with-id drug "dibucaine" "NCIT:C28984" :name "dibucaine" :no-plural t) 
(def-indiv-with-id drug "dimetridazole" "NCIT:C76419" :name "dimetridazole" :no-plural t) 
(def-indiv-with-id drug "edu" "NCIT:C87662" :name "edoxudine" :no-plural t) 
(def-indiv-with-id drug "eszopiclone" "NCIT:C65545" :name "eszopiclone" :no-plural t) 
(def-indiv-with-id drug "ethanedithiol" "MESH:C031854" :name "1,2-ethanedithiol" :no-plural t) 
(def-indiv-with-id drug "eugenol" "NCIT:C75095" :name "eugenol" :no-plural t) 
(def-indiv-with-id drug "fluphenazine" "NCIT:C47536" :name "fluphenazine" :no-plural t) 
(def-indiv-with-id drug "frovatriptan" "NCIT:C65772" :name "frovatriptan" :no-plural t) 
(def-indiv-with-id drug "immunosuppressant" "NCIT:C574" :name "immunosuppressant" :no-plural t) 
(def-indiv-with-id drug "immunotherapy" "NCIT:C308" :name "immunotherapeutic agent" :no-plural t) 
(def-indiv-with-id drug "isopentane" "MESH:C067038" :name "isopentane" :no-plural t) 
(def-indiv-with-id drug "ivermectin" "NCIT:C61796" :name "ivermectin" :no-plural t) 
(def-indiv-with-id drug "lactimidomycin" "MESH:C077633" :name "lactimidomycin" :no-plural t) 
(def-indiv-with-id drug "lapachol" "MESH:C008252" :name "lapachol" :no-plural t) 
(def-indiv-with-id drug "leishmanin" "MESH:C032127" :name "leishmanin" :no-plural t) 
(def-indiv-with-id drug "lignocellulose" "MESH:C036909" :name "lignocellulose" :no-plural t) 
(def-indiv-with-id drug "linezolid" "NCIT:C29158" :name "linezolid" :no-plural t) 
(def-indiv-with-id drug "maltodextrin" "MESH:C008315" :name "maltodextrin" :no-plural t) 
(def-indiv-with-id drug "maltotriose" "MESH:C008317" :name "maltotriose" :no-plural t) 
(def-indiv-with-id drug "meropenem" "NCIT:C1160" :name "meropenem" :no-plural t) 
(def-indiv-with-id drug "methicillin" "NCIT:C61842" :name "methicillin" :no-plural t) 
(def-indiv-with-id drug "metronidazole" "NCIT:C651" :name "metronidazole" :no-plural t) 
(def-indiv-with-id drug "nelarabine" "NCIT:C1704" :name "nelarabine" :no-plural t) 
(def-indiv-with-id drug "nitazoxanide" "NCIT:C47637" :name "nitazoxanide" :no-plural t) 
(def-indiv-with-id drug "nitrocefin" "NCIT:C76562" :name "nitrocefin" :no-plural t) 
(def-indiv-with-id drug "nonactin" "MESH:C050476" :name "nonactin" :no-plural t) 
(def-indiv-with-id drug "oritavancin" "MESH:C100708" :name "oritavancin" :no-plural t) 
(def-indiv-with-id drug "oseltamivir" "NCIT:C62061" :name "oseltamivir" :no-plural t) 
(def-indiv-with-id drug "palivizumab" "NCIT:C2625" :name "palivizumab" :no-plural t) 
(def-indiv-with-id drug "perampanel" "NCIT:C75029" :name "perampanel" :no-plural t) 
(def-indiv-with-id drug "phosphine" "MESH:C044646" :name "phosphine" :no-plural t) 
(def-indiv-with-id drug "piperacillin" "NCIT:C62069" :name "piperacillin" :no-plural t) 
(def-indiv-with-id drug "piperaquine" "NCIT:C87634" :name "piperaquine" :no-plural t) 
(def-indiv-with-id drug "pirlindole" "NCIT:C66428" :name "pirlindole" :no-plural t) 
(def-indiv-with-id drug "polysulfone" "MESH:C017662" :name "polysulfone P 1700" :no-plural t) 
(def-indiv-with-id drug "prodrug" "CHEBI:50266" :name "prodrug" :no-plural t) 
(def-indiv-with-id drug "propionamide" "MESH:C034666" :name "propionamide" :no-plural t) 
(def-indiv-with-id drug "remdesivir" "NCIT:C152185" :name "remdesivir" :no-plural t) 
(def-indiv-with-id drug "rupintrivir" "NCIT:C82255" :name "rupintrivir" :no-plural t) 
(def-indiv-with-id drug "salmochelin" "MESH:C000630262" :name "salmochelin" :no-plural t) 
(def-indiv-with-id drug "sarkosyl" "MESH:C025231" :name "sarkosyl" :no-plural t) 
(def-indiv-with-id drug "sulbactam" "NCIT:C61957" :name "sulbactam" :no-plural t) 
(def-indiv-with-id drug "tetramethylsilane" "MESH:C073196" :name "tetramethylsilane" :no-plural t) 
(def-indiv-with-id drug "tigecycline" "NCIT:C72865" :name "tigecycline" :no-plural t) 
(def-indiv-with-id drug "triethylamine" "MESH:C016162" :name "triethylamine" :no-plural t) 
(def-indiv-with-id drug "umifenovir" "NCIT:C152799" :name "umifenovir" :no-plural t) 
(def-indiv-with-id drug "zolmitriptan" "NCIT:C47789" :name "zolmitriptan" :no-plural t) 
(def-indiv-with-id drug "zopiclone" "NCIT:C80279" :name "zopiclone" :no-plural t) 
(def-indiv-with-id drug "Aluvia" "MESH:C558899" :name "lopinavir-ritonavir drug combination" :no-plural t) 
(def-indiv-with-id drug "Artesunate" "NCIT:C73005" :name "artesunate" :no-plural t) 
(def-indiv-with-id drug "Biologicals" "NCIT:C307" :name "biological agent" :no-plural t) 
(def-indiv-with-id drug "BisTris" "MESH:C026272" :name "Bistris" :no-plural t) 
(def-indiv-with-id drug "Cinolazepam" "NCIT:C77635" :name "cinolazepam" :no-plural t) 
(def-indiv-with-id drug "Clevidipine" "NCIT:C72727" :name "clevidipine" :no-plural t) 
(def-indiv-with-id drug "Darunavir" "NCIT:C65364" :name "darunavir" :no-plural t) 
(def-indiv-with-id drug "Flurazepam" "NCIT:C62030" :name "flurazepam" :no-plural t) 
(def-indiv-with-id drug "Fugene" "MESH:C411955" :name "FuGene" :no-plural t) 
(def-indiv-with-id drug "Gedunin" "MESH:C106014" :name "gedunin" :no-plural t) 
(def-indiv-with-id drug "IFNaB" "MESH:C076799" :name "interferon-alpha 8" :no-plural t) 
(def-indiv-with-id drug "Kaletra" "NCIT:C2096" :name "lopinavir/Ritonavir" :no-plural t) 
(def-indiv-with-id drug "Lipofectamine" "MESH:C086724" :name "Lipofectamine" :no-plural t) 
(def-indiv-with-id drug "Macrogen" "NCIT:C77591" :name "molgramostim" :no-plural t) 
(def-indiv-with-id drug "Mesalazine" "NCIT:C29249" :name "mesalamine" :no-plural t) 
(def-indiv-with-id drug "MonoQ" "MESH:C042855" :name "Mono Q" :no-plural t) 
(def-indiv-with-id drug "Novus" "MESH:C076789" :name "polyphosphazene fluoroelastomer" :no-plural t) 
(def-indiv-with-id drug "Oligofectamine" "MESH:C484027" :name "oligofectamine" :no-plural t) 
(def-indiv-with-id drug "Paramethasone" "NCIT:C66309" :name "paramethasone" :no-plural t) 
(def-indiv-with-id drug "Pefabloc" "MESH:C002010" :name "4-(2-aminoethyl)benzenesulfonylfluoride" :no-plural t) 
(def-indiv-with-id drug "Pyridostatin" "MESH:C567962" :name "pyridostatin" :no-plural t) 
(def-indiv-with-id drug "Rifabutin" "NCIT:C1408" :name "rifabutin" :no-plural t) 
(def-indiv-with-id drug "Telazol" "MESH:C006131" :name "tiletamine, zolazepam drug combination" :no-plural t) 
(def-indiv-with-id drug "Toremifene" "NCIT:C1256" :name "toremifene" :no-plural t) 
(def-indiv-with-id drug "Trizol" "MESH:C411644" :name "trizol" :no-plural t) 
(def-indiv-with-id drug "Urso" "NCIT:C1818" :name "ursodiol" :no-plural t) 
(def-indiv-with-id drug "Clocortolone" "NCIT:C61684" :name "clocortolone" :no-plural t) 
(def-indiv-with-id drug "Fosaprepitant" "NCIT:C72787" :name "fosaprepitant" :no-plural t) 
(def-indiv-with-id drug "compB" "MESH:C402921" :name "J 113397" :no-plural t) 
(def-indiv-with-id drug "Tilorone" "NCIT:C73335" :name "tilorone" :no-plural t) 