(in-package :sparser)


(def-ided-indiv bio-complex "ribosome" "GO:0005840" :name "ribosome") 
(def-ided-indiv bio-complex "pre-RC" "GO:0036387" :name "pre-replicative complex") 
(def-ided-indiv bio-complex "euchroma-tin" "GO:0000791" :name "euchromatin") 
(def-ided-indiv bio-complex "eIF4F" "GO:0016281" :name "eukaryotic translation initiation factor 4F complex") 
(def-ided-indiv bio-complex "eIF2" "GO:0005850" :name "eukaryotic translation initiation factor 2 complex") 
(def-ided-indiv bio-complex "apoptosome" "GO:0043293" :name "apoptosome") 
(def-ided-indiv bio-complex "U2AF" "GO:0089701" :name "U2AF") 
(def-ided-indiv bio-complex "TORC1" "GO:0031931" :name "TORC1 complex") 
(def-ided-indiv bio-complex "SET1C" "GO:0048188" :name "Set1C/COMPASS complex") 
(def-ided-indiv bio-complex "Ripoptosome" "GO:0097342" :name "ripoptosome") 
(def-ided-indiv bio-complex "Rad17-RFC" "GO:0031389" :name "Rad17 RFC-like complex") 
(def-ided-indiv bio-complex "Pre-BCR" "GO:0035369" :name "pre-B cell receptor complex") 
(def-ided-indiv bio-complex "PTPC" "GO:0005757" :name "mitochondrial permeability transition pore complex") 
(def-ided-indiv bio-complex "PIC" "GO:0019035" :name "viral integration complex") 
(def-ided-indiv bio-complex "IgG3" "GO:0071735" :name "IgG immunoglobulin complex") 
(def-ided-indiv bio-complex "IgG2b" "GO:0071735" :name "IgG immunoglobulin complex") 
(def-ided-indiv bio-complex "IgG2a" "GO:0071735" :name "IgG immunoglobulin complex") 
(def-ided-indiv bio-complex "IgG1" "GO:0071735" :name "IgG immunoglobulin complex") 
(def-ided-indiv bio-complex "F-actin" "GO:0031941" :name "filamentous actin") 