(in-package :sparser)


(def-indiv-with-id disease "CADASIL" "ORPHANET:136" :name "CADASIL") 
(def-indiv-with-id disease "CVD" "EFO:0000319" :name "cardiovascular disease") 
(def-indiv-with-id virus "EBOV" "NCIT:C112271" :name "ebola virus") 
(def-indiv-with-id virus "HDV" "NCIT:C93324" :name "hepatitis D virus") 
(def-indiv-with-id virus "HPIV" "NCIT:C125641" :name "human parainfluenza virus") 
(def-indiv-with-id cancer "IVA" "NCIT:C133425" :name "pathologic stage IVA esophageal adenocarcinoma AJCC v8") 
(def-indiv-with-id virus "NDV" "NCIT:C93023" :name "newcastle disease virus") 
(def-indiv-with-id disease "UTI" "NCIT:C50791" :name "urinary tract infection") 
(def-indiv-with-id virus "VZV" "NCIT:C71091" :name "varicella zoster virus") 
(def-indiv-with-id virus "YFV" "NCIT:C97156" :name "yellow fever virus") 
(def-indiv-with-id virus "ZIKV" "NCIT:C128553" :name "zika virus") 
(def-indiv-with-id virus "alphavirus" "NCIT:C112030" :name "alphavirus") 
(def-indiv-with-id disease "aortitis" "NCIT:C97085" :name "aortitis") 
(def-indiv-with-id virus "avulavirus" "NCIT:C117722" :name "avulavirus") 
(def-indiv-with-id disease "bacteraemia" "EFO:0003033" :name "bacteriemia") 
(def-indiv-with-id virus "betacoronavirus" "NCIT:C113207" :name "betacoronavirus") 
(def-indiv-with-id virus "bocavirus" "NCIT:C127691" :name "bocaparvovirus") 
(def-indiv-with-id disease "coagulopathy" "NCIT:C2902" :name "coagulation disorder") 
(def-indiv-with-id virus "coronaviridae" "NCIT:C113205" :name "coronaviridae") 
(def-indiv-with-id disease "dengue" "NCIT:C34528" :name "dengue fever") 
(def-indiv-with-id virus "echovirus" "NCIT:C112272" :name "echovirus") 
(def-indiv-with-id disease "eclampsia" "NCIT:C87167" :name "eclampsia") 
(def-indiv-with-id disease "enterocolitis" "EFO:1001481" :name "enterocolitis") 
(def-indiv-with-id virus "enterovirus" "NCIT:C14203" :name "enterovirus") 
(def-indiv-with-id cancer "erythroleukemia" "EFO:1001955" :name "erythroleukemia") 
(def-indiv-with-id bacterium "eubacterium" "NCIT:C86383" :name "eubacterium" :plural ("eubacteriums" "eubacteria")) 
(def-indiv-with-id virus "filovirus" "NCIT:C112031" :name "filoviridae") 
(def-indiv-with-id disease "funisitis" "NCIT:C97077" :name "funisitis") 
(def-indiv-with-id disease "hayfever" "EFO:0003956" :name "seasonal allergic rhinitis") 
(def-indiv-with-id disease "hyponatremia" "HP:0002902" :name "Hyponatremia") 
(def-indiv-with-id disease "laryngotracheitis" "NCIT:C26735" :name "croup") 
(def-indiv-with-id virus "lyssavirus" "NCIT:C112330" :name "lyssavirus") 
(def-indiv-with-id disease "parasitemia" "EFO:0001067" :name "parasitic infection") 
(def-indiv-with-id virus "parvovirus" "NCIT:C14299" :name "parvovirus") 
(def-indiv-with-id virus "pneumovirus" "NCIT:C112398" :name "pneumovirus") 
(def-indiv-with-id virus "respirovirus" "NCIT:C117721" :name "respirovirus") 
(def-indiv-with-id virus "vaccinia" "NCIT:C14281" :name "vaccinia virus") 
(def-indiv-with-id disease "vcf" "NCIT:C2989" :name "DiGeorge syndrome") 
(def-indiv-with-id disease "villitis" "EFO:0003110" :name "villitis") 
(def-indiv-with-id bacterium "Actinobacillus" "NCIT:C86097" :name "actinobacillus") 
(def-indiv-with-id bacterium "Actinobacteria" "NCIT:C76195" :name "actinobacteria") 
(def-indiv-with-id virus "Alphacoronavirus" "NCIT:C119319" :name "alphacoronavirus") 
(def-indiv-with-id bacterium "Arcobacter" "NCIT:C86152" :name "arcobacter") 
(def-indiv-with-id bacterium "Bifidobacterium" "NCIT:C86194" :name "bifidobacterium") 
(def-indiv-with-id bacterium "Burkholderiaceae" "NCIT:C85920" :name "burkholderiaceae") 
(def-indiv-with-id virus "Caliciviridae" "NCIT:C14304" :name "caliciviridae") 
(def-indiv-with-id bacterium "Carnobacteriaceae" "NCIT:C85922" :name "carnobacteriaceae") 
(def-indiv-with-id bacterium "Clostridium" "NCIT:C76275" :name "clostridium") 
(def-indiv-with-id cancer "Cmn" "NCIT:C6569" :name "congenital mesoblastic nephroma") 
(def-indiv-with-id disease "Copan" "ORPHANET:397725" :name "COASY protein-associated neurodegeneration") 
(def-indiv-with-id bacterium "Corynebacterium" "NCIT:C76308" :name "corynebacterium") 
(def-indiv-with-id virus "Deltacoronavirus" "NCIT:C122279" :name "deltacoronavirus") 
(def-indiv-with-id bacterium "Enterococcus" "NCIT:C76311" :name "enterococcus") 
(def-indiv-with-id bacterium "Escherichia" "NCIT:C77208" :name "escherichia") 
(def-indiv-with-id bacterium "Eubacterium" "NCIT:C86383" :name "eubacterium") 
(def-indiv-with-id virus "Filoviridae" "NCIT:C112031" :name "filoviridae") 
(def-indiv-with-id virus "Gammacoronavirus" "NCIT:C122313" :name "gammacoronavirus") 
(def-indiv-with-id bacterium "Gemella" "NCIT:C86889" :name "gemella") 
(def-indiv-with-id bacterium "Helicobacter" "NCIT:C14296" :name "helicobacter") 
(def-indiv-with-id virus "Henipavirus" "NCIT:C112290" :name "henipavirus") 
(def-indiv-with-id virus "Hepacivirus" "NCIT:C113202" :name "hepacivirus") 
;(def-indiv-with-id cancer "IIIc" "NCIT:C88139" :name "stage IIIC uveal melanoma AJCC v7") 
;(def-indiv-with-id cancer "IIc" "NCIT:C140168" :name "stage IIC prostate cancer AJCC v8") 
(def-indiv-with-id bacterium "Lactobacillus" "NCIT:C76352" :name "lactobacillus") 
(def-indiv-with-id bacterium "Leifsonia" "NCIT:C86490" :name "leifsonia") 
(def-indiv-with-id bacterium "Leptospiraceae" "NCIT:C86000" :name "leptospiraceae") 
(def-indiv-with-id bacterium "Leuconostoc" "NCIT:C76357" :name "leuconostoc") 
(def-indiv-with-id bacterium "Mannheimia" "NCIT:C86507" :name "mannheimia") 
(def-indiv-with-id bacterium "Microbacteriaceae" "NCIT:C85945" :name "microbacteriaceae") 
(def-indiv-with-id bacterium "Microbacterium" "NCIT:C85511" :name "microbacterium") 
(def-indiv-with-id bacterium "Moraxella" "NCIT:C86009" :name "moraxella") 
(def-indiv-with-id bacterium "Mycoplasma" "NCIT:C73540" :name "mycoplasma") 
(def-indiv-with-id bacterium "Neisseria" "NCIT:C76371" :name "neisseria") 
(def-indiv-with-id disease "ORs" "NCIT:C116333" :name "oculo-respiratory syndrome") 
(def-indiv-with-id virus "Orthomyxoviridae" "NCIT:C53453" :name "orthomyxoviridae") 
(def-indiv-with-id bacterium "Pantoea" "NCIT:C86631" :name "pantoea") 
(def-indiv-with-id bacterium "Paracoccus" "NCIT:C123337" :name "paracoccus") 
(def-indiv-with-id virus "parvovirus" "NCIT:C14299" :name "parvovirus" :plural ("parvoviruses" "Parvoviridae")) 
(def-indiv-with-id bacterium "Porphyromonas" "NCIT:C86653" :name "porphyromonas") 
(def-indiv-with-id bacterium "Pseudomonas" "NCIT:C76375" :name "pseudomonas") 
(def-indiv-with-id bacterium "Rhodobacteraceae" "NCIT:C118931" :name "rhodobacteraceae") 
(def-indiv-with-id bacterium "Rhodococcus" "NCIT:C76378" :name "rhodococcus") 
(def-indiv-with-id virus "Rotavirus" "NCIT:C77199" :name "rotavirus") 
(def-indiv-with-id disease "Rubella" "NCIT:C85051" :name "rubella infection") 
(def-indiv-with-id virus "SARSCoV" "NCIT:C112432" :name "SARS coronavirus") 
(def-indiv-with-id virus "Sapovirus" "NCIT:C112029" :name "sapovirus") 
(def-indiv-with-id bacterium "Sphingomonadaceae" "NCIT:C85964" :name "sphingomonadaceae") 
(def-indiv-with-id bacterium "Spirochaetes" "NCIT:C76206" :name "spirochaetes") 
(def-indiv-with-id cancer "TMDs" "NCIT:C27722" :name "therapy-related myelodysplastic syndrome") 
(def-indiv-with-id bacterium "Tenericutes" "NCIT:C85860" :name "tenericutes") 
(def-indiv-with-id bacterium "Treponema" "NCIT:C76385" :name "treponema") 
(def-indiv-with-id bacterium "Ureaplasma" "NCIT:C86832" :name "ureaplasma") 
(def-indiv-with-id disease "Zika" "NCIT:C128423" :name "zika virus infection") 
(def-indiv-with-id virus "hRSV" "NCIT:C14267" :name "human respiratory syncytial virus") 
