(in-package :sparser)


("p2" "ONT:GENE" :id "HGNC:9138" :name "exosome component 10") 
("UT" "ONT:PROTEIN-FAMILY" :id "XFAM:PF03253.12" :name "UT") 
("SL" "ONT:PROTEIN" :id "UP:P05045" :name "Seed lectin subunit I") 
("Mu" "ONT:PROTEIN-FAMILY" :id "FA:01672" :name "Mu family") 
("PV" "ONT:PROTEIN" :id "UP:P56530" :name "Phosvitin") 
("PG" "ONT:PROTEIN" :id "UP:Q9LW07" :name "Probable polygalacturonase At3g15720") 
("PN" "ONT:GENE-PROTEIN" :id "UP:Q15063" :name "Periostin") 
("MK" "ONT:GENE-PROTEIN" :id "UP:Q03426" :name "Mevalonate kinase") 
("RP" "ONT:GENE" :id "HGNC:7414" :name "mitochondrially encoded ATP synthase 6") 
("OT" "ONT:GENE" :id "NCIT:C52423" :name "OXT") 
("MN" "ONT:GENE" :id "NCIT:C52348" :name "GYPA") 
("JK" "ONT:GENE" :id "HGNC:10918" :name "solute carrier family 14 member 1 (Kidd blood group)") 
("IK" "ONT:GENE" :id "HGNC:5958" :name "IK cytokine, down-regulator of HLA II") 
("LN" "ONT:CELL-LINE" :id "CVCL:F127" :name "GM02063") 
("KF" "ONT:CELL-LINE" :id "CVCL:5M20" :name "KF") 
("KC" "ONT:CELL-LINE" :id "CVCL:Z833" :name "Kc") 
("JL" "ONT:CELL-LINE" :id "CVCL:F563" :name "JL") 
("JC" "ONT:CELL-LINE" :id "CVCL:3530" :name "JC") 
("HP" "ONT:CELL-LINE" :id "CVCL:3715" :name "HP") 
("BC" "ONT:PROCEDURE" :id "NCIT:C92225" :name "best case imputation technique") 
("FQ" "ONT:CELL-LINE" :id "CVCL:L984" :name "FQ") 
("FL" "ONT:CELL-LINE" :id "CVCL:1905" :name "FL") 
("DD" "ONT:CELL-LINE" :id "CVCL:J651" :name "DD") 
("Bu" "ONT:CELL-LINE" :id "CVCL:2527" :name "IMR-31") 
("BD" "ONT:CELL-LINE" :id "CVCL:F568" :name "BD") 
("AP" "ONT:CELL-LINE" :id "CVCL:E457" :name "AP") 
("pY" "ONT:PROTEIN" :id "UP:P0AD51" :name "Ribosome-associated factor Y {ECO:0000305}") 
("QC" "ONT:GENE-PROTEIN" :id "NCIT:C102505" :name "QPCT") 
("NP" "ONT:GENE-PROTEIN" :id "UP:Q9JGU1" :name "Nucleoprotein") 
("Gi" "ONT:GENE" :id "NCIT:C52638" :name "GNAI1") 
("FY" "ONT:GENE" :id "NCIT:C78152" :name "DARC") 
("EM" "ONT:GENE" :id "NCIT:C52483" :name "EMILIN") 
("LY" "ONT:CELL-LINE" :id "CVCL:2097" :name "L-5178-Y") 
("EB" "ONT:PROTEIN-FAMILY" :id "XFAM:PF01683.16" :name "EB") 
("TA" "ONT:PROTEIN" :id "UP:P37303" :name "Low specificity L-threonine aldolase") 
("RA" "ONT:PROTEIN" :id "UP:P10896" :name "Ribulose bisphosphate carboxylase/oxygenase activase, chloroplastic") 
("PS" "ONT:PROTEIN" :id "UP:Q9X713" :name "Pantothenate synthetase") 
("OM" "ONT:PROTEIN" :id "UP:O35508" :name "Oncomodulin") 
("LK" "ONT:PROTEIN" :id "UP:O15991" :name "Lombricine kinase") 
("LA" "ONT:PROTEIN" :id "NCIT:C70620" :name "lupus anticoagulant antibody") 
("HC" "ONT:PROTEIN" :id "UP:P08897" :name "Collagenase") 
("FC" "ONT:PROTEIN" :id "UP:Q06529" :name "Cytochrome subunit of sulfide dehydrogenase") 
("EC" "ONT:PROTEIN" :id "UP:Q16769" :name "Glutaminyl-peptide cyclotransferase") 
("DH" "ONT:PROTEIN" :id "UP:P23834" :name "Diuretic hormone") 
("CB" "ONT:PROTEIN" :id "UP:P0CAS1" :name "Phospholipase A2 crotoxin basic chain") 
("HA" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF03457.12" :name "HA") 
;;("DCs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1775" :name "Dyskeratosis congenita") see "DC"
("XO" "ONT:GENE-PROTEIN" :id "NCIT:C50947" :name "XDH") 
("TK" "ONT:GENE-PROTEIN" :id "UP:P29401" :name "Transketolase") 
("TG" "ONT:GENE-PROTEIN" :id "HGNC:11764" :name "thyroglobulin") 
("SI" "ONT:GENE-PROTEIN" :id "HGNC:10856" :name "sucrase-isomaltase") 
("HR" "ONT:GENE-PROTEIN" :id "HGNC:5172" :name "hair growth associated") 
("FA" "ONT:GENE-PROTEIN" :id "XFAM:PF08736.9" :name "FA") 
("EL" "ONT:GENE-PROTEIN" :id "UP:Q5QJ74" :name "Tubulin-specific chaperone cofactor E-like protein") 
("CS" "ONT:GENE-PROTEIN" :id "HGNC:2422" :name "citrate synthase") 
("SW" "ONT:GENE" :id "NCIT:C105065" :name "SLC4A1") 
("PI" "ONT:GENE" :id "NCIT:C105011" :name "SERPINA1") 
("OS" "ONT:GENE" :id "NCIT:C75731" :name "MID1") 
("OB" "ONT:GENE" :id "NCIT:C95049" :name "LEP") 
("KD" "ONT:GENE" :id "NCIT:C51572" :name "AR") 
("MC" "ONT:CELL-LINE" :id "CVCL:W203" :name "MC") 
("LH" "ONT:CELL-LINE" :id "CVCL:V626" :name "PrEC LH") 
("HS" "ONT:CELL-LINE" :id "CVCL:W404" :name "Hs") 
("HO" "ONT:CELL-LINE" :id "CVCL:M698" :name "Ho") 
("HK" "ONT:CELL-LINE" :id "CVCL:L805" :name "HK") 
("GS" "ONT:CELL-LINE" :id "CVCL:S933" :name "GS") 
("GP" "ONT:CELL-LINE" :id "CVCL:S009" :name "GP") 
("FG" "ONT:CELL-LINE" :id "CVCL:8196" :name "FG") 
("EA" "ONT:CELL-LINE" :id "CVCL:E575" :name "EA") 
("DM" "ONT:CELL-LINE" :id "CVCL:F549" :name "DM") 
("DG" "ONT:CELL-LINE" :id "CVCL:S101" :name "DG") 
("CP" "ONT:CELL-LINE" :id "CVCL:6F78" :name "CP") 
("CE" "ONT:CELL-LINE" :id "CVCL:6D96" :name "CE") 
("CC" "ONT:CELL-LINE" :id "CVCL:E520" :name "CC") 
("CA" "ONT:CELL-LINE" :id "CVCL:E319" :name "CA") 
("BM" "ONT:CELL-LINE" :id "CVCL:S926" :name "BM") 
("DS" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF01916.15" :name "DS") 
("TQ" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C126913" :name "tocopherylquinone") 
("T-Q" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C126913" :name "tocopherylquinone") 
("im" "ONT:MOLECULE" :id "CHEBI:30366" :name "imidazolide") 
("Vn" "ONT:MOLECULE" :id "CHEBI:35170" :name "vanadium(0)") 
("RH" "ONT:MOLECULE" :id "CHEBI:18310" :name "alkane") 
("QD" "ONT:MOLECULE" :id "CHEBI:50853" :name "quantum dot") 
("NO" "ONT:MOLECULE" :id "CHEBI:29121" :name "oxidonitrate(1-)") 
("KH" "ONT:MOLECULE" :id "CHEBI:32589" :name "potassium hydride") 
("I-2" "ONT:MOLECULE" :id "CHEBI:36899" :name "diiodine(.1+)") 
("GA" "ONT:MOLECULE" :id "CHEBI:5206" :name "GA") 
("FO" "ONT:MOLECULE" :id "CHEBI:30244" :name "hypofluorite") 
("YF" "ONT:CHEMICAL" :id "CHEBI:75005" :name "Tyr-Phe") 
("WL" "ONT:CHEMICAL" :id "CHEBI:74871" :name "Trp-Leu") 
("VM" "ONT:CHEMICAL" :id "CHEBI:75015" :name "Val-Met") 
("VI" "ONT:CHEMICAL" :id "CHEBI:75012" :name "Val-Ile") 
("VC" "ONT:CHEMICAL" :id "CHEBI:28509" :name "chloroethene") 
("TV" "ONT:CHEMICAL" :id "CHEBI:75193" :name "tetrazolium violet") 
("T-V" "ONT:CHEMICAL" :id "CHEBI:75193" :name "tetrazolium violet") 
("SQ" "ONT:CHEMICAL" :id "CHEBI:74808" :name "Ser-Gln") 
("RR" "ONT:CHEMICAL" :id "CHEBI:73811" :name "Arg-Arg") 
("QQ" "ONT:CHEMICAL" :id "CHEBI:73846" :name "Gln-Gln") 
("Q-E" "ONT:CHEMICAL" :id "CHEBI:73847" :name "Gln-Glu") 
("Pb" "ONT:CHEMICAL" :id "NCIT:C44396" :name "lead metal") ;; cleared (but may be case dependent)
("OH" "ONT:CHEMICAL" :id "CHEBI:16234" :name "hydroxide") 
("Ni" "ONT:CHEMICAL" :id "NCIT:C690" :name "nickel") ;;cleared (but may be case dependent)
("MH" "ONT:CHEMICAL" :id "CHEBI:74703" :name "Met-His") 
("LV" "ONT:CHEMICAL" :id "CHEBI:73579" :name "Leu-Val") 
("K+" "ONT:CHEMICAL" :id "CHEBI:29103" :name "potassium(1+)") ;; cleared 
("IH" "ONT:CHEMICAL" :id "CHEBI:73520" :name "Ile-His") 
("IG" "ONT:CHEMICAL" :id "CHEBI:74066" :name "Ile-Gly") 
("IA" "ONT:CHEMICAL" :id "CHEBI:74062" :name "Ile-Ala") 
("GV" "ONT:CHEMICAL" :id "CHEBI:73922" :name "Gly-Val") 
("FK" "ONT:CHEMICAL" :id "CHEBI:66872" :name "potassium fluoride") 
("E-D" "ONT:CHEMICAL" :id "CHEBI:73503" :name "Glu-Asp") 
("DV" "ONT:CHEMICAL" :id "CHEBI:73832" :name "Asp-Val") 
("DR" "ONT:CHEMICAL" :id "CHEBI:73445" :name "Asp-Arg") 
("DL" "ONT:CHEMICAL" :id "CHEBI:68596" :name "alpha-Asp-Leu") 
("DA" "ONT:CHEMICAL" :id "CHEBI:73826" :name "Asp-Ala") 
("Cd" "ONT:CHEMICAL" :id "NCIT:C44348" :name "cadmium") ;; cleared (but may be case dependent)
("AH" "ONT:CHEMICAL" :id "CHEBI:73771" :name "Ala-His") 
("AA" "ONT:CHEMICAL" :id "CHEBI:72816" :name "L-alanyl-L-alanine") 
("A-V" "ONT:CHEMICAL" :id "CHEBI:73809" :name "Ala-Val") 
("w-v" "ONT:CELL-LINE" :id "CVCL:E079" :name "W-V") 
("j-l" "ONT:CELL-LINE" :id "CVCL:F563" :name "JL") 
("i1" "ONT:CELL-LINE" :id "CVCL:AS22" :name "iPS NIHi1") 
("c-d" "ONT:CELL-LINE" :id "CVCL:W955" :name "CD") 
("a-a" "ONT:CELL-LINE" :id "CVCL:Z223" :name "ATC-15") 
("ZA" "ONT:CELL-LINE" :id "CVCL:D596" :name "ZA") 
("YN" "ONT:CELL-LINE" :id "CVCL:Y579" :name "YN") 
("YH" "ONT:CELL-LINE" :id "CVCL:1795" :name "YH-13") 
("Y0" "ONT:CELL-LINE" :id "CVCL:2783" :name "Y0") 
("XM" "ONT:CELL-LINE" :id "CVCL:R938" :name "XM") 
("WD" "ONT:CELL-LINE" :id "CVCL:8435" :name "WD PaCa") 
("W-7" "ONT:CELL-LINE" :id "CVCL:0576" :name "WEHI-7.1") 
("TF" "ONT:CELL-LINE" :id "CVCL:8274" :name "TF") 
("T-T" "ONT:CELL-LINE" :id "CVCL:1774" :name "TT") 
("T-L" "ONT:CELL-LINE" :id "CVCL:E852" :name "TL") 
("T-2" "ONT:CELL-LINE" :id "CVCL:2211" :name "T2") 
("T-1" "ONT:CELL-LINE" :id "CVCL:M858" :name "T-1") 
("SU" "ONT:CELL-LINE" :id "CVCL:W201" :name "SU") 
("SR" "ONT:CELL-LINE" :id "CVCL:1711" :name "SR") 
("SP" "ONT:CELL-LINE" :id "CVCL:L986" :name "SpR") 
("SM" "ONT:CELL-LINE" :id "CVCL:7004" :name "ACC-LC-171") 
("SH" "ONT:CELL-LINE" :id "CVCL:S945" :name "SH") 
("SE" "ONT:CELL-LINE" :id "CVCL:6D91" :name "SE") 
("SC" "ONT:CELL-LINE" :id "CVCL:6444" :name "SC") 
("SB" "ONT:CELL-LINE" :id "CVCL:M146" :name "NCI-EWS-95") 
("SA" "ONT:CELL-LINE" :id "CVCL:E822" :name "SA") 
("S-G" "ONT:CELL-LINE" :id "CVCL:M617" :name "SG") 
("S-D" "ONT:CELL-LINE" :id "CVCL:W902" :name "SD") 
("RG" "ONT:CELL-LINE" :id "CVCL:E626" :name "FH41") 
("RE" "ONT:CELL-LINE" :id "CVCL:U263" :name "RE") 
("RB" "ONT:CELL-LINE" :id "CVCL:L985" :name "RB") 
("R-F" "ONT:CELL-LINE" :id "CVCL:S939" :name "RF") 
("PK" "ONT:CELL-LINE" :id "CVCL:AZ81" :name "PK") 
("PF" "ONT:CELL-LINE" :id "CVCL:R981" :name "PF") 
("PE" "ONT:CELL-LINE" :id "CVCL:1D86" :name "PE") 
("PD" "ONT:CELL-LINE" :id "CVCL:8401" :name "PD PaCa") 
("PA" "ONT:CELL-LINE" :id "CVCL:E800" :name "PA") 
("P-A" "ONT:CELL-LINE" :id "CVCL:E800" :name "PA") 
("P-2" "ONT:CELL-LINE" :id "CVCL:Z997" :name "P2") 
("P-1" "ONT:CELL-LINE" :id "CVCL:G239" :name "P-1") 
("NK" "ONT:CELL-LINE" :id "CVCL:1D01" :name "Novikoff-Hepatoma") 
("NF" "ONT:CELL-LINE" :id "CVCL:W770" :name "NF") 
("NE" "ONT:CELL-LINE" :id "CVCL:3554" :name "NE") 
("N6" "ONT:CELL-LINE" :id "CVCL:D461" :name "mHypoE-N6") 
("MO" "ONT:CELL-LINE" :id "CVCL:1439" :name "Mo") 
("MJ" "ONT:CELL-LINE" :id "CVCL:1414" :name "MJ") 
("MF" "ONT:CELL-LINE" :id "CVCL:Y126" :name "MF") 
("MA" "ONT:CELL-LINE" :id "CVCL:Z027" :name "ACC-LC-78") 
("M-5" "ONT:CELL-LINE" :id "CVCL:C542" :name "RPMI-8322") 
("M-4" "ONT:CELL-LINE" :id "CVCL:U812" :name "M4") 
("M-3" "ONT:CELL-LINE" :id "CVCL:4Y25" :name "M3") 
("L-H" "ONT:CELL-LINE" :id "CVCL:V626" :name "PrEC LH") 
("L-6" "ONT:CELL-LINE" :id "CVCL:0385" :name "L6") 
("K-A" "ONT:CELL-LINE" :id "CVCL:7023" :name "ACC-LC-61") 
("JA" "ONT:CELL-LINE" :id "CVCL:W874" :name "JA") 
("HH" "ONT:CELL-LINE" :id "EFO:0002194" :name "HH") 
("B-m" "ONT:CELL-LINE" :id "CVCL:S926" :name "BM") 
("A-p" "ONT:CELL-LINE" :id "CVCL:E457" :name "AP") 
("A-3" "ONT:CELL-LINE" :id "CVCL:1061" :name "A3") 
("A-2" "ONT:CELL-LINE" :id "CVCL:1939" :name "A-2") 
("A-1" "ONT:CELL-LINE" :id "CVCL:6G43" :name "A1 [Human leukemia]") 
("LC" "ONT:CELL" :id "CO:0000453" :name "Langerhans cell") 
("iPS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:88621" :name "Ichthyosis prematurity syndrome") ;; actually Induced pluripotent stem cells (also known as iPS cells or iPSCs) 
("hep" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:95159" :name "Hepatoerythropoietic porphyria") ;; may be Heparin, hepatitis, hepatic, or a Hep allele in flies (http://flybase.org/reports/FBal0119240.html) depending on context -- have found examples of all but the hepatitis one in rasmachine_sentences
("XP" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:910" :name "Xeroderma pigmentosum") ;; only found it as part of citation
("TBS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:857" :name "Townes-Brocks syndrome") ;; in context may be "theta burst stimulation" or "Tris-buffered saline (TBS)" both in rasmachine
("SOD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:3157" :name "Septo-optic dysplasia") ;; actually "superoxide dismutase" protein family
("SMA" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:70" :name "Proximal spinal muscular atrophy") ;; in context "smooth muscle actin"
("SEI" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:455" :name "Superficial epidermolytic ichthyosis") ;; in context, "senkyunolide I"
("SCA1" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:98755" :name "Spinocerebellar ataxia type 1") ;; cleared
("PJS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2869" :name "Peutz-Jeghers syndrome")  ;; cleared
("OHSS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:64739" :name "Ovarian hyperstimulation syndrome") ;; cleared
("NKA" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:407" :name "Glycine encephalopathy") ;; actually "Na+,K+-ATPase"
("NEM" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:607" :name "Nemaline myopathy") ;; actually "N-ethylmaleimide"
("MNK" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:565" :name "Menkes disease") ;; actually "MAPK interacting serine/threonine protein kinase"
("MLC" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:2478" :name "Megalencephalic leukoencephalopathy with subcortical cysts") ;; actually "myosin light chain" -- added as peptide without ID, can't find ID for just this part
("MEN2" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:653" :name "Multiple endocrine neoplasia type 2") ;; cleared
("HVR" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:71291" :name "Hereditary vascular retinopathy") ;; actually "hypervariable region"
("HI" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:457" :name "Harlequin ichthyosis") ;; actually "high intensity [exercise]" in context
("DN" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C7656" :name "hepatic dysplastic nodule") ;; in context, either "dominant-negative" (e.g., PAK1-DN) or "diabetic nephropathy" -- both in ras
("DC" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1775" :name "Dyskeratosis congenita") ;; in context "dendritic cells"
("BV" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C116973" :name "bacterial vaginosis") ;; in context, BV-2 cell line
("BMD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1243" :name "Best vitelliform macular dystrophy") ;; in context, "bone mineral density"
("AOA1" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1168" :name "Ataxia - oculomotor apraxia type 1") ;; cleared
("RT" "ONT:CANCER" :id "NCIT:C82594" :name "refractory thrombocytopenia") ;; mostly part of RT-PCR real-time
("α2" "ONT:PROCEDURE" :id "NCIT:C67051" :name "affy alpha2 significance") ;; more likely to be a protein designator in a conjunction
("α1" "ONT:PROCEDURE" :id "NCIT:C67050" :name "affy alpha1 significance") ;; more likely to be a protein designator in a conjunction
("LE" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C76188" :name "LE rat strain") ;; more likely "late endosome" or "luminal epithelium" -- both possible in our contexts
("pM" "ONT:MEASURE-UNIT" :id "UO:0000066" :name "picomolar") ;; cleared (but may be case dependent)
("pH" "ONT:MEASURE-UNIT" :id "UO:0000196" :name "pH") ;; cleared (but may be case dependent)
("mV" "ONT:MEASURE-UNIT" :id "UO:0000247" :name "millivolt") ;; cleared (but may be case dependent)
("bp" "ONT:MEASURE-UNIT" :id "UO:0000244" :name "base pair") ;; cleared
("Ci" "ONT:MEASURE-UNIT" :id "UO:0000133" :name "curie") ;; too case dependent
("TJ" "ONT:CELL-PART" :id "UP:SL-0265" :name "Tight junction") ;; cleared
("SJ" "ONT:CELL-PART" :id "UP:SL-0246" :name "Septate junction") ;; only found as author initials
("IC" "ONT:CELL-PART" :id "UP:SL-0098" :name "Endoplasmic reticulum-Golgi intermediate compartment") ;; separated from the "50" in "IC50" which is the "half maximal inhibitory concentration"
("ug" "ONT:WEIGHT-UNIT" :id "UO:0000023" :name "microgram") ;; cleared
("E2" "pubchem" :type "simple-chemical" :id "PC:5757") ;; many possibilities in rasmachine "cyclin E2" or "Prostaglandin E2" or the "E2 enzyme" XFAM:PF00179 or "estradiol" (this is the TRIPS def -- which seems to be the most common that shows up on its own without being in a potential polyword) or a figure, in addition to the figure, other potential sources of difficulty are conjunctions e.g. "prostaglandin I2 and E2" and "cyclins B1 D2, and E2" "E2 ubiquitin conjugating enzyme"
("E7" "pfam" :type "family" :id "XFAM:PF00527") ;; cleared (oncoprotein from HPV)
("3D" "pfam" :type "family" :id "XFAM:PF06725") ;; much more likely to be 3-dimensions 
("SV" "pubchem" :type "simple-chemical" :id "PC:7020159") ;; "sedimentation velocity" or "somatic variant" or "stromal vascular" (cells) all in rasmachine
("E1" "pubchem" :type "simple-chemical" :id "PC:5870") ;; figure or "cyclin E1"
("M1" "pubchem" :type "simple-chemical" :id "PC:13019211") ;; mostly M1 macrophage (https://en.wikipedia.org/wiki/Macrophage), but also "M1 leukemia" (http://www.meds.com/leukemia/facts/facts_m1.html) and "M1 pyruvate" (https://en.wikipedia.org/wiki/PKM2) and "four endocytic motifs (M1-M4)" all in rasmachine as a side note, this pubchem ID is for "Deethylterbutryne" which doesn't even list "M1" on its page but CHEBI does
("M2" "pubchem" :type "simple-chemical" :id "PC:25058172") ;; same as M1 in terms of possible bindings and the fact that the pubchem page doesn't mention "M2" but CHEBI does
("E3" "pubchem" :type "simple-chemical" :id "PC:5756") ;; "E3 ubiquitin ligase" or "E3 ligase" in all of rasmachine, but this pubchem is for Estriol
("R6" "uberon" :type "organ" :id "UBERON:0005519")  ;; this is for rhombomere 6, part of the hindbrain, but in rasmachine, it just appears in one article about "compound r6" "2-cyclohexylamino-5,8-dimethoxy-1,4-naphthoquinone" but it's also PPP1R3D "Protein Phosphatase 1-Binding Subunit R6" and "R6 mouse models" (e.g. "R6/1 mouse brain")

;;(def-ided-indiv molecule "d–e" "CHEBI:73828" :name "Asp-Glu") should have been put in suspect defs
