(in-package :sparser)


(def-indiv-with-id molecule "CH3COOH" "CHEBI:15366" :name "acetic acid") 
(def-indiv-with-id molecule "FADH2" "CHEBI:17877" :name "FADH2") 
(def-indiv-with-id molecule "GA98" "CHEBI:133480" :name "gibberellin A98") 
(def-indiv-with-id molecule "GM1a" "CHEBI:18216" :name "alpha-N-acetylneuraminosyl-(2->3)-[beta-D-galactosyl-(1->3)-N-acetyl-beta-D-galactosaminyl-(1->4)]-beta-D-galactosyl-(1->4)-beta-D-glucosyl-(1<->1')-N-acylsphingosine") 
(def-indiv-with-id molecule "GQ1b" "CHEBI:27515" :name "alpha-Neu5Ac-(2->8)-alpha-Neu5Ac-(2->3)-beta-Gal-D-(1->3)-beta-D-GalNAc-(1->4)-[alpha-Neu5Ac-(2->8)-alpha-Neu5Ac-(2->3)]-beta-D-Gal-(1->4)-beta-D-Glc-(1<->1')-Cer") 
(def-indiv-with-id molecule "H2SO4" "CHEBI:26836" :name "sulfuric acid") 
(def-indiv-with-id molecule "H3K4me1" "CHEBI:85042" :name "H3K4Me1") 
(def-indiv-with-id molecule "NH4OAc" "CHEBI:62947" :name "ammonium acetate") 
(def-indiv-with-id molecule "NH4OH" "CHEBI:18219" :name "ammonium hydroxide") 
(def-indiv-with-id molecule "NaBH4" "CHEBI:50985" :name "sodium borohydride") 
(def-indiv-with-id molecule "Neu5GC" "CHEBI:62084" :name "N-glycoloyl-beta-neuraminic acid") 
(def-indiv-with-id molecule "PQ9" "CHEBI:28377" :name "plastoquinone-9") 
(def-indiv-with-id molecule "VO2" "CHEBI:30047" :name "vanadium dioxide") 
(def-indiv-with-id molecule "gastrin17" "CHEBI:75441" :name "gastrin-17") 
(def-indiv-with-id molecule "t21" "CHEBI:75682" :name "dT21") 
(def-indiv-with-id molecule "αcubebene" "CHEBI:10224" :name "alpha-Cubebene") 
(def-indiv-with-id molecule "βlactam" "CHEBI:35627" :name "beta-lactam") 