(in-package :sparser)


(def-family-with-id "AGR" "FA:00127" :name "AGR family") 
(def-family-with-id "APEC" "XFAM:PF16977" :name "ApeC") 
(def-family-with-id "CESA" "XFAM:PF11439" :name "T3SchapCesA") 
(def-family-with-id "CMC" "FA:04991" :name "CMC family") 
(def-family-with-id "COOT" "XFAM:PF10133" :name "CooT") 
(def-family-with-id "ERGIC" "FA:01131" :name "ERGIC family") 
(def-family-with-id "FCR" "NCIT:C17070" :name "Fc receptor") 
(def-family-with-id "GATAN" "XFAM:PF05349" :name "GATA-N") 
(def-family-with-id "HCG" "FPLX:hCG" :name "hCG") 
(def-family-with-id "KYY" "XFAM:PF10199" :name "adaptin binding") 
(def-family-with-id "MAGUK" "FA:02147" :name "MAGUK family") 
(def-family-with-id "MOEA" "FA:02340" :name "moeA family") 
(def-family-with-id "NCR" "NCIT:C129776" :name "natural cytotoxicity receptor family") 
(def-family-with-id "NPHII" "XFAM:PF12011" :name "NPH-II") 
(def-family-with-id "PARV" "FPLX:PARV" :name "PARV") 
(def-family-with-id "SRD" "XFAM:PF10317" :name "7TM GPCR Srd") 
(def-family-with-id "UAA" "XFAM:PF08449" :name "UAA") 
(def-family-with-id "VELVET" "XFAM:PF11754" :name "velvet") 
(def-family-with-id "WRW" "XFAM:PF10206" :name "WRW") 
(def-family-with-id "bornavirus" "XFAM:PF06208" :name "BDV G") 
(def-family-with-id "cand" "FA:00453" :name "CAND family") 
(def-family-with-id "cbil" "GO:0043781" :name "cobalt-factor II C20-methyltransferase activity") 
(def-family-with-id "chemokine" "FPLX:Chemokine" :name "Chemokine") 
(def-family-with-id "cycline" "FPLX:Cyclin_E" :name "Cyclin-E") 
(def-family-with-id "fetuin" "FA:01341" :name "fetuin family") 
(def-family-with-id "nido" "XFAM:PF06119" :name "NIDO") 
;(def-family-with-id "trans" "XFAM:PF06986" :name "TraN") 
(def-family-with-id "AmiGO" "FA:01834" :name "AMIGO family") 
(def-family-with-id "Crea" "XFAM:PF05981" :name "CreA") 
(def-family-with-id "DpnI" "XFAM:PF06044" :name "DpnI") 
(def-family-with-id "Klee" "XFAM:PF17394" :name "KleE") 
;(def-family-with-id "MSAs" "GO:0050641" :name "6-methylsalicylic acid synthase activity") 
(def-family-with-id "Plc" "FPLX:PLC" :name "PLC") 
(def-family-with-id "Tweety" "FA:04246" :name "tweety family") 
(def-family-with-id "sHsp" "NCIT:C136829" :name "small heat shock protein") 
