(in-package :sparser)


(def-indiv-with-id organism "SUS" "NCIT:C160990" :name "sus") 
(def-indiv-with-id bio-organ "bradyzoite" "BTO:0002342" :name "bradyzoite") 
(def-indiv-with-id organism "california" "NCIT:C76364" :name "california rabbit") 
(def-indiv-with-id organism "canid" "NCIT:C14331" :name "canidae") 
(def-indiv-with-id organism "echinacea" "NCIT:C54160" :name "echinacea") 
(def-indiv-with-id bio-organ "gravid" "BTO:0004733" :name "gravid adult") 
(def-indiv-with-id organism "hominid" "NCIT:C79740" :name "hominidae") 
(def-indiv-with-id bio-organ "metacestode" "BTO:0000859" :name "metacestode") 
(def-indiv-with-id organism "saimiri" "NCIT:C160934" :name "saimiri") 
(def-indiv-with-id bio-organ "schizont" "BTO:0001002" :name "schizont") 
(def-indiv-with-id organism "woodchuck" "NCIT:C124252" :name "eastern woodchuck") 
(def-indiv-with-id organism "Chlorocebus" "NCIT:C161031" :name "chlorocebus") 
(def-indiv-with-id organism "Cladosporium" "NCIT:C122261" :name "cladosporium") 
(def-indiv-with-id organism "Cologne" "NCIT:C79955" :name "cologne zebrafish") 
(def-indiv-with-id organism "Cynomolgus" "NCIT:C14232" :name "cynomolgus monkey") 
(def-indiv-with-id organism "Echinococcus" "NCIT:C122025" :name "echinococcus") 
(def-indiv-with-id organism "Entamoeba" "NCIT:C122048" :name "entamoeba") 
(def-indiv-with-id organism "Erythrocebus" "NCIT:C161036" :name "erythrocebus") 
(def-indiv-with-id organism "Fasciola" "NCIT:C122021" :name "fasciola") 
(def-indiv-with-id organism "Felidae" "NCIT:C14321" :name "felidae") 
(def-indiv-with-id organism "Giardia" "NCIT:C77213" :name "giardia") 
(def-indiv-with-id organism "Gottingen" "NCIT:C77102" :name "gottingen pig") 
(def-indiv-with-id organism "Göttingen" "NCIT:C77102" :name "gottingen pig") 
(def-indiv-with-id organism "Macaca" "NCIT:C14231" :name "macaque") 
(def-indiv-with-id organism "Macacus" "NCIT:C14231" :name "macaque") 
(def-indiv-with-id organism "Mansonella" "NCIT:C118942" :name "mansonella") 
(def-indiv-with-id organism "Onchocerca" "NCIT:C124282" :name "onchocerca") 
(def-indiv-with-id organism "Papio" "NCIT:C14252" :name "baboon") 
(def-indiv-with-id organism "Penicillium" "NCIT:C123540" :name "penicillium") 
(def-indiv-with-id organism "Pichia" "NCIT:C123544" :name "pichia") 
(def-indiv-with-id organism "Pyrenees" "NCIT:C53766" :name "great pyrenees") 
(def-indiv-with-id organism "Rodentia" "NCIT:C14270" :name "rodentia") 
(def-indiv-with-id organism "Solanum" "NCIT:C72445" :name "solanum nigrum") 
(def-indiv-with-id organism "Suid" "NCIT:C14322" :name "suidae") 
(def-indiv-with-id organism "Taenia" "NCIT:C125925" :name "taenia") 
(def-indiv-with-id organism "Trichinella" "NCIT:C125928" :name "trichinella") 
(def-indiv-with-id organism "ViteX" "NCIT:C72243" :name "angus castus") 
(def-indiv-with-id organism "Wuchereria" "NCIT:C122013" :name "wuchereria") 