(in-package :sparser)

("ARIP2" (UP:"Q3T0C9") "Bos taurus (Bovine)")
("ATSRA1" (UP:"Q5S2C3") "Arabidopsis thaliana (Mouse-ear cress)")
("ActR-II" (UP:"Q28043") "Bos taurus (Bovine)")
("Als3" (UP:"Q9ZUT3") "Arabidopsis thaliana (Mouse-ear cress)")
("AtCTC1" (UP:"D0EL35") "Arabidopsis thaliana (Mouse-ear cress)")
("AtSTN1" (UP:"Q9LMK5") "Arabidopsis thaliana (Mouse-ear cress)")
("AtVPS11" (UP:"Q9SJ40") "Arabidopsis thaliana (Mouse-ear cress)")
("Atgr1" (UP:"Q9LSV0") "Arabidopsis thaliana (Mouse-ear cress)")
("Bud23" (UP:"P25627") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("CBD1" (UP:"P60023") "Pan troglodytes (Chimpanzee)")
("CCAT2" (UP:"B3TP03") "Gallus gallus (Chicken)")
("CDMP-2" (UP:"P55106") "Bos taurus (Bovine)")
("CE5" (UP:"Q28896") "Canis lupus familiaris (Dog) (Canis familiaris)")
("CTFbeta" (UP:"Q60495") "Cavia porcellus (Guinea pig)")
("DCoHalpha" (UP:"Q9DG45") "Gallus gallus (Chicken)")
("DRAP27" (UP:"P30409") "Chlorocebus aethiops (Green monkey) (Cercopithecus aethiops)")
("E2O" (UP:"Q9N0F1") "Sus scrofa (Pig)")
("FAP221" (UP:"A8J6X7") "Chlamydomonas reinhardtii (Chlamydomonas smithii)")
("FAP52" (UP:"O13154") "Gallus gallus (Chicken)")
("GIR" (UP:"Q9TTQ9") "Canis lupus familiaris (Dog) (Canis familiaris)")
("GST-18" (UP:"Q9ZVQ3") "Arabidopsis thaliana (Mouse-ear cress)")
("GST-M" (UP:"Q9N0V4") "Bos taurus (Bovine)")
("Gas5" (UP:"Q08193") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("HP-F1" (UP:"Q05164") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Hap6" (UP:"Q93Z16") "Arabidopsis thaliana (Mouse-ear cress)")
("ICP8" (UP:"P04296") "Human herpesvirus 1 (strain 17) (HHV-1) (Human herpes simplex virus 1)")
("LTCP-1" (UP:"Q9Z1E9") "Cricetulus griseus (Chinese hamster) (Cricetulus barabensis griseus)")
("MYONAP" (UP:"Q5F3L9") "Gallus gallus (Chicken)")
("Mic12" (UP:"P38341") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("NDH-1" (UP:"P40215") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("NKA1b2" (UP:"Q5J583") "Ochotona curzoniae (Black-lipped pika)")
("Netrin-2" (UP:"Q90923") "Gallus gallus (Chicken)")
("P19Arf" (UP:"O77618") "Monodelphis domestica (Gray short-tailed opossum)")
("PRC8" (UP:"O23715") "Arabidopsis thaliana (Mouse-ear cress)")
("Pex10p" (UP:"Q9SYU4") "Arabidopsis thaliana (Mouse-ear cress)")
("Pex12p" (UP:"Q9M841") "Arabidopsis thaliana (Mouse-ear cress)")
("Pex13p" (UP:"Q9SRR0") "Arabidopsis thaliana (Mouse-ear cress)")
("Pex14p" (UP:"Q9FXT6") "Arabidopsis thaliana (Mouse-ear cress)")
("Pex2p" (UP:"Q9CA86") "Arabidopsis thaliana (Mouse-ear cress)")
("Pex7p" (UP:"Q9XF57") "Arabidopsis thaliana (Mouse-ear cress)")
("PiP2" (UP:"P52488") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Pip2" (UP:"P52488") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Qin" (UP:"Q90964") "Gallus gallus (Chicken)")
("RAB-GDI" (UP:"P39958") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Rab-GDI" (UP:"P39958") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Rgp1p" (UP:"P16664") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Ric1p" (UP:"P40395") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("SH3p13" (UP:"Q8AXU9") "Gallus gallus (Chicken)")
("SH3p4" (UP:"Q8AXV1") "Gallus gallus (Chicken)")
("SH3p8" (UP:"Q8AXV0") "Gallus gallus (Chicken)")
("Slt-1" (UP:"P53146") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("TAF130" (UP:"P46677") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("TAF48" (UP:"A6ZM67") "Saccharomyces cerevisiae (strain YJM789) (Baker's yeast)")
("Ubi-Z" (UP:"P62978") "Cavia porcellus (Guinea pig)")
("VBP" (UP:"Q92172") "Gallus gallus (Chicken)")
("WSP-1" (UP:"Q12044") "Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast)")
("Wise" (UP:"Q6VYA3") "Gallus gallus (Chicken)")
("ZF1" (UP:"Q9SSW1") "Arabidopsis thaliana (Mouse-ear cress)")
("apolipoprotein-B" (UP:"P11682") "Gallus gallus (Chicken)")
("arrestin3" (UP:"P32120") "Bos taurus (Bovine)")
("beta 1 -AR" (UP:"Q28927") "Ovis aries (Sheep)")
("beta 3" (UP:"O09029") "Mesocricetus auratus (Golden hamster)")
("beta1-AR" (UP:"Q28927") "Ovis aries (Sheep)")
("beta3-tubulin" (UP:"P33632") "Anemia phyllitidis (Fern) (Osmunda phyllitidis)")
("betaCAP73" (UP:"Q8HYY4") "Bos taurus (Bovine)")
("c-Myc" (UP:"Q17103") "Asterias rubens (Common European starfish) (Asterias vulgaris)")
("dZC3H3" (UP:"Q9VSK8") "Drosophila melanogaster (Fruit fly)")
("proacrosin" (UP:"Q2UVH8") "Meleagris gallopavo (Wild turkey)")
