;; multi-categories for word in fire
                    
;; 10/11/21 18:41:39

("American"
  country  ;SPARSER:DOSSIERS;COUNTRIES.LISP
  name-word  ;SPARSER:MIDEAST;NAMED-ENTITIES.LISP
)

("CT"
  us-state  ;SPARSER:DOSSIERS;US-STATES.LISP
  timezone  ;SPARSER:DOSSIERS;TIMEZONES.LISP
)

("E"
  direction  ;SPARSER:DOSSIERS;COMPASS-POINTS.LISP
  single-capitalized-letter  ;SPARSER:NAMES-MODEL;SINGLE-LETTERS.LISP
)

("Georgia"
  us-state  ;SPARSER:DOSSIERS;US-STATES.LISP
  country  ;SPARSER:DOSSIERS;COUNTRIES.LISP
)

("I"
  pronoun/first/singular  ;SPARSER:PRONOUNS;CASES.LISP
  post-ordinal  ;SPARSER:DOSSIERS;ORDINALS.LISP
  single-capitalized-letter  ;SPARSER:NAMES-MODEL;SINGLE-LETTERS.LISP
)

("Israeli"
  country  ;SPARSER:DOSSIERS;COUNTRIES.LISP
  name-word  ;SPARSER:MIDEAST;NAMED-ENTITIES.LISP
)

("MT"
  us-state  ;SPARSER:DOSSIERS;US-STATES.LISP
  timezone  ;SPARSER:DOSSIERS;TIMEZONES.LISP
)

("Macau"
  country  ;SPARSER:DOSSIERS;COUNTRIES.LISP
  city  ;SPARSER:DOSSIERS;COUNTRIES.LISP
)

("N"
  direction  ;SPARSER:DOSSIERS;COMPASS-POINTS.LISP
  single-capitalized-letter  ;SPARSER:NAMES-MODEL;SINGLE-LETTERS.LISP
)

("NE"
  us-state  ;SPARSER:DOSSIERS;US-STATES.LISP
  direction  ;SPARSER:DOSSIERS;COMPASS-POINTS.LISP
)

("NSA"
  authority  ;SPARSER:DOSSIERS;MILITARY-AUTHORITIES.LISP
  name-word  ;SPARSER:MIDEAST;NAMED-ENTITIES.LISP
)

("S"
  direction  ;SPARSER:DOSSIERS;COMPASS-POINTS.LISP
  single-capitalized-letter  ;SPARSER:NAMES-MODEL;SINGLE-LETTERS.LISP
)

("Shanghai"
  city  ;SPARSER:DOSSIERS;COUNTRIES.LISP
  name-word  ;SPARSER:BANKING;BANKS.LISP
)

("W"
  direction  ;SPARSER:DOSSIERS;COMPASS-POINTS.LISP
  single-capitalized-letter  ;SPARSER:NAMES-MODEL;SINGLE-LETTERS.LISP
)

("adjunct"
  adjunct  ;SPARSER:BIO;CATEGORY-DEFINING-WORDS.LISP
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
)

("answer"
  answer  ;SPARSER:DOSSIERS;VERBS.LISP
  answer/info  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("answers"
  answer  ;SPARSER:DOSSIERS;VERBS.LISP
  answer/info  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("anxious"
  awareness  ;SPARSER:MID-LEVEL;THINGS.LISP
  anxiety  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("around"
  approximator  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  around  ;SPARSER:WORDS;PREPOSITIONS.LISP
)

("avian"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  bird  ;SPARSER:MID-LEVEL;ORGANISMS.LISP
)

("avianner"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  comparative-modifier  ;SPARSER:MID-LEVEL;ORGANISMS.LISP
)

("aviannest"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  superlative-modifier  ;SPARSER:MID-LEVEL;ORGANISMS.LISP
)

("bad"
  goodness-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  goodness  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("bar"
  music-bar  ;SPARSER:MUSIC;OBJECTS.LISP
  bar  ;SPARSER:WORDS;PREPOSITIONS.LISP
)

("believe"
  believe  ;SPARSER:DOSSIERS;VERBS.LISP
  belief  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("believed"
  believe  ;SPARSER:DOSSIERS;VERBS.LISP
  belief  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("believes"
  believe  ;SPARSER:DOSSIERS;VERBS.LISP
  belief  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("believing"
  believe  ;SPARSER:DOSSIERS;VERBS.LISP
  belief  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("big"
  size-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  size  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("black"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("blue"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("brown"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("certainly"
  certainly  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  certain  ;SPARSER:MID-LEVEL;CERTAIN.LISP
)

("chief"
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
  title  ;SPARSER:MIDEAST;TITLES.LISP
)

("company"
  company  ;SPARSER:BIO;CATEGORY-DEFINING-WORDS.LISP
  generic-co-word  ;SPARSER:DOSSIERS;GENERIC-CO-WORDS.LISP
)

("concern"
  generic-co-word  ;SPARSER:DOSSIERS;GENERIC-CO-WORDS.LISP
  concern  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("decision"
  decision  ;SPARSER:DOSSIERS;VERBS.LISP
  decide  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("decisions"
  decision  ;SPARSER:DOSSIERS;VERBS.LISP
  decide  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("deputy"
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
  title  ;SPARSER:DOSSIERS;TITLES.LISP
)

("down"
  down  ;SPARSER:DOSSIERS;SPATIAL-PREPOSITIONS.LISP
  direction  ;SPARSER:DOSSIERS;DIRECTIONS.LISP
)

("executive"
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
  title  ;SPARSER:DOSSIERS;TITLES.LISP
)

("exit"
  region-type  ;SPARSER:DOSSIERS;LOCATION-KINDS.LISP
  location  ;SPARSER:PLACES;PATHS.LISP
)

("exits"
  region-type  ;SPARSER:DOSSIERS;LOCATION-KINDS.LISP
  location  ;SPARSER:PLACES;PATHS.LISP
)

("fast"
  rate-of-change-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  rate-of-change  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("first"
  sequencer  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  ordinal  ;SPARSER:DOSSIERS;ORDINALS.LISP
)

("focus"
  focus-verb  ;SPARSER:MID-LEVEL;THINGS.LISP
  focus-noun  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("focuses"
  focus-verb  ;SPARSER:MID-LEVEL;THINGS.LISP
  focus-noun  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("follow"
  follow  ;SPARSER:DOSSIERS;VERBS.LISP
  event-follows  ;SPARSER:MID-LEVEL;EVENTS.LISP
)

("followed"
  follow  ;SPARSER:DOSSIERS;VERBS.LISP
  event-follows  ;SPARSER:MID-LEVEL;EVENTS.LISP
)

("following"
  sequencer  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  follow  ;SPARSER:DOSSIERS;VERBS.LISP
  following  ;SPARSER:WORDS;PREPOSITIONS.LISP
)

("follows"
  follow  ;SPARSER:DOSSIERS;VERBS.LISP
  event-follows  ;SPARSER:MID-LEVEL;EVENTS.LISP
)

("former"
  title-status  ;SPARSER:DOSSIERS;TITLE-QUALIFIERS.LISP
  sequencer  ;SPARSER:DOSSIERS;MODIFIERS.LISP
)

("founder"
  role-based-person  ;SPARSER:DOSSIERS;PERSON-ROLES.LISP
  title  ;SPARSER:DOSSIERS;TITLES.LISP
)

("founders"
  role-based-person  ;SPARSER:DOSSIERS;PERSON-ROLES.LISP
  title  ;SPARSER:DOSSIERS;TITLES.LISP
)

("fraction"
  multiplier  ;SPARSER:DOSSIERS;NUMBERS.LISP
  fraction-of  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("fractions"
  multiplier  ;SPARSER:DOSSIERS;NUMBERS.LISP
  fraction-of  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("given"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  give  ;SPARSER:DOSSIERS;VERBS.LISP
)

("good"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  acknowledgement  ;SPARSER:MID-LEVEL;DISCOURSE.LISP
  goodness-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  goodness  ;SPARSER:DOSSIERS;QUALITIES.LISP
  acknowledgement  ;SPARSER:MID-LEVEL;DISCOURSE.LISP
)

("great"
  goodness-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  goodness  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("green"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("group"
  kind-of-company  ;SPARSER:DOSSIERS;KINDS-OF-COMPANIES.LISP
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
  group  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("groups"
  kind-of-company  ;SPARSER:DOSSIERS;KINDS-OF-COMPANIES.LISP
  group  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("high"
  amount-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  amount  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("individual"
  role-based-person  ;SPARSER:DOSSIERS;PERSON-ROLES.LISP
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
)

("journal"
  kind-of-company  ;SPARSER:DOSSIERS;KINDS-OF-COMPANIES.LISP
  journal  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("journals"
  kind-of-company  ;SPARSER:DOSSIERS;KINDS-OF-COMPANIES.LISP
  journal  ;SPARSER:MID-LEVEL;THINGS.LISP
  journal  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("known"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  know  ;SPARSER:DOSSIERS;VERBS.LISP
)

("large"
  size-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  size  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("little"
  size-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  size  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("long"
  length-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  length  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("low"
  amount-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  amount  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("lower"
  lower-note  ;SPARSER:DOSSIERS;VERBS.LISP
  comparative  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("martyr"
  title  ;SPARSER:MIDEAST;MARTYRDOM.LISP
  martyred  ;SPARSER:MIDEAST;MARTYRDOM.LISP
)

("martyrs"
  title  ;SPARSER:MIDEAST;MARTYRDOM.LISP
  martyred  ;SPARSER:MIDEAST;MARTYRDOM.LISP
)

("measure"
  music-measure  ;SPARSER:MUSIC;OBJECTS.LISP
  measure-as-measurement  ;SPARSER:AMOUNTS;MEASUREMENTS.LISP
  measure  ;SPARSER:AMOUNTS;MEASUREMENTS.LISP
)

("measures"
  music-measure  ;SPARSER:MUSIC;OBJECTS.LISP
  measure-as-measurement  ;SPARSER:AMOUNTS;MEASUREMENTS.LISP
  measure  ;SPARSER:AMOUNTS;MEASUREMENTS.LISP
)

("model"
  model-cl-verb  ;SPARSER:MID-LEVEL;THINGS.LISP
  model  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("models"
  model-cl-verb  ;SPARSER:MID-LEVEL;THINGS.LISP
  model  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("move"
  move-something-somewhere  ;SPARSER:DOSSIERS;VERBS.LISP
  move-to  ;SPARSER:DOSSIERS;VERBS.LISP
)

("moved"
  move-something-somewhere  ;SPARSER:DOSSIERS;VERBS.LISP
  move-to  ;SPARSER:DOSSIERS;VERBS.LISP
)

("moves"
  move-something-somewhere  ;SPARSER:DOSSIERS;VERBS.LISP
  move-to  ;SPARSER:DOSSIERS;VERBS.LISP
)

("moving"
  move-something-somewhere  ;SPARSER:DOSSIERS;VERBS.LISP
  move-to  ;SPARSER:DOSSIERS;VERBS.LISP
)

("ms"
  person-prefix  ;SPARSER:DOSSIERS;PERSON-PREFIXES.LISP
  unit-of-measure  ;SPARSER:DOSSIERS;UNITS-OF-MEASURE.LISP
  time-unit  ;SPARSER:DOSSIERS;TIME-UNITS.LISP
)

("name"
  name-to-position  ;SPARSER:DOSSIERS;JOB-EVENTS.LISP
  name-something  ;SPARSER:MID-LEVEL;THINGS.LISP
  has-name  ;SPARSER:MID-LEVEL;THINGS.LISP
  name  ;SPARSER:MID-LEVEL;ATTRIBUTES.LISP
)

("named"
  name-to-position  ;SPARSER:DOSSIERS;JOB-EVENTS.LISP
  name-something  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("names"
  name-to-position  ;SPARSER:DOSSIERS;JOB-EVENTS.LISP
  name-something  ;SPARSER:MID-LEVEL;THINGS.LISP
  has-name  ;SPARSER:MID-LEVEL;THINGS.LISP
  name  ;SPARSER:MID-LEVEL;ATTRIBUTES.LISP
)

("naming"
  name-to-position  ;SPARSER:DOSSIERS;JOB-EVENTS.LISP
  name-something  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("narrow"
  width-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  width  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("no"
  no  ;SPARSER:WORDS;QUANTIFIERS.LISP
  acknowledgement  ;SPARSER:MID-LEVEL;DISCOURSE.LISP
)

("novel"
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
  novel/book  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("one"
  indefinite-pronoun  ;SPARSER:PRONOUNS;CASES.LISP
  ones-number  ;SPARSER:DOSSIERS;NUMBERS.LISP
)

("operating"
  financial-qualifier  ;SPARSER:DOSSIERS;FINANCIAL-DATA-ITEMS.LISP
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
)

("orange"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("partners"
  generic-co-word  ;SPARSER:DOSSIERS;GENERIC-CO-WORDS.LISP
  title  ;SPARSER:DOSSIERS;TITLES.LISP
)

("pink"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("play"
  play-a-role-in  ;SPARSER:DOSSIERS;VERBS.LISP
  play  ;SPARSER:DOSSIERS;VERBS.LISP
)

("played"
  play-a-role-in  ;SPARSER:DOSSIERS;VERBS.LISP
  play  ;SPARSER:DOSSIERS;VERBS.LISP
)

("playing"
  play-a-role-in  ;SPARSER:DOSSIERS;VERBS.LISP
  play  ;SPARSER:DOSSIERS;VERBS.LISP
)

("plays"
  play-a-role-in  ;SPARSER:DOSSIERS;VERBS.LISP
  play  ;SPARSER:DOSSIERS;VERBS.LISP
)

("professional"
  role-based-person  ;SPARSER:DOSSIERS;PERSON-ROLES.LISP
  modifier  ;SPARSER:DOSSIERS;MODIFIERS.LISP
)

("publishing"
  company-activity-word  ;SPARSER:DOSSIERS;CO-ACTIVITY-WORDS.LISP
  publication  ;SPARSER:MID-LEVEL;THINGS.LISP
)

("purple"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("quarter"
  fiscal-quarter  ;SPARSER:TIME;FISCAL.LISP
  quarter  ;SPARSER:NUMBERS;FRACTIONS.LISP
)

("quarters"
  fiscal-quarter  ;SPARSER:TIME;FISCAL.LISP
  quarter  ;SPARSER:NUMBERS;FRACTIONS.LISP
)

("rate"
  rate-as-evaluate  ;SPARSER:DOSSIERS;VERBS.LISP
  rate  ;SPARSER:AMOUNTS;MEASUREMENTS.LISP
)

("rates"
  rate-as-evaluate  ;SPARSER:DOSSIERS;VERBS.LISP
  rate  ;SPARSER:AMOUNTS;MEASUREMENTS.LISP
)

("red"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("scientist"
  role-based-person  ;SPARSER:DOSSIERS;PERSON-ROLES.LISP
  title  ;SPARSER:DOSSIERS;TITLE-HEADS.LISP
)

("scientists"
  role-based-person  ;SPARSER:DOSSIERS;PERSON-ROLES.LISP
  title  ;SPARSER:DOSSIERS;TITLE-HEADS.LISP
)

("second"
  time-unit  ;SPARSER:DOSSIERS;TIME-UNITS.LISP
  ordinal  ;SPARSER:DOSSIERS;ORDINALS.LISP
)

("senior"
  person-version  ;SPARSER:DOSSIERS;PERSON-VERSIONS.LISP
  title-modifier  ;SPARSER:DOSSIERS;TITLE-MODIFIERS.LISP
)

("share"
  share-of-stock  ;SPARSER:FINANCE;PER-SHARE.LISP
  share-part  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("shares"
  share-of-stock  ;SPARSER:FINANCE;PER-SHARE.LISP
  share-part  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("short"
  height-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  height  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("slow"
  rate-of-change-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  rate-of-change  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("small"
  size-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  size  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("step"
  step  ;SPARSER:BLOCKS;VOCABULARY.LISP
  music-step  ;SPARSER:MUSIC;OBJECTS.LISP
)

("steps"
  step  ;SPARSER:BLOCKS;VOCABULARY.LISP
  music-step  ;SPARSER:MUSIC;OBJECTS.LISP
)

("table"
  table  ;SPARSER:BLOCKS;VOCABULARY.LISP
  article-table  ;SPARSER:MID-LEVEL;DOCUMENT-PARTS.LISP
)

("tables"
  table  ;SPARSER:BLOCKS;VOCABULARY.LISP
  article-table  ;SPARSER:MID-LEVEL;DOCUMENT-PARTS.LISP
)

("tall"
  height-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  height  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("target"
  target-waypoint  ;SPARSER:WAYPOINTS;WAYPOINT.LISP
  target  ;SPARSER:FINANCE;TARGET.LISP
)

("targets"
  target-waypoint  ;SPARSER:WAYPOINTS;WAYPOINT.LISP
  target  ;SPARSER:FINANCE;TARGET.LISP
)

("there"
  syntactic-there  ;SPARSER:SYNTAX-VG;BE.LISP
  deictic-location  ;SPARSER:PLACES;OBJECT.LISP
)

("total"
  financial-datum-value-verb  ;SPARSER:DOSSIERS;FINANCIAL-DATA-ITEMS.LISP
  total  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("totals"
  financial-datum-value-verb  ;SPARSER:DOSSIERS;FINANCIAL-DATA-ITEMS.LISP
  total  ;SPARSER:MID-LEVEL;GROUPS.LISP
)

("unit"
  financial-qualifier  ;SPARSER:DOSSIERS;FINANCIAL-DATA-ITEMS.LISP
  kind-of-subsidiary  ;SPARSER:DOSSIERS;KINDS-OF-SUBSIDIARIES.LISP
)

("units"
  financial-qualifier  ;SPARSER:DOSSIERS;FINANCIAL-DATA-ITEMS.LISP
  kind-of-subsidiary  ;SPARSER:DOSSIERS;KINDS-OF-SUBSIDIARIES.LISP
)

("up"
  up  ;SPARSER:DOSSIERS;SPATIAL-PREPOSITIONS.LISP
  direction  ;SPARSER:DOSSIERS;DIRECTIONS.LISP
)

("violet"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("white"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("wide"
  width-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  width  ;SPARSER:DOSSIERS;QUALITIES.LISP
)

("yellow"
  color-value  ;SPARSER:DOSSIERS;QUALITIES.LISP
  color  ;SPARSER:DOSSIERS;QUALITIES.LISP
)