(in-package :sparser)


(def-indiv-with-id rna "GSEC" "HGNC:48645" :name "G-quadruplex forming sequence containing lncRNA") 
(def-indiv-with-id rna "BISPR" "HGNC:51290" :name "BST2 interferon stimulated positive regulator") 
(def-indiv-with-id rna "SSRA" "NCIT:C95954" :name "transfer-messenger RNA") 
(def-indiv-with-id rna "HULC" "HGNC:34232" :name "hepatocellular carcinoma up-regulated long non-coding RNA") 
(def-indiv-with-id rna "NRIR" "HGNC:51269" :name "negative regulator of interferon response") 
(def-indiv-with-id rna "EGOT" "HGNC:37129" :name "eosinophil granule ontogeny transcript") 
(def-indiv-with-id rna "TUNA" "HGNC:44088" :name "TCL1 upstream neural differentiation-associated RNA") 
(def-indiv-with-id rna "THRIL" "HGNC:49503" :name "TNF and HNRNPL related immunoregulatory long non-coding RNA") 
(def-indiv-with-id rna "IPW" "HGNC:6109" :name "imprinted in Prader-Willi syndrome") 
(def-indiv-with-id rna "RMST" "HGNC:29893" :name "rhabdomyosarcoma 2 associated transcript") 
(def-indiv-with-id rna "FENDRR" "HGNC:43894" :name "FOXF1 adjacent non-coding developmental regulatory RNA") 
(def-indiv-with-id rna "NRAV" "HGNC:48588" :name "negative regulator of antiviral response") 
(def-indiv-with-id rna "EBER" "NCIT:C111618" :name "epstein-barr virus early RNA") 
(def-indiv-with-id rna "LIPCAR" "HGNC:50279" :name "mitochondrially encoded long non-coding cardiac associated RNA") 
(def-indiv-with-id rna "SAMMSON" "HGNC:49644" :name "survival associated mitochondrial melanoma specific oncogenic non-coding RNA") 
(def-indiv-with-id rna "NKILA" "HGNC:51599" :name "NF-kappaB interacting lncRNA") 
(def-indiv-with-id rna "limt" "HGNC:27886" :name "long intergenic non-protein coding RNA 1089") 
(def-indiv-with-id rna "Mort" "HGNC:44321" :name "ZNF667 antisense RNA 1 (head to head)") 
(def-indiv-with-id rna "NamA" "HGNC:42408" :name "non-protein coding RNA, associated with MAP kinase pathway and growth arrest") 
(def-indiv-with-id rna "Beyla" "HGNC:39078" :name "long intergenic non-protein coding RNA 293") 
(def-indiv-with-id rna "tmRNA" "NCIT:C95954" :name "transfer-messenger RNA") 
(def-indiv-with-id rna "trnK" "HGNC:7489" :name "mitochondrially encoded tRNA-Lys (AAA/G)") 
(def-indiv-with-id rna "hnRNA" "NCIT:C28454" :name "hnRNA") 
(def-indiv-with-id rna "Trnd" "HGNC:7478" :name "mitochondrially encoded tRNA-Asp (GAU/C)") 
(def-indiv-with-id rna "aroD" "HGNC:50913" :name "lncRNA activating regulator of DKK1") 
(def-indiv-with-id rna "trnG" "HGNC:7486" :name "mitochondrially encoded tRNA-Gly (GGN)") 
(def-indiv-with-id rna "Chaer" "HGNC:53620" :name "cardiac hypertrophy associated epigenetic regulator 1") 
(def-indiv-with-id rna "Rian" "HGNC:14574" :name "maternally expressed 8, small nucleolar RNA host gene") 
(def-indiv-with-id rna "trnI" "HGNC:7488" :name "mitochondrially encoded tRNA-Ile (AUU/C)") 
(def-indiv-with-id rna "Eric" "HGNC:49404" :name "E2F1-regulated inhibitor of cell death") 
(def-indiv-with-id rna "TrV" "HGNC:12353" :name "tRNA-Val (anticodon AAC) 1-4") 
(def-indiv-with-id rna "Norad" "HGNC:44311" :name "non-coding RNA activated by DNA damage") 
(def-indiv-with-id rna "Apal" "HGNC:44880" :name "ST8SIA6 antisense RNA 1") 