(in-package :sparser)


(def-indiv-with-id cancer "uMT" "NCIT:C6481" :name "inflammatory myofibroblastic tumor") 
(def-indiv-with-id cancer "PBLs" "NCIT:C7224" :name "plasmablastic lymphoma") 
(def-indiv-with-id cancer "HygroPalm" "NCIT:C3724" :name "cystic hygroma") 
(def-indiv-with-id cancer "ERGMs" "EFO:0000437" :name "embryonal rhabdomyosarcoma") 
(def-indiv-with-id cancer "Dunnet" "NCIT:C9505" :name "dysembryoplastic neuroepithelial tumor") 
(def-indiv-with-id cancer "APMiV" "NCIT:C4344" :name "acute panmyelosis with myelofibrosis") 
(def-indiv-with-id cancer "uib" "NCIT:C88136" :name "stage IIB uveal melanoma AJCC v7") 
(def-indiv-with-id cancer "thegpm" "NCIT:C3405" :name "thecoma") 
(def-indiv-with-id cancer "pbil" "NCIT:C7224" :name "plasmablastic lymphoma") 
(def-indiv-with-id cancer "condylomata" "NCIT:C2960" :name "condyloma acuminatum") 
(def-indiv-with-id cancer "fulc" "NCIT:C4131" :name "fibrolamellar carcinoma") 
(def-indiv-with-id cancer "csps" "EFO:0000653" :name "phyllodes tumor") 
(def-indiv-with-id cancer "TCSPC" "NCIT:C153336" :name "castration-sensitive prostate carcinoma") 
(def-indiv-with-id cancer "RCKC" "EFO:0000681" :name "renal cell carcinoma") 
(def-indiv-with-id cancer "JMOL" "NCIT:C9233" :name "juvenile myelomonocytic leukemia") 
(def-indiv-with-id cancer "HLCV" "NCIT:C7401" :name "hairy cell leukemia variant") 
(def-indiv-with-id cancer "GTY" "NCIT:C4699" :name "gestational trophoblastic tumor") 