(in-package :sparser)


(def-indiv-with-id bacterium "Streptoccocus" "NCIT:C76383" :name "streptococcus") 
(def-indiv-with-id bacterium "Staphyloccocus" "NCIT:C62583" :name "staphylococcus") 
(def-indiv-with-id bacterium "Staphycoccus" "NCIT:C62583" :name "staphylococcus") 
(def-indiv-with-id bacterium "Sphingomonadales" "NCIT:C85964" :name "sphingomonadaceae") 
(def-indiv-with-id bacterium "Rhodobacterales" "NCIT:C118931" :name "rhodobacteraceae") 
(def-indiv-with-id bacterium "Rhizobiales" "NCIT:C85959" :name "rhizobiaceae") 
(def-indiv-with-id bacterium "Proprionibacterium" "NCIT:C86013" :name "propionibacterium") 
(def-indiv-with-id bacterium "Poribacteria" "NCIT:C76196" :name "proteobacteria") 
(def-indiv-with-id bacterium "Oxalobacteriaceae" "NCIT:C85907" :name "caulobacteraceae") 
(def-indiv-with-id bacterium "Klebsiela" "NCIT:C28165" :name "klebsiella") 
(def-indiv-with-id bacterium "Heliocobacter" "NCIT:C14296" :name "helicobacter") 
(def-indiv-with-id bacterium "Grimont" "NCIT:C85976" :name "grimontia") 
(def-indiv-with-id bacterium "Gammaproteobacteria" "NCIT:C76196" :name "proteobacteria") 
(def-indiv-with-id bacterium "Enterobatecriaceae" "NCIT:C85932" :name "enterobacteriaceae") 
(def-indiv-with-id bacterium "Enterobactericeae" "NCIT:C85932" :name "enterobacteriaceae") 
(def-indiv-with-id bacterium "Enhydrobacter" "NCIT:C76310" :name "enterobacter") 
(def-indiv-with-id bacterium "Chlamyophila" "NCIT:C86254" :name "chlamydophila") 
(def-indiv-with-id bacterium "megasoftware" "NCIT:C86895" :name "megasphaera") 