(in-package :sparser)


(def-indiv-with-id virus "Whispovirus" "NCIT:C112029" :name "sapovirus") 
(def-indiv-with-id virus "ViroChip" "NCIT:C14219" :name "human immunodeficiency virus") 
(def-indiv-with-id virus "TBDev" "NCIT:C112422" :name "tick-borne encephalitis virus") 
(def-indiv-with-id virus "Siadenovirus" "NCIT:C14179" :name "adenoviridae") 
(def-indiv-with-id virus "Roniviridae" "NCIT:C112026" :name "reoviridae") 
(def-indiv-with-id virus "Rhinvoirus" "NCIT:C77200" :name "rhinovirus") 
(def-indiv-with-id virus "Rhabdovirdae" "NCIT:C112027" :name "rhabdoviridae") 
(def-indiv-with-id virus "Picornavirales" "NCIT:C14256" :name "picornavirus") 
(def-indiv-with-id virus "Phaeovirus" "NCIT:C14299" :name "parvovirus") 
(def-indiv-with-id virus "MuCoV" "NCIT:C112357" :name "molluscum contagiosum virus") 
(def-indiv-with-id virus "HBoV" "NCIT:C14215" :name "hepatitis B virus") 
(def-indiv-with-id virus "Flaviridae" "NCIT:C112031" :name "filoviridae") 
(def-indiv-with-id virus "Enterovius" "NCIT:C14203" :name "enterovirus") 
(def-synonym coronavirus (:noun "Coronvirus")) 
(def-synonym coronavirus (:noun "Coronoavirus")) 
(def-indiv-with-id virus "CnMV" "NCIT:C14196" :name "cytomegalovirus") 
(def-indiv-with-id virus "Asfarviridae" "NCIT:C112231" :name "astroviridae") 
(def-indiv-with-id virus "vaccinica" "NCIT:C14281" :name "vaccinia virus") 
(def-indiv-with-id virus "rabiesvirus" "NCIT:C112414" :name "rubivirus") 
(def-indiv-with-id virus "polioviruse" "NCIT:C14259" :name "poliovirus") 
(def-indiv-with-id virus "paleovirus" "NCIT:C14259" :name "poliovirus") 
(def-indiv-with-id virus "nidovirus" "NCIT:C112358" :name "nairovirus") 
(def-indiv-with-id virus "herpesvirues" "NCIT:C14217" :name "herpesvirus") 
(def-indiv-with-id virus "deltaretrovirus" "NCIT:C14347" :name "deltaretrovirus") 
(def-indiv-with-id virus "cyotomegalovirus" "NCIT:C14196" :name "cytomegalovirus") 
(def-synonym coronavirus (:noun "coronovirus")) 
(def-synonym coronavirus (:noun "coronavirusa")) 
(def-indiv-with-id virus "archaeovirus" "NCIT:C112272" :name "echovirus") 
(def-indiv-with-id virus "adenovirsuses" "NCIT:C14179" :name "adenoviridae") 
(def-indiv-with-id virus "WHBV" "NCIT:C124253" :name "woodchuck hepatitis virus") 
(def-indiv-with-id virus "NNV" "NCIT:C112363" :name "norwalk virus") 
(def-indiv-with-id virus "MACV" "NCIT:C73535" :name "merkel cell polyomavirus") 
(def-indiv-with-id virus "JCVI" "NCIT:C14229" :name "JC virus") 
(def-indiv-with-id virus "HPMV" "NCIT:C125640" :name "human metapneumovirus") 
(def-indiv-with-id virus "FLUV" "NCIT:C53454" :name "influenza A virus") 