(in-package :sparser)


(def-indiv-with-id cellular-location "Tij" "UP:SL-0265" :name "Tight junction") 
(def-indiv-with-id cellular-location "Techniplast" "GO:0009705" :name "plant-type vacuole membrane") 
(def-indiv-with-id cellular-location "SEcv" "GO:0020003" :name "symbiont-containing vacuole") 
(def-indiv-with-id cellular-location "ProteinPilot" "GO:0031986" :name "proteinoplast") 
(def-indiv-with-id cellular-location "Nucleid" "UP:SL-0187" :name "Nucleoid") 
(def-indiv-with-id cellular-location "NuPAGE" "GO:0043186" :name "P granule") 
(def-indiv-with-id cellular-location "MouseZoom" "GO:0046868" :name "mesosome") 
(def-indiv-with-id cellular-location "Cytostore" "GO:0031910" :name "cytostome") 
(def-indiv-with-id cellular-location "Cytoperm" "GO:0035230" :name "cytoneme") 
(def-indiv-with-id cellular-location "Centriprep" "UP:SL-0047" :name "Centromere") 
(def-indiv-with-id cellular-location "COVc" "UP:SL-0073" :name "Contractile vacuole") 
(def-indiv-with-id cellular-location "AAAVd" "GO:0044754" :name "autolysosome") 
(def-synonym dendritic-spine (:noun "sapien")) 
(def-indiv-with-id cellular-location "pronucleus" "GO:0045120" :name "pronucleus" :plural ("pronucleuses" "pronuclei")) 
(def-indiv-with-id cellular-location "nucleocapids" "GO:0019013" :name "viral nucleocapsid") 
(def-indiv-with-id cellular-location "microvili" "UP:SL-0293" :name "Microvillus") 
(def-synonym membrane (:noun "mebrane")) 
(def-synonym endosome (:noun "endsome")) 
(def-indiv-with-id cellular-location "Chromoplast" "UP:SL-0063" :name "Chromoplast" :plural ("Chromoplasts" "chromoplasts")) 
(def-indiv-with-id cellular-location "capsomers" "GO:0046727" :name "capsomere") 