(in-package :sparser)

;; definitions that are confounding to non-bio
;; nucleus but decided to put it in non-academic anyway
(def-indiv-with-id cellular-location "spike" "GO:0098029" :name "icosahedral viral capsid, spike" :synonyms ("peplomer")) ;; obviously this one is also relevvant outside academic bio these days
(def-indiv-with-id cellular-location "ruffle" "GO:0001726") 
(def-indiv-with-id cellular-location "MOM" "GO:0036407" :name "mycolate outer membrane" :maintain-case t) 
(def-indiv-with-id cellular-location "Host" "UP:SL-0431" :name "Host") 
(def-indiv-with-id cellular-location "groove" "GO:0097610" :name "cell surface furrow")
(def-indiv-with-id cellular-location "halo" "GO:1990038" :name "Lewy body corona")
(def-indiv-with-id cellular-location "ER" "GO:0005783" :name "endoplasmic reticulum") ;; put without "ER" in non-academic
(def-indiv-with-id cellular-location "spine" "GO:0043197" :name "dendritic spine") 
(def-indiv-with-id cellular-location "spindle" "UP:SL-0251" :name "Spindle") 
(def-indiv-with-id cellular-location "microspike" "GO:0044393" :name "microspike")
(def-indiv-with-id cellular-location "veil" "GO:0030027" :name "lamellipodium")(def-indiv-with-id cellular-location "budding" "UP:SL-0027" :name "bud") 
(def-indiv-with-id cellular-location "satellite" "UP:SL-0485" :name "Centriolar satellite")
(def-indiv-with-id cellular-location "midbody" "UP:SL-0469" :name "Midbody") 
(def-indiv-with-id cellular-location "midline" "GO:0031430" :name "M band")

(def-indiv-with-id cellular-location "GEMS" "GO:0097504" :name "Gemini of coiled bodies") 
(def-indiv-with-id cellular-location "CORE" "GO:0019013" :name "viral nucleocapsid") 
(def-indiv-with-id cellular-location "microparticle" "UP:SL-0499" :name "Extracellular vesicle")
(def-indiv-with-id cellular-location "cingulum" "GO:0097611" :name "dinoflagellate cingulum") ;; brain white matter tract
(def-indiv-with-id cellular-location "cilium" "UP:SL-0066" :name "Cilium" :plural ("cilia")) ;; also eyelashes
(def-indiv-with-id cellular-location "sulcus" "GO:0097612" :name "dinoflagellate sulcus" :plural ("sulci")) ;; also brain sulcus
(def-indiv-with-id cellular-location "septum" "GO:0030428" :name "cell septum" :plural ("septums" "septa")) ;; also nose
(def-indiv-with-id cellular-location "tectum" "GO:0043676" :name "tectum") ;; also brainstem
(def-indiv-with-id cellular-location "soma" "GO:0044297" :name "cell body")  

(def-indiv-with-id cellular-location "target cell" "UP:SL-0487") 
(def-indiv-with-id cellular-location "tight junction" "UP:SL-0265") 
(def-indiv-with-id cellular-location "cell surface" "GO:0009986") 
;;(def-indiv-with-id cellular-location "nucleolus" "GO:0005730")

(def-indiv-with-id cellular-location "lipid droplet" "UP:SL-0154") 
(def-indiv-with-id cellular-location "recycling endosome" "GO:0055037") 
(def-indiv-with-id cellular-location "late endosome" "GO:0005770") 
(def-indiv-with-id cellular-location "replication fork" "GO:0005657") 
(def-indiv-with-id cellular-location "extracellular space" "GO:0005615") 
(def-indiv-with-id cellular-location "stress fiber" "GO:0001725") 
(def-indiv-with-id cellular-location "clathrin coated pit" "UP:SL-0069") 
(def-indiv-with-id cellular-location "endocytic vesicle" "GO:0030139") 
(def-indiv-with-id cellular-location "primary cilium" "GO:0072372" :plural ("primary cilia")) 
(def-indiv-with-id cellular-location "basement membrane" "GO:0005604") 
(def-indiv-with-id cellular-location "basal lamina" "GO:0005605") 
(def-indiv-with-id cellular-location "aggresome" "GO:0016235") 
(def-indiv-with-id cellular-location "adherens junction" "GO:0005912") 
(def-indiv-with-id cellular-location "sarcomere" "UP:SL-0313" :name "Sarcomere") 
(def-indiv-with-id cellular-location "Pseudopodium" "UP:SL-0298" :name "Pseudopodium" :plural ("Pseudopodiums" "pseudopodia")) 

(def-indiv-with-id cellular-location "podosome" "UP:SL-0295" :name "Podosome") 


(def-indiv-with-id cellular-location "microsome" "UP:SL-0166" :name "Microsome") 
(def-indiv-with-id cellular-location "micronucleus" "GO:0031040" :name "micronucleus") 

(def-indiv-with-id cellular-location "Invadopodium" "UP:SL-0148" :name "Invadopodium" :plural ("Invadopodiums" "invadopodia")) 
(def-indiv-with-id cellular-location "fibril" "GO:0043205" :name "fibril") 
(def-indiv-with-id cellular-location "exosome" "UP:SL-0466" :name "Exosome") 
(def-indiv-with-id cellular-location "endomembrane" "UP:SL-0147" :name "Endomembrane system")
(def-indiv-with-id cellular-location "autophagosome" "UP:SL-0023" :name "Autophagosome") 

(def-indiv-with-id cellular-location "PML-NB" "GO:0016605" :name "PML body" :synonyms ("ND10")) 
(def-indiv-with-id cellular-location "P-body" "UP:SL-0230" :name "P-body") 
(def-indiv-with-id cellular-location "MVB" "GO:0005771" :name "multivesicular body") 
;(def-synonym golgi-apparatus (:noun "Golgi")) 
(def-indiv-with-id cellular-location "Cross-Bridge" "GO:0097595" :name "ventral disc crossbridge") 
(def-indiv-with-id cellular-location "Z-body" "UP:SL-0314" :name "Z-body")
(def-indiv-with-id cellular-location "cyclosome" "GO:0005680" :name "anaphase-promoting complex") 
(def-indiv-with-id cellular-location "peroxisome" "UP:SL-0204" :name "Peroxisome") 
(def-indiv-with-id cellular-location "PVC" "UP:SL-0223" :name "Prevacuolar compartment") 
(def-indiv-with-id cellular-location "kinetoplast" "UP:SL-0150" :name "Kinetoplast") 
(def-indiv-with-id cellular-location "chiasmata" "GO:0005712" :name "chiasma") 
(def-indiv-with-id cellular-location "rhabdomere" "GO:0016028" :name "rhabdomere") 
(def-indiv-with-id cellular-location "GCI" "GO:0097409" :name "glial cytoplasmic inclusion") 
(def-indiv-with-id cellular-location "HLB" "GO:0035363" :name "histone locus body") 
(def-indiv-with-id cellular-location "IAM" "UP:SL-0004" :name "Acrosome inner membrane") 
(def-indiv-with-id cellular-location "IPM" "UP:SL-0146" :name "Interphotoreceptor matrix") 
(def-indiv-with-id cellular-location "IMC" "UP:SL-0362" :name "Inner membrane complex") 
(def-indiv-with-id cellular-location "MDV" "GO:0099073" :name "mitochondrion-derived vesicle") 
(def-indiv-with-id cellular-location "MCS" "GO:0044232" :name "organelle membrane contact site") 
(def-indiv-with-id cellular-location "PAA" "GO:1990295" :name "post-anaphase microtubule array") 
(def-indiv-with-id cellular-location "SCV" "GO:0020003" :name "symbiont-containing vacuole") 
(def-indiv-with-id cellular-location "autosome" "GO:0030849" :name "autosome") 
(def-indiv-with-id cellular-location "autolysosome" "GO:0044754" :name "autolysosome") 
(def-indiv-with-id cellular-location "acrosome" "UP:SL-0007" :name "Acrosome") 
(def-indiv-with-id cellular-location "chylomicron" "GO:0042627" :name "chylomicron") 

;(def-synonym golgi-apparatus (:noun "golgi")) 
(def-indiv-with-id cellular-location "glycocalyx" "GO:0030112" :name "glycocalyx") 


(def-indiv-with-id cellular-location "macronucleus" "GO:0031039" :name "macronucleus") 
(def-indiv-with-id cellular-location "nucleoskeleton" "GO:0016363" :name "nuclear matrix") 
(def-indiv-with-id cellular-location "nucleoid" "UP:SL-0187" :name "Nucleoid") 
(def-indiv-with-id cellular-location "myofibril" "UP:SL-0312" :name "Myofibril")  


(def-indiv-with-id cellular-location "microvesicle" "GO:1990742" :name "microvesicle") 
(def-indiv-with-id cellular-location "microfibril" "GO:0001527" :name "microfibril") 
(def-indiv-with-id cellular-location "ooplasm" "GO:1990917" :name "ooplasm") 
(def-indiv-with-id cellular-location "omegasome" "GO:1990462" :name "omegasome") 
(def-indiv-with-id cellular-location "paraspeckles" "GO:0042382" :name "paraspeckles")

(def-indiv-with-id cellular-location "Rhoptry" "UP:SL-0233" :name "Rhoptry" :plural ("Rhoptries" "rhoptries")) 
(def-indiv-with-id cellular-location "Stereocilium" "UP:SL-0302" :name "Stereocilium" :plural ("Stereociliums" "stereocilia")) 
(def-indiv-with-id cellular-location "spherosomes" "GO:0012511" :name "monolayer-surrounded lipid storage body") 
(def-indiv-with-id cellular-location "IGC" "UP:SL-0186" :name "Nucleus speckle" :maintain-case t) 
(def-indiv-with-id cellular-location "Z-disc" "GO:0030018" :name "Z disc") 

(def-indiv-with-id cellular-location "macropinosome" "GO:0044354" :name "macropinosome") 
(def-indiv-with-id cellular-location "pSG" "GO:0034515" :name "proteasome storage granule") 
(def-indiv-with-id cellular-location "phagolysosome" "GO:0032010" :name "phagolysosome")


(def-indiv-with-id cellular-location "axoneme" "GO:0005930" :name "axoneme") 
(def-indiv-with-id cellular-location "chromocentre" "GO:0010369" :name "chromocenter") 
(def-indiv-with-id cellular-location "microbody" "GO:0042579" :name "microbody") 
(def-indiv-with-id cellular-location "fimbria" "GO:0009289" :name "pilus" :plural ("fimbrias" "fimbriae" "piluses" "pili")) 
(def-indiv-with-id cellular-location "tna" "CHEBI:48019" :name "threose nucleic acid") 
(def-indiv-with-id cellular-location "bleb" "UP:SL-0472" :name "Bleb") 
(def-indiv-with-id cellular-location "Desmosome" "UP:SL-0092" :name "Desmosome" :plural ("Desmosomes" "desmosomes")) 
(def-indiv-with-id cellular-location "microvillus" "UP:SL-0293" :name "Microvillus" :plural ("microvilluses" "microvilli")) 
(def-indiv-with-id cellular-location "tight-junction" "UP:SL-0265" :name "Tight junction" :synonyms ("TJ")) 
(def-indiv-with-id cellular-location "CVC" "UP:SL-0073" :name "Contractile vacuole") 

(def-indiv-with-id cellular-location "chorion" "GO:0042600" :name "chorion") 
(def-indiv-with-id cellular-location "cis-Golgi" "UP:SL-0067" :name "cis-Golgi network") 
(def-indiv-with-id cellular-location "provirus" "GO:0019038" :name "provirus") 

(def-indiv-with-id cellular-location "Perikaryon" "UP:SL-0197" :name "Perikaryon" :plural ("perikaryons" "perikarya"))
(def-indiv-with-id cellular-location "nucleosome" "GO:0000786" :name "nucleosome") 

;; post-covid
(def-indiv-with-id cellular-location "archaellum" "GO:0097589" :name "archaeal-type flagellum") 
(def-indiv-with-id cellular-location "plasmodesmata" "UP:SL-0208" :name "Plasmodesma") 
(def-indiv-with-id cellular-location "tonoplast" "GO:0009705" :name "plant-type vacuole membrane") 
(def-indiv-with-id cellular-location "CCV" "UP:SL-0070" :name "Clathrin-coated vesicle") 
(def-indiv-with-id cellular-location "MSB" "GO:0150086" :name "multiple synapse bouton") 
(def-indiv-with-id cellular-location "MTOC" "GO:0005815" :name "microtubule organizing center") 
(def-indiv-with-id cellular-location "PCMC" "GO:1990075" :name "periciliary membrane compartment") 
(def-indiv-with-id cellular-location "phagosome" "UP:SL-0206" :name "Phagosome") 
(def-indiv-with-id cellular-location "uropod" "GO:0001931" :name "uropod") 
(def-indiv-with-id cellular-location "membrane raft" "GO:0045121" :name "lipid raft" :synonyms ("lipid raft" "GEM domain" "glycolipid-enriched membrane domain"))

(def-indiv-with-id cellular-location "GWB" "UP:SL-0230" :name "P-body") 
(def-indiv-with-id cellular-location "ERQC" "GO:0044322" :name "endoplasmic reticulum quality control compartment") 
(def-indiv-with-id cellular-location "MVE" "GO:0005771" :name "multivesicular body") 

(def-indiv-with-id cellular-location "subtelomere" "GO:0099115" :name "chromosome, subtelomeric region") 
(def-synonym plasma-membrane (:noun "plasmalemma")) 
(def-indiv-with-id cellular-location "cellulosome" "GO:0043263" :name "cellulosome") 
(def-indiv-with-id cellular-location "exine" "GO:0043668" :name "exine") 
(def-indiv-with-id cellular-location "carboxysome" "UP:SL-0034" :name "Carboxysome") 
(def-indiv-with-id cellular-location "thylakoid" "UP:SL-0450" :name "Thylakoid") 
(def-indiv-with-id cellular-location "pellicle" "GO:0020039" :name "pellicle") 
(def-indiv-with-id cellular-location "internode" "GO:0033269" :name "internode region of axon") 
(def-indiv-with-id cellular-location "sarcoplasm" "UP:SL-0311" :name "Sarcoplasm") 
(def-indiv-with-id cellular-location "axoplasm" "GO:1904115" :name "axon cytoplasm") 
(def-indiv-with-id cellular-location "capsomer" "GO:0046727" :name "capsomere") 
(def-synonym extracellular-matrix (:noun "matrisome")) 
(def-indiv-with-id cellular-location "paranode" "GO:0033270" :name "paranode region of axon") 
(def-indiv-with-id cellular-location "periplasm" "UP:SL-0200" :name "Periplasm") 
(def-indiv-with-id cellular-location "apicoplast" "UP:SL-0018" :name "Apicoplast") 
(def-indiv-with-id cellular-location "autophagolysosome" "GO:0044754" :name "autolysosome") 
(def-indiv-with-id cellular-location "conoid" "GO:0020010" :name "conoid") 
(def-indiv-with-id cellular-location "apoplast" "UP:SL-0019" :name "Apoplast") 
(def-indiv-with-id cellular-location "microneme" "UP:SL-0163" :name "Microneme") 
(def-indiv-with-id cellular-location "sarcolemma" "UP:SL-0238" :name "Sarcolemma") 
(def-indiv-with-id cellular-location "crystalloid" "GO:0044312" :name "crystalloid") 
(def-indiv-with-id cellular-location "acidocalcisome" "UP:SL-0002" :name "Acidocalcisome") 
(def-indiv-with-id cellular-location "amphisome" "GO:0044753" :name "amphisome") 
(def-indiv-with-id cellular-location "cristae" "GO:0030061" :name "mitochondrial crista") 
(def-indiv-with-id cellular-location "haustorium" "GO:0085035" :name "haustorium") 
(def-indiv-with-id cellular-location "Mipa" "GO:0032046" :name "micropexophagy-specific membrane apparatus") 
(def-indiv-with-id cellular-location "Phagophore" "GO:0061908" :name "phagophore") 
(def-indiv-with-id cellular-location "PSj" "UP:SL-0192" :name "Paranodal septate junction") 
(def-indiv-with-id cellular-location "Stv" "GO:0097547" :name "synaptic vesicle protein transport vesicle") 
(def-indiv-with-id cellular-location "NlB" "GO:1990934" :name "nucleolus-like body") 
