(in-package :sparser)

;;

(define-protein "HGNC:756" ("ASPA" "aspartoacylase")) 
(define-protein "UP:Q9S795" ("BADH" "Betaine aldehyde dehydrogenase 1, chloroplastic")) 
(define-protein "HGNC:1020" ("BCS" "BCS1 homolog, ubiquinol-cytochrome c reductase complex chaperone")) 
(define-protein "NCIT:C97584" ("BDE" "HOXD13")) 
(define-protein "NCIT:C104890" ("BPA" "DST")) 
(define-protein "UP:P86970" ("BPL" "C-type lectin BpLec")) 
(define-protein "NCIT:C126547" ("BSS" "GP1BA")) 
(define-protein "UP:P41365" ("CALB" "Lipase B")) 
(define-protein "NCIT:C107578" ("CGAT" "SLC18A1")) 
(define-protein "UP:P07469" ("CSI" "Corticostatin 1")) 
(define-protein "NCIT:C51755" ("CTPA" "EPHA2")) 
(define-protein "NCIT:C75412" ("DGCR" "TBX1")) 
(define-protein "UP:Q8JIR6" ("DMY" "Doublesex- and mab-3-related transcription factor 1Y")) 
(define-protein "UP:P16620" ("DPTP" "Tyrosine-protein phosphatase 69D")) 
(define-protein "UP:A1YPR3" ("EVE" "2-epi-5-epi-valiolone epimerase")) 
(define-protein "UP:P21760" ("EXFABP" "Extracellular fatty acid-binding protein")) 
(define-protein "NCIT:C113586" ("FMD" "FLNA")) 
(define-protein "UP:Q9NFH9" ("HCB" "Hemocyanin B chain")) 
(define-protein "NCIT:C54307" ("HYPD" "MAGEA3")) 
(define-protein "UP:Q04557" ("IAH" "Indoleacetamide hydrolase")) 
(define-protein "NCIT:C152982" ("ICH" "COL4A2")) 
(define-protein "NCIT:C52798" ("IFI" "IFNG")) 
(define-protein "HGNC:18163" ("IFNE" "interferon epsilon")) 
(define-protein "HGNC:21714" ("IFNK" "interferon kappa")) 
(define-protein "NCIT:C118231" ("IGO" "IGLL1")) 
(define-protein "HGNC:10437" ("KLS" "ribosomal protein S6 kinase B2")) 
(define-protein "NCIT:C51245" ("MSV" "MOS")) 
(define-protein "HGNC:7678" ("NDP" "norrin cystine knot growth factor NDP")) 
(define-protein "UP:P09142" ("NFP" "Non-fluorescent flavoprotein")) 
(define-protein "HGNC:218" ("NPI" "ADAM metallopeptidase with thrombospondin type 1 motif 2")) 
(define-protein "HGNC:30621" ("NRS" "sphingolipid transporter 1 (putative)")) 
(define-protein "NCIT:C54312" ("NTI" "MGP")) 
(define-protein "UP:P17958" ("ORFV" "Uncharacterized 25.6 kDa protein in aldolase locus")) 
(define-protein "NCIT:C91333" ("PCCF" "F5")) 
(define-protein "HGNC:8999" ("PISD" "phosphatidylserine decarboxylase")) 
(define-protein "UP:Q9T216" ("RDF" "Recombination directionality factor")) 
(define-protein "UP:P00335" ("RDH" "Ribitol 2-dehydrogenase")) 
(define-protein "UP:P68747" ("ROCT" "Ornithine carbamoyltransferase 2, anabolic")) 
(define-protein "UP:P50748" ("RODS" "Kinetochore-associated protein 1")) 
(define-protein "UP:Q9MYK8" ("RXN" "Prorelaxin")) 
(define-protein "NCIT:C21022" ("TCAD" "cadherin-13")) 
(define-protein "NCIT:C52279" ("VDBP" "GC")) 
(define-protein "UP:P83255" ("VLF" "Snake venom metalloproteinase fibrolase")) 
(define-protein "UP:P91664" ("dmax" "Protein max")) 
(define-protein "UP:P10104" ("fibritin" "Fibritin")) 
(define-protein "UP:Q91061" ("ictacalcin" "Ictacalcin")) 
(define-protein "UP:P16405" ("ora" "Octapeptide-repeat antigen")) 
(define-protein "UP:Q06902" ("pepo" "Aspergillopepsin-1")) 
(define-protein "UP:Q8IDR3" ("pfma" "Myosin-A")) 
(define-protein "HGNC:26810" ("pika" "EGF like, fibronectin type III and laminin G domains")) 
(define-protein "UP:Q8VCZ9" ("pos" "Hydroxyproline dehydrogenase")) 
(define-protein "HGNC:11610" ("tele" "titin-cap")) 
(define-protein "UP:Q9SBK8" ("thionin" "Thionin")) 
(define-protein "HGNC:29369" ("unk" "unk zinc finger")) 
(define-protein "HGNC:2294" ("viii" "cytochrome c oxidase subunit 8A")) 
(define-protein "UP:Q8GW43" ("AONs" "8-amino-7-oxononanoate synthase")) 
(define-protein "NCIT:C75865" ("Ahx" "NR0B1")) 
(define-protein "UP:P63237" ("CspE" "Cold shock-like protein CspE")) 
(define-protein "UP:P30823" ("EcoR" "High affinity cationic amino acid transporter 1")) 
(define-protein "UP:P32187" ("Ependymin" "Ependymin")) 
(define-protein "UP:P01080" ("Iik" "Proteinase inhibitor type-2 K")) 
(define-protein "NCIT:C137976" ("LOCs" "LAMA3")) 
(define-protein "UP:Q9JLI6" ("MScl" "Selenocysteine lyase")) 
(define-protein "UP:P07636" ("MuA" "DDE-recombinase A")) 
(define-protein "UP:Q9I834" ("Mvi" "Basic phospholipase A2 homolog 2")) 
(define-protein "UP:Q98267" ("Nphi" "Nucleoside triphosphatase I")) 
(define-protein "NCIT:C74969" ("PRTs" "ARX")) 
(define-protein "HGNC:27230" ("RBs" "establishment of sister chromatid cohesion N-acetyltransferase 2")) 
(define-protein "NCIT:C157308" ("Req" "DPF2")) 
(define-protein "UP:A0ZZH6" ("SPase" "Sucrose phosphorylase {ECO:0000303|PubMed:14740189, ECO:0000303|PubMed:14756551, ECO:0000303|PubMed:20691225}")) 
(define-protein "UP:Q5EXX3" ("Zenon" "Zinc finger and BTB domain-containing protein 38")) 
(define-protein "NCIT:C116409" ("tgD" "ABCA1"))


;;

(define-protein "NCIT:C84254" ("DBP-MAF" "vitamin D-binding protein")) 
(define-protein "NCIT:C20528" ("CD40-Ligand" "CD40 ligand")) 
(define-protein "UP:P01483" ("Bot-II" "Neurotoxin Bot2")) 
(define-protein "UP:P01488" ("Bot-I" "Alpha-toxin Bot1")) 
(define-protein "NCIT:C129919" ("AB-3" "human anti-anti-idiotype antibody")) 
(define-protein "UP:P28171" ("IFN-τ" "Interferon tau")) 
(define-protein "UP:Q86WN2" ("IFN-ε" "Interferon epsilon")) 
(define-protein "UP:Q6KCA4" ("ICP-1" "Amoebiasin-1")) 
(define-protein "UP:O46677" ("GROβ" "Growth-regulated protein homolog beta")) 
(define-protein "UP:P21760" ("Ex-FABP" "Extracellular fatty acid-binding protein")) 
(define-protein "UP:Q1HVI8" ("EBNA-LP" "Epstein-Barr nuclear antigen leader protein")) 
(define-protein "UP:Q03003" ("ORFs-e" "Uncharacterized protein in P47K 3'region")) 
(define-protein "UP:P21290" ("ORF-7" "Protein ADP-ribose pyrophosphatase ORF38")) 
(define-protein "UP:Q5U9S1" ("MBL-A" "Mannose-binding protein A")) 
(define-protein "UP:P03145" ("L-HBsAg" "Large envelope protein")) 
(define-protein "UP:Q9SPK5" ("JFH-S" "Formate--tetrahydrofolate ligase")) 
(define-protein "NCIT:C118114" ("Interleukin-27" "interleukin-27")) 
(define-protein "UP:Q8IZJ0" ("IFNλ2" "Interferon lambda-2")) 
(define-protein "UP:P16805" ("TRL-7" "Uncharacterized protein IRL7")) 
(define-protein "UP:P84726" ("TIR-NBS-LRR" "Putative disease resistance protein PS10")) 
(define-protein "UP:P30019" ("S-HBsAg" "Small envelope protein")) 
(define-protein "UP:P58261" ("PSK-α" "Phytosulfokine-alpha")) 
(define-protein "UP:A0QZ12" ("PPMV-1" "Polyprenol monophosphomannose synthase")) 
(define-protein "UP:Q60420" ("beta-1" "Transcription factor 12")) 
(define-protein "UP:P15144" ("aminopeptidase-N" "Aminopeptidase N")) 
(define-protein "UP:P81425" ("act-3" "Dipeptidyl peptidase 4")) 
(define-protein "UP:Q9PT40" ("VLP2" "Venom serine proteinase-like protein 2")) 
(define-protein "NCIT:C126413" ("VEGF-165" "vascular endothelial growth factor A 165 isoform")) 
(define-protein "UP:P85008" ("defensins-1" "Defensin-1")) 
(define-protein "UP:Q8W034" ("hRNP1" "Heterogeneous nuclear ribonucleoprotein 1")) 
(define-protein "UP:Q0VIL3" ("omp-1" "Otolith matrix protein 1")) 
(define-protein "NCIT:C88047" ("neurofilament-M" "neurofilament medium polypeptide")) 
(define-protein "UP:A0A0C5XL88" ("mono-ADP-ribosyltransferases" "Prs ADP-ribosylating toxin")) 
(define-protein "UP:Q99289" ("t−l" "Thermolabile hemolysin")) 
(define-protein "UP:Q8S8Q6" ("tetraspanin-8" "Tetraspanin-8")) 
(define-protein "UP:G8YXZ9" ("t-th" "Tetrathionate hydrolase")) 
(define-protein "NCIT:C20495" ("β–interferon" "interferon beta")) 
(define-protein "NCIT:C17433" ("αβTCR" "T-cell receptor alpha-beta")) 
(define-protein "UP:P06733" ("α-enolase" "Alpha-enolase")) 
(define-protein "NCIT:C51755" ("CTP-A" "EPHA2")) 
(define-protein "HGNC:1814" ("CEACAMs-1" "CEA cell adhesion molecule 1")) 
(define-protein "UP:O43246" ("CAT-4" "Cationic amino acid transporter 4")) 
(define-protein "HGNC:1118" ("BstB1" "bone marrow stromal cell antigen 1")) 
(define-protein "HGNC:1085" ("Binp3L" "BCL2 interacting protein 3 like")) 
(define-protein "HGNC:11551" ("BMRF1" "BRF1 RNA polymerase III transcription initiation factor subunit")) 
(define-protein "UP:Q8TD06" ("AG-3" "Anterior gradient protein 3")) 
(define-protein "NCIT:C26318" ("IFN-αA" "interferon alpha-2")) 
(define-protein "HGNC:18364" ("IFN-l2" "interferon lambda 2")) 
(define-protein "NCIT:C154135" ("PDCA-1" "BST2")) 
(define-protein "HGNC:23721" ("PARP-13" "zinc finger CCCH-type containing, antiviral 1")) 
(define-protein "HGNC:14374" ("NKRP1" "NLR family pyrin domain containing 1")) 
(define-protein "NCIT:C132076" ("KIR2DS3" "KIR2DS3")) 
(define-protein "UP:A6NMB1" ("Siglec-16" "Sialic acid-binding Ig-like lectin 16")) 
(define-protein "NCIT:C129051" ("cystathionine-β-synthase" "cystathionine beta-synthase")) 
(define-protein "HGNC:2442" ("cs-5" "chorionic somatomammotropin hormone like 1")) 
(define-protein "UP:Q9GZU1" ("ml−1" "Mucolipin-1")) 
(define-protein "HGNC:41" ("mAb-C2" "ATP binding cassette subfamily B member 10")) 
(define-protein "UP:Q9SF40" ("l−1" "60S ribosomal protein L4-1")) 
(define-protein "NCIT:C17772" ("pGPT-1" "CD44 antigen")) 
(define-protein "NCIT:C53116" ("p65" "RELA")) 
(define-protein "UP:Q6VZT9" ("vBcl-2" "Apoptosis regulator Bcl-2 homolog")) 
(define-protein "HGNC:11782" ("t−h" "tyrosine hydroxylase")) 
(define-protein "UP:P01009" ("α1-antitrypsins" "Alpha-1-antitrypsin")) 
(define-protein "NCIT:C105012" ("α1-ATs" "alpha-1-antitrypsin")) 
(define-protein "HGNC:1371" ("Cas12" "carbonic anhydrase 12")) 
(define-protein "HGNC:1445" ("CaM-II" "calmodulin 2")) 
(define-protein "NCIT:C150119" ("COVID-9" "PRKCD")) 
(define-protein "HGNC:1820" ("CEACAMs-8" "CEA cell adhesion molecule 8")) 
(define-protein "HGNC:1323" ("C4-a" "complement C4A (Rodgers blood group)")) 
(define-protein "NCIT:C52297" ("AAAC-3" "SLC25A6")) 
(define-protein "HGNC:21714" ("IFN-ks" "interferon kappa")) 
(define-protein "NCIT:C97810" ("HOM-MEL-40" "SSX2")) 
(define-protein "HGNC:13525" ("HERV-W" "endogenous retrovirus group W member 1, envelope")) 
(define-protein "HGNC:27030" ("GS-3" "DnaJ heat shock protein family (Hsp40) member C21")) 
(define-protein "NCIT:C51304" ("ERC-55" "RCN2")) 
(define-protein "HGNC:7596" ("MyR1" "myosin IB")) 
(define-protein "HGNC:10923" ("MCT-7" "solute carrier family 16 member 2")) 
(define-protein "HGNC:30740" ("TAARs−2" "threonyl-tRNA synthetase 2, mitochondrial")) 
(define-protein "HGNC:18430" ("SF-2001" "SLAM family member 9")) 
(define-protein "HGNC:22939" ("pan-8" "NLR family pyrin domain containing 14")) 
(define-protein "HGNC:9339" ("pRB3" "proline rich protein BstNI subfamily 3")) 
(define-protein "HGNC:9522" ("psg-5" "pregnancy specific beta-1-glycoprotein 5")) 
(define-protein "NCIT:C50385" ("top-3" "TOP3A")) 
;;;

(define-protein "NCIT:C162401" ("Étoile" "KHDRBS3")) 
(define-protein "HGNC:12816" ("xPx" "XPC complex subunit, DNA damage recognition and repair factor")) 
(define-protein "HGNC:11295" ("sRLU" "sarcalumenin")) 
(define-protein "NCIT:C50964" ("rprA" "EXTL3")) 
(define-protein "HGNC:25410" ("rlucVP" "RAB40A like")) 
(define-protein "HGNC:668" ("rhyB" "ras homolog family member B")) 
(define-protein "HGNC:28923" ("rTadglob" "diacylglycerol lipase beta")) 
(define-protein "UP:Q9FRV0" ("rSCV" "Basic endochitinase C")) 
(define-protein "UP:Q96E11" ("rORF" "Ribosome-recycling factor, mitochondrial")) 
(define-protein "UP:P13693" ("rCTP" "Translationally-controlled tumor protein")) 
(define-protein "HGNC:28923" ("rAdglob" "diacylglycerol lipase beta")) 
(define-protein "UP:P48532" ("ptDNA" "Pleiotrophin-A")) 
(define-protein "HGNC:19012" ("prSCV" "corin, serine peptidase")) 
(define-protein "HGNC:9336" ("prME" "preferentially expressed antigen in melanoma")) 
(define-protein "UP:Q9LCB4" ("pmsB" "2-phosphinomethylmalate synthase")) 
(define-protein "UP:Q9NUI1" ("pcDR" "Peroxisomal 2,4-dienoyl-CoA reductase")) 
(define-protein "HGNC:9339" ("pWRG" "proline rich protein BstNI subfamily 3")) 
(define-protein "UP:Q99K85" ("pSMART" "Phosphoserine aminotransferase")) 
(define-protein "HGNC:9446" ("pRRL" "prolactin receptor")) 
(define-protein "NCIT:C92656" ("pQCXIP" "CPQ")) 
(define-protein "UP:P81863" ("pQCXIH" "Pardaxin-1")) 
(define-protein "HGNC:11054" ("pProT" "solute carrier family 6 member 7")) 
(define-protein "HGNC:8070" ("pNGVL" "nuclear VCP like")) 
(define-protein "NCIT:C17911" ("pLKO" "serine/Threonine-protein kinase PLK1")) 
(define-protein "HGNC:8918" ("pGEX" "phosphate regulating endopeptidase homolog X-linked")) 
(define-protein "HGNC:8830" ("pGEMT" "phosphatidylethanolamine N-methyltransferase")) 
(define-protein "NCIT:C97740" ("pEYFP" "PRF1")) 
(define-protein "UP:Q9U6Y8" ("pDsRed" "Red fluorescent protein drFP583")) 
(define-protein "NCIT:C51521" ("pCSFLW" "PGF")) 
(define-protein "HGNC:20589" ("pCMVi" "potassium channel modulatory factor 1")) 
(define-protein "HGNC:8729" ("pCDNA" "proliferating cell nuclear antigen")) 
(define-protein "HGNC:8646" ("pBCD" "pterin-4 alpha-carbinolamine dehydratase 1")) 
(define-protein "NCIT:C92656" ("pAcGP" "CPQ")) 
(define-protein "UP:Q01647" ("pAPEC" "Phosphoenolpyruvate carboxylase")) 
(define-protein "HGNC:7981" ("Ntot" "nuclear receptor subfamily 4 group A member 2")) 
(define-protein "UP:Q8NEV4" ("myosinIIA" "Myosin-IIIa")) 
(define-protein "NCIT:C126622" ("myosinII" "unconventional myosin-If")) 
(define-protein "UP:Q58502" ("mmgDthat" "Deoxyuridine 5'-triphosphate nucleotidohydrolase")) 
(define-protein "HGNC:18121" ("mRFP" "membrane frizzled-related protein")) 
(define-protein "UP:Q99MH6" ("mNDK" "Protein naked cuticle homolog 1")) 
(define-protein "HGNC:19331" ("mMAbs" "metabolism of cobalamin associated B")) 
(define-protein "HGNC:23723" ("mCEACAM" "cerebral endothelial cell adhesion molecule")) 
(define-protein "UP:P09333" ("lowP" "Outer cell wall protein")) 
(define-protein "HGNC:6187" ("iVLP" "involucrin")) 
(define-protein "UP:P14617" ("iRRV" "Insulin receptor-related protein")) 
(define-protein "UP:Q96QV1" ("highP" "Hedgehog-interacting protein")) 
(define-protein "NCIT:C116607" ("haveWhere" "HAVCR1")) 
(define-protein "UP:P50312" ("hPGK" "Phosphoglycerate kinase, glycosomal")) 
(define-protein "HGNC:25676" ("gerAB" "golgin, RAB6 interacting")) 
(define-protein "NCIT:C51558" ("fHCs" "LDLR")) 
(define-protein "HGNC:3590" ("fAGP" "fibroblast activation protein alpha")) 
(define-protein "UP:P16930" ("fAAA" "Fumarylacetoacetase")) 
(define-protein "NCIT:C118583" ("emPCR" "PROCR")) 
(define-protein "NCIT:C97532" ("cytoHubba" "SPECC1")) 
(define-protein "HGNC:2085" ("cVLPs" "colipase")) 
(define-protein "HGNC:1966" ("asHere" "cholinergic receptor nicotinic epsilon subunit")) 
(define-protein "UP:Q03393" ("ZipTips" "6-pyruvoyl tetrahydrobiopterin synthase")) 
(define-protein "NCIT:C118473" ("Zeba" "trans-activator protein BZLF1")) 
(define-protein "NCIT:C73663" ("YLLs" "SETD2")) 
(define-protein "UP:Q07016" ("Xmaxj" "Protein max")) 
(define-protein "HGNC:12811" ("Xjk" "X-linked Kx blood group")) 
(define-protein "NCIT:C147566" ("XecnGV" "ARHGEF10")) 
(define-protein "NCIT:C113822" ("WHsAg" "AHSG")) 
(define-protein "HGNC:17902" ("WHcAg" "COMM domain containing 5")) 
(define-protein "UP:Q02221" ("Voxiva" "Cytochrome c oxidase subunit 6A2, mitochondrial")) 
(define-protein "NCIT:C68596" ("Verorab" "aurora kinase B")) 
(define-protein "HGNC:28498" ("VaxiJen" "vexin")) 
(define-protein "UP:J3S836" ("VFs" "Venom factor")) 
(define-protein "HGNC:12516" ("UtoC" "urocortin")) 
(define-protein "UP:O48947" ("Uthai" "Cellulose synthase A catalytic subunit 2 [UDP-forming]")) 
(define-protein "HGNC:13205" ("UTRdb" "STE20 related adaptor beta")) 
(define-protein "UP:O77404" ("Tyx" "Tryparedoxin")) 
(define-protein "HGNC:14607" ("Twincore" "TINCR ubiquitin domain containing")) 
(define-protein "UP:Q16473" ("Tunxi" "Putative tenascin-XA")) 
(define-protein "NCIT:C132323" ("TtoC" "RHBDF2")) 
(define-protein "UP:P25697" ("TprK" "Phosphoribulokinase, chloroplastic")) 
(define-protein "NCIT:C94788" ("Thang" "TNFSF13B")) 
(define-protein "HGNC:11577" ("Tanz" "tafazzin")) 
(define-protein "NCIT:C17448" ("Taitai" "pancreatic secretory trypsin inhibitor")) 
(define-protein "NCIT:C82942" ("TIANprep" "CTNND2")) 
(define-protein "NCIT:C131590" ("TIANamp" "POLR3B")) 
(define-protein "UP:Q8AWG6" ("THEKxS" "Hematopoietically-expressed homeobox protein hhex")) 
(define-protein "HGNC:9898" ("Suwon" "RNA binding motif protein 12")) 
(define-protein "UP:P33183" ("Sunyaev" "Nigrin b")) 
(define-protein "UP:P11916" ("SubLoc" "Oocytes ribonuclease")) 
(define-protein "UP:P22542" ("StuI" "Heat-stable enterotoxin II")) 
(define-protein "HGNC:11424" ("Stratton" "striatin")) 
(define-protein "UP:P22629" ("Steptavidin" "Streptavidin")) 
(define-protein "NCIT:C53130" ("Stbl" "EEF1A2")) 
(define-protein "UP:O17901" ("StataCorp" "Probable coatomer subunit zeta")) 
(define-protein "NCIT:C38583" ("StartingBlock" "elongation factor 1-alpha 2")) 
(define-protein "HGNC:29361" ("SpeI" "selenoprotein I")) 
(define-protein "NCIT:C37271" ("Sorp" "tyrosine-protein phosphatase non-receptor type substrate 1")) 
(define-protein "NCIT:C119717" ("Sogo" "SGO1")) 
(define-protein "HGNC:10802" ("Softspec" "surfactant protein C")) 
(define-protein "HGNC:32322" ("Sixbey" "scleraxis bHLH transcription factor")) 
(define-protein "UP:Q920G3" ("SigCleave" "Sialic acid-binding Ig-like lectin 5")) 
(define-protein "HGNC:26742" ("Shatin" "N-acetyltransferase 8 like")) 
(define-protein "HGNC:30397" ("Sequenom" "selenoprotein M")) 
(define-protein "HGNC:10739" ("SeqMan" "semaphorin 6B")) 
(define-protein "NCIT:C17313" ("Sendi" "cell surface glycoprotein MUC18")) 
(define-protein "NCIT:C21463" ("SealSafe" "DNA ligase 4")) 
(define-protein "HGNC:30377" ("Schreib" "scribble planar cell polarity protein")) 
(define-protein "UP:P32644" ("Scheliga" "Putative ATP-dependent RNA helicase ECM32")) 
(define-protein "UP:Q9QYF1" ("Scheld" "Retinol dehydrogenase 11")) 
(define-protein "UP:P01144" ("Sauvigny" "Sauvagin")) 
(define-protein "UP:P49187" ("Sapkota" "Mitogen-activated protein kinase 10")) 
(define-protein "HGNC:27934" ("SPEPlip" "speckle type BTB/POZ protein like")) 
(define-protein "UP:P16641" ("SIMjk" "Taurocyamine kinase")) 
(define-protein "HGNC:20335" ("SCoV" "short coiled-coil protein")) 
(define-protein "HGNC:32322" ("SCgHZ" "scleraxis bHLH transcription factor")) 
(define-protein "NCIT:C102505" ("SAQc" "QPCT")) 
(define-protein "HGNC:16858" ("Rowntree" "USP6 N-terminal like")) 
(define-protein "HGNC:14211" ("RUblank" "B cell linker")) 
(define-protein "UP:Q7F613" ("RUSick" "Secretory carrier-associated membrane protein 2")) 
(define-protein "UP:P30784" ("RTAclv" "Delta-stichotoxin-Hcr1c")) 
(define-protein "UP:O64392" ("RNaseOUT" "Wheatwin-1")) 
(define-protein "NCIT:C51429" ("RHRc" "ADRB1")) 
(define-protein "NCIT:C52113" ("RDTs" "SMARCB1")) 
(define-protein "HGNC:25179" ("RDCoV" "nucleoredoxin like 1")) 
(define-protein "NCIT:C92519" ("Qij" "SIK2")) 
(define-protein "HGNC:9358" ("QIAprep" "prolyl endopeptidase")) 
(define-protein "HGNC:1472" ("QIAmp" "cathelicidin antimicrobial peptide")) 
(define-protein "HGNC:18" ("QIAamp" "angio associated migratory cell protein")) 
(define-protein "HGNC:9052" ("Pulau" "plasminogen activator, urokinase")) 
(define-protein "HGNC:9682" ("Ptprzeta" "protein tyrosine phosphatase receptor type T")) 
(define-protein "HGNC:9500" ("PseAAC" "prostate stem cell antigen")) 
(define-protein "UP:P69006" ("ProteomeLab" "Protamine-B")) 
(define-protein "NCIT:C131324" ("ProteinLynx" "lithostathine-1-alpha")) 
(define-protein "UP:P20382" ("Promochem" "Pro-MCH")) 
(define-protein "UP:O88273" ("PredAcc" "Gremlin-2")) 
(define-protein "HGNC:9705" ("PovRay" "PVR cell adhesion molecule")) 
(define-protein "NCIT:C54318" ("Pizarro" "MPZL1")) 
(define-protein "UP:Q03198" ("PiuA" "Proteinase inhibitor I-A")) 
(define-protein "NCIT:C51105" ("Phuket" "CALM1")) 
(define-protein "HGNC:8876" ("Pfafll" "phosphofructokinase, liver type")) 
(define-protein "HGNC:21464" ("Pernod" "NLR family pyrin domain containing 10")) 
(define-protein "HGNC:9319" ("PPxY" "protein phosphatase 4 catalytic subunit")) 
(define-protein "UP:P02872" ("PNAs" "Galactose-binding lectin")) 
(define-protein "HGNC:16705" ("PLoS" "terminal nucleotidyltransferase 4A")) 
(define-protein "UP:P41736" ("PCTmax" "Delta-paraponeritoxin-Pc1a")) 
(define-protein "HGNC:18966" ("PCPá" "cysteine sulfinic acid decarboxylase")) 
(define-protein "HGNC:22644" ("OtoChip" "otospiralin")) 
(define-protein "NCIT:C37276" ("Offenbury" "interferon alpha/Beta receptor 1")) 
(define-protein "HGNC:8061" ("NimbleGen" "NUMB like endocytic adaptor protein")) 
(define-protein "NCIT:C52103" ("Ngoc" "RTN4")) 
(define-protein "HGNC:2467" ("Ngac" "chondroitin sulfate proteoglycan 5")) 
(define-protein "HGNC:29920" ("NeseNPV" "centromere protein V")) 
(define-protein "HGNC:30399" ("NeleNPV" "selenoprotein V")) 
(define-protein "NCIT:C128942" ("NcoI" "MT-CO1")) 
(define-protein "HGNC:17996" ("Nargis" "N-acetylglutamate synthase")) 
(define-protein "UP:P45671" ("NarI" "DNA-binding transcriptional regulator NtrC")) 
(define-protein "UP:Q18179" ("NaPyr" "Putative neuropeptide Y receptor 11")) 
(define-protein "HGNC:736" ("NaAz" "N-acylethanolamine acid amidase")) 
(define-protein "NCIT:C50989" ("NVivo" "XRCC5")) 
(define-protein "HGNC:218" ("NPIs" "ADAM metallopeptidase with thrombospondin type 1 motif 2")) 
(define-protein "HGNC:7863" ("NNTs" "nicotinamide nucleotide transhydrogenase")) 
(define-protein "NCIT:C33999" ("NFn" "neogenin")) 
(define-protein "NCIT:C20433" ("NDFs" "neuregulin")) 
(define-protein "NCIT:C25276" ("NCAMs" "neural cell adhesion molecule 1")) 
(define-protein "UP:Q9JLI6" ("MySQL" "Selenocysteine lyase")) 
(define-protein "HGNC:23251" ("Muffat" "acyl-CoA wax alcohol acyltransferase 2")) 
(define-protein "HGNC:7211" ("Mpigi" "N-methylpurine DNA glycosylase")) 
(define-protein "UP:P01515" ("MpeX" "Mastoparan-X")) 
(define-protein "HGNC:13363" ("Moxley" "Mix paired-like homeobox")) 
(define-protein "HGNC:7141" ("Modilon" "motilin")) 
(define-protein "HGNC:7154" ("MmeI" "membrane metalloendopeptidase")) 
(define-protein "UP:P35755" ("Mirpur" "Iron-utilization periplasmic protein")) 
(define-protein "HGNC:8517" ("Miaoli" "otoraplin")) 
(define-protein "UP:Q8X151" ("Menlo" "Manganese lipoxygenase")) 
(define-protein "HGNC:6826" ("MenB" "mannosidase alpha class 2B member 1")) 
(define-protein "UP:P21376" ("Meleagrid" "Meleagrin")) 
(define-protein "HGNC:29622" ("Mcapt" "malonyl-CoA-acyl carrier protein transacylase")) 
(define-protein "HGNC:6906" ("Mattek" "megakaryocyte-associated tyrosine kinase")) 
(define-protein "UP:Q55FT4" ("Matsunami" "Probable serine/threonine-protein kinase tsuA")) 
(define-protein "HGNC:26689" ("MasterPure" "MEF2 activating motif and SAP domain containing transcriptional regulator")) 
(define-protein "NCIT:C51375" ("MapSolver" "MPL")) 
(define-protein "HGNC:24628" ("Maixin" "mediator complex subunit 28")) 
(define-protein "HGNC:29679" ("MagMax" "presequence translocase associated motor 16")) 
(define-protein "NCIT:C52548" ("MVRAs" "MRAS")) 
(define-protein "UP:A0R6E0" ("MTases" "Trehalose synthase/amylase TreS")) 
(define-protein "UP:P05402" ("MPRci" "Placental prolactin-related protein 1")) 
(define-protein "HGNC:7188" ("MNVwt" "MAX network transcriptional repressor")) 
(define-protein "NCIT:C53096" ("MFIx" "NFIX")) 
(define-protein "HGNC:16460" ("MFIr" "FERM, ARH/RhoGEF and pleckstrin domain protein 2")) 
(define-protein "HGNC:21156" ("MBLrev" "polycomb group ring finger 6")) 
(define-protein "UP:Q8N895" ("MAXIscript" "Zinc finger protein 366")) 
(define-protein "NCIT:C101453" ("Löfdahl" "ECT2L")) 
(define-protein "UP:Q9YML3" ("Lynbrook" "Uncharacterized Bro-N domain-containing protein J")) 
(define-protein "UP:P19990" ("LuIIIV" "Leucokinin-8")) 
(define-protein "UP:C0HK42" ("Llij" "Lasioglossin-1")) 
(define-protein "UP:Q5ECE3" ("LipoP" "Lopap")) 
(define-protein "HGNC:29503" ("LiCor" "ligand dependent nuclear receptor corepressor")) 
(define-protein "UP:P84907" ("Leica" "Snake venom metalloproteinase leucurolysin-A")) 
(define-protein "NCIT:C112158" ("LTNPs" "C1GALT1C1")) 
(define-protein "NCIT:C52274" ("LANs" "ABCB6")) 
(define-protein "UP:P58704" ("Kyanasur" "Cyanate hydratase")) 
(define-protein "NCIT:C125198" ("Kpn" "PKN1")) 
(define-protein "UP:P60602" ("Kolyushin" "Reactive oxygen species modulator 1")) 
(define-protein "UP:O70503" ("Kikai" "Very-long-chain 3-oxoacyl-CoA reductase")) 
(define-protein "NCIT:C118592" ("Katy" "F11R")) 
(define-protein "HGNC:6404" ("Kapton" "kaptin, actin binding protein")) 
(define-protein "HGNC:19084" ("Kamel" "junction adhesion molecule like")) 
(define-protein "NCIT:C18400" ("KIPyV" "platelet glycoprotein 4")) 
(define-protein "HGNC:4065" ("KGaA" "glucosidase alpha, acid")) 
(define-protein "NCIT:C101426" ("Jinhua" "KIF5B")) 
(define-protein "HGNC:3355" ("Jenpep" "glutamyl aminopeptidase")) 
(define-protein "HGNC:19309" ("Janke" "KN motif and ankyrin repeat domains 1")) 
(define-protein "HGNC:6369" ("Ivarsson" "kallikrein related peptidase 8")) 
(define-protein "UP:Q655X8" ("Isaiah" "Probable allantoate deiminase")) 
(define-protein "UP:Q9NZJ4" ("Isaacson" "Sacsin")) 
(define-protein "UP:P0DQD3" ("InflBw" "Internalin B")) 
(define-protein "UP:P0DQD3" ("InflB" "Internalin B")) 
(define-protein "UP:Q90334" ("ITRs" "Isotocin receptor")) 
(define-protein "UP:Q9FMN4" ("IDClight" "Thioredoxin-like protein Clot")) 
(define-protein "HGNC:18412" ("HyPhy" "zinc finger DHHC-type palmitoyltransferase 17")) 
(define-protein "NCIT:C118985" ("HomPW" "Mu-type opioid receptor")) 
(define-protein "NCIT:C52497" ("Hoerdt" "TERT")) 
(define-protein "NCIT:C52088" ("Hneigh" "NEURL1")) 
(define-protein "HGNC:20166" ("Hknown" "KH and NYN domain containing")) 
(define-protein "NCIT:C129053" ("Hjarre" "AKR1C3")) 
(define-protein "HGNC:30796" ("HisTrap" "serine/threonine kinase receptor associated protein")) 
(define-protein "UP:Q14671" ("HisPurTM" "Pumilio homolog 1")) 
(define-protein "UP:Q96QV1" ("Hiep" "Hedgehog-interacting protein")) 
(define-protein "HGNC:17192" ("HiTrap" "TIR domain containing adaptor protein")) 
(define-protein "UP:Q5JRX3" ("HiPrep" "Presequence protease, mitochondrial")) 
(define-protein "NCIT:C50952" ("HiLoad" "LIF")) 
(define-protein "UP:Q9M5G3" ("HetPW" "Translationally-controlled tumor protein homolog")) 
(define-protein "HGNC:6296" ("HensBC" "potassium voltage-gated channel subfamily Q member 2")) 
(define-protein "UP:Q9GZZ1" ("Hazan" "N-alpha-acetyltransferase 50")) 
(define-protein "NCIT:C134184" ("Haorui" "ARIH1")) 
(define-protein "UP:Q9GZZ1" ("Haan" "N-alpha-acetyltransferase 50")) 
(define-protein "HGNC:4982" ("HMGBs" "hydroxymethylbilane synthase")) 
(define-protein "NCIT:C20705" ("HLAs" "MHC class II protein")) 
(define-protein "HGNC:20570" ("HLAIs" "cyclin L2")) 
(define-protein "UP:Q5NE16" ("HCTplus" "Putative inactive cathepsin L-like protein CTSL3P")) 
(define-protein "NCIT:C50376" ("HAIs" "ST14")) 
(define-protein "UP:P0C8P8" ("Gurgaon" "Thiostrepton")) 
(define-protein "NCIT:C147570" ("GreeneChipVr" "ARHGEF10L")) 
(define-protein "NCIT:C525" ("GpppA" "glycophorin-A")) 
(define-protein "HGNC:23657" ("Gneg" "glucosamine (UDP-N-acetyl)-2-epimerase/N-acetylmannosamine kinase")) 
(define-protein "HGNC:4232" ("GmDNV" "glial cell derived neurotrophic factor")) 
(define-protein "HGNC:16973" ("Gijsbers" "protein phosphatase 1 regulatory subunit 17")) 
(define-protein "UP:Q7Z4K8" ("Genway" "Tripartite motif-containing protein 46")) 
(define-protein "NCIT:C92175" ("Genosys" "FOXD3")) 
(define-protein "HGNC:21153" ("Garilhe" "ring finger protein 128")) 
(define-protein "NCIT:C16614" ("Gaghi" "GAG gene")) 
(define-protein "HGNC:4114" ("GagL" "galanin and GMAP prepropeptide")) 
(define-protein "UP:P05804" ("GUVs" "Beta-glucuronidase")) 
(define-protein "UP:P03732" ("GPUs" "Tail tube terminator protein")) 
(define-protein "HGNC:4296" ("GLaz" "galactosidase alpha")) 
(define-protein "UP:Q9UWR6" ("GFPpos" "Geranylfarnesyl diphosphate synthase")) 
(define-protein "UP:A6QM00" ("GAsDock" "Acidic amino acid decarboxylase GADL1")) 
(define-protein "HGNC:4141" ("GAPDHRev" "glyceraldehyde-3-phosphate dehydrogenase")) 
(define-protein "HGNC:4141" ("GAPDHFwd" "glyceraldehyde-3-phosphate dehydrogenase")) 
(define-protein "UP:P15286" ("Fluka" "Flagellar regulator flk")) 
(define-protein "UP:Q04666" ("FRhL" "Transcription factor HES-1")) 
(define-protein "NCIT:C68596" ("Eurolab" "aurora kinase B")) 
(define-protein "UP:Q197W8" ("Ettan" "Microtubule-binding protein TANGLED")) 
(define-protein "NCIT:C21372" ("Etiko" "cytoplasmic tyrosine-protein kinase BMX")) 
(define-protein "NCIT:C21372" ("Etika" "cytoplasmic tyrosine-protein kinase BMX")) 
(define-protein "NCIT:C131263" ("EpiSearch" "COMP")) 
(define-protein "NCIT:C17772" ("EpiScan" "CD44 antigen")) 
(define-protein "UP:Q5U259" ("Ellora" "ELAV-like protein 1-B")) 
(define-protein "HGNC:3246" ("EgHF" "ETS homologous factor")) 
(define-protein "HGNC:28861" ("Ebersberg" "caspase recruitment domain family member 18")) 
(define-protein "HGNC:3133" ("EbGP" "EBP cholestenol delta-isomerase")) 
(define-protein "UP:A3DDN1" ("EGDe" "Endoglucanase D")) 
(define-protein "NCIT:C75394" ("EBLVs" "SH2D1A")) 
(define-protein "HGNC:10601" ("Dynatech" "sodium channel epithelial 1 delta subunit")) 
(define-protein "HGNC:2960" ("Dynal" "deoxyribonuclease 2, lysosomal")) 
(define-protein "HGNC:2681" ("DxGxT" "death domain associated protein")) 
(define-protein "NCIT:C101298" ("Dunnett" "TSPYL2")) 
(define-protein "HGNC:15750" ("DsDNV" "destrin, actin depolymerizing factor")) 
(define-protein "UP:P11861" ("Dojindo" "1,2-dihydroxynaphthalene dioxygenase")) 
(define-protein "UP:Q8SWV6" ("Difco" "Protein adenylyltransferase Fic")) 
(define-protein "UP:Q9IAT6" ("DelCn" "Delta-like protein C")) 
(define-protein "HGNC:18144" ("Dassel" "dermatan sulfate epimerase like")) 
(define-protein "UP:P91943" ("DTAclv" "Protein pangolin, isoforms A/H/I/S")) 
(define-protein "UP:O89107" ("DNeasy" "Deoxyribonuclease gamma")) 
(define-protein "HGNC:2681" ("DExx" "death domain associated protein")) 
(define-protein "NCIT:C20693" ("Cytokertin" "cytokeratin")) 
(define-protein "HGNC:4141" ("CtGAPDH" "glyceraldehyde-3-phosphate dehydrogenase")) 
(define-protein "NCIT:C153276" ("CrleGV" "TDGF1")) 
(define-protein "HGNC:21011" ("Cpos" "carboxypeptidase O")) 
(define-protein "UP:Q54CU4" ("CoolSnap" "Colossin-A")) 
(define-protein "UP:P56871" ("Ciara" "Circulin-A")) 
(define-protein "UP:P47733" ("CellMask" "Sulfakinin")) 
(define-protein "HGNC:14013" ("Capecchi" "structural maintenance of chromosomes 4")) 
(define-protein "HGNC:23723" ("CEACAMb" "cerebral endothelial cell adhesion molecule")) 
(define-protein "HGNC:23723" ("CEACAMa" "cerebral endothelial cell adhesion molecule")) 
(define-protein "NCIT:C20451" ("CDFs" "interleukin-6")) 
(define-protein "HGNC:1712" ("CDAs" "cytidine deaminase")) 
(define-protein "UP:Q9RL17" ("BvCMO" "Baeyer-Villiger monooxygenase")) 
(define-protein "HGNC:30251" ("BsmBI" "BMP and activin membrane bound inhibitor")) 
(define-protein "NCIT:C52374" ("BsaH" "BLNK")) 
(define-protein "NCIT:C19865" ("Brahms" "BRAHMA")) 
(define-protein "HGNC:1133" ("BioTEK" "Bruton tyrosine kinase")) 
(define-protein "UP:Q9H694" ("BioCyc" "Protein bicaudal C homolog 1")) 
(define-protein "HGNC:1014" ("Becr" "BCR activator of RhoGEF and GTPase")) 
(define-protein "NCIT:C118242" ("BcAtrB" "CTRB1")) 
(define-protein "UP:P87362" ("BamH" "Bleomycin hydrolase")) 
(define-protein "NCIT:C120950" ("BLASTx" "CD48")) 
(define-protein "UP:P38506" ("Axxora" "Flap endonuclease Xni")) 
(define-protein "HGNC:2981" ("AusPep" "aspartyl aminopeptidase")) 
(define-protein "UP:Q9LIH6" ("Atun" "Uracil-DNA glycosylase, mitochondrial")) 
(define-protein "HGNC:360" ("Arieh" "autoimmune regulator")) 
(define-protein "UP:Q03343" ("ArcView" "Adenylate cyclase type 6")) 
(define-protein "UP:P02647" ("ApaI" "Apolipoprotein A-I")) 
(define-protein "NCIT:C33977" ("Antova" "RNA-binding protein nova-2")) 
(define-protein "NCIT:C16295" ("Antibiot" "antibody")) 
(define-protein "NCIT:C70547" ("Anas" "antinuclear antibody")) 
(define-protein "UP:Q04507" ("Amoy" "Ammonia monooxygenase alpha subunit")) 
(define-protein "NCIT:C112514" ("AffiniPure" "NPR1")) 
(define-protein "HGNC:15766" ("Adenopw" "activity dependent neuroprotector homeobox")) 
(define-protein "HGNC:327" ("AdEasy" "alkylglycerone phosphate synthase")) 
(define-protein "UP:P11834" ("Abcam" "Opioid-binding protein/cell adhesion molecule")) 
(define-protein "HGNC:23" ("Abatih" "4-aminobutyrate aminotransferase")) 
(define-protein "UP:P01008" ("AatII" "Antithrombin-III")) 
(define-protein "UP:Q9NQ79" ("AaSPVII" "Cartilage acidic protein 1")) 
(define-protein "UP:Q9NQ79" ("AaSPVI" "Cartilage acidic protein 1")) 
(define-protein "UP:P07758" ("AaET" "Alpha-1-antitrypsin 1-1")) 
(define-protein "NCIT:C134184" ("ARIs" "ARIH1")) 
(define-protein "UP:Q9M1T1" ("APIs" "Probable arabinose 5-phosphate isomerase")) 
(define-protein "UP:P21812" ("AMOScmp" "Mast cell protease 4")) 
(define-protein "HGNC:13200" ("zymoxin" "zyxin")) 
(define-protein "NCIT:C99661" ("zlog" "DLK1")) 
(define-protein "UP:D4GP40" ("xsd" "D-xylonate dehydratase")) 
(define-protein "UP:Q06615" ("xnt" "Homeobox protein notochord")) 
(define-protein "NCIT:C21415" ("upenn" "DNA-(Apurinic or apyrimidinic site) lyase")) 
(define-protein "NCIT:C16836" ("unep" "neprilysin")) 
(define-protein "UP:P48399" ("uchsc" "Chalcone synthase C")) 
(define-protein "UP:Q84UC0" ("tvfac" "Bifunctional fatty acid conjugase/Delta(12)-oleate desaturase")) 
(define-protein "HGNC:11740" ("transferin" "transferrin")) 
(define-protein "HGNC:9091" ("tblastn" "plastin 3")) 
(define-protein "UP:Q9F3C7" ("sourceforge" "Formylglycine-generating enzyme {ECO:0000303|PubMed:18390551, ECO:0000303|PubMed:25931126}")) 
(define-protein "HGNC:25428" ("sjt" "KIAA1217")) 
(define-protein "HGNC:30422" ("shtml" "shroom family member 3")) 
(define-protein "HGNC:21299" ("rollout" "ciliary rootlet coiled-coil, rootletin")) 
(define-protein "HGNC:10012" ("rhodopsins" "rhodopsin")) 
(define-protein "UP:Q0VCS0" ("ptas" "Pre T-cell antigen receptor alpha")) 
(define-protein "NCIT:C79964" ("prealbumins" "transthyretin")) 
(define-protein "HGNC:9071" ("plasmnogen" "plasminogen")) 
(define-protein "HGNC:8933" ("phrap" "pleckstrin homology like domain family A member 1")) 
(define-protein "NCIT:C16970" ("permwash" "permease")) 
(define-protein "UP:I3R7G3" ("pccu" "Propionyl-CoA carboxylase, biotin carboxylase and biotin-carboxyl carrier subunit")) 
(define-protein "UP:P35362" ("opsins" "Rhodopsin")) 
(define-protein "NCIT:C119650" ("ofthese" "SH3PXD2B")) 
(define-protein "UP:P52391" ("nwhere" "23S rRNA (adenosine(1067)-2'-O)-methyltransferase")) 
(define-protein "UP:Q9QSP4" ("nucleoproteins" "Nucleoprotein")) 
(define-protein "UP:Q98267" ("npho" "Nucleoside triphosphatase I")) 
(define-protein "HGNC:8002" ("nrlmry" "neural retina leucine zipper")) 
(define-protein "UP:Q01888" ("ngdc" "Graves disease carrier protein")) 
(define-protein "NCIT:C29997" ("microspin" "sarcospan")) 
(define-protein "UP:P56202" ("lymphopaenia" "Cathepsin W")) 
(define-protein "HGNC:24961" ("logy" "HOP homeobox")) 
(define-protein "NCIT:C20029" ("lipoproteins" "lipoprotein")) 
(define-protein "HGNC:16673" ("lanl" "acidic nuclear phosphoprotein 32 family member E")) 
(define-protein "UP:Q9UJ71" ("langerhan" "C-type lectin domain family 4 member K")) 
(define-protein "UP:P62756" ("itis" "Inter-alpha-trypsin inhibitor")) 
(define-protein "NCIT:C567" ("iges" "IgE")) 
(define-protein "NCIT:C17902" ("furine" "furin"))


(define-protein "NCIT:C51383" ("fastme" "FAS")) 
(define-protein "UP:P15808" ("fadeouts" "Flavin-dependent thymidylate synthase")) 
(define-protein "UP:Q8IS64" ("exe" "Endothelin-converting enzyme homolog {ECO:0000305|PubMed:12752656, ECO:0000312|EMBL:AAN73018.1}")) 
(define-protein "HGNC:3327" ("ephln" "elastin")) 
(define-protein "UP:P41801" ("elicitins" "Elicitin")) 
(define-protein "HGNC:3078" ("dtu" "deoxyuridine triphosphatase")) 
(define-protein "UP:Q9V3K3" ("dropdown" "RuvB-like helicase 2")) 
(define-protein "NCIT:C119684" ("degas" "AMIGO2")) 
(define-protein "UP:P21525" ("defra" "Transcription factor kayak, isoforms A/B/F")) 
(define-protein "HGNC:13432" ("defin" "ring finger protein 19A, RBR E3 ubiquitin protein ligase")) 
(define-protein "NCIT:C129850" ("cyco" "CYCS")) 
(define-protein "NCIT:C50985" ("csbio" "ERCC6")) 
(define-protein "UP:O01305" ("cqvip" "Calcium vector protein")) 
(define-protein "UP:P08897" ("collagenases" "Collagenase")) 
(define-protein "UP:P35030" ("chemotrypsinogen" "Trypsin-3")) 
(define-protein "UP:E3YBA4" ("cbcb" "Methanobactin mb-OB3b {ECO:0000303|PubMed:15361623, ECO:0000312|EMBL:EFS20503.1}")) 
(define-protein "NCIT:C16389" ("cathesin" "cathepsin")) 
(define-protein "UP:P78357" ("caspur" "Contactin-associated protein 1")) 
(define-protein "HGNC:29972" ("bitten" "centrosomal protein 70")) 
(define-protein "NCIT:C21195" ("biomol" "bcl-2-like protein 11")) 
(define-protein "UP:P84703" ("bacteriocins" "Bacteriocin")) 
(define-protein "UP:Q7Y0S0" ("autoreader" "Urease accessory protein D")) 
(define-protein "NCIT:C51192" ("autodock" "ATM")) 
(define-protein "NCIT:C51324" ("aij" "AURKA")) 
(define-protein "NCIT:C116035" ("ÄCTA" "CES1")) 
(define-protein "NCIT:C51294" ("ZZC" "PLAGL1")) 
(define-protein "HGNC:30960" ("ZYH" "zyg-11 related cell cycle regulator")) 
(define-protein "HGNC:13200" ("ZXMIN" "zyxin")) 
(define-protein "HGNC:4524" ("ZJQ" "prokineticin receptor 1")) 
(define-protein "UP:P86355" ("ZCH" "Canavanine hydrolase")) 
(define-protein "HGNC:11295" ("YSRL" "sarcalumenin")) 
(define-protein "UP:Q9JGU1" ("YNP" "Nucleoprotein")) 
(define-protein "UP:A3QVN2" ("YHY" "Hyaluronidase")) 
(define-protein "HGNC:1299" ("YBY" "ybeY metalloendoribonuclease")) 
(define-protein "UP:P53773" ("XLL" "Homeobox protein DLL-1")) 
(define-protein "HGNC:6344" ("XKL" "klotho")) 
(define-protein "NCIT:C84456" ("WSAVA" "T")) 
(define-protein "HGNC:30238" ("WLSP" "Wnt ligand secretion mediator")) 
(define-protein "UP:P04971" ("WBX" "Thrombin-like enzyme batroxobin")) 
(define-protein "HGNC:30910" ("WARPA" "von Willebrand factor A domain containing 1")) 
(define-protein "HGNC:32325" ("WAFELTP" "cilia and flagella associated protein 126")) 
(define-protein "UP:Q10754" ("VSAPAM" "Acidic phospholipase A2 inhibitor vaspin A chain")) 
(define-protein "HGNC:12687" ("VJL" "von Hippel-Lindau tumor suppressor")) 
(define-protein "NCIT:C149345" ("VIRIP" "HIVEP1")) 
(define-protein "UP:P81539" ("VFDB" "Ferredoxin B")) 
(define-protein "HGNC:30904" ("VDPV" "USO1 vesicle transport factor")) 
(define-protein "HGNC:2464" ("VCNA" "versican")) 
(define-protein "UP:P21090" ("VCBP" "Inactive chemokine-binding protein")) 
(define-protein "UP:Q8IVY1" ("VARTEMP" "Type III endosome membrane protein TEMP")) 
(define-protein "HGNC:15947" ("UUUAAAC" "uveal autoantigen with coiled-coil domains and ankyrin repeats")) 
(define-protein "HGNC:84" ("UUCUUAACAA" "acetyl-CoA carboxylase alpha")) 
(define-protein "HGNC:33116" ("UNSIC" "INSC spindle orientation adaptor protein")) 
(define-protein "UP:P42849" ("UMMC" "Umecyanin")) 
(define-protein "HGNC:7697" ("UGGGA" "NADH:ubiquinone oxidoreductase subunit B2")) 
(define-protein "NCIT:C74448" ("UGAUG" "NOD2")) 
(define-protein "UP:P35127" ("UCHC" "Ubiquitin carboxyl-terminal hydrolase YUH1")) 
(define-protein "UP:Q9RTE6" ("UCED" "UV DNA damage endonuclease")) 
(define-protein "HGNC:84" ("UCAACU" "acetyl-CoA carboxylase alpha")) 
(define-protein "HGNC:7697" ("UAUGGGAA" "NADH:ubiquinone oxidoreductase subunit B2")) 
(define-protein "NCIT:C94721" ("UAAUG" "MPG")) 
(define-protein "NCIT:C95930" ("TYC" "CD55")) 
(define-protein "UP:P23360" ("TXI" "Endo-1,4-beta-xylanase")) 
(define-protein "HGNC:12271" ("TROG" "T cell receptor gamma locus")) 
(define-protein "UP:P46115" ("TOSV" "Alpha-toxin Ts5")) 
(define-protein "NCIT:C97261" ("TOFI" "TFPI")) 
(define-protein "NCIT:C26419" ("TMCRA" "T-cell receptor alpha locus")) 
(define-protein "UP:P0DOJ7" ("TMAG" "Middle T antigen")) 
(define-protein "UP:P29401" ("TKY" "Transketolase")) 
(define-protein "NCIT:C84305" ("TECAN" "CARD8")) 
(define-protein "UP:O02194" ("TDMPS" "Presenilin homolog")) 
(define-protein "NCIT:C29926" ("TCAGGCC" "protein S100-A12")) 
(define-protein "NCIT:C131172" ("TAYLA" "UBASH3A")) 
(define-protein "HGNC:11804" ("TAIR" "TIA1 cytotoxic granule associated RNA binding protein like 1")) 
(define-protein "NCIT:C105065" ("SWW" "SLC4A1")) 
(define-protein "HGNC:11291" ("SSRF" "serum response factor")) 
(define-protein "NCIT:C97807" ("SSCR" "SSX1")) 
(define-protein "HGNC:10699" ("SPQF" "SEC14 like lipid binding 2")) 
(define-protein "UP:P35247" ("SPDI" "Pulmonary surfactant-associated protein D")) 
(define-protein "NCIT:C75407" ("SMGGB" "SMC1A")) 
(define-protein "NCIT:C107620" ("SLZ" "TXNRD2")) 
(define-protein "HGNC:10690" ("SEIDR" "caveolae associated protein 2")) 
(define-protein "NCIT:C96913" ("SDCAA" "SDC1")) 
(define-protein "HGNC:32322" ("SCXK" "scleraxis bHLH transcription factor")) 
(define-protein "UP:Q15067" ("SCIEX" "Peroxisomal acyl-coenzyme A oxidase 1")) 
(define-protein "HGNC:17699" ("SBJ" "SH3 domain binding kinase 1")) 
(define-protein "UP:P0CU39" ("SARSID" "Secretory-abundant heat soluble protein 33020")) 
(define-protein "UP:O00258" ("RWB" "Tail-anchored protein insertion receptor WRB")) 
(define-protein "HGNC:12155" ("RTB" "T cell receptor beta locus")) 
(define-protein "HGNC:9865" ("RRB" "retinoic acid receptor beta")) 
(define-protein "NCIT:C51285" ("RPSP" "MSMB")) 
(define-protein "HGNC:9358" ("RPEP" "prolyl endopeptidase")) 
(define-protein "UP:Q94FV7" ("RPBS" "Polyketide synthase BAS")) 
(define-protein "UP:O64392" ("RNEASY" "Wheatwin-1")) 
(define-protein "NCIT:C101096" ("RKKRRQRRR" "CDK12")) 
(define-protein "HGNC:26314" ("RKKR" "ribosomal protein S6 kinase related")) 
(define-protein "NCIT:C49407" ("RKC" "DDX6")) 
(define-protein "NCIT:C52113" ("RIDT" "SMARCB1")) 
(define-protein "HGNC:9954" ("RELL" "REL proto-oncogene, NF-kB subunit")) 
(define-protein "NCIT:C103947" ("REFMAC" "SLC19A1")) 
(define-protein "HGNC:10008" ("RCHE" "Rh blood group CcEe antigens")) 
(define-protein "NCIT:C52113" ("RADT" "SMARCB1")) 
(define-protein "UP:O22446" ("QHD" "Histone deacetylase 19")) 
(define-protein "UP:O15553" ("PYHIN" "Pyrin")) 
(define-protein "HGNC:27849" ("PXXXP" "PAXX non-homologous end joining factor")) 
(define-protein "NCIT:C38967" ("PUMV" "mucin-1")) 
(define-protein "UP:P16233" ("PTOL" "Pancreatic triacylglycerol lipase")) 
(define-protein "HGNC:17575" ("PSEN" "spen family transcriptional repressor")) 
(define-protein "HGNC:9449" ("PRNPN" "prion protein")) 
(define-protein "UP:Q6I7B6" ("PPMV" "Phosphopentomutase")) 
(define-protein "UP:O94680" ("PPDAT" "Phospholipid:diacylglycerol acyltransferase")) 
(define-protein "HGNC:7892" ("PNPR" "purine nucleoside phosphorylase")) 
(define-protein "UP:O34819" ("PNNL" "Pectin lyase")) 
(define-protein "UP:D4GXZ3" ("PMID" "Phosphomevalonate decarboxylase")) 
(define-protein "NCIT:C95247" ("PICT" "GLRX3")) 
(define-protein "UP:Q95XM2" ("PHEM" "Probable peptidylglycine alpha-hydroxylating monooxygenase 1 {ECO:0000312|WormBase:Y71G12B.4}")) 
(define-protein "UP:P20041" ("PGAA" "Polygalacturonase")) 
(define-protein "HGNC:17270" ("PARSKR" "PAS domain containing serine/threonine kinase")) 
(define-protein "HGNC:8594" ("PAML" "paralemmin")) 
(define-protein "NCIT:C17990" ("PACF" "histone acetyltransferase KAT2B")) 
(define-protein "HGNC:14645" ("OPOKO" "inositol-pentakisphosphate 2-kinase")) 
(define-protein "HGNC:823" ("OMRU" "ATP synthase F1 subunit alpha")) 
(define-protein "NCIT:C52798" ("OFI" "IFNG")) 
(define-protein "HGNC:17283" ("OBO" "regulating synaptic membrane exocytosis 2")) 
(define-protein "UP:P43142" ("NWO" "G-protein coupled receptor 182")) 
(define-protein "HGNC:3356" ("NIPPS" "ectonucleotide pyrophosphatase/phosphodiesterase 1")) 
(define-protein "HGNC:5178" ("NHRC" "histidine rich calcium binding protein")) 
(define-protein "UP:Q96EN8" ("NHAMCS" "Molybdenum cofactor sulfurase {ECO:0000255|HAMAP-Rule:MF_03050}")) 
(define-protein "NCIT:C114811" ("NEN" "SCN9A")) 
(define-protein "HGNC:7667" ("NCML" "nucleolin")) 
(define-protein "NCIT:C124116" ("NCAE" "SLC3A2")) 
(define-protein "HGNC:7641" ("NAPPA" "NSF attachment protein alpha")) 
(define-protein "UP:Q5BKR2" ("NAHICO" "Sodium/hydrogen exchanger 9B2")) 
(define-protein "UP:Q9BW11" ("MYXV" "Max dimerization protein 3")) 
(define-protein "HGNC:6914" ("MSZ" "MYC associated zinc finger protein")) 
(define-protein "HGNC:986" ("MSY" "branched chain keto acid dehydrogenase E1 subunit alpha")) 
(define-protein "HGNC:7321" ("MSCW" "musculin")) 
(define-protein "HGNC:27087" ("MOSFOM" "modulator of smoothened")) 
(define-protein "HGNC:14010" ("MOGA" "MAX dimerization protein MGA")) 
(define-protein "HGNC:27087" ("MOFSOM" "modulator of smoothened")) 
(define-protein "UP:P48531" ("MNKB" "Midkine-B")) 
(define-protein "HGNC:7150" ("MLOGD" "malonyl-CoA decarboxylase")) 
(define-protein "NCIT:C102931" ("MJR" "DNAJB6")) 
(define-protein "UP:Q58717" ("MJAGK" "Protein argonaute")) 
(define-protein "HGNC:16298" ("MIDNV" "midnolin")) 
(define-protein "UP:P90648" ("MHCBN" "Myosin heavy chain kinase B")) 
(define-protein "NCIT:C28731" ("MARV" "C-C motif chemokine 7")) 
(define-protein "HGNC:6816" ("MAJ" "male germ cell associated kinase")) 
(define-protein "NCIT:C49524" ("LYPF" "PTPN22")) 
(define-protein "UP:Q8NTE1" ("LYPD" "Dihydrolipoyl dehydrogenase")) 
(define-protein "NCIT:C49524" ("LYPB" "PTPN22")) 
(define-protein "HGNC:6667" ("LYPA" "lipoprotein(a)")) 
(define-protein "HGNC:6667" ("LXPA" "lipoprotein(a)")) 
(define-protein "HGNC:6724" ("LUMC" "lumican")) 
(define-protein "HGNC:29572" ("LSRII" "lipolysis stimulated lipoprotein receptor")) 
(define-protein "HGNC:6667" ("LPAI" "lipoprotein(a)")) 
(define-protein "NCIT:C49511" ("LMM" "CDKN2A")) 
(define-protein "HGNC:17082" ("LIVIM" "modulator of VRAC current 1")) 
(define-protein "HGNC:6344" ("KYL" "klotho")) 
(define-protein "NCIT:C105597" ("KVRF" "VEGFB")) 
(define-protein "NCIT:C54314" ("KSM" "KMT2D")) 
(define-protein "UP:O60333" ("KPL" "Kinesin-like protein KIF1B")) 
(define-protein "HGNC:28916" ("KMY" "junction mediating and regulatory protein, p53 cofactor")) 
(define-protein "NCIT:C97297" ("KML" "MKL1")) 
(define-protein "UP:P14510" ("KEMRI" "Kanamycin resistance protein")) 
(define-protein "NCIT:C75620" ("KAOL" "ANOS1")) 
(define-protein "HGNC:6264" ("KAG" "potassium inwardly rectifying channel subfamily J member 3")) 
(define-protein "HGNC:26288" ("JYH" "junctional cadherin complex regulator")) 
(define-protein "HGNC:6315" ("JHK" "ketohexokinase")) 
(define-protein "HGNC:3700" ("JFH" "fumarate hydratase")) 
(define-protein "UP:C0HJB3" ("JFBM" "Alpha-mannosidase")) 
(define-protein "NCIT:C118592" ("JCM" "F11R")) 
(define-protein "UP:P03718" ("IVPI" "Internal protein I")) 
(define-protein "HGNC:12516" ("IUCN" "urocortin")) 
(define-protein "HGNC:17870" ("INSV" "inversin")) 
(define-protein "UP:P22488" ("IFU" "Non-neuronal cytoplasmic intermediate filament protein")) 
(define-protein "HGNC:21714" ("IFNL" "interferon kappa")) 
(define-protein "HGNC:40050" ("IDSA" "multiciliate differentiation and DNA synthesis associated cell cycle protein")) 
(define-protein "UP:P24856" ("IDGP" "Ice-structuring glycoprotein")) 
(define-protein "HGNC:2681" ("IDEXX" "death domain associated protein")) 
(define-protein "NCIT:C566" ("IBGD" "IgD")) 
(define-protein "UP:A3QVN2" ("HYW" "Hyaluronidase")) 
(define-protein "HGNC:4851" ("HYT" "huntingtin")) 
(define-protein "HGNC:4827" ("HVB" "hemoglobin subunit beta")) 
(define-protein "UP:P13817" ("HRPO" "Knob-associated histidine-rich protein")) 
(define-protein "HGNC:8918" ("HPRD" "phosphate regulating endopeptidase homolog X-linked")) 
(define-protein "HGNC:32935" ("HMMTOP" "solute carrier family 22 member 25")) 
(define-protein "HGNC:6584" ("HLJBY" "luteinizing hormone subunit beta")) 
(define-protein "NCIT:C20705" ("HLAI" "MHC class II protein")) 
(define-protein "HGNC:34403" ("HKK" "hydroxylysine kinase")) 
(define-protein "HGNC:26922" ("HEEBO" "ERCC excision repair 6 like 2")) 
(define-protein "UP:Q719L8" ("HCRC" "Snaclec crotocetin")) 
(define-protein "UP:O75603" ("HCMB" "Chorion-specific transcription factor GCMb")) 
(define-protein "NCIT:C113636" ("HCIII" "SERPIND1")) 
(define-protein "UP:Q6QNF4" ("HCGFAA" "Hepatocyte growth factor activator")) 
(define-protein "HGNC:4829" ("HBDDE" "hemoglobin subunit delta")) 
(define-protein "UP:P04150" ("GWR" "Glucocorticoid receptor")) 
(define-protein "HGNC:25068" ("GTAC" "glutamyl-tRNA amidotransferase subunit C")) 
(define-protein "UP:Q6L1T2" ("GND" "D-gluconate/D-galactonate dehydratase")) 
(define-protein "UP:Q96GX5" ("GLW" "Serine/threonine-protein kinase greatwall")) 
(define-protein "HGNC:4331" ("GLSL" "glutaminase")) 
(define-protein "HGNC:3355" ("GENEPOP" "glutamyl aminopeptidase")) 
(define-protein "UP:Q15406" ("GENECONV" "Nuclear receptor subfamily 6 group A member 1")) 
(define-protein "HGNC:4563" ("GDAS" "GRB2 related adaptor protein 2")) 
(define-protein "HGNC:15990" ("GCUA" "grancalcin")) 
(define-protein "HGNC:23432" ("GCTLNF" "centlein")) 
(define-protein "UP:P29109" ("GBNV" "Oleosin Bn-V")) 
(define-protein "HGNC:4065" ("GAAA" "glucosidase alpha, acid")) 
(define-protein "HGNC:27741" ("FWPV" "chromosome 4 open reading frame 54")) 
(define-protein "UP:P15369" ("FSLB" "Scytalidopepsin B")) 
(define-protein "NCIT:C70998" ("FJH" "HNF1B")) 
(define-protein "HGNC:32325" ("FELTP" "cilia and flagella associated protein 126")) 
(define-protein "NCIT:C103953" ("FELASA" "PLVAP")) 
(define-protein "NCIT:C50979" ("FCTC" "ATR")) 
(define-protein "UP:A1YPR3" ("EVW" "2-epi-5-epi-valiolone epimerase")) 
(define-protein "UP:Q90VW1" ("EUB" "Erabutoxin b")) 
(define-protein "HGNC:3444" ("ERNF" "ETS2 repressor factor")) 
(define-protein "NCIT:C116089" ("EPPM" "STX2")) 
(define-protein "HGNC:11529" ("EPCM" "epithelial cell adhesion molecule")) 
(define-protein "NCIT:C52126" ("EIRT" "ELF3")) 
(define-protein "HGNC:4882" ("EHYL" "hes related family bHLH transcription factor with YRPW motif like")) 
(define-protein "UP:Q54UT2" ("DYKDDDDK" "Deoxyguanosine kinase")) 
(define-protein "UP:Q949W8" ("DXL" "Xylulose kinase 2")) 
(define-protein "HGNC:2768" ("DWK" "DEK proto-oncogene")) 
(define-protein "NCIT:C50994" ("DUGV" "MSH3")) 
(define-protein "HGNC:33446" ("DSTL" "D-dopachrome tautomerase like")) 
(define-protein "UP:Q5W1L5" ("DSCR" "Pro-corazonin")) 
(define-protein "HGNC:29812" ("DPCPSI" "decapping enzyme, scavenger")) 
(define-protein "UP:P09208" ("DONR" "Insulin-like receptor")) 
(define-protein "UP:P91664" ("DMXAAA" "Protein max")) 
(define-protein "HGNC:2960" ("DDNL" "deoxyribonuclease 2, lysosomal")) 
(define-protein "UP:Q54LT0" ("DDMC" "Calcium uniporter protein, mitochondrial")) 
(define-protein "HGNC:225" ("DAAR" "adenosine deaminase RNA specific")) 
(define-protein "UP:P07469" ("CSU" "Corticostatin 1")) 
(define-protein "HGNC:24050" ("CREBATF" "CREB3 regulatory factor")) 
(define-protein "HGNC:17104" ("CODONW" "cell adhesion associated, oncogene regulated")) 
(define-protein "HGNC:29920" ("CNPV" "centromere protein V")) 
(define-protein "UP:Q2HJ53" ("CIQS" "Cytokine-inducible SH2-containing protein")) 
(define-protein "UP:O35949" ("CINII" "Elongation of very long chain fatty acids protein 3 {ECO:0000255|HAMAP-Rule:MF_03203, ECO:0000305}")) 
(define-protein "NCIT:C104588" ("CINI" "NT5C2")) 
(define-protein "HGNC:4028" ("CHIKF" "FXYD domain containing ion transport regulator 4")) 
(define-protein "HGNC:14214" ("CEIC" "capicua transcriptional repressor")) 
(define-protein "HGNC:23723" ("CECAM" "cerebral endothelial cell adhesion molecule")) 
;;(define-protein "NCIT:C51151" ("CDPHE" "CDH1")) 
(define-protein "HGNC:1616" ("CCCTG" "chaperonin containing TCP1 subunit 3")) 
(define-protein "NCIT:C118583" ("CCACC" "PROCR")) 
(define-protein "UP:W3VKA4" ("CAYLA" "Lipase A")) 
;;(define-protein "NCIT:C51088" ("CACCC" "CLCA2")) 
(define-protein "UP:P51853" ("BZLF" "Benzaldehyde lyase")) 
(define-protein "UP:P52699" ("BLOMAP" "Metallo-beta-lactamase type 2")) 
(define-protein "HGNC:20220" ("BJA" "FCF1 rRNA-processing protein")) 
(define-protein "HGNC:1122" ("BDT" "biotinidase")) 
(define-protein "UP:P17404" ("BASCGAP" "Leukocyte cell-derived chemotaxin 1")) 
(define-protein "UP:Q9S795" ("BADJ" "Betaine aldehyde dehydrogenase 1, chloroplastic")) 
(define-protein "HGNC:7697" ("AUGGGA" "NADH:ubiquinone oxidoreductase subunit B2")) 
(define-protein "HGNC:16001" ("AUGCT" "succinyl-CoA:glutarate-CoA transferase")) 
(define-protein "UP:P22702" ("AUAP" "Arginine attenuator peptide")) 
(define-protein "NCIT:C51063" ("AKC" "TNK2")) 
(define-protein "UP:C0NDZ7" ("AHMPPI" "Probable Xaa-Pro aminopeptidase P")) 
(define-protein "HGNC:84" ("AGCCA" "acetyl-CoA carboxylase alpha")) 
(define-protein "HGNC:316" ("AFMB" "afamin")) 
(define-protein "UP:Q9P8W3" ("AECII" "Zinc finger transcription factor ace1")) 
(define-protein "HGNC:259" ("ADMV" "adrenomedullin")) 
(define-protein "NCIT:C150160" ("ACGT" "ACTG1")) 
(define-protein "HGNC:84" ("ACACCA" "acetyl-CoA carboxylase alpha")) 
(define-protein "NCIT:C33977" ("ABNOVA" "RNA-binding protein nova-2")) 
(define-protein "HGNC:84" ("AACCC" "acetyl-CoA carboxylase alpha")) 
(define-protein "NCIT:C94721" ("AAAG" "MPG")) 
;;
