(in-package :sparser)


("BPD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:70589" :name "Bronchopulmonary dysplasia") 
("CNM" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:595" :name "Centronuclear myopathy") 
("CVID" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1572" :name "Common variable immunodeficiency") 
("DOA" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:98672" :name "Autosomal dominant optic atrophy") 
("EBSS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:89839" :name "Epidermolysis bullosa simplex superficialis") 
("GDD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:53697" :name "Gnathodiaphyseal dysplasia") 
("IFD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:332" :name "Congenital intrinsic factor deficiency") 
("IPD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:238455" :name "Infantile dystonia-parkinsonism") 
("IPS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:88621" :name "Ichthyosis prematurity syndrome") 
("IRD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:772" :name "Infantile Refsum disease") 
("LCPS" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:363618" :name "LMNA-related cardiocutaneous progeria syndrome") 
("LPG" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:329481" :name "Lipoprotein glomerulopathy") 
("MHPA" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:79651" :name "Mild hyperphenylalaninemia") 
("MPGN" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:54370" :name "Primary membranoproliferative glomerulonephritis") 
("PPP" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:163927" :name "Pustulosis palmaris et plantaris") 
("VSD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1480" :name "Ventricular septal defect") 
("cie" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:79394" :name "Congenital non-bullous ichthyosiform erythroderma") 
("ied" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:92050" :name "Intestinal epithelial dysplasia") 
("ofd" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:140997" :name "Orofaciodigital syndrome") 
("CSs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1465" :name "Coffin-Siris syndrome") 
("IDi" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:363300" :name "Genetic intractable diarrhea of infancy") 
("SLOs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:818" :name "Smith-Lemli-Opitz syndrome") 
("Sao" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:98868" :name "Southeast Asian ovalocytosis") 
("mecD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:98954" :name "Meesmann corneal dystrophy") 
("pCD" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:158" :name "Systemic primary carnitine deficiency") 
("rRs" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:1507" :name "Autosomal recessive Robinow syndrome") 