
(define-protein "11betaHSD2" ("UP:P80365" "Corticosteroid 11-beta-dehydrogenase isozyme 2")) 
(define-protein "2KR" ("UP:O32264" "Probable 2-ketogluconate reductase")) 
(define-protein "3BP2" ("UP:P78314" "SH3 domain-binding protein 2")) 
(define-protein "4-1BB" ("NCIT:C105112" "TNFRSF9")) 
(define-protein "4E-BP3" ("UP:Q98TT6" "Eukaryotic translation initiation factor 4E-binding protein 3-like")) 
(define-protein "4EBPs" ("UP:Q54DU8" "Eukaryotic translation initiation factor 4E-1A-binding protein homolog")) 
(define-protein "4PS" ("UP:P81122" "Insulin receptor substrate 2")) 
(define-protein "6PGD" ("GO:0004616" "phosphogluconate dehydrogenase (decarboxylating) activity")) 
(define-protein "AAC" ("UP:Q2KIR7" "Glycine N-acyltransferase {ECO:0000303|PubMed:22071172}")) 
(define-protein "AAPs" ("UP:P22702" "Arginine attenuator peptide")) 
(define-protein "AAR" ("UP:Q54765" "Long-chain acyl-[acyl-carrier-protein] reductase")) 
(define-protein "AARE" ("UP:P13798" "Acylamino-acid-releasing enzyme")) 
(define-protein "AAT" ("UP:P07758" "Alpha-1-antitrypsin 1-1")) 
(define-protein "AATF" ("HGNC:19235" "apoptosis antagonizing transcription factor")) 
(define-protein "ACA" ("NCIT:C95408" "anticardiolipin antibody")) 
(define-protein "ACAC" ("NCIT:C103886" "ACACA")) 
(define-protein "ACACA" ("HGNC:84" "acetyl-CoA carboxylase alpha")) 
(define-protein "ACACB" ("HGNC:85" "acetyl-CoA carboxylase beta")) 
(define-protein "ACCA" ("XFAM:PF03255.12" "ACCA")) 
(define-protein "ACCalpha" ("NCIT:C103887" "acetyl-CoA carboxylase 1")) 
(define-protein "ACCbeta" ("UP:O00763" "Acetyl-CoA carboxylase 2")) 
(define-protein "ACF" ("NCIT:C20154" "ACF complex")) 
(define-protein "ACP" ("UP:O14561" "Acyl carrier protein, mitochondrial")) 
(define-protein "ACRC" ("HGNC:15805" "germ cell nuclear acidic peptidase")) 
(define-protein "ACTH" ("NCIT:C2282" "adrenocorticotropic hormone")) 
(define-protein "ACs" ("UP:Q13510" "Acid ceramidase")) 
(define-protein "ADCs" ("UP:P28819" "Aminodeoxychorismate/anthranilate synthase component 2")) 
(define-protein "ADH" ("UP:P42327" "Alcohol dehydrogenase")) 
(define-protein "ADI" ("UP:Q8FAD9" "Arginine deiminase")) 
(define-protein "ADPRT" ("NCIT:C51001" "PARP1")) 
(define-protein "ADR" ("UP:Q09851" "NADPH-dependent 1-acyldihydroxyacetone phosphate reductase")) 
(define-protein "ADRB" ("NCIT:C17062" "beta adrenergic receptor")) 
(define-protein "AEN" ("HGNC:25722" "apoptosis enhancing nuclease")) 
(define-protein "AF4" ("FA:00123" "AF4 family")) 
(define-protein "AFM" ("HGNC:316" "afamin")) 
(define-protein "AFPs" ("HGNC:317" "alpha fetoprotein")) 
(define-protein "AFT" ("XFAM:PF08731.9" "AFT")) 
(define-protein "AG" ("UP:P12023" "Amyloid beta A4 protein")) 
(define-protein "AGA" ("HGNC:318" "aspartylglucosaminidase")) 
(define-protein "AHSP" ("HGNC:18075" "alpha hemoglobin stabilizing protein")) 
(define-protein "AI" ("UP:P26461" "Sperm-associated acrosin inhibitor")) 
(define-protein "AICAR" ("NCIT:C97401" "ATIC")) 
(define-protein "AID" ("NCIT:C101414" "AICDA")) 
(define-protein "AII" ("NCIT:C77203" "NLRP3")) 
(define-protein "AIs" ("UP:P26461" "Sperm-associated acrosin inhibitor")) 
(define-protein "AKTIP" ("HGNC:16710" "AKT interacting protein")) 
(define-protein "ALDH" ("UP:O74187" "Aldehyde dehydrogenase")) 
(define-protein "ALT1" ("UP:A4IFH5" "Alanine aminotransferase 1")) 
(define-protein "ALX" ("UP:Q26657" "Aristaless homeobox protein")) 
(define-protein "AMBN" ("HGNC:452" "ameloblastin")) 
(define-protein "AMG" ("HGNC:461" "amelogenin, X-linked")) 
(define-protein "AMH" ("HGNC:464" "anti-Mullerian hormone")) 
(define-protein "AMO" ("UP:Q04507" "Ammonia monooxygenase, acetylene-binding")) 
(define-protein "AMSH" ("NCIT:C52457" "AMSH")) 
(define-protein "ANCA" ("NCIT:C129400" "antineutrophil cytoplasmic antibody")) 
(define-protein "ANK" ("UP:Q9HCJ1" "Progressive ankylosis protein homolog")) 
(define-protein "ANP" ("XFAM:PF00212.16" "ANP")) 
(define-protein "ANPK" ("UP:Q9H422" "Homeodomain-interacting protein kinase 3")) 
(define-protein "ANT" ("XFAM:PF03374.12" "ANT")) 
(define-protein "APBs" ("UP:Q9H4A4" "Aminopeptidase B")) 
(define-protein "APCL" ("NCIT:C52459" "APCL")) 
(define-protein "APF" ("UP:P22324" "Alpha-1-antiproteinase F")) 
(define-protein "APH" ("XFAM:PF01636.21" "APH")) 
(define-protein "APHs" ("XFAM:PF01636.21" "APH")) 
(define-protein "APLF" ("HGNC:28724" "aprataxin and PNKP like factor")) 
(define-protein "APPL" ("HGNC:24035" "adaptor protein, phosphotyrosine interacting with PH domain and leucine zipper 1")) 
(define-protein "APR" ("NCIT:C95473" "LRP1")) 
(define-protein "APRIL" ("NCIT:C105968" "TNFSF13")) 
(define-protein "APTX" ("HGNC:15984" "aprataxin")) 
(define-protein "ARB" ("UP:Q54NZ7" "Aldose reductase B")) 
(define-protein "ARGs" ("NCIT:C51062" "ABL2")) 
(define-protein "ARI" ("HGNC:689" "ariadne RBR E3 ubiquitin protein ligase 1")) 
(define-protein "ART" ("XFAM:PF01129.16" "ART")) 
(define-protein "ARTS" ("NCIT:C104503" "SEPT4")) 
(define-protein "ARs" ("HGNC:644" "androgen receptor")) 
(define-protein "ASA" ("UP:Q08DD1" "Arylsulfatase A")) 
(define-protein "ASD" ("UP:P51689" "Arylsulfatase D")) 
(define-protein "ASPS" ("NCIT:C125589" "CSNK1D")) 
(define-protein "ATDC" ("NCIT:C51192" "ATM")) 
(define-protein "ATE" ("NCIT:C51192" "ATM")) 
(define-protein "ATFa" ("HGNC:792" "activating transcription factor 7")) 
(define-protein "ATMIN" ("HGNC:29034" "ATM interactor")) 
(define-protein "ATX" ("UP:P14421" "Neutral phospholipase A2 agkistrodotoxin")) 
(define-protein "AURKB" ("HGNC:11390" "aurora kinase B")) 
(define-protein "ActRIB" ("NCIT:C28714" "activin-A type-B receptor")) 
(define-protein "ActRIIB" ("NCIT:C21274" "activin-A type-IIB receptor")) 
(define-protein "AktI" ("UP:P85498" "Kunitz-type trypsin inhibitor alpha chain")) 
(define-protein "AlkB" ("FA:00158" "alkB family")) 
(define-protein "AnAc" ("UP:Q9C932" "NAC domain-containing protein 19")) 
(define-protein "AnnexinV" ("NCIT:C21333" "annexin-A5 protein")) 
(define-protein "ApoB" ("HGNC:603" "apolipoprotein B")) 
(define-protein "ApoCIII" ("NCIT:C117098" "APOC3")) 
(define-protein "ArPIKfyve" ("HGNC:25507" "Vac14, PIKFYVE complex component")) 
(define-protein "AuroraB" ("NCIT:C68596" "serine-threonine kinase-12")) 
(define-protein "BAGE" ("HGNC:942" "B melanoma antigen")) 
(define-protein "BATF" ("HGNC:958" "basic leucine zipper ATF-like transcription factor")) 
(define-protein "BCAP" ("HGNC:17024" "PHD finger protein 11")) 
(define-protein "BCAT" ("UP:O14370" "Branched-chain-amino-acid aminotransferase, mitochondrial")) 
(define-protein "BCLW" ("NCIT:C49351" "BCL2L2")) 
(define-protein "BCRP" ("NCIT:C52276" "ABCG2")) 
(define-protein "BCa" ("HGNC:14211" "B-cell linker")) 
(define-protein "BEL" ("UP:F2Z266" "Boletus edulis lectin")) 
(define-protein "BENE" ("XFAM:PF03594.11" "BenE")) 
(define-protein "BFP" ("HGNC:12968" "ring finger protein 112")) 
(define-protein "BFR" ("UP:Q10985" "Bacterioferritin heavy chain")) 
(define-protein "BG" ("HGNC:616" "apolipoprotein H")) 
(define-protein "BGs" ("HGNC:616" "apolipoprotein H")) 
(define-protein "BHC" ("NCIT:C73444" "NKX2-1")) 
(define-protein "BHD" ("NCIT:C63517" "FLCN")) 
(define-protein "BI" ("UP:P01068" "Bromelain inhibitor")) 
(define-protein "BIK" ("HGNC:1051" "BCL2 interacting killer")) 
(define-protein "BIS" ("NCIT:C105995" "BAG3")) 
(define-protein "BKS" ("HGNC:30430" "signal transducing adaptor family member 2")) 
(define-protein "BLID" ("HGNC:33495" "BH3-like motif containing, cell death inducer")) 
(define-protein "BLRP" ("UP:P75990" "Blue light- and temperature-regulated antirepressor BluF")) 
(define-protein "BMK" ("UP:P08103" "Tyrosine-protein kinase HCK")) 
(define-protein "BMPER" ("HGNC:24154" "BMP binding endothelial regulator")) 
(define-protein "BMPRIA" ("HGNC:1076" "bone morphogenetic protein receptor type 1A")) 
(define-protein "BMPRIB" ("HGNC:1077" "bone morphogenetic protein receptor type 1B")) 
(define-protein "BMPRII" ("HGNC:1078" "bone morphogenetic protein receptor type 2")) 
(define-protein "BOK" ("HGNC:1087" "BOK, BCL2 family apoptosis regulator")) 
(define-protein "BOP" ("NCIT:C75391" "EYA")) 
(define-protein "BORIS" ("NCIT:C111819" "CTCFL")) 
(define-protein "BP" ("NCIT:C51250" "HP")) 
(define-protein "BPTF" ("HGNC:3581" "bromodomain PHD finger transcription factor")) 
(define-protein "BPs" ("NCIT:C51250" "HP")) 
(define-protein "BRCAX" ("NCIT:C54377" "BRCA3")) 
(define-protein "BRUCE" ("HGNC:13516" "baculoviral IAP repeat containing 6")) 
(define-protein "BRs" ("UP:P33969" "Bacteriorhodopsin")) 
(define-protein "BS" ("NCIT:C49406" "BLM")) 
(define-protein "BTX" ("UP:P80163" "Bibrotoxin")) 
(define-protein "BaF" ("FA:00326" "BAF family")) 
(define-protein "BclxL" ("HGNC:992" "BCL2 like 1")) 
(define-protein "BiPs" ("NCIT:C48836" "GRP78 protein")) 
(define-protein "BimS" ("HGNC:994" "BCL2 like 11")) 
(define-protein "CABYR" ("HGNC:15569" "calcium binding tyrosine phosphorylation regulated")) 
(define-protein "CAC" ("HGNC:1421" "solute carrier family 25 member 20")) 
(define-protein "CACs" ("HGNC:1421" "solute carrier family 25 member 20")) 
(define-protein "CAFs" ("NCIT:C51293" "PCAF")) 
(define-protein "CAKI" ("UP:Q24210" "Peripheral plasma membrane protein CASK")) 
(define-protein "CAML" ("UP:P49069" "Calcium signal-modulating cyclophilin ligand")) 
(define-protein "CAPER" ("HGNC:15923" "RNA binding motif protein 39")) 
(define-protein "CAPERalpha" ("HGNC:15923" "RNA binding motif protein 39")) 
(define-protein "CAPERbeta" ("HGNC:20155" "RNA binding motif protein 23")) 
(define-protein "CARF" ("HGNC:14435" "calcium responsive transcription factor")) 
(define-protein "CATG" ("NCIT:C104054" "CTSG")) 
(define-protein "CB" ("UP:P0CAS1" "Phospholipase A2 crotoxin basic chain")) 
(define-protein "CBAP" ("HGNC:26722" "transmembrane protein 102")) 
(define-protein "CBFB" ("HGNC:1539" "core-binding factor beta subunit")) 
(define-protein "CBFalpha" ("NCIT:C18319" "core-binding factor alpha")) 
(define-protein "CBFbeta" ("UP:Q13951" "Core-binding factor subunit beta")) 
(define-protein "CBLb" ("HGNC:1542" "Cbl proto-oncogene B")) 
(define-protein "CCK" ("HGNC:1569" "cholecystokinin")) 
(define-protein "CCNA" ("NCIT:C49515" "CCNA2")) 
(define-protein "CCNY" ("HGNC:23354" "cyclin Y")) 
(define-protein "CCNs" ("HGNC:20570" "cyclin L2")) 
(define-protein "CCOT" ("NCIT:C51214" "MAP3K8")) 
(define-protein "CCRK" ("HGNC:21420" "cyclin dependent kinase 20")) 
(define-protein "CCTalpha" ("NCIT:C104957" "choline-phosphate cytidylyltransferase A")) 
(define-protein "CCTbeta" ("HGNC:8755" "phosphate cytidylyltransferase 1, choline, beta")) 
(define-protein "CCTepsilon" ("UP:P48643" "T-complex protein 1 subunit epsilon")) 
(define-protein "CDH" ("UP:Q8NE62" "Choline dehydrogenase, mitochondrial")) 
(define-protein "CDIP" ("HGNC:13234" "cell death inducing p53 target 1")) 
(define-protein "CDKs" ("NCIT:C17767" "cyclin-dependent kinase")) 
(define-protein "CDR" ("UP:Q8VQF5" "Cindoxin reductase")) 
(define-protein "CDS" ("FA:00546" "CDS family")) 
(define-protein "CER" ("UP:P13387" "Epidermal growth factor receptor")) 
(define-protein "CGH" ("NCIT:C111821" "HTC2 gene")) 
(define-protein "CHA" ("HGNC:11646" "transcription factor like 5")) 
(define-protein "CHD" ("UP:Q8NE62" "Choline dehydrogenase, mitochondrial")) 
(define-protein "CHFR" ("HGNC:20455" "checkpoint with forkhead and ring finger domains")) 
(define-protein "CHOD" ("UP:P22637" "Cholesterol oxidase")) 
(define-protein "CHS" ("UP:B5UAQ8" "Cheilanthifoline synthase")) 
(define-protein "CINP" ("HGNC:23789" "cyclin dependent kinase 2 interacting protein")) 
(define-protein "CIPC" ("HGNC:20365" "CLOCK interacting pacemaker")) 
(define-protein "CIS" ("UP:Q2HJ53" "Cytokine-inducible SH2-containing protein")) 
(define-protein "CKI" ("NCIT:C51051" "CHK")) 
(define-protein "CKIIalpha" ("UP:P28523" "Casein kinase II subunit alpha")) 
(define-protein "CKIalpha" ("UP:P48729" "Casein kinase I isoform alpha")) 
(define-protein "CKIdelta" ("UP:P48730" "Casein kinase I isoform delta")) 
(define-protein "CKO" ("UP:P58763" "Cytokinin dehydrogenase")) 
(define-protein "CLB" ("HGNC:18355" "citrate lyase beta like")) 
(define-protein "CLC" ("HGNC:2014" "Charcot-Leyden crystal galectin")) 
(define-protein "CLM" ("UP:Q7TSN2" "CMRF35-like molecule")) 
(define-protein "CLS" ("UP:Q9UJA2" "Cardiolipin synthase (CMP-forming)")) 
(define-protein "CMF" ("UP:P34090" "Conditioned medium factor")) 
(define-protein "CNK" ("NCIT:C51198" "CNK")) 
(define-protein "COASTER" ("HGNC:21091" "zinc finger protein 451")) 
(define-protein "COMT" ("HGNC:2228" "catechol-O-methyltransferase")) 
(define-protein "CPAP" ("HGNC:17272" "centromere protein J")) 
(define-protein "CPCs" ("UP:P29602" "Cucumber peeling cupredoxin")) 
(define-protein "CPD" ("HGNC:2301" "carboxypeptidase D")) 
(define-protein "CPF" ("NCIT:C112511" "NR5A2")) 
(define-protein "CPH" ("UP:Q04965" "Hexon protein")) 
(define-protein "CPT" ("UP:Q56148" "Chloramphenicol 3-O phosphotransferase")) 
(define-protein "CPs" ("HGNC:2295" "ceruloplasmin")) 
(define-protein "CR" ("UP:P22676" "Calretinin")) 
(define-protein "CRABPII" ("NCIT:C104926" "CRABP2")) 
(define-protein "CRBN" ("HGNC:30185" "cereblon")) 
(define-protein "CRCs" ("UP:Q719L8" "Snaclec crotocetin")) 
(define-protein "CREBZF" ("HGNC:24905" "CREB/ATF bZIP transcription factor")) 
(define-protein "CREG" ("FA:00754" "CREG family")) 
(define-protein "CRF" ("XFAM:PF00473.15" "CRF")) 
(define-protein "CRG" ("HGNC:20626" "chromodomain helicase DNA binding protein 7")) 
(define-protein "CRIPak" ("UP:Q8N1N5" "Cysteine-rich PAK1 inhibitor")) 
(define-protein "CRLs" ("XFAM:PF07417.10" "crl")) 
(define-protein "CRT" ("UP:Q9PWF3" "Crotamine {ECO:0000303|PubMed:1176086}")) 
(define-protein "CRY" ("UP:P15570" "Beta-elicitin cryptogein")) 
(define-protein "CRYZ" ("HGNC:2419" "crystallin zeta")) 
(define-protein "CSDH" ("HGNC:30404" "serine dehydratase like")) 
(define-protein "CSP" ("UP:O33672" "Competence-stimulating peptide")) 
(define-protein "CSPC" ("HGNC:4710" "granzyme H")) 
(define-protein "CTAG" ("NCIT:C54412" "CTAG1")) 
(define-protein "CTBs" ("HGNC:2496" "chitobiase")) 
(define-protein "CTDSPL" ("HGNC:16890" "CTD small phosphatase like")) 
(define-protein "CTF" ("NCIT:C53094" "NFIC wt allele")) 
(define-protein "CTFs" ("NCIT:C53094" "NFIC wt allele")) 
(define-protein "CTLs" ("UP:Q6T7B7" "C-type lectin 1")) 
(define-protein "CTMP" ("HGNC:17947" "thioesterase superfamily member 4")) 
(define-protein "CTRL" ("HGNC:2524" "chymotrypsin like")) 
(define-protein "CYP" ("NCIT:C16484" "cytochrome-P450")) 
(define-protein "CaCC" ("NCIT:C51088" "CLCA2")) 
(define-protein "CapZIP" ("NCIT:C119662" "RCSD1")) 
(define-protein "CdA" ("HGNC:1712" "cytidine deaminase")) 
(define-protein "ChC" ("NCIT:C97416" "CLTCL1")) 
(define-protein "ClpP" ("HGNC:2084" "caseinolytic mitochondrial matrix peptidase proteolytic subunit")) 
(define-protein "CnA" ("NCIT:C49425" "PPP3CA")) 
(define-protein "CoAA" ("NCIT:C114449" "RBM14")) 
(define-protein "CpGs" ("GO:0036356" "cyclic 2,3-diphosphoglycerate synthetase activity")) 
(define-protein "CrkII" ("NCIT:C52537" "CRK")) 
(define-protein "CtIP" ("NCIT:C73441" "RBBP8")) 
(define-protein "CyclinD" ("UP:Q5SCB5" "Cyclin-D")) 
(define-protein "CypB" ("NCIT:C115180" "PPIB")) 
(define-protein "DAD" ("UP:Q10318" "Putative dihydroxy-acid dehydratase, mitochondrial")) 
(define-protein "DAF" ("NCIT:C95931" "complement decay-accelerating factor")) 
(define-protein "DANS" ("UP:P12995" "Adenosylmethionine-8-amino-7-oxononanoate aminotransferase")) 
(define-protein "DAPk" ("HGNC:2674" "death associated protein kinase 1")) 
(define-protein "DCF" ("GO:0004167" "dopachrome isomerase activity")) 
(define-protein "DCN" ("HGNC:2705" "decorin")) 
(define-protein "DCTs" ("HGNC:2709" "dopachrome tautomerase")) 
(define-protein "DDR" ("XFAM:PF08841.8" "DDR")) 
(define-protein "DDT" ("HGNC:2732" "D-dopachrome tautomerase")) 
(define-protein "DDXs" ("NCIT:C129053" "AKR1C3")) 
(define-protein "DEDD" ("HGNC:2755" "death effector domain containing")) 
(define-protein "DEF" ("FA:00922" "def family")) 
(define-protein "DENN" ("XFAM:PF02141.19" "DENN")) 
(define-protein "DEPP" ("XFAM:PF15343.4" "DEPP")) 
(define-protein "DES" ("HGNC:2770" "desmin")) 
(define-protein "DFX" ("UP:O29425" "Desulfoferrodoxin homolog")) 
(define-protein "DFs" ("NCIT:C84325" "CFD")) 
(define-protein "DGC" ("UP:P0AAP1" "Probable diguanylate cyclase AdrA")) 
(define-protein "DGKalpha" ("NCIT:C112502" "DGKA")) 
(define-protein "DGKtheta" ("UP:P52824" "Diacylglycerol kinase theta")) 
(define-protein "DGKzeta" ("UP:Q13574" "Diacylglycerol kinase zeta")) 
(define-protein "DIF" ("NCIT:C51526" "TNF")) 
(define-protein "DINE" ("HGNC:3147" "endothelin converting enzyme like 1")) 
(define-protein "DJBP" ("HGNC:24204" "EF-hand calcium binding domain 6")) 
(define-protein "DLP" ("HGNC:26041" "thioredoxin like 4B")) 
(define-protein "DMD" ("HGNC:2928" "dystrophin")) 
(define-protein "DMPK" ("HGNC:2933" "dystrophia myotonica protein kinase")) 
(define-protein "DNAPK" ("NCIT:C21483" "protein kinase DNA-activated catalytic subunit")) 
(define-protein "DNAPKcs" ("UP:P78527" "DNA-dependent protein kinase catalytic subunit")) 
(define-protein "DNM" ("HGNC:2972" "dynamin 1")) 
(define-protein "DNTT" ("HGNC:2983" "DNA nucleotidylexotransferase")) 
(define-protein "DPPIV" ("FA:02787" "DPPIV subfamily")) 
(define-protein "DRAM" ("HGNC:25645" "DNA damage regulated autophagy modulator 1")) 
(define-protein "DRB" ("NCIT:C52341" "DRB")) 
(define-protein "DSC" ("HGNC:3037" "desmocollin 3")) 
(define-protein "DSP" ("HGNC:3052" "desmoplakin")) 
(define-protein "DUB" ("UP:A7ZP88" "Protease ElaD")) 
(define-protein "DVL" ("XFAM:PF08137.10" "DVL")) 
(define-protein "DeltaA" ("UP:Q6DI48" "Delta-like protein A")) 
(define-protein "DeltaC" ("UP:Q9IAT6" "Delta-like protein C")) 
(define-protein "DeltaD" ("UP:Q8UWJ4" "Delta-like protein D")) 
(define-protein "DrICE" ("UP:O01382" "Caspase")) 
(define-protein "EAC" ("NCIT:C92680" "CYLD")) 
(define-protein "EAG" ("HGNC:6250" "potassium voltage-gated channel subfamily H member 1")) 
(define-protein "EBI" ("UP:P81705" "Bowman-Birk type proteinase inhibitor")) 
(define-protein "EC" ("UP:Q16769" "Glutaminyl-peptide cyclotransferase")) 
(define-protein "ECSCR" ("HGNC:35454" "endothelial cell surface expressed chemotaxis and apoptosis regulator")) 
(define-protein "EDD" ("NCIT:C111929" "UBR5")) 
(define-protein "EF" ("UP:P40136" "Calmodulin-sensitive adenylate cyclase")) 
(define-protein "EGFRs" ("HGNC:3236" "epidermal growth factor receptor")) 
(define-protein "EGI" ("UP:Q02934" "Endoglucanase 1")) 
(define-protein "EGb" ("UP:P18126" "Endoglucanase B")) 
(define-protein "EL" ("UP:Q5QJ74" "Tubulin-specific chaperone cofactor E-like protein")) 
(define-protein "EMD" ("HGNC:3331" "emerin")) 
(define-protein "EMSY" ("HGNC:18071" "EMSY, BRCA2 interacting transcriptional repressor")) 
(define-protein "ENAM" ("HGNC:3344" "enamelin")) 
(define-protein "ENL" ("NCIT:C33943" "ENL protein")) 
(define-protein "EP" ("NCIT:C49784" "EPO")) 
(define-protein "EPCR" ("NCIT:C118583" "PROCR")) 
(define-protein "EPRS" ("HGNC:3418" "glutamyl-prolyl-tRNA synthetase")) 
(define-protein "ERBP" ("HGNC:24013" "deoxynucleotidyltransferase terminal interacting protein 2")) 
(define-protein "ERF" ("HGNC:3444" "ETS2 repressor factor")) 
(define-protein "ERFS" ("HGNC:4834" "HBS1 like translational GTPase")) 
(define-protein "ERG" ("HGNC:3446" "ERG, ETS transcription factor")) 
(define-protein "ERK 1" ("UP:Q5A1D3" "Extracellular signal-regulated kinase 1")) 
(define-protein "ERRalpha" ("NCIT:C101394" "steroid hormone receptor ERR1")) 
(define-protein "ERb" ("NCIT:C51575" "ESR2")) 
(define-protein "ERs" ("UP:P03372" "Estrogen receptor")) 
(define-protein "ETAR" ("NCIT:C71439" "EDNRA")) 
(define-protein "ETO" ("NCIT:C52522" "CBFA2T1")) 
(define-protein "ETP" ("UP:P46979" "Myoactive tetradecapeptide")) 
(define-protein "ETS" ("FA:01142" "ETS family")) 
(define-protein "EXOG" ("HGNC:3347" "exo/endonuclease G")) 
(define-protein "EXT" ("NCIT:C50957" "EXT1")) 
(define-protein "ElonginB" ("UP:Q15370" "Transcription elongation factor B polypeptide 2")) 
(define-protein "EnR" ("UP:Q9SLA8" "Enoyl-[acyl-carrier-protein] reductase [NADH], chloroplastic")) 
(define-protein "EpsinR" ("UP:Q14677" "Clathrin interactor 1")) 
(define-protein "ErbBs" ("NCIT:C17763" "oncogene ERB-B")) 
(define-protein "EtBr" ("UP:P24530" "Endothelin B receptor")) 
(define-protein "FA" ("XFAM:PF08736.9" "FA")) 
(define-protein "FAC" ("NCIT:C86028" "FANCC")) 
(define-protein "FAIM" ("HGNC:18703" "Fas apoptotic inhibitory molecule")) 
(define-protein "FAKTS" ("HGNC:25444" "Holliday junction recognition protein")) 
(define-protein "FANCJ" ("NCIT:C63527" "BRIP1")) 
(define-protein "FANCM" ("HGNC:23168" "Fanconi anemia complementation group M")) 
(define-protein "FAPalpha" ("NCIT:C17799" "fibroblast activation protein alpha")) 
(define-protein "FB" ("UP:P22027" "ATP synthase subunit s, mitochondrial")) 
(define-protein "FBA" ("XFAM:PF04300.11" "FBA")) 
(define-protein "FBP" ("UP:Q96AE4" "Far upstream element-binding protein 1")) 
(define-protein "FC" ("UP:Q06529" "Cytochrome subunit of sulfide dehydrogenase")) 
(define-protein "FCHL" ("NCIT:C53117" "USF1")) 
(define-protein "FCP" ("UP:Q39709" "Fucoxanthin-chlorophyll a-c binding protein, chloroplastic")) 
(define-protein "FGFR" ("NCIT:C17297" "fibroblast growth factor receptor family")) 
(define-protein "FGFRs" ("NCIT:C17297" "fibroblast growth factor receptor family")) 
(define-protein "FKBPL" ("HGNC:13949" "FK506 binding protein like")) 
(define-protein "FKN" ("NCIT:C49753" "CX3CL1")) 
(define-protein "FLASH" ("NCIT:C126618" "CASP8AP2")) 
(define-protein "FLCN" ("HGNC:27310" "folliculin")) 
(define-protein "FLP" ("UP:P03870" "Site-specific recombinase Flp")) 
(define-protein "FLS" ("UP:Q9ZWQ9" "Flavonol synthase/flavanone 3-hydroxylase")) 
(define-protein "FLSs" ("UP:Q9ZWQ9" "Flavonol synthase/flavanone 3-hydroxylase")) 
(define-protein "FMRP" ("NCIT:C75423" "fragile X mental retardation 1 protein")) 
(define-protein "FOG" ("NCIT:C84287" "ZFPM1")) 
(define-protein "FOXO6" ("HGNC:24814" "forkhead box O6")) 
(define-protein "FRP" ("NCIT:C95301" "SFRP1")) 
(define-protein "FTS" ("FA:04283" "FTS subfamily")) 
(define-protein "FXa" ("NCIT:C76141" "F10")) 
(define-protein "FYB" ("HGNC:4036" "FYN binding protein")) 
(define-protein "FcgammaRIIa" ("NCIT:C38553" "IgG-Fc-receptor-IIA")) 
(define-protein "Forkhead Box O3a" ("NCIT:C28520" "forkhead box-O3A protein")) 
(define-protein "FosB" ("HGNC:3797" "FosB proto-oncogene, AP-1 transcription factor subunit")) 
(define-protein "GAST" ("HGNC:4164" "gastrin")) 
(define-protein "GATA" ("FA:04921" "gatA subfamily")) 
(define-protein "GCA" ("HGNC:15990" "grancalcin")) 
(define-protein "GCK" ("HGNC:4195" "glucokinase")) 
(define-protein "GCTs" ("UP:P27623" "Glycerol-3-phosphate cytidylyltransferase")) 
(define-protein "GCs" ("HGNC:4187" "GC, vitamin D binding protein")) 
(define-protein "GDI" ("GO:0005092" "GDP-dissociation inhibitor activity")) 
(define-protein "GEM" ("HGNC:4234" "GTP binding protein overexpressed in skeletal muscle")) 
(define-protein "GFAT" ("UP:P53704" "Glutamine--fructose-6-phosphate aminotransferase [isomerizing]")) 
(define-protein "GFR" ("HGNC:16862" "Rap guanine nucleotide exchange factor 5")) 
(define-protein "GGPP" ("UP:Q55034" "Glucosylglycerol-phosphate phosphatase")) 
(define-protein "GGTI" ("NCIT:C52049" "PGGT1B")) 
(define-protein "GIV" ("HGNC:25523" "coiled-coil domain containing 88A")) 
(define-protein "GKLF" ("NCIT:C73450" "KLF4")) 
(define-protein "GLA" ("HGNC:4296" "galactosidase alpha")) 
(define-protein "GLI" ("UP:P55878" "Zinc finger protein GLI1")) 
(define-protein "GLP" ("UP:P63294" "Glucagon-like peptide")) 
(define-protein "GLS" ("HGNC:4331" "glutaminase")) 
(define-protein "GLUT" ("NCIT:C52298" "SLC2A1")) 
(define-protein "GLUTs" ("NCIT:C52298" "SLC2A1")) 
(define-protein "GM" ("HGNC:9291" "protein phosphatase 1 regulatory subunit 3A")) 
(define-protein "GMF" ("FA:00087" "GMF subfamily")) 
(define-protein "GMPS" ("HGNC:4378" "guanine monophosphate synthase")) 
(define-protein "GMRalpha" ("UP:P15509" "Granulocyte-macrophage colony-stimulating factor receptor subunit alpha")) 
(define-protein "GPA" ("NCIT:C52348" "GYPA")) 
(define-protein "GPIb" ("UP:P42863" "Glucose-6-phosphate isomerase, cytosolic B")) 
(define-protein "GRD" ("UP:Q24352" "Gamma-aminobutyric acid receptor alpha-like")) 
(define-protein "GRK" ("NCIT:C26233" "G protein-coupled receptor kinase family")) 
(define-protein "GRO" ("NCIT:C20471" "C-X-C motif chemokine ligand-1")) 
(define-protein "GRs" ("UP:P04150" "Glucocorticoid receptor")) 
(define-protein "GSIs" ("UP:P05457" "Glutamine synthetase 1")) 
(define-protein "GSKIP" ("HGNC:20343" "GSK3B interacting protein")) 
(define-protein "GSL" ("HGNC:9251" "cathepsin A")) 
(define-protein "GSLs" ("HGNC:9251" "cathepsin A")) 
(define-protein "GSTpi" ("NCIT:C18049" "glutathione S-transferase-Pi")) 
(define-protein "GT" ("UP:P51161" "Gastrotropin")) 
(define-protein "GTFs" ("UP:P49331" "Glucosyltransferase-S")) 
(define-protein "GW" ("UP:Q96GX5" "Serine/threonine-protein kinase greatwall")) 
(define-protein "GpG" ("UP:P26699" "Probable tail fiber assembly protein")) 
(define-protein "GrB" ("NCIT:C104354" "GZMB wtAllele")) 
(define-protein "GroA" ("NCIT:C49763" "CXCL1")) 
(define-protein "GsPCR" ("GO:0004930" "G-protein coupled receptor activity")) 
(define-protein "GzmA" ("HGNC:4708" "granzyme A")) 
(define-protein "GzmK" ("HGNC:4711" "granzyme K")) 
(define-protein "HAFs" ("NCIT:C104217" "F12")) 
(define-protein "HAM" ("NCIT:C119672" "activating transcription factor 7-interacting protein 1")) 
(define-protein "HAMP" ("HGNC:15598" "hepcidin antimicrobial peptide")) 
(define-protein "HARA" ("NCIT:C107430" "human anti-ricin antibody")) 
(define-protein "HAVCR" ("NCIT:C116607" "HAVCR1")) 
(define-protein "HBD" ("HGNC:4829" "hemoglobin subunit delta")) 
(define-protein "HBM" ("HGNC:4826" "hemoglobin subunit mu")) 
(define-protein "HBZ" ("HGNC:4835" "hemoglobin subunit zeta")) 
(define-protein "HBeAg" ("UP:P0C692" "External core antigen")) 
(define-protein "HC" ("UP:P08897" "Collagenase")) 
(define-protein "HCA" ("UP:P14750" "Hemocyanin A chain")) 
(define-protein "HCC" ("UP:Q9NFL6" "Hemocyanin C chain")) 
(define-protein "HCCP" ("UP:Q95W85" "GFP-like non-fluorescent chromoprotein")) 
(define-protein "HCCs" ("HGNC:4837" "holocytochrome c synthase")) 
(define-protein "HCD" ("UP:P02241" "Hemocyanin D chain")) 
(define-protein "HDGF" ("HGNC:4856" "hepatoma-derived growth factor")) 
(define-protein "HDL" ("NCIT:C113166" "HSD11B1")) 
(define-protein "HDM" ("UP:Q91695" "Probable histone deacetylase 1-A")) 
(define-protein "HDRP" ("NCIT:C102493" "HDAC9")) 
(define-protein "HDX" ("HGNC:26411" "highly divergent homeobox")) 
(define-protein "HDs" ("UP:O22446" "Histone deacetylase 19 {ECO:0000303|PubMed:12466527}")) 
(define-protein "HEF" ("UP:P68762" "Hemagglutinin-esterase-fusion glycoprotein")) 
(define-protein "HEFs" ("UP:P68762" "Hemagglutinin-esterase-fusion glycoprotein")) 
(define-protein "HELQ" ("HGNC:18536" "helicase, POLQ-like")) 
(define-protein "HELZ" ("HGNC:16878" "helicase with zinc finger")) 
(define-protein "HEPACAM" ("HGNC:26361" "hepatic and glial cell adhesion molecule")) 
(define-protein "HET" ("XFAM:PF06985.9" "HET")) 
(define-protein "HEX" ("NCIT:C114958" "HHEX")) 
(define-protein "HF" ("NCIT:C121490" "granzyme A")) 
(define-protein "HFs" ("NCIT:C121490" "granzyme A")) 
(define-protein "HGFL" ("HGNC:24942" "phosphoinositide-3-kinase interacting protein 1")) 
(define-protein "HGFs" ("HGNC:4893" "hepatocyte growth factor")) 
(define-protein "HHC" ("HGNC:1514" "calcium sensing receptor")) 
(define-protein "HHEX" ("HGNC:4901" "hematopoietically expressed homeobox")) 
(define-protein "HIRA" ("HGNC:4916" "histone cell cycle regulator")) 
(define-protein "HJURP" ("HGNC:25444" "Holliday junction recognition protein")) 
(define-protein "HKII" ("NCIT:C51050" "HK2")) 
(define-protein "HKMT" ("UP:Q8X225" "Histone-lysine N-methyltransferase, H3 lysine-9 specific dim-5")) 
(define-protein "HLA" ("NCIT:C121977" "HLA complex")) 
(define-protein "HLFs" ("HGNC:4977" "HLF, PAR bZIP transcription factor")) 
(define-protein "HLTF" ("HGNC:11099" "helicase like transcription factor")) 
(define-protein "HMW" ("HGNC:29276" "cilia and flagella associated protein 97")) 
(define-protein "HNC" ("NCIT:C41046" "matrix metalloproteinase-8")) 
(define-protein "HNE" ("NCIT:C104196" "ELANE")) 
(define-protein "HNRPK" ("HGNC:5044" "heterogeneous nuclear ribonucleoprotein K")) 
(define-protein "HOPS" ("NCIT:C104231" "ALPL")) 
(define-protein "HPIP" ("XFAM:PF15226.4" "HPIP")) 
(define-protein "HPO" ("UP:A6YIH8" "Premnaspirodiene oxygenase")) 
(define-protein "HPR" ("HGNC:5156" "haptoglobin-related protein")) 
(define-protein "HR" ("HGNC:5172" "HR, lysine demethylase and nuclear receptor corepressor")) 
(define-protein "HRI" ("NCIT:C97324" "EIF2AK1")) 
(define-protein "HSD" ("NCIT:C116935" "CHST3")) 
(define-protein "HSF" ("UP:P22813" "Heat shock factor protein")) 
(define-protein "HSL" ("UP:Q05469" "Hormone-sensitive lipase")) 
(define-protein "HSPC" ("HGNC:9536" "proteasome subunit alpha 7")) 
(define-protein "HSPGs" ("UP:P98160" "Basement membrane-specific heparan sulfate proteoglycan core protein")) 
(define-protein "HTR" ("NCIT:C51443" "F2R")) 
(define-protein "HTS" ("UP:Q01886" "HC-toxin synthetase")) 
(define-protein "HUNK" ("HGNC:13326" "hormonally up-regulated Neu-associated kinase")) 
(define-protein "HURP" ("HGNC:16864" "DLG associated protein 5")) 
(define-protein "HepaCAM" ("HGNC:26361" "hepatic and glial cell adhesion molecule")) 
(define-protein "HuD" ("UP:P26378" "ELAV-like protein 4")) 
(define-protein "ICK" ("HGNC:21219" "intestinal cell kinase")) 
(define-protein "ICL" ("GO:0004451" "isocitrate lyase activity")) 
(define-protein "ICOS" ("HGNC:5351" "inducible T-cell costimulator")) 
(define-protein "ICTP" ("NCIT:C107567" "C-terminal telopeptide type I collagen")) 
(define-protein "IDPs" ("NCIT:C77217" "isocitrate dehydrogenase NADP cytoplasmic")) 
(define-protein "IFAs" ("UP:P16274" "Non-neuronal cytoplasmic intermediate filament protein A")) 
(define-protein "IFG" ("NCIT:C52798" "IFNG")) 
(define-protein "IFNR" ("NCIT:C37278" "interferon alpha-beta receptor beta chain")) 
(define-protein "IFNb" ("HGNC:5434" "interferon beta 1")) 
(define-protein "IFNbeta" ("UP:P01574" "Interferon beta")) 
(define-protein "IFP" ("NCIT:C20694" "intermediate filament protein")) 
(define-protein "IFs" ("UP:P22488" "Non-neuronal cytoplasmic intermediate filament protein")) 
(define-protein "IGF" ("UP:P22618" "Insulin-like growth factor")) 
(define-protein "IGFIR" ("NCIT:C51548" "IGF1R")) 
(define-protein "IGFs" ("UP:P22618" "Insulin-like growth factor")) 
(define-protein "IIs" ("HGNC:31748" "secretoglobin family 1D member 4")) 
(define-protein "IK" ("HGNC:5958" "IK cytokine, down-regulator of HLA II")) 
(define-protein "IKAROS" ("NCIT:C68731" "IKZF1")) 
(define-protein "IKK" ("NCIT:C104199" "I-kappa-B kinase")) 
(define-protein "IKKb" ("UP:Q95KV0" "Inhibitor of nuclear factor kappa-B kinase subunit beta")) 
(define-protein "IKKgamma" ("NCIT:C75609" "NF-kappa-B essential modulator")) 
(define-protein "IL" ("NCIT:C20497" "interleukin")) 
(define-protein "IPs" ("NCIT:C97774" "SDHB")) 
(define-protein "IRAS" ("NCIT:C101382" "NISCH")) 
(define-protein "IRF" ("FA:01910" "IRF family")) 
(define-protein "IRGM" ("HGNC:29597" "immunity related GTPase M")) 
(define-protein "IRIS" ("NCIT:C52060" "BRCA1")) 
(define-protein "IRR" ("UP:P14617" "Insulin receptor-related protein")) 
(define-protein "IRTKS" ("NCIT:C106365" "BAIAP2L1")) 
(define-protein "IRs" ("UP:P06213" "Insulin receptor")) 
(define-protein "IVL" ("HGNC:6187" "involucrin")) 
(define-protein "IgH" ("HGNC:5477" "immunoglobulin heavy locus")) 
(define-protein "IkBalpha" ("NCIT:C17678" "I-kappa-B-alpha protein")) 
(define-protein "IkappaBs" ("NCIT:C17583" "I-kappa-B protein")) 
(define-protein "JAKs" ("FA:03129" "JAK subfamily")) 
(define-protein "JAMP" ("HGNC:20184" "JNK1/MAPK8-associated membrane protein")) 
(define-protein "JG" ("UP:P30431" "Zinc metalloproteinase-disintegrin-like jararhagin")) 
(define-protein "JIP" ("UP:P34609" "JNK-interacting protein")) 
(define-protein "JKAP" ("NCIT:C39671" "dual specificity phosphatase-22")) 
(define-protein "JN" ("HGNC:29208" "ermin")) 
(define-protein "JNKs" ("GO:0004705" "JUN kinase activity")) 
(define-protein "JunB" ("HGNC:6205" "JunB proto-oncogene, AP-1 transcription factor subunit")) 
(define-protein "JunD" ("HGNC:6206" "JunD proto-oncogene, AP-1 transcription factor subunit")) 
(define-protein "KANK" ("HGNC:19309" "KN motif and ankyrin repeat domains 1")) 
(define-protein "KAP" ("UP:P61110" "Kidney androgen-regulated protein")) 
(define-protein "KATs" ("NCIT:C118592" "F11R")) 
(define-protein "KD" ("NCIT:C51572" "AR")) 
(define-protein "KEN" ("HGNC:16068" "pericentrin")) 
(define-protein "KFs" ("HGNC:20910" "arylformamidase")) 
(define-protein "KILLIN" ("NCIT:C95287" "KILLIN")) 
(define-protein "KIR" ("NCIT:C104678" "killer-cell immunoglobulin-like receptors")) 
(define-protein "KIS" ("HGNC:19683" "U2AF homology motif kinase 1")) 
(define-protein "KN" ("NCIT:C84438" "CR1")) 
(define-protein "KP" ("UP:P09346" "Knob-associated histidine-rich protein")) 
(define-protein "KRC" ("HGNC:13561" "human immunodeficiency virus type I enhancer binding protein 3")) 
(define-protein "KS" ("UP:Q05356" "Putative polyketide beta-ketoacyl synthase 1")) 
(define-protein "LA" ("NCIT:C70620" "lupus anticoagulant antibody")) 
(define-protein "LAK" ("HGNC:698" "ADP ribosylation factor like GTPase 4C")) 
(define-protein "LANA" ("NCIT:C114489" "latent nuclear antigen")) 
(define-protein "LAR" ("UP:P10586" "Receptor-type tyrosine-protein phosphatase F")) 
(define-protein "LARC" ("NCIT:C49735" "CCL20")) 
(define-protein "LAX" ("XFAM:PF15681.3" "LAX")) 
(define-protein "LBH" ("HGNC:29532" "limb bud and heart development")) 
(define-protein "LBL" ("UP:P16300" "Lectin")) 
(define-protein "LCPTP" ("NCIT:C49528" "PTPN7")) 
(define-protein "LCR" ("UP:P08074" "Carbonyl reductase [NADPH] 2")) 
(define-protein "LCoR" ("HGNC:29503" "ligand dependent nuclear receptor corepressor")) 
(define-protein "LDL" ("NCIT:C25187" "low density lipoprotein")) 
(define-protein "LDs" ("NCIT:C52877" "forkhead box C2")) 
(define-protein "LF" ("UP:P15917" "Lethal factor")) 
(define-protein "LFs" ("UP:P15917" "Lethal factor")) 
(define-protein "LIME" ("HGNC:26016" "Lck interacting transmembrane adaptor 1")) 
(define-protein "LIX" ("NCIT:C20470" "epithelial neutrophil activating peptide-78")) 
(define-protein "LMN" ("NCIT:C52441" "LMNB1")) 
(define-protein "LMP" ("XFAM:PF04778.10" "LMP")) 
(define-protein "LMPs" ("XFAM:PF04778.10" "LMP")) 
(define-protein "LOR" ("HGNC:6663" "loricrin")) 
(define-protein "LPGDS" ("HGNC:9592" "prostaglandin D2 synthase")) 
(define-protein "LPLI" ("NCIT:C104625" "LYPLA1")) 
(define-protein "LPP" ("HGNC:6679" "LIM domain containing preferred translocation partner in lipoma")) 
(define-protein "LPTs" ("NCIT:C97215" "PINX1")) 
(define-protein "LRF" ("NCIT:C52242" "ZBTB7")) 
(define-protein "LRR" ("UP:P84730" "Putative leucine-rich repeat protein PS14")) 
(define-protein "LRRs" ("UP:P84730" "Putative leucine-rich repeat protein PS14")) 
(define-protein "LSF" ("NCIT:C101801" "TFCP2")) 
(define-protein "LYST" ("HGNC:1968" "lysosomal trafficking regulator")) 
(define-protein "LZAP" ("NCIT:C71441" "CDK5RAP3")) 
(define-protein "LZIC" ("HGNC:17497" "leucine zipper and CTNNBIP1 domain containing")) 
(define-protein "LaminC" ("UP:Q03427" "Lamin-C")) 
(define-protein "LigB" ("UP:P9WNV4" "DNA ligase B")) 
(define-protein "LynA" ("UP:P62553" "Antitoxin CcdA")) 
(define-protein "LynB" ("UP:P62555" "Toxin CcdB")) 
(define-protein "MADD" ("HGNC:6766" "MAP kinase activating death domain")) 
(define-protein "MAPKAP kinase-2" ("UP:P49136" "MAP kinase-activated protein kinase 2")) 
(define-protein "MAPKKKs" ("GO:0004709" "MAP kinase kinase kinase activity")) 
(define-protein "MARE" ("NCIT:C106287" "NPRL3")) 
(define-protein "MART" ("UP:Q8K4J0" "Protein artemis")) 
(define-protein "MAT" ("HGNC:6903" "methionine adenosyltransferase 1A")) 
(define-protein "MBPC" ("UP:P11226" "Mannose-binding protein C")) 
(define-protein "MBR" ("NCIT:C122728" "TSPO")) 
(define-protein "MCC" ("HGNC:6935" "mutated in colorectal cancers")) 
(define-protein "MCM" ("UP:P22033" "Methylmalonyl-CoA mutase, mitochondrial")) 
(define-protein "MCP" ("UP:P68673" "Phi-Lf prophage-derived major coat protein")) 
(define-protein "MCSP" ("NCIT:C52436" "CSPG4")) 
(define-protein "MDB" ("HGNC:81" "active BCR-related")) 
(define-protein "MDM" ("HGNC:18746" "secreted LY6/PLAUR domain containing 1")) 
(define-protein "MECR" ("HGNC:19691" "mitochondrial trans-2-enoyl-CoA reductase")) 
(define-protein "MEF" ("NCIT:C97473" "ELF4")) 
(define-protein "MEI5" ("XFAM:PF10376.7" "mei5")) 
(define-protein "MIHA" ("NCIT:C49358" "BIRC4")) 
(define-protein "MIM" ("HGNC:20443" "MTSS1, I-BAR domain containing")) 
(define-protein "MIMP" ("NCIT:C102899" "MTCH2")) 
(define-protein "MISP" ("HGNC:27000" "mitotic spindle positioning")) 
(define-protein "MITA" ("NCIT:C101587" "TMEM173")) 
(define-protein "MIZF" ("HGNC:17850" "histone H4 transcription factor")) 
(define-protein "MK" ("UP:Q03426" "Mevalonate kinase")) 
(define-protein "MKP2" ("NCIT:C112128" "DUSP4")) 
(define-protein "MKs" ("UP:Q03426" "Mevalonate kinase")) 
(define-protein "MLE" ("UP:Q43931" "Muconate cycloisomerase 1")) 
(define-protein "MLM" ("NCIT:C49511" "CDKN2A")) 
(define-protein "MLN" ("HGNC:7141" "motilin")) 
(define-protein "MLTK" ("HGNC:17797" "mitogen-activated protein kinase kinase kinase 20")) 
(define-protein "MLX" ("HGNC:11645" "MLX, MAX dimerization protein")) 
(define-protein "MMC" ("UP:P0A3R9" "Neocarzinostatin")) 
(define-protein "MMH" ("NCIT:C51000" "OGG1")) 
(define-protein "MMP" ("NCIT:C18164" "matrix metalloproteinase")) 
(define-protein "MN" ("NCIT:C52348" "GYPA")) 
(define-protein "MNT" ("HGNC:7188" "MAX network transcriptional repressor")) 
(define-protein "MNs" ("NCIT:C52348" "GYPA")) 
(define-protein "MOG" ("HGNC:7197" "myelin oligodendrocyte glycoprotein")) 
(define-protein "MOMP" ("UP:Q46203" "Major outer membrane porin")) 
(define-protein "MOZ" ("NCIT:C71430" "MYST3")) 
(define-protein "MP" ("UP:P0C648" "Movement protein")) 
(define-protein "MPC" ("UP:Q53034" "Metapyrocatechase")) 
(define-protein "MPCs" ("UP:Q53034" "Metapyrocatechase")) 
(define-protein "MPD" ("UP:A6RGF3" "Mannitol-1-phosphate 5-dehydrogenase")) 
(define-protein "MPTP" ("UP:Q06180" "Tyrosine-protein phosphatase non-receptor type 2")) 
(define-protein "MR" ("UP:P08235" "Mineralocorticoid receptor")) 
(define-protein "MRC" ("NCIT:C80106" "CD200")) 
(define-protein "MRCK" ("HGNC:1737" "CDC42 binding protein kinase alpha")) 
(define-protein "MRG" ("XFAM:PF05712.11" "MRG")) 
(define-protein "MRNIP" ("HGNC:30817" "MRN complex interacting protein")) 
(define-protein "MRX" ("NCIT:C52276" "ABCG2")) 
(define-protein "MSH" ("UP:D4GTL2" "Malate synthase")) 
(define-protein "MSI" ("UP:Q3BK13" "Disintegrin lebein-2-alpha")) 
(define-protein "MSLN" ("HGNC:7371" "mesothelin")) 
(define-protein "MTAP" ("HGNC:7413" "methylthioadenosine phosphorylase")) 
(define-protein "MTBP" ("HGNC:7417" "MDM2 binding protein")) 
(define-protein "MTP" ("UP:Q1HVJ0" "Major tegument protein")) 
(define-protein "MTs" ("UP:P03076" "Middle T antigen")) 
(define-protein "MU" ("HGNC:18561" "biogenesis of lysosomal organelles complex 1 subunit 5")) 
(define-protein "MX" ("NCIT:C113310" "MX1")) 
(define-protein "MYCBP" ("HGNC:7554" "MYC binding protein")) 
(define-protein "MYCC" ("HGNC:7553" "v-myc avian myelocytomatosis viral oncogene homolog")) 
(define-protein "MYH" ("NCIT:C61057" "MUTYH")) 
(define-protein "MYOC" ("HGNC:7610" "myocilin")) 
(define-protein "MYOCD" ("HGNC:16067" "myocardin")) 
(define-protein "MYPN" ("HGNC:23246" "myopalladin")) 
(define-protein "MaSC" ("UP:Q9EPB4" "Apoptosis-associated speck-like protein containing a CARD")) 
(define-protein "MaSCs" ("UP:Q9EPB4" "Apoptosis-associated speck-like protein containing a CARD")) 
(define-protein "MetS" ("NCIT:C52869" "ETV3")) 
(define-protein "MiR" ("UP:Q93105" "Insulin-like receptor")) 
(define-protein "MondoA" ("HGNC:17055" "MLX interacting protein")) 
(define-protein "MstI" ("UP:P80321" "Bowman-Birk type proteinase inhibitor")) 
(define-protein "NAIP" ("HGNC:7634" "NLR family apoptosis inhibitory protein")) 
(define-protein "NAK" ("NCIT:C30077" "TANK-binding kinase-1")) 
(define-protein "NB" ("XFAM:PF04159.11" "NB")) 
(define-protein "NBK" ("NCIT:C49374" "BIK")) 
(define-protein "NBN" ("HGNC:7652" "nibrin")) 
(define-protein "NC" ("NCIT:C97444" "N-chimaerin")) 
(define-protein "NCA" ("NCIT:C107470" "CEACAM6")) 
(define-protein "NCM" ("HGNC:29322" "CWC22 spliceosome associated protein homolog")) 
(define-protein "NCP" ("UP:P22175" "Major non-capsid protein")) 
(define-protein "NCS" ("UP:P0A3R9" "Neocarzinostatin")) 
(define-protein "NCYM" ("NCIT:C52133" "NCYM")) 
(define-protein "NDN" ("HGNC:7675" "necdin, MAGE family member")) 
(define-protein "NDPK" ("UP:Q9UR66" "Nucleoside diphosphate kinase")) 
(define-protein "NEB" ("HGNC:7720" "nebulin")) 
(define-protein "NELF" ("HGNC:29843" "NMDA receptor synaptonuclear signaling and neuronal migration factor")) 
(define-protein "NER" ("UP:P06903" "Negative regulator of transcription")) 
(define-protein "NFAT" ("NCIT:C17903" "NF-AT")) 
(define-protein "NFI" ("HGNC:7765" "neurofibromin 1")) 
(define-protein "NFkB" ("NCIT:C17380" "NF-kB")) 
(define-protein "NFs" ("HGNC:29866" "neurofascin")) 
(define-protein "NGT" ("UP:A3N2T3" "UDP-glucose:protein N-beta-glucosyltransferase")) 
(define-protein "NIAM" ("HGNC:29551" "transforming growth factor beta regulator 1")) 
(define-protein "NIBAN" ("FA:02467" "niban family")) 
(define-protein "NID" ("NCIT:C52485" "NID")) 
(define-protein "NIFK" ("HGNC:17838" "nucleolar protein interacting with the FHA domain of MKI67")) 
(define-protein "NIRF" ("HGNC:5982" "interleukin 17B")) 
(define-protein "NIS" ("NCIT:C17536" "sodium-iodide symporter")) 
(define-protein "NMDARs" ("NCIT:C118457" "N-methyl-D-aspartate receptor")) 
(define-protein "NMI" ("HGNC:7854" "N-myc and STAT interactor")) 
(define-protein "NOD" ("XFAM:PF06816.11" "NOD")) 
(define-protein "NONO" ("HGNC:7871" "non-POU domain containing, octamer-binding")) 
(define-protein "NOS" ("UP:O61608" "Nitric oxide synthase")) 
(define-protein "NP" ("UP:Q9JGU1" "Nucleoprotein")) 
(define-protein "NPAT" ("HGNC:7896" "nuclear protein, coactivator of histone transcription")) 
(define-protein "NPF" ("UP:Q8MP00" "Neuropeptide F")) 
(define-protein "NPFs" ("UP:Q8MP00" "Neuropeptide F")) 
(define-protein "NPP" ("XFAM:PF08384.8" "NPP")) 
(define-protein "NPPA" ("HGNC:7939" "natriuretic peptide A")) 
(define-protein "NPs" ("HGNC:33940" "neuropeptide S")) 
(define-protein "NR" ("UP:P27967" "Nitrate reductase [NADH]")) 
(define-protein "NRARP" ("HGNC:33843" "NOTCH-regulated ankyrin repeat protein")) 
(define-protein "NRDc" ("HGNC:7995" "nardilysin convertase")) 
(define-protein "NRs" ("UP:P27967" "Nitrate reductase [NADH]")) 
(define-protein "NSE" ("NCIT:C62213" "ENO2")) 
(define-protein "NSPs" ("NCIT:C97532" "SPECC1")) 
(define-protein "NTM" ("HGNC:17941" "neurotrimin")) 
(define-protein "NTS" ("HGNC:8038" "neurotensin")) 
(define-protein "NTg" ("HGNC:8140" "OPA1, mitochondrial dynamin like GTPase")) 
(define-protein "NUMBL" ("HGNC:8061" "NUMB like, endocytic adaptor protein")) 
(define-protein "NURF" ("NCIT:C19801" "NURF")) 
(define-protein "NUT" ("FA:05191" "NUT family")) 
(define-protein "OBP" ("UP:P10193" "Replication origin-binding protein")) 
(define-protein "OBs" ("NCIT:C95049" "LEP")) 
(define-protein "OCI" ("UP:P09229" "Cysteine proteinase inhibitor 1")) 
(define-protein "OCRL" ("HGNC:8108" "OCRL, inositol polyphosphate-5-phosphatase")) 
(define-protein "OCs" ("NCIT:C104591" "BGLAP")) 
(define-protein "ODD" ("HGNC:4274" "gap junction protein alpha 1")) 
(define-protein "OGA" ("UP:Q9EQQ9" "Protein O-GlcNAcase {ECO:0000303|PubMed:16517082}")) 
(define-protein "OGF" ("NCIT:C126497" "met-enkephalin")) 
(define-protein "OPG" ("NCIT:C51379" "TNFRSF11B")) 
(define-protein "OREBP" ("NCIT:C93132" "NFAT5")) 
(define-protein "OSA" ("NCIT:C19862" "OSA")) 
(define-protein "OT" ("NCIT:C52423" "OXT")) 
(define-protein "OTR" ("UP:P30559" "Oxytocin receptor")) 
(define-protein "OVT" ("UP:P85895" "Ovotransferrin {ECO:0000303|PubMed:21058653}")) 
(define-protein "PAB" ("UP:P9WGU0" "Phosphate-binding protein PstS 1")) 
(define-protein "PACAP" ("UP:P18509" "Pituitary adenylate cyclase-activating polypeptide")) 
(define-protein "PAFR" ("UP:P25105" "Platelet-activating factor receptor")) 
(define-protein "PAL" ("UP:P35511" "Phenylalanine ammonia-lyase")) 
(define-protein "PALMD" ("HGNC:15846" "palmdelphin")) 
(define-protein "PAM" ("HGNC:8596" "peptidylglycine alpha-amidating monooxygenase")) 
(define-protein "PAMPs" ("UP:Q96TA2" "ATP-dependent zinc metalloprotease YME1L1")) 
(define-protein "PAO" ("XFAM:PF08417.10" "PaO")) 
(define-protein "PAPC" ("HGNC:8660" "protocadherin 8")) 
(define-protein "PARC" ("NCIT:C49723" "CCL18")) 
(define-protein "PARI" ("UP:Q9NWS1" "PCNA-interacting partner")) 
(define-protein "PARP" ("UP:P35875" "Poly [ADP-ribose] polymerase")) 
(define-protein "PASK" ("HGNC:17270" "PAS domain containing serine/threonine kinase")) 
(define-protein "PATZ" ("NCIT:C97877" "PATZ1")) 
(define-protein "PBC" ("XFAM:PF03792.11" "PBC")) 
(define-protein "PBEF" ("NCIT:C50958" "PBEF")) 
(define-protein "PBK" ("HGNC:18282" "PDZ binding kinase")) 
(define-protein "PCAD" ("NCIT:C51152" "CDH3")) 
(define-protein "PCDGF" ("NCIT:C101402" "GRN")) 
(define-protein "PCM" ("UP:O42781" "Mitogen-activated protein kinase 2")) 
(define-protein "PCNS" ("UP:Q7SZN0" "Venom prothrombin activator pseutarin-C non-catalytic subunit")) 
(define-protein "PCNT" ("HGNC:16068" "pericentrin")) 
(define-protein "PCTAIRE" ("HGNC:8749" "cyclin dependent kinase 16")) 
(define-protein "PCa" ("UP:P00299" "Plastocyanin A, chloroplastic")) 
(define-protein "PDE" ("HGNC:877" "aldehyde dehydrogenase 7 family member A1")) 
(define-protein "PDEF" ("NCIT:C102919" "SPDEF")) 
(define-protein "PDGFRs" ("GO:0005017" "platelet-derived growth factor-activated receptor activity")) 
(define-protein "PDIp" ("UP:Q13087" "Protein disulfide-isomerase A2")) 
(define-protein "PDPN" ("HGNC:29602" "podoplanin")) 
(define-protein "PDX" ("UP:P00259" "Putidaredoxin")) 
(define-protein "PELP" ("UP:Q03211" "Pistil-specific extensin-like protein")) 
(define-protein "PEPD" ("HGNC:8840" "peptidase D")) 
(define-protein "PFL" ("GO:0008861" "formate C-acetyltransferase activity")) 
(define-protein "PFM" ("NCIT:C74966" "ALX4")) 
(define-protein "PG" ("UP:Q9LW07" "Probable polygalacturonase At3g15720")) 
(define-protein "PGC" ("HGNC:8890" "progastricsin")) 
(define-protein "PGD" ("HGNC:8891" "phosphogluconate dehydrogenase")) 
(define-protein "PGDH" ("UP:O04130" "D-3-phosphoglycerate dehydrogenase 2, chloroplastic")) 
(define-protein "PGIS" ("NCIT:C96439" "PTGIS")) 
(define-protein "PGM" ("UP:Q9SCY0" "Phosphoglucomutase, chloroplastic")) 
(define-protein "PGs" ("UP:Q9LW07" "Probable polygalacturonase At3g15720")) 
(define-protein "PHLPPL" ("NCIT:C107126" "PHLPP2")) 
(define-protein "PIA" ("UP:P13415" "Major outer membrane protein P.IA")) 
(define-protein "PIASxalpha" ("HGNC:17311" "protein inhibitor of activated STAT 2")) 
(define-protein "PIASxbeta" ("HGNC:17311" "protein inhibitor of activated STAT 2")) 
(define-protein "PIBF" ("UP:Q8WXW3" "Progesterone-induced-blocking factor 1")) 
(define-protein "PICOT" ("NCIT:C95248" "glutaredoxin-3")) 
(define-protein "PIF" ("XFAM:PF05092.10" "PIF")) 
(define-protein "PIM" ("FA:03078" "PIM subfamily")) 
(define-protein "PIPKIIbeta" ("NCIT:C34025" "phosphatidylinositol-4-phosphate-5-kinase type-II beta")) 
(define-protein "PITALRE" ("NCIT:C126981" "CDK9")) 
(define-protein "PKBbeta" ("NCIT:C51185" "AKT2")) 
(define-protein "PKCmu" ("NCIT:C95257" "PRKD1")) 
(define-protein "PKDs" ("FA:03079" "PKD subfamily")) 
(define-protein "PKIB" ("HGNC:9018" "protein kinase (cAMP-dependent, catalytic) inhibitor beta")) 
(define-protein "PKK" ("XFAM:PF12474.6" "PKK")) 
(define-protein "PLD" ("UP:C0JAT4" "Phospholipase D LhSicTox-alphaIA1i")) 
(define-protein "PLK" ("NCIT:C51263" "PLK")) 
(define-protein "PMF" ("HGNC:9337" "proline rich protein BstNI subfamily 1")) 
(define-protein "PML" ("HGNC:9113" "promyelocytic leukemia")) 
(define-protein "PNA" ("UP:P02872" "Galactose-binding lectin")) 
(define-protein "PNK" ("UP:P06855" "Polynucleotide kinase")) 
(define-protein "PNR" ("HGNC:7974" "nuclear receptor subfamily 2 group E member 3")) 
(define-protein "PNUTS" ("HGNC:9284" "protein phosphatase 1 regulatory subunit 10")) 
(define-protein "POK" ("UP:Q58379" "Putative pantoate kinase")) 
(define-protein "POLG" ("HGNC:9179" "DNA polymerase gamma, catalytic subunit")) 
(define-protein "POLQ" ("HGNC:9186" "DNA polymerase theta")) 
(define-protein "POX" ("UP:Q5B2E9" "Pyranose 2-oxidase")) 
(define-protein "PPAN" ("HGNC:9227" "peter pan homolog (Drosophila)")) 
(define-protein "PPARbeta" ("NCIT:C96462" "peroxisome proliferator-activated receptor delta")) 
(define-protein "PPARdelta" ("UP:Q0ZAQ8" "Peroxisome proliferator-activated receptor delta")) 
(define-protein "PRD" ("UP:G4MZI3" "NAD(P)H-dependent pentose reductase")) 
(define-protein "PRG" ("HGNC:9339" "proline rich protein BstNI subfamily 3")) 
(define-protein "PRI" ("NCIT:C101603" "RNH1")) 
(define-protein "PRK" ("UP:P25697" "Phosphoribulokinase, chloroplastic")) 
(define-protein "PRKAA" ("NCIT:C116019" "5-AMP-activated protein kinase catalytic subunit alpha")) 
(define-protein "PRM" ("UP:O74478" "Probable phosphoribomutase {ECO:0000250|UniProtKB:Q03262}")) 
(define-protein "PRR" ("UP:P07052" "Pathogenesis-related protein R minor form")) 
(define-protein "PRUNE" ("FA:02994" "prune subfamily")) 
(define-protein "PRY" ("HGNC:14024" "PTPN13-like, Y-linked")) 
(define-protein "PRs" ("UP:P06401" "Progesterone receptor")) 
(define-protein "PSA" ("UP:P07288" "Prostate-specific antigen")) 
(define-protein "PSD" ("HGNC:9507" "pleckstrin and Sec7 domain containing")) 
(define-protein "PSF" ("NCIT:C71444" "splicing factor proline-and glutamine-rich")) 
(define-protein "PSTI" ("NCIT:C17448" "serine protease inhibitor kazal type-1")) 
(define-protein "PTCH" ("NCIT:C51720" "PTCH")) 
(define-protein "PTCs" ("UP:Q13635" "Protein patched homolog 1")) 
(define-protein "PTGES" ("HGNC:9599" "prostaglandin E synthase")) 
(define-protein "PTIP" ("NCIT:C112903" "PAXIP1")) 
(define-protein "PTMS" ("HGNC:9629" "parathymosin")) 
(define-protein "PTPRD" ("HGNC:9668" "protein tyrosine phosphatase, receptor type D")) 
(define-protein "PTS" ("HGNC:9689" "6-pyruvoyltetrahydropterin synthase")) 
(define-protein "PTTG" ("NCIT:C49536" "PTTG1")) 
(define-protein "PTalpha" ("UP:Q0VCS0" "Pre T-cell antigen receptor alpha")) 
(define-protein "PURalpha" ("NCIT:C51297" "PURA")) 
(define-protein "PXK" ("HGNC:23326" "PX domain containing serine/threonine kinase like")) 
(define-protein "PYK" ("HGNC:8926" "phosphorylase kinase regulatory subunit alpha 2")) 
(define-protein "PYM" ("FA:04685" "pym family")) 
(define-protein "PolH" ("HGNC:9181" "DNA polymerase eta")) 
(define-protein "PrSCs" ("HGNC:19012" "corin, serine peptidase")) 
(define-protein "PrimPol" ("HGNC:26575" "primase and DNA directed polymerase")) 
(define-protein "ProF" ("NCIT:C122830" "WDFY2")) 
(define-protein "QKI" ("HGNC:21100" "QKI, KH domain containing RNA binding")) 
(define-protein "QM" ("NCIT:C53153" "RPL10")) 
(define-protein "RA" ("UP:P10896" "Ribulose bisphosphate carboxylase/oxygenase activase, chloroplastic")) 
(define-protein "RAB" ("FA:03661" "rab family")) 
(define-protein "RAGEF" ("UP:G5EDB9" "Rap guanine nucleotide exchange factor")) 
(define-protein "RAH" ("HGNC:16519" "RAB34, member RAS oncogene family")) 
(define-protein "RALT" ("NCIT:C101730" "ERRFI1")) 
(define-protein "RARA" ("HGNC:9864" "retinoic acid receptor alpha")) 
(define-protein "RARbeta" ("UP:P22448" "Retinoic acid receptor beta")) 
(define-protein "RARgamma" ("UP:P13631" "Retinoic acid receptor gamma")) 
(define-protein "RARs" ("HGNC:9870" "arginyl-tRNA synthetase")) 
(define-protein "RAX" ("HGNC:18662" "retina and anterior neural fold homeobox")) 
(define-protein "RBCC" ("HGNC:13430" "tripartite motif containing 17")) 
(define-protein "RBPMS" ("HGNC:19097" "RNA binding protein with multiple splicing")) 
(define-protein "RBaK" ("HGNC:17680" "RB associated KRAB zinc finger")) 
(define-protein "RCL" ("HGNC:21218" "2'-deoxynucleoside 5'-phosphate N-hydrolase 1")) 
(define-protein "RECs" ("HGNC:16147" "minichromosome maintenance 8 homologous recombination repair factor")) 
(define-protein "REF" ("XFAM:PF05755.10" "REF")) 
(define-protein "REFs" ("XFAM:PF05755.10" "REF")) 
(define-protein "REGgamma" ("NCIT:C95864" "proteasome activator complex subunit 3")) 
(define-protein "REN" ("HGNC:9958" "renin")) 
(define-protein "RFC" ("NCIT:C103948" "folate transporter 1")) 
(define-protein "RFFL" ("HGNC:24821" "ring finger and FYVE like domain containing E3 ubiquitin protein ligase")) 
(define-protein "RFG" ("NCIT:C19886" "nuclear receptor coactivator-4")) 
(define-protein "RGDS" ("HGNC:9842" "ral guanine nucleotide dissociation stimulator")) 
(define-protein "RHD" ("HGNC:10009" "Rh blood group D antigen")) 
(define-protein "RICS" ("HGNC:17399" "Rho GTPase activating protein 32")) 
(define-protein "RIL" ("NCIT:C54424" "RIL")) 
(define-protein "RIM" ("UP:Q22366" "Rab-3-interacting molecule unc-10")) 
(define-protein "RIP" ("UP:P56626" "Type I ribosome-inactivating protein trichoanguina")) 
(define-protein "RIS" ("HGNC:30289" "RAS like family 12")) 
(define-protein "RISC" ("UP:Q7F613" "Secretory carrier-associated membrane protein 2")) 
(define-protein "RIZ" ("HGNC:9347" "PR/SET domain 2")) 
(define-protein "RKTG" ("UP:Q6TCH7" "Progestin and adipoQ receptor family member 3")) 
(define-protein "RLP" ("UP:Q5WH45" "Putative 2,3-diketo-5-methylthiopentyl-1-phosphate enolase")) 
(define-protein "RO" ("NCIT:C95314" "CALR")) 
(define-protein "ROCKI" ("UP:Q13464" "Rho-associated protein kinase 1")) 
(define-protein "RORalpha" ("NCIT:C29881" "RAR-related orphan receptor-A")) 
(define-protein "RORgammat" ("NCIT:C106314" "nuclear receptor ROR-gamma T")) 
(define-protein "RP" ("HGNC:7414" "mitochondrially encoded ATP synthase 6")) 
(define-protein "RPA" ("UP:O27438" "Replication factor A")) 
(define-protein "RPE" ("HGNC:10293" "ribulose-5-phosphate-3-epimerase")) 
(define-protein "RPEs" ("HGNC:10293" "ribulose-5-phosphate-3-epimerase")) 
(define-protein "RPF" ("UP:Q7CQE0" "tRNA threonylcarbamoyladenosine biosynthesis protein TsaB")) 
(define-protein "RPTOR" ("HGNC:30287" "regulatory associated protein of MTOR complex 1")) 
(define-protein "RPTPalpha" ("UP:P18433" "Receptor-type tyrosine-protein phosphatase alpha")) 
(define-protein "RPTPepsilon" ("UP:P23469" "Receptor-type tyrosine-protein phosphatase epsilon")) 
(define-protein "RPTPs" ("UP:Q13332" "Receptor-type tyrosine-protein phosphatase S")) 
(define-protein "RPTPsigma" ("NCIT:C124925" "receptor-type tyrosine-protein phosphatase S")) 
(define-protein "RPs" ("HGNC:7414" "mitochondrially encoded ATP synthase 6")) 
(define-protein "RRAD" ("HGNC:10446" "RRAD, Ras related glycolysis inhibitor and calcium channel regulator")) 
(define-protein "RRP" ("UP:O75783" "Rhomboid-related protein 1")) 
(define-protein "RTA" ("UP:Q1HVG0" "Replication and transcription activator")) 
(define-protein "RTIs" ("UP:P80301" "Defensin-like protein 4")) 
(define-protein "RX" ("HGNC:18662" "retina and anterior neural fold homeobox")) 
(define-protein "RYBP" ("HGNC:10480" "RING1 and YY1 binding protein")) 
(define-protein "RanGAP" ("UP:Q9VIW3" "Ran GTPase-activating protein")) 
(define-protein "RhoGAP" ("UP:P38339" "RHO GTPase-activating protein RGD1")) 
(define-protein "RhoGEF" ("GO:0005089" "Rho guanyl-nucleotide exchange factor activity")) 
(define-protein "RyRs" ("XFAM:PF02026.14" "RyR")) 
(define-protein "SAC" ("HGNC:21285" "adenylate cyclase 10, soluble")) 
(define-protein "SAMS" ("HGNC:6903" "methionine adenosyltransferase 1A")) 
(define-protein "SAPKalpha" ("UP:Q86AT8" "Stress-activated protein kinase alpha")) 
(define-protein "SAPKbeta" ("UP:P49187" "Mitogen-activated protein kinase 10")) 
(define-protein "SAPKs" ("GO:0016909" "SAP kinase activity")) 
(define-protein "SARI" ("UP:Q8N1L9" "Basic leucine zipper transcriptional factor ATF-like 2")) 
(define-protein "SARM" ("NCIT:C102780" "SARM1")) 
(define-protein "SASPs" ("XFAM:PF00269.18" "SASP")) 
(define-protein "SAT" ("NCIT:C51343" "SAT")) 
(define-protein "SCA" ("UP:Q10992" "Cysteine proteinase inhibitor A")) 
(define-protein "SCAPs" ("HGNC:30634" "SREBF chaperone")) 
(define-protein "SCCs" ("HGNC:10569" "serpin family B member 3")) 
(define-protein "SCG" ("UP:P70168" "Importin subunit beta-1")) 
(define-protein "SCGs" ("UP:P70168" "Importin subunit beta-1")) 
(define-protein "SCs" ("UP:O81191" "1,8-cineole synthase, chloroplastic")) 
(define-protein "SDS" ("HGNC:10691" "serine dehydratase")) 
(define-protein "SEA" ("XFAM:PF01390.18" "SEA")) 
(define-protein "SELS" ("UP:Q9BQE4" "Selenoprotein S")) 
(define-protein "SERPIN" ("FA:03578" "serpin family")) 
(define-protein "SFB" ("UP:P21272" "CCAAT/enhancer-binding protein beta {ECO:0000312|RGD:2327}")) 
(define-protein "SFs" ("NCIT:C51506" "HGF")) 
(define-protein "SGT" ("FA:03594" "SGT family")) 
(define-protein "SHK" ("UP:Q9UHJ6" "Sedoheptulokinase")) 
(define-protein "SHP" ("XFAM:PF03579.11" "SHP")) 
(define-protein "SHPRH" ("HGNC:19336" "SNF2 histone linker PHD RING helicase")) 
(define-protein "SHPs" ("XFAM:PF03579.11" "SHP")) 
(define-protein "SIPAR" ("HGNC:22422" "family with sequence similarity 220 member A")) 
(define-protein "SIRP" ("NCIT:C51031" "PTPNS1")) 
(define-protein "SIRPalpha" ("NCIT:C51031" "PTPNS1")) 
(define-protein "SIVA" ("XFAM:PF05458.10" "siva")) 
(define-protein "SKIL" ("HGNC:10897" "SKI like proto-oncogene")) 
(define-protein "SKIP" ("NCIT:C29993" "SKI-interacting protein")) 
(define-protein "SKY" ("HGNC:12446" "TYRO3 protein tyrosine kinase")) 
(define-protein "SL" ("UP:P05045" "Seed lectin subunit I")) 
(define-protein "SLAM" ("XFAM:PF06214.9" "SLAM")) 
(define-protein "SLD" ("HGNC:10933" "solute carrier family 17 member 5")) 
(define-protein "SLIM" ("NCIT:C105696" "PDLIM2")) 
(define-protein "SMC" ("FA:03684" "SMC family")) 
(define-protein "SMN" ("FA:03696" "SMN family")) 
(define-protein "SMOX" ("HGNC:15862" "spermine oxidase")) 
(define-protein "SMS" ("HGNC:11123" "spermine synthase")) 
(define-protein "SMTN" ("HGNC:11126" "smoothelin")) 
(define-protein "SNAP" ("FA:03701" "SNAP family")) 
(define-protein "SNARE" ("GO:0005484" "SNAP receptor activity")) 
(define-protein "SNCA" ("HGNC:11138" "synuclein alpha")) 
(define-protein "SNCG" ("HGNC:11141" "synuclein gamma")) 
(define-protein "SNFT" ("HGNC:28915" "basic leucine zipper ATF-like transcription factor 3")) 
(define-protein "SNT" ("NCIT:C52381" "FRS2")) 
(define-protein "SOST" ("HGNC:13771" "sclerostin")) 
(define-protein "SOUL" ("XFAM:PF04832.10" "SOUL")) 
(define-protein "SPC" ("UP:P11686" "Pulmonary surfactant-associated protein C")) 
(define-protein "SPH" ("UP:P13082" "Streptomycin 3''-kinase")) 
(define-protein "SPIB" ("HGNC:11242" "Spi-B transcription factor")) 
(define-protein "SPRY" ("UP:O44783" "Protein sprouty")) 
(define-protein "SRA" ("UP:P68193" "Stationary-phase-induced ribosome-associated protein")) 
(define-protein "SRAP" ("XFAM:PF02586.12" "SRAP")) 
(define-protein "SRCAP" ("HGNC:16974" "Snf2 related CREBBP activator protein")) 
(define-protein "SRCs" ("HGNC:11283" "SRC proto-oncogene, non-receptor tyrosine kinase")) 
(define-protein "SRL" ("HGNC:11295" "sarcalumenin")) 
(define-protein "SRY" ("HGNC:11311" "sex determining region Y")) 
(define-protein "SSB" ("HGNC:11316" "Sjogren syndrome antigen B")) 
(define-protein "SSF" ("XFAM:PF00474.15" "SSF")) 
(define-protein "SSP" ("UP:D8KY57" "Probable salivary secreted peptide")) 
(define-protein "STARD9" ("HGNC:19162" "StAR related lipid transfer domain containing 9")) 
(define-protein "STF" ("UP:P03764" "Tail fiber protein {ECO:0000305}")) 
(define-protein "STH" ("HGNC:18839" "saitohin")) 
(define-protein "STIP" ("HGNC:18248" "elongator acetyltransferase complex subunit 2")) 
(define-protein "STM" ("UP:Q9SZJ5" "Serine hydroxymethyltransferase 1, mitochondrial")) 
(define-protein "STYX" ("HGNC:11447" "serine/threonine/tyrosine interacting protein")) 
(define-protein "SUMO" ("UP:P55853" "Small ubiquitin-related modifier")) 
(define-protein "SVIL" ("HGNC:11480" "supervillin")) 
(define-protein "SVIP" ("HGNC:25238" "small VCP interacting protein")) 
(define-protein "SYNs" ("NCIT:C51117" "FYN")) 
(define-protein "SeV" ("UP:P07647" "Submandibular glandular kallikrein-9")) 
(define-protein "SelH" ("UP:Q8IZQ5" "Selenoprotein H")) 
(define-protein "ShcD" ("HGNC:16743" "SHC adaptor protein 4")) 
(define-protein "SnoN" ("NCIT:C29970" "SKI-like protein-SKIL")) 
(define-protein "SphKs" ("NCIT:C92512" "SPHK1")) 
(define-protein "StpC" ("UP:P25050" "Saimiri transformation-associated protein")) 
(define-protein "TAK" ("NCIT:C126981" "CDK9")) 
(define-protein "TAKl" ("HGNC:16457" "MAP3K7 C-terminal like")) 
(define-protein "TARC" ("NCIT:C49720" "CCL17")) 
(define-protein "TATI" ("NCIT:C17448" "serine protease inhibitor kazal type-1")) 
(define-protein "TAs" ("UP:P37303" "Low specificity L-threonine aldolase")) 
(define-protein "TBCD" ("HGNC:11581" "tubulin folding cofactor D")) 
(define-protein "TBET" ("NCIT:C104249" "TBX21")) 
(define-protein "TC" ("NCIT:C129396" "transcobalamin")) 
(define-protein "TCL" ("NCIT:C106081" "RHOJ")) 
(define-protein "TCSs" ("HGNC:11654" "treacle ribosome biogenesis factor 1")) 
(define-protein "TCTP" ("UP:P13693" "Translationally-controlled tumor protein")) 
(define-protein "TET" ("UP:O59196" "Tetrahedral aminopeptidase")) 
(define-protein "TFEB" ("HGNC:11753" "transcription factor EB")) 
(define-protein "TFIIH" ("NCIT:C20593" "TFIIH")) 
(define-protein "TFIIIC" ("NCIT:C29681" "general transcription factor-IIIC1 alpha subunit")) 
(define-protein "TG" ("HGNC:11764" "thyroglobulin")) 
(define-protein "TGA" ("NCIT:C75412" "TBX1")) 
(define-protein "TGCs" ("HGNC:11778" "transglutaminase 2")) 
(define-protein "TGFa" ("HGNC:11765" "transforming growth factor alpha")) 
(define-protein "TGIF" ("NCIT:C75418" "TGIF1")) 
(define-protein "TGY" ("HGNC:16255" "transglutaminase 6")) 
(define-protein "TGZ" ("UP:Q96PF1" "Protein-glutamine gamma-glutamyltransferase Z")) 
(define-protein "TGs" ("HGNC:11764" "thyroglobulin")) 
(define-protein "THIF" ("NCIT:C113218" "TXNIP")) 
(define-protein "TIEG" ("HGNC:11810" "Kruppel like factor 10")) 
(define-protein "TIF" ("HGNC:12446" "TYRO3 protein tyrosine kinase")) 
(define-protein "TIRAP" ("HGNC:17192" "TIR domain containing adaptor protein")) 
(define-protein "TK" ("UP:P29401" "Transketolase")) 
(define-protein "TKIs" ("UP:P16223" "Locustatachykinin-1")) 
(define-protein "TKR" ("NCIT:C17660" "receptor tyrosine kinase")) 
(define-protein "TKRs" ("NCIT:C17660" "receptor tyrosine kinase")) 
(define-protein "TMEPAI" ("HGNC:14107" "prostate transmembrane protein, androgen induced 1")) 
(define-protein "TMS" ("NCIT:C51047" "TYMS")) 
(define-protein "TMX" ("HGNC:15487" "thioredoxin related transmembrane protein 1")) 
(define-protein "TNFRI" ("NCIT:C51380" "TNFRSF1A")) 
(define-protein "TNFRII" ("NCIT:C51381" "TNFRSF1B")) 
(define-protein "TNIK" ("HGNC:30765" "TRAF2 and NCK interacting kinase")) 
(define-protein "TNL" ("HGNC:31859" "tripartite motif containing 67")) 
(define-protein "TOB" ("HGNC:11979" "transducer of ERBB2, 1")) 
(define-protein "TOF" ("HGNC:13506" "FEZ family zinc finger 2")) 
(define-protein "TONSL" ("HGNC:7801" "tonsoku-like, DNA repair protein")) 
(define-protein "TOPK" ("HGNC:18282" "PDZ binding kinase")) 
(define-protein "TOPORS" ("HGNC:21653" "TOP1 binding arginine/serine rich protein")) 
(define-protein "TOR" ("GO:0050626" "trimethylamine-N-oxide reductase (cytochrome c) activity")) 
(define-protein "TPK" ("UP:P35202" "Thiamine pyrophosphokinase")) 
(define-protein "TPL" ("UP:Q9CQX3" "BPI fold-containing family A member 5")) 
(define-protein "TPO" ("HGNC:12015" "thyroid peroxidase")) 
(define-protein "TPP" ("UP:P10463" "Calcyphosin")) 
(define-protein "TPPP" ("HGNC:24164" "tubulin polymerization promoting protein")) 
(define-protein "TPalpha" ("UP:P40939" "Trifunctional enzyme subunit alpha, mitochondrial")) 
(define-protein "TPbeta" ("UP:P55084" "Trifunctional enzyme subunit beta, mitochondrial")) 
(define-protein "TRAM" ("FA:04146" "TRAM family")) 
(define-protein "TRANCE" ("NCIT:C50965" "TNFSF11")) 
(define-protein "TRE" ("HGNC:12266" "trehalase")) 
(define-protein "TREs" ("HGNC:12266" "trehalase")) 
(define-protein "TRH" ("HGNC:12298" "thyrotropin releasing hormone")) 
(define-protein "TRIP" ("NCIT:C125107" "TRAIP")) 
(define-protein "TRO" ("HGNC:12326" "trophinin")) 
(define-protein "TRbeta" ("UP:Q9PVE4" "Thyroid hormone receptor beta")) 
(define-protein "TS" ("UP:P90463" "Thymidylate synthase")) 
(define-protein "TSG" ("XFAM:PF04668.10" "tsg")) 
(define-protein "TSH" ("NCIT:C2280" "thyroid stimulating hormone")) 
(define-protein "TSLPR" ("NCIT:C97431" "CRLF2")) 
(define-protein "TSP" ("UP:Q858F5" "Tail spike protein {ECO:0000305}")) 
(define-protein "TSPY" ("NCIT:C52092" "TSPY")) 
(define-protein "TSPs" ("UP:Q858F5" "Tail spike protein {ECO:0000305}")) 
(define-protein "TUCAN" ("NCIT:C84305" "CARD8")) 
(define-protein "TWEAKR" ("NCIT:C117072" "TNFRSF12A")) 
(define-protein "TYP" ("NCIT:C112128" "DUSP4")) 
(define-protein "TonEBP" ("NCIT:C93134" "nuclear factor of activated T-cells 5")) 
(define-protein "TopoI" ("UP:O17966" "DNA topoisomerase 1")) 
(define-protein "TpN" ("UP:O15533" "Tapasin")) 
(define-protein "TrkAIII" ("NCIT:C105368" "high affinity nerve growth factor receptor isoform trkA-III")) 
(define-protein "TyrP" ("NCIT:C18271" "tyrosinase-related protein-1")) 
(define-protein "UBF" ("HGNC:12511" "upstream binding transcription factor, RNA polymerase I")) 
(define-protein "UBIN" ("NCIT:C118580" "UBQLN4")) 
(define-protein "UCH" ("UP:P35127" "Ubiquitin carboxyl-terminal hydrolase YUH1")) 
(define-protein "UGD" ("HGNC:17729" "UDP-glucuronate decarboxylase 1")) 
(define-protein "UK" ("UP:O31749" "Uridylate kinase")) 
(define-protein "UNRIP" ("HGNC:30796" "serine/threonine kinase receptor associated protein")) 
(define-protein "UPD" ("UP:P06132" "Uroporphyrinogen decarboxylase")) 
(define-protein "UPP" ("HGNC:12576" "uridine phosphorylase 1")) 
(define-protein "USF" ("UP:Q07957" "Upstream stimulatory factor 1")) 
(define-protein "USFs" ("UP:Q07957" "Upstream stimulatory factor 1")) 
(define-protein "USP" ("UP:Q50777" "Universal stress protein MTBMA_c15380")) 
(define-protein "VDRA" ("UP:Q9PTN2" "Vitamin D3 receptor A")) 
(define-protein "VEGFRs" ("GO:0005021" "vascular endothelial growth factor-activated receptor activity")) 
(define-protein "VF" ("UP:J3S836" "Venom factor")) 
(define-protein "VGF" ("HGNC:12684" "VGF nerve growth factor inducible")) 
(define-protein "VGs" ("UP:Q16927" "Vitellogenin-A1")) 
(define-protein "VIM" ("HGNC:12692" "vimentin")) 
(define-protein "VP" ("NCIT:C52392" "AVP")) 
(define-protein "VPA" ("UP:Q58L90" "Venom prothrombin activator omicarin-C non-catalytic subunit")) 
(define-protein "WAP" ("UP:P09837" "Whey acidic protein")) 
(define-protein "WR" ("NCIT:C105065" "SLC4A1")) 
(define-protein "WRN" ("HGNC:12791" "Werner syndrome RecQ like helicase")) 
(define-protein "XLA" ("NCIT:C75014" "BTK")) 
(define-protein "XMT" ("UP:A4GE69" "7-methylxanthosine synthase 1")) 
(define-protein "XPV" ("NCIT:C91286" "POLH")) 
(define-protein "XR" ("UP:Q7Z4W1" "L-xylulose reductase")) 
(define-protein "YFP" ("UP:P21578" "Yellow fluorescent protein")) 
(define-protein "YL" ("UP:P98163" "Putative vitellogenin receptor")) 
(define-protein "ZASP" ("HGNC:15710" "LIM domain binding 3")) 
(define-protein "ZEBRA" ("NCIT:C118473" "trans-activator protein BZLF1")) 
(define-protein "ZF" ("HGNC:24905" "CREB/ATF bZIP transcription factor")) 
(define-protein "ZFX" ("HGNC:12869" "zinc finger protein, X-linked")) 
(define-protein "ZID" ("HGNC:16764" "zinc finger and BTB domain containing 6")) 
(define-protein "ZIP" ("XFAM:PF02535.20" "zip")) 
(define-protein "aPPD" ("HGNC:20764" "pleckstrin homology and FYVE domain containing 1")) 
(define-protein "alphaMSH" ("NCIT:C114797" "melanotropin alpha")) 
(define-protein "alphaNAC" ("NCIT:C97655" "nascent polypeptide-associated complex subunit alpha")) 
(define-protein "alphaPIX" ("HGNC:685" "Rac/Cdc42 guanine nucleotide exchange factor 6")) 
(define-protein "apoB" ("HGNC:603" "apolipoprotein B")) 
(define-protein "bPR" ("UP:Q9AFF7" "Blue-light absorbing proteorhodopsin")) 
(define-protein "betaPix" ("NCIT:C97202" "rho guanine nucleotide exchange factor 7")) 
(define-protein "betaTrCP" ("UP:Q91854" "Beta-TrCP")) 
(define-protein "c-Src-" ("HGNC:11283" "SRC proto-oncogene, non-receptor tyrosine kinase")) 
(define-protein "cAbl" ("NCIT:C51061" "ABL1")) 
(define-protein "cCbl" ("NCIT:C52501" "CBL")) 
(define-protein "cGAS" ("UP:E1BGN7" "Cyclic GMP-AMP synthase")) 
(define-protein "cGK" ("UP:Q03042" "cGMP-dependent protein kinase, isozyme 1")) 
(define-protein "cKO" ("UP:P58763" "Cytokinin dehydrogenase")) 
(define-protein "cRBP" ("HGNC:9919" "retinol binding protein 1")) 
(define-protein "cSrc" ("HGNC:11283" "SRC proto-oncogene, non-receptor tyrosine kinase")) 
(define-protein "cTnI" ("NCIT:C104224" "TNNI3")) 
(define-protein "cyclinD" ("UP:Q5SCB5" "Cyclin-D")) 
(define-protein "dMax" ("UP:P91664" "Protein max")) 
(define-protein "delE" ("HGNC:28969" "KIAA0141")) 
(define-protein "drICE" ("UP:O01382" "Caspase")) 
(define-protein "dynAP" ("HGNC:26808" "dynactin associated protein")) 
(define-protein "ferT" ("NCIT:C51074" "FER")) 
(define-protein "fosB" ("HGNC:3797" "FosB proto-oncogene, AP-1 transcription factor subunit")) 
(define-protein "gAPN" ("UP:Q3C1A6" "NADP-dependent glyceraldehyde-3-phosphate dehydrogenase")) 
(define-protein "hAPP" ("UP:P14163" "Plasmodium-specific hydrophobic abundant protein")) 
(define-protein "hBRAG" ("NCIT:C118524" "carbohydrate sulfotransferase 15")) 
(define-protein "hCAD" ("NCIT:C113325" "CALD1")) 
(define-protein "hCGbeta" ("NCIT:C17479" "human chorionic gonadotropin beta subunit")) 
(define-protein "hCaR" ("UP:P78310" "Coxsackievirus and adenovirus receptor")) 
(define-protein "hCds" ("UP:P02241" "Hemocyanin D chain")) 
(define-protein "hECs" ("HGNC:16909" "NDC80, kinetochore complex component")) 
(define-protein "hEPC" ("NCIT:C104272" "HAMP")) 
(define-protein "hEPCs" ("NCIT:C104272" "HAMP")) 
(define-protein "hLBH" ("UP:Q53QV2" "Protein LBH")) 
(define-protein "hMYH" ("NCIT:C61057" "MUTYH")) 
(define-protein "hPDL" ("HGNC:28242" "4-hydroxyphenylpyruvate dioxygenase like")) 
(define-protein "hPR" ("HGNC:5156" "haptoglobin-related protein")) 
(define-protein "hPRL" ("NCIT:C51719" "PRLR")) 
(define-protein "hPS" ("UP:Q7S565" "Probable hexaprenyl pyrophosphate synthase, mitochondrial")) 
(define-protein "hepaCAM" ("HGNC:26361" "hepatic and glial cell adhesion molecule")) 
(define-protein "iBRAF" ("UP:Q9DC33" "High mobility group protein 20A")) 
(define-protein "junB" ("HGNC:6205" "JunB proto-oncogene, AP-1 transcription factor subunit")) 
(define-protein "junD" ("HGNC:6206" "JunD proto-oncogene, AP-1 transcription factor subunit")) 
(define-protein "mArf" ("NCIT:C113228" "MFN2")) 
(define-protein "mEF" ("NCIT:C97473" "ELF4")) 
(define-protein "mIL" ("NCIT:C51274" "RAF1")) 
(define-protein "mPIN" ("UP:P63168" "Dynein light chain 1, cytoplasmic")) 
(define-protein "mPTP" ("UP:Q06180" "Tyrosine-protein phosphatase non-receptor type 2")) 
(define-protein "mTR" ("HGNC:7468" "5-methyltetrahydrofolate-homocysteine methyltransferase")) 
(define-protein "mUb" ("UP:Q2TA46" "Ubiquitin-like protein 3")) 
(define-protein "miR" ("UP:Q93105" "Insulin-like receptor")) 
(define-protein "miRs" ("UP:Q93105" "Insulin-like receptor")) 
(define-protein "mmP" ("NCIT:C18164" "matrix metalloproteinase")) 
(define-protein "mtTFA" ("UP:Q00059" "Transcription factor A, mitochondrial")) 
(define-protein "p21 Protein" ("UP:P12356" "Photosystem I reaction center subunit III, chloroplastic")) 
(define-protein "p38 MAP kinases" ("NCIT:C26369" "MAP-kinase-14")) 
(define-protein "p38 MAPKs" ("NCIT:C20585" "MAP-kinase kinase kinase 8")) 
(define-protein "pAPC" ("UP:P10297" "Antiviral protein I")) 
(define-protein "pAb" ("UP:P9WGU0" "Phosphate-binding protein PstS 1")) 
(define-protein "pBK" ("HGNC:18282" "PDZ binding kinase")) 
(define-protein "pDR" ("UP:P33164" "Phthalate dioxygenase reductase")) 
(define-protein "pGL" ("UP:P52697" "6-phosphogluconolactonase")) 
(define-protein "pHi" ("NCIT:C17428" "glucose phosphate isomerase")) 
(define-protein "pIGF" ("UP:Q07326" "Phosphatidylinositol-glycan biosynthesis class F protein")) 
(define-protein "pMS" ("HGNC:9337" "proline rich protein BstNI subfamily 1")) 
(define-protein "pSV" ("UP:P08798" "Prespore vesicle protein")) 
(define-protein "pX" ("UP:P14269" "Pre-core protein X")) 
(define-protein "pY" ("UP:P0AD51" "Ribosome-associated factor Y {ECO:0000305}")) 
(define-protein "rDNA" ("NCIT:C95943" "ribosomal RNA gene")) 
(define-protein "rIL" ("NCIT:C54424" "RIL")) 
(define-protein "rIgG" ("HGNC:5411" "interferon induced protein with tetratricopeptide repeats 3")) 
(define-protein "rPTPsigma" ("NCIT:C124925" "receptor-type tyrosine-protein phosphatase S")) 
(define-protein "rPtn" ("HGNC:26809" "repetin")) 
(define-protein "sGC" ("NCIT:C20141" "soluble guanylate cyclase")) 
(define-protein "sLZIP" ("HGNC:2347" "cAMP responsive element binding protein 3")) 
(define-protein "sUV" ("UP:Q9LLC6" "Cytochrome b6-f complex subunit petO, chloroplastic")) 
(define-protein "uNK" ("HGNC:29369" "unkempt family zinc finger")) 
(define-protein "vFLIP" ("UP:F5HEZ4" "Viral FLICE protein")) 
(define-protein "vGPCR" ("UP:Q98146" "viral G-protein coupled receptor")) 
(define-protein "vSrc" ("NCIT:C19106" "V-SRC")) 
(define-protein "xLS" ("HGNC:27849" "chromosome 9 open reading frame 142")) 