
(define-protein "Abl" ("UP:Q00022" "Agaricus bisporus lectin")) 
(define-protein "Abraxas" ("FA:01249" "abraxas subfamily")) 
(define-protein "Abs" ("NCIT:C16295" "antibody")) 
(define-protein "Acacb" ("HGNC:85" "acetyl-CoA carboxylase beta")) 
(define-protein "Acta" ("XFAM:PF05058.10" "ActA")) 
(define-protein "Adr" ("UP:Q09851" "NADPH-dependent 1-acyldihydroxyacetone phosphate reductase")) 
(define-protein "Ahnak" ("HGNC:347" "AHNAK nucleoprotein")) 
(define-protein "Aicar" ("NCIT:C97401" "ATIC")) 
(define-protein "Aii" ("NCIT:C77203" "NLRP3")) 
(define-protein "Aire" ("HGNC:360" "autoimmune regulator")) 
(define-protein "Akti" ("UP:P85498" "Kunitz-type trypsin inhibitor alpha chain")) 
(define-protein "Aldo" ("UP:Q86A67" "Fructose-bisphosphate aldolase")) 
(define-protein "Alix" ("UP:Q8T7K0" "ALG-2 interacting protein X")) 
(define-protein "Als" ("UP:P35858" "Insulin-like growth factor-binding protein complex acid labile subunit")) 
(define-protein "Amot" ("HGNC:17810" "angiomotin")) 
(define-protein "Amph" ("HGNC:471" "amphiphysin")) 
(define-protein "Ana" ("NCIT:C70547" "antinuclear antibody")) 
(define-protein "Angiotensin" ("UP:Q10757" "Angiotensin")) 
(define-protein "Anillin" ("UP:Q9V4P1" "Anillin")) 
(define-protein "Ank" ("UP:Q9HCJ1" "Progressive ankylosis protein homolog")) 
(define-protein "Apc" ("HGNC:583" "APC, WNT signaling pathway regulator")) 
(define-protein "Aph" ("XFAM:PF01636.21" "APH")) 
(define-protein "Apollon" ("NCIT:C28697" "baculoviral IAP repeat-containing protein-6")) 
(define-protein "Aprataxin" ("HGNC:15984" "aprataxin")) 
(define-protein "Araf" ("HGNC:646" "A-Raf proto-oncogene, serine/threonine kinase")) 
(define-protein "Arf" ("FA:03659" "arf family")) 
(define-protein "Arix" ("HGNC:691" "paired like homeobox 2a")) 
(define-protein "Armus" ("UP:Q9BYX2" "TBC1 domain family member 2A")) 
(define-protein "Asb" ("UP:P33727" "Arylsulfatase B")) 
(define-protein "Astrin" ("UP:Q96R06" "Sperm-associated antigen 5")) 
(define-protein "Asy" ("NCIT:C52103" "RTN4")) 
(define-protein "Atk" ("NCIT:C75014" "BTK")) 
(define-protein "Atm" ("HGNC:795" "ATM serine/threonine kinase")) 
(define-protein "Atr" ("HGNC:882" "ATR serine/threonine kinase")) 
(define-protein "Atrip" ("HGNC:33499" "ATR interacting protein")) 
(define-protein "Aurka" ("HGNC:11393" "aurora kinase A")) 
(define-protein "Autotaxin" ("NCIT:C104211" "ectonucleotide pyrophosphatase-phosphodiesterase family member 2")) 
(define-protein "Axam" ("UP:Q9EQE1" "Sentrin-specific protease 2")) 
(define-protein "Baf" ("FA:00326" "BAF family")) 
(define-protein "Bambi" ("HGNC:30251" "BMP and activin membrane bound inhibitor")) 
(define-protein "Bcr" ("HGNC:1014" "BCR, RhoGEF and GTPase activating protein")) 
(define-protein "Bhd" ("NCIT:C63517" "FLCN")) 
(define-protein "Bik" ("HGNC:1051" "BCL2 interacting killer")) 
(define-protein "Bis" ("NCIT:C105995" "BAG3")) 
(define-protein "Bmf" ("HGNC:24132" "Bcl2 modifying factor")) 
(define-protein "Bmp" ("XFAM:PF02608.12" "bmp")) 
(define-protein "Bmx" ("HGNC:1079" "BMX non-receptor tyrosine kinase")) 
(define-protein "Bok" ("HGNC:1087" "BOK, BCL2 family apoptosis regulator")) 
(define-protein "Bptf" ("HGNC:3581" "bromodomain PHD finger transcription factor")) 
(define-protein "Brahma" ("NCIT:C19865" "BRAHMA")) 
(define-protein "Brm" ("NCIT:C19865" "BRAHMA")) 
(define-protein "Brn-3a" ("UP:P55968" "POU domain, class 4, transcription factor 1")) 
(define-protein "Bruce" ("HGNC:13516" "baculoviral IAP repeat containing 6")) 
(define-protein "Bsep" ("NCIT:C123860" "ABCB11")) 
(define-protein "Calreticulin" ("HGNC:1455" "calreticulin")) 
(define-protein "Casp" ("UP:P15156" "Calcium-dependent serine proteinase")) 
(define-protein "Cathepsins" ("NCIT:C16389" "cathepsin")) 
(define-protein "Cav" ("NCIT:C52498" "CAV2")) 
(define-protein "Cbfa" ("NCIT:C93121" "nuclease-sensitive element binding protein 1")) 
(define-protein "Cbl" ("HGNC:1541" "Cbl proto-oncogene")) 
(define-protein "Cbp" ("UP:O42720" "Calcium-binding protein")) 
(define-protein "Cbx" ("HGNC:1551" "chromobox 1")) 
(define-protein "Cdh" ("UP:Q8NE62" "Choline dehydrogenase, mitochondrial")) 
(define-protein "Cdks" ("NCIT:C17767" "cyclin-dependent kinase")) 
(define-protein "Cdon" ("HGNC:17104" "cell adhesion associated, oncogene regulated")) 
(define-protein "Cdx" ("UP:Q8VQF4" "Cindoxin")) 
(define-protein "Cenpb" ("HGNC:1852" "centromere protein B")) 
(define-protein "Cenpc" ("HGNC:1854" "centromere protein C")) 
(define-protein "Cer" ("UP:P70041" "Cerberus")) 
(define-protein "Cezanne" ("HGNC:16683" "OTU deubiquitinase 7B")) 
(define-protein "Chaperone" ("NCIT:C17764" "chaperone")) 
(define-protein "Chfr" ("HGNC:20455" "checkpoint with forkhead and ring finger domains")) 
(define-protein "Chk" ("NCIT:C51051" "CHK")) 
(define-protein "Chrebp" ("UP:Q9NP71" "Carbohydrate-responsive element-binding protein")) 
(define-protein "Chronophin" ("UP:Q3ZBF9" "Pyridoxal phosphate phosphatase")) 
(define-protein "Cip" ("HGNC:21355" "muscular LMNA interacting protein")) 
(define-protein "Cis" ("UP:Q2HJ53" "Cytokine-inducible SH2-containing protein")) 
(define-protein "Cki" ("NCIT:C51051" "CHK")) 
(define-protein "Cks" ("UP:P35790" "Choline kinase alpha")) 
(define-protein "Cld" ("NCIT:C29977" "chloride anion exchanger")) 
(define-protein "Clu" ("HGNC:2095" "clusterin")) 
(define-protein "Cobb" ("GO:0042242" "cobyrinic acid a,c-diamide synthase activity")) 
(define-protein "Cpd" ("HGNC:2301" "carboxypeptidase D")) 
(define-protein "Crebh" ("NCIT:C95486" "CREB3L3")) 
(define-protein "Cripto" ("HGNC:11701" "teratocarcinoma-derived growth factor 1")) 
(define-protein "Crk" ("HGNC:2362" "CRK proto-oncogene, adaptor protein")) 
(define-protein "Crkl" ("HGNC:2363" "CRK like proto-oncogene, adaptor protein")) 
(define-protein "Csp" ("UP:O33672" "Competence-stimulating peptide")) 
(define-protein "Ctrl" ("HGNC:2524" "chymotrypsin like")) 
(define-protein "Ctx" ("UP:Q02454" "Cytotoxin")) 
(define-protein "Cux" ("NCIT:C95579" "CUX1")) 
(define-protein "Cyld" ("HGNC:2584" "CYLD lysine 63 deubiquitinase")) 
(define-protein "Cyp" ("NCIT:C16484" "cytochrome-P450")) 
(define-protein "Dai" ("HGNC:16176" "Z-DNA binding protein 1")) 
(define-protein "Dcc" ("HGNC:2701" "DCC netrin 1 receptor")) 
(define-protein "Dcn" ("HGNC:2705" "decorin")) 
(define-protein "Dec" ("UP:Q8HAE6" "Decoration protein")) 
(define-protein "Dei" ("UP:P00599" "Basic phospholipase A2 1")) 
(define-protein "Dhfr" ("HGNC:2861" "dihydrofolate reductase")) 
(define-protein "Dll" ("UP:P53773" "Homeobox protein DLL-1")) 
(define-protein "Dnmt" ("NCIT:C16508" "DNA modification methylase")) 
(define-protein "Doppel" ("XFAM:PF11466.6" "doppel")) 
(define-protein "Drice" ("UP:O01382" "Caspase")) 
(define-protein "Drosha" ("HGNC:17904" "drosha ribonuclease III")) 
(define-protein "Dvl" ("XFAM:PF08137.10" "DVL")) 
(define-protein "Dysadherin" ("UP:Q96DB9" "FXYD domain-containing ion transport regulator 5")) 
(define-protein "Ebi" ("UP:P81705" "Bowman-Birk type proteinase inhibitor")) 
(define-protein "Ecad" ("NCIT:C51151" "CDH1")) 
(define-protein "Ecd" ("HGNC:17029" "ecdysoneless cell cycle regulator")) 
(define-protein "Eck" ("NCIT:C51755" "EPHA2")) 
(define-protein "Eed" ("HGNC:3188" "embryonic ectoderm development")) 
(define-protein "Egfr" ("UP:P0CY46" "Epidermal growth factor receptor")) 
(define-protein "Endostatin" ("NCIT:C18046" "endostatin")) 
(define-protein "Eng" ("HGNC:3349" "endoglin")) 
(define-protein "Engl" ("HGNC:3347" "exo/endonuclease G")) 
(define-protein "Enh" ("HGNC:17468" "PDZ and LIM domain 5")) 
(define-protein "Eomes" ("HGNC:3372" "eomesodermin")) 
(define-protein "Eos" ("HGNC:30405" "protease, serine 33")) 
(define-protein "Eph" ("NCIT:C18606" "ephrin receptor")) 
(define-protein "Epo" ("HGNC:3415" "erythropoietin")) 
(define-protein "Eppin" ("UP:O95925" "Eppin")) 
(define-protein "Erf" ("HGNC:3444" "ETS2 repressor factor")) 
(define-protein "Erk 1" ("UP:Q5A1D3" "Extracellular signal-regulated kinase 1")) 
(define-protein "Erk1" ("UP:Q5A1D3" "Extracellular signal-regulated kinase 1")) 
(define-protein "Etk" ("NCIT:C21372" "BMX non-receptor tyrosine kinase")) 
(define-protein "Ets" ("FA:01142" "ETS family")) 
(define-protein "Evi" ("HGNC:30238" "wntless Wnt ligand secretion mediator")) 
(define-protein "Exp" ("HGNC:6923" "muscleblind like splicing regulator 1")) 
(define-protein "Fadd" ("HGNC:3573" "Fas associated via death domain")) 
(define-protein "Fam" ("NCIT:C101575" "USP9X")) 
(define-protein "Fbs" ("UP:P22027" "ATP synthase subunit s, mitochondrial")) 
(define-protein "Fes" ("HGNC:4650" "general transcription factor IIE subunit 1")) 
(define-protein "Fhit" ("HGNC:3701" "fragile histidine triad")) 
(define-protein "Flcn" ("HGNC:27310" "folliculin")) 
(define-protein "Folliculin" ("HGNC:27310" "folliculin")) 
(define-protein "Fortilin" ("NCIT:C101391" "translationally-controlled tumor protein")) 
(define-protein "Fos" ("FA:00408" "fos subfamily")) 
(define-protein "Fps" ("NCIT:C103875" "succinate dehydrogenase ubiquinone flavoprotein subunit mitochondrial")) 
(define-protein "Frodo" ("UP:Q8JJ48" "Dapper 1-A")) 
(define-protein "Frs2alpha" ("NCIT:C52381" "FRS2")) 
(define-protein "Frzb" ("HGNC:3959" "frizzled-related protein")) 
(define-protein "Fshb" ("NCIT:C104398" "FSHB")) 
(define-protein "G-3" ("HGNC:13919" "BCL2 associated athanogene 6")) 
(define-protein "Gadd45beta" ("NCIT:C105845" "GADD45B")) 
(define-protein "Gadkin" ("UP:Q63HQ0" "AP-1 complex-associated regulatory protein")) 
(define-protein "Galphaq" ("NCIT:C19276" "G-q alpha")) 
(define-protein "Gan" ("HGNC:4137" "gigaxonin")) 
(define-protein "Gao" ("UP:P0CS93" "Galactose oxidase")) 
(define-protein "Gata" ("FA:04921" "gatA subfamily")) 
(define-protein "Gdnf" ("HGNC:4232" "glial cell derived neurotrophic factor")) 
(define-protein "Gef" ("GO:0005085" "guanyl-nucleotide exchange factor activity")) 
(define-protein "Gklf" ("NCIT:C73450" "KLF4")) 
(define-protein "Gli" ("UP:P55878" "Zinc finger protein GLI1")) 
(define-protein "Globin" ("UP:P14393" "Globin")) 
(define-protein "Glp" ("UP:P63294" "Glucagon-like peptide")) 
(define-protein "Gls" ("UP:Q29458" "Gastric triacylglycerol lipase")) 
(define-protein "Golg" ("HGNC:4427" "golgin A4")) 
(define-protein "Grap" ("HGNC:4562" "GRB2-related adaptor protein")) 
(define-protein "Gravin" ("NCIT:C21326" "A kinase anchor protein-12")) 
(define-protein "Grb" ("NCIT:C104354" "GZMB wtAllele")) 
(define-protein "Gro" ("NCIT:C20471" "C-X-C motif chemokine ligand-1")) 
(define-protein "Grp" ("HGNC:4605" "gastrin releasing peptide")) 
(define-protein "Gst" ("FA:01669" "GST superfamily")) 
(define-protein "Hara" ("NCIT:C107430" "human anti-ricin antibody")) 
(define-protein "Has" ("UP:P12946" "Heme A synthase")) 
(define-protein "Haspin" ("FA:03103" "haspin subfamily")) 
(define-protein "Hausp" ("NCIT:C118238" "USP7")) 
(define-protein "Hdh" ("UP:Q9C5U8" "Histidinol dehydrogenase, chloroplastic")) 
(define-protein "Hepc" ("NCIT:C104272" "HAMP")) 
(define-protein "Hes" ("UP:P91953" "50 kDa hatching enzyme")) 
(define-protein "Hex" ("NCIT:C114958" "HHEX")) 
(define-protein "Hgs" ("HGNC:4897" "hepatocyte growth factor-regulated tyrosine kinase substrate")) 
(define-protein "Hif-1alpha" ("UP:Q16665" "Hypoxia-inducible factor 1-alpha")) 
(define-protein "Hili" ("HGNC:17644" "piwi like RNA-mediated gene silencing 2")) 
(define-protein "Hpo" ("UP:A6YIH8" "Premnaspirodiene oxygenase")) 
(define-protein "Hpse" ("HGNC:5164" "heparanase")) 
(define-protein "Hras" ("NCIT:C52545" "HRAS")) 
(define-protein "Hrg" ("HGNC:5181" "histidine rich glycoprotein")) 
(define-protein "Hrk" ("HGNC:5185" "harakiri, BCL2 interacting protein")) 
(define-protein "Hrs" ("HGNC:5172" "HR, lysine demethylase and nuclear receptor corepressor")) 
(define-protein "Htt" ("HGNC:4851" "huntingtin")) 
(define-protein "Hzf" ("HGNC:17521" "zinc finger protein 385A")) 
(define-protein "Icmt" ("HGNC:5350" "isoprenylcysteine carboxyl methyltransferase")) 
(define-protein "Iduna" ("NCIT:C99466" "RNF146")) 
(define-protein "Ifnb" ("HGNC:5434" "interferon beta 1")) 
(define-protein "Ifng" ("HGNC:5438" "interferon gamma")) 
(define-protein "Igalpha" ("NCIT:C97423" "B-cell antigen receptor complex-associated protein alpha chain")) 
(define-protein "Igbeta" ("NCIT:C97426" "B-cell antigen receptor complex-associated protein beta chain")) 
(define-protein "Ikaros" ("NCIT:C68731" "IKZF1")) 
(define-protein "Ikka" ("UP:O15111" "Inhibitor of nuclear factor kappa-B kinase subunit alpha")) 
(define-protein "Ikkbeta" ("UP:Q95KV0" "Inhibitor of nuclear factor kappa-B kinase subunit beta")) 
(define-protein "Ink4a" ("NCIT:C49511" "CDKN2A")) 
(define-protein "Ins" ("NCIT:C51123" "CD44")) 
(define-protein "Insulin like growth factor-1" ("NCIT:C16743" "insulin-like growth factor-1")) 
(define-protein "Ire1alpha" ("NCIT:C113614" "serine threonine-protein kinase endoribonuclease IRE1")) 
(define-protein "Irs" ("UP:P06213" "Insulin receptor")) 
(define-protein "Iscu" ("HGNC:29882" "iron-sulfur cluster assembly enzyme")) 
(define-protein "Itis" ("UP:P62756" "Inter-alpha-trypsin inhibitor")) 
(define-protein "Itk" ("HGNC:6171" "IL2 inducible T-cell kinase")) 
(define-protein "Jak" ("FA:03129" "JAK subfamily")) 
(define-protein "Jakl" ("NCIT:C51087" "JAK3")) 
(define-protein "Jaks" ("FA:03129" "JAK subfamily")) 
(define-protein "Kank" ("HGNC:19309" "KN motif and ankyrin repeat domains 1")) 
(define-protein "Kendrin" ("UP:O95613" "Pericentrin")) 
(define-protein "Kinases" ("GO:0016301" "kinase activity")) 
(define-protein "Kras" ("HGNC:6407" "KRAS proto-oncogene, GTPase")) 
(define-protein "Ksr" ("NCIT:C51209" "KSR")) 
(define-protein "Lats" ("HGNC:18874" "linker for activation of T-cells")) 
(define-protein "Lbh" ("HGNC:29532" "limb bud and heart development")) 
(define-protein "Lep" ("HGNC:6553" "leptin")) 
(define-protein "Lepr" ("NCIT:C51373" "LEPR")) 
(define-protein "Lfng" ("HGNC:6560" "LFNG O-fucosylpeptide 3-beta-N-acetylglucosaminyltransferase")) 
(define-protein "Livin" ("NCIT:C20951" "livin")) 
(define-protein "Lmna" ("HGNC:6636" "lamin A/C")) 
(define-protein "Lox" ("HGNC:6664" "lysyl oxidase")) 
(define-protein "Lpd" ("UP:Q8NTE1" "Dihydrolipoyl dehydrogenase")) 
(define-protein "Lum" ("HGNC:6724" "lumican")) 
(define-protein "Maf" ("FA:00410" "maf subfamily")) 
(define-protein "Mal" ("HGNC:6817" "mal, T-cell differentiation protein")) 
(define-protein "Mastl" ("HGNC:19042" "microtubule associated serine/threonine kinase like")) 
(define-protein "Mcm" ("UP:P22033" "Methylmalonyl-CoA mutase, mitochondrial")) 
(define-protein "Mdm" ("HGNC:18746" "secreted LY6/PLAUR domain containing 1")) 
(define-protein "Med" ("HGNC:2218" "collagen type IX alpha 2 chain")) 
(define-protein "Mel" ("NCIT:C52547" "MEL")) 
(define-protein "Mesd" ("FA:02236" "MESD family")) 
(define-protein "Mets" ("HGNC:7029" "MET proto-oncogene, receptor tyrosine kinase")) 
(define-protein "Mia" ("HGNC:7076" "melanoma inhibitory activity")) 
(define-protein "Mif" ("HGNC:7097" "macrophage migration inhibitory factor (glycosylation-inhibiting factor)")) 
(define-protein "Mil" ("NCIT:C51274" "RAF1")) 
(define-protein "Mio" ("NCIT:C102475" "MLXIPL")) 
(define-protein "Mira" ("UP:Q6TEM9" "E3 ubiquitin-protein ligase MYLIP-A")) 
(define-protein "Mirk" ("HGNC:3092" "dual specificity tyrosine phosphorylation regulated kinase 1B")) 
(define-protein "Mitf" ("HGNC:7105" "melanogenesis associated transcription factor")) 
(define-protein "Mitosin" ("NCIT:C17928" "centromere protein-F")) 
(define-protein "Miz" ("NCIT:C119667" "ZMIZ1")) 
(define-protein "Mlx" ("HGNC:11645" "MLX, MAX dimerization protein")) 
(define-protein "Mme" ("HGNC:7154" "membrane metalloendopeptidase")) 
(define-protein "Mnt" ("HGNC:7188" "MAX network transcriptional repressor")) 
(define-protein "Mpl" ("HGNC:7217" "MPL proto-oncogene, thrombopoietin receptor")) 
(define-protein "Mtbp" ("HGNC:7417" "MDM2 binding protein")) 
(define-protein "Mucdhl" ("HGNC:7521" "cadherin related family member 5")) 
(define-protein "Mut" ("HGNC:7526" "methylmalonyl-CoA mutase")) 
(define-protein "Myb" ("HGNC:7545" "MYB proto-oncogene, transcription factor")) 
(define-protein "Nat" ("UP:P0A5L9" "Arylamine N-acetyltransferase")) 
(define-protein "Nbk" ("NCIT:C49374" "BIK")) 
(define-protein "Ncad" ("NCIT:C77158" "CDH2")) 
(define-protein "Nck" ("HGNC:7664" "NCK adaptor protein 1")) 
(define-protein "Necdin" ("UP:Q99608" "Necdin")) 
(define-protein "Ngfr" ("HGNC:7809" "nerve growth factor receptor")) 
(define-protein "Niban" ("FA:02467" "niban family")) 
(define-protein "Nile" ("UP:Q05695" "Neural cell adhesion molecule L1")) 
(define-protein "Nin" ("HGNC:14906" "ninein")) 
(define-protein "Noc" ("UP:P37524" "Nucleoid occlusion protein")) 
(define-protein "Nrarp" ("HGNC:33843" "NOTCH-regulated ankyrin repeat protein")) 
(define-protein "Nras" ("NCIT:C52549" "NRAS")) 
(define-protein "Nuc" ("HGNC:8043" "nucleobindin 1")) 
(define-protein "Nucleophosmin" ("HGNC:7910" "nucleophosmin")) 
(define-protein "Nudel" ("HGNC:17620" "nudE neurodevelopment protein 1 like 1")) 
(define-protein "Numbl" ("HGNC:8061" "NUMB like, endocytic adaptor protein")) 
(define-protein "Optn" ("HGNC:17142" "optineurin")) 
(define-protein "Orf" ("NCIT:C106210" "ATP6AP1")) 
(define-protein "Osm" ("HGNC:8506" "oncostatin M")) 
(define-protein "Osx" ("NCIT:C75731" "MID1")) 
(define-protein "Palladin" ("UP:Q8WX93" "Palladin")) 
(define-protein "Pam" ("HGNC:8596" "peptidylglycine alpha-amidating monooxygenase")) 
(define-protein "Pancortin" ("UP:Q9IAK4" "Noelin")) 
(define-protein "Par3beta" ("HGNC:14446" "par-3 family cell polarity regulator beta")) 
(define-protein "Parc" ("NCIT:C49723" "CCL18")) 
(define-protein "Paris" ("HGNC:21948" "zinc finger protein 746")) 
(define-protein "Parp" ("UP:P35875" "Poly [ADP-ribose] polymerase")) 
(define-protein "Pcna" ("HGNC:8729" "proliferating cell nuclear antigen")) 
(define-protein "Pdgfb" ("HGNC:8800" "platelet derived growth factor subunit B")) 
(define-protein "Pem" ("NCIT:C38967" "mucin-1")) 
(define-protein "Pez" ("NCIT:C125448" "PTPN14")) 
(define-protein "Phi" ("NCIT:C17428" "glucose phosphate isomerase")) 
(define-protein "Pidd" ("HGNC:16491" "p53-induced death domain protein 1")) 
(define-protein "Pim" ("FA:03078" "PIM subfamily")) 
(define-protein "Piwi" ("FA:00252" "piwi subfamily")) 
(define-protein "Pix" ("UP:P68970" "Hexon-associated protein")) 
(define-protein "Plk" ("NCIT:C51263" "PLK")) 
(define-protein "Pnck" ("HGNC:13415" "pregnancy up-regulated nonubiquitous CaM kinase")) 
(define-protein "Pneumolysin" ("UP:Q04IN8" "Pneumolysin")) 
(define-protein "Pnn" ("HGNC:9162" "pinin, desmosome associated protein")) 
(define-protein "Polk" ("HGNC:9183" "DNA polymerase kappa")) 
(define-protein "Pon" ("NCIT:C116048" "PON1")) 
(define-protein "Pontin" ("UP:Q0IFL2" "RuvB-like helicase 1")) 
(define-protein "Postn" ("HGNC:16953" "periostin")) 
(define-protein "Prkcd" ("HGNC:9399" "protein kinase C delta")) 
(define-protein "Prkcq" ("HGNC:9410" "protein kinase C theta")) 
(define-protein "Prl" ("HGNC:9445" "prolactin")) 
(define-protein "Prnp" ("HGNC:9449" "prion protein")) 
(define-protein "Proc" ("HGNC:9451" "protein C, inactivator of coagulation factors Va and VIIIa")) 
(define-protein "Prosaposin" ("HGNC:9498" "prosaposin")) 
(define-protein "Prot" ("HGNC:11054" "solute carrier family 6 member 7")) 
(define-protein "Psim" ("UP:P48185" "Photosystem I reaction center subunit XII")) 
(define-protein "Pso" ("UP:Q29RU9" "Peroxisomal sarcosine oxidase")) 
(define-protein "Ptc" ("UP:Q13635" "Protein patched homolog 1")) 
(define-protein "Ptch" ("NCIT:C51720" "PTCH")) 
(define-protein "Ptn" ("HGNC:9630" "pleiotrophin")) 
(define-protein "Ptprd" ("HGNC:9668" "protein tyrosine phosphatase, receptor type D")) 
(define-protein "Puralpha" ("NCIT:C51297" "PURA")) 
(define-protein "Qin" ("NCIT:C52899" "FOXG1B")) 
(define-protein "Rab" ("FA:03661" "rab family")) 
(define-protein "Rak" ("NCIT:C29586" "FYN-related kinase")) 
(define-protein "Ral" ("XFAM:PF11058.6" "ral")) 
(define-protein "Rao" ("UP:O75106" "Retina-specific copper amine oxidase")) 
(define-protein "Rbpj" ("HGNC:5724" "recombination signal binding protein for immunoglobulin kappa J region")) 
(define-protein "Rbx" ("UP:P01478" "Delta-hexatoxin-Ar1a")) 
(define-protein "Rcl" ("HGNC:21218" "2'-deoxynucleoside 5'-phosphate N-hydrolase 1")) 
(define-protein "Refs" ("XFAM:PF05755.10" "REF")) 
(define-protein "Rel" ("HGNC:9954" "REL proto-oncogene, NF-kB subunit")) 
(define-protein "Reln" ("HGNC:9957" "reelin")) 
(define-protein "Ren" ("HGNC:9958" "renin")) 
(define-protein "Rep1" ("UP:O91254" "Para-Rep C1")) 
(define-protein "Rgnef" ("NCIT:C97266" "RGNEF")) 
(define-protein "Rhes" ("HGNC:18229" "RASD family member 2")) 
(define-protein "Rho" ("FA:03668" "rho family")) 
(define-protein "Rin" ("HGNC:10017" "Ras like without CAAX 2")) 
(define-protein "Rlim" ("HGNC:13429" "ring finger protein, LIM domain interacting")) 
(define-protein "Ron" ("NCIT:C52177" "MST1R")) 
(define-protein "Rootletin" ("UP:Q5TZA2" "Rootletin")) 
(define-protein "Rorc" ("HGNC:10260" "RAR related orphan receptor C")) 
(define-protein "Rox" ("UP:P44683" "Probable ribosomal oxygenase HI_0396")) 
(define-protein "Rps" ("HGNC:7414" "mitochondrially encoded ATP synthase 6")) 
(define-protein "Rpx" ("HGNC:4877" "HESX homeobox 1")) 
(define-protein "Rsc" ("NCIT:C19802" "RSC")) 
(define-protein "Rsk" ("NCIT:C104765" "RPS6KA1")) 
(define-protein "Rta" ("UP:Q1HVG0" "Replication and transcription activator")) 
(define-protein "Sal" ("UP:P81608" "Salivary lipocalin")) 
(define-protein "San" ("HGNC:29533" "N(alpha)-acetyltransferase 50, NatE catalytic subunit")) 
(define-protein "Sarafotoxin" ("UP:P13208" "Sarafotoxin")) 
(define-protein "Scap" ("HGNC:30634" "SREBF chaperone")) 
(define-protein "Sclerostin" ("HGNC:13771" "sclerostin")) 
(define-protein "Scott" ("UP:Q9BYC2" "Succinyl-CoA:3-ketoacid coenzyme A transferase 2, mitochondrial")) 
(define-protein "Sema" ("XFAM:PF01403.17" "sema")) 
(define-protein "Ses" ("XFAM:PF08491.8" "SE")) 
(define-protein "Sev" ("UP:P07647" "Submandibular glandular kallikrein-9")) 
(define-protein "Shc" ("NCIT:C52429" "SHC1")) 
(define-protein "Shelterin" ("NCIT:C118795" "shelterin")) 
(define-protein "Shi" ("UP:P19651" "Delta-stichotoxin-She1a {ECO:0000303|PubMed:22683676}")) 
(define-protein "Siva" ("XFAM:PF05458.10" "siva")) 
(define-protein "Slp" ("XFAM:PF03843.11" "slp")) 
(define-protein "Smit" ("HGNC:11038" "solute carrier family 5 member 3")) 
(define-protein "Snk" ("NCIT:C51320" "SNK")) 
(define-protein "Somatostatin" ("HGNC:11329" "somatostatin")) 
(define-protein "Sorcin" ("HGNC:11292" "sorcin")) 
(define-protein "Sost" ("HGNC:13771" "sclerostin")) 
(define-protein "Spl" ("UP:Q9C509" "Sphingosine-1-phosphate lyase")) 
(define-protein "Srcasm" ("HGNC:11983" "target of myb1 like 1 membrane trafficking protein")) 
(define-protein "Srk" ("NCIT:C29911" "ribosomal protein S6 kinase beta-2")) 
(define-protein "Sry" ("HGNC:11311" "sex determining region Y")) 
(define-protein "Stats" ("UP:P08457" "Streptothricin acetyltransferase")) 
(define-protein "Stx" ("HGNC:10870" "ST8 alpha-N-acetyl-neuraminide alpha-2,8-sialyltransferase 2")) 
(define-protein "Sufu" ("HGNC:16466" "SUFU negative regulator of hedgehog signaling")) 
(define-protein "Sumo" ("UP:P55853" "Small ubiquitin-related modifier")) 
(define-protein "Supervillin" ("HGNC:11480" "supervillin")) 
(define-protein "Sur" ("HGNC:59" "ATP binding cassette subfamily C member 8")) 
(define-protein "Synemin" ("HGNC:24466" "synemin")) 
(define-protein "Synip" ("UP:Q6ZWJ1" "Syntaxin-binding protein 4")) 
(define-protein "Syp" ("HGNC:11506" "synaptophysin")) 
(define-protein "Tak" ("NCIT:C126981" "CDK9")) 
(define-protein "Tara" ("HGNC:17009" "TRIO and F-actin binding protein")) 
(define-protein "Tenascin" ("UP:P10039" "Tenascin")) 
(define-protein "Tet" ("UP:O59196" "Tetrahedral aminopeptidase")) 
(define-protein "Tetraspan" ("HGNC:11859" "tetraspanin 4")) 
(define-protein "Tfam" ("HGNC:11741" "transcription factor A, mitochondrial")) 
(define-protein "Tfpt" ("HGNC:13630" "TCF3 fusion partner")) 
(define-protein "Tgfa" ("HGNC:11765" "transforming growth factor alpha")) 
(define-protein "Tgfbeta" ("FA:03989" "TGF-beta family")) 
(define-protein "Thioredoxin" ("HGNC:12435" "thioredoxin")) 
(define-protein "Tim" ("UP:P17751" "Triosephosphate isomerase")) 
(define-protein "Tipin" ("HGNC:30750" "TIMELESS interacting protein")) 
(define-protein "Tnf" ("HGNC:11892" "tumor necrosis factor")) 
(define-protein "Tob" ("HGNC:11979" "transducer of ERBB2, 1")) 
(define-protein "Tollip" ("FA:04120" "tollip family")) 
(define-protein "Topors" ("HGNC:21653" "TOP1 binding arginine/serine rich protein")) 
(define-protein "Tpo" ("HGNC:12015" "thyroid peroxidase")) 
(define-protein "Tpr" ("HGNC:12017" "translocated promoter region, nuclear basket protein")) 
(define-protein "Treslin" ("UP:Q6DRL4" "Treslin")) 
(define-protein "Tsad" ("HGNC:10821" "SH2 domain containing 2A")) 
(define-protein "Tshr" ("HGNC:12373" "thyroid stimulating hormone receptor")) 
(define-protein "Vdr" ("HGNC:12679" "vitamin D (1,25- dihydroxyvitamin D3) receptor")) 
(define-protein "Vegf" ("NCIT:C52018" "VEGF")) 
(define-protein "Vit" ("HGNC:12697" "vitrin")) 
(define-protein "Vpr" ("XFAM:PF00522.16" "VPR")) 
(define-protein "Vps" ("NCIT:C52392" "AVP")) 
(define-protein "Wapl" ("HGNC:23293" "WAPL cohesin release factor")) 
(define-protein "Xbra" ("UP:P24781" "Brachyury protein")) 
(define-protein "Xin" ("FA:04696" "xin family")) 
(define-protein "Yes" ("HGNC:12841" "YES proto-oncogene 1, Src family tyrosine kinase")) 
(define-protein "Zeb" ("NCIT:C105606" "ZEB1")) 