("14-3-3 sigma" "ONT:PROTEIN" :id "NCIT:C26474" :name "stratifin") 
("14-3-3zeta" "ONT:GENE" :id "NCIT:C88205" :name "YWHAZ") 
("24h" "ONT:CELL-LINE" :id "CVCL:8262" :name "SCLC-24H") 
("3alpha" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF03475.12" :name "3-alpha") 
("5-aminoimidazole-4-carboxamide" "ONT:CHEMICAL" :id "CHEBI:2030" :name "5-aminoimidazole-4-carboxamide") 
("501mel" "ONT:CELL-LINE" :id "CVCL:4633" :name "501-mel") 
("5alpha-dihydrotestosterone" "ONT:CHEMICAL" :id "CHEBI:16330" :name "17beta-hydroxy-5alpha-androstan-3-one") 
("abiraterone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77333" :name "abiraterone") 
("acacetin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C023717" :name "acacetin") 
("acadesine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C71537" :name "acadesine") 
("acriflavine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76253" :name "acriflavine") 
("activins" "ONT:GENE-PROTEIN" :id "NCIT:C20456" :name "activin") 
("adenanthin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C000600164" :name "adenanthin") 
("adenoviruses" "ONT:VIRUS" :id "NCIT:C14179" :name "adenovirus") 
("adhesin" "ONT:PROTEIN" :id "UP:P0C2T3" :name "Heparin-binding hemagglutinin") 
("adhesins" "ONT:PROTEIN" :id "UP:P0C2T3" :name "Heparin-binding hemagglutinin") 
("adipocytokine" "ONT:PROTEIN-FAMILY" :id "NCIT:C123810" :name "adipokine") 
("adipokines" "ONT:PROTEIN-FAMILY" :id "NCIT:C123810" :name "adipokine") 
("agouti" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05039.10" :name "agouti") 
("albuminuria" "ONT:PHYSICAL-CONDITION" :id "EFO:0004285" :name "albuminuria") 
("aliskiren" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65222" :name "aliskiren") 
("alkaloid" "ONT:CHEMICAL" :id "CHEBI:22315" :name "alkaloid") 
("alpha-actinin" "ONT:PROTEIN-FAMILY" :id "FA:00161" :name "alpha-actinin family") 
("alphavirus" "ONT:VIRUS" :id "NCIT:C112030" :name "alphavirus") 
("amides" "ONT:MOLECULE" :id "CHEBI:32988" :name "amide") 
("aminopurine" "ONT:MOLECULE" :id "CHEBI:22527" :name "aminopurine") 
("amsacrine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C240" :name "amsacrine") 
("anabolism" "ONT:BIOLOGICAL-PROCESS" :id "GO:0009058" :name "biosynthetic process") 
("anagen" "ONT:TIME-SPAN" :id "GO:0042640" :name "anagen") 
("andrographolide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61637" :name "andrographolide") 
("angiomyolipomas" "ONT:CANCER" :id "NCIT:C3734" :name "angiomyolipoma") 
("anillin" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF08174.9" :name "anillin") 
("ansamycin" "ONT:MOLECULE" :id "CHEBI:22565" :name "ansamycin") 
("ansamycins" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1003" :name "ansamycin antineoplastic antibiotic") 
("anthracycline" "ONT:CHEMICAL" :id "CHEBI:48120" :name "anthracycline") 
("antiandrogen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C242" :name "anti-androgen") 
("antiandrogens" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C242" :name "anti-androgen") 
("antimetabolites" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C272" :name "antimetabolite") 
("antioxidants" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C275" :name "antioxidant") 
("apicidin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C102351" :name "apicidin") 
("apoptin" "ONT:PROTEIN" :id "UP:P54095" :name "Apoptin") 
("apoptotic protease activating factor-1" "ONT:PROTEIN" :id "NCIT:C20930" :name "apoptotic protease activating factor-1") 
("aprotinin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47402" :name "aprotinin bovine") 
("arco" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C543979" :name "artemisinin-naphthoquine combination") 
("arecoline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76610" :name "arecoline") 
("arrs" "ONT:BIOLOGICAL-PROCESS" :id "GO:0090644" :name "age-related resistance") 
("arzoxifene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1805" :name "arzoxifene") 
("astemizole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28834" :name "astemizole") 
("astrin" "ONT:PROTEIN" :id "UP:Q96R06" :name "Sperm-associated antigen 5") 
("ates" "ONT:GENE" :id "NCIT:C51192" :name "ATM") 
("atropine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28840" :name "atropine") 
("autoantibodies" "ONT:PROTEIN" :id "NCIT:C48966" :name "autoantibody") 
("autolysosome" "ONT:CELL-PART" :id "GO:0044754" :name "autolysosome") 
("autolysosomes" "ONT:CELL-PART" :id "GO:0044754" :name "autolysosome") 
("autophagolysosome" "ONT:CELL-PART" :id "GO:0044754" :name "autolysosome") 
("autotaxin" "ONT:PROTEIN" :id "NCIT:C104211" :name "ectonucleotide pyrophosphatase-phosphodiesterase family member 2") 
("autotransporter" "ONT:PROTEIN" :id "GO:0015474" :name "autotransporter activity") 
("axons" "ONT:CELL-PART" :id "UP:SL-0279" :name "Axon") 
("azaserine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C289" :name "azaserine") 
("azepine" "ONT:MOLECULE" :id "CHEBI:48105" :name "azepine") 
("bacitracin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C295" :name "bacitracin") 
("baclofen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28858" :name "baclofen") 
("baculovirus" "ONT:VIRUS" :id "NCIT:C61156" :name "baculoviridae") 
("benzenesulfonyl" "ONT:CHEMICAL" :id "CHEBI:52916" :name "phenylsulfonyl group") 
("benzidine" "ONT:CHEMICAL" :id "NCIT:C44335" :name "benzidine") 
("benzimidazole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C031000" :name "benzimidazole") 
("benzodiazepines" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:22720" :name "benzodiazepine") 
("betac" "ONT:PROTEIN" :id "NCIT:C26104" :name "colony stimulating factor-2 receptor beta") 
("betacatenin" "ONT:GENE-PROTEIN" :id "NCIT:C17478" :name "beta catenin") 
("betaglycan" "ONT:GENE-PROTEIN" :id "NCIT:C30099" :name "transforming growth factor beta receptor-III") 
("bicalutamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1599" :name "bicalutamide") 
("biguanide" "ONT:MOLECULE" :id "CHEBI:3095" :name "biguanide") 
("bilirubin" "ONT:CHEMICAL" :id "CHEBI:16990" :name "bilirubin") 
("bisulfite" "ONT:CHEMICAL" :id "CHEBI:17137" :name "hydrogensulfite") 
("blastema" "ONT:INTERNAL-BODY-PART" :id "BTO:0001638" :name "blastema") 
("blebbistatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C472645" :name "blebbistatin") 
("boldine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C011686" :name "boldine") 
("bosentan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47417" :name "bosentan") 
("boutons" "ONT:CELL-PART" :id "GO:0043195" :name "terminal bouton") 
("bromodomains" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00439.23" :name "bromodomain") 
("butadiene" "ONT:MOLECULE" :id "CHEBI:39479" :name "butadiene") 
("butanediol" "ONT:MOLECULE" :id "CHEBI:52684" :name "butanediol") 
("butyrolactone" "ONT:CHEMICAL" :id "CHEBI:42639" :name "gamma-butyrolactone") 
("cabazitaxel" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C552428" :name "cabazitaxel") 
("cachexia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "HP:0004326" :name "cachexia") 
("calbindin" "ONT:GENE-PROTEIN" :id "UP:P05937" :name "Calbindin") 
("calmidazolium" "ONT:CHEMICAL" :id "CHEBI:75400" :name "calmidazolium") 
("calpeptin" "ONT:MOLECULE" :id "CHEBI:3330" :name "Calpeptin") 
("calreticulin" "ONT:GENE-PROTEIN" :id "HGNC:1455" :name "calreticulin") 
("capa" "ONT:CELL-LINE" :id "CVCL:1U09" :name "CaPa") 
("carbenoxolone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C63669" :name "carbenoxolone") 
("carcinoid" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0004243" :name "carcinoid tumor") 
("carnosol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C068623" :name "carnosol") 
("casodex" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1599" :name "bicalutamide") 
("catalyses" "ONT:BIOLOGICAL-PROCESS" :id "NCIT:C52472" :name "catalysis") 
("cathepsins" "ONT:PROTEIN" :id "NCIT:C16389" :name "cathepsin") 
("caveolins" "ONT:PROTEIN-FAMILY" :id "FA:00489" :name "caveolin family") 
("centrioles" "ONT:CELL-PART" :id "UP:SL-0046" :name "Centriole") 
("centrobin" "ONT:PROTEIN" :id "UP:Q8N137" :name "Centrobin") 
("cercosporamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C085452" :name "cercosporamide") 
("cess" "ONT:CELL-LINE" :id "EFO:0002130" :name "CESS") 
("chelators" "ONT:CHEMICAL" :id "NCIT:C360" :name "chelating agent") 
("chez" "ONT:PROTEIN-FAMILY" :id "XFAM:PF04344.11" :name "CheZ") 
("chlamydiae" "ONT:BACTERIUM" :id "NCIT:C76270" :name "chlamydiae") 
("chloropyramine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81130" :name "chloropyramine") 
("cholate" "ONT:CHEMICAL" :id "CHEBI:29747" :name "cholate") 
("chronophin" "ONT:PROTEIN" :id "UP:Q3ZBF9" :name "Pyridoxal phosphate phosphatase") 
("chrysin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C043561" :name "chrysin") 
("chrysotile" "ONT:CHEMICAL" :id "CHEBI:46664" :name "chrysotile") 
("cicaprost" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C043867" :name "cicaprost") 
("ciclopirox" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61677" :name "ciclopirox") 
("cilengitide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1834" :name "cilengitide") 
("cina" "ONT:PROTEIN-FAMILY" :id "XFAM:PF02464.15" :name "CinA") 
("circ" "ONT:PROTEIN" :id "UP:P84641" :name "Circulin-C") 
("cladosporol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C548360" :name "cladosporol") 
("clonidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C380" :name "clonidine") 
("co-" "ONT:CELL-LINE" :id "CVCL:J653" :name "CO") 
("coagulopathy" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C2902" :name "coagulation disorder") 
("cohesins" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00963.16" :name "cohesin") 
("colchicine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C385" :name "colchicine") 
("condensins" "ONT:PROTEIN-FAMILY" :id "XFAM:PF04079.14" :name "SMC ScpB") 
("conidia" "ONT:INTERNAL-BODY-PART" :id "BTO:0000283" :name "conidium") 
("connexons" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0005922" :name "connexin complex") 
("coreceptors" "ONT:PROTEIN" :id "GO:0015026" :name "coreceptor activity") 
("corticotroph" "ONT:CELL" :id "CO:0002309" :name "corticotroph") 
("cpm" "ONT:GENE-PROTEIN" :id "HGNC:2311" :name "carboxypeptidase M") 
("cristae" "ONT:CELL-PART" :id "GO:0030061" :name "mitochondrial crista") 
("cryptorchidism" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0004562" :name "cryptorchidism") 
("cyclodepsipeptide" "ONT:MOLECULE" :id "CHEBI:35213" :name "cyclodepsipeptide") 
("cyclophosphamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C405" :name "cyclophosphamide") 
("cynomolgus" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14232" :name "cynomolgus monkey") 
("cyproterone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C407" :name "cyproterone") 
("cystadenomas" "ONT:CANCER" :id "NCIT:C2972" :name "cystadenoma") 
("cystatins" "ONT:GENE-PROTEIN" :id "FA:00839" :name "cystatin family") 
("cytarabine" "ONT:CHEMICAL" :id "CHEBI:28680" :name "cytarabine") 
("daintain" "ONT:PROTEIN" :id "UP:P81076" :name "Allograft inflammatory factor 1") 
("dantrolene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61697" :name "dantrolene") 
("de-differentiation" "ONT:BIOLOGICAL-PROCESS" :id "GO:0043696" :name "dedifferentiation") 
("deguelin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C107676" :name "deguelin") 
("dehydrotestosterone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C013915" :name "boldenone") 
("dem" "ONT:CELL-LINE" :id "CVCL:E559" :name "DEM") 
("dendrites" "ONT:CELL-PART" :id "UP:SL-0283" :name "Dendrite") 
("deoxycholate" "ONT:CHEMICAL" :id "CHEBI:23614" :name "deoxycholate") 
("deoxyribonucleotides" "ONT:MOLECULE" :id "CHEBI:4431" :name "deoxyribonucleotide") 
("deuterium" "ONT:CHEMICAL" :id "CHEBI:29237" :name "deuterium atom") 
("dexrazoxane" "ONT:CHEMICAL" :id "NCIT:C1333" :name "dexrazoxane") 
("diacerein" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C025292" :name "diacetylrhein") 
("diarylpropionitrile" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C492519" :name "diarylpropionitrile") 
("diazoxide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C428" :name "diazoxide") 
("diclofenac" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C28985" :name "diclofenac") 
("dicoumarol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C310" :name "dicumarol") 
("dieldrin" "ONT:CHEMICAL" :id "CHEBI:34696" :name "dieldrin") 
("dienestrol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65377" :name "dienestrol") 
("dienogest" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C87238" :name "dienogest") 
("diethylnitrosamine" "ONT:CHEMICAL" :id "CHEBI:34873" :name "N-nitrosodiethylamine") 
("diethylstilbestrol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C433" :name "diethylstilbestrol") 
("diferuloylmethane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C401" :name "curcumin") 
("digitonin" "ONT:CHEMICAL" :id "CHEBI:27729" :name "digitonin") 
("diglycine" "ONT:CHEMICAL" :id "CHEBI:24786" :name "iminodiacetic acid") 
("dinoprostone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61727" :name "dinoprostone") 
("diosgenin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:4629" :name "diosgenin") 
("dipeptide" "ONT:MOLECULE" :id "CHEBI:46761" :name "dipeptide") 
("diphenyleneiodonium" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C007517" :name "diphenyleneiodonium") 
("diss" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:94064" :name "Deafness-infertility syndrome") 
("disulfides" "ONT:MOLECULE" :id "CHEBI:35489" :name "organic disulfide") 
("docetaxol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C067311" :name "docetaxel") 
("dodecyl" "ONT:MOLECULE" :id "CHEBI:23870" :name "dodecyl group") 
("doxycyclin" "ONT:MOLECULE" :id "CHEBI:50845" :name "doxycycline") 
("dynasore" "ONT:CHEMICAL" :id "CHEBI:132754" :name "dynasore") 
("dysadherin" "ONT:PROTEIN" :id "UP:Q96DB9" :name "FXYD domain-containing ion transport regulator 5") 
("ebselen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65503" :name "ebselen") 
("eckol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:65819" :name "eckol") 
("eclampsia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C87167" :name "eclampsia") 
("edoxaban" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C96539" :name "edoxaban") 
("eicosanoid" "ONT:MOLECULE" :id "CHEBI:23899" :name "icosanoid") 
("embelin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C010945" :name "embelin") 
("endolysosomes" "ONT:CELL-PART" :id "GO:0036019" :name "endolysosome") 
("endonucleases" "ONT:PROTEIN" :id "GO:0004519" :name "endonuclease activity") 
("endosialin" "ONT:PROTEIN" :id "UP:Q9HCU0" :name "Endosialin") 
("endotheliocytes" "ONT:CELL" :id "CO:0000115" :name "endothelial cell") 
("enteroviruses" "ONT:VIRUS" :id "NCIT:C14203" :name "enterovirus") 
("entinostat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C118739" :name "entinostat") 
("enzalutamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:68534" :name "enzalutamide") 
("epigen" "ONT:GENE-PROTEIN" :id "UP:Q5EG71" :name "Epigen") 
("epinephrine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C473" :name "therapeutic epinephrine") 
("eplerenone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47513" :name "eplerenone") 
("equol" "ONT:MOLECULE" :id "CHEBI:34741" :name "equol") 
("ergosterol" "ONT:CHEMICAL" :id "CHEBI:16933" :name "ergosterol") 
("erythroblasts" "ONT:CELL" :id "BTO:0001571" :name "erythroblast") 
("erythroleukemia" "ONT:CANCER" :id "NCIT:C7152" :name "erythroleukemia") 
("escin" "ONT:CHEMICAL" :id "CHEBI:2500" :name "Aescin") 
("estramustine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C479" :name "estramustine") 
("estriol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C80154" :name "estriol") 
("ethidium" "ONT:CHEMICAL" :id "CHEBI:42478" :name "ethidium") 
("ethynyl" "ONT:MOLECULE" :id "CHEBI:30085" :name "ethynyl") 
("etodolac" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47526" :name "etodolac") 
("euchromatin" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0000791" :name "euchromatin") 
("eukaryote" "ONT:ORGANISM" :id "NCIT:C25796" :name "eukaryote") 
("evodiamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C049639" :name "evodiamine") 
("exemestane" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1097" :name "exemestane") 
("exosomes" "ONT:CELL-PART" :id "UP:SL-0466" :name "Exosome") 
("faslodex" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1379" :name "fulvestrant") 
("febuxostat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65629" :name "febuxostat") 
("fenofibrate" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29047" :name "fenofibrate") 
("fenretinide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1098" :name "fenretinide") 
("fetus" "ONT:INTERNAL-BODY-PART" :id "BTO:0000449" :name "fetus") 
("fibrocytes" "ONT:CELL" :id "CO:0000135" :name "fibrocyte") 
("fibroids" "ONT:CANCER" :id "NCIT:C3157" :name "leiomyoma") 
("fidarestat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C81355" :name "fidarestat") 
("filipin" "ONT:CHEMICAL" :id "CHEBI:83267" :name "filipin III") 
("finasteride" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1099" :name "finasteride") 
("flavone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C043562" :name "flavone") 
("flotillins" "ONT:PROTEIN-FAMILY" :id "FA:00330" :name "flotillin subfamily") 
("fluorophosphate" "ONT:MOLECULE" :id "CHEBI:42699" :name "fluoridophosphate") 
("flutamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C509" :name "flutamide") 
("fluticasone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61767" :name "fluticasone") 
("fortilin" "ONT:GENE-PROTEIN" :id "NCIT:C101391" :name "translationally-controlled tumor protein") 
("fostriecin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1372" :name "fostriecin") 
("fucoxanthinol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C483031" :name "fucoxanthinol") 
("fumonisin" "ONT:CHEMICAL" :id "CHEBI:38224" :name "fumonisin") 
("fungizone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62201" :name "amphotericin B deoxycholate") 
("gadd45beta" "ONT:GENE" :id "NCIT:C105845" :name "GADD45B") 
("galeterone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C84866" :name "specific androgen receptor modulator CYP17 inhibitor TOK-001") 
("gallotannin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:24182" :name "gallotannin") 
("gangliosides" "ONT:MOLECULE" :id "CHEBI:28892" :name "ganglioside") 
("garcinol" "ONT:MOLECULE" :id "CHEBI:5276" :name "Garcinol") 
("gastrins" "ONT:GENE-PROTEIN" :id "HGNC:4164" :name "gastrin") 
("genotoxin" "ONT:CHEMICAL" :id "CHEBI:50902" :name "genotoxin") 
("genotoxins" "ONT:CHEMICAL" :id "CHEBI:50902" :name "genotoxin") 
("geraldol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C560847" :name "3,4',7-trihydroxy-3'-methoxyflavone") 
("ginsenoside" "ONT:CHEMICAL" :id "CHEBI:74978" :name "ginsenoside") 
("gliotoxin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:5385" :name "gliotoxin") 
("globotriaosylceramide" "ONT:CHEMICAL" :id "CHEBI:18313" :name "alpha-D-galactosyl-(1->4)-beta-D-galactosyl-(1->4)-beta-D-glucosylceramide") 
("glyburide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29076" :name "glyburide") 
("glyceollins" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C017343" :name "glyceollin") 
("glycosaminoglycan" "ONT:MOLECULE" :id "CHEBI:18085" :name "glycosaminoglycan") 
("glycosaminoglycans" "ONT:MOLECULE" :id "CHEBI:18085" :name "glycosaminoglycan") 
("glycosphingolipids" "ONT:MOLECULE" :id "CHEBI:24402" :name "glycosphingolipid") 
("gonadotrophs" "ONT:CELL" :id "CO:0000437" :name "gonadtroph") 
("gonorrhoeae" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C92950" :name "gonorrhea") 
("gramicidin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C65816" :name "gramicidin") 
("gravin" "ONT:PROTEIN" :id "NCIT:C21326" :name "A kinase anchor protein-12") 
("guanidino" "ONT:MOLECULE" :id "CHEBI:48551" :name "guanidino group") 
("guggulsterone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C023617" :name "pregna-4,17-diene-3,16-dione") 
("hapten" "ONT:CHEMICAL" :id "CHEBI:59174" :name "hapten") 
("hemangiomas" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1000635" :name "hemangioma") 
("hematoxylin" "ONT:CHEMICAL" :id "CHEBI:51686" :name "haematoxylin") 
("hemerythrin" "ONT:PROTEIN" :id "UP:P80255" :name "Hemerythrin") 
("henryin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C586151" :name "henryin") 
("heregulins" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1426" :name "recombinant heregulin") 
("herpesviridae" "ONT:VIRUS" :id "NCIT:C14217" :name "herpesvirus") 
("herpesviruses" "ONT:VIRUS" :id "NCIT:C14217" :name "herpesvirus") 
("hexose" "ONT:MOLECULE" :id "CHEBI:18133" :name "hexose") 
("hif-1alpha" "ONT:GENE-PROTEIN" :id "UP:Q16665" :name "Hypoxia-inducible factor 1-alpha") 
("hispidin" "ONT:CHEMICAL" :id "CHEBI:36332" :name "hispidin") 
("histiocytes" "ONT:CELL" :id "CO:0000235" :name "macrophage") 
("histones" "ONT:PROTEIN" :id "NCIT:C16687" :name "histone") 
("homoserine" "ONT:CHEMICAL" :id "CHEBI:30653" :name "homoserine") 
("hydrocortisone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C555" :name "therapeutic hydrocortisone") 
("hydroperoxides" "ONT:MOLECULE" :id "CHEBI:35923" :name "hydroperoxide") 
("hydroquinone" "ONT:CHEMICAL" :id "NCIT:C29823" :name "hydroquinone") 
("hydroxyanthraquinone" "ONT:MOLECULE" :id "CHEBI:28877" :name "1-hydroxyanthraquinone") 
("hydroxyflutamide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C63948" :name "hydroxyflutamide") 
("hydroxyquinoline" "ONT:MOLECULE" :id "CHEBI:38774" :name "hydroxyquinoline") 
("hydroxyurea" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C560" :name "hydroxyurea") 
("hyperglycaemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "HP:0003074" :name "Hyperglycemia") 
("hypericin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C37456" :name "hypericin") 
("hypertriglyceridemia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0004211" :name "Hypertriglyceridemia") 
("hypospadias" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C40341" :name "hypospadias") 
("idelalisib" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C552946" :name "idelalisib") 
("iduna" "ONT:GENE-PROTEIN" :id "NCIT:C99466" :name "RNF146") 
("immunosuppressants" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C574" :name "immunosuppressant") 
("indirubin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C027185" :name "indirubin") 
("indolocarbazole" "ONT:MOLECULE" :id "CHEBI:51915" :name "indolocarbazole") 
("inducers" "ONT:CHEMICAL" :id "NCIT:C120268" :name "inducer") 
("infarct" "ONT:BIOLOGICAL-PROCESS" :id "NCIT:C25738" :name "infarction") 
("ink4a" "ONT:GENE" :id "NCIT:C49511" :name "CDKN2A") 
("insulin like growth factor-1" "ONT:PROTEIN" :id "NCIT:C16743" :name "insulin-like growth factor-1") 
("insulinomas" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000549" :name "insulinoma") 
("interleukin 1 beta" "ONT:GENE" :id "HGNC:5992" :name "interleukin 1 beta") 
("interleukin 1beta" "ONT:PROTEIN" :id "NCIT:C20522" :name "interleukin-1-beta") 
("invadopodium" "ONT:CELL-PART" :id "UP:SL-0148" :name "Invadopodium") 
("isoflavones" "ONT:MOLECULE" :id "CHEBI:38757" :name "isoflavones") 
("isoliquiritigenin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C040920" :name "isoliquiritigenin") 
("isoprenoid" "ONT:MOLECULE" :id "CHEBI:24913" :name "isoprenoid") 
("isosilybin" "ONT:CHEMICAL" :id "CHEBI:80744" :name "isosilybin") 
("jacalin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C043696" :name "jacalin") 
("jasplakinolide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C057531" :name "jasplakinolide") 
("karyogamy" "ONT:BIOLOGICAL-PROCESS" :id "GO:0000741" :name "karyogamy") 
("keloid" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C3145" :name "keloid") 
("kenpaullone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C119620" :name "kenpaullone") 
("kilodalton" "ONT:WEIGHT-UNIT" :id "UO:0000222" :name "kilodalton") 
("kinesins" "ONT:GENE-PROTEIN" :id "FA:01965" :name "kinesin family") 
("kreisler" "ONT:PROTEIN" :id "UP:P54841" :name "Transcription factor MafB") 
("kringles" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF00051.16" :name "kringle") 
("lacritin" "ONT:GENE" :id "HGNC:16430" :name "lacritin") 
("lactacystin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C067713" :name "lactacystin") 
("lalanyl" "ONT:MOLECULE" :id "CHEBI:46217" :name "L-alanine residue") 
("laminins" "ONT:PROTEIN-FAMILY" :id "NCIT:C16778" :name "laminin") 
("layilin" "ONT:GENE-PROTEIN" :id "HGNC:29471" :name "layilin") 
("lenalidomide" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C467567" :name "lenalidomide") 
("lentiviruses" "ONT:VIRUS" :id "NCIT:C14290" :name "lentivirus") 
("let-7" "ONT:RNA" :id "NCIT:C48183" :name "let-7") 
("letrozole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1527" :name "letrozole") 
("liquiritigenin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C083152" :name "liquiritigenin") 
("lumina" "ONT:MEASURE-UNIT" :id "UO:0000118" :name "lumen") 
("lupulone" "ONT:MOLECULE" :id "CHEBI:6574" :name "Lupulone") 
("lycopene" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C015329" :name "lycopene") 
("lysotracker" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C493330" :name "Red DND-99") 
("macroautophagy" "ONT:BIOLOGICAL-PROCESS" :id "GO:0016236" :name "macroautophagy") 
("macrolide" "ONT:MOLECULE" :id "CHEBI:25106" :name "macrolide") 
("macrolides" "ONT:MOLECULE" :id "CHEBI:25106" :name "macrolide") 
("magnetite" "ONT:CHEMICAL" :id "CHEBI:46726" :name "magnetite") 
("mahanine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C465290" :name "mahanine") 
("manumycin" "ONT:MOLECULE" :id "CHEBI:29623" :name "Manumycin A") 
("maritoclax" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C528298" :name "marinopyrrole A") 
("megakaryocytes" "ONT:CELL" :id "BTO:0000843" :name "megakaryocyte") 
("melphalan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C633" :name "melphalan") 
("ment" "ONT:GENE" :id "HGNC:26045" :name "chromosome 1 open reading frame 56") 
("mepacrine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C87656" :name "quinacrine") 
("mers" "ONT:GENE-PROTEIN" :id "UP:P84089" :name "Enhancer of rudimentary homolog") 
("metalloenzyme" "ONT:PROTEIN-FAMILY" :id "XFAM:PF01676.16" :name "metalloenzyme") 
("metazoan" "ONT:PROTEIN-FAMILY" :id "FA:00289" :name "metazoan subfamily") 
("metazoans" "ONT:PROTEIN-FAMILY" :id "FA:00289" :name "metazoan subfamily") 
("methacholine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:6804" :name "methacholine") 
("methamphetamine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61840" :name "methamphetamine") 
("methoxyflavone" "ONT:MOLECULE" :id "CHEBI:25241" :name "methoxyflavone") 
("methylases" "ONT:PROTEIN" :id "GO:0008168" :name "methyltransferase activity") 
("methylcholanthrene" "ONT:CHEMICAL" :id "CHEBI:34342" :name "3-methylcholanthrene") 
("metyrapone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47619" :name "metyrapone") 
("mevastatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C96285" :name "mevastatin") 
("mibolerone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72100" :name "mibolerone") 
("microbiome" "ONT:MICROORGANISM" :id "NCIT:C68564" :name "microbiome") 
("microfibrils" "ONT:CELL-PART" :id "GO:0001527" :name "microfibril") 
("microfilaments" "ONT:CELL-PART" :id "GO:0005884" :name "actin filament") 
("microflora" "ONT:MICROORGANISM" :id "NCIT:C93019" :name "intestinal flora") 
("microliters" "ONT:VOLUME-UNIT" :id "UO:0000101" :name "microliter") 
("micronuclei" "ONT:CELL-PART" :id "GO:0031040" :name "micronucleus") 
("microspike" "ONT:CELL-PART" :id "GO:0044393" :name "microspike") 
("microtubuli" "ONT:CELL-PART" :id "GO:0005874" :name "microtubule") 
("microvesicle" "ONT:CELL-PART" :id "GO:1990742" :name "microvesicle") 
("microvilli" "ONT:CELL-PART" :id "UP:SL-0293" :name "Microvillus") 
("minima" "ONT:PROCEDURE" :id "NCIT:C82867" :name "minimum value derivation technique") 
("minocycline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61849" :name "minocycline") 
("mirin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C526365" :name "6-(4-hydroxyphenyl)-2-thioxo-2,3-dihydro-4(1H)-pyrimidinone") 
("mirtazapine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29265" :name "mirtazapine") 
("mito" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1820" :name "mitomycin C") 
("mitophagy" "ONT:BIOLOGICAL-PROCESS" :id "GO:0000422" :name "mitophagy") 
("mitoxantrone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:50729" :name "mitoxantrone") 
("monensin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C83971" :name "monensin") 
("mono-" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34726" :name "infectious mononucleosis") 
("monoblasts" "ONT:CELL" :id "CO:0000040" :name "monoblast") 
("morin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C008548" :name "morin") 
("morphogens" "ONT:PROTEIN" :id "GO:0016015" :name "morphogen activity") 
("muscarine" "ONT:MOLECULE" :id "CHEBI:7034" :name "Muscarine") 
("mutagen" "ONT:CHEMICAL" :id "CHEBI:25435" :name "mutagen") 
("myeloblasts" "ONT:CELL" :id "CO:0000835" :name "myeloblast") 
("myofibrils" "ONT:CELL-PART" :id "UP:SL-0312" :name "Myofibril") 
("myoglobin" "ONT:GENE-PROTEIN" :id "HGNC:6915" :name "myoglobin") 
("myositis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000783" :name "myositis") 
("myotubes" "ONT:CELL" :id "CO:0002372" :name "myotube") 
("myxedema" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34834" :name "myxedema") 
("nanosecond" "ONT:TIME-UNIT" :id "UO:0000150" :name "nanosecond") 
("naphthoquinone" "ONT:MOLECULE" :id "CHEBI:25481" :name "naphthoquinone") 
("navitoclax" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C528561" :name "navitoclax") 
("nephronectin" "ONT:GENE-PROTEIN" :id "HGNC:27405" :name "nephronectin") 
("neurites" "ONT:CELL-PART" :id "GO:0043005" :name "neuron projection") 
("neuroblasts" "ONT:CELL" :id "CO:0000031" :name "neuroblast") 
("neurofibromas" "ONT:CANCER" :id "EFO:0000622" :name "neurofibroma") 
("neurofilaments" "ONT:CELL-PART" :id "GO:0005883" :name "neurofilament") 
("neurotoxicant" "ONT:CHEMICAL" :id "CHEBI:50910" :name "neurotoxin") 
("neurotoxins" "ONT:PROTEIN" :id "UP:P83108" :name "Neurotoxin") 
("neurotransmitters" "ONT:CHEMICAL" :id "CHEBI:25512" :name "neurotransmitter") 
("nevi" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000625" :name "nevus") 
("nicorandil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C84012" :name "nicorandil") 
("nitrocellulose" "ONT:CHEMICAL" :id "CHEBI:53325" :name "nitrocellulose") 
("nitrotyrosine" "ONT:CHEMICAL" :id "CHEBI:86267" :name "nitrotyrosine") 
("nitroxoline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72634" :name "nitroxoline") 
("nitroxyl" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C039900" :name "nitroxyl") 
("non-" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14460" :name "NON mouse") 
("nonylphenol" "ONT:MOLECULE" :id "CHEBI:79516" :name "Nonylphenol") 
("noscapine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C80589" :name "noscapine") 
("novobiocin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C705" :name "novobiocin") 
("nucleoli" "ONT:CELL-PART" :id "UP:SL-0188" :name "Nucleolus") 
("nucleophosmin" "ONT:GENE-PROTEIN" :id "HGNC:7910" :name "nucleophosmin") 
("nucleoporins" "ONT:PROTEIN" :id "NCIT:C21183" :name "nucleoporin") 
("nucleosides" "ONT:MOLECULE" :id "CHEBI:33838" :name "nucleoside") 
("obatoclax" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C520962" :name "obatoclax") 
("ofa" "ONT:PROTEIN" :id "UP:Q51330" :name "Oxalate:formate antiporter") 
("ogen" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47521" :name "estropipate") 
("olanzapine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47639" :name "olanzapine") 
("oleate" "ONT:CHEMICAL" :id "CHEBI:30823" :name "oleate") 
("oligodendrocytes" "ONT:CELL" :id "BTO:0000962" :name "oligodendrocyte") 
("oligodendroglia" "ONT:CELL" :id "BTO:0000770" :name "oligodendroglia") 
("oligomer" "ONT:MOLECULE" :id "CHEBI:132554" :name "oligomer") 
("oligonucleotides" "ONT:MOLECULE" :id "CHEBI:7754" :name "oligonucleotide") 
("oligopeptides" "ONT:MOLECULE" :id "CHEBI:25676" :name "oligopeptide") 
("omentin" "ONT:PROTEIN" :id "NCIT:C124078" :name "intelectin-1") 
("oncoproteins" "ONT:PROTEIN" :id "NCIT:C16934" :name "oncoprotein") 
("orlistat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29303" :name "orlistat") 
("ort" "ONT:CELL-LINE" :id "CVCL:N815" :name "ORT") 
("orthovanadate" "ONT:CHEMICAL" :id "CHEBI:46442" :name "vanadate(3-)") 
("osteocytes" "ONT:CELL" :id "BTO:0002038" :name "osteocyte") 
("osthole" "ONT:CHEMICAL" :id "CHEBI:69832" :name "osthole") 
("ovine" "ONT:NONHUMAN-ANIMAL" :id "NCIT:C14273" :name "sheep") 
("oxindoles" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C508198" :name "oxindole") 
("oxotremorine" "ONT:MOLECULE" :id "CHEBI:7851" :name "Oxotremorine") 
("p21 protein" "ONT:PROTEIN" :id "UP:P12356" :name "Photosystem I reaction center subunit III, chloroplastic") 
("p21 proteins" "ONT:PROTEIN" :id "UP:P12356" :name "Photosystem I reaction center subunit III, chloroplastic") 
("p38 alpha" "ONT:GENE" :id "NCIT:C51219" :name "MAPK14") 
("p38alpha" "ONT:GENE" :id "NCIT:C51219" :name "MAPK14") 
("palladin" "ONT:PROTEIN" :id "UP:Q8WX93" :name "Palladin") 
("pancortin" "ONT:PROTEIN" :id "UP:Q9IAK4" :name "Noelin") 
("panobinostat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C496932" :name "panobinostat") 
("papillomaviruses" "ONT:VIRUS" :id "NCIT:C14251" :name "papillomavirus") 
("parabens" "ONT:MOLECULE" :id "CHEBI:85122" :name "paraben") 
("parecoxib" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C66318" :name "parecoxib") 
("pargyline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C66322" :name "pargyline") 
("paricalcitol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C084656" :name "paricalcitol") 
("parvalbumin" "ONT:GENE-PROTEIN" :id "HGNC:9704" :name "parvalbumin") 
("parvovirus" "ONT:VIRUS" :id "NCIT:C14299" :name "parvovirus") 
("pentapeptide" "ONT:MOLECULE" :id "CHEBI:48545" :name "pentapeptide") 
("pentoxifylline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C733" :name "pentoxifylline") 
("pepstatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C96295" :name "pepstatin") 
("percentile" "ONT:PROCEDURE" :id "NCIT:C48919" :name "percentile") 
("peroxisomes" "ONT:CELL-PART" :id "UP:SL-0204" :name "Peroxisome") 
("pexophagy" "ONT:BIOLOGICAL-PROCESS" :id "GO:0030242" :name "pexophagy") 
("phage" "ONT:VIRUS" :id "NCIT:C14188" :name "bacteriophage") 
("phagosome" "ONT:CELL-PART" :id "UP:SL-0206" :name "Phagosome") 
("phagosomes" "ONT:CELL-PART" :id "UP:SL-0206" :name "Phagosome") 
("phenanthroline" "ONT:MOLECULE" :id "CHEBI:36417" :name "phenanthroline") 
("pheno" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C739" :name "phenobarbital") 
("phenoxazines" "ONT:MOLECULE" :id "CHEBI:25970" :name "phenoxazine") 
("phleomycin" "ONT:CHEMICAL" :id "CHEBI:75044" :name "phleomycin") 
("phloretin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:17276" :name "phloretin") 
("phloroglucinol" "ONT:CHEMICAL" :id "CHEBI:16204" :name "phloroglucinol") 
("phosphatidylglycerol" "ONT:CHEMICAL" :id "CHEBI:17517" :name "phosphatidylglycerol") 
("phosphoantigen" "ONT:CHEMICAL" :id "CHEBI:59544" :name "phosphoantigen") 
("phosphoantigens" "ONT:CHEMICAL" :id "CHEBI:59544" :name "phosphoantigen") 
("phosphocreatine" "ONT:CHEMICAL" :id "CHEBI:17287" :name "N-phosphocreatine") 
("phosphoryl" "ONT:MOLECULE" :id "CHEBI:29315" :name "phosphoryl") 
("photofrin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1377" :name "hematoporphyrin derivative") 
("physalin" "ONT:CHEMICAL" :id "CHEBI:76361" :name "physalin") 
("phytoestrogen" "ONT:CHEMICAL" :id "CHEBI:76989" :name "phytoestrogen") 
("phytoestrogens" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1194" :name "phytoestrogen") 
("picornaviruses" "ONT:VIRUS" :id "NCIT:C14256" :name "picornavirus") 
("piebaldism" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C85009" :name "piebaldism") 
("pilocarpine" "ONT:MOLECULE" :id "CHEBI:39462" :name "pilocarpine") 
("pirenzepine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76002" :name "pirenzepine") 
("plas" "ONT:PROTEIN" :id "UP:A1CFS2" :name "Probable pectin lyase A") 
("plasmablasts" "ONT:CELL" :id "CO:0000980" :name "plasmablast") 
("plasmalemma" "ONT:CELL-PART" :id "GO:0005886" :name "plasma membrane") 
("plumbagin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C014758" :name "plumbagin") 
("pneumocytes" "ONT:CELL" :id "CO:0000322" :name "pneumocyte") 
("pneumolysin" "ONT:PROTEIN" :id "UP:Q04IN8" :name "Pneumolysin") 
("pols" "ONT:GENE-PROTEIN" :id "UP:P03261" :name "DNA polymerase") 
("polyneuropathy" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26951" :name "polyneuropathy") 
("polysome" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0005844" :name "polysome") 
("polysomes" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0005844" :name "polysome") 
("presenilins" "ONT:PROTEIN-FAMILY" :id "XFAM:PF01080.15" :name "presenilin") 
("preset" "ONT:PROTEIN-FAMILY" :id "XFAM:PF05033.14" :name "pre-SET") 
("probasin" "ONT:PROTEIN" :id "UP:O08976" :name "Probasin") 
("procyanidin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C017674" :name "procyanidin") 
("prodigiosin" "ONT:CHEMICAL" :id "CHEBI:82758" :name "prodigiosin") 
("prodrugs" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:50266" :name "prodrug") 
("progestogen" "ONT:CHEMICAL" :id "CHEBI:50745" :name "progestogen") 
("propionitrile" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C005557" :name "propionitrile") 
("propofol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29384" :name "propofol") 
("prostanoids" "ONT:MOLECULE" :id "CHEBI:26347" :name "prostanoid") 
("protoporphyrins" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C785" :name "protoporphyrin") 
("protrudin" "ONT:PROTEIN" :id "UP:Q5T4F4" :name "Protrudin") 
("pseudopod" "ONT:CELL-PART" :id "GO:0031143" :name "pseudopodium") 
("pseudopods" "ONT:CELL-PART" :id "GO:0031143" :name "pseudopodium") 
("pterygia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0000678" :name "pterygium") 
("purvalanol" "ONT:MOLECULE" :id "CHEBI:38934" :name "purvalanol") 
("pyocyanin" "ONT:MOLECULE" :id "CHEBI:62220" :name "pyocyanin") 
("pyrazolopyrimidine" "ONT:MOLECULE" :id "CHEBI:38669" :name "pyrazolopyrimidine") 
("pyridone" "ONT:MOLECULE" :id "CHEBI:38183" :name "pyridone") 
("pyridopyrimidine" "ONT:MOLECULE" :id "CHEBI:38932" :name "pyridopyrimidine") 
("pyrimidines" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C030986" :name "pyrimidine") 
("pyrimidones" "ONT:MOLECULE" :id "CHEBI:38337" :name "pyrimidone") 
("pyrithione" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61916" :name "pyrithione") 
("pyrone" "ONT:MOLECULE" :id "CHEBI:37963" :name "pyranone") 
("pyrrolidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C032519" :name "pyrrolidine") 
("quercetagetin" "ONT:CHEMICAL" :id "CHEBI:8695" :name "quercetagetin") 
("quinazoline" "ONT:MOLECULE" :id "CHEBI:36621" :name "quinazoline") 
("radicicol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1462" :name "radicicol") 
("rapsyn" "ONT:GENE-PROTEIN" :id "UP:Q09485" :name "43 kDa receptor-associated protein of the synapse homolog") 
("resazurin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C005843" :name "resazurin") 
("resibufogenin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77829" :name "bufogenin") 
("reversine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:70723" :name "reversine") 
("rhinitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C34986" :name "rhinitis") 
("ribosomes" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0005840" :name "ribosome") 
("ribozyme" "ONT:RNA" :id "NCIT:C1292" :name "ribozyme") 
("riluzole" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47704" :name "riluzole") 
("ritonavir" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1609" :name "ritonavir") 
("rivaroxaban" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C77995" :name "rivaroxaban") 
("rolipram" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C72842" :name "rolipram") 
("rootletin" "ONT:GENE-PROTEIN" :id "UP:Q5TZA2" :name "Rootletin") 
("roscovitine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C104586" :name "roscovitine") 
("rotavirus" "ONT:VIRUS" :id "NCIT:C77199" :name "rotavirus") 
("rpts" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF13446.4" :name "RPT") 
("salbutamol" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:2549" :name "albuterol") 
("salinomycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C76430" :name "salinomycin") 
("salsalate" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C62636" :name "salsalate") 
("sangivamycin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C005699" :name "sangivamycin") 
("sarafotoxin" "ONT:PROTEIN" :id "UP:P13208" :name "Sarafotoxin") 
("sarcolemma" "ONT:CELL-PART" :id "UP:SL-0238" :name "Sarcolemma") 
("sarcopenia" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1000653" :name "sarcopenia") 
("sarkosyl" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C025231" :name "sarkosyl") 
("satraplatin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1493" :name "satraplatin") 
("schisandrin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C011105" :name "schizandrin") 
("scoparone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C018145" :name "scoparone") 
("scytonemin" "ONT:CHEMICAL" :id "CHEBI:90127" :name "scytonemin") 
("selegiline" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61938" :name "selegiline") 
("selenite" "ONT:MOLECULE" :id "CHEBI:48839" :name "selenite gypsum") 
("sepharose" "ONT:CHEMICAL" :id "CHEBI:2511" :name "agarose") 
("seribantumab" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C78859" :name "anti-erbB3 receptor monoclonal antibody MM-121") 
("serin" "ONT:CHEMICAL" :id "CHEBI:17822" :name "serine") 
("shelterin" "ONT:PROTEIN" :id "NCIT:C118795" :name "shelterin") 
("signalosomes" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0008180" :name "COP9 signalosome") 
("silibinin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:9144" :name "silibinin") 
("sirtuins" "ONT:PROTEIN-FAMILY" :id "FA:03623" :name "sirtuin family") 
("sml" "ONT:CELL-LINE" :id "CVCL:6446" :name "SML, clone 4D8") 
("somatotroph" "ONT:CELL" :id "CO:0002312" :name "somatotroph") 
("sorbinil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C97357" :name "sorbinil") 
("sorcin" "ONT:GENE-PROTEIN" :id "HGNC:11292" :name "sorcin") 
("spartin" "ONT:PROTEIN" :id "UP:A0JNJ3" :name "Spartin") 
("spermatids" "ONT:CELL" :id "CO:0000018" :name "spermatid") 
("sphingolipids" "ONT:MOLECULE" :id "CHEBI:26739" :name "sphingolipid") 
("spironolactone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C840" :name "spironolactone") 
("spliceosomes" "ONT:MACROMOLECULAR-COMPLEX" :id "GO:0005681" :name "spliceosomal complex") 
("statins" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1655" :name "HMG-CoA reductase inhibitor") 
("staurosporin" "ONT:CHEMICAL" :id "CHEBI:15738" :name "staurosporine") 
("stearate" "ONT:CHEMICAL" :id "CHEBI:25629" :name "stearate") 
("steatohepatitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:0003934" :name "fatty liver") 
("streptozotocin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C845" :name "streptozocin") 
("sulfasalazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C29469" :name "sulfasalazine") 
("sulfinyl" "ONT:MOLECULE" :id "CHEBI:29822" :name "sulfinyl group") 
("sulindac" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C850" :name "sulindac") 
("sulphone" "ONT:MOLECULE" :id "CHEBI:35850" :name "sulfone") 
("suprabasin" "ONT:GENE-PROTEIN" :id "HGNC:24950" :name "suprabasin") 
("synemin" "ONT:GENE-PROTEIN" :id "HGNC:24466" :name "synemin") 
("synoretin" "ONT:PROTEIN" :id "NCIT:C21218" :name "synuclein gamma") 
("synovitis" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C50766" :name "synovitis") 
("tanshinone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C021751" :name "tanshinone") 
("taurolidine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2639" :name "taurolidine") 
("taus" "ONT:GENE-PROTEIN" :id "NCIT:C75652" :name "microtubule-associated protein tau") 
("tautomycin" "ONT:MOLECULE" :id "CHEBI:9414" :name "Tautomycin") 
("telogen" "ONT:TIME-SPAN" :id "GO:0042639" :name "telogen") 
("temsirolimus" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C401859" :name "temsirolimus") 
("tendinopathy" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "EFO:1001434" :name "Tendinopathy") 
("tenocytes" "ONT:CELL" :id "CO:0000388" :name "tendon cell") 
("terpenoids" "ONT:MOLECULE" :id "CHEBI:26873" :name "terpenoid") 
("tetrapeptide" "ONT:MOLECULE" :id "CHEBI:48030" :name "tetrapeptide") 
("tetrapeptides" "ONT:MOLECULE" :id "CHEBI:48030" :name "tetrapeptide") 
("tetraploidy" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "ORPHANET:3305" :name "Tetraploidy") 
("theaflavin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C056068" :name "theaflavin") 
("thermolysin" "ONT:PROTEIN" :id "UP:Q43880" :name "Thermolysin") 
("thiazolidinedione" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C089946" :name "2,4-thiazolidinedione") 
("thiols" "ONT:MOLECULE" :id "CHEBI:29256" :name "thiol") 
("thioridazine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C61971" :name "thioridazine") 
("thiostrepton" "ONT:PROTEIN" :id "UP:P0C8P8" :name "Thiostrepton") 
("thromboses" "ONT:MEDICAL-DISORDERS-AND-CONDITIONS" :id "NCIT:C26891" :name "thrombosis") 
("thyrocytes" "ONT:CELL" :id "BTO:0003736" :name "thyroid epithelial cell") 
("tobe" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF03459.15" :name "TOBE") 
("topotecan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1413" :name "topotecan") 
("tori" "ONT:MOLECULAR-DOMAIN" :id "XFAM:PF16131.3" :name "torus") 
("tran" "ONT:PROTEIN-FAMILY" :id "XFAM:PF06986.9" :name "TraN") 
("transportin" "ONT:PROTEIN" :id "UP:Q55CQ7" :name "Transportin") 
("trapoxin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1665" :name "trapoxin") 
("triapine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C2242" :name "triapine") 
("trichostatin" "ONT:CHEMICAL" :id "CHEBI:39146" :name "trichostatin") 
("triciribine" "ONT:CHEMICAL" :id "CHEBI:65310" :name "triciribine") 
("triglyceride" "ONT:CHEMICAL" :id "CHEBI:17855" :name "triglyceride") 
("triglycerides" "ONT:CHEMICAL" :id "CHEBI:17855" :name "triglyceride") 
("tripeptide" "ONT:MOLECULE" :id "CHEBI:47923" :name "tripeptide") 
("troglitazone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1522" :name "troglitazone") 
("tropism" "ONT:BIOLOGICAL-PROCESS" :id "GO:0009606" :name "tropism") 
("troponins" "ONT:PROTEIN-FAMILY" :id "XFAM:PF00992.18" :name "troponin") 
("tubacin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C474316" :name "tubacin") 
("tylophorine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C004218" :name "tylophorine") 
("ureido" "ONT:MOLECULE" :id "CHEBI:48349" :name "carbamoylamino group") 
("uropod" "ONT:CELL-PART" :id "GO:0001931" :name "uropod") 
("uropods" "ONT:CELL-PART" :id "GO:0001931" :name "uropod") 
("valproate" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "CHEBI:60654" :name "valproate") 
("valsartan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C47781" :name "valsartan") 
("varicosities" "ONT:CELL-PART" :id "GO:0043196" :name "varicosity") 
("verapamil" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C928" :name "verapamil") 
("vernodalin" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C465365" :name "vernodalin") 
("virions" "ONT:CELL-PART" :id "UP:SL-0274" :name "Virion") 
("vit" "ONT:GENE-PROTEIN" :id "HGNC:12697" :name "vitrin") 
("volasertib" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C79844" :name "polo-like kinase 1 inhibitor BI 6727") 
("wafl" "ONT:GENE-PROTEIN" :id "HGNC:23397" :name "FK506 binding protein 15") 
("wedelolactone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C051122" :name "wedelolactone") 
("xenoestrogens" "ONT:CHEMICAL" :id "CHEBI:76988" :name "xenoestrogen") 
("zebularine" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C37455" :name "zebularine") 
("zerumbone" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "MESH:C403304" :name "zerumbone") 
("zibotentan" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C48430" :name "ZD4054") 
("zinedin" "ONT:GENE-PROTEIN" :id "HGNC:15721" :name "striatin 4") 
("zoledronate" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C1699" :name "zoledronate") 
("zopolrestat" "ONT:PHARMACOLOGIC-SUBSTANCE" :id "NCIT:C82174" :name "zopolrestat") 
