
(define-protein "Akt1" ("HGNC:391" "AKT serine/threonine kinase 1")) 
(define-protein "Bax" ("HGNC:959" "BCL2 associated X, apoptosis regulator")) 
(define-protein "CDK2" ("HGNC:1771" "cyclin dependent kinase 2")) 
(define-protein "CUL4A" ("HGNC:2554" "cullin 4A")) 
(define-protein "Cdc2" ("NCIT:C49452" "CDC2")) 
(define-protein "Delta" ("NCIT:C106586" "delta-like protein-1")) 
(define-protein "EBPs" ("HGNC:3133" "emopamil binding protein (sterol isomerase)")) 
(define-protein "GCE" ("UP:P55203" "Retinal guanylyl cyclase 1")) 
(define-protein "IGF-IR" ("NCIT:C51548" "IGF1R")) 
(define-protein "IGF1R" ("HGNC:5465" "insulin like growth factor 1 receptor")) 
(define-protein "IGFR" ("NCIT:C51548" "IGF1R")) 
(define-protein "Ku-70" ("FA:02002" "Ku70 family")) 
(define-protein "Lats1" ("HGNC:6514" "large tumor suppressor kinase 1")) 
(define-protein "MEKK1" ("NCIT:C50392" "MAP3K1")) 
(define-protein "MKK1" ("UP:Q02750" "Dual specificity mitogen-activated protein kinase kinase 1")) 
(define-protein "MMP-2" ("HGNC:7166" "matrix metallopeptidase 2")) 
(define-protein "MSK1" ("NCIT:C51319" "RPS6KA5")) 
(define-protein "PDP1" ("HGNC:9279" "pyruvate dehyrogenase phosphatase catalytic subunit 1")) 
(define-protein "PLA" ("UP:A1CFS2" "Probable pectin lyase A")) 
(define-protein "ROCK1" ("HGNC:10251" "Rho associated coiled-coil containing protein kinase 1")) 
(define-protein "ROS" ("HGNC:10261" "ROS proto-oncogene 1, receptor tyrosine kinase")) 
(define-protein "RagA" ("NCIT:C52614" "RRAGA")) 
(define-protein "RagC" ("UP:Q9HB90" "Ras-related GTP-binding protein C")) 
(define-protein "SSTR1" ("HGNC:11330" "somatostatin receptor 1")) 
(define-protein "STAT1" ("HGNC:11362" "signal transducer and activator of transcription 1")) 
(define-protein "SUMO2" ("HGNC:11125" "small ubiquitin-like modifier 2")) 
(define-protein "Smad1" ("HGNC:6767" "SMAD family member 1")) 
(define-protein "Smad2" ("HGNC:6768" "SMAD family member 2")) 
(define-protein "Smad6" ("HGNC:6772" "SMAD family member 6")) 
(define-protein "Smurf1" ("HGNC:16807" "SMAD specific E3 ubiquitin protein ligase 1")) 
(define-protein "Ulk1" ("HGNC:12558" "unc-51 like autophagy activating kinase 1")) 
(define-protein "Wnt-5a" ("HGNC:12784" "Wnt family member 5A")) 
(define-protein "ZEB1" ("HGNC:11642" "zinc finger E-box binding homeobox 1")) 
(define-protein "cdc2" ("NCIT:C49452" "CDC2")) 
(define-protein "hChlR1" ("UP:Q96FC9" "Probable ATP-dependent DNA helicase DDX11 {ECO:0000305}")) 
(define-protein "kalirin" ("UP:O60229" "Kalirin")) 
(define-protein "p42" ("HGNC:21420" "cyclin dependent kinase 20")) 
(define-protein "p44" ("UP:Q8TCB0" "Interferon-induced protein 44")) 
(define-protein "sGC" ("NCIT:C20141" "soluble guanylate cyclase")) 