;;; -*- Mode:LISP; Syntax:Common-Lisp; Package:(SPARSER COMMON-LISP) -*-
;;; Copyright (c) 2014-2015 SIFT LLC. All Rights Reserved
;;;
;;;    File: "RAS2-proteins"
;;;  Module: "grammar/model/sl/biology/
;;; version: June 2015

;; Definitions of all (and only) the proteins from the MITRE RAS2 model

(in-package :sparser)
(define-protein "1433E_HUMAN" ("14-3-3E" "YWHAE")) 
(define-protein "1433F_HUMAN" ("YWHAH" "YWHA1")) 
(define-protein "1433G_HUMAN" ("YWHAG" "KCIP-1")) 
(define-protein "1433Z_HUMAN" ("YWHAZ" "KCIP-1")) 
(define-protein "1A80_HUMAN" ("HLA-A" "Aw-80" "HLAA")) 
(define-protein "1B38_HUMAN" ("Bw-4" "HLA-B" "HLAB")) 
(define-protein "1B38_HUMAN" ("MHC class I antigen B*38" "Bw-4" "HLA-B" "HLAB")) 
(define-protein "1B40_HUMAN" ("HLA-B" "Bw-60" "HLAB")) 
(define-protein "1B59_HUMAN" ("HLA-B" "HLAB")) 
(define-protein "1B67_HUMAN" ("HLA-B" "HLAB")) 
(define-protein "1B73_HUMAN" ("HLA-B" "HLAB")) 
(define-protein "1B81_HUMAN" ("B'DT" "HLA-B" "HLAB")) 
(define-protein "1B82_HUMAN" ("HLA-B" "HLAB")) 
(define-protein "1C05_HUMAN" ("HLA-C" "HLAC")) 
(define-protein "1C05_HUMAN" ("MHC class I antigen Cw*5" "HLA-C" "HLAC")) 
(define-protein "1C06_HUMAN" ("HLA-C" "HLAC")) 
(define-protein "1C15_HUMAN" ("HLA-C" "HLAC")) 
(define-protein "1C16_HUMAN" ("HLA-C" "HLAC")) 
(define-protein "1C17_HUMAN" ("D6S204" "HLA-JY3" "HLA-C" "HLAC")) 
(define-protein "1C17_HUMAN" ("D6S204" "MHC class I antigen Cw*17" "HLA-JY3" "HLA-C" "HLAC")) 
(define-protein "1C18_HUMAN" ("HLA-C" "HLAC")) 
(define-protein "ABI1_HUMAN" ("ABI1" "e3B1" "Nap1BP" "Abi-1" "SSH3BP1" "AblBP4")) 
(define-protein "ABI2_HUMAN" ("Abi-2" "Abelson interactor 2" "ArgBP1" "Arg-binding protein 1" "ABI2" "ARGBPIA" "AblBP3" "Abl-binding protein 3")) 
(define-protein "ABI2_HUMAN" ("Abi-2" "ArgBP1" "ABI2" "ARGBPIA" "AblBP3")) 
(define-protein "ABR_HUMAN" ("ABR")) 
(define-protein "ACTBM_HUMAN" ("ACTBL3" "POTEKP" "Kappa-actin" "POTE ankyrin domain family member K")) 
(define-protein "ACTBM_HUMAN" ("ACTBL3" "POTEKP" "Kappa-actin")) 
(define-protein "ACV1C_HUMAN" ("ACTR-IC" "ALK-7" "2.7.11.30" "ALK7" "ACVR1C")) 
(define-protein "ACVR1_HUMAN" ("SKR1" "ACVRLK2" "TSR-I" "2.7.11.30" "ALK-2" "ACTR-I" "ACVR1")) 
(define-protein "ADA17_HUMAN" ("CSVP" "TACE" "3.4.24.86" "ADAM17" "CD156b")) 
(define-protein "AKAP9_HUMAN" ("KIAA0803" "AKAP9" "PRKA9" "AKAP350" "CG-NAP" "AKAP-9" "AKAP450")) 
(define-protein "AKAP9_HUMAN" ("KIAA0803" "Protein yotiao" "AKAP9" "PRKA9" "AKAP350" "Centrosome- and Golgi-localized PKN-associated protein" "CG-NAP" "A-kinase anchor protein 450 kDa" "Protein kinase A-anchoring protein 9" "hgAKAP 350" "A-kinase anchor protein 350 kDa" "AKAP 450" "AKAP 120-like protein" "AKAP-9" "AKAP450" "Protein hyperion" "AKAP 350")) 
(define-protein "AKP13_HUMAN" ("PRKA13" "AKAP-13" "AKAP13" "HT31" "LBC" "p47" "AKAP-Lbc" "BRX")) 
(define-protein "AKT3_HUMAN" ("PKBG" "RAC-PK-gamma" "2.7.11.1" "STK-2" "AKT3")) 
(define-protein "AKT3_HUMAN" ("Protein kinase B gamma" "PKBG" "Protein kinase Akt-3" "RAC-PK-gamma" "2.7.11.1" "STK-2" "PKB gamma" "AKT3")) 
(define-protein "AMHR2_HUMAN" ("AMHR2" "MISR2" "MRII" "MISRII" "2.7.11.30" "AMHR")) 
(define-protein "ANGP1_HUMAN" ("ANG-1" "ANGPT1" "KIAA0003")) 
(define-protein "AOC3_HUMAN" ("HPAO" "VAP1" "1.4.3.21" "VAP-1" "SSAO" "AOC3")) 
(define-protein "ARAP3_HUMAN" ("Centaurin-delta-3" "Cnt-d3" "CENTD3" "ARAP3")) 
(define-protein "ARF1_HUMAN" ("ARF1")) 
(define-protein "ARF5_HUMAN" ("ARF5")) 
(define-protein "ARF6_HUMAN" ("ARF6")) 
(define-protein "ARG28_HUMAN" ("p190-RhoGEF" "KIAA1998" "p190RhoGEF" "ARHGEF28" "RGNEF")) 
(define-protein "ARGAL_HUMAN" ("GRINCHGEF" "KIAA1626" "ARHGEF10L" "GrinchGEF")) 
(define-protein "ARHG1_HUMAN" ("p115RhoGEF" "p115-RhoGEF" "ARHGEF1" "Sub1.5" "115 kDa guanine nucleotide exchange factor")) 
(define-protein "ARHG1_HUMAN" ("p115RhoGEF" "p115-RhoGEF" "ARHGEF1" "Sub1.5")) 
(define-protein "ARHG2_HUMAN" ("ARHGEF2" "GEF-H1" "LFP40" "KIAA0651")) 
(define-protein "ARHG2_HUMAN" ("ARHGEF2" "Guanine nucleotide exchange factor H1" "GEF-H1" "LFP40" "Microtubule-regulated Rho-GEF" "Proliferating cell nucleolar antigen p40" "KIAA0651")) 
(define-protein "ARHG3_HUMAN" ("ARHGEF3" "Exchange factor found in platelets and leukemic and neuronal tissues" "XPLN")) 
(define-protein "ARHG3_HUMAN" ("ARHGEF3" "XPLN")) 
(define-protein "ARHG4_HUMAN" ("ARHGEF4" "Asef1" "APC-stimulated guanine nucleotide exchange factor 1" "KIAA1112" "Asef")) 
(define-protein "ARHG4_HUMAN" ("ARHGEF4" "Asef1" "KIAA1112" "Asef")) 
(define-protein "ARHG5_HUMAN" ("TIM" "ARHGEF5" "Ephexin-3")) 
(define-protein "ARHG6_HUMAN" ("ARHGEF6" "COOL2" "Alpha-Pix" "PIXA" "KIAA0006" "COOL-2")) 
(define-protein "ARHG7_HUMAN" ("P85SPR" "ARHGEF7" "p85" "PIXB" "COOL-1" "COOL1" "KIAA0142" "Beta-Pix" "PAK3BP")) 
(define-protein "ARHG8_HUMAN" ("ARHGEF8" "NET1")) 
(define-protein "ARHGC_HUMAN" ("LARG" "ARHGEF12" "KIAA0382")) 
(define-protein "ARHGC_HUMAN" ("Leukemia-associated RhoGEF" "LARG" "ARHGEF12" "KIAA0382")) 
(define-protein "ARHGG_HUMAN" ("NBR" "ARHGEF16" "Ephexin-4" "EPHEXIN4")) 
(define-protein "ARHGH_HUMAN" ("p164RhoGEF" "TEM4" "Tumor endothelial marker 4" "p164-RhoGEF" "ARHGEF17" "KIAA0337" "164 kDa Rho-specific guanine-nucleotide exchange factor")) 
(define-protein "ARHGH_HUMAN" ("p164RhoGEF" "TEM4" "p164-RhoGEF" "ARHGEF17" "KIAA0337")) 
(define-protein "ARHGI_HUMAN" ("KIAA0521" "ARHGEF18" "SA-RhoGEF" "p114-Rho-GEF" "p114RhoGEF")) 
(define-protein "ARHGP_HUMAN" ("p63RhoGEF" "ARHGEF25" "GEFT")) 
(define-protein "ATRIP_HUMAN" ("AGS1" "ATRIP")) 
(define-protein "ATR_HUMAN" ("2.7.11.1" "ATR" "FRP1")) 
(define-protein "AVR2B_HUMAN" ("ACVR2B" "2.7.11.30" "ACTR-IIB")) 
(define-protein "B2CL1_HUMAN" ("Bcl2-L-1" "BCLX" "BCL2L" "BCL2L1")) 
(define-protein "B2MG_HUMAN" ("B2M")) 
(define-protein "BAD_HUMAN" ("BCL2L8" "BBC6" "Bcl2-L-8" "BAD")) 
(define-protein "BAD_HUMAN" ("Bcl2 antagonist of cell death" "BCL2L8" "BBC6" "Bcl-2-like protein 8" "Bcl-2-binding component 6" "Bcl2-L-8" "BAD" "Bcl-xL/Bcl-2-associated death promoter")) 
(define-protein "BAMBI_HUMAN" ("NMA" "BAMBI")) 
(define-protein "BLNK_HUMAN" ("SLP-65" "SLP65" "BASH" "BLNK")) 
(define-protein "BMP8A_HUMAN" ("BMP-8A" "BMP8A")) 
(define-protein "BMPR2_HUMAN" ("BMPR2" "PPH1" "2.7.11.30" "BMPR-II" "BMPR-2")) 
(define-protein "BRK1_HUMAN" ("BRK1" "C3orf10")) 
(define-protein "BRPF3_HUMAN" ("BRPF3" "KIAA1286")) 
(define-protein "BTK_HUMAN" ("BPK" "AGMX1" "ATK" "2.7.10.2" "BTK")) 
(define-protein "CABIN_HUMAN" ("KIAA0330" "CABIN1" "CAIN")) 
(define-protein "CABIN_HUMAN" ("KIAA0330" "Calcineurin inhibitor" "CABIN1" "CAIN")) 
(define-protein "CABL1_HUMAN" ("Ik3-1" "CABLES" "CABLES1")) 
(define-protein "CALM_HUMAN" ("CAM" "CaM" "CAM1" "CAM2" "CAM3" "CALM" "CALML2" "CAMIII" "CALM3" "CAMB" "CAMC" "CALM2" "CALM1")) 
(define-protein "CDC37_HUMAN" ("CDC37A" "p50Cdc37" "CDC37")) 
(define-protein "CDC42_HUMAN" ("CDC42")) 
(define-protein "CE164_HUMAN" ("Cep164" "NPHP15" "CEP164" "KIAA1052")) 
(define-protein "CIR1_HUMAN" ("CIR1" "Recepin" "CIR")) 
(define-protein "CLSPN_HUMAN" ("CLSPN" "hClaspin")) 
(define-protein "CP1B1_HUMAN" ("CYP1B1" "CYPIB1" "1.14.14.1")) 
(define-protein "CXCL9_HUMAN" ("CXCL9" "CMK" "HuMIG" "SCYB9" "MIG")) 
(define-protein "CXCR4_HUMAN" ("Fusin" "LAP-3" "CXCR-4" "CD184" "NPYRL" "LESTR" "LCR1" "CXCR4" "CXC-R4" "HM89" "FB22")) 
(define-protein "CYFP2_HUMAN" ("PIR121" "KIAA1168" "CYFIP2")) 
(define-protein "CYFP2_HUMAN" ("p53-inducible protein 121" "PIR121" "KIAA1168" "CYFIP2")) 
(define-protein "CYH1_HUMAN" ("PSCD1" "CYTH1" "D17S811E")) 
(define-protein "CYH2_HUMAN" ("ARF exchange factor" "PSCD2" "PSCD2L" "Protein ARNO" "PH, SEC7 and coiled-coil domain-containing protein 2" "CYTH2" "ARNO" "ARF nucleotide-binding site opener")) 
(define-protein "CYH2_HUMAN" ("PSCD2" "PSCD2L" "CYTH2" "ARNO")) 
(define-protein "DAAM1_HUMAN" ("DAAM1" "KIAA0666")) 
(define-protein "DAB2P_HUMAN" ("AF9Q34" "DAB2IP" "KIAA1743" "AIP-1" "AIP1")) 
(define-protein "DAPP1_HUMAN" ("B lymphocyte adapter protein Bam32" "DAPP1" "hDAPP1" "B-cell adapter molecule of 32 kDa" "BAM32")) 
(define-protein "DAPP1_HUMAN" ("DAPP1" "hDAPP1" "BAM32")) 
(define-protein "DEFI6_HUMAN" ("DEF6" "IBP" "DEF-6")) 
(define-protein "DEFI6_HUMAN" ("IRF4-binding protein" "DEF6" "IBP" "DEF-6")) 
(define-protein "DHB12_HUMAN" ("1.3.1.-" "HSD17B12" "KAR" "1.1.1.62")) 
(define-protein "DLG4_HUMAN" ("SAP-90" "PSD-95" "DLG4" "PSD95" "SAP90")) 
(define-protein "DLK1_HUMAN" ("DLK-1" "FA1" "pG2" "DLK1" "DLK")) 
(define-protein "DLL3_HUMAN" ("DLL3" "Delta3")) 
(define-protein "DLL3_HUMAN" ("DLL3" "Drosophila Delta homolog 3" "Delta3")) 
(define-protein "DLL4_HUMAN" ("DLL4" "Delta4")) 
(define-protein "DLL4_HUMAN" ("Drosophila Delta homolog 4" "DLL4" "Delta4")) 
(define-protein "DNMBP_HUMAN" ("KIAA1010" "DNMBP")) 
(define-protein "DOC10_HUMAN" ("ZIZ3" "Zizimin-3" "KIAA0694" "DOCK10")) 
(define-protein "DOC11_HUMAN" ("Zizimin-2" "ACG" "DOCK11" "ZIZ2")) 
(define-protein "DOCK1_HUMAN" ("DOCK1" "DOCK180")) 
(define-protein "DOCK2_HUMAN" ("DOCK2" "KIAA0209")) 
(define-protein "DOCK6_HUMAN" ("KIAA1395" "DOCK6")) 
(define-protein "DOCK9_HUMAN" ("KIAA1058" "DOCK9" "Cdc42 guanine nucleotide exchange factor zizimin-1")) 
(define-protein "DOCK9_HUMAN" ("KIAA1058" "DOCK9")) 
(define-protein "DOK1_HUMAN" ("DOK1" "pp62" "Downstream of tyrosine kinase 1" "p62(dok)")) 
(define-protein "DOK1_HUMAN" ("DOK1" "pp62" "p62(dok)")) 
(define-protein "DVL3_HUMAN" ("DVL3" "Dishevelled-3" "DSH homolog 3" "KIAA0208")) 
(define-protein "DVL3_HUMAN" ("DVL3" "Dishevelled-3" "KIAA0208")) 
(define-protein "ECT2_HUMAN" ("ECT2")) 
(define-protein "ECT2_HUMAN" ("Epithelial cell-transforming sequence 2 oncogene" "ECT2")) 
(define-protein "EFNB1_HUMAN" ("LERK-2" "LERK2" "EFNB1" "EFL-3" "ELK-L" "EPLG2" "EFL3")) 
(define-protein "EFNB3_HUMAN" ("LERK8" "EFNB3" "EPLG8" "LERK-8")) 
(define-protein "EIF2A_HUMAN" ("65 kDa eukaryotic translation initiation factor 2A" "Eukaryotic translation initiation factor 2A, N-terminally processed" "EIF2A" "eIF-2A")) 
(define-protein "EIF2A_HUMAN" ("EIF2A" "eIF-2A")) 
(define-protein "ELMO1_HUMAN" ("KIAA0281" "ELMO1")) 
(define-protein "ELMO1_HUMAN" ("KIAA0281" "Protein ced-12 homolog" "ELMO1")) 
(define-protein "EPHA6_HUMAN" ("EPHA6" "EHK2" "EHK-2" "HEK12" "EK12" "2.7.10.1")) 
(define-protein "EPHA6_HUMAN" ("EPHA6" "EHK2" "EHK-2" "HEK12" "EPH homology kinase 2" "EK12" "EPH-like kinase 12" "2.7.10.1")) 
(define-protein "EPHA7_HUMAN" ("EPHA7" "EHK3" "HEK11" "EHK-3" "EK11" "hEK11" "2.7.10.1")) 
(define-protein "EPHAA_HUMAN" ("EPHA10" "2.7.10.1")) 
(define-protein "EPS8_HUMAN" ("EPS8")) 
(define-protein "ERBB4_HUMAN" ("p180erbB4" "ERBB4" "HER4" "4ICD" "s80HER4" "2.7.10.1" "E4ICD")) 
(define-protein "ESR2_HUMAN" ("NR3A2" "ER-beta" "ESR2" "ESTRB")) 
(define-protein "ESR2_HUMAN" ("NR3A2" "Nuclear receptor subfamily 3 group A member 2" "ER-beta" "ESR2" "ESTRB")) 
(define-protein "FAK1_HUMAN" ("FAK1" "p125FAK" "PPP1R71" "2.7.10.2" "PTK2" "FAK" "FRNK" "pp125FAK")) 
(define-protein "FAK2_HUMAN" ("FAK2" "CAK-beta" "2.7.10.2" "CADTK" "PYK2" "PTK2B" "RAFTK" "CAKB")) 
(define-protein "FARP1_HUMAN" ("PLEKHC2" "CDEP" "FARP1")) 
(define-protein "FARP1_HUMAN" ("Pleckstrin homology domain-containing family C member 2" "PLEKHC2" "PH domain-containing family C member 2" "CDEP" "Chondrocyte-derived ezrin-like protein" "FARP1")) 
(define-protein "FCERB_HUMAN" ("FcERI" "FCER1B" "APY" "MS4A2" "IGER")) 
(define-protein "FGD1_HUMAN" ("FGD1" "FGDY" "ZFYVE3")) 
(define-protein "FGD2_HUMAN" ("FGD2" "ZFYVE4")) 
(define-protein "FGD3_HUMAN" ("ZFYVE5" "FGD3")) 
(define-protein "FGD4_HUMAN" ("FGD1-related F-actin-binding protein" "ZFYVE6" "Actin filament-binding protein frabin" "Zinc finger FYVE domain-containing protein 6" "FRABP" "FGD4")) 
(define-protein "FGD4_HUMAN" ("ZFYVE6" "FRABP" "FGD4")) 
(define-protein "FGF20_HUMAN" ("FGF-20" "FGF20")) 
(define-protein "FGF22_HUMAN" ("FGF-22" "FGF22")) 
(define-protein "FGF23_HUMAN" ("Phosphatonin" "FGF23" "FGF-23" "HYPF")) 
(define-protein "FGF23_HUMAN" ("Tumor-derived hypophosphatemia-inducing factor" "Phosphatonin" "FGF23" "Fibroblast growth factor 23 N-terminal peptide" "FGF-23" "HYPF" "Fibroblast growth factor 23 C-terminal peptide")) 
(define-protein "FKB1A_HUMAN" ("FKBP-1A" "Rotamase" "FKBP1A" "FKBP-12" "Calstabin-1" "FKBP12" "5.2.1.8" "FKBP1")) 
(define-protein "FOG1_HUMAN" ("ZFN89A" "FOG1" "FOG-1" "ZFPM1")) 
(define-protein "FRS2_HUMAN" ("SNT-1" "FRS2")) 
(define-protein "FZD2_HUMAN" ("hFz2" "FZD2" "FzE2" "Fz-2")) 
(define-protein "GAB1_HUMAN" ("GAB1")) 
(define-protein "GAB2_HUMAN" ("KIAA0571" "GAB2" "pp100")) 
(define-protein "GAB2_HUMAN" ("KIAA0571" "Growth factor receptor bound protein 2-associated protein 2" "GAB2" "GRB2-associated binder 2" "pp100")) 
(define-protein "GAB3_HUMAN" ("GAB3")) 
(define-protein "GBB1_HUMAN" ("GNB1")) 
(define-protein "GBG2_HUMAN" ("GNG2")) 
(define-protein "GBLP_HUMAN" ("RACK1" "GNB2L1" "HLC-7")) 
(define-protein "GDF15_HUMAN" ("PDF" "NRG-1" "MIC-1" "NAG-1" "GDF-15" "PLAB" "MIC1" "PTGFB" "GDF15")) 
(define-protein "GDF15_HUMAN" ("PDF" "Placental TGF-beta" "Prostate differentiation factor" "NRG-1" "Placental bone morphogenetic protein" "MIC-1" "NAG-1" "GDF-15" "PLAB" "MIC1" "NSAID-regulated gene 1 protein" "NSAID-activated gene 1 protein" "PTGFB" "GDF15" "Macrophage inhibitory cytokine 1")) 
(define-protein "GDF2_HUMAN" ("GDF2" "Bone morphogenetic protein 9" "GDF-2" "BMP9" "BMP-9")) 
(define-protein "GDF2_HUMAN" ("GDF2" "GDF-2" "BMP9" "BMP-9")) 
(define-protein "GDF3_HUMAN" ("GDF3" "GDF-3")) 
(define-protein "GDF6_HUMAN" ("BMP13" "GDF6" "BMP-13" "GDF-6" "GDF16")) 
(define-protein "GDF7_HUMAN" ("GDF7" "GDF-7")) 
(define-protein "GIT1_HUMAN" ("GIT1" "CAT1" "CAT-1")) 
(define-protein "GIT1_HUMAN" ("GIT1" "CAT1" "GRK-interacting protein 1" "CAT-1" "Cool-associated and tyrosine-phosphorylated protein 1" "ARF GAP GIT1" "G protein-coupled receptor kinase-interactor 1")) 
(define-protein "GIT2_HUMAN" ("KIAA0148" "CAT2" "CAT-2" "GIT2")) 
(define-protein "GNA12_HUMAN" ("GNA12")) 
(define-protein "GNA13_HUMAN" ("GNA13")) 
(define-protein "GNAI1_HUMAN" ("GNAI1")) 
(define-protein "GNDS_HUMAN" ("RGF" "RalGDS" "KIAA1308" "RalGEF" "RALGDS")) 
(define-protein "GRAP_HUMAN" ("GRAP")) 
(define-protein "GRB14_HUMAN" ("GRB14")) 
(define-protein "GRB2_HUMAN" ("ASH" "GRB2")) 
(define-protein "GRP2_HUMAN" ("CalDAG-GEFI" "MCG7" "CDC25L" "RASGRP2" "hCDC25L")) 
(define-protein "GRP3_HUMAN" ("RASGRP3" "KIAA0846" "GRP3")) 
(define-protein "GRP4_HUMAN" ("RASGRP4")) 
(define-protein "HABP4_HUMAN" ("IHABP-4" "HABP4" "IHABP4")) 
(define-protein "HBEGF_HUMAN" ("DT-R" "Diphtheria toxin receptor" "HB-EGF" "HBEGF" "HEGFL" "Heparin-binding EGF-like growth factor" "DTR" "DTS")) 
(define-protein "HBEGF_HUMAN" ("DT-R" "HB-EGF" "HBEGF" "HEGFL" "DTR" "DTS")) 
(define-protein "I10R1_HUMAN" ("IL-10RA" "IL10RA" "IL-10R1" "IL10R" "CDw210a" "CD210")) 
(define-protein "I10R2_HUMAN" ("CRF2-4" "CRFB4" "IL-10RB" "CDw210b" "D21S58" "D21S66" "IL10RB" "IL-10R2")) 
(define-protein "I11RA_HUMAN" ("IL-11RA" "IL-11R-alpha" "IL11RA")) 
(define-protein "I12R2_HUMAN" ("IL12RB2" "IL-12RB2" "IL-12R subunit beta-2" "IL-12R-beta-2" "IL-12 receptor subunit beta-2")) 
(define-protein "I12R2_HUMAN" ("IL12RB2" "IL-12RB2" "IL-12R-beta-2")) 
(define-protein "I13R1_HUMAN" ("CD213a1" "IL13RA" "IL-13RA1" "CT19" "IL-13R-alpha-1" "IL13RA1" "IL13R")) 
(define-protein "I13R2_HUMAN" ("IL-13RA2" "CD213a2" "IL-13R-alpha-2" "IL13R" "IL13RA2")) 
(define-protein "I15RA_HUMAN" ("IL-15R-alpha" "sIL-15R-alpha" "sIL-15RA" "IL15RA" "IL-15RA" "CD215")) 
(define-protein "I20RA_HUMAN" ("IL-20R1" "IL-20RA" "IL20RA" "CRF2-8" "IL-20R-alpha" "ZcytoR7")) 
(define-protein "I20RA_HUMAN" ("IL-20R1" "IL-20RA" "IL20RA" "Cytokine receptor family 2 member 8" "CRF2-8" "IL-20 receptor subunit alpha" "IL-20R-alpha" "Cytokine receptor class-II member 8" "ZcytoR7")) 
(define-protein "ICEF1_HUMAN" ("KIAA0403" "IPCEF1")) 
(define-protein "IKZF3_HUMAN" ("IKZF3" "Ikaros family zinc finger protein 3" "ZNFN1A3")) 
(define-protein "IKZF3_HUMAN" ("IKZF3" "ZNFN1A3")) 
(define-protein "IL17F_HUMAN" ("IL17F" "Cytokine ML-1" "IL-17F")) 
(define-protein "IL17F_HUMAN" ("IL17F" "IL-17F")) 
(define-protein "IL17_HUMAN" ("IL17A" "CTLA-8" "IL-17" "CTLA8" "IL17" "IL-17A")) 
(define-protein "IL18_HUMAN" ("IGIF" "IL-18" "Iboctadekin" "IL18" "IL1F4")) 
(define-protein "IL21_HUMAN" ("Za11" "IL21" "IL-21")) 
(define-protein "IL23A_HUMAN" ("SGRF" "IL23A" "IL-23p19" "IL-23-A")) 
(define-protein "IL23A_HUMAN" ("SGRF" "IL23A" "IL-23p19" "Interleukin-23 subunit p19" "IL-23-A" "IL-23 subunit alpha")) 
(define-protein "IL2_HUMAN" ("TCGF" "Aldesleukin" "IL-2" "IL2")) 
(define-protein "IL5RA_HUMAN" ("CDw125" "IL5R" "IL-5RA" "CD125" "IL5RA" "IL-5R-alpha")) 
(define-protein "ILK_HUMAN" ("p59ILK" "ILK" "2.7.11.1" "ILK1" "ILK2" "ILK-1" "ILK-2")) 
(define-protein "INHBE_HUMAN" ("INHBE")) 
(define-protein "IQEC1_HUMAN" ("ARFGEP100" "KIAA0763" "BRAG2" "IQSEC1")) 
(define-protein "IRS2_HUMAN" ("IRS2" "IRS-2")) 
(define-protein "ITK_HUMAN" ("ITK" "LYK" "2.7.10.2")) ;; drop "EMT" -- it is a bio-process in all cases we have seen
(define-protein "ITSN1_HUMAN" ("ITSN" "SH3D1A" "SH3P17" "ITSN1")) 
(define-protein "ITSN2_HUMAN" ("SH3D1B" "SH3P18" "KIAA1256" "SH3P18-like WASP-associated protein" "SWAP" "SH3 domain-containing protein 1B" "ITSN2")) 
(define-protein "ITSN2_HUMAN" ("SH3D1B" "SH3P18" "KIAA1256" "SWAP" "ITSN2")) 
(define-protein "JAG1_HUMAN" ("JAGL1" "hJ1" "Jagged1" "CD339" "JAG1")) 
(define-protein "JAG2_HUMAN" ("Jagged2" "JAG2" "hJ2")) 
(define-protein "KAD5_HUMAN" ("2.7.4.3" "AK5" "2.7.4.6")) 
(define-protein "KAD5_HUMAN" ("AK 5" "2.7.4.3" "ATP-AMP transphosphorylase 5" "AK5" "2.7.4.6")) 
(define-protein "KCC2A_HUMAN" ("KIAA0968" "2.7.11.17" "CAMK2A" "CAMKA")) 
(define-protein "KCC2A_HUMAN" ("KIAA0968" "2.7.11.17" "CaM kinase II subunit alpha" "CaMK-II subunit alpha" "CAMK2A" "CAMKA")) 
(define-protein "KCC2B_HUMAN" ("2.7.11.17" "CAMK2B" "CAMK2" "CAM2" "CAMKB")) 
(define-protein "KCC2D_HUMAN" ("CAMKD" "2.7.11.17" "CAMK2D")) 
(define-protein "KCC2G_HUMAN" ("CAMKG" "CAMK" "CAMK2G" "2.7.11.17" "CAMK-II")) 
(define-protein "KCC4_HUMAN" ("CAMKIV" "CAMK4" "CAMK" "2.7.11.17" "CAMK-GR")) 
(define-protein "KDIS_HUMAN" ("KIAA1250" "Ankyrin repeat-rich membrane-spanning protein" "KIDINS220" "ARMS")) 
(define-protein "KDIS_HUMAN" ("KIAA1250" "KIDINS220" "ARMS")) 
(define-protein "KEAP1_HUMAN" ("KLHL19" "KIAA0132" "KEAP1" "INRF2" "INrf2")) 
(define-protein "KGUA_HUMAN" ("GUK1" "2.7.4.8" "GMK")) 
(define-protein "KIRR1_HUMAN" ("KIRREL" "Kin of irregular chiasm-like protein 1" "NEPH1" "Nephrin-like protein 1" "KIRREL1")) 
(define-protein "KIRR1_HUMAN" ("KIRREL" "NEPH1" "KIRREL1")) 
(define-protein "KLOTB_HUMAN" ("BKL" "KLB" "BetaKlotho")) 
(define-protein "KLOT_HUMAN" ("3.2.1.31" "KL" "Klotho peptide")) 
(define-protein "KLOT_HUMAN" ("3.2.1.31" "KL")) 
(define-protein "KPCD1_HUMAN" ("PRKD1" "2.7.11.13" "PRKCM" "PKD1" "PKD" "nPKC-D1" "nPKC-mu")) 
(define-protein "KPCD2_HUMAN" ("PRKD2" "2.7.11.13" "PKD2" "nPKC-D2")) 
(define-protein "KPCD_HUMAN" ("2.7.11.13" "nPKC-delta" "SDK1" "2.7.10.2" "PRKCD")) 
(define-protein "KPCE_HUMAN" ("2.7.11.13" "nPKC-epsilon" "PRKCE" "PKCE")) 
(define-protein "KPCT_HUMAN" ("PRKCQ" "2.7.11.13" "nPKC-theta" "PRKCT")) 
(define-protein "KPCZ_HUMAN" ("PRKCZ" "2.7.11.13" "nPKC-zeta" "PKC2")) 
(define-protein "KSR1_HUMAN" ("KSR" "KSR1")) 
(define-protein "LCP2_HUMAN" ("SLP76" "LCP2")) 
(define-protein "LFNG_HUMAN" ("2.4.1.222" "LFNG")) 
(define-protein "LIGO1_HUMAN" ("LINGO1" "LRRN6A" "LERN1")) 
(define-protein "LIGO1_HUMAN" ("LINGO1" "LRRN6A" "Leucine-rich repeat neuronal protein 6A" "Leucine-rich repeat neuronal protein 1" "LERN1" "Leucine-rich repeat and immunoglobulin domain-containing protein 1")) 
(define-protein "LNX1_HUMAN" ("LNX" "PDZRN2" "6.3.2.-" "LNX1")) 
(define-protein "LNX2_HUMAN" ("PDZRN1" "LNX2")) 
(define-protein "LPAR1_HUMAN" ("LPA-1" "LPA1" "LPA receptor 1" "LPAR1" "EDG2" "Lysophosphatidic acid receptor Edg-2")) 
(define-protein "LPAR1_HUMAN" ("LPA-1" "LPA1" "LPAR1" "EDG2")) 
(define-protein "LPAR2_HUMAN" ("LPA-2" "LPA2" "LPA receptor 2" "LPAR2" "Lysophosphatidic acid receptor Edg-4" "EDG4")) 
(define-protein "LPAR2_HUMAN" ("LPA-2" "LPA2" "LPAR2" "EDG4")) 
(define-protein "LY96_HUMAN" ("ESOP1" "LY96" "Ly-96" "MD2" "ESOP-1")) 
(define-protein "LY96_HUMAN" ("ESOP1" "LY96" "Ly-96" "MD2" "ESOP-1"))
(define-protein "LY96_HUMAN" ("ESOP1" "Protein MD-2" "LY96" "Ly-96" "MD2" "ESOP-1")) 
(define-protein "M3K1_HUMAN" ("MEKK1" "MAP3K1" "2.7.11.25" "MEKK" "MAPKKK1")) 
(define-protein "M3K2_HUMAN" ("MAPK/ERK kinase kinase 2" "MEKK2" "MAP3K2" "MEK kinase 2" "2.7.11.25" "MEKK 2" "MAPKKK2")) 
(define-protein "M3K2_HUMAN" ("MEKK2" "MAP3K2" "2.7.11.25" "MAPKKK2")) 
(define-protein "M3K3_HUMAN" ("MEKK3" "MAP3K3" "MAPKKK3" "2.7.11.25")) 
(define-protein "M3K3_HUMAN" ("MEKK3" "MAPK/ERK kinase kinase 3" "MAP3K3" "MEK kinase 3" "MAPKKK3" "2.7.11.25" "MEKK 3")) 
(define-protein "M3K4_HUMAN" ("MAP3K4" "MTK1" "KIAA0213" "MEKK4" "MAPKKK4" "2.7.11.25")) 
(define-protein "M3K4_HUMAN" ("MAPK/ERK kinase kinase 4" "MEK kinase 4" "MAP3K4" "MTK1" "KIAA0213" "MEKK4" "MAPKKK4" "MAP three kinase 1" "2.7.11.25" "MEKK 4")) 
(define-protein "M3K5_HUMAN" ("MAP3K5" "MEKK5" "2.7.11.25" "MAPKKK5" "ASK-1" "ASK1")) 
(define-protein "M3K5_HUMAN" ("MEK kinase 5" "MAPK/ERK kinase kinase 5" "MAP3K5" "MEKK5" "Apoptosis signal-regulating kinase 1" "2.7.11.25" "MAPKKK5" "MEKK 5" "ASK-1" "ASK1")) 
(define-protein "M3KCL_HUMAN" ("MAP3K7CL" "TAK1L" "C21orf7")) 
(define-protein "MAGI-3" NIL) 
(define-protein "MAML1_HUMAN" ("KIAA0200" "MAML1" "Mam-1")) 
(define-protein "MAX_HUMAN" ("MAX" "bHLHd4" "BHLHD4")) 
(define-protein "MEF2D_HUMAN" ("MEF2D")) 
(define-protein "MP2K1_HUMAN" ("MKK1" "MAP2K1" "PRKMK1" "MEK1" "2.7.12.2" "p45MAPKK" "p45mapkk")) 
(define-protein "MUC20_HUMAN" ("KIAA1359" "MUC20" "MUC-20")) 
(define-protein "NADE_HUMAN" ("6.3.5.1" "NADSYN1")) 
(define-protein "NCKP1_HUMAN" ("HEM2" "p125Nap1" "NAP1" "KIAA0587" "NCKAP1")) 
(define-protein "NCKP1_HUMAN" ("NAP 1" "HEM2" "p125Nap1" "Membrane-associated protein HEM-2" "NAP1" "KIAA0587" "NCKAP1")) 
(define-protein "NCOR2_HUMAN" ("CTG repeat protein 26" "TRAC" "T3 receptor-associating factor" "Silencing mediator of retinoic acid and thyroid hormone receptor" "CTG26" "Thyroid-, retinoic-acid-receptor-associated corepressor" "NCOR2" "N-CoR2" "SMAP270" "SMRT")) 
(define-protein "NCOR2_HUMAN" ("TRAC" "CTG26" "NCOR2" "N-CoR2" "SMAP270" "SMRT")) 
(define-protein "NDEL1_HUMAN" ("NDEL1" "NUDEL" "EOPA" "MITAP1")) 
(define-protein "NDEL1_HUMAN" ("Protein Nudel" "NDEL1" "NUDEL" "EOPA" "Mitosin-associated protein 1" "MITAP1")) 
(define-protein "NFAC2_HUMAN" ("NFATc2" "NFATP" "NFAT1" "NF-ATp" "NF-ATc2" "NFATC2")) 
(define-protein "NFAC3_HUMAN" ("NFATc3" "NF-ATc3" "NFAT4" "NFATx" "NFATC3" "NF-AT4")) 
(define-protein "NGAP_HUMAN" ("RASAL2" "NGAP" "RAS protein activator-like 2")) 
(define-protein "NGAP_HUMAN" ("RASAL2" "NGAP")) 
(define-protein "NGEF_HUMAN" ("NGEF")) 
(define-protein "NHRF2_HUMAN" ("NHERF-2" "TKA-1" "SIP-1" "NHERF2" "SLC9A3R2")) 
(define-protein "NMDE1_HUMAN" ("NMDAR2A" "NR2A" "hNR2A" "GluN2A" "GRIN2A")) 
(define-protein "NMDE2_HUMAN" ("NMDAR2B" "NR2B" "GRIN2B" "GluN2B" "hNR3" "NR3")) 
(define-protein "NMDE3_HUMAN" ("NMDAR2C" "NR2C" "GRIN2C" "GluN2C")) 
(define-protein "NMDZ1_HUMAN" ("GRIN1" "NMDAR1" "GluN1" "NMD-R1")) 
(define-protein "NODAL_HUMAN" ("NODAL")) 
(define-protein "NOTC2_HUMAN" ("NOTCH2" "hN2")) 
(define-protein "NOTC3_HUMAN" ("NOTCH3" "Notch 3 intracellular domain" "Notch 3 extracellular truncation" "Notch 3")) 
(define-protein "NOTC3_HUMAN" ("NOTCH3")) 
(define-protein "NOTC4_HUMAN" ("hNotch4" "NOTCH4" "INT3")) 
(define-protein "NOTC4_HUMAN" ("hNotch4" "Notch 4 extracellular truncation" "NOTCH4" "Notch 4" "Notch 4 intracellular domain" "INT3")) 
(define-protein "NOX1_HUMAN" ("NADH/NADPH mitogenic oxidase subunit P65-MOX" "NOH-1" "Mitogenic oxidase 1" "MOX1" "MOX-1" "NOX1" "NOH1" "NOX-1" "1.-.-.-")) 
(define-protein "NOX1_HUMAN" ("NOH-1" "MOX1" "MOX-1" "NOX1" "NOH1" "NOX-1" "1.-.-.-")) 
(define-protein "NRG1_HUMAN" ("HGL" "Pro-NRG1" "HRGA" "GGF" "Neuregulin-1" "Heregulin" "NDF" "HRG" "ARIA" "NRG1" "SMDF")) 
(define-protein "NRG4_HUMAN" ("NRG-4" "NRG4" "Neuregulin-4" "Pro-NRG4")) 
(define-protein "NTAL_HUMAN" ("LAB" "WBSCR15" "WBS15" "WBSCR5" "NTAL" "LAT2")) 
(define-protein "NTAL_HUMAN" ("Linker for activation of B-cells" "Non-T-cell activation linker" "LAB" "WBSCR15" "WBS15" "WBSCR5" "NTAL" "LAT2" "Williams-Beuren syndrome chromosomal region 5 protein" "Membrane-associated adapter molecule" "Williams-Beuren syndrome chromosomal region 15 protein")) 
(define-protein "NTRK2_HUMAN" ("GP145-TrkB" "Trk-B" "NTRK2" "TRKB" "2.7.10.1")) 
(define-protein "NTRK3_HUMAN" ("NTRK3" "GP145-TrkC" "Trk-C" "TRKC" "2.7.10.1")) 
(define-protein "OBSCN_HUMAN" ("Obscurin-MLCK" "KIAA1639" "OBSCN" "2.7.11.1" "KIAA1556" "Obscurin-RhoGEF")) 
(define-protein "OFUT1_HUMAN" ("FUT12" "2.4.1.221" "KIAA0180" "O-FucT-1" "POFUT1")) 
(define-protein "OFUT1_HUMAN" ("Peptide-O-fucosyltransferase 1" "FUT12" "2.4.1.221" "KIAA0180" "O-FucT-1" "POFUT1")) 
(define-protein "P63_HUMAN" ("P73H" "Chronic ulcerative stomatitis protein" "Keratinocyte transcription factor KET" "Tumor protein p73-like" "TP63" "P63" "p40" "KET" "TP73L" "p51" "CUSP" "p63" "p73L" "Transformation-related protein 63" "P73L")) 
(define-protein "P63_HUMAN" ("P73H" "TP63" "P63" "p40" "KET" "TP73L" "p51" "CUSP" "p63" "p73L" "P73L")) 
(define-protein "PAK1_HUMAN" ("Alpha-PAK" "2.7.11.1" "PAK-1" "p65-PAK" "PAK1")) 
(define-protein "PAK2_HUMAN" ("PAK-2p27" "PAK65" "PAK-2p34" "Gamma-PAK" "p58" "p27" "p34" "PAK2" "2.7.11.1" "PAK-2" "C-t-PAK2")) 
(define-protein "PAR4_HUMAN" ("F2RL3" "PAR-4" "PAR4")) 
(define-protein "PAR4_HUMAN" ("F2RL3" "PAR-4" "Thrombin receptor-like 3" "PAR4" "Coagulation factor II receptor-like 3")) 
(define-protein "PDGFC_HUMAN" ("PDGF-C" "SCDGF" "Fallotein" "VEGF-E" "PDGFC")) 
(define-protein "PDGFC_HUMAN" ("PDGF-C" "SCDGF" "PDGFC receptor-binding form" "Platelet-derived growth factor C, receptor-binding form" "Platelet-derived growth factor C, latent form" "Fallotein" "VEGF-E" "PDGFC" "PDGFC latent form" "Spinal cord-derived growth factor")) 
(define-protein "PDGFD_HUMAN" ("Iris-expressed growth factor" "SCDGF-B" "PDGF-D" "Spinal cord-derived growth factor B" "IEGF" "PDGFD receptor-binding form" "Platelet-derived growth factor D, latent form" "Platelet-derived growth factor D, receptor-binding form" "SCDGFB" "PDGFD latent form" "PDGFD")) 
(define-protein "PDGFD_HUMAN" ("SCDGF-B" "PDGF-D" "IEGF" "SCDGFB" "PDGFD")) 
(define-protein "PELP1_HUMAN" ("MNAR" "PELP1" "HMX3")) 
(define-protein "PI3R5_HUMAN" ("PI3-kinase regulatory subunit 5" "PtdIns-3-kinase p101" "PI3-kinase p101 subunit" "p101-PI3K" "PIK3R5" "Phosphatidylinositol 4,5-bisphosphate 3-kinase regulatory subunit" "PtdIns-3-kinase regulatory subunit" "Protein FOAP-2")) 
(define-protein "PI3R5_HUMAN" ("p101-PI3K" "PIK3R5")) 
(define-protein "PI3R6_HUMAN" ("C17orf38" "p87PIKAP" "PIK3R6")) 
(define-protein "PI51A_HUMAN" ("2.7.1.68" "PIP5K1-alpha" "PIP5K1A" "PIP5KIalpha")) 
(define-protein "PI51A_HUMAN" ("2.7.1.68" "Phosphatidylinositol 4-phosphate 5-kinase type I alpha" "PtdIns(4)P-5-kinase 1 alpha" "68 kDa type I phosphatidylinositol 4-phosphate 5-kinase alpha" "PIP5K1-alpha" "PIP5K1A" "PIP5KIalpha")) 
(define-protein "PIPNA_HUMAN" ("PITPN" "PI-TP-alpha" "PITPNA")) 
(define-protein "PK3C3_HUMAN" ("2.7.1.137" "PIK3C3" "VPS34" "hVps34")) 
(define-protein "PKHG2_HUMAN" ("PLEKHG2" "PH domain-containing family G member 2")) 
(define-protein "PKHG2_HUMAN" ("PLEKHG2")) 
(define-protein "PKHG6_HUMAN" ("MyoGEF" "PLEKHG6")) 
(define-protein "PKN1_HUMAN" ("2.7.11.13" "PKN1" "PRKCL1" "PRK1" "PKN" "PAK-1" "PAK1")) 
(define-protein "PKN2_HUMAN" ("PRKCL2" "2.7.11.13" "PKN2" "PRK2")) 
(define-protein "PLCB1_HUMAN" ("KIAA0581" "PLC-154" "3.1.4.11" "PLCB1" "PLC-I" "PLC-beta-1")) 
(define-protein "PLCB1_HUMAN" ("KIAA0581" "Phospholipase C-I" "Phospholipase C-beta-1" "PLC-154" "3.1.4.11" "PLCB1" "Phosphoinositide phospholipase C-beta-1" "PLC-I" "PLC-beta-1")) 
(define-protein "PLCB2_HUMAN" ("3.1.4.11" "PLCB2" "PLC-beta-2")) 
(define-protein "PLCB3_HUMAN" ("PLCB3" "PLC-beta-3" "3.1.4.11")) 
(define-protein "PLCB4_HUMAN" ("PLCB4" "PLC-beta-4" "3.1.4.11")) 
(define-protein "PLCE1_HUMAN" ("PLC-epsilon-1" "PLCE1" "PLCE" "KIAA1516" "3.1.4.11" "PPLC")) 
(define-protein "PLCE1_HUMAN" ("PLC-epsilon-1" "PLCE1" "PLCE" "KIAA1516" "Phosphoinositide phospholipase C-epsilon-1" "Pancreas-enriched phospholipase C" "Phospholipase C-epsilon-1" "3.1.4.11" "PPLC")) 
(define-protein "PLD1_HUMAN" ("PLD1" "3.1.4.4" "hPLD1")) 
(define-protein "PLXD1_HUMAN" ("KIAA0620" "PLXND1")) 
(define-protein "PODO_HUMAN" ("NPHS2")) 
(define-protein "PPARA_HUMAN" ("PPARA" "PPAR-alpha" "NR1C1" "PPAR")) 
(define-protein "PREX1_HUMAN" ("KIAA1415" "PREX1" "P-Rex1")) 
(define-protein "PREX2_HUMAN" ("P-Rex2" "PREX2" "DEPDC2")) 
(define-protein "PTEN_HUMAN" ("MMAC1" "TEP1" "3.1.3.16" "PTEN" "3.1.3.67" "3.1.3.48")) 
(define-protein "PTN11_HUMAN" ("SH-PTP2" "SH-PTP3" "PTPN11" "PTP2C" "Shp2" "SHPTP2" "PTP-2C" "SHP-2" "PTP-1D" "3.1.3.48")) 
(define-protein "PTPRJ_HUMAN" ("PTPRJ" "DEP-1" "R-PTP-eta" "R-PTP-J" "DEP1" "CD148" "3.1.3.48")) 
(define-protein "RABX5_HUMAN" ("Rabaptin-5-associated exchange factor for Rab5" "Rabex-5" "RABGEF1" "RAP1" "RABEX5")) 
(define-protein "RABX5_HUMAN" ("Rabex-5" "RABGEF1" "RAP1" "RABEX5")) 
(define-protein "RAC1_HUMAN" ("RAC1" "TC25" "p21-Rac1")) 
(define-protein "RAC3_HUMAN" ("RAC3" "p21-Rac3")) 
(define-protein "RAD9A_HUMAN" ("3.1.11.2" "hRAD9" "RAD9A" "DNA repair exonuclease rad9 homolog A")) 
(define-protein "RAD9A_HUMAN" ("3.1.11.2" "hRAD9" "RAD9A")) 
(define-protein "RANB9_HUMAN" ("RANBP9" "BPM90" "RanBPM" "BPM-L" "RanBP9" "RANBPM" "RanBP7")) 
(define-protein "RANB9_HUMAN" ("RANBP9" "BPM90" "RanBPM" "Ran-binding protein M" "BPM-L" "RanBP9" "RANBPM" "RanBP7")) 
(define-protein "RAP1A_HUMAN" ("KREV1" "C21KG" "RAP1A" "G-22K")) 
(define-protein "RAP1B_HUMAN" ("RAP1B")) 
(define-protein "RASA2_HUMAN" ("GAP1M" "RASGAP" "GAP1m" "RASA2")) 
(define-protein "RB11B_HUMAN" ("RAB11B" "YPT3")) 
(define-protein "RBP10_HUMAN" ("KIAA1464" "RanBP10" "RANBP10")) 
(define-protein "RBPJL_HUMAN" ("RBPL" "RBPJL" "RBPSUHL")) 
(define-protein "RBPJL_HUMAN" ("Transcription factor RBP-L" "RBPL" "RBPJL" "RBPSUHL")) 
(define-protein "RERG_HUMAN" ("RERG")) 
(define-protein "RGL1_HUMAN" ("RGL" "KIAA0959" "RGL1")) 
(define-protein "RGL1_HUMAN" ("RGL" "RalGDS-like 1" "KIAA0959" "RGL1")) 
(define-protein "RGRF1_HUMAN" ("GRF1" "RASGRF1" "GNRP" "Ras-GRF1" "CDC25")) 
(define-protein "RHG04_HUMAN" ("RGC1" "ARHGAP4" "KIAA0131" "RHOGAP4" "p115")) 
(define-protein "RHOA_HUMAN" ("h12" "ARH12" "ARHA" "RHOA" "RHO12")) 
(define-protein "RHOB_HUMAN" ("ARH6" "ARHB" "RHOB" "h6")) 
(define-protein "RHOG_HUMAN" ("ARHG" "RHOG")) 
(define-protein "RIN1_HUMAN" ("RIN1")) 
(define-protein "RIN2_HUMAN" ("RASSF4" "RIN2")) 
(define-protein "RIN2_HUMAN" ("Ras association domain family 4" "RASSF4" "RIN2" "Ras interaction/interference protein 2" "Ras inhibitor JC265")) 
(define-protein "RIT1_HUMAN" ("ROC1" "RIT" "RIT1" "RIBB")) 
(define-protein "RIT1_HUMAN" ("Ras-like protein expressed in many tissues" "ROC1" "Ras-like without CAAX protein 1" "RIT" "RIT1" "RIBB")) 
(define-protein "RIT2_HUMAN" ("ROC2" "RIN" "RIT2")) 
(define-protein "RIT2_HUMAN" ("ROC2" "RIN" "Ras-like without CAAX protein 2" "Ras-like protein expressed in neurons" "RIT2")) 
(define-protein "ROBO1_HUMAN" ("DUTT1" "ROBO1" "H-Robo-1")) 
(define-protein "ROBO1_HUMAN" ("Deleted in U twenty twenty" "DUTT1" "ROBO1" "H-Robo-1")) 
(define-protein "ROCK1_HUMAN" ("ROCK1" "2.7.11.1" "p160ROCK" "ROCK-I")) 
(define-protein "ROR2_HUMAN" ("ROR2" "NTRKR2" "2.7.10.1")) 
(define-protein "RPGF1_HUMAN" ("GRF2" "RAPGEF1")) 
(define-protein "RPGP2_HUMAN" ("KIAA1039" "GARNL4" "RAP1GA2" "Rap1GAP2" "RAP1GAP2")) 
(define-protein "RRAS2_HUMAN" ("TC21" "RRAS2")) 
(define-protein "RTN4R_HUMAN" ("NgR" "NOGOR" "RTN4R")) 
(define-protein "RTN4R_HUMAN" ("Nogo receptor" "NgR" "Nogo-66 receptor" "NOGOR" "RTN4R")) 
(define-protein "SAR1B_HUMAN" ("GTBPB" "SARA2" "SARB" "SAR1B")) 
(define-protein "SAR1B_HUMAN" ("GTP-binding protein B" "GTBPB" "SARA2" "SARB" "SAR1B")) 
(define-protein "SC23A_HUMAN" ("SEC23A")) 
(define-protein "SHC2_HUMAN" ("SCK" "SHCB" "SHC2")) 
(define-protein "SHC3_HUMAN" ("N-Shc" "NSHC" "SHC3" "SHCC")) 
(define-protein "SHC3_HUMAN" ("N-Shc" "Protein Rai" "SHC-transforming protein C" "SH2 domain protein C3" "NSHC" "Src homology 2 domain-containing-transforming protein C3" "SHC3" "SHCC" "Neuronal Shc")) 
(define-protein "SHIP1_HUMAN" ("SIP-145" "SH2 domain-containing inositol phosphatase 1" "p150Ship" "SH2 domain-containing inositol 5'-phosphatase 1" "SHIP1" "SHIP" "SHIP-1" "hp51CN" "Inositol polyphosphate-5-phosphatase of 145 kDa" "INPP5D" "3.1.3.86")) 
(define-protein "SHIP1_HUMAN" ("SIP-145" "p150Ship" "SHIP1" "SHIP" "SHIP-1" "hp51CN" "INPP5D" "3.1.3.86")) 
(define-protein "SLAP1_HUMAN" ("SLAP" "hSLAP" "SLAP-1" "SLAP1" "SLA")) 
(define-protein "SLAP2_HUMAN" ("C20orf156" "SLAP-2" "SLA2" "SLAP2" "MARS")) 
(define-protein "SLAP2_HUMAN" ("Modulator of antigen receptor signaling" "C20orf156" "SLAP-2" "SLA2" "SLAP2" "Src-like adapter protein 2" "MARS")) 
(define-protein "SMO_HUMAN" ("SMO" "Protein Gx" "SMOH")) 
(define-protein "SMO_HUMAN" ("SMO" "SMOH")) 
(define-protein "SMS1_HUMAN" ("2.7.8.27" "MOB" "SGMS1" "TMEM23" "SMS1")) 
(define-protein "SND1_HUMAN" ("SND1" "TDRD11")) 
(define-protein "SOS1_HUMAN" ("SOS1" "SOS-1")) 
(define-protein "SOS2_HUMAN" ("SOS-2" "SOS2")) 
(define-protein "SPHK1_HUMAN" ("SPK" "2.7.1.91" "SPHK1" "SPHK")) 
(define-protein "SPHK1_HUMAN" ("SPK" "SK 1" "2.7.1.91" "SPK 1" "SPHK1" "SPHK")) 
(define-protein "SPHK2_HUMAN" ("SK 2" "SPHK2" "2.7.1.91" "SPK 2")) 
(define-protein "SPHK2_HUMAN" ("SPHK2" "2.7.1.91")) 
(define-protein "SPRE1_HUMAN" ("Spred-1" "hSpred1" "SPRED1")) 
(define-protein "SPRE2_HUMAN" ("Spred-2" "SPRED2")) 
(define-protein "SPT13_HUMAN" ("Asef2" "APC-stimulated guanine nucleotide exchange factor 2" "SPATA13")) 
(define-protein "SPT13_HUMAN" ("Asef2" "SPATA13")) 
(define-protein "SPTB2_HUMAN" ("SPTBN1" "SPTB2")) 
(define-protein "SPTN1_HUMAN" ("NEAS" "SPTA2" "SPTAN1")) 
(define-protein "SPTN4_HUMAN" ("SPTBN3" "SPTBN4" "KIAA1642")) 
(define-protein "SPTN4_HUMAN" ("Spectrin, non-erythroid beta chain 3" "Beta-IV spectrin" "SPTBN3" "SPTBN4" "KIAA1642")) 
(define-protein "SPTN5_HUMAN" ("Beta-V spectrin" "SPTBN5" "HUSPECV" "BSPECV" "HUBSPECV")) 
(define-protein "SPTN5_HUMAN" ("SPTBN5" "HUSPECV" "BSPECV" "HUBSPECV")) 
(define-protein "STAT4_HUMAN" ("STAT4")) 
(define-protein "SUH_HUMAN" ("RBP-J" "RBP-JK" "IGKJRB1" "CBF-1" "RBPSUH" "RBPJ" "RBPJK" "IGKJRB")) 
(define-protein "SYGP1_HUMAN" ("KIAA1938" "Neuronal RasGAP" "Synaptic Ras-GAP 1" "Synaptic Ras GTPase-activating protein 1" "SYNGAP1")) 
(define-protein "SYGP1_HUMAN" ("KIAA1938" "SYNGAP1")) 
(define-protein "TBA4A_HUMAN" ("TUBA4A" "TUBA1")) 
(define-protein "TF65_HUMAN" ("RELA" "NFKB3")) 
(define-protein "TGFB2_HUMAN" ("G-TSF" "Cetermin" "LAP" "TGF-beta-2" "Polyergin" "TGFB2")) 
(define-protein "TIAM1_HUMAN" ("TIAM1" "TIAM-1")) 
(define-protein "TIAM2_HUMAN" ("TIAM2" "TIAM-2" "STEF" "KIAA2016")) 
(define-protein "TIE2_HUMAN" ("CD202b" "hTIE2" "2.7.10.1" "TEK" "TIE2" "VMCM1" "VMCM")) 
(define-protein "TIM_HUMAN" ("TIMELESS1" "TIM" "TIM1" "TIMELESS" "hTIM")) 
(define-protein "TIPIN_HUMAN" ("TIPIN")) 
(define-protein "TISB_HUMAN" ("ZFP36L1" "ERF1" "BRF1" "TIS11B" "RNF162B" "BERG36" "ERF-1")) 
(define-protein "TITIN_HUMAN" ("2.7.11.1" "Rhabdomyosarcoma antigen MU-RMS-40.14" "TTN" "Connectin")) 
(define-protein "TITIN_HUMAN" ("2.7.11.1" "TTN" "Connectin")) 
(define-protein "TLL2_HUMAN" ("KIAA0932" "3.4.24.-" "TLL2")) 
(define-protein "TLN1_HUMAN" ("TLN1" "KIAA1027" "TLN")) 
(define-protein "TNPO1_HUMAN" ("MIP" "MIP1" "Karyopherin beta-2" "TRN" "importin beta-2" "KPNB2" "M9 region interaction protein" "TNPO1")) 
(define-protein "TNPO1_HUMAN" ("MIP" "MIP1" "TRN" "KPNB2" "TNPO1")) 
(define-protein "TOPB1_HUMAN" ("DNA topoisomerase II-binding protein 1" "TopBP1" "KIAA0259" "TOPBP1" "DNA topoisomerase II-beta-binding protein 1")) 
(define-protein "TOPB1_HUMAN" ("TopBP1" "KIAA0259" "TOPBP1")) 
(define-protein "TRPV1_HUMAN" ("TRPV1" "OTRPC1" "VR1" "TrpV1")) 
(define-protein "UNC5A_HUMAN" ("UNC5H1" "KIAA1976" "UNC5A")) 
(define-protein "UPAR_HUMAN" ("uPAR" "UPAR" "U-PAR" "MO3" "CD87" "PLAUR")) 
(define-protein "US6NL_HUMAN" ("RN-tre" "KIAA0019" "USP6NL")) 
(define-protein "US6NL_HUMAN" ("Related to the N-terminus of tre" "RN-tre" "KIAA0019" "USP6NL")) 
(define-protein "VAV3_HUMAN" ("VAV3" "VAV-3")) 
(define-protein "WASF1_HUMAN" ("Protein WAVE-1" "Verprolin homology domain-containing protein 1" "WASP family protein member 1" "WASF1" "SCAR1" "WAVE1" "KIAA0269")) 
(define-protein "WASF1_HUMAN" ("WASF1" "SCAR1" "WAVE1" "KIAA0269")) 
(define-protein "WASF2_HUMAN" ("Protein WAVE-2" "WASP family protein member 2" "Verprolin homology domain-containing protein 2" "WAVE2" "WASF2")) 
(define-protein "WASF2_HUMAN" ("WAVE2" "WASF2")) 
(define-protein "ZBT17_HUMAN" ("MIZ1" "Miz-1" "ZNF60" "ZBTB17" "ZNF151")) 
