(in-package :sparser)


(def-indiv-with-id rna "mtRNA" "NCIT:C25975" :name "mitochondrial RNA") 
(def-indiv-with-id micro-rna "MiR29b" "NCIT:C105365" :name "microRNA 29b") 
(def-indiv-with-id micro-rna "MiR124" "NCIT:C106407" :name "microRNA 124") 
(def-indiv-with-id rna "dsRNA" "NCIT:C95938" :name "double-stranded RNA") 
(def-indiv-with-id rna "gRNA" "NCIT:C95952" :name "guide RNA") 
(def-indiv-with-id rna "ncRNA" "NCIT:C26549" :name "functional RNA") 
(def-indiv-with-id rna "rRNA" "NCIT:C814" :name "ribosomal RNA") 
(def-indiv-with-id rna "premiRNA" "NCIT:C25968" :name "pre-miRNA") 
(def-indiv-with-id rna "piRNA" "NCIT:C95953" :name "piwi-interacting RNA") 
(def-indiv-with-id rna "shRNA" "NCIT:C123893" :name "short hairpin RNA") 
(def-indiv-with-id rna "snoRNA" "NCIT:C111316" :name "small nucleolar RNA") 
(def-indiv-with-id micro-rna "c13orf25" "NCIT:C118113" :name "MIR17HG gene") 
(def-indiv-with-id rna "hTERC" "NCIT:C2097" :name "telomerase RNA component") 
(def-indiv-with-id micro-rna "miRNA-16" "NCIT:C129416" :name "microRNA 16") 
(def-indiv-with-id rna "ssRNA" "NCIT:C95939" :name "single-stranded RNA") 
(def-indiv-with-id rna "snRNA" "NCIT:C815" :name "small nuclear RNA") 
(def-indiv-with-id rna "PCA3" "NCIT:C92559" :name "prostate cancer antigen 3") 
(def-indiv-with-id micro-rna "miRs181" "NCIT:C116021" :name "microRNA 181") 