(in-package :sparser)


(def-indiv-with-id bio-process "pyrexia" "GO:0001660" :name "fever generation") 
(def-indiv-with-id bio-process "GRIP" "NCIT:C78654" :name "grip") 
(def-indiv-with-id bio-process "Flight" "GO:0060361" :name "flight") 
(def-indiv-with-id bio-process "GvL" "NCIT:C18156" :name "graft-vs-leukemia effect") 
(def-indiv-with-id bio-process "Granulopoiesis" "NCIT:C26080" :name "granulopoiesis") 
(def-indiv-with-id bio-process "HRR" "GO:0000724" :name "double-strand break repair via homologous recombination") 
(def-indiv-with-id bio-process "Memory" "GO:0007613" :name "memory") 
(def-indiv-with-id bio-process "Neto" "GO:0051519" :name "activation of bipolar cell growth") 
(def-indiv-with-id bio-process "NRP" "GO:0085015" :name "dormancy maintenance of symbiont in host") 
(def-indiv-with-id bio-process "NMD" "NCIT:C29648" :name "nonsense-mediated decay") 
(def-indiv-with-id bio-process "NHEJ" "GO:0006303" :name "double-strand break repair via nonhomologous end joining") 
(def-indiv-with-id bio-process "Pregnancy" "NCIT:C25742" :name "pregnancy") 
(def-indiv-with-id bio-process "PTGS" "GO:0016441" :name "posttranscriptional gene silencing") 
(def-indiv-with-id bio-process "Resolution" "NCIT:C25655" :name "resolution") 
(def-indiv-with-id bio-process "RdDM" "GO:0080188" :name "RNA-directed DNA methylation") 
(def-indiv-with-id bio-process "SOC" "GO:0031578" :name "mitotic spindle orientation checkpoint") 
(def-indiv-with-id bio-process "SDSA" "GO:0045003" :name "double-strand break repair via synthesis-dependent strand annealing") 
(def-indiv-with-id bio-process "Splicing" "NCIT:C17106" :name "RNA splicing") 
(def-indiv-with-id bio-process "biosynthesis" "NCIT:C17702" :name "biosynthesis") 
(def-indiv-with-id bio-process "angiogenesis" "GO:0001525" :name "angiogenesis") 
(def-indiv-with-id bio-process "aggrephagy" "GO:0035973" :name "aggrephagy") 
(def-indiv-with-id bio-process "adaption" "NCIT:C68767" :name "acclimatization") 
(def-indiv-with-id bio-process "acidification" "GO:0045851" :name "pH reduction") 
(def-indiv-with-id bio-process "corticogenesis" "GO:0021987" :name "cerebral cortex development") 
(def-indiv-with-id bio-process "contractile" "NCIT:C30085" :name "muscle contraction") 
(def-indiv-with-id bio-process "conjugation" "GO:0000746" :name "conjugation") 
(def-indiv-with-id bio-process "cognition" "GO:0050890" :name "cognition") 
(def-indiv-with-id bio-process "coagulation" "GO:0050817" :name "coagulation") 
(def-indiv-with-id bio-process "chelating" "NCIT:C40483" :name "chelating activity") 
(def-indiv-with-id bio-process "carcinogenesis" "NCIT:C18078" :name "carcinogenesis") 
(def-indiv-with-id bio-process "ectasia" "NCIT:C120877" :name "ectasia") 
(def-indiv-with-id bio-process "diastole" "NCIT:C62109" :name "diastole") 
(def-indiv-with-id bio-process "desensitization" "NCIT:C45549" :name "receptor desensitization") 
(def-indiv-with-id bio-process "delamination" "GO:0060232" :name "delamination") 
(def-indiv-with-id bio-process "degranulation" "NCIT:C114629" :name "mast cell degranulation") 
(def-indiv-with-id bio-process "glycosidase" "GO:0016798" :name "hydrolase activity, acting on glycosyl bonds") 
(def-indiv-with-id bio-process "gestation" "GO:0007565" :name "female pregnancy") 
(def-indiv-with-id bio-process "fucosylation" "GO:0036065" :name "fucosylation") 
(def-indiv-with-id bio-process "fibroplasia" "NCIT:C120881" :name "fibroplasia") 
(def-indiv-with-id bio-process "fibrinolysis" "GO:0042730" :name "fibrinolysis") 
(def-indiv-with-id bio-process "fertilization" "GO:0009566" :name "fertilization") 
(def-indiv-with-id bio-process "ferroptosis" "GO:0097707" :name "ferroptosis") 
(def-indiv-with-id bio-process "erythropoiesis" "NCIT:C16559" :name "erythropoiesis") 
(def-indiv-with-id bio-process "engraftment" "NCIT:C37947" :name "engraftment") 
(def-indiv-with-id bio-process "embryogenesis" "NCIT:C16649" :name "embryogenesis") 
(def-indiv-with-id bio-process "integration" "NCIT:C18855" :name "DNA integration") 
(def-indiv-with-id bio-process "innervation" "GO:0060384" :name "innervation") 
(def-indiv-with-id bio-process "infarct" "NCIT:C25738" :name "infarction") 
(def-indiv-with-id bio-process "immunity" "NCIT:C16710" :name "immunity") 
(def-indiv-with-id bio-process "hypomethylation" "NCIT:C121521" :name "hypomethylation") 
(def-indiv-with-id bio-process "hypersensitivity" "GO:0002524" :name "hypersensitivity") 
(def-indiv-with-id bio-process "hematopoiesis" "NCIT:C16674" :name "hematopoiesis") 
(def-indiv-with-id bio-process "melanogenesis" "NCIT:C20628" :name "melanogenesis") 
(def-indiv-with-id bio-process "meiosis" "NCIT:C16834" :name "meiosis") 
(def-indiv-with-id bio-process "macropinocytosis" "GO:0044351" :name "macropinocytosis") 
(def-indiv-with-id bio-process "macrometastasis" "NCIT:C106296" :name "macrometastasis" :plural ("macrometastasises" "macrometastases")) 
(def-indiv-with-id bio-process "macroautophagy" "GO:0016236" :name "macroautophagy") 
(def-indiv-with-id bio-process "mDR" "NCIT:C17745" :name "multidrug resistance") 
(def-indiv-with-id bio-process "lymphomagenesis" "NCIT:C18128" :name "leukemogenesis") 
(def-indiv-with-id bio-process "lymphangiogenesis" "GO:0001946" :name "lymphangiogenesis") 
(def-indiv-with-id bio-process "lipophagy" "GO:0061724" :name "lipophagy") 
(def-indiv-with-id bio-process "lipolysis" "GO:0016042" :name "lipid catabolic process") 
(def-indiv-with-id bio-process "lactation" "GO:0007595" :name "lactation") 
(def-indiv-with-id bio-process "intravasation" "NCIT:C48197" :name "intravasation") 
(def-indiv-with-id bio-process "neurogenesis" "GO:0022008" :name "neurogenesis") 
(def-indiv-with-id bio-process "myelination" "GO:0042552" :name "myelination") 
(def-indiv-with-id bio-process "mtUPR" "GO:0034514" :name "mitochondrial unfolded protein response") 
(def-indiv-with-id bio-process "morphogenesis" "NCIT:C16879" :name "morphogenesis") 
(def-indiv-with-id bio-process "mitogenesis" "NCIT:C20863" :name "stimulation of cell proliferation") 
(def-indiv-with-id bio-process "metabolized" "NCIT:C19536" :name "metabolic process") 
(def-indiv-with-id bio-process "ovulation" "GO:0030728" :name "ovulation") 
(def-indiv-with-id bio-process "oogenesis" "GO:0048477" :name "oogenesis") 
(def-indiv-with-id bio-process "ocular" "NCIT:C38533" :name "sight") 
(def-indiv-with-id bio-process "permissiveness" "NCIT:C19311" :name "biologic permissiveness") 
(def-indiv-with-id bio-process "pathogenesis" "GO:0009405" :name "pathogenesis" :plural ("pathogenesises" "pathogeneses")) 
(def-indiv-with-id bio-process "phlebotomies" "GO:0044369" :name "feeding on blood of other organism") 
(def-indiv-with-id bio-process "phagocytosis" "GO:0006909" :name "phagocytosis") 
(def-indiv-with-id bio-process "sequestering" "GO:0051235" :name "maintenance of location") 
(def-indiv-with-id bio-process "sensitization" "GO:0046960" :name "sensitization") 
(def-indiv-with-id bio-process "rme" "NCIT:C18107" :name "receptor mediated endocytosis") 
(def-indiv-with-id bio-process "retrotransposition" "NCIT:C19915" :name "retrotransposition") 
(def-indiv-with-id bio-process "resorption" "NCIT:C93204" :name "resorption") 
(def-indiv-with-id bio-process "systole" "NCIT:C62110" :name "systole") 
(def-indiv-with-id bio-process "spermatogenesis" "GO:0007283" :name "spermatogenesis") 
(def-indiv-with-id bio-process "tropism" "GO:0009606" :name "tropism") 
(def-indiv-with-id bio-process "transcytosis" "GO:0045056" :name "transcytosis") 
(def-indiv-with-id bio-process "tolerance" "NCIT:C17712" :name "immunologic tolerance") 
(def-indiv-with-id bio-process "xenophagy" "GO:0098792" :name "xenophagy") 
(def-indiv-with-id bio-process "F1-ATPase" "GO:0046961" :name "proton-transporting ATPase activity, rotational mechanism") 
(def-indiv-with-id bio-process "cytogamy" "GO:0000755" :name "cytogamy") 
(def-indiv-with-id bio-process "pigmentation" "GO:0043473" :name "pigmentation") 
(def-indiv-with-id bio-process "rhophilin" "GO:0017048" :name "Rho GTPase binding") 
(def-indiv-with-id bio-process "ageing" "GO:0007568" :name "aging") 
(def-indiv-with-id bio-process "locomotion" "GO:0040011" :name "locomotion") 
(def-indiv-with-id bio-process "degenerate" "NCIT:C61557" :name "degeneration") 
(def-indiv-with-id bio-process "zinc-binding" "GO:0008270" :name "zinc ion binding") 
(def-indiv-with-id bio-process "S-phase" "NCIT:C17395" :name "S-phase") 
(def-indiv-with-id bio-process "antigen-presentation" "NCIT:C17663" :name "antigen presentation") 
(def-indiv-with-id bio-process "auto-immune" "NCIT:C16313" :name "autoimmune process") 
(def-indiv-with-id bio-process "blebbing" "GO:0032060" :name "bleb assembly") 
(def-indiv-with-id bio-process "carbohydrate-binding" "GO:0030246" :name "carbohydrate binding") 
(def-indiv-with-id bio-process "conception" "NCIT:C16465" :name "conception") 
(def-indiv-with-id bio-process "contact-inhibition" "GO:0060242" :name "contact inhibition") 
(def-indiv-with-id bio-process "covalent" "NCIT:C41573" :name "covalent interaction") 
(def-indiv-with-id bio-process "exocytosis" "GO:0006887" :name "exocytosis") 
(def-indiv-with-id bio-process "gastrulation" "GO:0007369" :name "gastrulation") 
(def-indiv-with-id bio-process "gluconeogenesis" "GO:0006094" :name "gluconeogenesis") 
(def-indiv-with-id bio-process "mating" "GO:0007618" :name "mating") 
(def-indiv-with-id bio-process "mitosis" "NCIT:C16864" :name "mitosis" :plural ("mitosises" "mitoses")) 