(in-package :sparser)

(def-indiv-with-id cellular-location "cyclosome" "GO:0005680" :name "anaphase-promoting complex") 
(def-indiv-with-id cellular-location "peroxisome" "UP:SL-0204" :name "Peroxisome") 

(def-indiv-with-id cellular-location "PVC" "UP:SL-0223" :name "Prevacuolar compartment") 
(def-indiv-with-id cellular-location "kinetoplast" "UP:SL-0150" :name "Kinetoplast") 
(def-indiv-with-id cellular-location "chiasmata" "GO:0005712" :name "chiasma") 
(def-indiv-with-id cellular-location "rhabdomere" "GO:0016028" :name "rhabdomere") 
(def-indiv-with-id cellular-location "GCI" "GO:0097409" :name "glial cytoplasmic inclusion") 
(def-indiv-with-id cellular-location "HLBs" "GO:0035363" :name "histone locus body") 
(def-indiv-with-id cellular-location "IAM" "UP:SL-0004" :name "Acrosome inner membrane") 
(def-indiv-with-id cellular-location "Host" "UP:SL-0431" :name "Host") 
(def-indiv-with-id cellular-location "IPMs" "UP:SL-0146" :name "Interphotoreceptor matrix") 
(def-indiv-with-id cellular-location "IMC" "UP:SL-0362" :name "Inner membrane complex") 
(def-indiv-with-id cellular-location "MDV" "GO:0099073" :name "mitochondrion-derived vesicle") 
(def-indiv-with-id cellular-location "MCS" "GO:0044232" :name "organelle membrane contact site") 
(def-indiv-with-id cellular-location "PAA" "GO:1990295" :name "post-anaphase microtubule array") 
(def-indiv-with-id cellular-location "SCV" "GO:0020003" :name "symbiont-containing vacuole") 
(def-indiv-with-id cellular-location "autosome" "GO:0030849" :name "autosome") 
(def-indiv-with-id cellular-location "autolysosome" "GO:0044754" :name "autolysosome") 
(def-indiv-with-id cellular-location "acrosome" "UP:SL-0007" :name "Acrosome") 
(def-indiv-with-id cellular-location "chylomicron" "GO:0042627" :name "chylomicron") 
(def-indiv-with-id cellular-location "chromosome" "UP:SL-0468" :name "Chromosome") 
(def-indiv-with-id cellular-location "bouton" "GO:0043195" :name "terminal bouton") 
(def-indiv-with-id cellular-location "groove" "GO:0097610" :name "cell surface furrow") 
(def-synonym golgi-apparatus (:noun "golgi")) 
(def-indiv-with-id cellular-location "glycocalyx" "GO:0030112" :name "glycocalyx") 
(def-indiv-with-id cellular-location "Flagellum" "UP:SL-0117" :name "Flagellum" :plural ("Flagellums" "flagella")) 
(def-indiv-with-id cellular-location "halo" "GO:1990038" :name "Lewy body corona") 
(def-indiv-with-id cellular-location "melanosome" "UP:SL-0161" :name "Melanosome") 
(def-indiv-with-id cellular-location "macronucleus" "GO:0031039" :name "macronucleus") 
(def-indiv-with-id cellular-location "nucleoskeleton" "GO:0016363" :name "nuclear matrix") 
(def-indiv-with-id cellular-location "nucleoid" "UP:SL-0187" :name "Nucleoid") 
(def-indiv-with-id cellular-location "neurofilament" "GO:0005883" :name "neurofilament") 
(def-indiv-with-id cellular-location "myofibril" "UP:SL-0312" :name "Myofibril") 
(def-indiv-with-id cellular-location "myelin" "UP:SL-0176" :name "Myelin membrane") 
(def-indiv-with-id cellular-location "mucus" "GO:0070701" :name "mucus layer") 
(def-indiv-with-id cellular-location "mitochondrion" "UP:SL-0173" :name "Mitochondrion" :plural ("mitochondrions" "mitochondria") :synonyms ("GO:0005680")) 
(def-indiv-with-id cellular-location "midline" "GO:0031430" :name "M band") 
(def-indiv-with-id cellular-location "microvesicle" "GO:1990742" :name "microvesicle") 
(def-indiv-with-id cellular-location "microspike" "GO:0044393" :name "microspike") 
(def-indiv-with-id cellular-location "microfibril" "GO:0001527" :name "microfibril") 
(def-indiv-with-id cellular-location "ooplasm" "GO:1990917" :name "ooplasm") 
(def-indiv-with-id cellular-location "omegasome" "GO:1990462" :name "omegasome") 
(def-indiv-with-id cellular-location "paraspeckles" "GO:0042382" :name "paraspeckles") 
(def-indiv-with-id cellular-location "rER" "GO:0005791" :name "rough endoplasmic reticulum") 
(def-indiv-with-id cellular-location "presynapse" "GO:0098793" :name "presynapse") 
(def-indiv-with-id cellular-location "Rhoptry" "UP:SL-0233" :name "Rhoptry" :plural ("Rhoptries" "rhoptries")) 
(def-indiv-with-id cellular-location "telomere" "UP:SL-0276" :name "Telomere") 
(def-indiv-with-id cellular-location "synaptosome" "UP:SL-0261" :name "Synaptosome") 
(def-indiv-with-id cellular-location "sulci" "GO:0097612" :name "dinoflagellate sulcus") 
(def-indiv-with-id cellular-location "Stereocilium" "UP:SL-0302" :name "Stereocilium" :plural ("Stereociliums" "stereocilia")) 
(def-synonym dendritic-spine (:noun "spine")) 
(def-indiv-with-id cellular-location "spindle" "UP:SL-0251" :name "Spindle") 
(def-indiv-with-id cellular-location "spherosomes" "GO:0012511" :name "monolayer-surrounded lipid storage body") 
(def-indiv-with-id cellular-location "virion" "UP:SL-0274" :name "Virion") 
(def-synonym lamellipodium (:noun "veil")) 
(def-indiv-with-id cellular-location "IgC" "UP:SL-0186" :name "Nucleus speckle") 
(def-indiv-with-id cellular-location "Z-disc" "GO:0030018" :name "Z disc") 
(def-indiv-with-id cellular-location "Chloroplast" "UP:SL-0049" :name "Chloroplast" :plural ("Chloroplasts" "chloroplasts")) 
(def-indiv-with-id cellular-location "macropinosome" "GO:0044354" :name "macropinosome") 
(def-indiv-with-id cellular-location "nucleocapsid" "GO:0019013" :name "viral nucleocapsid") 
(def-indiv-with-id cellular-location "pSG" "GO:0034515" :name "proteasome storage granule") 
(def-indiv-with-id cellular-location "phagolysosome" "GO:0032010" :name "phagolysosome") 
(def-indiv-with-id cellular-location "septum" "GO:0030428" :name "cell septum") 
(def-indiv-with-id cellular-location "aminoacyl-tRNA" "CHEBI:2651" :name "alpha-aminoacyl-tRNA") 
(def-indiv-with-id cellular-location "axoneme" "GO:0005930" :name "axoneme") 
(def-indiv-with-id cellular-location "chromocenter" "GO:0010369" :name "chromocenter") 
(def-indiv-with-id cellular-location "microbody" "GO:0042579" :name "microbody") 
(def-indiv-with-id cellular-location "pilus" "GO:0009289" :name "pilus") 
(def-indiv-with-id cellular-location "tna" "CHEBI:48019" :name "threose nucleic acid") 
(def-indiv-with-id cellular-location "Bleb" "UP:SL-0472" :name "Bleb" :plural ("Blebs" "blebs")) 
(def-indiv-with-id cellular-location "budding" "UP:SL-0027" :name "Bud") 
(def-indiv-with-id cellular-location "Desmosome" "UP:SL-0092" :name "Desmosome" :plural ("Desmosomes" "desmosomes")) 
(def-indiv-with-id cellular-location "microvillus" "UP:SL-0293" :name "Microvillus") 
(def-indiv-with-id cellular-location "midbody" "UP:SL-0469" :name "Midbody") 
(def-indiv-with-id cellular-location "tight-junction" "UP:SL-0265" :name "Tight junction") 
(def-indiv-with-id cellular-location "CVC" "UP:SL-0073" :name "Contractile vacuole") 
(def-indiv-with-id cellular-location "Polynucleotide" "CHEBI:15986" :name "polynucleotide") 
(def-indiv-with-id cellular-location "Y-chromosome" "GO:0000806" :name "Y chromosome") 
(def-indiv-with-id cellular-location "C-fiber" "GO:0044299" :name "C-fiber" :plural ("C-fibers" "c-fibers")) 
(def-indiv-with-id cellular-location "chorion" "GO:0042600" :name "chorion") 
(def-indiv-with-id cellular-location "cis-Golgi" "UP:SL-0067" :name "cis-Golgi network") 
(def-indiv-with-id cellular-location "provirus" "GO:0019038" :name "provirus") 
(def-indiv-with-id cellular-location "satellites" "UP:SL-0485" :name "Centriolar satellite") 
(def-indiv-with-id cellular-location "tectum" "GO:0043676" :name "tectum") 
