;;; -*- Mode:LISP; Syntax:Common-Lisp; Package:SPARSER -*-
;;; copyright (c) 199-1995,2011-2013  David D. McDonald  -- all rights reserved
;;; extensions copyright (c) 2007-2010 BBNT Solutions LLC. All Rights Reserved
;;; $Id:$
;;;
;;;     File:  "countries"
;;;   Module:  "model;dossiers:"
;;;  version:  0.1 March 2013

;; 0.1 (10/12/92 v2.1) introducing new semantics
;;     (9/7 v2.3) revived the existing set of cases
;;     (10/29) added Hong Kong  (9/26/94) added Holland  (5/3/95) "United Kingdom"
;;     (7/16/07) "France". (5/22/10) "Hati". (12/19/11) "Mexico".
;; 0.1 (11/24/12) pulled in  Charlie G's dump for IL MDIS 
;;     work circa January 2010 from state.gov
;;     (3/4/13) Added Kurdistan and its adjective, /// but it's not really a country

(in-package :sparser)

(define-country "Afghanistan")
(define-country "Albania")
(define-country "Algeria")
(define-country "Andorra")
(define-country "Angola")
(define-country "Antigua and Barbuda")
(define-country "Argentina")
(define-country "Armenia")
(define-country "Australia" :adjective "Australian")
(define-country "Austria")
(define-country "Azerbaijan")
(define-country "The Bahamas")
(define-country "Bahrain")
(define-country "Bangladesh")
(define-country "Barbados")
(define-country "Belarus")
(define-country "Belgium")
(define-country "Belize")
(define-country "Benin")
(define-country "Bhutan")
(define-country "Bolivia")
(define-country "Bosnia and Herzegovina")
(define-country "Botswana")
(define-country "Brazil")
(define-country "Britain" :aliases '("United Kingdom") :adjective "British")
;; England  Scotland  Wales  Northern Irland
(define-country "Brunei")
(define-country "Bulgaria")
(define-country "Burkina Faso"  )
(define-country "Burma")
(define-country "Burundi")
(define-country "Cambodia")
(define-country "Cameroon")
(define-country "Canada" :adjective "Canadian")
(define-country "Cape Verde")
(define-country "Central African Republic")
(define-country "Chad")
(define-country "Chile")
(define-country "China")
(define-country "Colombia")
(define-country "Comoros")
(define-country "Costa Rica")
;define-country should be Côte d'Ivoire but having problems with the circumflex diacritic mark and apostrophe
(define-country "Ivory Coast")
(define-country "Croatia")
(define-country "Cuba")
(define-country "Cyprus")
(define-country "Czech Republic")
(define-country "Democratic Republic of the Congo")
(define-country "Denmark")
(define-country "Djibouti")
(define-country "Dominica")
(define-country "Dominican Republic")
(define-country "Ecuador")
(define-country "Egypt")
(define-country "El Salvador") 
(define-country "Equatorial Guinea")
(define-country "Eritrea")
(define-country "Estonia")
(define-country "Ethiopia")
(define-country "Federated States of Micronesia")
(define-country "Fiji")
(define-country "Finland")
(define-country "France"  :adjective "french")
(define-country "Gabon")
(define-country "The Gambia")
(define-country "Georgia")
(define-country "Germany" :adjective "German")
(define-country "Ghana")
(define-country "Greece")
(define-country "Grenada")
(define-country "Guatemala")
(define-country "Guinea")
(define-country "Guinea-Bissau")
(define-country "Guyana")
(define-country "Haiti" :adjective "Haitian")
(define-country "Holy See")
(define-country "Honduras")
(define-country "Hong Kong")
(define-country "Hungary")
(define-country "Iceland")
(define-country "India" :adjective "Indian")
(define-country "Indonesia")
(define-country "Iran")
(define-country "Iraq" :adjective "Iraqi")
(define-country "Ireland")
(define-country "Israel")
(define-country "Italy")
(define-country "Jamaica")
(define-country "Japan" :adjective "Japanese")
(define-country "Jordan")
(define-country "Kazakhstan")
(define-country "Kenya" :adjective "Kenyian")
(define-country "Kiribati")
(define-country "Kosovo")
(define-country "Kuwait")
(define-country "Kyrgyzstan")
(define-country "Laos")
(define-country "Latvia")
(define-country "Lebanon")
(define-country "Lesotho")
(define-country "Liberia")
(define-country "Libya")
(define-country "Liechtenstein")
(define-country "Lithuania")
(define-country "Luxembourg")
(define-country "Macedonia")
(define-country "Madagascar")
(define-country "Malawi")
(define-country "Malaysia")
(define-country "Maldives")
(define-country "Mali")
(define-country "Malta")
(define-country "Marshall Islands")
(define-country "Mauritania")
(define-country "Mauritius")
(define-country "Mexico" :adjective "Mexican")
(define-country "Moldova")
(define-country "Monaco")
(define-country "Mongolia")
(define-country "Montenegro")
(define-country "Morocco")
(define-country "Mozambique")
(define-country "Namibia")
(define-country "Nauru")
(define-country "Nepal")
(define-country "Netherlands":adjective "Dutch" :aliases '("Holland"))
(define-country "New Zealand")
(define-country "Nicaragua")
(define-country "Niger")
(define-country "Nigeria")
(define-country "North Korea")
(define-country "Norway")
(define-country "Oman")
(define-country "Pakistan")
(define-country "Palau")
(define-country "Panama")
(define-country "Papua New Guinea")
(define-country "Paraguay")
(define-country "Peru")
(define-country "Philippines")
(define-country "Poland")
(define-country "Portugal")
(define-country "Qatar")
(define-country "Republic of the Congo")
(define-country "Romania")
(define-country "Russia")
(define-country "Rwanda")
(define-country "Saint Kitts and Nevis")
(define-country "Saint Lucia")
(define-country "Saint Vincent and the Grenadines")
(define-country "Samoa")
(define-country "San Marino")
(define-country "Sao Tome and Principe")
(define-country "Saudi Arabia")
(define-country "Senegal")
(define-country "Serbia")
(define-country "Seychelles")
(define-country "Sierra Leone")
(define-country "Singapore")
(define-country "Slovakia")
(define-country "Slovenia")
(define-country "Solomon Islands")
(define-country "Somalia")
(define-country "South Africa")
(define-country "South Korea")
(define-country "Spain")
(define-country "Sri Lanka")
(define-country "Sudan")
(define-country "Suriname")
(define-country "Swaziland")
(define-country "Sweden" :adjective "Swedish")
(define-country "Switzerland")
(define-country "Syria")
(define-country "Taiwan")
(define-country "Tajikistan")
(define-country "Tanzania")
(define-country "Thailand")
(define-country "Timor-Leste")
(define-country "Togo")
(define-country "Tonga")
(define-country "Trinidad and Tobago")
(define-country "Tunisia")
(define-country "Turkey")
(define-country "Turkmenistan")
(define-country "Tuvalu")
(define-country "Uganda")
(define-country "Ukraine")
(define-country "United Arab Emirates")
(define-country "United States" :aliases '("US" "U.S." "U.S.A." "America" ))
(define-country "Uruguay")
(define-country "Uzbekistan")
(define-country "Vanuatu")
(define-country "Venezuela")
(define-country "Vietnam")
(define-country "Yemen")
(define-country "Zambia")
(define-country "Zimbabwe")


;;---  pseudoo countries, named regions
;; should have a different treatment, but this will do until we
;;   need to fuse with "northern Iraq"
(define-country "Kurdistan" :adjective "Kurdish") ;; Kurds
;; merology with other countries might be easy to do

(define-country "Gaza" :aliases '("Gaza Strip"))
(define-country "West Bank")
;;  Palestine
;;  Siberia

